% ============================================================================
% CONSTRAINT STORY: preparedness_persistence__husk_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-20
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_preparedness_persistence__husk_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:suppression_profile/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: preparedness_persistence__husk_reading
 *   human_readable: Memorial Performance of Disaster Preparedness
 *   domain: institutional/disaster_preparedness
 *
 * SUMMARY:
 *   This is the husk_reading of the preparedness_persistence kernel, which
 *   contends that scheduled drills and inspections in disaster preparedness
 *   have become memorial performance: the institutional form persists and
 *   expands while the operational competence it was meant to guarantee has
 *   atrophied. Sibling readings include competence_reading (live exercised
 *   knowledge) and hybrid_reading (stratified competence). The constraint is
 *   claimed as piton â atrophied function maintained by institutional
 *   inertia â but is often mistaken for a mountain (inevitable, natural) or
 *   rope (genuine coordination).
 *
 * KEY AGENTS:
 *   - emergency_management_agencies (institutional/arbitrage): Administer drills, capture legitimacy and budget, could reform but face prohibitive cost of exposing atrophy.
 *   - population_at_flood_risk (powerless/trapped): Bear disaster risk under false security generated by certified readiness metrics.
 *   - frontline_emergency_personnel (moderate/constrained): Experience the gap between script and reality; structurally excluded from official validation chains.
 *   - legislative_oversight (institutional/analytical): Validates activity metrics by default due to lack of independent operational assessment capacity.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(preparedness_persistence__husk_reading, 0.55).
domain_priors:suppression_score(preparedness_persistence__husk_reading, 0.3).
domain_priors:theater_ratio(preparedness_persistence__husk_reading, 0.88).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(preparedness_persistence__husk_reading, extractiveness, 0.55).
narrative_ontology:constraint_metric(preparedness_persistence__husk_reading, suppression_requirement, 0.3).
narrative_ontology:constraint_metric(preparedness_persistence__husk_reading, theater_ratio, 0.88).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(preparedness_persistence__husk_reading, accessibility_collapse, 0.65).
narrative_ontology:constraint_metric(preparedness_persistence__husk_reading, resistance, 0.15).

% --- Constraint claim ---
narrative_ontology:constraint_claim(preparedness_persistence__husk_reading, piton).
narrative_ontology:human_readable(preparedness_persistence__husk_reading, "Memorial Performance of Disaster Preparedness").
narrative_ontology:topic_domain(preparedness_persistence__husk_reading, "institutional/disaster_preparedness").

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(preparedness_persistence__husk_reading, '614bc452-c5d9-4bd6-bacc-b1e0a7427590').
narrative_ontology:cs_kernel_codification('614bc452-c5d9-4bd6-bacc-b1e0a7427590', formalized).
narrative_ontology:cs_authority_grounding('614bc452-c5d9-4bd6-bacc-b1e0a7427590', extraction).
narrative_ontology:cs_interpretation_layer_present('614bc452-c5d9-4bd6-bacc-b1e0a7427590').
narrative_ontology:cs_reading_relation('614bc452-c5d9-4bd6-bacc-b1e0a7427590', preparedness_persistence__competence_reading, forecloses).
narrative_ontology:cs_reading_relation('614bc452-c5d9-4bd6-bacc-b1e0a7427590', preparedness_persistence__hybrid_reading, coexists_with).
narrative_ontology:cs_axiom('614bc452-c5d9-4bd6-bacc-b1e0a7427590', foundational, drill_compliance_does_not_imply_readiness).
narrative_ontology:cs_axiom_status(drill_compliance_does_not_imply_readiness, holdable).
narrative_ontology:cs_axiom_grounding('614bc452-c5d9-4bd6-bacc-b1e0a7427590', drill_compliance_does_not_imply_readiness, empirically_contingent).
narrative_ontology:cs_axiom('614bc452-c5d9-4bd6-bacc-b1e0a7427590', foundational, institutional_legitimacy_requires_demonstrated_competence).
narrative_ontology:cs_axiom_status(institutional_legitimacy_requires_demonstrated_competence, holdable).
narrative_ontology:cs_axiom_grounding('614bc452-c5d9-4bd6-bacc-b1e0a7427590', institutional_legitimacy_requires_demonstrated_competence, conventional).
narrative_ontology:cs_reference_frame('614bc452-c5d9-4bd6-bacc-b1e0a7427590', certified_readiness_framework).
narrative_ontology:cs_drift_state('614bc452-c5d9-4bd6-bacc-b1e0a7427590', post_competence_atrophy_observation, gap(practice_drift, substantial, false)).
narrative_ontology:cs_created_at('614bc452-c5d9-4bd6-bacc-b1e0a7427590', '').
narrative_ontology:cs_kernel_id(preparedness_persistence__husk_reading, preparedness_persistence).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(preparedness_persistence__husk_reading, emergency_management_agencies).
narrative_ontology:constraint_victim(preparedness_persistence__husk_reading, population_at_flood_risk).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Administer mandated drills and inspections, file compliance reports, and receive budgetary allocations and political legitimacy for maintaining certified preparedness. The institutional mandate and funding persist regardless of whether operational competence matches the certified readiness level.
narrative_ontology:constraint_stakeholder(preparedness_persistence__husk_reading, emergency_management_agencies, agenda_setter,
    institutional, generational, arbitrage, national).
narrative_ontology:stakeholder_secondary_role(preparedness_persistence__husk_reading, emergency_management_agencies, beneficiary).

% Live in designated flood zones under the assumption that institutional preparedness programs confer reliable protection. Bear the mortality and property risk when actual event response fails to match the certified readiness level, with no practical ability to opt out of the institutional safety promise.
narrative_ontology:constraint_stakeholder(preparedness_persistence__husk_reading, population_at_flood_risk, payer,
    powerless, biographical, trapped, local).

% Conduct drills they know to be scripted and inspections that verify paperwork rather than capability. Their experiential knowledge of atrophied competence is structurally excluded from the official reporting chain that validates preparedness to oversight bodies.
narrative_ontology:constraint_stakeholder(preparedness_persistence__husk_reading, frontline_emergency_personnel, excluded,
    moderate, biographical, constrained, regional).

% Reviews aggregate drill completion rates and budget execution as proxies for readiness. Lacks independent operational assessment capacity, so validates the institutional narrative by default and treats activity metrics as outcome metrics.
narrative_ontology:constraint_stakeholder(preparedness_persistence__husk_reading, legislative_oversight, observer,
    institutional, generational, analytical, national).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(preparedness_persistence__husk_reading, emergency_management_agencies).
narrative_ontology:fixing_cost_class(preparedness_persistence__husk_reading, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Originally: to synchronize multi-agency response and verify operational capability before large-scale flooding. Currently: to generate auditable records of preparedness activity for institutional accountability cycles.
% TRANSFER_FUNCTION: Moves public funds and political legitimacy from taxpayers and at-risk communities to emergency management institutions, while transferring the mortality and property risk of inadequate response back to the at-risk population.
% ABSENT_VOICES: Frontline emergency personnel who experience the decoupling of drills from operational reality; at-risk residents who would demand competence-based metrics if included in preparedness validation rather than activity-based certification.
% DISAPPEARANCE_RATIONALE: If the memorial performance of drills and inspections ceased, emergency management agencies would lose their primary legitimacy and budget justification, forcing a sectoral rearrangement toward actual competence-based accountability or collapse of the institutional shell.
% FOUNDING_PROBLEM: Large-scale flooding events require practiced, coordinated multi-agency response to prevent chaos and reduce casualties; unpracticed agencies fail under stress.
% FOUNDING_PROBLEM_CORROBORATION: Independent disaster-sociology researchers and post-disaster after-action reviews from outside the agency funding stream document the decoupling of drill completion from response quality. Frontline personnel attest to the gap in anonymized surveys. State auditors occasionally note that checklist compliance does not predict operational outcomes.
narrative_ontology:disappearance_verdict(preparedness_persistence__husk_reading, world_rearranges).
narrative_ontology:founding_problem_status(preparedness_persistence__husk_reading, dead).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(preparedness_persistence__husk_reading, '8080348c4e16a265fafc924dcde83360dfd170fc',
    'becd0f87568a1ec0be97d1229ae702098dbd6568', '2026-07-20',
    'no_scope_rebuild_kimi', 'agent/example_platform_commission.json',
    'kimi-k2.6', 'max_tokens=32000,temperature=model_default,reasoning=model_default').
narrative_ontology:story_seed(preparedness_persistence__husk_reading, 'none', 1).
narrative_ontology:epsilon_provenance(preparedness_persistence__husk_reading, 0.55, 'kimi-k2.6', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(preparedness_persistence__husk_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(preparedness_persistence__husk_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(preparedness_persistence__husk_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Theater_ratio is very high (0.88 at interval end) because the constraint's visible activity (drills, inspections) no longer correlates with its nominal function (operational readiness). Extractiveness is moderate (0.55) because the at-risk population pays with misplaced trust and uncompensated risk exposure, but the extraction is diffuse and indirect rather than concentrated rent. Suppression is low (0.30) because the constraint persists by inertia and narrative normalization rather than active coercion. Resistance is minimal (0.15) because the performance is socially validated as 'doing something about preparedness.' The temporal series shows monotonic drift: rising theater_ratio and slowly accumulating extractiveness as the institutional form ages and competence decays.
 *
 * PERSPECTIVAL GAP:
 *   The agenda-setter seat (agencies) experiences the constraint as institutional routine and necessary compliance; the payer seat (at-risk population) experiences it as protective infrastructure; the excluded seat (frontline personnel) experiences it as theater. The engine computes this divergence from power and exit differentials: the agencies have arbitrage-grade exit (they could reform) but do not use it; the population is trapped; frontline personnel are constrained by career risk.
 *
 * DIRECTIONALITY LOGIC:
 *   Emergency_management_agencies are declared beneficiaries (low d) because legitimacy and budget flow to them. Population_at_flood_risk are declared victims (high d) because they bear the uncompensated risk that the institutional shell fails to mitigate. Frontline personnel are not declared victims in base_properties but their excluded/constrained position amplifies the structural suppression of competence information. No directionality override is needed: the derivation chain produces the correct asymmetry.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem â genuine coordination of multi-agency flood response â is dead (founding_problem_status: dead), but the constraint persists (disappearance_verdict: world_rearranges). This is the mandatrophy signature: the mandate has outlived its function. The high theater_ratio and moderate extractiveness with low suppression are consistent with piton classification â inertia, not active predation, sustains the arrangement. If a concentrated beneficiary were actively capturing rents, the classification would shift toward snare; the omega institutional_legitimacy_capture tests this boundary.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    kernel_reading_position,
    'This constraint is the husk_reading of the preparedness_persistence kernel. Sibling readings (competence_reading, hybrid_reading) assign different structural relationships between drill activity and operational readiness. Does the evidence support a pure husk reading over a hybrid stratification?',
    'Independent operational audits of emergency response units, comparing drill-script compliance against unscripted exercise outcomes across all components (engineering, logistics, evacuation, command).',
    'If hybrid is supported, the constraint reclassifies toward tangled_rope; if pure husk, piton classification holds.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_reading_position, conceptual, 'Structural ambiguity between pure husk and hybrid readings of the same kernel.').

omega_variable(
    competence_atrophy_rate,
    'Is the gap between memorial drill performance and operational competence widening, and at what rate?',
    'Longitudinal study pairing drill metrics with post-disaster after-action reviews and unannounced operational stress tests.',
    'A widening gap confirms rising extractiveness and supports the husk reading; a stable gap suggests the constraint was always theatrical (different origin narrative).',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(competence_atrophy_rate, empirical, 'Rate of divergence between performative and operational readiness.').

omega_variable(
    institutional_legitimacy_capture,
    'Does the legitimacy accrued by emergency management agencies constitute concentrated extraction sufficient to reclassify this constraint as snare rather than piton?',
    'Budget-flow analysis: determine whether the agencies'' budget and mandate scale with demonstrated competence or with drill/inspection throughput.',
    'If budget tracks throughput regardless of competence, legitimacy is a captured rent stream (snare); if budget is insensitive to drill volume and the agencies merely inherit inertia, piton classification holds.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(institutional_legitimacy_capture, empirical, 'Whether beneficiary concentration is sufficient to override piton inertia.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(preparedness_persistence__husk_reading, 0, 40).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(preparedness_husk_tr_t0, preparedness_persistence__husk_reading, theater_ratio, 0, 0.2).
narrative_ontology:measurement(preparedness_husk_tr_t8, preparedness_persistence__husk_reading, theater_ratio, 8, 0.32).
narrative_ontology:measurement(preparedness_husk_tr_t16, preparedness_persistence__husk_reading, theater_ratio, 16, 0.45).
narrative_ontology:measurement(preparedness_husk_tr_t24, preparedness_persistence__husk_reading, theater_ratio, 24, 0.6).
narrative_ontology:measurement(preparedness_husk_tr_t32, preparedness_persistence__husk_reading, theater_ratio, 32, 0.75).
narrative_ontology:measurement(preparedness_husk_tr_t40, preparedness_persistence__husk_reading, theater_ratio, 40, 0.88).

% Extraction over time
narrative_ontology:measurement(preparedness_husk_be_t0, preparedness_persistence__husk_reading, base_extractiveness, 0, 0.3).
narrative_ontology:measurement(preparedness_husk_be_t8, preparedness_persistence__husk_reading, base_extractiveness, 8, 0.35).
narrative_ontology:measurement(preparedness_husk_be_t16, preparedness_persistence__husk_reading, base_extractiveness, 16, 0.4).
narrative_ontology:measurement(preparedness_husk_be_t24, preparedness_persistence__husk_reading, base_extractiveness, 24, 0.47).
narrative_ontology:measurement(preparedness_husk_be_t32, preparedness_persistence__husk_reading, base_extractiveness, 32, 0.52).
narrative_ontology:measurement(preparedness_husk_be_t40, preparedness_persistence__husk_reading, base_extractiveness, 40, 0.55).

% Suppression authored static: scalar-only by design, no temporal series
narrative_ontology:suppression_profile(preparedness_persistence__husk_reading, static).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:affects_constraint(preparedness_persistence__husk_reading, preparedness_persistence__competence_reading).
narrative_ontology:affects_constraint(preparedness_persistence__husk_reading, preparedness_persistence__hybrid_reading).

% DUAL FORMULATION NOTE:
% The preparedness_persistence kernel decomposes into three structurally distinct constraints. Competence_reading would classify as rope (low Îµ, genuine coordination). Husk_reading classifies as piton (moderate Îµ, inertial performance). Hybrid_reading would classify as tangled_rope or mixed (stratified competence, asymmetric extraction in ritualized components). They are linked as a constraint family.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
