% ============================================================================
% CONSTRAINT STORY: marriage_authority__gender_rights_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_marriage_authority__gender_rights_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: marriage_authority__gender_rights_reading
 *   human_readable: Judicial Expansion of Constitutional Equality into Personal Law (Gender Rights Reading)
 *   domain: legal/constitutional/family law
 *
 * SUMMARY:
 *   This constraint story models marriage authority as contested through the
 *   lens of intra-community gender equality, specifically the standing
 *   arrangement whereby constitutional courts expand equality guarantees to
 *   invalidate discriminatory personal-law practices such as triple talaq,
 *   inequitable maintenance, and property exclusion. Under the
 *   gender_rights_reading of the marriage_authority kernel, this judicial
 *   expansion pathway is the central mechanism for reform. The story treats
 *   the arrangement as a high-extraction constraint: it presents itself as
 *   gender emancipation but structurally extracts from the very women it
 *   claims to liberate by exposing them to communal backlash, politicizing
 *   their position, and concentrating institutional gains in the advocacy and
 *   judicial complex. The reading cross-cuts the communal/secular divide by
 *   attacking patriarchal practices within communities rather than attacking
 *   community identity per se. Sibling readings include
 *   communal_autonomy_reading (religious tradition as ground),
 *   federalist_millet_reading (pluralism as anti-tyranny),
 *   judicial_harmonization_reading (neutral case-by-case review), and
 *   secularist_reading (legislative UCC as terminus).
 *
 * KEY AGENTS:
 *   - women_rights_advocates: Primary beneficiary (organized/mobile) â collect institutional power, funding, and legal victories from the litigation pathway.
 *   - women_within_patriarchal_personal_law: Primary target (powerless/identity_locked) â bear the costs of discriminatory practices and of the backlash generated by judicial intervention.
 *   - constitutional_judiciary: Agenda-setter (institutional/analytical) â expands equality jurisprudence into personal law, accumulating authority.
 *   - patriarchal_community_gatekeepers: Excluded from reform design (organized/constrained) â would reject constitutional override but are framed as regressive obstacles rather than parties to the solution.
 *   - secular_legislature: Observer (institutional/analytical) â defers to judicial and community politics, ceding the reform agenda.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(marriage_authority__gender_rights_reading, 0.82).
domain_priors:suppression_score(marriage_authority__gender_rights_reading, 0.78).
domain_priors:theater_ratio(marriage_authority__gender_rights_reading, 0.52).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(marriage_authority__gender_rights_reading, extractiveness, 0.82).
narrative_ontology:constraint_metric(marriage_authority__gender_rights_reading, suppression_requirement, 0.78).
narrative_ontology:constraint_metric(marriage_authority__gender_rights_reading, theater_ratio, 0.52).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(marriage_authority__gender_rights_reading, accessibility_collapse, 0.65).
narrative_ontology:constraint_metric(marriage_authority__gender_rights_reading, resistance, 0.72).

% --- Constraint claim ---
narrative_ontology:constraint_claim(marriage_authority__gender_rights_reading, snare).
narrative_ontology:human_readable(marriage_authority__gender_rights_reading, "Judicial Expansion of Constitutional Equality into Personal Law (Gender Rights Reading)").
narrative_ontology:topic_domain(marriage_authority__gender_rights_reading, "legal/constitutional/family law").

domain_priors:requires_active_enforcement(marriage_authority__gender_rights_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(marriage_authority__gender_rights_reading, '22720f89-7a13-4bfd-95f6-9e494cece5f0').
narrative_ontology:cs_kernel_codification('22720f89-7a13-4bfd-95f6-9e494cece5f0', formalized).
narrative_ontology:cs_authority_grounding('22720f89-7a13-4bfd-95f6-9e494cece5f0', lineage).
narrative_ontology:cs_interpretation_layer_present('22720f89-7a13-4bfd-95f6-9e494cece5f0').
narrative_ontology:cs_reading_relation('22720f89-7a13-4bfd-95f6-9e494cece5f0', marriage_authority__communal_autonomy_reading, forecloses).
narrative_ontology:cs_reading_relation('22720f89-7a13-4bfd-95f6-9e494cece5f0', marriage_authority__federalist_millet_reading, influences).
narrative_ontology:cs_reading_relation('22720f89-7a13-4bfd-95f6-9e494cece5f0', marriage_authority__judicial_harmonization_reading, coexists_with).
narrative_ontology:cs_reading_relation('22720f89-7a13-4bfd-95f6-9e494cece5f0', marriage_authority__secularist_reading, coexists_with).
narrative_ontology:cs_axiom('22720f89-7a13-4bfd-95f6-9e494cece5f0', foundational, constitutional_equality_overrides_communal_marriage_norms).
narrative_ontology:cs_axiom_status(constitutional_equality_overrides_communal_marriage_norms, holdable).
narrative_ontology:cs_axiom_grounding('22720f89-7a13-4bfd-95f6-9e494cece5f0', constitutional_equality_overrides_communal_marriage_norms, conventional).
narrative_ontology:cs_axiom('22720f89-7a13-4bfd-95f6-9e494cece5f0', foundational, patriarchal_personal_law_constitutes_structural_subordination).
narrative_ontology:cs_axiom_status(patriarchal_personal_law_constitutes_structural_subordination, holdable).
narrative_ontology:cs_axiom_grounding('22720f89-7a13-4bfd-95f6-9e494cece5f0', patriarchal_personal_law_constitutes_structural_subordination, empirically_contingent).
narrative_ontology:cs_reference_frame('22720f89-7a13-4bfd-95f6-9e494cece5f0', constitutional_equality_marriage_governance).
narrative_ontology:cs_drift_state('22720f89-7a13-4bfd-95f6-9e494cece5f0', contemporary, gap(practice_drift, substantial, false)).
narrative_ontology:cs_created_at('22720f89-7a13-4bfd-95f6-9e494cece5f0', '').
narrative_ontology:cs_kernel_id(marriage_authority__gender_rights_reading, marriage_authority).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(marriage_authority__gender_rights_reading, women_rights_advocates).
narrative_ontology:constraint_victim(marriage_authority__gender_rights_reading, women_within_patriarchal_personal_law).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Litigate constitutional challenges to personal law, produce research and advocacy campaigns, and receive institutional funding and public visibility when courts deliver favorable judgments. Their professional and organizational growth is tied to the existence of a contested personal-law landscape that can be progressively corrected through constitutional litigation.
narrative_ontology:constraint_stakeholder(marriage_authority__gender_rights_reading, women_rights_advocates, beneficiary,
    organized, generational, mobile, national).

% Live under religious personal law regimes governing marriage, divorce, maintenance, and inheritance. They are the named beneficiaries of constitutional litigation but often experience community backlash, social ostracism, or legal uncertainty when courts invalidate practices like triple talaq. Most never access the judicial pathway; those who do risk losing family and community support without gaining viable state-based alternatives.
narrative_ontology:constraint_stakeholder(marriage_authority__gender_rights_reading, women_within_patriarchal_personal_law, payer,
    powerless, biographical, identity_locked, local).

% Expands the scope of constitutional equality jurisprudence into personal law through public-interest litigation and constitutional review. Strikes down specific gender-discriminatory practices while avoiding systemic overhaul. Accumulates authority vis-Ã -vis legislature and community institutions, but its orders require executive and social enforcement that is unevenly delivered.
narrative_ontology:constraint_stakeholder(marriage_authority__gender_rights_reading, constitutional_judiciary, agenda_setter,
    institutional, civilizational, analytical, national).

% Religious and community authorities who administer personal law at the local level. They are not consulted in constitutional litigation design and their authority is progressively undermined by judicial override. They would argue that marriage norms are constitutive of community identity and that external constitutional imposition destroys social cohesion, but this voice is treated as illegitimate in the rights-based framing.
narrative_ontology:constraint_stakeholder(marriage_authority__gender_rights_reading, patriarchal_community_gatekeepers, excluded,
    organized, generational, constrained, local).

% Constitutionally empowered to enact a Uniform Civil Code but has chronically deferred to judicial and community politics. Observes the judicialization of personal law reform without mustering the political will to codify gender equality legislatively, thereby ceding the field to courts and rights advocates.
narrative_ontology:constraint_stakeholder(marriage_authority__gender_rights_reading, secular_legislature, observer,
    institutional, biographical, analytical, national).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Provides a judicial forum for resolving the conflict between constitutional equality guarantees and religious personal law norms without requiring legislative consensus on a uniform civil code.
% TRANSFER_FUNCTION: Moves legal authority over marriage norms from community institutions to constitutional courts; moves symbolic and material resources from women within communities to the advocacy ecosystem that litigates on their behalf.
% ABSENT_VOICES: Women within patriarchal personal law who would prefer legislative or communal rather than judicial resolution; community adjudicators and religious scholars who administer family dispute mechanisms; legislators who would enact comprehensive family law reform but are politically constrained. These voices are excluded because the gender rights reading frames the problem as constitutional litigation and treats communal preferences as false consciousness or illegitimate patriarchy.
% DISAPPEARANCE_RATIONALE: If the judicial expansion pathway vanished, personal law would revert to unfiltered community authority; women would lose the constitutional litigation lever but might also experience reduced community polarization; rights advocates would lose their primary institutional venue and funding narrative; the judiciary would cede authority over marriage back to communities and the legislature.
% FOUNDING_PROBLEM: Gender-discriminatory practices within personal law systems (triple talaq, unequal maintenance, property exclusion) that legislative politics could not address due to communal political sensitivities.
% FOUNDING_PROBLEM_CORROBORATION: Women within patriarchal personal law attest the problem is live through litigation petitions; women rights advocates attest it is live. Community authorities contest that the problem is externally imposed. Independent academic legal scholars and human rights monitors corroborate that discriminatory practices persist but debate whether judicial expansion is the appropriate remedy.
narrative_ontology:disappearance_verdict(marriage_authority__gender_rights_reading, world_rearranges).
narrative_ontology:founding_problem_status(marriage_authority__gender_rights_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(marriage_authority__gender_rights_reading, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_kimi2', 'agent/example_platform_commission.json',
    'kimi-k2.6', 'max_tokens=32000,temperature=model_default,reasoning=model_default').
narrative_ontology:story_seed(marriage_authority__gender_rights_reading, 'none', 1).
narrative_ontology:epsilon_provenance(marriage_authority__gender_rights_reading, 0.82, 'kimi-k2.6', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(marriage_authority__gender_rights_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(marriage_authority__gender_rights_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(marriage_authority__gender_rights_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is high (0.82) because the judicial pathway concentrates institutional authority and resources in the advocacy-judicial complex while delivering piecemeal, non-systemic relief. Suppression is high (0.78) because the constraint's persistence depends on actively suppressing communal alternatives and legislative pathways, crowding out other reform vocabularies. Theater ratio crosses 0.5 (0.52) because an increasing share of enforcement activity celebrates constitutional victories that do not alter the material conditions of most target women. Accessibility collapse (0.65) reflects that legislative UCC and internal community reform have been pushed to the margins by the judicialization of the issue. Resistance (0.72) is substantial due to sustained communal and political pushback against judicial encroachment on personal law.
 *
 * PERSPECTIVAL GAP:
 *   From the judicial seat, the constraint is a necessary constitutional correction of democratic failure â the court steps in where legislatures fear to tread. From the community women's seat, the same constraint is an unpredictable external force that invalidates their marriage norms but does not substitute viable social infrastructure, leaving them ostracized. From the advocate seat, it is a measurable progress mechanism. These divergences are structurally encoded in the power and exit asymmetries.
 *
 * DIRECTIONALITY LOGIC:
 *   Women rights advocates are structural beneficiaries: the litigation economy and donor attention flow to organizations that can demonstrate constitutional victories. Their exit is mobile â they can shift issue areas. The judiciary is a secondary beneficiary in the directionality derivation: it gains authority relative to both legislature and community institutions. Women within patriarchal personal law are full targets: they cannot exit their community identity without severe social cost, and the judicial remedy often leaves them more exposed than before. The engine will derive near-zero d for the advocates and near-unity d for the community women, amplifying effective extraction for the latter and dampening it for the former.
 *
 * MANDATROPHY ANALYSIS:
 *   The risk here is misclassifying the constraint as a Scaffold (transitional support toward equality) or Tangled Rope (coordination with side-effects). It is not a Scaffold because it carries no sunset clause and no plausible terminus â the litigation is perpetual. It is not a Tangled Rope because the coordination story (gender equality) does not genuinely coordinate the underlying social practice; the parties to the marriage system (communities and women) are not coordinated by the judicial order, they are polarized by it. The extraction is primary and the coordination is cover, which is the Snare signature. Theater ratio above 0.5 at interval end confirms that an increasing share of activity is performative â celebrating constitutional victories that do not alter the material conditions of most target women.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    kernel_reading_boundary,
    'This constraint is the gender_rights_reading of the marriage_authority kernel. How does its structural classification change if the judicial harmonization reading (case-by-case neutral review) or the secularist reading (legislative UCC) were adopted as the operative frame?',
    'Comparative analysis of the same legal events under each reading''s axioms to identify which structural elements (beneficiary/victim sets, extraction paths) are reading-dependent versus kernel-invariant.',
    'If the extraction profile is reading-dependent, the kernel is irreducibly contested; if invariant, one reading is misclassified.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_reading_boundary, conceptual, 'Structural boundary between gender rights and sibling readings of marriage authority').

omega_variable(
    judicial_reform_material_impact,
    'Does piecemeal judicial invalidation of specific personal-law practices (triple talaq, maintenance) improve the material condition and social standing of women within those communities, or does it primarily empower the litigation ecosystem while leaving most women exposed to backlash?',
    'Longitudinal socioeconomic study of women in communities before and after major constitutional interventions, measuring not just legal status but family support networks, economic security, and intra-community bargaining power.',
    'If material conditions stagnate or worsen while advocacy organizations grow, the classification as snare is reinforced; if conditions improve broadly, reclassification to tangled_rope or scaffold may be warranted.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(judicial_reform_material_impact, empirical, 'Whether judicial gender rights reform delivers material benefits or performs extraction').

omega_variable(
    community_voice_exclusion,
    'Are women_within_patriarchal_personal_law who oppose constitutional litigation (preferring communal or legislative resolution) structurally excluded from the gender rights reading, and does this exclusion inflate the coordination story?',
    'Ethnographic study of women''s preference heterogeneity within target communities; analysis of who speaks in PIL proceedings.',
    'If significant internal dissent is suppressed, the constraint''s suppression metric is higher than structurally visible and the snare classification strengthens.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(community_voice_exclusion, conceptual, 'Internal dissent suppression within the victim class').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(marriage_authority__gender_rights_reading, 0, 40).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(magr_tr_t0, marriage_authority__gender_rights_reading, theater_ratio, 0, 0.18).
narrative_ontology:measurement(magr_tr_t8, marriage_authority__gender_rights_reading, theater_ratio, 8, 0.22).
narrative_ontology:measurement(magr_tr_t16, marriage_authority__gender_rights_reading, theater_ratio, 16, 0.28).
narrative_ontology:measurement(magr_tr_t24, marriage_authority__gender_rights_reading, theater_ratio, 24, 0.35).
narrative_ontology:measurement(magr_tr_t32, marriage_authority__gender_rights_reading, theater_ratio, 32, 0.45).
narrative_ontology:measurement(magr_tr_t40, marriage_authority__gender_rights_reading, theater_ratio, 40, 0.52).

% Extraction over time
narrative_ontology:measurement(magr_be_t0, marriage_authority__gender_rights_reading, base_extractiveness, 0, 0.42).
narrative_ontology:measurement(magr_be_t8, marriage_authority__gender_rights_reading, base_extractiveness, 8, 0.51).
narrative_ontology:measurement(magr_be_t16, marriage_authority__gender_rights_reading, base_extractiveness, 16, 0.58).
narrative_ontology:measurement(magr_be_t24, marriage_authority__gender_rights_reading, base_extractiveness, 24, 0.65).
narrative_ontology:measurement(magr_be_t32, marriage_authority__gender_rights_reading, base_extractiveness, 32, 0.75).
narrative_ontology:measurement(magr_be_t40, marriage_authority__gender_rights_reading, base_extractiveness, 40, 0.82).

% Suppression requirement over time
narrative_ontology:measurement(magr_su_t0, marriage_authority__gender_rights_reading, suppression_requirement, 0, 0.45).
narrative_ontology:measurement(magr_su_t8, marriage_authority__gender_rights_reading, suppression_requirement, 8, 0.52).
narrative_ontology:measurement(magr_su_t16, marriage_authority__gender_rights_reading, suppression_requirement, 16, 0.58).
narrative_ontology:measurement(magr_su_t24, marriage_authority__gender_rights_reading, suppression_requirement, 24, 0.68).
narrative_ontology:measurement(magr_su_t32, marriage_authority__gender_rights_reading, suppression_requirement, 32, 0.78).
narrative_ontology:measurement(magr_su_t40, marriage_authority__gender_rights_reading, suppression_requirement, 40, 0.85).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:affects_constraint(marriage_authority__gender_rights_reading, marriage_authority__judicial_harmonization_reading).
narrative_ontology:affects_constraint(marriage_authority__gender_rights_reading, marriage_authority__secularist_reading).

% DUAL FORMULATION NOTE:
% The marriage_authority kernel decomposes into multiple constraints because the label conflates structurally distinct claims: communal autonomy, federalist pluralism, gender rights, judicial harmonization, and secular UCC. Each reading produces a different epsilon, beneficiary/victim structure, and classification. This story (gender_rights_reading) is linked to its siblings as part of the constraint family.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
