% ============================================================================
% CONSTRAINT STORY: ip_category_emergence__synchronic_diachronic_seam
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_ip_category_emergence__synchronic_diachronic_seam, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:suppression_profile/2,
    narrative_ontology:measurement_basis/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: ip_category_emergence__synchronic_diachronic_seam
 *   human_readable: Synchronic/Diachronic Seam Test: Category Emergence vs. Occupancy Change (M4/M5 Collapse)
 *   domain: legal_philosophy/intellectual_property/historical_jurisprudence
 *
 * SUMMARY:
 *   This story instantiates the synchronic/diachronic seam reading within the
 *   ip_category_emergence kernel. Rather than asserting that 1710 marks
 *   category emergence (the thinkability_reading) or occupancy change (the
 *   first_holding_reading), this reading asks whether the two claims are
 *   formally independent variables that happened to co-occur in the English
 *   case, or whether the apparent 1710 rupture is a temporal-framing artifact
 *   generated by collapsing two logically separable questions into one
 *   narrative event. The constraint under contest here is the doctrinal
 *   practice of running M4 (thinkability) and M5 (first-holding) as a single
 *   collapse test and treating their joint outcome as evidence about the
 *   authenticity of the kernel's structure. The ε authored below is for THIS
 *   test's own operation as a doctrinal practice — how much extraction the
 *   seam-collapsing convention itself performs on parties who would benefit
 *   from the independence finding — not for either sibling reading's endorsed
 *   historical claim.
 *
 * KEY AGENTS:
 *   - modern_ip_maximalist_scholarship: agenda_setter over which doctrinal framing dominates teaching and citation
 *   - publisher_guild_successors: beneficiary of a collapsed, singular-rupture narrative
 *   - public_domain_theorists: payer when the seam is collapsed rather than tested
 *   - pre_1710_customary_printers: erased regardless of collapse or independence, but more thoroughly erased under collapse
 *   - analytical_jurisprudence_researchers: observer seat running the formal test itself
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(ip_category_emergence__synchronic_diachronic_seam, 0.52).
domain_priors:suppression_score(ip_category_emergence__synchronic_diachronic_seam, 0.4).
domain_priors:theater_ratio(ip_category_emergence__synchronic_diachronic_seam, 0.45).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(ip_category_emergence__synchronic_diachronic_seam, extractiveness, 0.52).
narrative_ontology:constraint_metric(ip_category_emergence__synchronic_diachronic_seam, suppression_requirement, 0.4).
narrative_ontology:constraint_metric(ip_category_emergence__synchronic_diachronic_seam, theater_ratio, 0.45).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(ip_category_emergence__synchronic_diachronic_seam, accessibility_collapse, 0.5).
narrative_ontology:constraint_metric(ip_category_emergence__synchronic_diachronic_seam, resistance, 0.55).

% --- Constraint claim ---
narrative_ontology:constraint_claim(ip_category_emergence__synchronic_diachronic_seam, tangled_rope).
narrative_ontology:human_readable(ip_category_emergence__synchronic_diachronic_seam, "Synchronic/Diachronic Seam Test: Category Emergence vs. Occupancy Change (M4/M5 Collapse)").
narrative_ontology:topic_domain(ip_category_emergence__synchronic_diachronic_seam, "legal_philosophy/intellectual_property/historical_jurisprudence").

domain_priors:requires_active_enforcement(ip_category_emergence__synchronic_diachronic_seam).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(ip_category_emergence__synchronic_diachronic_seam, '446751dc-74b2-48f0-9f1f-628c8cfc11d9').
narrative_ontology:cs_kernel_codification('446751dc-74b2-48f0-9f1f-628c8cfc11d9', distributed).
narrative_ontology:cs_authority_grounding('446751dc-74b2-48f0-9f1f-628c8cfc11d9', practice).
narrative_ontology:cs_interpretation_layer_present('446751dc-74b2-48f0-9f1f-628c8cfc11d9').
narrative_ontology:cs_reading_relation('446751dc-74b2-48f0-9f1f-628c8cfc11d9', ip_category_emergence__thinkability_reading, influences).
narrative_ontology:cs_reading_relation('446751dc-74b2-48f0-9f1f-628c8cfc11d9', ip_category_emergence__first_holding_reading, influences).
narrative_ontology:cs_axiom('446751dc-74b2-48f0-9f1f-628c8cfc11d9', foundational, category_and_occupancy_are_formally_separable).
narrative_ontology:cs_axiom_status(category_and_occupancy_are_formally_separable, holdable).
narrative_ontology:cs_axiom_grounding('446751dc-74b2-48f0-9f1f-628c8cfc11d9', category_and_occupancy_are_formally_separable, empirically_contingent).
narrative_ontology:cs_axiom('446751dc-74b2-48f0-9f1f-628c8cfc11d9', foundational, temporal_co_occurrence_does_not_entail_joint_determination).
narrative_ontology:cs_axiom_status(temporal_co_occurrence_does_not_entail_joint_determination, holdable).
narrative_ontology:cs_axiom_grounding('446751dc-74b2-48f0-9f1f-628c8cfc11d9', temporal_co_occurrence_does_not_entail_joint_determination, empirically_contingent).
narrative_ontology:cs_reference_frame('446751dc-74b2-48f0-9f1f-628c8cfc11d9', unified_1710_rupture_convention).
narrative_ontology:cs_drift_state('446751dc-74b2-48f0-9f1f-628c8cfc11d9', contemporary_comparative_historiography, gap(axiom_overriding, substantial, false)).
narrative_ontology:cs_created_at('446751dc-74b2-48f0-9f1f-628c8cfc11d9', '').
narrative_ontology:cs_kernel_id(ip_category_emergence__synchronic_diachronic_seam, ip_category_emergence).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(ip_category_emergence__synchronic_diachronic_seam, publisher_guild_successors).
narrative_ontology:constraint_beneficiary(ip_category_emergence__synchronic_diachronic_seam, doctrinal_historians_of_authorship).
narrative_ontology:constraint_beneficiary(ip_category_emergence__synchronic_diachronic_seam, modern_ip_maximalist_scholarship).
narrative_ontology:constraint_victim(ip_category_emergence__synchronic_diachronic_seam, public_domain_theorists).
narrative_ontology:constraint_victim(ip_category_emergence__synchronic_diachronic_seam, pre_1710_customary_printers).
narrative_ontology:constraint_victim(ip_category_emergence__synchronic_diachronic_seam, comparative_legal_historians_outside_anglophone_tradition).
narrative_ontology:constraint_vindicates(ip_category_emergence__synchronic_diachronic_seam, statute_of_anne_as_singular_rupture).
narrative_ontology:constraint_vindicates(ip_category_emergence__synchronic_diachronic_seam, category_and_occupancy_are_jointly_determined).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Administers the dominant doctrinal narrative in copyright treatises and casebooks, deciding whether 1710 is taught as the moment 'ownable expression became thinkable' (category emergence) or 'the author became the legitimate first holder' (occupancy change). Collapsing the seam — treating the two as always co-occurring — simplifies the teaching narrative and forecloses harder questions about whether either claim is doing independent work. Has strong exit: can shift terminology across editions without ever being tested against the historical record.
narrative_ontology:constraint_stakeholder(ip_category_emergence__synchronic_diachronic_seam, modern_ip_maximalist_scholarship, agenda_setter,
    institutional, generational, arbitrage, global).

% Corporate and institutional successors to the Stationers' Company interest structure benefit from a doctrinal story in which 1710 marks a clean, singular rupture rather than a contingent overlap of two separable processes. If the seam collapses into 'always co-occurring,' the resulting narrative of inevitability supports strong, naturalized property claims over expression; if the seam holds as independent variation, the naturalness of that inevitability narrative weakens.
narrative_ontology:constraint_stakeholder(ip_category_emergence__synchronic_diachronic_seam, publisher_guild_successors, beneficiary,
    organized, civilizational, mobile, national).

% Academic authorship-history specialists whose scholarly capital depends on 1710 functioning as a legible singular event. A finding of formal independence between thinkability and first-holding would fragment their object of study into two less citable, less teachable sub-events, diluting the canonical status of their existing body of work.
narrative_ontology:constraint_stakeholder(ip_category_emergence__synchronic_diachronic_seam, doctrinal_historians_of_authorship, beneficiary,
    institutional, generational, arbitrage, continental).
narrative_ontology:stakeholder_secondary_role(ip_category_emergence__synchronic_diachronic_seam, doctrinal_historians_of_authorship, observer).

% Scholars and advocates arguing for narrower, historically contingent readings of authorial property bear the cost of the collapsed-seam narrative: if courts and legislatures treat category emergence and occupancy change as one indivisible event, arguments for narrowing either dimension independently (e.g., recognizing new categories without granting maximal exclusive occupancy, or vice versa) are read as incoherent rather than as live doctrinal options. Their exit is constrained to law review argument and amicus practice; they cannot unilaterally re-open the historical question in binding forums.
narrative_ontology:constraint_stakeholder(ip_category_emergence__synchronic_diachronic_seam, public_domain_theorists, payer,
    moderate, generational, constrained, national).

% The historical guild-based printers whose customary, non-authorial claims to reproduction rights are retroactively erased by any reading (collapsed or independent) that treats 1710 as installing author-as-holder as the only legitimate claimant type. They cannot speak for themselves in the present controversy; their historical practice is simply overwritten by whichever doctrinal frame wins.
narrative_ontology:constraint_stakeholder(ip_category_emergence__synchronic_diachronic_seam, pre_1710_customary_printers, payer,
    powerless, civilizational, trapped, national).

% Historians working on continental droit d'auteur, Ottoman print privilege systems, and other non-English traditions would object that the entire M4/M5 seam question is parochially anglophone — that in other traditions category emergence and occupancy change visibly diverge in time and by centuries. They are rarely cited in the anglophone doctrinal debate that decides whether the seam is real or artifactual.
narrative_ontology:constraint_stakeholder(ip_category_emergence__synchronic_diachronic_seam, comparative_legal_historians_outside_anglophone_tradition, excluded,
    moderate, generational, constrained, global).

% Run the formal collapse test itself: attempting to hold thinkability (was ownable expression a coherent legal category before 1710?) and first-holding (did the author enter the legitimate claimant set at 1710, replacing prior guild-based claimants?) as separately falsifiable claims, to determine whether the 1710 rupture is one event or a temporal-framing artifact conflating two.
narrative_ontology:constraint_stakeholder(ip_category_emergence__synchronic_diachronic_seam, analytical_jurisprudence_researchers, observer,
    analytical, civilizational, analytical, universal).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(ip_category_emergence__synchronic_diachronic_seam, publisher_guild_successors).
narrative_ontology:fixing_cost_class(ip_category_emergence__synchronic_diachronic_seam, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: The seam test itself coordinates a genuine analytical problem: it lets historians and jurists distinguish between two logically separable claims about the Statute of Anne — that a new ownable-expression category became conceivable, and that a new class of claimant (the author, displacing the guild) actually took occupancy of existing or new rights — instead of treating '1710' as an indivisible datum that answers both questions at once.
% TRANSFER_FUNCTION: The framing choice moves interpretive authority: if the seam collapses (M4=M5, thinkability entails first-holding and vice versa), authority over 'what changed in 1710' consolidates in whichever narrative already dominates (author-centered rights story); if the seam holds as independent, interpretive authority fragments and must be re-earned separately for each claim, transferring some authority toward historians who can show divergent timing in comparative or pre-1710 evidence.
% ABSENT_VOICES: Pre-1710 customary printers and non-anglophone comparative historians would object that the collapse/independence question, as framed, already assumes the Statute of Anne is the correct site of analysis; they are not consulted in the anglophone doctrinal literature that runs this test.
% DISAPPEARANCE_RATIONALE: If this seam-test reading vanished, the doctrinal literature would likely default silently back to treating 1710 as an indivisible rupture (the beneficiaries' preferred state), which is a substantive rearrangement for public-domain theorists and comparative historians who rely on the seam being explicitly tested to keep the independence question open — but it would be experienced as 'no change' by parties already committed to the collapsed narrative, hence contested rather than a clean verdict either way.
% FOUNDING_PROBLEM: The M4/M5 collapse test was built to resolve an ambiguity in historical IP scholarship: does the phrase 'copyright began in 1710' describe one event or silently conflate two — a category becoming thinkable, and a claimant class taking first occupancy — such that the doctrine's authority rests on an unexamined assumption of their necessary co-occurrence.
% FOUNDING_PROBLEM_CORROBORATION: Analytical jurisprudence researchers running the formal test attest the ambiguity remains unresolved in the primary sources; comparative legal historians outside the anglophone tradition independently corroborate that in other jurisdictions the two processes are documented to occur at different times, which is evidence against automatic co-occurrence and was not generated by, or for the benefit of, the anglophone doctrinal beneficiaries.
narrative_ontology:disappearance_verdict(ip_category_emergence__synchronic_diachronic_seam, contested).
narrative_ontology:founding_problem_status(ip_category_emergence__synchronic_diachronic_seam, live).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(ip_category_emergence__synchronic_diachronic_seam, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet2', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(ip_category_emergence__synchronic_diachronic_seam, 'none', 1).
narrative_ontology:epsilon_provenance(ip_category_emergence__synchronic_diachronic_seam, 0.52, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(ip_category_emergence__synchronic_diachronic_seam_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(ip_category_emergence__synchronic_diachronic_seam, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(ip_category_emergence__synchronic_diachronic_seam_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is moderate (0.52 at present) because the seam test's practical effect is interpretive-authority consolidation, not direct material extraction — but that consolidation compounds over 300+ years of doctrinal citation, which the measurement series reflects as a slow rise. Theater ratio is elevated and rising (0.45) because much of the modern academic apparatus around 'the 1710 moment' performs the collapse as settled historical fact rather than continuing to test it; the test itself increasingly functions as a citation ritual validating an already-fixed narrative rather than a live falsifiable inquiry. Suppression (0.4) reflects the structural difficulty of re-opening a 300-year-old doctrinal convention against institutional teaching momentum, not violent coercion.
 *
 * DIRECTIONALITY LOGIC:
 *   Modern IP maximalist scholarship and publisher-successor interests sit near the beneficiary end: the collapsed reading serves their citation and doctrinal interests with minimal cost. Public domain theorists and comparative legal historians sit toward the target end: they bear the interpretive cost of an unexamined assumption of co-occurrence that forecloses arguments they would otherwise be able to make independently. Pre-1710 customary printers are structurally beyond directionality in the usual sense — they are historical non-participants whose claims are erased by the doctrine's operation regardless of the seam's resolution, hence trapped/powerless rather than merely disadvantaged.
 *
 * MANDATROPHY ANALYSIS:
 *   The seam test prevents a mandatrophy failure mode: without it, the doctrinal community risks perpetually re-litigating '1710' as though the answer to 'did the category emerge' automatically answers 'did occupancy change,' laundering an unexamined joint-determination assumption as historical fact. By keeping M4 and M5 formally separable, the test preserves the possibility that the founding problem (was 1710 one event or two conflated events) remains live rather than being silently declared solved by narrative convenience.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    seam_authenticity_vs_artifact,
    'Is the apparent co-occurrence of category-emergence and first-holding-change at 1710 evidence of a genuinely unified historical event, or an artifact of anglophone doctrinal historiography selecting 1710 as the frame precisely because it makes two separable processes look like one?',
    'Comparative analysis across jurisdictions (continental droit d''auteur timelines, pre-modern non-European print privilege systems) to test whether category emergence and occupancy change are ever observed to diverge in time elsewhere; if they diverge cleanly in even one well-documented comparative case, the anglophone co-occurrence is evidence of framing convenience rather than necessary joint determination.',
    'If the seam is authentic (M4 and M5 are truly bound), the kernel''s structure is validated as a single coherent event and both sibling readings are aspects of one claim. If the seam is an artifact, the kernel decomposes into two independently contestable claims, and doctrinal reliance on ''1710'' as a singular rupture is substantially weakened.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(seam_authenticity_vs_artifact, empirical, 'Whether the M4/M5 co-occurrence at 1710 is structurally necessary or a historiographic artifact of frame selection.').

omega_variable(
    collapse_test_own_extractiveness,
    'Does running the collapse test itself, within institutions already committed to the collapsed narrative, produce a genuine re-examination or merely a ritual confirmation that forecloses the independence finding in advance?',
    'Track citation patterns: does scholarship citing the seam test ever conclude independence, or does it uniformly reaffirm collapse regardless of evidence presented? A one-sided citation record would indicate the test functions as theater.',
    'If the test is performed but never permitted to conclude independence, the theater_ratio measurement here understates the constraint''s actual function as pure doctrinal reinforcement rather than live inquiry, and the classification should move toward a more purely extractive reading.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(collapse_test_own_extractiveness, conceptual, 'Whether the formal seam test is a live falsifiable inquiry or a foreclosed ritual within current doctrinal institutions.').

omega_variable(
    cs_framing_kernel_object_choice,
    'Should the kernel object here be ''1710 as historical event'' or ''the doctrinal practice of citing 1710 as singular rupture''? These are two coherent framings that could produce different cs_pattern readings — the former treats 1710 itself as the kernel text/event under contest, the latter treats the citation convention as the operative commitment system.',
    'Examine whether removing the citation convention (i.e., if courts stopped treating 1710 as a singular event) would change legal outcomes independent of what actually happened historically in 1710 — if outcomes track the citation convention rather than the historical record, the convention is the real kernel object.',
    'Choosing the citation-convention framing supports authority_grounding: extraction (the doctrinal community benefits from citation stability); choosing the historical-event framing supports authority_grounding: expertise (historians adjudicating what actually happened). This story adopts the citation-convention framing as primary, given the beneficiary structure authored above.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(cs_framing_kernel_object_choice, conceptual, 'Alternative framings of the kernel object (historical event vs. citation convention) and their effect on cs_pattern classification.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(ip_category_emergence__synchronic_diachronic_seam, 1690, 2025).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(ip_c_tr_t1690, ip_category_emergence__synchronic_diachronic_seam, theater_ratio, 1690, 0.15).
narrative_ontology:measurement_basis(ip_c_tr_t1690, observed).
narrative_ontology:measurement(ip_c_tr_t1710, ip_category_emergence__synchronic_diachronic_seam, theater_ratio, 1710, 0.22).
narrative_ontology:measurement_basis(ip_c_tr_t1710, observed).
narrative_ontology:measurement(ip_c_tr_t1850, ip_category_emergence__synchronic_diachronic_seam, theater_ratio, 1850, 0.3).
narrative_ontology:measurement_basis(ip_c_tr_t1850, observed).
narrative_ontology:measurement(ip_c_tr_t1950, ip_category_emergence__synchronic_diachronic_seam, theater_ratio, 1950, 0.36).
narrative_ontology:measurement_basis(ip_c_tr_t1950, observed).
narrative_ontology:measurement(ip_c_tr_t1990, ip_category_emergence__synchronic_diachronic_seam, theater_ratio, 1990, 0.41).
narrative_ontology:measurement_basis(ip_c_tr_t1990, observed).
narrative_ontology:measurement(ip_c_tr_t2025, ip_category_emergence__synchronic_diachronic_seam, theater_ratio, 2025, 0.45).
narrative_ontology:measurement_basis(ip_c_tr_t2025, observed).

% Extraction over time
narrative_ontology:measurement(ip_c_be_t1690, ip_category_emergence__synchronic_diachronic_seam, base_extractiveness, 1690, 0.2).
narrative_ontology:measurement_basis(ip_c_be_t1690, observed).
narrative_ontology:measurement(ip_c_be_t1710, ip_category_emergence__synchronic_diachronic_seam, base_extractiveness, 1710, 0.35).
narrative_ontology:measurement_basis(ip_c_be_t1710, observed).
narrative_ontology:measurement(ip_c_be_t1850, ip_category_emergence__synchronic_diachronic_seam, base_extractiveness, 1850, 0.42).
narrative_ontology:measurement_basis(ip_c_be_t1850, observed).
narrative_ontology:measurement(ip_c_be_t1950, ip_category_emergence__synchronic_diachronic_seam, base_extractiveness, 1950, 0.46).
narrative_ontology:measurement_basis(ip_c_be_t1950, observed).
narrative_ontology:measurement(ip_c_be_t1990, ip_category_emergence__synchronic_diachronic_seam, base_extractiveness, 1990, 0.49).
narrative_ontology:measurement_basis(ip_c_be_t1990, observed).
narrative_ontology:measurement(ip_c_be_t2025, ip_category_emergence__synchronic_diachronic_seam, base_extractiveness, 2025, 0.52).
narrative_ontology:measurement_basis(ip_c_be_t2025, observed).

% Suppression authored static: scalar-only by design, no temporal series
narrative_ontology:suppression_profile(ip_category_emergence__synchronic_diachronic_seam, static).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(ip_category_emergence__synchronic_diachronic_seam, identity_coordination).
narrative_ontology:boltzmann_floor_override(ip_category_emergence__synchronic_diachronic_seam, 0.08).
narrative_ontology:affects_constraint(ip_category_emergence__synchronic_diachronic_seam, thinkability_reading).
narrative_ontology:affects_constraint(ip_category_emergence__synchronic_diachronic_seam, first_holding_reading).

% DUAL FORMULATION NOTE:
% This constraint is the methodological seam-test reading within the ip_category_emergence kernel family. thinkability_reading and first_holding_reading each assert that ONE dimension (category emergence or occupancy change, respectively) is the operative claim about 1710; this reading tests whether that assumption of a single operative dimension is itself sound, by asking whether the two dimensions vary independently (in comparative or pre-1710 evidence) or are bound together only by anglophone doctrinal framing. Because this reading's finding (independence vs. artifact) directly determines whether the siblings' claims are separable, well-formed hypotheses or two facets of a conflated single event, it influences both siblings without foreclosing either — a genuine collapse-test outcome in either direction leaves both siblings live as claims about different (or the same) variable.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
