% ============================================================================
% CONSTRAINT STORY: marriage_authority__communal_autonomy_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-14
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_marriage_authority__communal_autonomy_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: marriage_authority__communal_autonomy_reading
 *   human_readable: Marriage Authority Grounded in Communal Religious Tradition (Communal Autonomy Reading)
 *   domain: legal_pluralism/constitutional_law/family_law
 *
 * SUMMARY:
 *   This story instantiates the communal autonomy reading of the marriage
 *   authority kernel: the state enforces marriage, divorce, and inheritance
 *   outcomes generated by community religious authorities without authoring
 *   the substantive norms itself. On this reading, the arrangement is a
 *   legitimate coordination mechanism protecting minority self-governance in
 *   a plural polity, not a transitional anomaly and not primarily a
 *   gender-rights battleground (those are the secularist and gender-rights
 *   readings, authored as separate constraints). The referent for
 *   extractiveness here is the standing arrangement of state-enforced,
 *   community-authored personal law as this reading sees it — moderate ε
 *   reflecting genuine coordination benefit for compliant members alongside
 *   real costs borne by trapped dissenters, not the reading's own preferred
 *   steady state.
 *
 * KEY AGENTS:
 *   - religious_leadership: agenda_setter/beneficiary (institutional/arbitrage) — administers and interprets the norms, collects institutional standing
 *   - the_state: agenda_setter (institutional/constrained) — enforces without authoring, balancing minority protection against equality guarantees
 *   - community_members_in_compliance: beneficiary (moderate/constrained) — receives predictable, legitimate procedures
 *   - intra_community_dissenters: payer (powerless/trapped) — bears the cost of nonconforming life choices
 *   - women_seeking_exit_within_personal_law: payer (powerless/trapped) — bears gendered asymmetry within the tradition's own terms
 *   - civil_courts_and_constitutional_bench: observer (institutional/analytical) — mediates the boundary case by case
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(marriage_authority__communal_autonomy_reading, 0.42).
domain_priors:suppression_score(marriage_authority__communal_autonomy_reading, 0.55).
domain_priors:theater_ratio(marriage_authority__communal_autonomy_reading, 0.18).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(marriage_authority__communal_autonomy_reading, extractiveness, 0.42).
narrative_ontology:constraint_metric(marriage_authority__communal_autonomy_reading, suppression_requirement, 0.55).
narrative_ontology:constraint_metric(marriage_authority__communal_autonomy_reading, theater_ratio, 0.18).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(marriage_authority__communal_autonomy_reading, accessibility_collapse, 0.5).
narrative_ontology:constraint_metric(marriage_authority__communal_autonomy_reading, resistance, 0.6).

% --- Constraint claim ---
narrative_ontology:constraint_claim(marriage_authority__communal_autonomy_reading, rope).
narrative_ontology:human_readable(marriage_authority__communal_autonomy_reading, "Marriage Authority Grounded in Communal Religious Tradition (Communal Autonomy Reading)").
narrative_ontology:topic_domain(marriage_authority__communal_autonomy_reading, "legal_pluralism/constitutional_law/family_law").

domain_priors:requires_active_enforcement(marriage_authority__communal_autonomy_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(marriage_authority__communal_autonomy_reading, '6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6').
narrative_ontology:cs_kernel_codification('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', distributed).
narrative_ontology:cs_authority_grounding('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', lineage).
narrative_ontology:cs_interpretation_layer_present('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6').
narrative_ontology:cs_reading_relation('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', marriage_authority__secularist_reading, forecloses).
narrative_ontology:cs_reading_relation('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', marriage_authority__gender_rights_reading, coexists_with).
narrative_ontology:cs_reading_relation('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', marriage_authority__federalist_millet_reading, influences).
narrative_ontology:cs_reading_relation('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', marriage_authority__judicial_harmonization_reading, influences).
narrative_ontology:cs_axiom('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', foundational, religious_community_holds_original_jurisdiction_over_family_law).
narrative_ontology:cs_axiom_status(religious_community_holds_original_jurisdiction_over_family_law, holdable).
narrative_ontology:cs_axiom_grounding('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', religious_community_holds_original_jurisdiction_over_family_law, conventional).
narrative_ontology:cs_axiom('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', secondary, state_enforcement_without_authorship_preserves_legitimate_pluralism).
narrative_ontology:cs_axiom_status(state_enforcement_without_authorship_preserves_legitimate_pluralism, holdable).
narrative_ontology:cs_axiom_grounding('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', state_enforcement_without_authorship_preserves_legitimate_pluralism, instrumental).
narrative_ontology:cs_reference_frame('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', communal_self_governance_at_incorporation).
narrative_ontology:cs_drift_state('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', contemporary_constitutional_equality_era, gap(practice_drift, substantial, false)).
narrative_ontology:cs_created_at('6c878b02-eb1f-4e4d-8ad9-f2a9cb98efc6', '').
narrative_ontology:cs_kernel_id(marriage_authority__communal_autonomy_reading, marriage_authority).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(marriage_authority__communal_autonomy_reading, religious_leadership).
narrative_ontology:constraint_beneficiary(marriage_authority__communal_autonomy_reading, community_institutional_identity).
narrative_ontology:constraint_victim(marriage_authority__communal_autonomy_reading, intra_community_dissenters).
narrative_ontology:constraint_victim(marriage_authority__communal_autonomy_reading, women_seeking_exit_within_personal_law).
% Derived from stakeholders[] roles (beneficiary->beneficiary, payer->victim;
% agent-gated; excluded derives nothing; deduped against the authored arrays).
narrative_ontology:constraint_beneficiary(marriage_authority__communal_autonomy_reading, community_members_in_compliance).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Interprets and administers marriage, divorce, and inheritance norms for the community under a doctrine of communal self-governance. Negotiates with the state to preserve personal law jurisdiction, resists legislative harmonization, and derives institutional standing and adjudicative authority from being the recognized interpreter of the tradition. Any reform requires their assent or the state risks being cast as violating minority religious freedom.
narrative_ontology:constraint_stakeholder(marriage_authority__communal_autonomy_reading, religious_leadership, agenda_setter,
    institutional, civilizational, arbitrage, national).
narrative_ontology:stakeholder_secondary_role(marriage_authority__communal_autonomy_reading, religious_leadership, beneficiary).

% Enforces personal law rulings issued by community religious authorities through courts and registries, but does not author the substantive norms — it recognizes and executes them. Constitutionally committed to both minority protection and gender equality, it defers to community leadership on substantive family law content to avoid appearing majoritarian or secularist-imposing, even where this produces divergent legal outcomes by religious identity.
narrative_ontology:constraint_stakeholder(marriage_authority__communal_autonomy_reading, the_state, agenda_setter,
    institutional, generational, constrained, national).

% Marry, divorce, and inherit under familiar communal norms administered by recognized religious authorities, with predictable procedures embedded in their social world. For those whose life plans align with the tradition's expectations, the arrangement provides legitimacy, community standing, and continuity without needing to engage an unfamiliar civil system.
narrative_ontology:constraint_stakeholder(marriage_authority__communal_autonomy_reading, community_members_in_compliance, beneficiary,
    moderate, generational, constrained, regional).

% Seek marriage terms, divorce, or inheritance outcomes inconsistent with the community's religious authority's interpretation — inter-faith unions, non-recognition of certain divorces, disinheritance under gendered succession rules. Formal exit to the general civil system exists on paper but carries severe social and economic costs: loss of community standing, family estrangement, and contested legal recognition across jurisdictions.
narrative_ontology:constraint_stakeholder(marriage_authority__communal_autonomy_reading, intra_community_dissenters, payer,
    powerless, biographical, trapped, local).

% Seek divorce, maintenance, or custody outcomes under personal law provisions that grant men more unilateral power than women within the same tradition. The community's own interpretive authority holds the levers governing their status; appeal outside the community's forum risks accusations of betraying the community and rarely produces timely relief.
narrative_ontology:constraint_stakeholder(marriage_authority__communal_autonomy_reading, women_seeking_exit_within_personal_law, payer,
    powerless, biographical, trapped, local).

% Adjudicates disputes at the boundary between constitutional equality guarantees and communal religious autonomy, deciding case by case whether to intervene in personal law outcomes. Its restraint or intervention shapes how much substantive content community authorities can retain.
narrative_ontology:constraint_stakeholder(marriage_authority__communal_autonomy_reading, civil_courts_and_constitutional_bench, observer,
    institutional, generational, analytical, national).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Allows a religious community to govern marriage, divorce, and inheritance according to its own tradition without a centralized, potentially unfamiliar or majoritarian civil code being imposed on its members, preserving communal continuity and self-determination in a plural society.
% TRANSFER_FUNCTION: Moves adjudicative authority and enforcement backing from the state to community religious leadership; moves compliance costs, procedural predictability loss, and reduced exit options from individual dissenters (especially women and those seeking non-traditional unions) to the benefit of the leadership's institutional standing and the compliant majority's continuity.
% ABSENT_VOICES: Intra-community dissenters and women disadvantaged by gendered succession or divorce rules are formally represented by the same leadership whose authority they are contesting; secular reform advocates and inter-faith couples are largely absent from the negotiating table between state and religious leadership.
% DISAPPEARANCE_RATIONALE: If communal authority over marriage law vanished overnight, personal law jurisdiction would collapse into a uniform civil framework; religious leadership would lose adjudicative standing and the associated institutional resources, compliant community members would need to navigate an unfamiliar civil registry system, and dissenters currently trapped within community forums would gain immediate access to a common legal framework — a major reallocation of authority and resources.
% FOUNDING_PROBLEM: In a religiously plural society emerging from or containing colonial-era legal fragmentation, the founding problem was how to grant religious minorities enough self-governance over intimate family matters that they would accept incorporation into a common state without fearing majoritarian legal absorption.
% FOUNDING_PROBLEM_CORROBORATION: Religious leadership and many compliant community members attest the founding problem — fear of majoritarian legal absorption — remains live. Independent constitutional scholars, civil courts in dissenting judgments, and international human rights bodies attest that the protective function has increasingly become a shield for internal power retention, particularly regarding gender-differentiated outcomes, rather than a genuine ongoing defense against external assimilation.
narrative_ontology:disappearance_verdict(marriage_authority__communal_autonomy_reading, world_rearranges).
narrative_ontology:founding_problem_status(marriage_authority__communal_autonomy_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(marriage_authority__communal_autonomy_reading, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet2', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(marriage_authority__communal_autonomy_reading, 'none', 1).
narrative_ontology:epsilon_provenance(marriage_authority__communal_autonomy_reading, 0.42, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(marriage_authority__communal_autonomy_reading_tests).
:- end_tests(marriage_authority__communal_autonomy_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is moderate (0.42 at interval end) because the arrangement performs genuine coordination for the compliant majority while extracting predictability and exit options from a persistently trapped minority within the community. Suppression (0.55) reflects the combination of formal exit (civil marriage exists) and severe informal barriers (social excommunication, contested cross-jurisdiction recognition) that keep dissenters functionally trapped. Theater ratio is low (0.18) because the coordination function is substantively real, not performative — the community forums genuinely adjudicate and resolve disputes, they just do so asymmetrically.
 *
 * PERSPECTIVAL GAP:
 *   From religious leadership's seat, the arrangement reads as a rope — a coordination mechanism preserving communal self-determination against external imposition, functioning smoothly for the overwhelming majority who never contest its outcomes. From the trapped-dissenter seat, the same structure computes closer to tangled rope or worse: genuine coordination exists, but their specific costs are asymmetric and structurally locked in by the same mechanism that benefits everyone else. The engine's per-seat computation is expected to diverge here — that divergence is exactly what the communal-autonomy claim vs. authored metrics gap is meant to surface, not something to reconcile away.
 *
 * DIRECTIONALITY LOGIC:
 *   Religious leadership sits closest to full beneficiary: it sets, interprets, and enforces the applicable norms and retains institutional standing from doing so — d low. Compliant community members are near-beneficiaries with mild indirect cost (constrained exit, but exit is not the operative concern for them). Intra-community dissenters and women seeking exit sit near full-target: trapped exit options, powerless power atom, and the same structure that serves the majority extracts predictability and legal parity from them specifically.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem — protecting a religious minority from majoritarian legal absorption at the moment of incorporation into a common state — has partially outlived its original urgency in contexts where formal equal citizenship is otherwise secure, yet the personal law jurisdiction persists and has, per some corroborating outside sources, drifted toward being primarily a mechanism of internal power retention for religious leadership rather than a live defense against external threat. This story does not resolve that question (mandatrophy_resolved is not declared) because the founding_problem_status is authored as contested — the leadership's own attestation that the protective function remains live is a real, structurally motivated claim, not merely self-serving, given ongoing majoritarian political pressure in many such polities.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    protective_function_still_live,
    'Does communal personal law jurisdiction still perform genuine protection against majoritarian legal absorption, or has that function been substantially achieved by other constitutional guarantees, leaving the jurisdiction as primarily an instrument of internal authority retention?',
    'Comparative analysis of polities where personal law jurisdiction was curtailed or harmonized without triggering the majoritarian absorption the doctrine warns against, weighed against polities where curtailment did coincide with documented minority-rights erosion.',
    'If the protective function has been substantially superseded, this reading''s coordination claim weakens materially and the arrangement drifts toward tangled_rope or piton; if the function remains live, the rope characterization is better supported.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(protective_function_still_live, empirical, 'Whether the founding protective function against majoritarian absorption remains operative today.').

omega_variable(
    internal_dissent_representation_gap,
    'Is the apparent unanimity behind communal autonomy real consensus, or does it reflect the structural absence of dissenting and reform-minded community voices from the negotiation between state and religious leadership?',
    'Survey or qualitative fieldwork directly sampling community members who have attempted exit or reform, comparing their assessment to the leadership''s public position, corroborated by independent (non-community, non-state) civil-society sources.',
    'If dissent is structurally excluded rather than genuinely absent, the apparent coordination consensus this reading relies on is partly manufactured by who is and is not in the room — this would not change the reading''s own ε (which is already reading-indexed) but would sharpen the absent_voices analysis and support the gender_rights_reading''s competing account of the same kernel.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(internal_dissent_representation_gap, conceptual, 'Whether communal consensus reflects genuine agreement or structural exclusion of dissenting voices.').

omega_variable(
    religious_tradition_naturalness_vs_construction,
    'Is the specific content of the personal law code as currently administered a stable, continuous expression of religious tradition, or a colonial-era or modern codification presented as more ancient and fixed than it structurally is?',
    'Historical-legal scholarship tracing the codification history of the specific personal law provisions in question, comparing pre-codification practice diversity to the current administered code''s uniformity claims.',
    'If the code is substantially a modern or colonial-era construction rather than continuous tradition, the leadership''s authority claim to be merely interpreting an inherited tradition weakens, and the arrangement looks more like an invented-tradition mechanism for retaining adjudicative power than a genuine continuity-preserving coordination device.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(religious_tradition_naturalness_vs_construction, conceptual, 'Whether the administered personal law code is genuinely traditional or a more recent construction presented as traditional.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(marriage_authority__communal_autonomy_reading, 0, 40).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(marr_tr_t0, marriage_authority__communal_autonomy_reading, theater_ratio, 0, 0.1).
narrative_ontology:measurement(marr_tr_t8, marriage_authority__communal_autonomy_reading, theater_ratio, 8, 0.12).
narrative_ontology:measurement(marr_tr_t16, marriage_authority__communal_autonomy_reading, theater_ratio, 16, 0.14).
narrative_ontology:measurement(marr_tr_t24, marriage_authority__communal_autonomy_reading, theater_ratio, 24, 0.15).
narrative_ontology:measurement(marr_tr_t32, marriage_authority__communal_autonomy_reading, theater_ratio, 32, 0.17).
narrative_ontology:measurement(marr_tr_t40, marriage_authority__communal_autonomy_reading, theater_ratio, 40, 0.18).

% Extraction over time
narrative_ontology:measurement(marr_be_t0, marriage_authority__communal_autonomy_reading, base_extractiveness, 0, 0.28).
narrative_ontology:measurement(marr_be_t8, marriage_authority__communal_autonomy_reading, base_extractiveness, 8, 0.31).
narrative_ontology:measurement(marr_be_t16, marriage_authority__communal_autonomy_reading, base_extractiveness, 16, 0.35).
narrative_ontology:measurement(marr_be_t24, marriage_authority__communal_autonomy_reading, base_extractiveness, 24, 0.38).
narrative_ontology:measurement(marr_be_t32, marriage_authority__communal_autonomy_reading, base_extractiveness, 32, 0.4).
narrative_ontology:measurement(marr_be_t40, marriage_authority__communal_autonomy_reading, base_extractiveness, 40, 0.42).

% Suppression requirement over time
narrative_ontology:measurement(marr_su_t0, marriage_authority__communal_autonomy_reading, suppression_requirement, 0, 0.4).
narrative_ontology:measurement(marr_su_t8, marriage_authority__communal_autonomy_reading, suppression_requirement, 8, 0.44).
narrative_ontology:measurement(marr_su_t16, marriage_authority__communal_autonomy_reading, suppression_requirement, 16, 0.47).
narrative_ontology:measurement(marr_su_t24, marriage_authority__communal_autonomy_reading, suppression_requirement, 24, 0.5).
narrative_ontology:measurement(marr_su_t32, marriage_authority__communal_autonomy_reading, suppression_requirement, 32, 0.53).
narrative_ontology:measurement(marr_su_t40, marriage_authority__communal_autonomy_reading, suppression_requirement, 40, 0.55).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(marriage_authority__communal_autonomy_reading, identity_coordination).
narrative_ontology:boltzmann_floor_override(marriage_authority__communal_autonomy_reading, 0.1).
narrative_ontology:affects_constraint(marriage_authority__communal_autonomy_reading, secularist_reading).
narrative_ontology:affects_constraint(marriage_authority__communal_autonomy_reading, gender_rights_reading).
narrative_ontology:affects_constraint(marriage_authority__communal_autonomy_reading, federalist_millet_reading).
narrative_ontology:affects_constraint(marriage_authority__communal_autonomy_reading, judicial_harmonization_reading).

% DUAL FORMULATION NOTE:
% This constraint is one of five sibling readings of the marriage_authority kernel, each authored as a separate constraint with its own ε and stakeholder structure per the ε-invariance principle. communal_autonomy_reading (this file) authors moderate ε (0.42, rope-leaning) reflecting genuine coordination benefit for the compliant community weighed against real but bounded extraction from trapped dissenters. gender_rights_reading is expected to author substantially higher ε for the same standing arrangement, foregrounding the gendered asymmetry this reading treats as a secondary cost. secularist_reading treats the arrangement as an illegitimate transitional anomaly with correspondingly different beneficiary/victim framing. federalist_millet_reading shares this reading's positive valence toward pluralism but grounds it in anti-majoritarian constitutional design rather than religious self-governance per se. judicial_harmonization_reading describes a distinct, evolving equilibrium being produced by case-by-case constitutional review rather than either a stable communal-autonomy or a stable secularist end-state.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
