% ============================================================================
% CONSTRAINT STORY: nuclear_impossibility_kernel__credibility_paradox_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_nuclear_impossibility_kernel__credibility_paradox_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: nuclear_impossibility_kernel__credibility_paradox_reading
 *   human_readable: Nuclear Deterrence Credibility Paradox (Escalation-Ladder Reading)
 *   domain: strategic/military/political
 *
 * SUMMARY:
 *   This story instantiates the credibility-paradox reading of the nuclear
 *   impossibility kernel: deterrence requires a threat to use weapons whose
 *   use guarantees mutual destruction, making the terminal threat
 *   structurally incredible. Rather than treating this as a closed physical
 *   impossibility (the structural_contraction_reading) or a rational-choice
 *   dead end that removes victory from consideration (the
 *   rational_dropout_reading), this reading holds that the incredibility is
 *   managed, not resolved — nuclear states respond by constructing escalation
 *   ladders, counterforce options, and limited-war doctrines that render some
 *   rung of the threat credible even though the terminal rung remains
 *   suicidal. 'Unthinkability' functions here as public rhetoric layered over
 *   an actively maintained architecture of intermediate, allegedly 'usable'
 *   nuclear options. War remains reachable through escalation, not foreclosed
 *   by physics or rational choice.
 *
 * KEY AGENTS:
 *   - nuclear_weapons_states_command_authorities: primary agenda-setter and beneficiary — administers escalation doctrine
 *   - defense_industrial_base: beneficiary — captures procurement generated by the credibility-restoration project
 *   - strategic_studies_establishment: beneficiary — intellectual capital tied to the unresolved paradox
 *   - non_nuclear_frontline_populations, conscript_and_professional_military_personnel, non_nuclear_weapon_states: victims — bear escalation risk without doctrinal voice
 *   - strategic_analysts_observer: analytical seat assessing crisis-stability literature
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(nuclear_impossibility_kernel__credibility_paradox_reading, 0.68).
domain_priors:suppression_score(nuclear_impossibility_kernel__credibility_paradox_reading, 0.62).
domain_priors:theater_ratio(nuclear_impossibility_kernel__credibility_paradox_reading, 0.58).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(nuclear_impossibility_kernel__credibility_paradox_reading, extractiveness, 0.68).
narrative_ontology:constraint_metric(nuclear_impossibility_kernel__credibility_paradox_reading, suppression_requirement, 0.62).
narrative_ontology:constraint_metric(nuclear_impossibility_kernel__credibility_paradox_reading, theater_ratio, 0.58).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(nuclear_impossibility_kernel__credibility_paradox_reading, accessibility_collapse, 0.4).
narrative_ontology:constraint_metric(nuclear_impossibility_kernel__credibility_paradox_reading, resistance, 0.71).

% --- Constraint claim ---
narrative_ontology:constraint_claim(nuclear_impossibility_kernel__credibility_paradox_reading, tangled_rope).
narrative_ontology:human_readable(nuclear_impossibility_kernel__credibility_paradox_reading, "Nuclear Deterrence Credibility Paradox (Escalation-Ladder Reading)").
narrative_ontology:topic_domain(nuclear_impossibility_kernel__credibility_paradox_reading, "strategic/military/political").

domain_priors:requires_active_enforcement(nuclear_impossibility_kernel__credibility_paradox_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(nuclear_impossibility_kernel__credibility_paradox_reading, 'b93944ac-537e-4c6e-ab97-5ae1372a6b85').
narrative_ontology:cs_kernel_codification('b93944ac-537e-4c6e-ab97-5ae1372a6b85', distributed).
narrative_ontology:cs_authority_grounding('b93944ac-537e-4c6e-ab97-5ae1372a6b85', practice).
narrative_ontology:cs_interpretation_layer_present('b93944ac-537e-4c6e-ab97-5ae1372a6b85').
narrative_ontology:cs_reading_relation('b93944ac-537e-4c6e-ab97-5ae1372a6b85', nuclear_impossibility_kernel__structural_contraction_reading, coexists_with).
narrative_ontology:cs_reading_relation('b93944ac-537e-4c6e-ab97-5ae1372a6b85', nuclear_impossibility_kernel__rational_dropout_reading, influences).
narrative_ontology:cs_axiom('b93944ac-537e-4c6e-ab97-5ae1372a6b85', foundational, credibility_is_engineerable_not_fixed).
narrative_ontology:cs_axiom_status(credibility_is_engineerable_not_fixed, holdable).
narrative_ontology:cs_axiom_grounding('b93944ac-537e-4c6e-ab97-5ae1372a6b85', credibility_is_engineerable_not_fixed, empirically_contingent).
narrative_ontology:cs_axiom('b93944ac-537e-4c6e-ab97-5ae1372a6b85', foundational, unthinkability_is_declaratory_not_structural).
narrative_ontology:cs_axiom_status(unthinkability_is_declaratory_not_structural, holdable).
narrative_ontology:cs_axiom_grounding('b93944ac-537e-4c6e-ab97-5ae1372a6b85', unthinkability_is_declaratory_not_structural, empirically_contingent).
narrative_ontology:cs_reference_frame('b93944ac-537e-4c6e-ab97-5ae1372a6b85', assured_destruction_baseline).
narrative_ontology:cs_drift_state('b93944ac-537e-4c6e-ab97-5ae1372a6b85', post_cold_war_doctrinal_expansion, gap(practice_drift, substantial, false)).
narrative_ontology:cs_created_at('b93944ac-537e-4c6e-ab97-5ae1372a6b85', '').
narrative_ontology:cs_kernel_id(nuclear_impossibility_kernel__credibility_paradox_reading, nuclear_impossibility_kernel).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(nuclear_impossibility_kernel__credibility_paradox_reading, nuclear_weapons_states_command_authorities).
narrative_ontology:constraint_beneficiary(nuclear_impossibility_kernel__credibility_paradox_reading, defense_industrial_base).
narrative_ontology:constraint_beneficiary(nuclear_impossibility_kernel__credibility_paradox_reading, strategic_studies_establishment).
narrative_ontology:constraint_victim(nuclear_impossibility_kernel__credibility_paradox_reading, non_nuclear_frontline_populations).
narrative_ontology:constraint_victim(nuclear_impossibility_kernel__credibility_paradox_reading, conscript_and_professional_military_personnel).
narrative_ontology:constraint_victim(nuclear_impossibility_kernel__credibility_paradox_reading, non_nuclear_weapon_states).
% Derived from stakeholders[] roles (beneficiary->beneficiary, payer->victim;
% agent-gated; excluded derives nothing; deduped against the authored arrays).
narrative_ontology:constraint_victim(nuclear_impossibility_kernel__credibility_paradox_reading, civilian_populations_of_nuclear_states).
narrative_ontology:constraint_vindicates(nuclear_impossibility_kernel__credibility_paradox_reading, escalation_dominance_doctrine).
narrative_ontology:constraint_vindicates(nuclear_impossibility_kernel__credibility_paradox_reading, flexible_response_doctrine).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Design and maintain graduated escalation options — counterforce targeting, tactical warheads, limited-strike doctrines — precisely because the pure countervalue threat is not credible. They administer the ladder, control alert postures, and retain the ability to reinterpret 'red lines' at will. Their exit from the paradox is to make the threat piecemeal-credible rather than to resolve the underlying incredibility.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, nuclear_weapons_states_command_authorities, agenda_setter,
    institutional, generational, arbitrage, global).
narrative_ontology:stakeholder_secondary_role(nuclear_impossibility_kernel__credibility_paradox_reading, nuclear_weapons_states_command_authorities, beneficiary).

% Manufactures the tactical and low-yield systems, missile defense components, and command-and-control infrastructure that the credibility problem generates demand for. Every new escalation rung funded to make deterrence 'usable again' is a procurement line. Has no exit incentive because the paradox itself is the revenue engine.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, defense_industrial_base, beneficiary,
    organized, generational, arbitrage, national).

% Think tanks, war colleges, and academic strategists build careers theorizing the credibility gap and proposing escalation-ladder solutions (flexible response, graduated deterrence, limited nuclear options). Their intellectual capital depends on the paradox remaining unresolved and analytically productive; genuine resolution (abolition or airtight structural impossibility) would eliminate the field's central puzzle.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, strategic_studies_establishment, beneficiary,
    organized, civilizational, mobile, global).

% Live in the theaters where 'limited' nuclear war is doctrinally imagined as fightable — the Central European front, the Korean peninsula, South Asia. They bear the risk that escalation ladders built to restore credibility actually get climbed. They have no vote in doctrine and no geographic exit from being the designated battlespace.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, non_nuclear_frontline_populations, payer,
    powerless, biographical, trapped, regional).

% Are the operators and targets within the counterforce and limited-war architectures built to make deterrence credible again. Their survival odds are the input variable strategists optimize when designing 'usable' options. Military service structures exit as desertion or court-martial, not a live option.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, conscript_and_professional_military_personnel, payer,
    powerless, biographical, constrained, national).

% Operate under extended-deterrence umbrellas or outside them entirely, subject to a global order shaped by nuclear states' need to keep threats credible through visible escalation infrastructure and periodic crisis brinkmanship. Cannot opt out of the risk environment nuclear-armed states' doctrine debates create; can only hedge (alliance-seeking or proliferation) at high cost.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, non_nuclear_weapon_states, payer,
    moderate, generational, constrained, global).

% Argue that resolving the credibility paradox by building more usable options is itself destabilizing, and press instead for verified reductions and de-escalatory postures. Their proposals are structurally marginal to doctrine-setting institutions dominated by command authorities and industrial interests.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, arms_control_diplomats, excluded,
    moderate, generational, constrained, global).

% Remain the ultimate countervalue target set underwriting the whole architecture, whatever counterforce refinements are layered on top. They fund the escalation ladder through taxation and bear the tail risk without input into doctrine.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, civilian_populations_of_nuclear_states, payer,
    powerless, biographical, trapped, national).

% Study the doctrinal record, war-gaming outcomes, and crisis-instability literature to assess whether escalation ladders genuinely restore credibility or merely add fragile intermediate rungs that make inadvertent war more likely.
narrative_ontology:constraint_stakeholder(nuclear_impossibility_kernel__credibility_paradox_reading, strategic_analysts_observer, observer,
    analytical, civilizational, analytical, universal).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(nuclear_impossibility_kernel__credibility_paradox_reading, defense_industrial_base).
narrative_ontology:fixing_cost_class(nuclear_impossibility_kernel__credibility_paradox_reading, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Coordinates the joint problem facing nuclear-armed states: how to make a threat that is strategically incredible at the terminal level (full exchange = mutual destruction) function as if credible, by building graduated, seemingly 'usable' intermediate options that restore some deterrent bite short of civilizational suicide.
% TRANSFER_FUNCTION: Moves resources from national treasuries and risk from decision-making elites onto frontline populations, conscripts, and non-nuclear states: procurement budgets flow to the defense industrial base and doctrinal prestige flows to strategists, while the tail risk of escalation is displaced onto those with no voice in doctrine.
% ABSENT_VOICES: Frontline populations in designated 'limited war' theaters, conscripts who operate the systems, and non-nuclear states living under or outside extended deterrence have no seat in doctrine formation; arms control diplomats are present but structurally marginalized relative to command authorities and industrial lobbies.
% DISAPPEARANCE_RATIONALE: If the credibility-paradox framing and its escalation-ladder solutions vanished, procurement priorities for tactical and counterforce systems would lose their doctrinal justification, war colleges would need a new organizing puzzle, and crisis diplomacy would shift from managing graduated brinkmanship to managing a starker binary (use or don't). Force postures, alliance guarantees, and defense budgets would all reorganize.
% FOUNDING_PROBLEM: Following Hiroshima and Nagasaki, and especially once the Soviet Union achieved secure second-strike capability, strategists faced a genuine logical problem: a threat whose fulfillment destroys the threatener has no rational execution path, which appears to void its deterrent value.
% FOUNDING_PROBLEM_CORROBORATION: Command authorities and strategic studies institutions attest the problem remains live and requires ongoing doctrinal refinement (flexible response, counterforce modernization). Independent crisis-stability researchers (e.g. Cold War crisis historiography, Nuclear Threat Initiative analyses) and several retired flag officers attest that escalation-ladder solutions have themselves generated new instability — inadvertent escalation risk, use-it-or-lose-it pressures — suggesting the 'fix' has partially superseded the original problem it was meant to solve.
narrative_ontology:disappearance_verdict(nuclear_impossibility_kernel__credibility_paradox_reading, world_rearranges).
narrative_ontology:founding_problem_status(nuclear_impossibility_kernel__credibility_paradox_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(nuclear_impossibility_kernel__credibility_paradox_reading, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet2', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(nuclear_impossibility_kernel__credibility_paradox_reading, 'none', 1).
narrative_ontology:epsilon_provenance(nuclear_impossibility_kernel__credibility_paradox_reading, 0.68, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(nuclear_impossibility_kernel__credibility_paradox_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(nuclear_impossibility_kernel__credibility_paradox_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(nuclear_impossibility_kernel__credibility_paradox_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness rises from moderate (0.35) at the dawn of the nuclear age to substantial (0.68) by 2025 as escalation-ladder doctrines proliferated (flexible response in the 1960s, PD-59/counterforce refinements in the 1980s, post-Cold War modernization and current hypersonic/tactical revivals). Theater ratio is high (0.58) because much of the doctrinal apparatus — declaratory policy, 'red line' rhetoric, arms control theater — performs stability management while the underlying credibility problem is never actually solved, only displaced onto intermediate rungs. Suppression tracks crisis intensity: it peaks during acute confrontations (Cuban Missile Crisis era, Able Archer 1983) and partially relaxes during détente/post-Cold War drawdown before rising again with contemporary great-power competition. Accessibility collapse is moderate (0.4) — alternatives such as verified disarmament or minimal deterrence exist and are actively argued by arms control communities, they are simply institutionally marginalized, not physically foreclosed. Resistance is high (0.71): the paradox has never lacked vocal critics (nuclear freeze movements, arms control diplomats, dissenting strategists), consistent with a tangled_rope's requirement of active, contested maintenance rather than an uncontested mountain.
 *
 * DIRECTIONALITY LOGIC:
 *   Command authorities, the defense industrial base, and the strategic studies establishment sit near the full-beneficiary end: they administer, profit from, or build careers around the credibility-restoration project. Frontline populations, conscripts, and non-nuclear states sit near the full-target end: they bear escalation risk and resource costs without doctrinal input, and their exit options are trapped or constrained by geography, service obligation, or geopolitical position. Civilian populations of nuclear states occupy a similar payer position — they underwrite the risk as the ultimate countervalue target set. Arms control diplomats are excluded rather than clearly positioned as victim or beneficiary; they attempt to shift the arrangement but are structurally sidelined.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem (a logically incredible terminal threat) is genuinely live in structural-physics terms, but the *specific arrangement* built to address it — proliferating escalation ladders and counterforce doctrine — has arguably outrun the problem it was meant to solve, generating new inadvertent-escalation risks (use-it-or-lose-it pressure, crisis miscalculation) that did not exist in a simpler assured-destruction posture. This is why founding_problem_status is authored as contested rather than flatly live: the mismatch between a persistently-cited justification and a demonstrably expanding architecture is exactly the capture signature the R5 interview is designed to surface.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    escalation_ladder_genuine_or_theatrical,
    'Do counterforce and limited-nuclear-option doctrines genuinely restore deterrent credibility at intermediate rungs, or are they primarily bureaucratic and rhetorical artifacts that do not actually change adversary calculations?',
    'Comparative crisis-behavior analysis across periods of doctrinal change (massive retaliation vs. flexible response vs. post-Cold War posture) controlling for adversary capability and political context; declassified adversary assessments of whether limited-option postures were read as more credible.',
    'If escalation ladders are shown to be largely theatrical, the constraint''s theater_ratio should be revised upward and its classification drifts further toward pure extraction (procurement and career capture riding on unresolved rhetoric); if they demonstrably alter adversary risk calculus, the coordination function is stronger than the extraction reading credits.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(escalation_ladder_genuine_or_theatrical, empirical, 'Whether graduated nuclear options genuinely restore credibility or merely perform it.').

omega_variable(
    kernel_framing_selection,
    'Is the credibility-paradox framing (incredibility as manageable-through-doctrine) the correct lens on the nuclear impossibility kernel, or do the sibling readings (physical impossibility / rational dropout) better describe the actual constraint on great-power behavior since 1945?',
    'Historical audit of near-miss crises (Cuban Missile Crisis, Able Archer 1983, 2019 Kashmir crisis) for evidence of genuine escalation-ladder climbing versus early off-ramping driven by rational-dropout or structural-contraction logic.',
    'If the historical record shows escalation consistently arrested well below any nuclear threshold regardless of declared doctrine, the rational_dropout_reading or structural_contraction_reading may better characterize actual great-power behavior, and this reading''s claim that ''war remains reachable via escalation ladders'' would be substantially weakened.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_framing_selection, conceptual, 'Which of the three kernel readings best fits the historical crisis-behavior record.').

omega_variable(
    beneficiary_capture_vs_genuine_strategic_need,
    'Is continued escalation-ladder doctrine sustained because it serves a genuine, unresolved strategic problem, or because the defense industrial base and strategic studies establishment have institutional incentives to keep the paradox analytically and materially productive?',
    'Trace procurement and research funding flows against doctrinal announcements; assess whether doctrinal ''gaps requiring new capability'' correlate with independent threat assessments or with industry proposal cycles.',
    'Strong correlation with proposal cycles over independent threat assessment would support classifying a larger share of the extraction as rent-seeking capture rather than genuine coordination against an unresolved strategic problem.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(beneficiary_capture_vs_genuine_strategic_need, empirical, 'Whether escalation doctrine tracks strategic necessity or institutional self-interest.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(nuclear_impossibility_kernel__credibility_paradox_reading, 1945, 2025).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(nucl_tr_t1945, nuclear_impossibility_kernel__credibility_paradox_reading, theater_ratio, 1945, 0.2).
narrative_ontology:measurement(nucl_tr_t1962, nuclear_impossibility_kernel__credibility_paradox_reading, theater_ratio, 1962, 0.35).
narrative_ontology:measurement(nucl_tr_t1983, nuclear_impossibility_kernel__credibility_paradox_reading, theater_ratio, 1983, 0.5).
narrative_ontology:measurement(nucl_tr_t1991, nuclear_impossibility_kernel__credibility_paradox_reading, theater_ratio, 1991, 0.55).
narrative_ontology:measurement(nucl_tr_t2010, nuclear_impossibility_kernel__credibility_paradox_reading, theater_ratio, 2010, 0.5).
narrative_ontology:measurement(nucl_tr_t2025, nuclear_impossibility_kernel__credibility_paradox_reading, theater_ratio, 2025, 0.58).

% Extraction over time
narrative_ontology:measurement(nucl_be_t1945, nuclear_impossibility_kernel__credibility_paradox_reading, base_extractiveness, 1945, 0.35).
narrative_ontology:measurement(nucl_be_t1962, nuclear_impossibility_kernel__credibility_paradox_reading, base_extractiveness, 1962, 0.52).
narrative_ontology:measurement(nucl_be_t1983, nuclear_impossibility_kernel__credibility_paradox_reading, base_extractiveness, 1983, 0.66).
narrative_ontology:measurement(nucl_be_t1991, nuclear_impossibility_kernel__credibility_paradox_reading, base_extractiveness, 1991, 0.58).
narrative_ontology:measurement(nucl_be_t2010, nuclear_impossibility_kernel__credibility_paradox_reading, base_extractiveness, 2010, 0.6).
narrative_ontology:measurement(nucl_be_t2025, nuclear_impossibility_kernel__credibility_paradox_reading, base_extractiveness, 2025, 0.68).

% Suppression requirement over time
narrative_ontology:measurement(nucl_su_t1945, nuclear_impossibility_kernel__credibility_paradox_reading, suppression_requirement, 1945, 0.3).
narrative_ontology:measurement(nucl_su_t1962, nuclear_impossibility_kernel__credibility_paradox_reading, suppression_requirement, 1962, 0.55).
narrative_ontology:measurement(nucl_su_t1983, nuclear_impossibility_kernel__credibility_paradox_reading, suppression_requirement, 1983, 0.68).
narrative_ontology:measurement(nucl_su_t1991, nuclear_impossibility_kernel__credibility_paradox_reading, suppression_requirement, 1991, 0.5).
narrative_ontology:measurement(nucl_su_t2010, nuclear_impossibility_kernel__credibility_paradox_reading, suppression_requirement, 2010, 0.55).
narrative_ontology:measurement(nucl_su_t2025, nuclear_impossibility_kernel__credibility_paradox_reading, suppression_requirement, 2025, 0.62).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(nuclear_impossibility_kernel__credibility_paradox_reading, enforcement_mechanism).
narrative_ontology:boltzmann_floor_override(nuclear_impossibility_kernel__credibility_paradox_reading, 0.12).
narrative_ontology:affects_constraint(nuclear_impossibility_kernel__credibility_paradox_reading, structural_contraction_reading).
narrative_ontology:affects_constraint(nuclear_impossibility_kernel__credibility_paradox_reading, rational_dropout_reading).

% DUAL FORMULATION NOTE:
% This story is one of three sibling readings of the nuclear_impossibility_kernel, each a separate constraint with its own epsilon and stakeholder structure per the ε-invariance principle. credibility_paradox_reading treats the incredibility as an ongoing, actively-managed doctrinal problem (tangled_rope: real coordination function of maintaining some deterrent value, plus asymmetric extraction via procurement and career capture layered on frontline populations and non-nuclear states). structural_contraction_reading treats the same underlying physical fact as a harder, more mountain-like impossibility with negligible extraction. rational_dropout_reading treats it as a rational-choice constraint that removes victory from consideration without asserting physical impossibility. All three link to each other via affects_constraints; none averages or hedges across the others' epsilon values.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(nuclear_impossibility_kernel__credibility_paradox_reading, moderate, 0.7).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
