#!/usr/bin/env python3
"""OQ-207 census: stakeholder-frame H1 across the three live legs + kernel_v1.

Two-stage per design D8 (the census reads an INTERMEDIATE ARTIFACT, which pins
the planted-violation injection point at the read site, not post-read):

  Stage 1 — serialized one-shot swipl goals per corpus (never concurrent),
  each: corpus_path overlay (retractall+assertz, the witnessed recipe) ->
  cache_registry:clear_all_caches (D7) -> load_all_testsets -> dump
  census_input_<leg>.json of per-constraint records
  {id, h0, h1, n_seats, n_real, verdict, plural_has_unknown, n_excluded}.
  The verdict class rides in the artifact because (h1, n_seats, n_real) alone
  cannot distinguish the seats_untyped stratum from cell (b) (both n_real=0
  with seats present).

  Stage 2 — the assertion layer consumes ONLY those artifacts and computes:
  null-cause strata, H1 distribution keyed by n_real, spectrum violations
  (must be 0), mcc-coherence cell counts (D4 table incl. divergence cells (a),
  (b) and the mixed plural([T,unknown]) cell) — every rate with raw count +
  n_in_domain (OQ-136).

Controls:
  - kernel_v1 all-null: zero stakeholder facts -> every record must read
    (null, null, 0, 0, no_agent_seats) — the negative-domain control.
  - planted violation: a doctored COPY of a census_input artifact (an
    out-of-spectrum h1 at a valid n_real) run through the SAME assertion path
    and shown FLAGGED — proving the probe fires on the artifact it audits.
  - zero-seat counts vs the OQ-202 mint strata 26/466/212 (drift = finding,
    not failure; reported, never asserted).

KILL CONDITION (D4) — FIRED 2026-07-12 (cell (b) live = 4) and RESOLVED by the
OQ-217 tightening (commit 871e69ac): consensus verdicts now compute over
is_real_type/1 seats only, so the divergence cells (a)/(b)/mixed are RETIRED.
Post-OQ-217 this script asserts their populations are ZERO — the detectors
stay live as regression tripwires (deleting them would be Build Discipline
Pattern 5: a gate satisfied by absence of its input). New coherent cells:
insufficient_real_seats, coherent_unanimous_untypeable.

Spectrum machinery is IMPORTED from oq195_h1_spectrum_check (Lemma-1 brute
force + T-bound), never forked; T is derived from code exactly as that script
derives it.

Usage: python3 python/audits/oq207_stakeholder_h1_census.py [--outdir DIR]
       [--skip-dump]   (reuse existing census_input_*.json artifacts)
Exit nonzero on: spectrum violation, incoherent mcc cell, null-rule violation,
kernel_v1 control failure, or a planted control that does NOT fire.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PROLOG_DIR = os.path.join(REPO, 'prolog')
sys.path.insert(0, os.path.join(REPO, 'python'))
sys.path.insert(0, os.path.join(REPO, 'python', 'audits'))

import oq195_h1_spectrum_check as oq195  # Lemma-1 machinery — no fork

LEGS = {
    'testsets': 'testsets',
    'testsets_haiku': 'testsets_haiku',
    'testsets_flash': 'testsets_flash',
    'kernel_v1': 'archives/datasets/kernel_v1',
}
LIVE_LEGS = ('testsets', 'testsets_haiku', 'testsets_flash')
OQ202_MINT_ZERO_SEAT = {'testsets': 26, 'testsets_haiku': 466, 'testsets_flash': 212}

DUMP_PL = r'''
% OQ-207 stage-1 dump (generated by oq207_stakeholder_h1_census.py — the
% canonical copy lives in that script; do not edit this file).
dump_leg(Leg, OutFile) :-
    retractall(config:param(corpus_path, _)),
    assertz(config:param(corpus_path, Leg)),
    cache_registry:clear_all_caches,
    format(user_error, "[clear] caches cleared for leg ~w~n", [Leg]),
    corpus_loader:load_all_testsets,
    setup_call_cleanup(open(OutFile, write, S), dump_records(S), close(S)).

dump_records(S) :-
    format(S, "[", []),
    findall(C, corpus_loader:corpus_constraint(C), Cs),
    dump_list(S, Cs),
    format(S, "~n]~n", []).

dump_list(_, []).
dump_list(S, [C|T]) :-
    dump_one(S, C),
    ( T == [] -> true ; format(S, ",", []) ),
    dump_list(S, T).

% n_excluded is MEASURED for every record by direct fact query, independent
% of the verdict shape (pre-OQ-217 dumps authored 0 for non-mcc verdicts — an
% authored-zero that under-determined the movement prediction, witnessed
% 2026-07-12 in movement_diff v1; Build Discipline Pattern 5).
dump_one(S, C) :-
    stakeholder_seats:stakeholder_obstruction(C, H0, H1, NS, NR),
    stakeholder_seats:consensus_provenance(C, V),
    findall(X, narrative_ontology:constraint_stakeholder(C, X, excluded, _, _, _, _), Excl),
    length(Excl, NExcl),
    verdict_fields(V, VName, HasUnknown),
    format(S, '~n  {"id": "~w", "h0": ~w, "h1": ~w, "n_seats": ~w, "n_real": ~w, "verdict": "~w", "plural_has_unknown": ~w, "n_excluded": ~w}',
           [C, H0, H1, NS, NR, VName, HasUnknown, NExcl]).

verdict_fields(no_agent_seats,               no_agent_seats,               null).
verdict_fields(seats_untyped,                seats_untyped,                null).
verdict_fields(insufficient_real_seats,      insufficient_real_seats,      null).
verdict_fields(unanimous_no_excluded_seats,  unanimous_no_excluded_seats,  null).
verdict_fields(unanimous_with_untypeable_seats,
               unanimous_with_untypeable_seats, null).
verdict_fields(manufactured_consensus_candidate(_),
               manufactured_consensus_candidate, null).
verdict_fields(manufactured_consensus_candidate_untypeable(_),
               manufactured_consensus_candidate_untypeable, null).
% plural_has_unknown is a RETIRED-cell tripwire post-OQ-217: the unknown token
% can no longer appear in a plural term, so true here = regression.
verdict_fields(plural(Us), plural, HU) :-
    ( memberchk(unknown, Us) -> HU = true ; HU = false ).
'''

UNANIMOUS_ALL_REAL = {'unanimous_no_excluded_seats', 'manufactured_consensus_candidate'}
UNANIMOUS_UNTYPEABLE = {'unanimous_with_untypeable_seats',
                        'manufactured_consensus_candidate_untypeable'}
# Cells retired by OQ-217 — populations MUST be 0; the detectors stay live.
RETIRED_CELLS = ('cell_a_single_real', 'cell_b_all_unknown', 'mixed_plural_unknown')


def derive_T():
    from axiom_reachability import ALL_TYPES
    return len([t for t in ALL_TYPES if t != 'unknown'])


def spectrum(n_real, T):
    """Proven reachable H1 set for n_real real seats, T-bounded (H(n,T))."""
    if n_real < 2:
        return set()
    return oq195.union(oq195.brute_bands(n_real, t_bound=T))


def dump_all(outdir):
    """Stage 1: serialized swipl dumps, one fresh process per leg."""
    pl_path = os.path.join(outdir, 'oq207_dump.pl')
    with open(pl_path, 'w') as f:
        f.write(DUMP_PL)
    for leg, path in LEGS.items():
        out = os.path.join(outdir, f'census_input_{leg}.json')
        goal = f"[stack], consult('{pl_path}'), dump_leg('{path}', '{out}'), halt"
        print(f"[stage1] dumping {leg} ({path}) ...", flush=True)
        r = subprocess.run(['swipl', '-g', goal, '-t', 'halt(1)'],
                           cwd=PROLOG_DIR, capture_output=True, text=True)
        clear_lines = [l for l in r.stderr.splitlines() if l.startswith('[clear]')]
        loaded = [l for l in r.stderr.splitlines() if 'Loaded' in l and 'testsets' in l]
        print('  ' + '\n  '.join(clear_lines + loaded), flush=True)
        if r.returncode != 0:
            print(r.stderr[-2000:], file=sys.stderr)
            raise SystemExit(f"stage-1 dump failed for {leg} (exit {r.returncode})")


def classify_cell(rec):
    """The coherence cell of one record (mirrors the plunit case table,
    post-OQ-217 EXACT biconditional). The retired divergence cells
    (cell_a/cell_b/mixed) are still DETECTED — they are regression
    tripwires asserted to zero in main(), never deleted branches."""
    v, h1, nr, ns = rec['verdict'], rec['h1'], rec['n_real'], rec['n_seats']
    if v == 'no_agent_seats':
        return 'no_agent_seats' if (ns == 0 and h1 is None) else 'INCOHERENT'
    if v == 'seats_untyped':
        return 'seats_untyped' if (ns >= 1 and nr == 0 and h1 is None) else 'INCOHERENT'
    if v == 'insufficient_real_seats':
        return 'insufficient_real_seats' if (ns >= 1 and nr < 2 and h1 is None) \
            else 'INCOHERENT'
    if v in UNANIMOUS_ALL_REAL:
        if nr >= 2 and nr == ns:
            return 'coherent_unanimous' if h1 == 0 else 'INCOHERENT'
        if nr == 1:
            return 'cell_a_single_real'      # RETIRED (OQ-217) — must be 0
        if nr == 0:
            return 'cell_b_all_unknown'      # RETIRED (OQ-217) — must be 0
        return 'INCOHERENT'                  # nr>=2,nr<ns owed the _untypeable token
    if v in UNANIMOUS_UNTYPEABLE:
        return 'coherent_unanimous_untypeable' \
            if (nr >= 2 and nr < ns and h1 == 0) else 'INCOHERENT'
    if v == 'plural':
        if rec['plural_has_unknown']:
            return 'mixed_plural_unknown'    # RETIRED (OQ-217) — must be 0
        return 'coherent_plural' if (nr >= 2 and isinstance(h1, int) and h1 > 0) \
            else 'INCOHERENT'
    return 'INCOHERENT'


def assess(records, T):
    """Stage 2: the assertion layer. Consumes artifact records ONLY."""
    n = len(records)
    out = {'n_corpus': n, 'violations': {'spectrum': [], 'null_rule': [], 'incoherent': []},
           'table_exhausted': []}
    # (key rename at OQ-217: 'all_unknown_cell_b' -> 'all_unknown_derived' —
    # the stratum now arrives via insufficient_real_seats, not a unanimity
    # wrong-verdict; nr, not the verdict, is the discriminator.)
    strata = {'no_agent_seats': 0, 'seats_untyped': 0, 'single_real_seat': 0,
              'all_unknown_derived': 0}
    h1_by_nreal = {}
    cells = {}
    for r in records:
        h1, nr, ns = r['h1'], r['n_real'], r['n_seats']
        # OQ-51 null rule, two-sided: h1 numbered <-> n_real >= 2
        if (h1 is None) != (nr < 2):
            out['violations']['null_rule'].append(r['id'])
        # null-cause strata (h1 null only)
        if h1 is None:
            if ns == 0:
                strata['no_agent_seats'] += 1
            elif r['verdict'] == 'seats_untyped':
                strata['seats_untyped'] += 1
            elif nr == 1:
                strata['single_real_seat'] += 1
            elif nr == 0:
                strata['all_unknown_derived'] += 1
        else:
            if nr > 12:
                out['table_exhausted'].append(r['id'])   # extension signal, not a law violation
            if h1 not in spectrum(nr, T):
                out['violations']['spectrum'].append(
                    {'id': r['id'], 'h1': h1, 'n_real': nr,
                     'expected': sorted(spectrum(nr, T))})
            h1_by_nreal.setdefault(nr, {}).setdefault(h1, 0)
            h1_by_nreal[nr][h1] += 1
        cell = classify_cell(r)
        cells[cell] = cells.get(cell, 0) + 1
        if cell == 'INCOHERENT':
            out['violations']['incoherent'].append(r['id'])
    n_null = sum(1 for r in records if r['h1'] is None)
    out['n_h1_null'] = n_null
    out['n_h1_numbered'] = n - n_null
    out['null_cause_strata'] = strata                      # counts; denominator = n_h1_null
    out['h1_distribution_by_n_real'] = {
        str(k): dict(sorted(v.items())) for k, v in sorted(h1_by_nreal.items())}
    out['mcc_coherence_cells'] = cells                     # counts; denominator = n_corpus
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--outdir', default=os.path.join(REPO, 'outputs', 'oq207_census'))
    ap.add_argument('--skip-dump', action='store_true',
                    help='reuse existing census_input_*.json artifacts')
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    T = derive_T()
    print(f"T (real type tokens, derived from code) = {T}")

    if not args.skip_dump:
        dump_all(args.outdir)

    failures = []
    census = {'T': T, 'legs': {}, 'controls': {}}

    for leg in LEGS:
        path = os.path.join(args.outdir, f'census_input_{leg}.json')
        records = json.load(open(path))
        res = assess(records, T)
        census['legs'][leg] = res
        v = res['violations']
        print(f"\n[{leg}] n_corpus={res['n_corpus']} "
              f"numbered={res['n_h1_numbered']} null={res['n_h1_null']} "
              f"(denominators: rates below are over n_corpus={res['n_corpus']})")
        print(f"  null-cause strata (n_in_domain={res['n_h1_null']}): {res['null_cause_strata']}")
        print(f"  mcc cells (n_in_domain={res['n_corpus']}): {res['mcc_coherence_cells']}")
        print(f"  violations: spectrum={len(v['spectrum'])} null_rule={len(v['null_rule'])} "
              f"incoherent={len(v['incoherent'])} table_exhausted={len(res['table_exhausted'])}")
        if v['spectrum'] or v['null_rule'] or v['incoherent']:
            failures.append(f"{leg}: violations {v}")

    # --- control 1: kernel_v1 all-null (negative domain) ---------------------
    kv = json.load(open(os.path.join(args.outdir, 'census_input_kernel_v1.json')))
    bad = [r['id'] for r in kv
           if not (r['h1'] is None and r['h0'] is None and r['n_seats'] == 0
                   and r['n_real'] == 0 and r['verdict'] == 'no_agent_seats')]
    ok1 = not bad
    census['controls']['kernel_v1_all_null'] = {
        'n': len(kv), 'non_null_ids': bad[:5], 'pass': ok1}
    print(f"\n[control] kernel_v1 all-(null,null,0,0): n={len(kv)} "
          f"{'PASS' if ok1 else 'FAIL ' + str(bad[:5])}")
    if not ok1:
        failures.append('kernel_v1_all_null')

    # --- control 2: planted violation on a DOCTORED COPY of the artifact -----
    # (D5/D8: the probe must fire on the artifact it audits, not post-read.)
    src = os.path.join(args.outdir, 'census_input_testsets.json')
    doctored_path = os.path.join(args.outdir, 'census_input_testsets.DOCTORED.json')
    doctored = json.load(open(src))
    target = next((r for r in doctored if isinstance(r['h1'], int)), None)
    if target is None:
        failures.append('planted_control_no_numbered_h1')
        census['controls']['planted_violation'] = {'pass': False,
                                                   'reason': 'no numbered h1 to doctor'}
    else:
        forbidden = 1  # {1..n-2} forbidden at every n >= 3; n_real >= 2 always holds here
        if target['n_real'] < 3:
            forbidden = target['n_real'] * (target['n_real'] - 1) // 2 + 1  # above max
        target['h1'] = forbidden
        with open(doctored_path, 'w') as f:
            json.dump(doctored, f)
        res2 = assess(json.load(open(doctored_path)), T)   # SAME assertion path
        flagged = [s for s in res2['violations']['spectrum'] if s['id'] == target['id']]
        ok2 = bool(flagged)
        census['controls']['planted_violation'] = {
            'doctored_id': target['id'], 'planted_h1': forbidden,
            'n_real': target['n_real'], 'flagged': flagged[:1], 'pass': ok2}
        print(f"[control] planted violation (id={target['id']}, h1->{forbidden} "
              f"at n_real={target['n_real']}): {'FLAGGED - PASS' if ok2 else 'NOT FLAGGED - FAIL'}")
        if not ok2:
            failures.append('planted_violation_not_flagged')

    # --- control 3 (reported, never asserted): zero-seat vs OQ-202 mint ------
    drift = {}
    for leg in LIVE_LEGS:
        now = census['legs'][leg]['null_cause_strata']['no_agent_seats']
        mint = OQ202_MINT_ZERO_SEAT[leg]
        drift[leg] = {'mint': mint, 'now': now, 'drift': now - mint}
    census['controls']['zero_seat_vs_oq202_mint'] = drift
    print(f"[report] zero-seat vs OQ-202 mint strata (drift = finding, not failure): {drift}")

    # --- retired-cell regression gate (OQ-217; successor of the D4 kill
    # condition, which FIRED 2026-07-12 and was resolved by the tightening).
    # The detectors above stay live; any nonzero population here is a
    # regression of the tightening itself and FAILS the census.
    retired = {leg: {c: census['legs'][leg]['mcc_coherence_cells'].get(c, 0)
                     for c in RETIRED_CELLS}
               for leg in LEGS}
    hot = {leg: cells for leg, cells in retired.items()
           if any(v > 0 for v in cells.values())}
    census['retired_cells_gate'] = {
        'counts': retired, 'pass': not hot,
        'provenance': 'D4 kill condition fired 2026-07-12; OQ-217 tightening'}
    print(f"\n[retired-cells gate] (a)/(b)/mixed populations (must all be 0): "
          f"{'PASS' if not hot else 'FAIL ' + str(hot)}")
    if hot:
        failures.append(f'retired_cells_nonzero: {hot}')

    census['verdict'] = 'PASS' if not failures else f'FAIL: {failures}'
    out = os.path.join(args.outdir, 'census.json')
    with open(out, 'w') as f:
        json.dump(census, f, indent=1, sort_keys=True)
    print(f"\ncensus -> {out}\nVERDICT: {census['verdict']}")
    return 0 if not failures else 1


if __name__ == '__main__':
    sys.exit(main())
