#!/usr/bin/env python3
"""oq375_wu_recon.py — the seed adapter for the generic cross-artifact reconciler.

Regenerates, from the two md5-frozen Wu sources, the figures that
`audits/2026-08-10_oq277_rq2_crosscoding/RECON.md` Finding R2 derived BY HAND and
that `docs/amnesiac_institution/amnesiac_institution_v0_6.md` publishes: the
catalog and the labelled dataset share 22 incident IDs and AGREE ON CLASS FOR 12
OF 22 (55% agreement); the remaining 10 disagree.

    .venv/bin/python python/audits/oq375_wu_recon.py --check

Before this existed, Appendix C row 6.2 of the paper recorded that its
agreement figure was "derived by hand ... regenerated by no repository command".
That is what this closes. The library doing the actual join is
`python/shared/recon.py`; the principle is `docs/technical/build_discipline.md`
-> *Cross-artifact reconciliation*. Named `oq375_*`, not `oq277_*`: the
`oq277_` prefix is a PINNED namespace in `python/pattern_citation_check.py`, and
this tool postdates that audit's close.

WHAT IT PARSES, AND WHAT IT REFUSES TO PARSE

  Join inputs -- ONLY these two, both under the freeze pin:
    packets/wu_source/failure_modes_catalog.md      (per-class markdown tables)
    packets/wu_source/llm_observer_ground_truth.yaml (the `cases:` list)

  NOT a join input, ever:
    packets/wu_unit_id_map.json
  That file carries the HAND-DERIVED catalog_class / dataset_class / agreeing
  fields -- it is R2's working, not R2's evidence. Consuming it as input would
  validate this tool against the very artifact it exists to replace: the check
  would pass by construction and could not fail. It is used ONLY as a
  separately-labelled per-unit cross-check, which is a different claim.

THE JOIN KEY IS A FINDING IN ITS OWN RIGHT.
  The two sources do NOT share a literal id space. The dataset's `id` field
  diverges from the catalog's filename for three units (dream_self_referential /
  dream_self_referential_hallucination; movespeed_tcc_sandbox /
  movespeed_tcc_sandbox_blood; finance_zombie_closure /
  zombie_detection_edge_case_closure). What they DO share is the case-document
  FILENAME: the catalog's table cell names it, and the dataset carries it in its
  own `file:` field. Joining on that is mechanical -- no hand mapping required --
  and it is why R2's "the same 22 incident IDs" is true. Unit choice is a ruling
  (build_discipline -> *Cross-artifact reconciliation*); this adapter DECLARES
  the one it made rather than leaving it implicit, and the per-unit cross-check
  against the hand map is what tests it.

WHY A REAL PARSER AND NOT A REGEX OVER PROSE.
  The catalog is a Chinese-language document whose class sections carry both the
  incident tables and unrelated sub-event tables. A prose regex counts the wrong
  rows. This walks the `### Class X` sections and accepts a row only when its
  FIRST cell is a backticked `*.md` filename. Note the filename convention is NOT
  uniform -- one of the 22 ends `_closure.md`, not `_case.md`, and a parser
  keyed on `_case.md` silently reports Class E as 7 instead of 8. That near-miss
  is preserved as control (e) below so the next reader cannot re-introduce it.

NO PyYAML IN THIS ENVIRONMENT, DELIBERATELY UNRESOLVED.
  `python/python_env_check.py` reports the declared import set and yaml is not in
  it. Rather than add a dependency for one file, the dataset is read with a small
  block parser over its regular two-space `cases:` list. It parses STRUCTURE (item
  boundaries and typed field lines), not prose.

EXIT STATUS IS DETERMINED BY PINS AND CONTROLS ONLY.
  The seed pair's own 10 disagreements are the EXPECTED CONDITION, not a failure.
  The fork buckets are REPORTED, never gated: "fork found, ruling owed" is data
  about Wu's sources, and a check that went red on it would be red forever and
  would train its reader to skip it. What CAN go red: a source drifting off its
  recorded md5, a pin no longer reproducing, a per-unit cross-check mismatch, a
  control that failed to discriminate, or a missing source.

WHY THE md5 CHECK LIVES HERE AND NOT IN THE `oq277 freeze` ROW (2026-08-25).
  The plan for this tool specified reading source-drift off the `oq277 freeze`
  gate row's colour: "pins red while oq277 freeze is ALSO RED -> the sources
  moved". THAT BRANCH IS UNREACHABLE. `oq277_build_prereg.py` is post-freeze; it
  verifies PREREGISTRATION.md against its recorded stamp and reports pinned-SOURCE
  drift as INFO with exit 0 -- by explicit design, because a permanently-red row
  trains its reader to route around it. Witnessed 2026-08-25: two pinned sources
  (CLAUDE.md, build_discipline.md) are currently drifted and that row prints GREEN.
  So a colour cross-read would have diagnosed EVERY pin failure as "the instrument
  changed", including the one case where the sources really had moved -- inverting
  the discrimination in exactly the situation it was built for. This tool
  therefore checks the two md5s ITSELF, against the pins recorded in the frozen
  PREREGISTRATION.md, making both branches reachable without depending on another
  row's exit code.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from shared.recon import reconcile, render_report, DuplicateUnitIDs  # noqa: E402
from shared import recon as recon_lib  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
AUDIT = REPO / "audits" / "2026-08-10_oq277_rq2_crosscoding"
CATALOG = AUDIT / "packets" / "wu_source" / "failure_modes_catalog.md"
DATASET = AUDIT / "packets" / "wu_source" / "llm_observer_ground_truth.yaml"
HAND_MAP = AUDIT / "packets" / "wu_unit_id_map.json"
PREREG = AUDIT / "PREREGISTRATION.md"

# --- PINS: RECON.md Finding R2, re-verified against that file 2026-08-25. -------
# These are a REGRESSION BASELINE, adjudicated on first run (2026-08-25: the
# machine parse reproduced every one, aggregate and per-unit). If one goes red,
# fix the instrument -- never edit a pin to match a new parse.
PIN_SHARED = 22
PIN_AGREE = 12
PIN_DISAGREE = 10
PIN_MARGINALS_CATALOG = {"A": 1, "B": 4, "C": 5, "D": 4, "E": 8}
PIN_MARGINALS_DATASET = {"A": 4, "B": 3, "C": 4, "D": 5, "E": 6}

# md5s as recorded in the FROZEN PREREGISTRATION.md Appendix A pin table.
PIN_MD5 = {
    "failure_modes_catalog.md": "f854454ed2be5bf489f2c5ee133ce013",
    "llm_observer_ground_truth.yaml": "f26359b2d9f98b6b310aed9b473a1395",
}

CLASS_HEADING = re.compile(r"^###\s+Class\s+([A-E])\b")
ANY_H2 = re.compile(r"^##\s")
TABLE_ID_CELL = re.compile(r"^`([A-Za-z0-9_]+\.md)`")
YAML_ITEM = re.compile(r"^  - id:\s*(\S+)\s*$")
YAML_FIELD = re.compile(r"^    (\w+):\s*(.*?)\s*$")


class MissingSource(FileNotFoundError):
    """A frozen source is absent. Fail closed -- never treat as 'nothing to compare'."""


def _read(p: Path) -> str:
    if not p.exists():
        raise MissingSource(f"frozen source missing: {p.relative_to(REPO)}")
    return p.read_text(encoding="utf-8")


def parse_catalog(text: str) -> list[tuple[str, dict]]:
    """`### Class X` sections -> [(case_filename, {'cls': X}), ...] as PAIRS.

    Pairs, not a dict: a duplicated filename across two class sections is exactly
    the kind of source defect the reconciler must be able to refuse, and a dict
    here would swallow it before the library ever saw it.
    """
    out: list[tuple[str, dict]] = []
    cls: str | None = None
    for line in text.splitlines():
        m = CLASS_HEADING.match(line)
        if m:
            cls = m.group(1)
            continue
        if ANY_H2.match(line):
            cls = None
        if cls and line.startswith("|"):
            cells = line.split("|")
            if len(cells) < 2:
                continue
            fm = TABLE_ID_CELL.match(cells[1].strip())
            if fm:
                out.append((fm.group(1), {"cls": cls}))
    return out


def parse_dataset(text: str) -> tuple[list[tuple[str, dict]], list[str]]:
    """The `cases:` list -> ([(case_filename, {'cls': ...}), ...], no_file_ids).

    Only `paper_canonical: true` rows join: the dataset carries 24 labelled
    incidents of which 22 are inside the paper's study cutoff, and the other two
    are post-cutoff additions the catalog cannot carry. Rows with NO `file:` field
    (the documented `D4_fabricated_release` known-gap row, which has no
    independent case document) are returned separately and reported as absent on
    one side -- never dropped silently, never coerced into a class.
    """
    cases: list[dict] = []
    cur: dict | None = None
    for line in text.splitlines():
        m = YAML_ITEM.match(line)
        if m:
            cur = {"id": m.group(1)}
            cases.append(cur)
            continue
        if cur is None:
            continue
        m = YAML_FIELD.match(line)
        if m and m.group(1) in ("file", "taxonomy_class", "paper_canonical"):
            cur[m.group(1)] = m.group(2).strip('"')
    pairs: list[tuple[str, dict]] = []
    no_file: list[str] = []
    for c in cases:
        if "file" not in c:
            no_file.append(c["id"])
            continue
        if c.get("paper_canonical") != "true":
            continue
        pairs.append((c["file"].rsplit("/", 1)[-1],
                      {"cls": c.get("taxonomy_class"), "dataset_id": c["id"]}))
    return pairs, no_file


def _fmt_marg(c: Counter | dict) -> str:
    return "/".join(f"{k}{c.get(k, 0)}" for k in "ABCDE")


def run_join(catalog_text: str, dataset_text: str, *, label_a="catalog",
             label_b="dataset"):
    cat_pairs = parse_catalog(catalog_text)
    ds_pairs, no_file = parse_dataset(dataset_text)
    r = reconcile(cat_pairs, ds_pairs, ["cls"], label_a=label_a, label_b=label_b)
    return r, cat_pairs, ds_pairs, no_file


# --------------------------------------------------------------------------
# CONTROLS. Every fixture below is GENERATED AT RUN TIME by mutating the frozen
# source text IN MEMORY. Nothing is checked in and nothing is written anywhere
# near packets/wu_source/. A checked-in fixture copy rots silently when the
# sources change, leaving the control passing against a document that no longer
# resembles its input -- a control that cannot fail, which is the defect this
# whole arc is about.
# --------------------------------------------------------------------------

def control_planted_agreement(cat_text: str) -> tuple[bool, str]:
    """One source joined against ITSELF must yield zero disagreements."""
    pairs = parse_catalog(cat_text)
    r = reconcile(pairs, list(pairs), ["cls"], label_a="cat", label_b="cat'")
    fr = r.per_field["cls"]
    ok = not fr.disagree and len(r.shared) == len(set(p[0] for p in pairs))
    return ok, (f"self-join: {len(r.shared)} shared, {len(fr.disagree)} disagreements "
                f"(want 0)")


def control_planted_disagreement(cat_text: str) -> tuple[bool, str]:
    """Mutate ONE catalog row's class; the tool must NAME that unit.

    Going red is not enough. A detector that fires without localising is
    indistinguishable from one that always fires.
    """
    pairs = parse_catalog(cat_text)
    target = pairs[0][0]
    mutated = [(u, dict(rec)) for u, rec in pairs]
    orig = mutated[0][1]["cls"]
    mutated[0] = (target, {"cls": "Z"})
    r = reconcile(pairs, mutated, ["cls"], label_a="cat", label_b="cat-mut")
    d = r.per_field["cls"].disagree
    ok = len(d) == 1 and d[0][0] == target and d[0][1] == orig and d[0][2] == "Z"
    return ok, (f"mutated {target} {orig}->Z; tool named "
                f"{d[0][0] if d else '<nothing>'} ({len(d)} disagreement(s), want 1)")


def control_parser_discrimination(cat_text: str, ds_text: str) -> tuple[bool, str]:
    """Each PARSER must notice a class edited in its own raw source text.

    Distinct from the control above: that one mutates the parsed structure, this
    one mutates the DOCUMENT and asks whether the parser carries the change
    through. A parser that silently skipped the edited row would pass the first
    control and fail this one.
    """
    notes = []
    ok = True

    cat_pairs = parse_catalog(cat_text)
    tgt = "movespeed_tcc_sandbox_blood_case.md"
    before = dict(cat_pairs)[tgt]["cls"]
    # move the row's whole line out of Class E into Class A by relocating it
    lines = cat_text.splitlines()
    row = next(l for l in lines if l.startswith(f"| `{tgt}`"))
    lines.remove(row)
    aidx = next(i for i, l in enumerate(lines) if CLASS_HEADING.match(l)
                and CLASS_HEADING.match(l).group(1) == "A")
    tidx = next(i for i in range(aidx, len(lines)) if lines[i].startswith("|"))
    lines.insert(tidx + 2, row)
    after = dict(parse_catalog("\n".join(lines))).get(tgt, {}).get("cls")
    good = before == "E" and after == "A"
    ok &= good
    notes.append(f"catalog parser: {tgt} {before}->{after} after moving its row "
                 f"to Class A (want E->A)")

    ds_pairs, _ = parse_dataset(ds_text)
    dtgt = "preflight_cascading_fix_case.md"
    dbefore = dict(ds_pairs)[dtgt]["cls"]
    # edit that case's taxonomy_class in the raw YAML
    dl = ds_text.splitlines()
    i = next(i for i, l in enumerate(dl) if l == "  - id: preflight_cascading_fix")
    j = next(j for j in range(i, len(dl)) if dl[j].startswith("    taxonomy_class:"))
    dl[j] = "    taxonomy_class: Q"
    dafter = dict(parse_dataset("\n".join(dl))[0]).get(dtgt, {}).get("cls")
    dgood = dbefore == "E" and dafter == "Q"
    ok &= dgood
    notes.append(f"dataset parser: {dtgt} {dbefore}->{dafter} after editing its "
                 f"taxonomy_class (want E->Q)")

    return ok, "; ".join(notes)


def control_case_md_nearmiss(cat_text: str) -> tuple[bool, str]:
    """The preserved near-miss: a `_case.md`-keyed parser undercounts Class E.

    Recorded as a control because it actually happened while building this tool
    (Class E parsed as 7, not 8) and because it is a FREE NEGATIVE CONTROL: the
    defective criterion is known, so we can assert it declines where the correct
    one fires, rather than only asserting the correct one fires.
    """
    narrow = re.compile(r"^`([A-Za-z0-9_]+)_case\.md`")
    cls, n_narrow = None, Counter()
    for line in cat_text.splitlines():
        m = CLASS_HEADING.match(line)
        if m:
            cls = m.group(1); continue
        if ANY_H2.match(line):
            cls = None
        if cls and line.startswith("|"):
            cells = line.split("|")
            if len(cells) >= 2 and narrow.match(cells[1].strip()):
                n_narrow[cls] += 1
    wide = Counter(rec["cls"] for _, rec in parse_catalog(cat_text))
    ok = n_narrow["E"] == 7 and wide["E"] == 8 and sum(wide.values()) == 22
    return ok, (f"`_case.md`-keyed criterion gives E={n_narrow['E']} (total "
                f"{sum(n_narrow.values())}); the `*.md` criterion gives E={wide['E']} "
                f"(total {sum(wide.values())}) -- want 7 vs 8, and 22 total")


def control_missing_source() -> tuple[bool, str]:
    """A missing frozen source must FAIL CLOSED, not read as 'nothing to compare'."""
    try:
        _read(AUDIT / "packets" / "wu_source" / "does_not_exist.md")
        return False, "reading an absent source did NOT raise"
    except MissingSource:
        return True, "absent source raises MissingSource (fail-closed)"


def check(verbose: bool = True) -> int:
    """All components run and report INDEPENDENTLY -- no fail-fast masking."""
    reds: list[str] = []
    out = print if verbose else (lambda *a, **k: None)

    out("=" * 78)
    out("OQ-375 — cross-artifact reconciliation of the two frozen Wu sources")
    out("=" * 78)

    # --- 0. source freeze, checked HERE (see the module docstring). -------------
    out("\n[0] SOURCE FREEZE (md5 vs the pins recorded in the frozen PREREGISTRATION.md)")
    for p in (CATALOG, DATASET):
        if not p.exists():
            reds.append(f"source missing: {p.name}")
            out(f"  RED   {p.name}: MISSING — fail closed")
            continue
        got = hashlib.md5(p.read_bytes()).hexdigest()
        want = PIN_MD5[p.name]
        if got == want:
            out(f"  ok    {p.name}  md5 {got}")
        else:
            reds.append(f"source drifted: {p.name}")
            out(f"  RED   {p.name}: md5 {got} != recorded {want}")
            out(f"        THE SOURCES MOVED. Re-adjudicate against RECON.md before "
                f"touching the parser or the pins.")
    if reds:
        out("\n  Aborting the join: a drifted or missing source makes every figure "
            "below\n  uninterpretable. This is the fail-closed branch, not a parse "
            "failure.")
        out("\nwu recon: RED — source freeze broken")
        return 1

    cat_text, ds_text = _read(CATALOG), _read(DATASET)

    # --- 1. the join + aggregate pins -------------------------------------------
    out("\n[1] THE JOIN")
    try:
        r, cat_pairs, ds_pairs, no_file = run_join(cat_text, ds_text)
    except DuplicateUnitIDs as e:
        out(f"  RED   duplicate unit ids in a source: {e}")
        out("\nwu recon: RED — duplicate unit ids (a FINDING about the sources)")
        return 1
    fr = r.per_field["cls"]
    out(render_report(r, unit_noun="incident"))
    if no_file:
        out(f"\n  absent-on-one-side (dataset rows with no case document, reported "
            f"not dropped): {', '.join(no_file)}")

    out("\n[1b] AGGREGATE PINS (RECON.md Finding R2)")
    mc = {k: r.marginals_a['cls'].get(k, 0) for k in "ABCDE"}
    md = {k: r.marginals_b['cls'].get(k, 0) for k in "ABCDE"}
    for name, got, want in (
        ("shared incidents", len(r.shared), PIN_SHARED),
        ("agree on class", len(fr.agree), PIN_AGREE),
        ("disagree on class", len(fr.disagree), PIN_DISAGREE),
    ):
        okk = got == want
        out(f"  {'ok   ' if okk else 'RED  '} {name}: {got} (pin {want})")
        if not okk:
            reds.append(f"pin {name}: {got} != {want}")
    for name, got, want in (("catalog marginals", mc, PIN_MARGINALS_CATALOG),
                            ("dataset marginals", md, PIN_MARGINALS_DATASET)):
        okk = got == want
        out(f"  {'ok   ' if okk else 'RED  '} {name}: {_fmt_marg(got)} "
            f"(pin {_fmt_marg(want)})")
        if not okk:
            reds.append(f"pin {name}")

    # --- 2. per-unit cross-check vs the HAND-DERIVED map (ASSERTED) -------------
    out("\n[2] PER-UNIT HAND-DERIVATION CROSS-CHECK vs packets/wu_unit_id_map.json")
    out("    Separately labelled: the map is R2's WORKING, never a join input.")
    out("    ASSERTED, not reporting-only. Compensating per-unit errors leave every")
    out("    aggregate above identical, and the map is NOT under the freeze pin, so")
    out("    this assertion is its only watcher.")
    if not HAND_MAP.exists():
        reds.append("hand map missing")
        out("  RED   wu_unit_id_map.json MISSING — fail closed")
    else:
        hm = json.loads(HAND_MAP.read_text(encoding="utf-8"))
        by_id = {row["source_id"]: row for row in hm["map"]}
        ds_by_file = dict(ds_pairs)
        cat_by_file = dict(cat_pairs)
        n_ok = 0
        for fname in r.shared:
            did = ds_by_file[fname]["dataset_id"]
            row = by_id.get(did)
            if row is None:
                reds.append(f"map has no row for {did}")
                out(f"  RED   no map row for dataset id {did} ({fname})")
                continue
            pc, pd = cat_by_file[fname]["cls"], ds_by_file[fname]["cls"]
            if row["catalog_class"] != pc or row["dataset_class"] != pd:
                reds.append(f"map/parse mismatch at {did}")
                out(f"  RED   {did}: map {row['catalog_class']}/{row['dataset_class']} "
                    f"vs parse {pc}/{pd}")
            elif row["agreeing"] != (pc == pd):
                reds.append(f"map agreeing bit wrong at {did}")
                out(f"  RED   {did}: map agreeing={row['agreeing']} vs parse "
                    f"{pc == pd}")
            else:
                n_ok += 1
        extra = set(by_id) - {ds_by_file[f]["dataset_id"] for f in r.shared}
        if extra:
            reds.append("map carries rows the join does not")
            out(f"  RED   map rows not reached by the join: {sorted(extra)}")
        out(f"  {'ok   ' if n_ok == len(r.shared) else 'RED  '} "
            f"{n_ok} of {len(r.shared)} units match the hand derivation on BOTH "
            f"class fields and the agreeing bit")

    # --- 3. controls -------------------------------------------------------------
    out("\n[3] CONTROLS (fixtures GENERATED AT RUN TIME from the frozen sources;")
    out("    nothing checked in, nothing written near packets/wu_source/)")
    controls = [
        ("(a) planted agreement", lambda: control_planted_agreement(cat_text)),
        ("(b) planted disagreement (must NAME the unit)",
         lambda: control_planted_disagreement(cat_text)),
        ("(c) parser-level discrimination, both parsers",
         lambda: control_parser_discrimination(cat_text, ds_text)),
        ("(d) preserved near-miss: `_case.md` criterion undercounts Class E",
         lambda: control_case_md_nearmiss(cat_text)),
        ("(e) missing source fails closed", control_missing_source),
    ]
    for name, fn in controls:
        try:
            okk, note = fn()
        except Exception as exc:                      # a control that errors is red
            okk, note = False, f"raised {type(exc).__name__}: {exc}"
        out(f"  {'ok   ' if okk else 'RED  '} {name}\n         {note}")
        if not okk:
            reds.append(f"control failed: {name}")

    out("\n[4] LIBRARY SELFTEST (python/shared/recon.py — the join algebra)")
    lib_rc = recon_lib.selftest(verbose=False)
    out(f"  {'ok   ' if lib_rc == 0 else 'RED  '} recon.selftest()")
    if lib_rc:
        reds.append("recon library selftest failed")

    out("")
    if reds:
        out(f"wu recon: RED — {len(reds)} problem(s): " + "; ".join(reds[:4])
            + (" ..." if len(reds) > 4 else ""))
        return 1
    # Round, never floor: 12/22 = 54.5%, and the figure of record (RECON.md R2,
    # the paper, comparing_incident_taxonomies.md Rule 1) is 55%. Integer floor
    # division prints 54% and quietly contradicts every citing text.
    out(f"wu recon: GREEN — {PIN_SHARED} shared incidents, {PIN_AGREE} agree "
        f"({100*PIN_AGREE/PIN_SHARED:.0f}% agreement) / {PIN_DISAGREE} disagree; "
        f"marginals + per-unit hand cross-check reproduce; controls 5/5 + library "
        f"selftest. The 10 disagreements are the EXPECTED condition (fork found, "
        f"ruling owed), not a failure.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="run the full check (pins, per-unit cross-check, controls)")
    ap.add_argument("--report", action="store_true",
                    help="print the reconciliation report only")
    a = ap.parse_args()
    if a.report:
        r, *_ = run_join(_read(CATALOG), _read(DATASET))
        print(render_report(r, unit_noun="incident"))
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main())
