:- module(domain_registry, [domain_category/2]).
% --- AUTOMATICALLY GENERATED DOMAIN REGISTRY ---
% Maps both Constraint IDs and Interval IDs to categories.

domain_category(ac_era, narrative_history).
domain_category(academic_peer_review_gatekeeping, extractive_market).
domain_category(academic_tenure_system, extractive_market).
domain_category(ad_fus_coordination, extractive_market).
domain_category(ad_synaptic_deficit, extractive_market).
domain_category(adverse_possession, extractive_market).
domain_category(adverse_possession_interval, extractive_market).
domain_category(advice_as_dangerous_gift, narrative_history).
domain_category(aging_longevity_tests, narrative_history).
domain_category(ai_cognitive_diversity_arbitrage, extractive_market).
domain_category(ai_driven_surveillance_sensor_layer, extractive_market).
domain_category(ai_edu_decentralization, narrative_history).
domain_category(ai_evaluators_matching, extractive_market).
domain_category(ai_professional_displacement, extractive_market).
domain_category(ai_task_horizon_reliability, narrative_history).
domain_category(airbnb_ipo_era, narrative_history).
domain_category(airbnb_str_regulation, narrative_history).
domain_category(algorithmic_bias, extractive_market).
domain_category(amish_technological_renunciation, extractive_market).
domain_category(ancestral_pueblo_hydrology, extractive_market).
domain_category(ancient_grudge_verona, extractive_market).
domain_category(antifragility, extractive_market).
domain_category(apartheid_nuclear_program, extractive_market).
domain_category(arctic_geopolitical_flashpoint, extractive_market).
domain_category(arrows_era, narrative_history).
domain_category(arrows_impossibility_theorem, narrative_history).
domain_category(asce_7_22_seismic_design, narrative_history).
domain_category(asce_cycle_22, narrative_history).
domain_category(asshole_filter_2015, extractive_market).
domain_category(astm_d638_tensile_testing, narrative_history).
domain_category(atsumono_period, extractive_market).
domain_category(authoritarian_power_paradox, extractive_market).
domain_category(automatic_enrollment_defaults, narrative_history).
domain_category(availability_heuristic, narrative_history).
domain_category(axiom_of_choice_determinacy, narrative_history).
domain_category(banach_era, narrative_history).
domain_category(banach_fixed_point, narrative_history).
domain_category(banach_tarski_era, narrative_history).
domain_category(banach_tarski_paradox, narrative_history).
domain_category(base_pair_complementarity, narrative_history).
domain_category(basel_era, narrative_history).
domain_category(basel_problem_convergence, narrative_history).
domain_category(bay_of_pigs_operational_silo, extractive_market).
domain_category(bedouin_sedentary_transition, extractive_market).
domain_category(belief_argument_conclusion, extractive_market).
domain_category(belief_argument_conclusion_interval, extractive_market).
domain_category(berkshire_compounding_culture, narrative_history).
domain_category(big_data_astrophysics_arbitrage, extractive_market).
domain_category(biological_curiosity, narrative_history).
domain_category(bip_narrative_illusion, extractive_market).
domain_category(bip_narrative_illusion_interval, extractive_market).
domain_category(birthday_era, narrative_history).
domain_category(birthday_paradox_collision, narrative_history).
domain_category(blackstone_carried_interest_taxation, narrative_history).
domain_category(blackstone_conflict_era, extractive_market).
domain_category(blackstone_conflicts_of_interest, extractive_market).
domain_category(blackstone_ipo_restructuring, narrative_history).
domain_category(blackstone_smd_control, extractive_market).
domain_category(blackstone_tra, extractive_market).
domain_category(blackstone_tra_life, extractive_market).
domain_category(bloom_acoustic_seduction_vigil, narrative_history).
domain_category(bloom_aeolus_advertisement_circuit, narrative_history).
domain_category(bloom_aeolus_interval, narrative_history).
domain_category(bloom_exclusion_id, narrative_history).
domain_category(bloom_exclusion_interval, narrative_history).
domain_category(bloom_ithaca_interval, narrative_history).
domain_category(bloom_ithaca_mathematical_order, narrative_history).
domain_category(bloom_kosher_transgression, narrative_history).
domain_category(bloom_samaritan_id, narrative_history).
domain_category(bloom_samaritan_paternal_care, narrative_history).
domain_category(bloom_secret_correspondence, narrative_history).
domain_category(bloom_sirens_interval, narrative_history).
domain_category(bloom_social_exclusion_dublin, narrative_history).
domain_category(bloom_xenophobic_exclusion, narrative_history).
domain_category(brain_network_paradigm_2026, narrative_history).
domain_category(broke_vs_poor_grocery_math, extractive_market).
domain_category(brouwer_era, narrative_history).
domain_category(brouwer_fixed_point, narrative_history).
domain_category(buffon_era, narrative_history).
domain_category(buffons_needle_pi_estimation, narrative_history).
domain_category(burali_forti_interval, narrative_history).
domain_category(burali_forti_paradox, narrative_history).
domain_category(burden_of_proof_engineering_safety, extractive_market).
domain_category(burden_of_proof_legal_criminal, narrative_history).
domain_category(burden_of_proof_scientific_empirical, narrative_history).
domain_category(bushman_money_magic, extractive_market).
domain_category(bushman_money_magic_interval, extractive_market).
domain_category(busy_beaver_era, narrative_history).
domain_category(busy_beaver_noncomputability, narrative_history).
domain_category(cantor_set_topology, narrative_history).
domain_category(cap_theorem, narrative_history).
domain_category(cap_theorem_interval, narrative_history).
domain_category(capture_interval, extractive_market).
domain_category(carbon_credit_markets_2026, narrative_history).
domain_category(carbon_credit_markets_2026_int, narrative_history).
domain_category(carrying_capacity, extractive_market).
domain_category(carrying_capacity_interval, extractive_market).
domain_category(castration_longevity_choice, extractive_market).
domain_category(cbdc_deployment, extractive_market).
domain_category(cbdc_implementation, extractive_market).
domain_category(celestial_mechanics_era, narrative_history).
domain_category(central_limit_theorem_convergence, narrative_history).
domain_category(cfsg_era, narrative_history).
domain_category(chaitin_era, narrative_history).
domain_category(chaitins_omega_undecidability, narrative_history).
domain_category(challenger_launch_decision, extractive_market).
domain_category(challenger_o_ring_integrity, extractive_market).
domain_category(challenger_post_mortem, extractive_market).
domain_category(china_critical_mineral_chokepoint, extractive_market).
domain_category(china_taiwan_reunification_mandate, extractive_market).
domain_category(church_turing_era, narrative_history).
domain_category(church_turing_thesis, narrative_history).
domain_category(cia_fbi_legal_wall, extractive_market).
domain_category(click_chemistry_paradigm_2026, narrative_history).
domain_category(climate_attribution_2026, narrative_history).
domain_category(climate_target_one_point_five, narrative_history).
domain_category(cloudflare_dual_class_asymmetry, extractive_market).
domain_category(clt_era, narrative_history).
domain_category(cobra_effect, narrative_history).
domain_category(cognitive_diversity_arbitrage, extractive_market).
domain_category(cognitive_induction_gap, extractive_market).
domain_category(cognitive_mimicry_arbitrage, extractive_market).
domain_category(cognitive_surrender_to_system_3, extractive_market).
domain_category(coinbase_crypto_volatility, narrative_history).
domain_category(coinbase_ipo_window, narrative_history).
domain_category(coinbase_regulatory_uncertainty, extractive_market).
domain_category(collatz_conjecture_determinism, narrative_history).
domain_category(collatz_era, narrative_history).
domain_category(college_admissions_market, extractive_market).
domain_category(colombia_2026_presidential_election, narrative_history).
domain_category(colorado_sbe_decentralization_friction, extractive_market).
domain_category(comitatus_bond, narrative_history).
domain_category(comitatus_era, narrative_history).
domain_category(compounding_logic, narrative_history).
domain_category(confirmation_bias, narrative_history).
domain_category(confirmation_bias_interval, narrative_history).
domain_category(constitutional_consecration, narrative_history).
domain_category(constitutional_supremacy, narrative_history).
domain_category(continuum_era, narrative_history).
domain_category(continuum_hypothesis_undecidability, narrative_history).
domain_category(conversational_dogmas_interruption, narrative_history).
domain_category(conway_era, narrative_history).
domain_category(conways_game_of_life_dynamics, narrative_history).
domain_category(copyleft_viral_licensing, narrative_history).
domain_category(copyright_protection, narrative_history).
domain_category(cost_of_observation, extractive_market).
domain_category(countable_infinity_cardinality, narrative_history).
domain_category(couples_residency_match, narrative_history).
domain_category(cow_field_poop, narrative_history).
domain_category(creative_commons_licensing, narrative_history).
domain_category(credentialing_shift_2026, extractive_market).
domain_category(criminal_trial_sequence, narrative_history).
domain_category(crispr_genomic_rewrite_2026, narrative_history).
domain_category(cuba_blackout_cycle, extractive_market).
domain_category(cuba_mandatrophic_collapse, extractive_market).
domain_category(cuban_missile_crisis_excomm_deliberation, narrative_history).
domain_category(currys_paradox, narrative_history).
domain_category(currys_paradox_interval, narrative_history).
domain_category(damped_harmonics, narrative_history).
domain_category(dark_patterns_manipulation, extractive_market).
domain_category(dead_sea_effect, narrative_history).
domain_category(deferential_realism_framework, narrative_history).
domain_category(dexy_gold_interval, narrative_history).
domain_category(dexy_gold_protocol, narrative_history).
domain_category(digital_credentialing_verification, extractive_market).
domain_category(diminishing_returns_interval, narrative_history).
domain_category(dionysiac_frenzy, extractive_market).
domain_category(dionysiac_frenzy_interval, extractive_market).
domain_category(dldr_information_policy, narrative_history).
domain_category(dldr_policy_interval, narrative_history).
domain_category(dna_structure_discovery, narrative_history).
domain_category(dprk_songun_cycle, extractive_market).
domain_category(dr_recursive_int, narrative_history).
domain_category(dual_masters_dublin_1904, extractive_market).
domain_category(dunbar_interval, narrative_history).
domain_category(dunbars_number, narrative_history).
domain_category(dunning_kruger_effect, narrative_history).
domain_category(e2ee_digital_privacy_2026, narrative_history).
domain_category(education_unbundling_implementation, narrative_history).
domain_category(ek_robot_integration_cycle, narrative_history).
domain_category(electrification_scale_2026, narrative_history).
domain_category(elencher_identity_transformation, narrative_history).
domain_category(em_clinical_guidelines, narrative_history).
domain_category(em_practice_v2, narrative_history).
domain_category(empty_tomb_transformation, narrative_history).
domain_category(endowment_effect, narrative_history).
domain_category(endowment_interval, narrative_history).
domain_category(epigenetics_complexity_2026, narrative_history).
domain_category(ergo_autolykos_asic_resistance, narrative_history).
domain_category(ergo_lets_interval, narrative_history).
domain_category(ergo_lets_protocol, narrative_history).
domain_category(ergo_mixer_protocol, narrative_history).
domain_category(ergo_nipopows, narrative_history).
domain_category(ergo_storage_rent, narrative_history).
domain_category(ergo_storage_rent_mechanism, narrative_history).
domain_category(ergodic_interval, narrative_history).
domain_category(ergodic_theorems, narrative_history).
domain_category(ergot_grain_poisoning, extractive_market).
domain_category(ergot_grain_poisoning_interval, extractive_market).
domain_category(erised_expectation, extractive_market).
domain_category(euler_characteristic_topology, narrative_history).
domain_category(euler_era, narrative_history).
domain_category(evolutionary_pressure_01, extractive_market).
domain_category(exoplanetary_habitability_arbitrage, narrative_history).
domain_category(exploration_vs_exploitation, narrative_history).
domain_category(extraordinary_narrative_shift, narrative_history).
domain_category(factional_instability, extractive_market).
domain_category(faint_blue_neural_bifurcation, extractive_market).
domain_category(fair_use_doctrine, narrative_history).
domain_category(family_estrangement_ratio, extractive_market).
domain_category(family_succession_system, extractive_market).
domain_category(fast_growing_hierarchy, narrative_history).
domain_category(fbc_era_operations, extractive_market).
domain_category(federalist_10_analysis, extractive_market).
domain_category(feigenbaum_universality, narrative_history).
domain_category(finite_pool_of_worry, extractive_market).
domain_category(finite_pool_of_worry_interval, extractive_market).
domain_category(finite_simple_group_classification, narrative_history).
domain_category(fittss_law, narrative_history).
domain_category(fittss_law_interval, narrative_history).
domain_category(fmeca_procedures_1980, narrative_history).
domain_category(fmeca_standard_era, narrative_history).
domain_category(four_color_era, narrative_history).
domain_category(four_color_theorem_topological_bound, narrative_history).
domain_category(framing_effect, narrative_history).
domain_category(framing_effect_interval, narrative_history).
domain_category(frankenstein_creation_hubris, extractive_market).
domain_category(fta_era, narrative_history).
domain_category(fundamental_theorem_of_algebra, narrative_history).
domain_category(galactic_selection_event, extractive_market).
domain_category(gale_shapley, extractive_market).
domain_category(galois_era, narrative_history).
domain_category(galois_theory_symmetry, narrative_history).
domain_category(gamblers_ruin_stochastic_extinction, extractive_market).
domain_category(game_theory_era, extractive_market).
domain_category(gauss_bonnet_era, narrative_history).
domain_category(gauss_bonnet_topology, narrative_history).
domain_category(generational_replacement_inertia, extractive_market).
domain_category(genetic_algorithms_evolution, narrative_history).
domain_category(genetic_predisposition, narrative_history).
domain_category(genetic_predisposition_interval, narrative_history).
domain_category(germline_regulation_threshold_2026, narrative_history).
domain_category(gerty_bloom_interval, narrative_history).
domain_category(gerty_bloom_voyeuristic_distance, narrative_history).
domain_category(gestation_the_wombfruit, narrative_history).
domain_category(gestation_wombfruit_id, narrative_history).
domain_category(gettysburg_address_analysis, narrative_history).
domain_category(gig_economy_algorithmic_management, extractive_market).
domain_category(gilgamesh_epic_cycle, extractive_market).
domain_category(gilgamesh_mortality_limit, extractive_market).
domain_category(gita_kurukshetra, narrative_history).
domain_category(gln_standard_lifecycle, narrative_history).
domain_category(global_stimulus_spree, extractive_market).
domain_category(global_water_bankruptcy, extractive_market).
domain_category(glp1_market_impact_2026, narrative_history).
domain_category(glp1_payload_efficiency_pivot, narrative_history).
domain_category(goedel_era, narrative_history).
domain_category(goedels_incompleteness_theorems, narrative_history).
domain_category(goldbach_conjecture, narrative_history).
domain_category(goldbach_era, narrative_history).
domain_category(golden_handcuffs, narrative_history).
domain_category(goodharts_law, narrative_history).
domain_category(goodharts_law_interval, narrative_history).
domain_category(gradient_descent_optimization, narrative_history).
domain_category(graph_coloring_complexity, narrative_history).
domain_category(graph_coloring_interval, narrative_history).
domain_category(greenland_crisis_2026, extractive_market).
domain_category(greenland_seizure_trade_war, extractive_market).
domain_category(greshams_law, narrative_history).
domain_category(grete_samsa_transition, narrative_history).
domain_category(gs1_gln_identification, narrative_history).
domain_category(gs1_spec_v25, narrative_history).
domain_category(gs1_standardized_identification, narrative_history).
domain_category(halting_era, narrative_history).
domain_category(halting_problem_undecidability, narrative_history).
domain_category(hamiltonian_path_complexity, narrative_history).
domain_category(hammurabi_lex_talionis, narrative_history).
domain_category(hanlons_razor, narrative_history).
domain_category(happiness_of_others, extractive_market).
domain_category(harm_principle_liberty, narrative_history).
domain_category(hawthorne_effect, narrative_history).
domain_category(hawthorne_interval, narrative_history).
domain_category(hegemony_transition_window, extractive_market).
domain_category(heisenberg_interval, narrative_history).
domain_category(heisenberg_uncertainty, narrative_history).
domain_category(helsinki_bus_theory, narrative_history).
domain_category(heuristic_optimization, narrative_history).
domain_category(hilberts_hotel_infinity, narrative_history).
domain_category(history_nightmare_1904, extractive_market).
domain_category(hiv_prep_prevention_2026, narrative_history).
domain_category(hoa_architectural_covenants, narrative_history).
domain_category(hoa_interval, narrative_history).
domain_category(hominin_evolutionary_bottleneck, extractive_market).
domain_category(hp_liberalism, narrative_history).
domain_category(hydra_game, extractive_market).
domain_category(hydra_interval, extractive_market).
domain_category(implementation_window_2026, narrative_history).
domain_category(indexical_relativity_core, narrative_history).
domain_category(industrial_testing_regime, narrative_history).
domain_category(information_foraging_theory, narrative_history).
domain_category(inner_model_era, narrative_history).
domain_category(inner_model_theory_constraints, narrative_history).
domain_category(innovators_dilemma, narrative_history).
domain_category(innovators_dilemma_interval, narrative_history).
domain_category(institutional_mutation_domestication, extractive_market).
domain_category(insult_wisdom_interval, extractive_market).
domain_category(insult_wisdom_training, extractive_market).
domain_category(integrated_digital_governance_stack, extractive_market).
domain_category(interstellar_quantum_link, narrative_history).
domain_category(iran_mandatrophic_collapse, extractive_market).
domain_category(iran_unrest_2025, extractive_market).
domain_category(iron_law_of_oligarchy, narrative_history).
domain_category(japan_gx_transition, narrative_history).
domain_category(japanese_energy_scaffold_2025, narrative_history).
domain_category(jevons_interval, narrative_history).
domain_category(jevons_paradox, narrative_history).
domain_category(job_hunt_volume_system_2026, extractive_market).
domain_category(keltner_relationship_evaluation, narrative_history).
domain_category(khantivadin_patience_interval, extractive_market).
domain_category(khantivadin_radical_patience, extractive_market).
domain_category(kidney_exchange_market, narrative_history).
domain_category(kirby_paris_interval, narrative_history).
domain_category(kirby_paris_theorem, narrative_history).
domain_category(kjv_great_awakening, narrative_history).
domain_category(kjv_linguistic_residue, narrative_history).
domain_category(kjv_puritan_new_world_exit, narrative_history).
domain_category(kjv_textual_authority, narrative_history).
domain_category(kleene_era, narrative_history).
domain_category(kleene_recursion_theorem, narrative_history).
domain_category(labor_management_conflict_r1, narrative_history).
domain_category(landscape_of_fear_2026, narrative_history).
domain_category(large_cardinal_era, narrative_history).
domain_category(large_cardinal_foundations, narrative_history).
domain_category(law_of_diminishing_returns, narrative_history).
domain_category(layered_brain_processing, narrative_history).
domain_category(legacy_system_technical_debt, narrative_history).
domain_category(lehman_repo_105, extractive_market).
domain_category(lestrygonian_metabolism_chp8, narrative_history).
domain_category(lestrygonian_metabolism_chp8_interval, narrative_history).
domain_category(liar_paradox, narrative_history).
domain_category(liar_paradox_interval, narrative_history).
domain_category(lindy_effect, narrative_history).
domain_category(litany_of_the_real, narrative_history).
domain_category(lln_convergence, narrative_history).
domain_category(lln_era, narrative_history).
domain_category(lobs_theorem, narrative_history).
domain_category(lobs_theorem_interval, narrative_history).
domain_category(local_vs_global_optima, narrative_history).
domain_category(logistic_map_dynamics, narrative_history).
domain_category(logistic_map_era, narrative_history).
domain_category(lorenz_attractor_dynamics, narrative_history).
domain_category(lorenz_era, narrative_history).
domain_category(lowenheim_skolem_interval, narrative_history).
domain_category(lowenheim_skolem_theorem, narrative_history).
domain_category(lsd_microdosing_professional_openness, narrative_history).
domain_category(lula_hemisphere_2026, extractive_market).
domain_category(magna_carta_liberties, narrative_history).
domain_category(mandatrophic_margin_collapse, extractive_market).
domain_category(mandatrophy_cycle, extractive_market).
domain_category(mandatrophy_lifecycle, extractive_market).
domain_category(mandatrophy_systemic_collapse, extractive_market).
domain_category(mariner_to_msl_era, narrative_history).
domain_category(mars_autonomy_evolution, narrative_history).
domain_category(mars_rover_navigational_autonomy, narrative_history).
domain_category(martian_signal_latency, narrative_history).
domain_category(matching_markets_general, narrative_history).
domain_category(matching_theory_era, narrative_history).
domain_category(material_tensile_strength, narrative_history).
domain_category(max_flow_min_cut, narrative_history).
domain_category(mco_failure_trajectory, narrative_history).
domain_category(mco_unit_system_discontinuity, narrative_history).
domain_category(med_diet_consensus_2026, narrative_history).
domain_category(medical_residency_match, narrative_history).
domain_category(medieval_church_hegemony, extractive_market).
domain_category(meta_logic_01, narrative_history).
domain_category(meta_stack_convergence, extractive_market).
domain_category(metamorphosis_samsa, extractive_market).
domain_category(micro_robot_electronics_integration, narrative_history).
domain_category(microbiome_symbiosis, narrative_history).
domain_category(midnight_deadline, narrative_history).
domain_category(midnight_deadline_period, narrative_history).
domain_category(migration_decision_threshold, narrative_history).
domain_category(migration_theory_review, narrative_history).
domain_category(mil_std_461g_emi_control, narrative_history).
domain_category(mil_std_461g_era, narrative_history).
domain_category(mil_std_810f_era, narrative_history).
domain_category(mil_std_810f_tailoring, narrative_history).
domain_category(minimax_decision_rule, narrative_history).
domain_category(minimax_era, narrative_history).
domain_category(misunderstanding_as_mismatch, extractive_market).
domain_category(molly_affirmation_cycle, narrative_history).
domain_category(molly_affirmation_id, narrative_history).
domain_category(monetary_regime_transition, narrative_history).
domain_category(monty_hall_conditional_probability, narrative_history).
domain_category(moores_law, narrative_history).
domain_category(moores_law_interval, narrative_history).
domain_category(nasa_faster_better_cheaper, extractive_market).
domain_category(nash_equilibrium_coordination, narrative_history).
domain_category(nash_era, narrative_history).
domain_category(necessary_day_job, extractive_market).
domain_category(negative_emissions_arbitrage, extractive_market).
domain_category(nestor_afternoon, extractive_market).
domain_category(net_zero_stabilization, extractive_market).
domain_category(network_effects, narrative_history).
domain_category(neural_interoperability, extractive_market).
domain_category(neurodiversity_spectrum, extractive_market).
domain_category(newton_era, narrative_history).
domain_category(newtons_method_convergence, narrative_history).
domain_category(nighttown_hallucinatory_vigil, narrative_history).
domain_category(nighttown_vigil_id, narrative_history).
domain_category(nixon_shock_1971, narrative_history).
domain_category(no_cloning_interval, narrative_history).
domain_category(no_cloning_theorem, narrative_history).
domain_category(noether_era, narrative_history).
domain_category(noethers_theorem_symmetry, narrative_history).
domain_category(non_compete_agreements, extractive_market).
domain_category(nonstandard_arithmetic_models, narrative_history).
domain_category(north_korea_songun_mandatrophy, extractive_market).
domain_category(oligarchy_interval, narrative_history).
domain_category(omelet_perfection_complexity, narrative_history).
domain_category(omelet_perfection_interval, narrative_history).
domain_category(on_liberty_analysis, narrative_history).
domain_category(openbsd_netiquette_protocol, narrative_history).
domain_category(operation_zapata_timeline, extractive_market).
domain_category(optimal_stopping_marriage, narrative_history).
domain_category(overton_interval, narrative_history).
domain_category(overton_window, narrative_history).
domain_category(p_vs_np, narrative_history).
domain_category(p_vs_np_interval, narrative_history).
domain_category(parable_fish_turtle, extractive_market).
domain_category(pareto_principle, narrative_history).
domain_category(parkinson_interval, narrative_history).
domain_category(parkinsons_law, narrative_history).
domain_category(peano_curve_mapping, narrative_history).
domain_category(peano_era, narrative_history).
domain_category(permissive_software_licensing, narrative_history).
domain_category(perovskite_self_etching, narrative_history).
domain_category(personalized_nutritional_arbitrage, extractive_market).
domain_category(peter_principle, narrative_history).
domain_category(planetary_boundaries, extractive_market).
domain_category(planetary_diet_constraint_2026, narrative_history).
domain_category(planning_fallacy, narrative_history).
domain_category(planning_fallacy_interval, narrative_history).
domain_category(platform_cooperativism_governance, narrative_history).
domain_category(platform_labor_epoch, extractive_market).
domain_category(platonic_coparenting, narrative_history).
domain_category(pnt_era, narrative_history).
domain_category(poetic_verse_and_past, extractive_market).
domain_category(poincare_conjecture, narrative_history).
domain_category(poincare_era, narrative_history).
domain_category(politeness_face_negotiation, extractive_market).
domain_category(post_trump_return, extractive_market).
domain_category(postman_survival_interval, narrative_history).
domain_category(postman_survival_protocol, narrative_history).
domain_category(pre_911_silo_regime, extractive_market).
domain_category(prime_number_theorem, narrative_history).
domain_category(prisoners_dilemma_equilibrium, extractive_market).
domain_category(private_identity_integration, narrative_history).
domain_category(probability_paradox_era, narrative_history).
domain_category(proof_of_work_consensus, narrative_history).
domain_category(protean_signatures_1904, narrative_history).
domain_category(proteus_strand_walk, narrative_history).
domain_category(public_domain_commons, narrative_history).
domain_category(pythagorean_era, narrative_history).
domain_category(pythagorean_geometric_constancy, narrative_history).
domain_category(qi_interval, extractive_market).
domain_category(qualified_immunity, extractive_market).
domain_category(quantum_decryption_risk_2026, extractive_market).
domain_category(quantum_entanglement_protocol, narrative_history).
domain_category(quantum_nonlocality_2026, narrative_history).
domain_category(quellcrist_falconer_justice, extractive_market).
domain_category(quine_era, narrative_history).
domain_category(quine_self_replication, narrative_history).
domain_category(qwerty_lockin_interval, narrative_history).
domain_category(qwerty_vs_dvorak, narrative_history).
domain_category(radiologic_diagnostic_threshold, extractive_market).
domain_category(radiology_r7, extractive_market).
domain_category(railway_gauge_standard, narrative_history).
domain_category(recipe_scaling_ai, narrative_history).
domain_category(reciprocity_laws_math, narrative_history).
domain_category(regulatory_capture, extractive_market).
domain_category(rejuvenation_centenary_cycle, extractive_market).
domain_category(relativity_of_simultaneity, narrative_history).
domain_category(relativity_physical_invariance, narrative_history).
domain_category(rfc9293_state_machine, narrative_history).
domain_category(rices_era, narrative_history).
domain_category(rices_theorem_undecidability, narrative_history).
domain_category(rn_withdrawal_cycle, extractive_market).
domain_category(rogers_commission_institutional_analysis, extractive_market).
domain_category(rope_design, narrative_history).
domain_category(rosen_bridge_interval, narrative_history).
domain_category(rosen_bridge_protocol, narrative_history).
domain_category(rotation_seven_black_soil, extractive_market).
domain_category(rotation_seven_isolation, extractive_market).
domain_category(rotation_seven_kubo_ranking, extractive_market).
domain_category(royal_navy_middle_east_withdrawal, extractive_market).
domain_category(ruin_era, extractive_market).
domain_category(rules_based_international_order, extractive_market).
domain_category(russell_era, extractive_market).
domain_category(russells_paradox_self_reference, extractive_market).
domain_category(russia_cannibalization_cycle, extractive_market).
domain_category(russian_war_cannibalization, extractive_market).
domain_category(sadhu_integrity_protocol, narrative_history).
domain_category(samsa_transformation_period, extractive_market).
domain_category(sapir_whorf_hypothesis, narrative_history).
domain_category(sapir_whorf_interval, narrative_history).
domain_category(sat_csp_complexity, narrative_history).
domain_category(sat_csp_interval, narrative_history).
domain_category(scientific_consensus_period, narrative_history).
domain_category(scientific_revolution_current, narrative_history).
domain_category(scs_legal_era, narrative_history).
domain_category(scs_operational_2026, extractive_market).
domain_category(scurvy_maritime_extraction, extractive_market).
domain_category(scurvy_maritime_interval, extractive_market).
domain_category(self_surpassing, extractive_market).
domain_category(shannon_entropy_limit, narrative_history).
domain_category(shitty_feedback_handling, narrative_history).
domain_category(shobies_existential_commitment, extractive_market).
domain_category(sig_usd_interval, narrative_history).
domain_category(sig_usd_protocol, narrative_history).
domain_category(silicon_lexicon_overload, extractive_market).
domain_category(skills_based_hiring, narrative_history).
domain_category(skolem_era, narrative_history).
domain_category(skolems_paradox, narrative_history).
domain_category(skolems_paradox_interval, narrative_history).
domain_category(sludge_bureaucratic_friction, extractive_market).
domain_category(smartphone_ubiquity, extractive_market).
domain_category(social_credit_architecture, extractive_market).
domain_category(social_loafing, narrative_history).
domain_category(social_loafing_interval, narrative_history).
domain_category(social_media_2025_cycle, narrative_history).
domain_category(social_media_participation_threshold, narrative_history).
domain_category(social_narrative_casting, narrative_history).
domain_category(software_lifecycle_r7, narrative_history).
domain_category(solar_system_weirdness, narrative_history).
domain_category(somatic_focusing_awareness, narrative_history).
domain_category(sorites_interval, narrative_history).
domain_category(sorites_paradox, narrative_history).
domain_category(south_china_sea_arbitration_2016_2026, narrative_history).
domain_category(spv_variations, narrative_history).
domain_category(square_cube_interval, narrative_history).
domain_category(square_cube_law, narrative_history).
domain_category(st_petersburg_era, extractive_market).
domain_category(st_petersburg_paradox, extractive_market).
domain_category(stable_marriage_coordination, narrative_history).
domain_category(starwars_evolutionary_mutation, extractive_market).
domain_category(statecraft_virtu, extractive_market).
domain_category(statecraft_virtu_analysis, extractive_market).
domain_category(steinmetz_valuation_asymmetry, extractive_market).
domain_category(stephen_shakespeare_ghost, narrative_history).
domain_category(stoic_logos_governance, extractive_market).
domain_category(strait_coercion_2025, narrative_history).
domain_category(strange_attractor_dynamics, narrative_history).
domain_category(sts86_ascent_checklist, narrative_history).
domain_category(sturgeon_interval, narrative_history).
domain_category(sturgeons_law, narrative_history).
domain_category(suanne_coup_of_peace, extractive_market).
domain_category(suanne_face_restoration, extractive_market).
domain_category(sunk_cost_fallacy, narrative_history).
domain_category(sunk_cost_interval, narrative_history).
domain_category(suslin_era, narrative_history).
domain_category(suslin_hypothesis_undecidability, narrative_history).
domain_category(sylow_era, narrative_history).
domain_category(sylow_theorems_group_theory, narrative_history).
domain_category(system_3_emergence, extractive_market).
domain_category(taiwan_existential_sovereignty, extractive_market).
domain_category(taiwan_grand_bargain, extractive_market).
domain_category(taiwan_status_quo_cycle, extractive_market).
domain_category(taiwan_storm_2026, extractive_market).
domain_category(taiwan_strait_hegemony_shift, extractive_market).
domain_category(tarski_interval, narrative_history).
domain_category(tarski_undefinability, narrative_history).
domain_category(tcp_rfc9293_interoperability, narrative_history).
domain_category(teaching_horses_to_sing, extractive_market).
domain_category(teaching_horses_to_sing_interval, extractive_market).
domain_category(technological_provenance_arbitrage, extractive_market).
domain_category(tehran_water_bankruptcy, extractive_market).
domain_category(telemachus_morning, extractive_market).
domain_category(temporal_scale_arbitrage, extractive_market).
domain_category(tensile_strength_interval, narrative_history).
domain_category(texas_hispanic_political_pivot, extractive_market).
domain_category(the_bacchae_madness_protocol, extractive_market).
domain_category(the_calm_expedition_window, extractive_market).
domain_category(the_calm_protocol_suppression, extractive_market).
domain_category(the_churn_systemic_upheaval, extractive_market).
domain_category(the_viceregal_cavalcade, narrative_history).
domain_category(the_wall_procedural_barrier, extractive_market).
domain_category(theban_dionysian_conflict, extractive_market).
domain_category(theory_of_visitors, extractive_market).
domain_category(thermodynamics_entropy, extractive_market).
domain_category(thermodynamics_entropy_interval, extractive_market).
domain_category(thirteen_days_crisis, narrative_history).
domain_category(three_body_unpredictability, narrative_history).
domain_category(toxic_social_infection, extractive_market).
domain_category(toxic_social_infection_interval, extractive_market).
domain_category(tractarian_logic_limit, extractive_market).
domain_category(trade_secret_law, narrative_history).
domain_category(tragedy_of_the_commons, extractive_market).
domain_category(transformer_self_attention, extractive_market).
domain_category(transient_event_detection, narrative_history).
domain_category(traveling_salesperson_problem, narrative_history).
domain_category(trojan_collapse_interval, extractive_market).
domain_category(trojan_war_spoils, extractive_market).
domain_category(trump_authoritarianism_2026, extractive_market).
domain_category(trump_ii_year_one, extractive_market).
domain_category(trump_making_china_great_2026, extractive_market).
domain_category(tx_pivot_window_2026, extractive_market).
domain_category(udhr_1948, narrative_history).
domain_category(un_era, narrative_history).
domain_category(unclos_2026, narrative_history).
domain_category(unclos_era, narrative_history).
domain_category(union_protection_underperformance, narrative_history).
domain_category(universal_mathematics_communication, narrative_history).
domain_category(us_hydrological_debt, extractive_market).
domain_category(us_suburban_zoning_2025, extractive_market).
domain_category(us_two_party_duopoly, extractive_market).
domain_category(utopia_apocalypse_fragility, extractive_market).
domain_category(van_der_waerden_interval, narrative_history).
domain_category(van_der_waerden_theorem, narrative_history).
domain_category(viral_transmission_rates, extractive_market).
domain_category(visa_ipo_regulatory_compliance, narrative_history).
domain_category(visa_ipo_window, narrative_history).
domain_category(visa_judgment_sharing_agreement, narrative_history).
domain_category(visa_litigation_ringfencing, narrative_history).
domain_category(weber_fechner_law, narrative_history).
domain_category(whitehead_era, narrative_history).
domain_category(whitehead_problem_undecidability, narrative_history).
domain_category(wikipedia_crowdsourcing_2026, narrative_history).
domain_category(wikipedia_notability_requirement_2026, narrative_history).
domain_category(winners_curse, extractive_market).
domain_category(xi_mao_ideological_centralization, extractive_market).
domain_category(zarathustra_hazar, extractive_market).
domain_category(zipfs_law, extractive_market).