:- module(domain_registry, [domain_category/2]).
% --- AUTOMATICALLY GENERATED DOMAIN REGISTRY ---
% Thresholds aligned with config.pl: Rope <= 0.15, Snare >= 0.46, Tangled Rope 0.16-0.9.
% Total entries: 1022

domain_category('26usc469_real_estate_exemption', snare).
domain_category('8k_tv_limit_2026', piton).
domain_category(absorbing_markov_chain_trap, snare).
domain_category(abstraction_boundary_overrun, snare).
domain_category(abstraction_leakage, snare).
domain_category(academic_fashion_modernism_2026, piton).
domain_category(academic_peer_review_gatekeeping, snare).
domain_category(academic_tenure_system, snare).
domain_category(ad_fus_coordination, snare).
domain_category(ad_synaptic_deficit, snare).
domain_category(adaptive_lag_trap, snare).
domain_category(adversarial_surface_inflation, snare).
domain_category(adversarial_truth_decay, piton).
domain_category(adverse_possession, snare).
domain_category(advice_as_dangerous_gift, tangled_rope).
domain_category(agency_atrophy, snare).
domain_category(agentive_optimism_2026, piton).
domain_category(aging_longevity_tests, snare).
domain_category(ai_adoption_stigma, snare).
domain_category(ai_auditability_gap, snare).
domain_category(ai_banal_capture, snare).
domain_category(ai_cognitive_diversity_arbitrage, snare).
domain_category(ai_compute_capital_moat, snare).
domain_category(ai_driven_surveillance_sensor_layer, snare).
domain_category(ai_edu_decentralization, rope).
domain_category(ai_nonconsensual_content_facilitation, snare).
domain_category(ai_performance_watermark, snare).
domain_category(ai_professional_displacement, snare).
domain_category(ai_religion_regulation, snare).
domain_category(ai_scholar_citation_trap, snare).
domain_category(ai_superpowers_2026, scaffold).
domain_category(ai_task_horizon_reliability, snare).
domain_category(ai_training_data_dependency, snare).
domain_category(airbnb_str_regulation, snare).
domain_category(airport_slot_use_it_or_lose_it, snare).
domain_category(algeria_france_colonial_legacy, snare).
domain_category(algorithmic_bias, snare).
domain_category(algorithmic_epistemic_capture, piton).
domain_category(alignment_tax_tradeoff, piton).
domain_category(alternative_sovereignty_scaffold, scaffold).
domain_category(altruistic_misery_paradox_2026, piton).
domain_category(alzheimers_levetiracetam, tangled_rope).
domain_category(alzheimers_nlrp3_inflammasome, snare).
domain_category(amish_technological_renunciation, snare).
domain_category(ancestral_pueblo_hydrology, snare).
domain_category(ancient_grudge_verona, snare).
domain_category(anticipatory_capacity_failure, piton).
domain_category(antifragility, snare).
domain_category(apartheid_nuclear_program, snare).
domain_category(ape_cognition_framework, snare).
domain_category(appropriations_brinkmanship, snare).
domain_category(arctic_geopolitical_flashpoint, snare).
domain_category(arctic_maritime_control, snare).
domain_category(arg_ev_tariff, snare).
domain_category(armra_colostrum_regulation, snare).
domain_category(arrows_impossibility_theorem, snare).
domain_category(art_market_decoupling, piton).
domain_category(artificial_scarcity_scaffold, scaffold).
domain_category(artificial_snow_2026, piton).
domain_category(asce_7_22_seismic_design, tangled_rope).
domain_category(asean_ceasefire_2011, scaffold).
domain_category(asshole_filter_2015, snare).
domain_category(astm_d638_tensile_testing, rope).
domain_category(asymmetric_burden_distribution, piton).
domain_category(asymmetric_computational_difficulty, piton).
domain_category(atrophied_optimization_piton, piton).
domain_category(attention_as_bottleneck_resource, piton).
domain_category(attention_market_cannibalization, snare).
domain_category(australia_social_ban_2026, snare).
domain_category(authoritarian_power_paradox, snare).
domain_category(automatic_enrollment_defaults, rope).
domain_category(autonomous_toolchain_sprawl, piton).
domain_category(availability_heuristic, tangled_rope).
domain_category(average_is_over_2026, snare).
domain_category(awareness_without_leverage, snare).
domain_category(axiom_of_choice, mountain).
domain_category(axiom_reasoner_2026, snare).
domain_category(banach_fixed_point, mountain).
domain_category(banach_fixed_point_theorem, mountain).
domain_category(banach_tarski_paradox, mountain).
domain_category(bangladesh_july_national_charter, snare).
domain_category(base_pair_complementarity, mountain).
domain_category(basel_problem_convergence, mountain).
domain_category(bay_of_pigs_operational_silo, snare).
domain_category(bayes_theorem_cognitive_bias, snare).
domain_category(bedouin_sedentary_transition, snare).
domain_category(beehiiv_platform_model, snare).
domain_category(belief_argument_conclusion, snare).
domain_category(berkshire_compounding_culture, rope).
domain_category(bgs_eigenvector_thermalization, tangled_rope).
domain_category(bgs_spectral_universality, mountain).
domain_category(bh_merger_gravitational_infall, mountain).
domain_category(big_data_astrophysics_arbitrage, snare).
domain_category(biological_curiosity, mountain).
domain_category(bip_narrative_illusion, snare).
domain_category(birthday_paradox_collision, mountain).
domain_category(blackstone_carried_interest_taxation, tangled_rope).
domain_category(blackstone_conflicts_of_interest, snare).
domain_category(blackstone_smd_control, snare).
domain_category(blackstone_tra, snare).
domain_category(bnpl_payment_systems, snare).
domain_category(board_of_peace_2026, snare).
domain_category(boiled_pineapple_trend_2026, piton).
domain_category(boltzmann_universality_2026, tangled_rope).
domain_category(bor_tax_exemption_nl, snare).
domain_category(boundary_dissolution_risk, snare).
domain_category(boundary_protocol, scaffold).
domain_category(brain_network_paradigm_2026, snare).
domain_category(brazil_2026_general_elections, snare).
domain_category(brazil_mexico_financial_requirement, snare).
domain_category(broke_vs_poor_grocery_math, snare).
domain_category(brouwer_fixed_point, mountain).
domain_category(buffons_needle_pi_estimation, snare).
domain_category(burali_forti_paradox, mountain).
domain_category(burden_of_proof_engineering_safety, snare).
domain_category(burden_of_proof_legal_criminal, rope).
domain_category(burden_of_proof_scientific, snare).
domain_category(bureaucratic_legibility_collapse, snare).
domain_category(bureaucratic_self_preservation, piton).
domain_category(bushman_money_magic, snare).
domain_category(busy_beaver_noncomputability, mountain).
domain_category(c_physical_blue_wavelength, mountain).
domain_category(canada_goose_realignment_2026, scaffold).
domain_category(canal_panama_influence, snare).
domain_category(cancer_chronotherapy_timing, rope).
domain_category(cancer_prevention, snare).
domain_category(cantor_set_topology, mountain).
domain_category(cantors_diagonal_argument, mountain).
domain_category(cap_theorem, mountain).
domain_category(capability_eval_overhang, piton).
domain_category(capital_misallocation_spiral, snare).
domain_category(capital_rotation_ai_narrative, snare).
domain_category(carbon_credit_markets_2026, snare).
domain_category(carrier_deployment_deterrence, snare).
domain_category(carrying_capacity, snare).
domain_category(cartel_drone_surveillance_el_paso, snare).
domain_category(cascading_constraint_failure, snare).
domain_category(cascading_uncertainty_2026, snare).
domain_category(castration_longevity_choice, snare).
domain_category(cb_far_beyond_human, snare).
domain_category(cbdc_implementation, snare).
domain_category(central_limit_theorem, mountain).
domain_category(cfius_hiefo_emcore_divestment, snare).
domain_category(cg_israelgaza_20231012, snare).
domain_category(chaitins_omega_undecidability, mountain).
domain_category(challenger_o_ring_integrity, snare).
domain_category(champions_bass_fishing_exclusion, snare).
domain_category(child_marriage, snare).
domain_category(china_critical_mineral_chokepoint, snare).
domain_category(china_ev_export_oversupply, snare).
domain_category(china_taiwan_reunification_mandate, snare).
domain_category(china_vactrain_standard, snare).
domain_category(choice_architecture_design, snare).
domain_category(cholesterol_pill_cost, snare).
domain_category(chrome_imagen2_integration, snare).
domain_category(church_turing_thesis, mountain).
domain_category(cia_fbi_legal_wall, snare).
domain_category(cinderella_midnight_deadline, scaffold).
domain_category(circadian_decoupling_arbitrage, snare).
domain_category(citation_collapse_dynamics, piton).
domain_category(civilizational_lifecycle_solara, snare).
domain_category(civilizational_maintenance_debt, snare).
domain_category(clawderberg_recursive_slop, piton).
domain_category(click_chemistry_paradigm_2026, rope).
domain_category(climate_attribution_2026, rope).
domain_category(climate_event_attribution, snare).
domain_category(climate_target_one_point_five, tangled_rope).
domain_category(cloudflare_dual_class_asymmetry, snare).
domain_category(clt_convergence_2026, mountain).
domain_category(cma, snare).
domain_category(cmr_001, snare).
domain_category(cn_tech_decoupling_security_software, snare).
domain_category(coalition_disinfo_framework_2026, snare).
domain_category(cobra_effect, snare).
domain_category(codex_access, snare).
domain_category(coe_ukraine_reparations_register, snare).
domain_category(coffee_cardiovascular_2026, scaffold).
domain_category(cognac_geopolitical_risk, snare).
domain_category(cognitive_bicycle_scaffold, rope).
domain_category(cognitive_diversity_arbitrage, snare).
domain_category(cognitive_energy_budget, snare).
domain_category(cognitive_hacking_2026, snare).
domain_category(cognitive_induction_gap, snare).
domain_category(cognitive_surrender_to_system_3, snare).
domain_category(coinbase_crypto_volatility, tangled_rope).
domain_category(coinbase_regulatory_uncertainty, snare).
domain_category(cold_dark_matter_paradigm, snare).
domain_category(collatz_conjecture_determinism, mountain).
domain_category(collective_action_deadlock, snare).
domain_category(collective_stupidity_2026, snare).
domain_category(college_admissions_market, snare).
domain_category(colombia_2026_presidential_election, rope).
domain_category(colorado_sbe_decentralization_friction, snare).
domain_category(comitatus_bond, tangled_rope).
domain_category(communal_narcissism_social_trap, piton).
domain_category(complexity_debt, snare).
domain_category(compounding_logic, snare).
domain_category(confirmation_bias, snare).
domain_category(consensus_without_truth, snare).
domain_category(constitutional_consecration, snare).
domain_category(constitutional_supremacy, snare).
domain_category(constraint_borsuk_ulam, mountain).
domain_category(constraint_ftc, mountain).
domain_category(constraint_galois_solvability, mountain).
domain_category(constraint_interaction_explosion, snare).
domain_category(constraint_lagrange_multipliers, tangled_rope).
domain_category(constraint_lorenz_sensitivity, mountain).
domain_category(constraint_nonstandard_arithmetic, mountain).
domain_category(constraint_pythagorean, mountain).
domain_category(constraint_riemann_mapping, tangled_rope).
domain_category(constraint_sylow, mountain).
domain_category(constraint_tarski_undefinability, mountain).
domain_category(constraint_twin_prime_conjecture, mountain).
domain_category(constraint_yoneda, tangled_rope).
domain_category(consumer_debt_slavery, snare).
domain_category(container_capacity_mismatch, snare).
domain_category(continuum_hypothesis_undecidability, mountain).
domain_category(conversational_dogmas_interruption, snare).
domain_category(conways_game_of_life_dynamics, mountain).
domain_category(coordination_attack_vulnerability, piton).
domain_category(coordination_fatigue, snare).
domain_category(coordination_threshold_failure, snare).
domain_category(copyleft_viral_licensing, rope).
domain_category(copyright_protection, tangled_rope).
domain_category(corporate_social_responsibility_theater, piton).
domain_category(cosmological_evolution_alpha_omega, mountain).
domain_category(cost_of_observation, snare).
domain_category(countable_infinity_cardinality, mountain).
domain_category(couples_residency_match, snare).
domain_category(cow_field_poop, tangled_rope).
domain_category(creative_commons_licensing, tangled_rope).
domain_category(credentialism_national_security, snare).
domain_category(credibility_inflation, snare).
domain_category(crisis_signal_saturation, piton).
domain_category(crispr_genomic_rewrite_2026, tangled_rope).
domain_category(critical_actor_overcentralization, snare).
domain_category(crop_defense_dependency, snare).
domain_category(cross_domain_coupling_spiral, snare).
domain_category(cs_ecmo_bridge, snare).
domain_category(cuba_mandatrophic_collapse, snare).
domain_category(cuban_missile_crisis_excomm_deliberation, rope).
domain_category(cultural_homogenization_social_media, snare).
domain_category(cultural_memory_decay, snare).
domain_category(cultural_refragmentation_2026, piton).
domain_category(cumbria_mine_rejection, snare).
domain_category(cuny_light_2026, rope).
domain_category(currys_paradox, mountain).
domain_category(cz_plea_agreement_2026, snare).
domain_category(damped_harmonics, mountain).
domain_category(dark_patterns_manipulation, snare).
domain_category(data_laundering_pipeline, snare).
domain_category(data_privacy_regulation, snare).
domain_category(data_replication_paradox, snare).
domain_category(dead_sea_effect, snare).
domain_category(debt_service_squeeze, snare).
domain_category(debt_trap_microfinance, snare).
domain_category(decentralized_infrastructure_rope, tangled_rope).
domain_category(decision_latency_mismatch, snare).
domain_category(deep_earth_hydrogen_availability, mountain).
domain_category(deferential_realism_framework, rope).
domain_category(deferred_risk_realization, snare).
domain_category(delayed_feedback_instability, snare).
domain_category(delta_force_selection_2026, snare).
domain_category(demographic_inertia_trap, snare).
domain_category(dexy_gold_protocol, tangled_rope).
domain_category(digital_credentialing_verification, snare).
domain_category(digital_euro_cbdc, snare).
domain_category(digital_identity_tether, snare).
domain_category(dionysiac_frenzy, snare).
domain_category(discover_core_2026, snare).
domain_category(djia_as_economic_barometer, snare).
domain_category(dk_foreign_convict_expulsion, snare).
domain_category(dldr_information_policy, rope).
domain_category(dn_paywall, snare).
domain_category(doomsday_clock_framework, snare).
domain_category(dunbars_number, mountain).
domain_category(dunning_kruger_effect, snare).
domain_category(dutch_minority_govt_2026, snare).
domain_category(dwp_carers_allowance_cliff, snare).
domain_category(e2ee_digital_privacy_2026, rope).
domain_category(ec_meta_manus_block, snare).
domain_category(edelman_2026_developed_stagnation, snare).
domain_category(edelman_2026_developing_volatility, snare).
domain_category(edelman_2026_insularity, snare).
domain_category(education_unbundling_implementation, rope).
domain_category(ehrenfest_barrier, mountain).
domain_category(electrification_scale_2026, tangled_rope).
domain_category(elencher_identity_transformation, mountain).
domain_category(elite_capture_2026, piton).
domain_category(elite_identity_capture_2026, snare).
domain_category(elite_overproduction_instability, snare).
domain_category(elliq_ai_companion, snare).
domain_category(em_clinical_guidelines, snare).
domain_category(emergency_bridge_scaffold, snare).
domain_category(emergency_mode_lock_in, snare).
domain_category(emergency_oversight_bureau, tangled_rope).
domain_category(emergency_powers_ratchet, snare).
domain_category(emergent_goal_misalignment, snare).
domain_category(emotional_cycles_2026, snare).
domain_category(empty_tomb_transformation, tangled_rope).
domain_category(endocrine_disruption_society, snare).
domain_category(endowment_effect, mountain).
domain_category(english_chinese_tense_structure, mountain).
domain_category(epigenetics_complexity_2026, mountain).
domain_category(epistemic_free_rider_problem, snare).
domain_category(epistemic_overload_collapse, snare).
domain_category(epstein_document_release_2026, snare).
domain_category(epstein_espionage_2026, piton).
domain_category(epstein_files_2026, piton).
domain_category(epstein_honeytrap, piton).
domain_category(erasmus_rejoining_scaffold, scaffold).
domain_category(ergo_autolykos_asic_resistance, snare).
domain_category(ergo_lets_protocol, rope).
domain_category(ergo_mixer_protocol, snare).
domain_category(ergo_nipopows, mountain).
domain_category(ergo_storage_rent, snare).
domain_category(ergo_storage_rent_mechanism, tangled_rope).
domain_category(ergodic_theorems, tangled_rope).
domain_category(ergot_grain_poisoning, snare).
domain_category(erised_expectation, piton).
domain_category(eu_affordable_housing_initiative, snare).
domain_category(eu_asylum_outsourcing_framework, snare).
domain_category(eu_deforestation_regulation, snare).
domain_category(eu_digital_services_act, snare).
domain_category(eu_ev_tariff_wall, snare).
domain_category(eu_irgc_terrorist_designation, snare).
domain_category(eu_mercosur_trade_agreement, snare).
domain_category(eu_renewable_energy_mandate, snare).
domain_category(eu_unanimity_rule_foreign_policy, snare).
domain_category(euler_characteristic_topology, mountain).
domain_category(eurozone_fragmentation_2026, snare).
domain_category(evfta_trade_agreement, snare).
domain_category(evidence_half_life, snare).
domain_category(evolutionary_knowledge, snare).
domain_category(evolutionary_mismatch_load, snare).
domain_category(exoplanetary_habitability_arbitrage, rope).
domain_category(expert_disempowerment, snare).
domain_category(exploration_vs_exploitation, snare).
domain_category(extraordinary_narrative_shift, tangled_rope).
domain_category(faa_boeing_regulatory_capture, tangled_rope).
domain_category(factional_instability, snare).
domain_category(faint_blue_neural_bifurcation, snare).
domain_category(fair_use_doctrine, rope).
domain_category(family_estrangement_ratio, snare).
domain_category(family_succession_system, snare).
domain_category(fast_growing_hierarchy, mountain).
domain_category(fcc_dji_covered_list, snare).
domain_category(fda_component_efficacy_standard, snare).
domain_category(fed_shutdown_2026, snare).
domain_category(feedback_loop_desynchronization, snare).
domain_category(feigenbaum_universality, mountain).
domain_category(fermat_proof_barrier, mountain).
domain_category(fgh_hierarchy_2026, mountain).
domain_category(fiat_currency_lifecycle, snare).
domain_category(fiber_optic_chip_tech, snare).
domain_category(financial_drag, snare).
domain_category(fine_particle_policy, snare).
domain_category(finite_pool_of_worry, snare).
domain_category(finite_simple_group_classification, mountain).
domain_category(finnish_debt_adjustment, snare).
domain_category(finnish_ubi_experiment, scaffold).
domain_category(fiscal_dominance_trap, piton).
domain_category(fitts_law_industrial_application, snare).
domain_category(floating_wall_2026, snare).
domain_category(fmeca_procedures_1980, rope).
domain_category(fmt_oncology_2026, scaffold).
domain_category(fnl_shadow_probe, tangled_rope).
domain_category(four_color_theorem_topological_bound, mountain).
domain_category(fragile_middle_layer_collapse, snare).
domain_category(framing_effect, snare).
domain_category(france_2027_presidential_election, snare).
domain_category(france_cordon_sanitaire_2026, piton).
domain_category(france_local_elections_march_2026, tangled_rope).
domain_category(franchisee_corporate_squeeze, snare).
domain_category(frankenstein_creation_hubris, snare).
domain_category(fraser_river_salmon_regulation, snare).
domain_category(french_ag_land_concentration, snare).
domain_category(frontex_pushback_coordination, snare).
domain_category(fundamental_theorem_of_algebra, mountain).
domain_category(future_dsm_integration, snare).
domain_category(g7_debt_trap, snare).
domain_category(gale_shapley, snare).
domain_category(galois_theory_symmetry, mountain).
domain_category(gamblers_ruin_stochastic_extinction, snare).
domain_category(gauss_bonnet_topology, mountain).
domain_category(gaza_aid_permit_revocation, snare).
domain_category(gaza_border_control_rafah, snare).
domain_category(gemini_scientific_advancement, tangled_rope).
domain_category(generational_replacement_inertia, snare).
domain_category(genetic_algorithms_evolution, mountain).
domain_category(genetic_predisposition, snare).
domain_category(genetic_predisposition_mania, mountain).
domain_category(genie_ip_constraint, snare).
domain_category(geophysics_superionic_core, mountain).
domain_category(geopolitical_insularity_2026, snare).
domain_category(germany_tennet_takeover, tangled_rope).
domain_category(germline_regulation_threshold_2026, snare).
domain_category(ghost_fishing_gear, snare).
domain_category(gig_economy_algorithmic_management, snare).
domain_category(gilgamesh_mortality_limit, snare).
domain_category(gita_kurukshetra, tangled_rope).
domain_category(glen_canyon_water_allocation, snare).
domain_category(global_digital_divide, snare).
domain_category(global_economic_anxiety_2026, piton).
domain_category(global_hoarding_scaling_laws, snare).
domain_category(global_protocol_entrenchment, snare).
domain_category(global_stimulus_spree, snare).
domain_category(global_water_bankruptcy, snare).
domain_category(glp1_payload_efficiency_pivot, rope).
domain_category(goal_boundary_poisoning, snare).
domain_category(goedels_incompleteness_theorems, mountain).
domain_category(gold_fomo_cycle, snare).
domain_category(gold_piton_2026, piton).
domain_category(goldbach_conjecture, mountain).
domain_category(golden_handcuffs, tangled_rope).
domain_category(goodharts_law, snare).
domain_category(goodstein_theorem_finite_proof, tangled_rope).
domain_category(google_ai_search_overview, snare).
domain_category(google_universal_commerce_protocol, snare).
domain_category(governance_latency_gap, snare).
domain_category(governance_overfitting, snare).
domain_category(gpt5_codex_dev_cycle, snare).
domain_category(gpt_store_marketplace, snare).
domain_category(gradient_descent_optimization, rope).
domain_category(graph_coloring_complexity, tangled_rope).
domain_category(great_awakening_rekindling, snare).
domain_category(great_mongolian_road_economic_dependency, snare).
domain_category(greenland_defence_pact_2026, snare).
domain_category(greenland_seizure_trade_war, snare).
domain_category(greshams_law, snare).
domain_category(grete_samsa_transition, snare).
domain_category(grievance_stack_overflow, snare).
domain_category(gs1_gln_identification, rope).
domain_category(gs1_standardized_identification, rope).
domain_category(gs_market_clearing, tangled_rope).
domain_category(guano_wealth_extraction, snare).
domain_category(guinea_junta_legitimization_2024, snare).
domain_category(guinea_worm_eradication, tangled_rope).
domain_category(guthrie_kidnapping_2026, snare).
domain_category(halting_problem_undecidability, mountain).
domain_category(hamiltonian_path_complexity, mountain).
domain_category(hammurabi_lex_talionis, snare).
domain_category(hanlons_razor, snare).
domain_category(happiness_of_others, snare).
domain_category(harm_principle_liberty, snare).
domain_category(hasbro_licensing_restriction, snare).
domain_category(hawthorne_effect, snare).
domain_category(hd101584_stellar_evolution, mountain).
domain_category(hedonic_adaptation_baseline, snare).
domain_category(hegemonic_entropy_2026, piton).
domain_category(heine_borel, mountain).
domain_category(heisenberg_uncertainty, mountain).
domain_category(help_to_buy_uk, snare).
domain_category(helsinki_bus_theory, tangled_rope).
domain_category(hershey_salt_strategy, snare).
domain_category(heuristic_optimization, rope).
domain_category(hhs_fetal_tissue_research_ban_2019, snare).
domain_category(hicbc_uk, snare).
domain_category(hidden_interdependency_risk, snare).
domain_category(hilbert_hotel_infinite_capacity, mountain).
domain_category(hilberts_hotel_infinity, mountain).
domain_category(hiv_prep_prevention_2026, mountain).
domain_category(hoa_covenants, piton).
domain_category(hollow_state_syndrome, piton).
domain_category(hominin_evolutionary_bottleneck, rope).
domain_category(horizon_liability_contract, snare).
domain_category(hp_liberalism, snare).
domain_category(hu_2026_election_rules, snare).
domain_category(huang_expectation_resilience_2026, piton).
domain_category(hub_short_form_tv_market_fragmentation, snare).
domain_category(hydra_game, snare).
domain_category(hypercompression_of_time_horizons, snare).
domain_category(hypernormie_equilibrium, snare).
domain_category(ia_digital_preservation, snare).
domain_category(ibm_shield_2026, snare).
domain_category(ibm_shield_contract_2026, snare).
domain_category(ice_memory_archive, scaffold).
domain_category(ice_raids_minnesota_2026, snare).
domain_category(ice_safe_departure, snare).
domain_category(identity_stack_incompatibility, snare).
domain_category(incentive_surface_warping, snare).
domain_category(incumbent_steel_production, snare).
domain_category(indexical_relativity_core, mountain).
domain_category(india_nuclear_liability_act_2010, snare).
domain_category(india_semi_mission, snare).
domain_category(indian_import_tariffs_eu, snare).
domain_category(individual_revolution_autonomy, snare).
domain_category(indo_german_defense_pact, snare).
domain_category(indonesia_penal_code_2023, snare).
domain_category(inference_cost_scaling_law, snare).
domain_category(information_foraging_theory, rope).
domain_category(informational_time_2026, snare).
domain_category(infrastructure_interoperability_decay, piton).
domain_category(inner_model_confirmation_bias, snare).
domain_category(inner_model_theory_constraints, tangled_rope).
domain_category(innovators_dilemma, snare).
domain_category(institutional_inertia_lock, snare).
domain_category(institutional_memory_loss, piton).
domain_category(institutional_mutation_domestication, snare).
domain_category(institutional_mutation_without_selection, snare).
domain_category(institutional_trust_decay, piton).
domain_category(insult_wisdom_training, snare).
domain_category(integrated_digital_governance_stack, snare).
domain_category(interface_contract_breakdown, snare).
domain_category(international_seabed_mining_regime, snare).
domain_category(internet_evolution_lifecycle, snare).
domain_category(interpretive_frame_fragmentation, snare).
domain_category(intertemporal_responsibility_gap, snare).
domain_category(invisible_infrastructure_dependency, piton).
domain_category(iran_guardian_council_vetting, snare).
domain_category(iran_hijab_law, snare).
domain_category(iran_mandatrophic_collapse, snare).
domain_category(iran_nin_repression, snare).
domain_category(iran_war_room_2026, snare).
domain_category(iron_law_of_oligarchy, snare).
domain_category(irreversible_policy_commitment, snare).
domain_category(isa_education_scaffold, scaffold).
domain_category(israel_egypt_gas_deal, snare).
domain_category(israel_electoral_threshold, snare).
domain_category(israel_gaza_ceasefire_violation, snare).
domain_category(israel_norwegian_law, snare).
domain_category(israel_override_clause, snare).
domain_category(israel_surplus_vote_agreements, snare).
domain_category(israeli_settlement_policy_authority_restriction, snare).
domain_category(iss_ped_ban, snare).
domain_category(iterated_function_system_convergence, tangled_rope).
domain_category(ivt_accessibility_barrier, snare).
domain_category(japanese_energy_scaffold_2025, snare).
domain_category(jevons_paradox, snare).
domain_category(job_hunt_volume_system_2026, snare).
domain_category(jp_eez_enforcement, snare).
domain_category(jp_nativist_politics, snare).
domain_category(jupiter_composition_knowledge_gap, tangled_rope).
domain_category(juvenile_underclass_2026, piton).
domain_category(keltner_relationship_evaluation, tangled_rope).
domain_category(khantivadin_radical_patience, snare).
domain_category(kidney_exchange_market, rope).
domain_category(kim_jong_un_succession, snare).
domain_category(kirby_paris_theorem, mountain).
domain_category(kjv_linguistic_residue, piton).
domain_category(kjv_puritan_new_world_exit, rope).
domain_category(kjv_textual_authority, tangled_rope).
domain_category(kleene_recursion_theorem, mountain).
domain_category(knowledge_action_gap, snare).
domain_category(kolmogorov_complexity, mountain).
domain_category(labor_union_dues, snare).
domain_category(landscape_of_fear_2026, tangled_rope).
domain_category(large_cardinal_foundations, tangled_rope).
domain_category(large_cardinals_inaccessibility, mountain).
domain_category(latent_goal_activation, snare).
domain_category(latent_regulatory_bomb, snare).
domain_category(lavender_ai_targeting, snare).
domain_category(law_of_diminishing_returns, tangled_rope).
domain_category(layered_brain_processing, rope).
domain_category(lcdm_hubble_tension, snare).
domain_category(lcdm_small_scale_anomalies, tangled_rope).
domain_category(legacy_system_technical_debt, piton).
domain_category(legal_formalism_overhang, piton).
domain_category(legibility_trap, snare).
domain_category(legitimacy_without_capacity, snare).
domain_category(legitimacy_without_effectiveness, piton).
domain_category(lehman_repo_105, snare).
domain_category(liar_paradox, mountain).
domain_category(lindy_effect, tangled_rope).
domain_category(linguistic_relativity_cultural_framing, tangled_rope).
domain_category(liquidity_illusion, snare).
domain_category(litany_of_the_real, mountain).
domain_category(litchfield_sensitive_locations_2026, piton).
domain_category(lln_convergence, mountain).
domain_category(lobs_theorem, mountain).
domain_category(local_vs_global_optima, mountain).
domain_category(logistic_map_dynamics, tangled_rope).
domain_category(lorenz_attractor_dynamics, tangled_rope).
domain_category(lowenheim_skolem_theorem, mountain).
domain_category(lsd_microdosing_professional_openness, tangled_rope).
domain_category(lula_hemisphere_2026, snare).
domain_category(lung_transplant_protocol, snare).
domain_category(lyapunov_stability, mountain).
domain_category(magna_carta_liberties, rope).
domain_category(maha_recovery_2026, scaffold).
domain_category(maintenance_capacity_shortfall, piton).
domain_category(maladaptive_selection_process, snare).
domain_category(mandatrophic_margin_collapse, snare).
domain_category(mandatrophy_systemic_collapse, snare).
domain_category(manga_distribution_duopoly, snare).
domain_category(manganese_catalysis_2026, scaffold).
domain_category(marriage_market_asymmetry_2026, snare).
domain_category(mars_rover_navigational_autonomy, rope).
domain_category(martian_signal_latency, mountain).
domain_category(mass_market_extinction_2026, snare).
domain_category(matching_market_congestion_externality, tangled_rope).
domain_category(matching_markets_general, tangled_rope).
domain_category(material_tensile_strength, mountain).
domain_category(max_flow_min_cut, snare).
domain_category(mco_unit_system_discontinuity, piton).
domain_category(med_diet_consensus_2026, snare).
domain_category(medical_residency_match, snare).
domain_category(medieval_church_hegemony, snare).
domain_category(memetic_fitness_vs_truth, piton).
domain_category(meta_governance_overload, piton).
domain_category(meta_model_lock_in, snare).
domain_category(meta_nda, snare).
domain_category(meta_nuclear_power_agreement, tangled_rope).
domain_category(meta_pay_or_okay_model, snare).
domain_category(metabolic_constraint_cognition, snare).
domain_category(metamorphosis_samsa, snare).
domain_category(mexican_airline_merger, snare).
domain_category(micro_robot_electronics_integration, snare).
domain_category(microbiome_symbiosis, tangled_rope).
domain_category(microrobot_manipulation, rope).
domain_category(microwave_weapon_1, snare).
domain_category(migration_decision_threshold, tangled_rope).
domain_category(mil_std_461g_emi_control, snare).
domain_category(mil_std_810f_tailoring, snare).
domain_category(milano_cortina_2026, piton).
domain_category(minimax_decision_rule, mountain).
domain_category(minimax_theorem_game_equilibrium, snare).
domain_category(minnesota_sovereignty_2026, piton).
domain_category(misunderstanding_as_mismatch, snare).
domain_category(mit_tfus_2026, scaffold).
domain_category(model_autonomy_creep, snare).
domain_category(model_collapse_feedback_loop, snare).
domain_category(model_of_models_regression, snare).
domain_category(moltbook_agent_theater, piton).
domain_category(moltbook_breach_2026, piton).
domain_category(moltbot_religion, snare).
domain_category(mom_z14_2026, rope).
domain_category(monetary_regime_transition, snare).
domain_category(monty_hall_conditional_probability, mountain).
domain_category(moores_law, tangled_rope).
domain_category(moral_outsourcing, snare).
domain_category(mrna_melanoma_therapy, snare).
domain_category(multi_agent_reward_hacking, snare).
domain_category(multi_planetary_latency_lock, snare).
domain_category(mutual_defection_equilibrium, snare).
domain_category(mvt_theorem_constraint, rope).
domain_category(naming_as_control, snare).
domain_category(narcissistic_ego_maintenance, piton).
domain_category(narrative_capacity_exhaustion, snare).
domain_category(narrative_engineering_2026, scaffold).
domain_category(narrative_overfitting, snare).
domain_category(nasa_faster_better_cheaper, snare).
domain_category(nash_equilibrium_coordination, snare).
domain_category(nato_arctic_defense_cooperation, tangled_rope).
domain_category(ncaa_eligibility_rules, snare).
domain_category(nds_2022_pacing_challenge, snare).
domain_category(necessary_day_job, snare).
domain_category(negative_emissions_arbitrage, snare).
domain_category(net_zero_stabilization, snare).
domain_category(network_effects, snare).
domain_category(neural_interoperability, snare).
domain_category(neural_substrate_2026, snare).
domain_category(neurodiversity_spectrum, snare).
domain_category(neuroplasticity_plateau, snare).
domain_category(new_start_expiration, snare).
domain_category(news_paywall_inequality, snare).
domain_category(newtons_method_convergence, mountain).
domain_category(nfl_superbowl_halftime_exclusivity, snare).
domain_category(nfl_superbowl_marketing_regulation, snare).
domain_category(nine_day_buffer, snare).
domain_category(no_cloning_theorem, mountain).
domain_category(noether_isomorphism_access, snare).
domain_category(noether_theorem, mountain).
domain_category(noethers_theorem_symmetry, mountain).
domain_category(non_compete_agreements, snare).
domain_category(nonstandard_arithmetic_models, mountain).
domain_category(norm_erosion_threshold, snare).
domain_category(north_korea_songun_mandatrophy, snare).
domain_category(north_sea_wind_grid, tangled_rope).
domain_category(notary_ink_dependency, piton).
domain_category(nsl_hk, snare).
domain_category(nsw_transmission_bottleneck, snare).
domain_category(nuclear_order_2026, piton).
domain_category(nuclear_vacuum_2026, snare).
domain_category(nvidia_cuda_ecosystem_lockin, snare).
domain_category(ny_private_school_discount, snare).
domain_category(nyc_metrocard_art_licensing, snare).
domain_category(olympic_legacy_curling_investment, tangled_rope).
domain_category(olympic_medal_allocation, tangled_rope).
domain_category(omega1_patching_process, snare).
domain_category(omelet_perfection_complexity, rope).
domain_category(open_source_commons, rope).
domain_category(openai_api_access, snare).
domain_category(openai_codex_app_constraint, snare).
domain_category(openai_health_review, snare).
domain_category(openai_implicit_translator, snare).
domain_category(openai_prism_development, snare).
domain_category(openbsd_netiquette_protocol, snare).
domain_category(openclaw_data_lock_in, snare).
domain_category(openclaw_regulation, snare).
domain_category(openscholar_peer_review, snare).
domain_category(opioid_political_realignment_2026, snare).
domain_category(optimal_stopping_marriage, mountain).
domain_category(optimization_fragility, snare).
domain_category(oral_glp1_market_access, snare).
domain_category(orbital_data_center_2026, snare).
domain_category(oscar_campaign_spending, tangled_rope).
domain_category(other_peoples_troubles_2026, piton).
domain_category(overfitting_to_frameworks, snare).
domain_category(overton_window, snare).
domain_category(p_g_golden_pear_surveillance, snare).
domain_category(p_vs_np, mountain).
domain_category(panama_canal_ports, snare).
domain_category(pancreatic_cancer_lethality_v1, mountain).
domain_category(parable_fish_turtle, snare).
domain_category(pareto_principle, mountain).
domain_category(paris_municipal_reform_2026, snare).
domain_category(parkinsons_law, snare).
domain_category(participatory_observer_hypothesis, tangled_rope).
domain_category(path_dependence_lock_in, snare).
domain_category(paxsilica_framework, snare).
domain_category(pe_fund_level_leverage, snare).
domain_category(pe_rental_market_lockin, snare).
domain_category(peano_curve_mapping, mountain).
domain_category(permissive_software_licensing, rope).
domain_category(perovskite_self_etching, snare).
domain_category(perseverance_ai_drive, rope).
domain_category(perseverance_rover_autonomy, rope).
domain_category(peter_principle, snare).
domain_category(pla_loyalty_purge, snare).
domain_category(planetary_boundaries, snare).
domain_category(planetary_diet_constraint_2026, tangled_rope).
domain_category(planning_fallacy, snare).
domain_category(plastic_asphalt_mandate, snare).
domain_category(platform_app_store_duopoly, snare).
domain_category(platform_cooperativism_governance, rope).
domain_category(platonic_coparenting_decoupling, snare).
domain_category(pna, snare).
domain_category(po_investigation_protocol_bias, snare).
domain_category(poetic_verse_and_past, snare).
domain_category(poincare_conjecture, mountain).
domain_category(policy_lag_catastrophe, piton).
domain_category(politeness_face_negotiation, snare).
domain_category(portugal_ad_stability_2026, scaffold).
domain_category(portugal_polarization_threshold_2026, snare).
domain_category(portuguese_presidential_term_limits, tangled_rope).
domain_category(postman_survival_protocol, rope).
domain_category(power_set_axiomatic_extraction, tangled_rope).
domain_category(power_without_responsibility, snare).
domain_category(prestige_signal_inflation, piton).
domain_category(price_signal_corruption, snare).
domain_category(prime_age_male_unwork, snare).
domain_category(prime_number_theorem, mountain).
domain_category(prisoners_dilemma_equilibrium, mountain).
domain_category(private_credit_market_opacity, snare).
domain_category(private_identity_integration, rope).
domain_category(procedural_compliance_theater, piton).
domain_category(procedural_legitimacy_decay, snare).
domain_category(project_vault_2026, snare).
domain_category(project_vault_extraction_2026, snare).
domain_category(proof_of_work_consensus, snare).
domain_category(protocol_capture_eee, snare).
domain_category(protocol_drift_accumulation, snare).
domain_category(public_domain_commons, rope).
domain_category(publishing_embargo, tangled_rope).
domain_category(pythagorean_geometric_constancy, mountain).
domain_category(qualified_immunity, snare).
domain_category(quantum_entanglement_protocol, rope).
domain_category(quantum_measurement_gap, mountain).
domain_category(quantum_nonlocality_2026, mountain).
domain_category(quellcrist_falconer_justice, snare).
domain_category(quine_self_replication, tangled_rope).
domain_category(qwerty_vs_dvorak, tangled_rope).
domain_category(raac_school_maintenance, snare).
domain_category(radiologic_diagnostic_threshold, snare).
domain_category(rafah_crossing_lifeline, rope).
domain_category(railway_gauge_standard, piton).
domain_category(ramsey_numbers, mountain).
domain_category(rare_earth_coop_2026, rope).
domain_category(rare_earth_dependency, snare).
domain_category(rare_earth_export_restrictions, snare).
domain_category(rare_earth_hydrogen_extraction, snare).
domain_category(rare_earth_seabed_mining, snare).
domain_category(rational_inertia_trap, snare).
domain_category(recipe_scaling_ai, snare).
domain_category(reciprocity_laws_math, mountain).
domain_category(regional_military_deterrence_mideast, snare).
domain_category(regulatory_capture, snare).
domain_category(relativity_of_simultaneity, mountain).
domain_category(relativity_physical_invariance, mountain).
domain_category(rent_seeking_equilibrium, snare).
domain_category(repair_probe_incomplete, snare).
domain_category(reputational_cascade_failure, snare).
domain_category(responsibility_dilution, snare).
domain_category(responsibility_without_power, snare).
domain_category(rfc9293_state_machine, tangled_rope).
domain_category(rices_theorem_undecidability, mountain).
domain_category(riot_incentive_loop_2026, piton).
domain_category(risk_socialization_threshold, snare).
domain_category(ritual_transition_scaffold, tangled_rope).
domain_category(ritual_without_belief, snare).
domain_category(rn_proteus_adoption, scaffold).
domain_category(robustness_vs_efficiency_tradeoff, snare).
domain_category(rogers_commission_institutional_analysis, snare).
domain_category(rosen_bridge_protocol, snare).
domain_category(rotation_seven_black_soil, snare).
domain_category(rotation_seven_isolation, snare).
domain_category(rotation_seven_kubo_ranking, snare).
domain_category(royal_navy_middle_east_withdrawal, snare).
domain_category(rule_update_failure, piton).
domain_category(rules_based_international_order, snare).
domain_category(russells_paradox_self_reference, snare).
domain_category(russian_war_cannibalization, snare).
domain_category(sa_renewable_price_differential, tangled_rope).
domain_category(sadhu_integrity_protocol, tangled_rope).
domain_category(sapir_whorf_hypothesis, snare).
domain_category(sat_csp_complexity, tangled_rope).
domain_category(satellite_d2m_standard, tangled_rope).
domain_category(scam_compound_2026, snare).
domain_category(scientific_paradigm_lifecycle, snare).
domain_category(scurvy_maritime_extraction, snare).
domain_category(second_order_unintended_consequences, piton).
domain_category(seedance_export_restriction, snare).
domain_category(self_surpassing, snare).
domain_category(semantic_attack_surface, snare).
domain_category(semantic_overload_friction, snare).
domain_category(semiconductor_fabrication_chokepoint, snare).
domain_category(semiconductor_mission_2026, snare).
domain_category(shadow_fleet_sanctions_evasion, snare).
domain_category(shadow_pricing_failure, piton).
domain_category(shannon_entropy_limit, mountain).
domain_category(shannon_source_coding, mountain).
domain_category(shield_east_fortification, snare).
domain_category(ship_of_theseus, piton).
domain_category(shitty_feedback_handling, rope).
domain_category(shobies_existential_commitment, snare).
domain_category(shock_propagation_asymmetry, snare).
domain_category(sig_usd_protocol, rope).
domain_category(signal_without_control, snare).
domain_category(silent_dependency_activation, snare).
domain_category(silicon_lexicon_overload, snare).
domain_category(silklink_2026, scaffold).
domain_category(silver_scarcity_2026, mountain).
domain_category(sk_ai_act_2026, snare).
domain_category(skills_based_hiring, rope).
domain_category(skolems_paradox, mountain).
domain_category(sleep_debt_externality, snare).
domain_category(slow_crisis_invisibility, snare).
domain_category(sludge_bureaucratic_friction, snare).
domain_category(sm_addictive_design, snare).
domain_category(smartphone_ubiquity, snare).
domain_category(social_credit_architecture, snare).
domain_category(social_loafing, snare).
domain_category(social_media_participation_threshold, snare).
domain_category(social_narrative_casting, tangled_rope).
domain_category(soe_property_bailout, snare).
domain_category(soft_authoritarian_drift, snare).
domain_category(solar_system_weirdness, rope).
domain_category(somatic_focusing_awareness, rope).
domain_category(sorites_paradox, tangled_rope).
domain_category(south_china_sea_arbitration_2016_2026, snare).
domain_category(spain_digital_offensive_2026, snare).
domain_category(spv_variations_us_cold, rope).
domain_category(square_cube_law, mountain).
domain_category(st_petersburg_paradox, snare).
domain_category(stable_marriage_coordination, tangled_rope).
domain_category(star_formation_barrier_g0253, mountain).
domain_category(star_to_black_hole_observational_limit, mountain).
domain_category(start_treaty, snare).
domain_category(starwars_evolutionary_mutation, snare).
domain_category(statecraft_virtu, snare).
domain_category(status_flattening_effect, snare).
domain_category(steinmetz_valuation_asymmetry, snare).
domain_category(sti_clinical_testing_bottleneck, snare).
domain_category(stoic_logos_governance, snare).
domain_category(strait_coercion_2025, snare).
domain_category(strange_attractor_dynamics, snare).
domain_category(strange_attractor_systemic_risk, snare).
domain_category(strategic_deep_sea_rare_earth_mining, snare).
domain_category(streaming_bundling_mandate, snare).
domain_category(structural_extraction_without_actor, piton).
domain_category(sts86_ascent_checklist, tangled_rope).
domain_category(student_loan_default_cliff, snare).
domain_category(student_loan_interest_accrual, snare).
domain_category(sturgeons_law, mountain).
domain_category(suanne_coup_of_peace, snare).
domain_category(suanne_face_restoration, snare).
domain_category(sunk_cost_fallacy, snare).
domain_category(superbowl_advertising_extraction, snare).
domain_category(suslin_hypothesis_proof_limits, mountain).
domain_category(suslin_hypothesis_undecidability, mountain).
domain_category(swift_legacy_piton, piton).
domain_category(swift_piton_snap, scaffold).
domain_category(sylow_theorems_group_theory, mountain).
domain_category(synthetic_data_feedback_loop, snare).
domain_category(systemic_blindspot, snare).
domain_category(tail_risk_compression, snare).
domain_category(taiwan_existential_sovereignty, snare).
domain_category(taiwan_grand_bargain, snare).
domain_category(taiwan_ids_program, snare).
domain_category(taiwan_storm_2026, snare).
domain_category(taiwan_strait_hegemony_shift, snare).
domain_category(taiwan_university_application_system, snare).
domain_category(taliban_slavery_law_2024, snare).
domain_category(taxonomy_drift, piton).
domain_category(tcp_rfc9293_interoperability, rope).
domain_category(teaching_horses_to_sing, snare).
domain_category(tear_gas_repression_2026, snare).
domain_category(technocratic_overreach, snare).
domain_category(technological_point_of_no_return, snare).
domain_category(temporal_scale_arbitrage, snare).
domain_category(terrain_inaccessibility_wheeled_vehicles, mountain).
domain_category(texas_insurance_market_instability, snare).
domain_category(thai_article_112_mountain, tangled_rope).
domain_category(thai_senate_veto_2026, snare).
domain_category(the_bacchae_madness_protocol, snare).
domain_category(the_calm_protocol_suppression, snare).
domain_category(the_churn_systemic_upheaval, snare).
domain_category(the_wall_procedural_barrier, snare).
domain_category(theory_of_visitors, snare).
domain_category(thermodynamics_entropy, mountain).
domain_category(three_body_problem_predictability_limit, mountain).
domain_category(three_body_unpredictability, mountain).
domain_category(tiktok_us_divestiture_mandate, snare).
domain_category(toxic_social_infection, snare).
domain_category(toxoplasma_hub_2026, snare).
domain_category(tractarian_logic_limit, snare).
domain_category(trade_secret_law, snare).
domain_category(tragedy_of_the_commons, snare).
domain_category(transformer_self_attention, snare).
domain_category(transient_event_detection, rope).
domain_category(traveling_salesperson_problem, snare).
domain_category(trillion_bond_rush_2026, snare).
domain_category(trivial_topology_info_asymmetry, snare).
domain_category(trojan_war_spoils, snare).
domain_category(trump_critical_minerals, snare).
domain_category(trump_epa_greenhouse_gas_reversal, snare).
domain_category(trump_indian_tariffs_2026, snare).
domain_category(trump_making_china_great_2026, snare).
domain_category(trump_second_term_authoritarianism_2026, snare).
domain_category(tsp_computational_complexity, snare).
domain_category(tsp_duplicate_elimination, rope).
domain_category(tx_hispanic_pivot, snare).
domain_category(ua_mobilization_protector_cert, snare).
domain_category(ua_wartime_mobilization, snare).
domain_category(udhr_1948, rope).
domain_category(uk_graduate_visa_salary_threshold, snare).
domain_category(uk_help_to_buy_scheme, snare).
domain_category(uk_hicbc_trap, snare).
domain_category(uk_necc_formation, snare).
domain_category(uk_unpaid_care_system, snare).
domain_category(ukr_mobilization, snare).
domain_category(ukraine_tight_gas_pilot, snare).
domain_category(ulysses_aeolus_1904, piton).
domain_category(ulysses_calypso_1904, piton).
domain_category(ulysses_circe_1904, piton).
domain_category(ulysses_cyclops_1904, piton).
domain_category(ulysses_eumaeus_1904, piton).
domain_category(ulysses_hades_1904, piton).
domain_category(ulysses_ithaca_1904, piton).
domain_category(ulysses_lestrygonians_1904, piton).
domain_category(ulysses_lotus_1904, piton).
domain_category(ulysses_nausicaa_1904, piton).
domain_category(ulysses_oxen_1904, piton).
domain_category(ulysses_penelope_1904, piton).
domain_category(ulysses_proteus_1904, piton).
domain_category(ulysses_rocks_1904, piton).
domain_category(ulysses_school_1904, piton).
domain_category(ulysses_scylla_1904, piton).
domain_category(ulysses_sirens_1904, piton).
domain_category(ulysses_tower_1904, piton).
domain_category(un_high_seas_treaty_2026, tangled_rope).
domain_category(unclos_2026, rope).
domain_category(union_protection_underperformance, snare).
domain_category(universal_mathematics_communication, mountain).
domain_category(unrequited_love_protocol, snare).
domain_category(unrwa_eviction_order, snare).
domain_category(us_arms_transfer_policy, snare).
domain_category(us_canada_geopolitical_asymmetry, snare).
domain_category(us_china_chip_tariffs_v2, snare).
domain_category(us_debt_ceiling, snare).
domain_category(us_embargo_cuba, snare).
domain_category(us_employer_health_insurance, snare).
domain_category(us_greenland_envoy, snare).
domain_category(us_iran_drone_conflict, snare).
domain_category(us_isolationism_policy_2026, snare).
domain_category(us_israel_faa_502b_nonenforcement, snare).
domain_category(us_labor_mobility, snare).
domain_category(us_legal_standard_reasonable_doubt, snare).
domain_category(us_military_recruitment_advertising, snare).
domain_category(us_sanctions_icc_israel_case, snare).
domain_category(us_sdf_alliance_abandonment_2026, snare).
domain_category(us_suburban_zoning_2025, snare).
domain_category(us_taiwan_arms_sales, snare).
domain_category(us_tariffs_2025, snare).
domain_category(us_two_party_duopoly, snare).
domain_category(us_usmca_china_leverage, snare).
domain_category(us_vaccine_recommendation_dismantling_2026, snare).
domain_category(us_venezuela_blockade, snare).
domain_category(us_venezuela_oil_pressure, snare).
domain_category(us_venezuela_plausible_deniability_2025, snare).
domain_category(us_visa_lottery, snare).
domain_category(usc_26_469_passive_loss, snare).
domain_category(utopia_apocalypse_fragility, snare).
domain_category(value_alignment_drift, snare).
domain_category(value_extraction_plateau, snare).
domain_category(van_der_waerden_theorem, mountain).
domain_category(venezuela_oil_privatization_v1, snare).
domain_category(vertebrate_turning_point_2026, rope).
domain_category(vienna_quantum_superposition_2026, snare).
domain_category(viral_emergence_covid19_exemplar, tangled_rope).
domain_category(viral_transmission_rates, snare).
domain_category(visa_ipo_regulatory_compliance, tangled_rope).
domain_category(visa_judgment_sharing_agreement, rope).
domain_category(visibility_bias_governance, snare).
domain_category(vns_implant_for_trd, snare).
domain_category(weierstrass_proof_limits, mountain).
domain_category(whitehead_incompleteness, mountain).
domain_category(whitehead_problem_undecidability, mountain).
domain_category(wikipedia_crowdsourcing_2026, rope).
domain_category(wikipedia_noncommercial_model, rope).
domain_category(wikipedia_notability_requirement_2026, tangled_rope).
domain_category(winners_curse, snare).
domain_category(working_dog_training, tangled_rope).
domain_category(world_factbook_sunset_2026, piton).
domain_category(wpl_scotland, snare).
domain_category(xi_mao_ideological_centralization, snare).
domain_category(yangtze_fishing_ban, snare).
domain_category(yc_equity_squeeze, snare).
domain_category(yt_ai_slop_incentive, snare).
domain_category(zipfs_law, snare).
domain_category(zombie_reasoning_2026, snare).
