:- module(validation_suite, [run_dynamic_suite/0]).
:- use_module(library(prolog_stack)).
:- use_module(library(time)).
:- use_module(scenario_manager).
:- use_module(data_validation).
:- use_module(report_generator).

:- chdir('../prolog').

:- dynamic test_passed/1, test_failed/3, test_case/4.

% --- Test Case Definitions ---
test_case('testsets/abrahamic_covenant__isaac_covenant_reading.pl', 'abrahamic_covenant__isaac_covenant_reading', 'ABRAHAMIC_COVENANT__ISAAC_COVENANT_READING', 1).
test_case('testsets/abrahamic_covenant__ishmael_covenant_reading.pl', 'abrahamic_covenant__ishmael_covenant_reading', 'ABRAHAMIC_COVENANT__ISHMAEL_COVENANT_READING', 2).
test_case('testsets/abrahamic_covenant__land_promise_constraint.pl', 'abrahamic_covenant__land_promise_constraint', 'ABRAHAMIC_COVENANT__LAND_PROMISE_CONSTRAINT', 3).
test_case('testsets/acceptable_risk_for_energy__catastrophic_tail_dominant.pl', 'acceptable_risk_for_energy__catastrophic_tail_dominant', 'ACCEPTABLE_RISK_FOR_ENERGY__CATASTROPHIC_TAIL_DOMINANT', 4).
test_case('testsets/acceptable_risk_for_energy__comparative_risk_dominant.pl', 'acceptable_risk_for_energy__comparative_risk_dominant', 'ACCEPTABLE_RISK_FOR_ENERGY__COMPARATIVE_RISK_DOMINANT', 5).
test_case('testsets/acceptable_risk_for_energy__expected_value_dominant.pl', 'acceptable_risk_for_energy__expected_value_dominant', 'ACCEPTABLE_RISK_FOR_ENERGY__EXPECTED_VALUE_DOMINANT', 6).
test_case('testsets/adjunctification_of_university_teaching_c0.pl', 'adjunctification_of_university_teaching_c0', 'ADJUNCTIFICATION_OF_UNIVERSITY_TEACHING_C0', 7).
test_case('testsets/ai_alignment_commitment__ethics_justice_reading.pl', 'ai_alignment_commitment__ethics_justice_reading', 'AI_ALIGNMENT_COMMITMENT__ETHICS_JUSTICE_READING', 8).
test_case('testsets/ai_alignment_commitment__integrated_reading.pl', 'ai_alignment_commitment__integrated_reading', 'AI_ALIGNMENT_COMMITMENT__INTEGRATED_READING', 9).
test_case('testsets/ai_alignment_commitment__safety_control_reading.pl', 'ai_alignment_commitment__safety_control_reading', 'AI_ALIGNMENT_COMMITMENT__SAFETY_CONTROL_READING', 10).
test_case('testsets/ai_dignity_safeguarding__autonomy_rights_reading.pl', 'ai_dignity_safeguarding__autonomy_rights_reading', 'AI_DIGNITY_SAFEGUARDING__AUTONOMY_RIGHTS_READING', 11).
test_case('testsets/ai_dignity_safeguarding__imago_dei_reading.pl', 'ai_dignity_safeguarding__imago_dei_reading', 'AI_DIGNITY_SAFEGUARDING__IMAGO_DEI_READING', 12).
test_case('testsets/ai_dignity_safeguarding__posthuman_continuity_reading.pl', 'ai_dignity_safeguarding__posthuman_continuity_reading', 'AI_DIGNITY_SAFEGUARDING__POSTHUMAN_CONTINUITY_READING', 13).
test_case('testsets/ai_human_relationship__incarnational_humanism.pl', 'ai_human_relationship__incarnational_humanism', 'AI_HUMAN_RELATIONSHIP__INCARNATIONAL_HUMANISM', 14).
test_case('testsets/ai_human_relationship__instrumental_subsidiarity.pl', 'ai_human_relationship__instrumental_subsidiarity', 'AI_HUMAN_RELATIONSHIP__INSTRUMENTAL_SUBSIDIARITY', 15).
test_case('testsets/ai_human_relationship__technocratic_optimization.pl', 'ai_human_relationship__technocratic_optimization', 'AI_HUMAN_RELATIONSHIP__TECHNOCRATIC_OPTIMIZATION', 16).
test_case('testsets/ai_risk_governance_priority__bridge_reading.pl', 'ai_risk_governance_priority__bridge_reading', 'AI_RISK_GOVERNANCE_PRIORITY__BRIDGE_READING', 17).
test_case('testsets/ai_risk_governance_priority__existential_risk_reading.pl', 'ai_risk_governance_priority__existential_risk_reading', 'AI_RISK_GOVERNANCE_PRIORITY__EXISTENTIAL_RISK_READING', 18).
test_case('testsets/ai_risk_governance_priority__near_term_harms_reading.pl', 'ai_risk_governance_priority__near_term_harms_reading', 'AI_RISK_GOVERNANCE_PRIORITY__NEAR_TERM_HARMS_READING', 19).
test_case('testsets/all_men_created_equal__originalist_reading.pl', 'all_men_created_equal__originalist_reading', 'ALL_MEN_CREATED_EQUAL__ORIGINALIST_READING', 20).
test_case('testsets/all_men_created_equal__textualist_paradox_reading.pl', 'all_men_created_equal__textualist_paradox_reading', 'ALL_MEN_CREATED_EQUAL__TEXTUALIST_PARADOX_READING', 21).
test_case('testsets/all_men_created_equal__universalist_reading.pl', 'all_men_created_equal__universalist_reading', 'ALL_MEN_CREATED_EQUAL__UNIVERSALIST_READING', 22).
test_case('testsets/aneyoshi_land_use_prohibition__behavioral_competence_reading.pl', 'aneyoshi_land_use_prohibition__behavioral_competence_reading', 'ANEYOSHI_LAND_USE_PROHIBITION__BEHAVIORAL_COMPETENCE_READING', 23).
test_case('testsets/aneyoshi_land_use_prohibition__commemorative_husk_reading.pl', 'aneyoshi_land_use_prohibition__commemorative_husk_reading', 'ANEYOSHI_LAND_USE_PROHIBITION__COMMEMORATIVE_HUSK_READING', 24).
test_case('testsets/article_17_complementarity__international_oversight_reading.pl', 'article_17_complementarity__international_oversight_reading', 'ARTICLE_17_COMPLEMENTARITY__INTERNATIONAL_OVERSIGHT_READING', 25).
test_case('testsets/article_17_complementarity__national_primacy_reading.pl', 'article_17_complementarity__national_primacy_reading', 'ARTICLE_17_COMPLEMENTARITY__NATIONAL_PRIMACY_READING', 26).
test_case('testsets/article_9_war_renunciation__collective_self_defense_reading.pl', 'article_9_war_renunciation__collective_self_defense_reading', 'ARTICLE_9_WAR_RENUNCIATION__COLLECTIVE_SELF_DEFENSE_READING', 27).
test_case('testsets/article_9_war_renunciation__inherent_right_reading.pl', 'article_9_war_renunciation__inherent_right_reading', 'ARTICLE_9_WAR_RENUNCIATION__INHERENT_RIGHT_READING', 28).
test_case('testsets/article_9_war_renunciation__strict_pacifist_reading.pl', 'article_9_war_renunciation__strict_pacifist_reading', 'ARTICLE_9_WAR_RENUNCIATION__STRICT_PACIFIST_READING', 29).
test_case('testsets/balfour_mandate_instruments__dual_obligation_indigenous_rights.pl', 'balfour_mandate_instruments__dual_obligation_indigenous_rights', 'BALFOUR_MANDATE_INSTRUMENTS__DUAL_OBLIGATION_INDIGENOUS_RIGHTS', 30).
test_case('testsets/balfour_mandate_instruments__jewish_national_home_primacy.pl', 'balfour_mandate_instruments__jewish_national_home_primacy', 'BALFOUR_MANDATE_INSTRUMENTS__JEWISH_NATIONAL_HOME_PRIMACY', 31).
test_case('testsets/balfour_mandate_instruments__mandatory_interpretive_discretion.pl', 'balfour_mandate_instruments__mandatory_interpretive_discretion', 'BALFOUR_MANDATE_INSTRUMENTS__MANDATORY_INTERPRETIVE_DISCRETION', 32).
test_case('testsets/biblical_authority__conciliar_reading.pl', 'biblical_authority__conciliar_reading', 'BIBLICAL_AUTHORITY__CONCILIAR_READING', 33).
test_case('testsets/biblical_authority__sola_scriptura_reading.pl', 'biblical_authority__sola_scriptura_reading', 'BIBLICAL_AUTHORITY__SOLA_SCRIPTURA_READING', 34).
test_case('testsets/biblical_authority__tradition_scripture_reading.pl', 'biblical_authority__tradition_scripture_reading', 'BIBLICAL_AUTHORITY__TRADITION_SCRIPTURE_READING', 35).
test_case('testsets/bitcoin_whitepaper_purpose__electronic_cash_reading.pl', 'bitcoin_whitepaper_purpose__electronic_cash_reading', 'BITCOIN_WHITEPAPER_PURPOSE__ELECTRONIC_CASH_READING', 36).
test_case('testsets/bitcoin_whitepaper_purpose__nakamoto_oracle_opacity.pl', 'bitcoin_whitepaper_purpose__nakamoto_oracle_opacity', 'BITCOIN_WHITEPAPER_PURPOSE__NAKAMOTO_ORACLE_OPACITY', 37).
test_case('testsets/bitcoin_whitepaper_purpose__store_of_value_reading.pl', 'bitcoin_whitepaper_purpose__store_of_value_reading', 'BITCOIN_WHITEPAPER_PURPOSE__STORE_OF_VALUE_READING', 38).
test_case('testsets/border_legitimacy__freedom_of_movement_reading.pl', 'border_legitimacy__freedom_of_movement_reading', 'BORDER_LEGITIMACY__FREEDOM_OF_MOVEMENT_READING', 39).
test_case('testsets/border_legitimacy__humanitarian_obligation_reading.pl', 'border_legitimacy__humanitarian_obligation_reading', 'BORDER_LEGITIMACY__HUMANITARIAN_OBLIGATION_READING', 40).
test_case('testsets/border_legitimacy__sovereignty_reading.pl', 'border_legitimacy__sovereignty_reading', 'BORDER_LEGITIMACY__SOVEREIGNTY_READING', 41).
test_case('testsets/border_normative_status__freedom_primary.pl', 'border_normative_status__freedom_primary', 'BORDER_NORMATIVE_STATUS__FREEDOM_PRIMARY', 42).
test_case('testsets/border_normative_status__qualified_sovereignty.pl', 'border_normative_status__qualified_sovereignty', 'BORDER_NORMATIVE_STATUS__QUALIFIED_SOVEREIGNTY', 43).
test_case('testsets/border_normative_status__sovereignty_primary.pl', 'border_normative_status__sovereignty_primary', 'BORDER_NORMATIVE_STATUS__SOVEREIGNTY_PRIMARY', 44).
test_case('testsets/catastrophe_memory_transmission__hybrid_embedded_reading.pl', 'catastrophe_memory_transmission__hybrid_embedded_reading', 'CATASTROPHE_MEMORY_TRANSMISSION__HYBRID_EMBEDDED_READING', 45).
test_case('testsets/catastrophe_memory_transmission__operational_competence_reading.pl', 'catastrophe_memory_transmission__operational_competence_reading', 'CATASTROPHE_MEMORY_TRANSMISSION__OPERATIONAL_COMPETENCE_READING', 46).
test_case('testsets/catastrophe_memory_transmission__symbol_continuity_reading.pl', 'catastrophe_memory_transmission__symbol_continuity_reading', 'CATASTROPHE_MEMORY_TRANSMISSION__SYMBOL_CONTINUITY_READING', 47).
test_case('testsets/cbdr_principle__historical_responsibility_reading.pl', 'cbdr_principle__historical_responsibility_reading', 'CBDR_PRINCIPLE__HISTORICAL_RESPONSIBILITY_READING', 48).
test_case('testsets/cbdr_principle__voluntary_commitment_reading.pl', 'cbdr_principle__voluntary_commitment_reading', 'CBDR_PRINCIPLE__VOLUNTARY_COMMITMENT_READING', 49).
test_case('testsets/climate_mitigation_imperative__opportunity_cost_reading.pl', 'climate_mitigation_imperative__opportunity_cost_reading', 'CLIMATE_MITIGATION_IMPERATIVE__OPPORTUNITY_COST_READING', 50).
test_case('testsets/climate_mitigation_imperative__portfolio_optimization_reading.pl', 'climate_mitigation_imperative__portfolio_optimization_reading', 'CLIMATE_MITIGATION_IMPERATIVE__PORTFOLIO_OPTIMIZATION_READING', 51).
test_case('testsets/climate_mitigation_imperative__systems_transition_reading.pl', 'climate_mitigation_imperative__systems_transition_reading', 'CLIMATE_MITIGATION_IMPERATIVE__SYSTEMS_TRANSITION_READING', 52).
test_case('testsets/commerce_clause_scope__broad_effects_test.pl', 'commerce_clause_scope__broad_effects_test', 'COMMERCE_CLAUSE_SCOPE__BROAD_EFFECTS_TEST', 53).
test_case('testsets/commerce_clause_scope__intermediate_channels.pl', 'commerce_clause_scope__intermediate_channels', 'COMMERCE_CLAUSE_SCOPE__INTERMEDIATE_CHANNELS', 54).
test_case('testsets/commerce_clause_scope__narrow_originalist.pl', 'commerce_clause_scope__narrow_originalist', 'COMMERCE_CLAUSE_SCOPE__NARROW_ORIGINALIST', 55).
test_case('testsets/competence_exercise_requirement__catastrophe_as_necessary_anchor.pl', 'competence_exercise_requirement__catastrophe_as_necessary_anchor', 'COMPETENCE_EXERCISE_REQUIREMENT__CATASTROPHE_AS_NECESSARY_ANCHOR', 56).
test_case('testsets/competence_exercise_requirement__hybrid_dependency.pl', 'competence_exercise_requirement__hybrid_dependency', 'COMPETENCE_EXERCISE_REQUIREMENT__HYBRID_DEPENDENCY', 57).
test_case('testsets/competence_exercise_requirement__simulation_as_adequate_exercise.pl', 'competence_exercise_requirement__simulation_as_adequate_exercise', 'COMPETENCE_EXERCISE_REQUIREMENT__SIMULATION_AS_ADEQUATE_EXERCISE', 58).
test_case('testsets/competence_exercise_validity__continuous_refresh_hybrid.pl', 'competence_exercise_validity__continuous_refresh_hybrid', 'COMPETENCE_EXERCISE_VALIDITY__CONTINUOUS_REFRESH_HYBRID', 59).
test_case('testsets/competence_exercise_validity__real_catastrophe_only.pl', 'competence_exercise_validity__real_catastrophe_only', 'COMPETENCE_EXERCISE_VALIDITY__REAL_CATASTROPHE_ONLY', 60).
test_case('testsets/competence_exercise_validity__simulation_as_proxy.pl', 'competence_exercise_validity__simulation_as_proxy', 'COMPETENCE_EXERCISE_VALIDITY__SIMULATION_AS_PROXY', 61).
test_case('testsets/constitutional_text_authority__living_constitutionalist_reading.pl', 'constitutional_text_authority__living_constitutionalist_reading', 'CONSTITUTIONAL_TEXT_AUTHORITY__LIVING_CONSTITUTIONALIST_READING', 62).
test_case('testsets/constitutional_text_authority__originalist_reading.pl', 'constitutional_text_authority__originalist_reading', 'CONSTITUTIONAL_TEXT_AUTHORITY__ORIGINALIST_READING', 63).
test_case('testsets/constitutional_text_authority__positivist_reading.pl', 'constitutional_text_authority__positivist_reading', 'CONSTITUTIONAL_TEXT_AUTHORITY__POSITIVIST_READING', 64).
test_case('testsets/correct_latin__continuity_reading.pl', 'correct_latin__continuity_reading', 'CORRECT_LATIN__CONTINUITY_READING', 65).
test_case('testsets/correct_latin__discontinuity_reading.pl', 'correct_latin__discontinuity_reading', 'CORRECT_LATIN__DISCONTINUITY_READING', 66).
test_case('testsets/correct_latin__hybrid_reading.pl', 'correct_latin__hybrid_reading', 'CORRECT_LATIN__HYBRID_READING', 67).
test_case('testsets/correct_latin_kernel__continuity_reading.pl', 'correct_latin_kernel__continuity_reading', 'CORRECT_LATIN_KERNEL__CONTINUITY_READING', 68).
test_case('testsets/correct_latin_kernel__discontinuity_reading.pl', 'correct_latin_kernel__discontinuity_reading', 'CORRECT_LATIN_KERNEL__DISCONTINUITY_READING', 69).
test_case('testsets/correct_latin_kernel__hybrid_reading.pl', 'correct_latin_kernel__hybrid_reading', 'CORRECT_LATIN_KERNEL__HYBRID_READING', 70).
test_case('testsets/cultural_property_legal_corpus__indigenous_stewardship_reading.pl', 'cultural_property_legal_corpus__indigenous_stewardship_reading', 'CULTURAL_PROPERTY_LEGAL_CORPUS__INDIGENOUS_STEWARDSHIP_READING', 71).
test_case('testsets/cultural_property_legal_corpus__sovereign_repatriation_reading.pl', 'cultural_property_legal_corpus__sovereign_repatriation_reading', 'CULTURAL_PROPERTY_LEGAL_CORPUS__SOVEREIGN_REPATRIATION_READING', 72).
test_case('testsets/cultural_property_legal_corpus__universal_heritage_reading.pl', 'cultural_property_legal_corpus__universal_heritage_reading', 'CULTURAL_PROPERTY_LEGAL_CORPUS__UNIVERSAL_HERITAGE_READING', 73).
test_case('testsets/decalogue_image_prohibition__iconoclast_reading.pl', 'decalogue_image_prohibition__iconoclast_reading', 'DECALOGUE_IMAGE_PROHIBITION__ICONOCLAST_READING', 74).
test_case('testsets/decalogue_image_prohibition__iconodule_reading.pl', 'decalogue_image_prohibition__iconodule_reading', 'DECALOGUE_IMAGE_PROHIBITION__ICONODULE_READING', 75).
test_case('testsets/decalogue_image_prohibition__moderate_iconoclast_reading.pl', 'decalogue_image_prohibition__moderate_iconoclast_reading', 'DECALOGUE_IMAGE_PROHIBITION__MODERATE_ICONOCLAST_READING', 76).
test_case('testsets/demographic_skill_mismatch_c0.pl', 'demographic_skill_mismatch_c0', 'DEMOGRAPHIC_SKILL_MISMATCH_C0', 77).
test_case('testsets/digital_money_emergence_boundary__conceptualization_reading.pl', 'digital_money_emergence_boundary__conceptualization_reading', 'DIGITAL_MONEY_EMERGENCE_BOUNDARY__CONCEPTUALIZATION_READING', 78).
test_case('testsets/digital_money_emergence_boundary__consumer_holdings_reading.pl', 'digital_money_emergence_boundary__consumer_holdings_reading', 'DIGITAL_MONEY_EMERGENCE_BOUNDARY__CONSUMER_HOLDINGS_READING', 79).
test_case('testsets/digital_money_emergence_boundary__infrastructure_reading.pl', 'digital_money_emergence_boundary__infrastructure_reading', 'DIGITAL_MONEY_EMERGENCE_BOUNDARY__INFRASTRUCTURE_READING', 80).
test_case('testsets/digital_money_origin__became_thinkable_reading.pl', 'digital_money_origin__became_thinkable_reading', 'DIGITAL_MONEY_ORIGIN__BECAME_THINKABLE_READING', 81).
test_case('testsets/digital_money_origin__first_held_reading.pl', 'digital_money_origin__first_held_reading', 'DIGITAL_MONEY_ORIGIN__FIRST_HELD_READING', 82).
test_case('testsets/digital_money_origin__regulatory_recognition_reading.pl', 'digital_money_origin__regulatory_recognition_reading', 'DIGITAL_MONEY_ORIGIN__REGULATORY_RECOGNITION_READING', 83).
test_case('testsets/divine_legitimacy_substrate__amun_polytheistic_reading.pl', 'divine_legitimacy_substrate__amun_polytheistic_reading', 'DIVINE_LEGITIMACY_SUBSTRATE__AMUN_POLYTHEISTIC_READING', 84).
test_case('testsets/divine_legitimacy_substrate__atenist_monotheistic_reading.pl', 'divine_legitimacy_substrate__atenist_monotheistic_reading', 'DIVINE_LEGITIMACY_SUBSTRATE__ATENIST_MONOTHEISTIC_READING', 85).
test_case('testsets/divine_legitimacy_substrate__folk_syncretistic_reading.pl', 'divine_legitimacy_substrate__folk_syncretistic_reading', 'DIVINE_LEGITIMACY_SUBSTRATE__FOLK_SYNCRETISTIC_READING', 86).
test_case('testsets/dollar_gold_convertibility__policy_flexible_reading.pl', 'dollar_gold_convertibility__policy_flexible_reading', 'DOLLAR_GOLD_CONVERTIBILITY__POLICY_FLEXIBLE_READING', 87).
test_case('testsets/dollar_gold_convertibility__strict_convertibility_reading.pl', 'dollar_gold_convertibility__strict_convertibility_reading', 'DOLLAR_GOLD_CONVERTIBILITY__STRICT_CONVERTIBILITY_READING', 88).
test_case('testsets/dollar_gold_convertibility__triffin_structural_reading.pl', 'dollar_gold_convertibility__triffin_structural_reading', 'DOLLAR_GOLD_CONVERTIBILITY__TRIFFIN_STRUCTURAL_READING', 89).
test_case('testsets/dual_class_legitimacy__disclosure_consent.pl', 'dual_class_legitimacy__disclosure_consent', 'DUAL_CLASS_LEGITIMACY__DISCLOSURE_CONSENT', 90).
test_case('testsets/dual_class_legitimacy__founder_stewardship.pl', 'dual_class_legitimacy__founder_stewardship', 'DUAL_CLASS_LEGITIMACY__FOUNDER_STEWARDSHIP', 91).
test_case('testsets/dual_class_legitimacy__minority_extraction.pl', 'dual_class_legitimacy__minority_extraction', 'DUAL_CLASS_LEGITIMACY__MINORITY_EXTRACTION', 92).
test_case('testsets/ecb_mandate_article_127__climate_incorporation.pl', 'ecb_mandate_article_127__climate_incorporation', 'ECB_MANDATE_ARTICLE_127__CLIMATE_INCORPORATION', 93).
test_case('testsets/ecb_mandate_article_127__expansive_secondary_objectives.pl', 'ecb_mandate_article_127__expansive_secondary_objectives', 'ECB_MANDATE_ARTICLE_127__EXPANSIVE_SECONDARY_OBJECTIVES', 94).
test_case('testsets/ecb_mandate_article_127__orthodox_price_stability.pl', 'ecb_mandate_article_127__orthodox_price_stability', 'ECB_MANDATE_ARTICLE_127__ORTHODOX_PRICE_STABILITY', 95).
test_case('testsets/employment_boundary__formalist_employment_reading.pl', 'employment_boundary__formalist_employment_reading', 'EMPLOYMENT_BOUNDARY__FORMALIST_EMPLOYMENT_READING', 96).
test_case('testsets/employment_boundary__hybrid_security_reading.pl', 'employment_boundary__hybrid_security_reading', 'EMPLOYMENT_BOUNDARY__HYBRID_SECURITY_READING', 97).
test_case('testsets/employment_boundary__substantive_employment_reading.pl', 'employment_boundary__substantive_employment_reading', 'EMPLOYMENT_BOUNDARY__SUBSTANTIVE_EMPLOYMENT_READING', 98).
test_case('testsets/end_of_life_authority__autonomy_reading.pl', 'end_of_life_authority__autonomy_reading', 'END_OF_LIFE_AUTHORITY__AUTONOMY_READING', 99).
test_case('testsets/end_of_life_authority__sanctity_reading.pl', 'end_of_life_authority__sanctity_reading', 'END_OF_LIFE_AUTHORITY__SANCTITY_READING', 100).
test_case('testsets/end_of_life_authority__slippery_slope_mechanism.pl', 'end_of_life_authority__slippery_slope_mechanism', 'END_OF_LIFE_AUTHORITY__SLIPPERY_SLOPE_MECHANISM', 101).
test_case('testsets/eternal_marriage_covenant__immutable_commandment_reading.pl', 'eternal_marriage_covenant__immutable_commandment_reading', 'ETERNAL_MARRIAGE_COVENANT__IMMUTABLE_COMMANDMENT_READING', 102).
test_case('testsets/eternal_marriage_covenant__prophetic_override_reading.pl', 'eternal_marriage_covenant__prophetic_override_reading', 'ETERNAL_MARRIAGE_COVENANT__PROPHETIC_OVERRIDE_READING', 103).
test_case('testsets/eternal_marriage_covenant__temporal_accommodation_reading.pl', 'eternal_marriage_covenant__temporal_accommodation_reading', 'ETERNAL_MARRIAGE_COVENANT__TEMPORAL_ACCOMMODATION_READING', 104).
test_case('testsets/exercise_as_competence_maintenance__hybrid_decay_reading.pl', 'exercise_as_competence_maintenance__hybrid_decay_reading', 'EXERCISE_AS_COMPETENCE_MAINTENANCE__HYBRID_DECAY_READING', 105).
test_case('testsets/exercise_as_competence_maintenance__lived_catastrophe_necessity_reading.pl', 'exercise_as_competence_maintenance__lived_catastrophe_necessity_reading', 'EXERCISE_AS_COMPETENCE_MAINTENANCE__LIVED_CATASTROPHE_NECESSITY_READING', 106).
test_case('testsets/exercise_as_competence_maintenance__simulation_sufficiency_reading.pl', 'exercise_as_competence_maintenance__simulation_sufficiency_reading', 'EXERCISE_AS_COMPETENCE_MAINTENANCE__SIMULATION_SUFFICIENCY_READING', 107).
test_case('testsets/family_law_authority__christian_canonical_reading.pl', 'family_law_authority__christian_canonical_reading', 'FAMILY_LAW_AUTHORITY__CHRISTIAN_CANONICAL_READING', 108).
test_case('testsets/family_law_authority__hindu_dharmashastra_reading.pl', 'family_law_authority__hindu_dharmashastra_reading', 'FAMILY_LAW_AUTHORITY__HINDU_DHARMASHASTRA_READING', 109).
test_case('testsets/family_law_authority__muslim_shariat_reading.pl', 'family_law_authority__muslim_shariat_reading', 'FAMILY_LAW_AUTHORITY__MUSLIM_SHARIAT_READING', 110).
test_case('testsets/family_law_authority__parsi_zoroastrian_reading.pl', 'family_law_authority__parsi_zoroastrian_reading', 'FAMILY_LAW_AUTHORITY__PARSI_ZOROASTRIAN_READING', 111).
test_case('testsets/family_law_authority__secular_contractual_reading.pl', 'family_law_authority__secular_contractual_reading', 'FAMILY_LAW_AUTHORITY__SECULAR_CONTRACTUAL_READING', 112).
test_case('testsets/federation_membership__integration_reading.pl', 'federation_membership__integration_reading', 'FEDERATION_MEMBERSHIP__INTEGRATION_READING', 113).
test_case('testsets/federation_membership__sovereignty_reading.pl', 'federation_membership__sovereignty_reading', 'FEDERATION_MEMBERSHIP__SOVEREIGNTY_READING', 114).
test_case('testsets/federation_membership_obligations__integration_primary.pl', 'federation_membership_obligations__integration_primary', 'FEDERATION_MEMBERSHIP_OBLIGATIONS__INTEGRATION_PRIMARY', 115).
test_case('testsets/federation_membership_obligations__member_sovereignty_primary.pl', 'federation_membership_obligations__member_sovereignty_primary', 'FEDERATION_MEMBERSHIP_OBLIGATIONS__MEMBER_SOVEREIGNTY_PRIMARY', 116).
test_case('testsets/federation_membership_obligations__selective_solidarity.pl', 'federation_membership_obligations__selective_solidarity', 'FEDERATION_MEMBERSHIP_OBLIGATIONS__SELECTIVE_SOLIDARITY', 117).
test_case('testsets/feud_obligation_kernel__christianized_pacification_reading.pl', 'feud_obligation_kernel__christianized_pacification_reading', 'FEUD_OBLIGATION_KERNEL__CHRISTIANIZED_PACIFICATION_READING', 118).
test_case('testsets/feud_obligation_kernel__extraction_cycle_reading.pl', 'feud_obligation_kernel__extraction_cycle_reading', 'FEUD_OBLIGATION_KERNEL__EXTRACTION_CYCLE_READING', 119).
test_case('testsets/feud_obligation_kernel__stateless_coordination_reading.pl', 'feud_obligation_kernel__stateless_coordination_reading', 'FEUD_OBLIGATION_KERNEL__STATELESS_COORDINATION_READING', 120).
test_case('testsets/fifth_republic_constitution__cohabitation_equilibrium_reading.pl', 'fifth_republic_constitution__cohabitation_equilibrium_reading', 'FIFTH_REPUBLIC_CONSTITUTION__COHABITATION_EQUILIBRIUM_READING', 121).
test_case('testsets/fifth_republic_constitution__hyper_presidential_reading.pl', 'fifth_republic_constitution__hyper_presidential_reading', 'FIFTH_REPUBLIC_CONSTITUTION__HYPER_PRESIDENTIAL_READING', 122).
test_case('testsets/fifth_republic_constitution__parliamentary_constraint_reading.pl', 'fifth_republic_constitution__parliamentary_constraint_reading', 'FIFTH_REPUBLIC_CONSTITUTION__PARLIAMENTARY_CONSTRAINT_READING', 123).
test_case('testsets/gold_fiat_transition_mechanism__automatic_constraint_reading.pl', 'gold_fiat_transition_mechanism__automatic_constraint_reading', 'GOLD_FIAT_TRANSITION_MECHANISM__AUTOMATIC_CONSTRAINT_READING', 124).
test_case('testsets/gold_fiat_transition_mechanism__composite_overdetermination_reading.pl', 'gold_fiat_transition_mechanism__composite_overdetermination_reading', 'GOLD_FIAT_TRANSITION_MECHANISM__COMPOSITE_OVERDETERMINATION_READING', 125).
test_case('testsets/gold_fiat_transition_mechanism__creditor_discipline_reading.pl', 'gold_fiat_transition_mechanism__creditor_discipline_reading', 'GOLD_FIAT_TRANSITION_MECHANISM__CREDITOR_DISCIPLINE_READING', 126).
test_case('testsets/gpl_copyleft_scope__enforcement_vacuum_reading.pl', 'gpl_copyleft_scope__enforcement_vacuum_reading', 'GPL_COPYLEFT_SCOPE__ENFORCEMENT_VACUUM_READING', 127).
test_case('testsets/gpl_copyleft_scope__narrow_scope_reading.pl', 'gpl_copyleft_scope__narrow_scope_reading', 'GPL_COPYLEFT_SCOPE__NARROW_SCOPE_READING', 128).
test_case('testsets/gpl_copyleft_scope__strong_copyleft_reading.pl', 'gpl_copyleft_scope__strong_copyleft_reading', 'GPL_COPYLEFT_SCOPE__STRONG_COPYLEFT_READING', 129).
test_case('testsets/hebrew_continuity__bridge_pidginized.pl', 'hebrew_continuity__bridge_pidginized', 'HEBREW_CONTINUITY__BRIDGE_PIDGINIZED', 130).
test_case('testsets/hebrew_continuity__liturgical_preservation.pl', 'hebrew_continuity__liturgical_preservation', 'HEBREW_CONTINUITY__LITURGICAL_PRESERVATION', 131).
test_case('testsets/hebrew_continuity__native_generative.pl', 'hebrew_continuity__native_generative', 'HEBREW_CONTINUITY__NATIVE_GENERATIVE', 132).
test_case('testsets/hebrew_living_language__literary_revival_reading.pl', 'hebrew_living_language__literary_revival_reading', 'HEBREW_LIVING_LANGUAGE__LITERARY_REVIVAL_READING', 133).
test_case('testsets/hebrew_living_language__liturgical_continuity_reading.pl', 'hebrew_living_language__liturgical_continuity_reading', 'HEBREW_LIVING_LANGUAGE__LITURGICAL_CONTINUITY_READING', 134).
test_case('testsets/hebrew_living_language__native_generation_reading.pl', 'hebrew_living_language__native_generation_reading', 'HEBREW_LIVING_LANGUAGE__NATIVE_GENERATION_READING', 135).
test_case('testsets/hebrew_vitality__hybrid_continuity_reading.pl', 'hebrew_vitality__hybrid_continuity_reading', 'HEBREW_VITALITY__HYBRID_CONTINUITY_READING', 136).
test_case('testsets/hebrew_vitality__liturgical_reading.pl', 'hebrew_vitality__liturgical_reading', 'HEBREW_VITALITY__LITURGICAL_READING', 137).
test_case('testsets/hebrew_vitality__native_daily_reading.pl', 'hebrew_vitality__native_daily_reading', 'HEBREW_VITALITY__NATIVE_DAILY_READING', 138).
test_case('testsets/human_dignity_ai_governance__magisterial_integralist_reading.pl', 'human_dignity_ai_governance__magisterial_integralist_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__MAGISTERIAL_INTEGRALIST_READING', 139).
test_case('testsets/human_dignity_ai_governance__pluralist_pragmatic_reading.pl', 'human_dignity_ai_governance__pluralist_pragmatic_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__PLURALIST_PRAGMATIC_READING', 140).
test_case('testsets/human_dignity_ai_governance__secular_humanist_reading.pl', 'human_dignity_ai_governance__secular_humanist_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__SECULAR_HUMANIST_READING', 141).
test_case('testsets/human_dignity_ai_governance__techno_optimist_reading.pl', 'human_dignity_ai_governance__techno_optimist_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__TECHNO_OPTIMIST_READING', 142).
test_case('testsets/human_transcendence_pathway__babel_reading.pl', 'human_transcendence_pathway__babel_reading', 'HUMAN_TRANSCENDENCE_PATHWAY__BABEL_READING', 143).
test_case('testsets/human_transcendence_pathway__jerusalem_reading.pl', 'human_transcendence_pathway__jerusalem_reading', 'HUMAN_TRANSCENDENCE_PATHWAY__JERUSALEM_READING', 144).
test_case('testsets/human_transcendence_pathway__technocratic_vs_incarnational_reading.pl', 'human_transcendence_pathway__technocratic_vs_incarnational_reading', 'HUMAN_TRANSCENDENCE_PATHWAY__TECHNOCRATIC_VS_INCARNATIONAL_READING', 145).
test_case('testsets/imposition_mechanism_kernel__endogenous_climb_reading.pl', 'imposition_mechanism_kernel__endogenous_climb_reading', 'IMPOSITION_MECHANISM_KERNEL__ENDOGENOUS_CLIMB_READING', 146).
test_case('testsets/imposition_mechanism_kernel__exogenous_override_reading.pl', 'imposition_mechanism_kernel__exogenous_override_reading', 'IMPOSITION_MECHANISM_KERNEL__EXOGENOUS_OVERRIDE_READING', 147).
test_case('testsets/imposition_mechanism_kernel__hybrid_legitimation_reading.pl', 'imposition_mechanism_kernel__hybrid_legitimation_reading', 'IMPOSITION_MECHANISM_KERNEL__HYBRID_LEGITIMATION_READING', 148).
test_case('testsets/income_support_commitment__dependency_trap_reading.pl', 'income_support_commitment__dependency_trap_reading', 'INCOME_SUPPORT_COMMITMENT__DEPENDENCY_TRAP_READING', 149).
test_case('testsets/income_support_commitment__freedom_floor_reading.pl', 'income_support_commitment__freedom_floor_reading', 'INCOME_SUPPORT_COMMITMENT__FREEDOM_FLOOR_READING', 150).
test_case('testsets/income_support_commitment__targeting_efficiency_reading.pl', 'income_support_commitment__targeting_efficiency_reading', 'INCOME_SUPPORT_COMMITMENT__TARGETING_EFFICIENCY_READING', 151).
test_case('testsets/institutional_trust_erosion_c0.pl', 'institutional_trust_erosion_c0', 'INSTITUTIONAL_TRUST_EROSION_C0', 152).
test_case('testsets/jewish_territorial_claim__cultural_zionism_reading.pl', 'jewish_territorial_claim__cultural_zionism_reading', 'JEWISH_TERRITORIAL_CLAIM__CULTURAL_ZIONISM_READING', 153).
test_case('testsets/jewish_territorial_claim__political_zionism_reading.pl', 'jewish_territorial_claim__political_zionism_reading', 'JEWISH_TERRITORIAL_CLAIM__POLITICAL_ZIONISM_READING', 154).
test_case('testsets/jewish_territorial_claim__revisionist_zionism_reading.pl', 'jewish_territorial_claim__revisionist_zionism_reading', 'JEWISH_TERRITORIAL_CLAIM__REVISIONIST_ZIONISM_READING', 155).
test_case('testsets/jurisprudential_method_kernel__hanafi_reading.pl', 'jurisprudential_method_kernel__hanafi_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__HANAFI_READING', 156).
test_case('testsets/jurisprudential_method_kernel__hanbali_reading.pl', 'jurisprudential_method_kernel__hanbali_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__HANBALI_READING', 157).
test_case('testsets/jurisprudential_method_kernel__maliki_reading.pl', 'jurisprudential_method_kernel__maliki_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__MALIKI_READING', 158).
test_case('testsets/jurisprudential_method_kernel__shafii_reading.pl', 'jurisprudential_method_kernel__shafii_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__SHAFII_READING', 159).
test_case('testsets/kami_buddha_ontology__domain_partition.pl', 'kami_buddha_ontology__domain_partition', 'KAMI_BUDDHA_ONTOLOGY__DOMAIN_PARTITION', 160).
test_case('testsets/kami_buddha_ontology__honji_suijaku_monism.pl', 'kami_buddha_ontology__honji_suijaku_monism', 'KAMI_BUDDHA_ONTOLOGY__HONJI_SUIJAKU_MONISM', 161).
test_case('testsets/kami_buddha_ontology__incoherent_bundle.pl', 'kami_buddha_ontology__incoherent_bundle', 'KAMI_BUDDHA_ONTOLOGY__INCOHERENT_BUNDLE', 162).
test_case('testsets/kjv_text_1611__exclusive_inspiration_reading.pl', 'kjv_text_1611__exclusive_inspiration_reading', 'KJV_TEXT_1611__EXCLUSIVE_INSPIRATION_READING', 163).
test_case('testsets/kjv_text_1611__functional_equivalence_reading.pl', 'kjv_text_1611__functional_equivalence_reading', 'KJV_TEXT_1611__FUNCTIONAL_EQUIVALENCE_READING', 164).
test_case('testsets/kjv_text_1611__revisable_translation_reading.pl', 'kjv_text_1611__revisable_translation_reading', 'KJV_TEXT_1611__REVISABLE_TRANSLATION_READING', 165).
test_case('testsets/kodashim_obligation__study_as_archive.pl', 'kodashim_obligation__study_as_archive', 'KODASHIM_OBLIGATION__STUDY_AS_ARCHIVE', 166).
test_case('testsets/kodashim_obligation__study_as_performance.pl', 'kodashim_obligation__study_as_performance', 'KODASHIM_OBLIGATION__STUDY_AS_PERFORMANCE', 167).
test_case('testsets/kodashim_obligation__study_as_preparation.pl', 'kodashim_obligation__study_as_preparation', 'KODASHIM_OBLIGATION__STUDY_AS_PREPARATION', 168).
test_case('testsets/lausanne_minority_protections__expansive_reading.pl', 'lausanne_minority_protections__expansive_reading', 'LAUSANNE_MINORITY_PROTECTIONS__EXPANSIVE_READING', 169).
test_case('testsets/lausanne_minority_protections__guarantor_reading.pl', 'lausanne_minority_protections__guarantor_reading', 'LAUSANNE_MINORITY_PROTECTIONS__GUARANTOR_READING', 170).
test_case('testsets/lausanne_minority_protections__restrictive_reading.pl', 'lausanne_minority_protections__restrictive_reading', 'LAUSANNE_MINORITY_PROTECTIONS__RESTRICTIVE_READING', 171).
test_case('testsets/legitimate_health_intervention__bodily_autonomy_primary.pl', 'legitimate_health_intervention__bodily_autonomy_primary', 'LEGITIMATE_HEALTH_INTERVENTION__BODILY_AUTONOMY_PRIMARY', 172).
test_case('testsets/legitimate_health_intervention__proportionality_reading.pl', 'legitimate_health_intervention__proportionality_reading', 'LEGITIMATE_HEALTH_INTERVENTION__PROPORTIONALITY_READING', 173).
test_case('testsets/legitimate_health_intervention__public_health_primary.pl', 'legitimate_health_intervention__public_health_primary', 'LEGITIMATE_HEALTH_INTERVENTION__PUBLIC_HEALTH_PRIMARY', 174).
test_case('testsets/liability_attribution__deployer_liability.pl', 'liability_attribution__deployer_liability', 'LIABILITY_ATTRIBUTION__DEPLOYER_LIABILITY', 175).
test_case('testsets/liability_attribution__developer_liability.pl', 'liability_attribution__developer_liability', 'LIABILITY_ATTRIBUTION__DEVELOPER_LIABILITY', 176).
test_case('testsets/liability_attribution__shared_liability.pl', 'liability_attribution__shared_liability', 'LIABILITY_ATTRIBUTION__SHARED_LIABILITY', 177).
test_case('testsets/literacy_acquisition_kernel__balanced_literacy_reading.pl', 'literacy_acquisition_kernel__balanced_literacy_reading', 'LITERACY_ACQUISITION_KERNEL__BALANCED_LITERACY_READING', 178).
test_case('testsets/literacy_acquisition_kernel__phonics_reading.pl', 'literacy_acquisition_kernel__phonics_reading', 'LITERACY_ACQUISITION_KERNEL__PHONICS_READING', 179).
test_case('testsets/literacy_acquisition_kernel__structured_literacy_reading.pl', 'literacy_acquisition_kernel__structured_literacy_reading', 'LITERACY_ACQUISITION_KERNEL__STRUCTURED_LITERACY_READING', 180).
test_case('testsets/literacy_acquisition_kernel__whole_language_reading.pl', 'literacy_acquisition_kernel__whole_language_reading', 'LITERACY_ACQUISITION_KERNEL__WHOLE_LANGUAGE_READING', 181).
test_case('testsets/living_language_status__literary_continuity_reading.pl', 'living_language_status__literary_continuity_reading', 'LIVING_LANGUAGE_STATUS__LITERARY_CONTINUITY_READING', 182).
test_case('testsets/living_language_status__liturgical_preservation_reading.pl', 'living_language_status__liturgical_preservation_reading', 'LIVING_LANGUAGE_STATUS__LITURGICAL_PRESERVATION_READING', 183).
test_case('testsets/living_language_status__native_generation_reading.pl', 'living_language_status__native_generation_reading', 'LIVING_LANGUAGE_STATUS__NATIVE_GENERATION_READING', 184).
test_case('testsets/magna_carta_1215__baronial_privilege_reading.pl', 'magna_carta_1215__baronial_privilege_reading', 'MAGNA_CARTA_1215__BARONIAL_PRIVILEGE_READING', 185).
test_case('testsets/magna_carta_1215__living_document_reading.pl', 'magna_carta_1215__living_document_reading', 'MAGNA_CARTA_1215__LIVING_DOCUMENT_READING', 186).
test_case('testsets/magna_carta_1215__universal_rights_reading.pl', 'magna_carta_1215__universal_rights_reading', 'MAGNA_CARTA_1215__UNIVERSAL_RIGHTS_READING', 187).
test_case('testsets/market_as_natural_default__beneficiary_maintained_reading.pl', 'market_as_natural_default__beneficiary_maintained_reading', 'MARKET_AS_NATURAL_DEFAULT__BENEFICIARY_MAINTAINED_READING', 188).
test_case('testsets/market_as_natural_default__hybrid_amnesia_reading.pl', 'market_as_natural_default__hybrid_amnesia_reading', 'MARKET_AS_NATURAL_DEFAULT__HYBRID_AMNESIA_READING', 189).
test_case('testsets/market_as_natural_default__lapsed_alternative_reading.pl', 'market_as_natural_default__lapsed_alternative_reading', 'MARKET_AS_NATURAL_DEFAULT__LAPSED_ALTERNATIVE_READING', 190).
test_case('testsets/market_naturalization__beneficiary_maintained_reading.pl', 'market_naturalization__beneficiary_maintained_reading', 'MARKET_NATURALIZATION__BENEFICIARY_MAINTAINED_READING', 191).
test_case('testsets/market_naturalization__hybrid_reading.pl', 'market_naturalization__hybrid_reading', 'MARKET_NATURALIZATION__HYBRID_READING', 192).
test_case('testsets/market_naturalization__lapsed_alternative_reading.pl', 'market_naturalization__lapsed_alternative_reading', 'MARKET_NATURALIZATION__LAPSED_ALTERNATIVE_READING', 193).
test_case('testsets/marriage_authority__communal_autonomy_reading.pl', 'marriage_authority__communal_autonomy_reading', 'MARRIAGE_AUTHORITY__COMMUNAL_AUTONOMY_READING', 194).
test_case('testsets/marriage_authority__federalist_millet_reading.pl', 'marriage_authority__federalist_millet_reading', 'MARRIAGE_AUTHORITY__FEDERALIST_MILLET_READING', 195).
test_case('testsets/marriage_authority__gender_rights_reading.pl', 'marriage_authority__gender_rights_reading', 'MARRIAGE_AUTHORITY__GENDER_RIGHTS_READING', 196).
test_case('testsets/marriage_authority__judicial_harmonization_reading.pl', 'marriage_authority__judicial_harmonization_reading', 'MARRIAGE_AUTHORITY__JUDICIAL_HARMONIZATION_READING', 197).
test_case('testsets/marriage_authority__secularist_reading.pl', 'marriage_authority__secularist_reading', 'MARRIAGE_AUTHORITY__SECULARIST_READING', 198).
test_case('testsets/marriage_commitment_legitimacy__endogenous_reinterpretation_reading.pl', 'marriage_commitment_legitimacy__endogenous_reinterpretation_reading', 'MARRIAGE_COMMITMENT_LEGITIMACY__ENDOGENOUS_REINTERPRETATION_READING', 199).
test_case('testsets/marriage_commitment_legitimacy__exogenous_override_reading.pl', 'marriage_commitment_legitimacy__exogenous_override_reading', 'MARRIAGE_COMMITMENT_LEGITIMACY__EXOGENOUS_OVERRIDE_READING', 200).
test_case('testsets/marriage_commitment_legitimacy__hybrid_pragmatic_reading.pl', 'marriage_commitment_legitimacy__hybrid_pragmatic_reading', 'MARRIAGE_COMMITMENT_LEGITIMACY__HYBRID_PRAGMATIC_READING', 201).
test_case('testsets/monetary_anchor_principle__overdetermined_composite_reading.pl', 'monetary_anchor_principle__overdetermined_composite_reading', 'MONETARY_ANCHOR_PRINCIPLE__OVERDETERMINED_COMPOSITE_READING', 202).
test_case('testsets/monetary_anchor_principle__punctuated_swap_reading.pl', 'monetary_anchor_principle__punctuated_swap_reading', 'MONETARY_ANCHOR_PRINCIPLE__PUNCTUATED_SWAP_READING', 203).
test_case('testsets/monetary_anchor_principle__triffin_inevitability_reading.pl', 'monetary_anchor_principle__triffin_inevitability_reading', 'MONETARY_ANCHOR_PRINCIPLE__TRIFFIN_INEVITABILITY_READING', 204).
test_case('testsets/montevideo_statehood_criteria__constitutive_reading.pl', 'montevideo_statehood_criteria__constitutive_reading', 'MONTEVIDEO_STATEHOOD_CRITERIA__CONSTITUTIVE_READING', 205).
test_case('testsets/montevideo_statehood_criteria__declaratory_reading.pl', 'montevideo_statehood_criteria__declaratory_reading', 'MONTEVIDEO_STATEHOOD_CRITERIA__DECLARATORY_READING', 206).
test_case('testsets/montevideo_statehood_criteria__hybrid_reading.pl', 'montevideo_statehood_criteria__hybrid_reading', 'MONTEVIDEO_STATEHOOD_CRITERIA__HYBRID_READING', 207).
test_case('testsets/nafta_jurisdictional_boundary__capital_supremacy_reading.pl', 'nafta_jurisdictional_boundary__capital_supremacy_reading', 'NAFTA_JURISDICTIONAL_BOUNDARY__CAPITAL_SUPREMACY_READING', 208).
test_case('testsets/nafta_jurisdictional_boundary__embedded_liberalism_reading.pl', 'nafta_jurisdictional_boundary__embedded_liberalism_reading', 'NAFTA_JURISDICTIONAL_BOUNDARY__EMBEDDED_LIBERALISM_READING', 209).
test_case('testsets/nafta_jurisdictional_boundary__sovereignty_primacy_reading.pl', 'nafta_jurisdictional_boundary__sovereignty_primacy_reading', 'NAFTA_JURISDICTIONAL_BOUNDARY__SOVEREIGNTY_PRIMACY_READING', 210).
test_case('testsets/naskh_principle__classical_abrogation.pl', 'naskh_principle__classical_abrogation', 'NASKH_PRINCIPLE__CLASSICAL_ABROGATION', 211).
test_case('testsets/naskh_principle__contextual_harmonization.pl', 'naskh_principle__contextual_harmonization', 'NASKH_PRINCIPLE__CONTEXTUAL_HARMONIZATION', 212).
test_case('testsets/naskh_principle__progressive_restriction.pl', 'naskh_principle__progressive_restriction', 'NASKH_PRINCIPLE__PROGRESSIVE_RESTRICTION', 213).
test_case('testsets/nicene_christological_kernel__homoiousios_reading.pl', 'nicene_christological_kernel__homoiousios_reading', 'NICENE_CHRISTOLOGICAL_KERNEL__HOMOIOUSIOS_READING', 214).
test_case('testsets/nicene_christological_kernel__homoousios_reading.pl', 'nicene_christological_kernel__homoousios_reading', 'NICENE_CHRISTOLOGICAL_KERNEL__HOMOOUSIOS_READING', 215).
test_case('testsets/notability_guidelines__deletionist_reading.pl', 'notability_guidelines__deletionist_reading', 'NOTABILITY_GUIDELINES__DELETIONIST_READING', 216).
test_case('testsets/notability_guidelines__inclusionist_reading.pl', 'notability_guidelines__inclusionist_reading', 'NOTABILITY_GUIDELINES__INCLUSIONIST_READING', 217).
test_case('testsets/organization_floor_c0.pl', 'organization_floor_c0', 'ORGANIZATION_FLOOR_C0', 218).
test_case('testsets/personhood_boundary__birth_threshold_reading.pl', 'personhood_boundary__birth_threshold_reading', 'PERSONHOOD_BOUNDARY__BIRTH_THRESHOLD_READING', 219).
test_case('testsets/personhood_boundary__fitness_contingent_reading.pl', 'personhood_boundary__fitness_contingent_reading', 'PERSONHOOD_BOUNDARY__FITNESS_CONTINGENT_READING', 220).
test_case('testsets/personhood_boundary__potential_based_reading.pl', 'personhood_boundary__potential_based_reading', 'PERSONHOOD_BOUNDARY__POTENTIAL_BASED_READING', 221).
test_case('testsets/preparedness_commitment__competence_reading.pl', 'preparedness_commitment__competence_reading', 'PREPAREDNESS_COMMITMENT__COMPETENCE_READING', 222).
test_case('testsets/preparedness_commitment__husk_reading.pl', 'preparedness_commitment__husk_reading', 'PREPAREDNESS_COMMITMENT__HUSK_READING', 223).
test_case('testsets/preparedness_commitment__hybrid_reading.pl', 'preparedness_commitment__hybrid_reading', 'PREPAREDNESS_COMMITMENT__HYBRID_READING', 224).
test_case('testsets/preparedness_transmission__competence_reading.pl', 'preparedness_transmission__competence_reading', 'PREPAREDNESS_TRANSMISSION__COMPETENCE_READING', 225).
test_case('testsets/preparedness_transmission__husk_reading.pl', 'preparedness_transmission__husk_reading', 'PREPAREDNESS_TRANSMISSION__HUSK_READING', 226).
test_case('testsets/preparedness_transmission__hybrid_reading.pl', 'preparedness_transmission__hybrid_reading', 'PREPAREDNESS_TRANSMISSION__HYBRID_READING', 227).
test_case('testsets/press_reformation_causality__co_constitution.pl', 'press_reformation_causality__co_constitution', 'PRESS_REFORMATION_CAUSALITY__CO_CONSTITUTION', 228).
test_case('testsets/press_reformation_causality__strategic_deployment.pl', 'press_reformation_causality__strategic_deployment', 'PRESS_REFORMATION_CAUSALITY__STRATEGIC_DEPLOYMENT', 229).
test_case('testsets/press_reformation_causality__technological_determinism.pl', 'press_reformation_causality__technological_determinism', 'PRESS_REFORMATION_CAUSALITY__TECHNOLOGICAL_DETERMINISM', 230).
test_case('testsets/provincial_sovereignty_boundary__compact_federalism.pl', 'provincial_sovereignty_boundary__compact_federalism', 'PROVINCIAL_SOVEREIGNTY_BOUNDARY__COMPACT_FEDERALISM', 231).
test_case('testsets/provincial_sovereignty_boundary__constitutional_subordination.pl', 'provincial_sovereignty_boundary__constitutional_subordination', 'PROVINCIAL_SOVEREIGNTY_BOUNDARY__CONSTITUTIONAL_SUBORDINATION', 232).
test_case('testsets/provincial_sovereignty_boundary__resource_sovereignty_primacy.pl', 'provincial_sovereignty_boundary__resource_sovereignty_primacy', 'PROVINCIAL_SOVEREIGNTY_BOUNDARY__RESOURCE_SOVEREIGNTY_PRIMACY', 233).
test_case('testsets/public_health_mandate_authority__bodily_autonomy_primary.pl', 'public_health_mandate_authority__bodily_autonomy_primary', 'PUBLIC_HEALTH_MANDATE_AUTHORITY__BODILY_AUTONOMY_PRIMARY', 234).
test_case('testsets/public_health_mandate_authority__proportionality_reading.pl', 'public_health_mandate_authority__proportionality_reading', 'PUBLIC_HEALTH_MANDATE_AUTHORITY__PROPORTIONALITY_READING', 235).
test_case('testsets/public_health_mandate_authority__public_health_primary.pl', 'public_health_mandate_authority__public_health_primary', 'PUBLIC_HEALTH_MANDATE_AUTHORITY__PUBLIC_HEALTH_PRIMARY', 236).
test_case('testsets/qwerty_persistence__incumbent_preservation_reading.pl', 'qwerty_persistence__incumbent_preservation_reading', 'QWERTY_PERSISTENCE__INCUMBENT_PRESERVATION_READING', 237).
test_case('testsets/qwerty_persistence__lapsed_alternatives_reading.pl', 'qwerty_persistence__lapsed_alternatives_reading', 'QWERTY_PERSISTENCE__LAPSED_ALTERNATIVES_READING', 238).
test_case('testsets/qwerty_persistence_mechanism__beneficiary_extraction_reading.pl', 'qwerty_persistence_mechanism__beneficiary_extraction_reading', 'QWERTY_PERSISTENCE_MECHANISM__BENEFICIARY_EXTRACTION_READING', 239).
test_case('testsets/qwerty_persistence_mechanism__lock_in_reading.pl', 'qwerty_persistence_mechanism__lock_in_reading', 'QWERTY_PERSISTENCE_MECHANISM__LOCK_IN_READING', 240).
test_case('testsets/qwerty_persistence_mechanism__naturalization_reading.pl', 'qwerty_persistence_mechanism__naturalization_reading', 'QWERTY_PERSISTENCE_MECHANISM__NATURALIZATION_READING', 241).
test_case('testsets/reading_acquisition_legitimacy__balanced_literacy_integration.pl', 'reading_acquisition_legitimacy__balanced_literacy_integration', 'READING_ACQUISITION_LEGITIMACY__BALANCED_LITERACY_INTEGRATION', 242).
test_case('testsets/reading_acquisition_legitimacy__phonics_decoding_primacy.pl', 'reading_acquisition_legitimacy__phonics_decoding_primacy', 'READING_ACQUISITION_LEGITIMACY__PHONICS_DECODING_PRIMACY', 243).
test_case('testsets/reading_acquisition_legitimacy__structured_literacy_remediation.pl', 'reading_acquisition_legitimacy__structured_literacy_remediation', 'READING_ACQUISITION_LEGITIMACY__STRUCTURED_LITERACY_REMEDIATION', 244).
test_case('testsets/reading_acquisition_mechanism__balanced_literacy_reading.pl', 'reading_acquisition_mechanism__balanced_literacy_reading', 'READING_ACQUISITION_MECHANISM__BALANCED_LITERACY_READING', 245).
test_case('testsets/reading_acquisition_mechanism__phonics_reading.pl', 'reading_acquisition_mechanism__phonics_reading', 'READING_ACQUISITION_MECHANISM__PHONICS_READING', 246).
test_case('testsets/reading_acquisition_mechanism__whole_language_reading.pl', 'reading_acquisition_mechanism__whole_language_reading', 'READING_ACQUISITION_MECHANISM__WHOLE_LANGUAGE_READING', 247).
test_case('testsets/refugee_convention_text__expansive_humanitarian_reading.pl', 'refugee_convention_text__expansive_humanitarian_reading', 'REFUGEE_CONVENTION_TEXT__EXPANSIVE_HUMANITARIAN_READING', 248).
test_case('testsets/refugee_convention_text__procedural_integrity_reading.pl', 'refugee_convention_text__procedural_integrity_reading', 'REFUGEE_CONVENTION_TEXT__PROCEDURAL_INTEGRITY_READING', 249).
test_case('testsets/refugee_convention_text__restrictive_sovereignty_reading.pl', 'refugee_convention_text__restrictive_sovereignty_reading', 'REFUGEE_CONVENTION_TEXT__RESTRICTIVE_SOVEREIGNTY_READING', 250).
test_case('testsets/remonstrance_authority__crown_reading.pl', 'remonstrance_authority__crown_reading', 'REMONSTRANCE_AUTHORITY__CROWN_READING', 251).
test_case('testsets/remonstrance_authority__magistrate_reading.pl', 'remonstrance_authority__magistrate_reading', 'REMONSTRANCE_AUTHORITY__MAGISTRATE_READING', 252).
test_case('testsets/sacrifice_obligation_kernel__messianic_suspension_reading.pl', 'sacrifice_obligation_kernel__messianic_suspension_reading', 'SACRIFICE_OBLIGATION_KERNEL__MESSIANIC_SUSPENSION_READING', 253).
test_case('testsets/sacrifice_obligation_kernel__performance_only_reading.pl', 'sacrifice_obligation_kernel__performance_only_reading', 'SACRIFICE_OBLIGATION_KERNEL__PERFORMANCE_ONLY_READING', 254).
test_case('testsets/sacrifice_obligation_kernel__study_as_exercise_reading.pl', 'sacrifice_obligation_kernel__study_as_exercise_reading', 'SACRIFICE_OBLIGATION_KERNEL__STUDY_AS_EXERCISE_READING', 255).
test_case('testsets/sacrifice_obligation_kernel__symbolic_archive_reading.pl', 'sacrifice_obligation_kernel__symbolic_archive_reading', 'SACRIFICE_OBLIGATION_KERNEL__SYMBOLIC_ARCHIVE_READING', 256).
test_case('testsets/scale_ceiling_c0.pl', 'scale_ceiling_c0', 'SCALE_CEILING_C0', 257).
test_case('testsets/secession_legitimacy_boundary__constitutional_impossibility_reading.pl', 'secession_legitimacy_boundary__constitutional_impossibility_reading', 'SECESSION_LEGITIMACY_BOUNDARY__CONSTITUTIONAL_IMPOSSIBILITY_READING', 258).
test_case('testsets/secession_legitimacy_boundary__grievance_threshold_reading.pl', 'secession_legitimacy_boundary__grievance_threshold_reading', 'SECESSION_LEGITIMACY_BOUNDARY__GRIEVANCE_THRESHOLD_READING', 259).
test_case('testsets/secession_legitimacy_boundary__popular_sovereignty_reading.pl', 'secession_legitimacy_boundary__popular_sovereignty_reading', 'SECESSION_LEGITIMACY_BOUNDARY__POPULAR_SOVEREIGNTY_READING', 260).
test_case('testsets/secession_legitimacy_boundary__treaty_primacy_reading.pl', 'secession_legitimacy_boundary__treaty_primacy_reading', 'SECESSION_LEGITIMACY_BOUNDARY__TREATY_PRIMACY_READING', 261).
test_case('testsets/second_amendment_boundary__individual_right_reading.pl', 'second_amendment_boundary__individual_right_reading', 'SECOND_AMENDMENT_BOUNDARY__INDIVIDUAL_RIGHT_READING', 262).
test_case('testsets/second_amendment_boundary__insurrectionist_reading.pl', 'second_amendment_boundary__insurrectionist_reading', 'SECOND_AMENDMENT_BOUNDARY__INSURRECTIONIST_READING', 263).
test_case('testsets/second_amendment_boundary__militia_conditioned_reading.pl', 'second_amendment_boundary__militia_conditioned_reading', 'SECOND_AMENDMENT_BOUNDARY__MILITIA_CONDITIONED_READING', 264).
test_case('testsets/second_amendment_text__collective_security_reading.pl', 'second_amendment_text__collective_security_reading', 'SECOND_AMENDMENT_TEXT__COLLECTIVE_SECURITY_READING', 265).
test_case('testsets/second_amendment_text__individual_right_reading.pl', 'second_amendment_text__individual_right_reading', 'SECOND_AMENDMENT_TEXT__INDIVIDUAL_RIGHT_READING', 266).
test_case('testsets/second_amendment_text__originalist_civic_virtue_reading.pl', 'second_amendment_text__originalist_civic_virtue_reading', 'SECOND_AMENDMENT_TEXT__ORIGINALIST_CIVIC_VIRTUE_READING', 267).
test_case('testsets/separation_of_powers_text__formalist_reading.pl', 'separation_of_powers_text__formalist_reading', 'SEPARATION_OF_POWERS_TEXT__FORMALIST_READING', 268).
test_case('testsets/separation_of_powers_text__functionalist_reading.pl', 'separation_of_powers_text__functionalist_reading', 'SEPARATION_OF_POWERS_TEXT__FUNCTIONALIST_READING', 269).
test_case('testsets/separation_of_powers_text__unitary_executive_reading.pl', 'separation_of_powers_text__unitary_executive_reading', 'SEPARATION_OF_POWERS_TEXT__UNITARY_EXECUTIVE_READING', 270).
test_case('testsets/shinbutsu_coexistence_commitment__domain_partition_reading.pl', 'shinbutsu_coexistence_commitment__domain_partition_reading', 'SHINBUTSU_COEXISTENCE_COMMITMENT__DOMAIN_PARTITION_READING', 271).
test_case('testsets/shinbutsu_coexistence_commitment__incoherent_bundle_reading.pl', 'shinbutsu_coexistence_commitment__incoherent_bundle_reading', 'SHINBUTSU_COEXISTENCE_COMMITMENT__INCOHERENT_BUNDLE_READING', 272).
test_case('testsets/shinbutsu_coexistence_commitment__syncretic_fusion_reading.pl', 'shinbutsu_coexistence_commitment__syncretic_fusion_reading', 'SHINBUTSU_COEXISTENCE_COMMITMENT__SYNCRETIC_FUSION_READING', 273).
test_case('testsets/shinbutsu_ontological_substrate__domain_partition_reading.pl', 'shinbutsu_ontological_substrate__domain_partition_reading', 'SHINBUTSU_ONTOLOGICAL_SUBSTRATE__DOMAIN_PARTITION_READING', 274).
test_case('testsets/shinbutsu_ontological_substrate__incoherent_bundle_reading.pl', 'shinbutsu_ontological_substrate__incoherent_bundle_reading', 'SHINBUTSU_ONTOLOGICAL_SUBSTRATE__INCOHERENT_BUNDLE_READING', 275).
test_case('testsets/shinbutsu_ontological_substrate__syncretic_fusion_reading.pl', 'shinbutsu_ontological_substrate__syncretic_fusion_reading', 'SHINBUTSU_ONTOLOGICAL_SUBSTRATE__SYNCRETIC_FUSION_READING', 276).
test_case('testsets/simultaneous_veneration__domain_partition_reading.pl', 'simultaneous_veneration__domain_partition_reading', 'SIMULTANEOUS_VENERATION__DOMAIN_PARTITION_READING', 277).
test_case('testsets/simultaneous_veneration__ontological_fusion_reading.pl', 'simultaneous_veneration__ontological_fusion_reading', 'SIMULTANEOUS_VENERATION__ONTOLOGICAL_FUSION_READING', 278).
test_case('testsets/simultaneous_veneration__pragmatic_incoherence_reading.pl', 'simultaneous_veneration__pragmatic_incoherence_reading', 'SIMULTANEOUS_VENERATION__PRAGMATIC_INCOHERENCE_READING', 279).
test_case('testsets/software_source_status__freedom_imperative_reading.pl', 'software_source_status__freedom_imperative_reading', 'SOFTWARE_SOURCE_STATUS__FREEDOM_IMPERATIVE_READING', 280).
test_case('testsets/software_source_status__pragmatic_development_reading.pl', 'software_source_status__pragmatic_development_reading', 'SOFTWARE_SOURCE_STATUS__PRAGMATIC_DEVELOPMENT_READING', 281).
test_case('testsets/software_source_status__property_rights_reading.pl', 'software_source_status__property_rights_reading', 'SOFTWARE_SOURCE_STATUS__PROPERTY_RIGHTS_READING', 282).
test_case('testsets/software_source_status__utilitarian_hybrid_reading.pl', 'software_source_status__utilitarian_hybrid_reading', 'SOFTWARE_SOURCE_STATUS__UTILITARIAN_HYBRID_READING', 283).
test_case('testsets/sovereign_legitimacy__constitutional_hybrid_reading.pl', 'sovereign_legitimacy__constitutional_hybrid_reading', 'SOVEREIGN_LEGITIMACY__CONSTITUTIONAL_HYBRID_READING', 284).
test_case('testsets/sovereign_legitimacy__monarchical_reading.pl', 'sovereign_legitimacy__monarchical_reading', 'SOVEREIGN_LEGITIMACY__MONARCHICAL_READING', 285).
test_case('testsets/sovereign_legitimacy__republican_reading.pl', 'sovereign_legitimacy__republican_reading', 'SOVEREIGN_LEGITIMACY__REPUBLICAN_READING', 286).
test_case('testsets/state_execution_authority__abolition_reading.pl', 'state_execution_authority__abolition_reading', 'STATE_EXECUTION_AUTHORITY__ABOLITION_READING', 287).
test_case('testsets/state_execution_authority__deterrence_reading.pl', 'state_execution_authority__deterrence_reading', 'STATE_EXECUTION_AUTHORITY__DETERRENCE_READING', 288).
test_case('testsets/state_execution_authority__retributive_reading.pl', 'state_execution_authority__retributive_reading', 'STATE_EXECUTION_AUTHORITY__RETRIBUTIVE_READING', 289).
test_case('testsets/state_killing_authority__categorical_abolition.pl', 'state_killing_authority__categorical_abolition', 'STATE_KILLING_AUTHORITY__CATEGORICAL_ABOLITION', 290).
test_case('testsets/state_killing_authority__deterrence_instrument.pl', 'state_killing_authority__deterrence_instrument', 'STATE_KILLING_AUTHORITY__DETERRENCE_INSTRUMENT', 291).
test_case('testsets/state_killing_authority__retributive_desert.pl', 'state_killing_authority__retributive_desert', 'STATE_KILLING_AUTHORITY__RETRIBUTIVE_DESERT', 292).
test_case('testsets/state_killing_legitimacy__deterrence_reading.pl', 'state_killing_legitimacy__deterrence_reading', 'STATE_KILLING_LEGITIMACY__DETERRENCE_READING', 293).
test_case('testsets/state_killing_legitimacy__retributive_reading.pl', 'state_killing_legitimacy__retributive_reading', 'STATE_KILLING_LEGITIMACY__RETRIBUTIVE_READING', 294).
test_case('testsets/substance_control_authority__harm_reduction_reading.pl', 'substance_control_authority__harm_reduction_reading', 'SUBSTANCE_CONTROL_AUTHORITY__HARM_REDUCTION_READING', 295).
test_case('testsets/substance_control_authority__legalization_reading.pl', 'substance_control_authority__legalization_reading', 'SUBSTANCE_CONTROL_AUTHORITY__LEGALIZATION_READING', 296).
test_case('testsets/substance_control_authority__prohibition_reading.pl', 'substance_control_authority__prohibition_reading', 'SUBSTANCE_CONTROL_AUTHORITY__PROHIBITION_READING', 297).
test_case('testsets/substance_control_legitimacy__harm_reduction_reading.pl', 'substance_control_legitimacy__harm_reduction_reading', 'SUBSTANCE_CONTROL_LEGITIMACY__HARM_REDUCTION_READING', 298).
test_case('testsets/substance_control_legitimacy__legalization_reading.pl', 'substance_control_legitimacy__legalization_reading', 'SUBSTANCE_CONTROL_LEGITIMACY__LEGALIZATION_READING', 299).
test_case('testsets/substance_control_legitimacy__prohibition_reading.pl', 'substance_control_legitimacy__prohibition_reading', 'SUBSTANCE_CONTROL_LEGITIMACY__PROHIBITION_READING', 300).
test_case('testsets/tcp_ip_interpretation__neutrality_reading.pl', 'tcp_ip_interpretation__neutrality_reading', 'TCP_IP_INTERPRETATION__NEUTRALITY_READING', 301).
test_case('testsets/tcp_ip_interpretation__prioritization_reading.pl', 'tcp_ip_interpretation__prioritization_reading', 'TCP_IP_INTERPRETATION__PRIORITIZATION_READING', 302).
test_case('testsets/tcp_ip_interpretation__zero_rating_reading.pl', 'tcp_ip_interpretation__zero_rating_reading', 'TCP_IP_INTERPRETATION__ZERO_RATING_READING', 303).
test_case('testsets/temple_sacrifice_commitment__hybrid_preparatory.pl', 'temple_sacrifice_commitment__hybrid_preparatory', 'TEMPLE_SACRIFICE_COMMITMENT__HYBRID_PREPARATORY', 304).
test_case('testsets/temple_sacrifice_commitment__performance_only.pl', 'temple_sacrifice_commitment__performance_only', 'TEMPLE_SACRIFICE_COMMITMENT__PERFORMANCE_ONLY', 305).
test_case('testsets/temple_sacrifice_commitment__study_as_exercise.pl', 'temple_sacrifice_commitment__study_as_exercise', 'TEMPLE_SACRIFICE_COMMITMENT__STUDY_AS_EXERCISE', 306).
test_case('testsets/temple_sacrifice_commitment__symbolic_transformation.pl', 'temple_sacrifice_commitment__symbolic_transformation', 'TEMPLE_SACRIFICE_COMMITMENT__SYMBOLIC_TRANSFORMATION', 307).
test_case('testsets/tenure_contract__academic_freedom_reading.pl', 'tenure_contract__academic_freedom_reading', 'TENURE_CONTRACT__ACADEMIC_FREEDOM_READING', 308).
test_case('testsets/tenure_contract__demographic_reproduction_reading.pl', 'tenure_contract__demographic_reproduction_reading', 'TENURE_CONTRACT__DEMOGRAPHIC_REPRODUCTION_READING', 309).
test_case('testsets/tenure_contract__institutional_extraction_reading.pl', 'tenure_contract__institutional_extraction_reading', 'TENURE_CONTRACT__INSTITUTIONAL_EXTRACTION_READING', 310).
test_case('testsets/territorial_sovereignty_legitimacy__covenant_continuity_reading.pl', 'territorial_sovereignty_legitimacy__covenant_continuity_reading', 'TERRITORIAL_SOVEREIGNTY_LEGITIMACY__COVENANT_CONTINUITY_READING', 311).
test_case('testsets/territorial_sovereignty_legitimacy__existential_matrix_reading.pl', 'territorial_sovereignty_legitimacy__existential_matrix_reading', 'TERRITORIAL_SOVEREIGNTY_LEGITIMACY__EXISTENTIAL_MATRIX_READING', 312).
test_case('testsets/territorial_sovereignty_legitimacy__self_determination_reading.pl', 'territorial_sovereignty_legitimacy__self_determination_reading', 'TERRITORIAL_SOVEREIGNTY_LEGITIMACY__SELF_DETERMINATION_READING', 313).
test_case('testsets/total_war_possibility_space__deterrence_equilibrium_reading.pl', 'total_war_possibility_space__deterrence_equilibrium_reading', 'TOTAL_WAR_POSSIBILITY_SPACE__DETERRENCE_EQUILIBRIUM_READING', 314).
test_case('testsets/total_war_possibility_space__nuclear_taboo_reading.pl', 'total_war_possibility_space__nuclear_taboo_reading', 'TOTAL_WAR_POSSIBILITY_SPACE__NUCLEAR_TABOO_READING', 315).
test_case('testsets/total_war_possibility_space__space_contraction_reading.pl', 'total_war_possibility_space__space_contraction_reading', 'TOTAL_WAR_POSSIBILITY_SPACE__SPACE_CONTRACTION_READING', 316).
test_case('testsets/udhr_authority__aspirational_sovereignty_reading.pl', 'udhr_authority__aspirational_sovereignty_reading', 'UDHR_AUTHORITY__ASPIRATIONAL_SOVEREIGNTY_READING', 317).
test_case('testsets/udhr_authority__binding_universalism_reading.pl', 'udhr_authority__binding_universalism_reading', 'UDHR_AUTHORITY__BINDING_UNIVERSALISM_READING', 318).
test_case('testsets/udhr_authority__customary_emergence_reading.pl', 'udhr_authority__customary_emergence_reading', 'UDHR_AUTHORITY__CUSTOMARY_EMERGENCE_READING', 319).
test_case('testsets/us_constitution_interpretive__living_constitution_reading.pl', 'us_constitution_interpretive__living_constitution_reading', 'US_CONSTITUTION_INTERPRETIVE__LIVING_CONSTITUTION_READING', 320).
test_case('testsets/us_constitution_interpretive__originalist_reading.pl', 'us_constitution_interpretive__originalist_reading', 'US_CONSTITUTION_INTERPRETIVE__ORIGINALIST_READING', 321).
test_case('testsets/us_constitution_interpretive__popular_constitutionalism_reading.pl', 'us_constitution_interpretive__popular_constitutionalism_reading', 'US_CONSTITUTION_INTERPRETIVE__POPULAR_CONSTITUTIONALISM_READING', 322).
test_case('testsets/vatican_ii_authority__composite_overdetermination_reading.pl', 'vatican_ii_authority__composite_overdetermination_reading', 'VATICAN_II_AUTHORITY__COMPOSITE_OVERDETERMINATION_READING', 323).
test_case('testsets/vatican_ii_authority__continuity_reading.pl', 'vatican_ii_authority__continuity_reading', 'VATICAN_II_AUTHORITY__CONTINUITY_READING', 324).
test_case('testsets/vatican_ii_authority__rupture_reading.pl', 'vatican_ii_authority__rupture_reading', 'VATICAN_II_AUTHORITY__RUPTURE_READING', 325).
test_case('testsets/waitangi_sovereignty_allocation__crown_sovereignty_reading.pl', 'waitangi_sovereignty_allocation__crown_sovereignty_reading', 'WAITANGI_SOVEREIGNTY_ALLOCATION__CROWN_SOVEREIGNTY_READING', 326).
test_case('testsets/waitangi_sovereignty_allocation__partnership_reading.pl', 'waitangi_sovereignty_allocation__partnership_reading', 'WAITANGI_SOVEREIGNTY_ALLOCATION__PARTNERSHIP_READING', 327).
test_case('testsets/waitangi_sovereignty_allocation__rangatiratanga_reading.pl', 'waitangi_sovereignty_allocation__rangatiratanga_reading', 'WAITANGI_SOVEREIGNTY_ALLOCATION__RANGATIRATANGA_READING', 328).
test_case('testsets/westphalian_sovereignty__absolute_sovereignty.pl', 'westphalian_sovereignty__absolute_sovereignty', 'WESTPHALIAN_SOVEREIGNTY__ABSOLUTE_SOVEREIGNTY', 329).
test_case('testsets/westphalian_sovereignty__conditional_sovereignty.pl', 'westphalian_sovereignty__conditional_sovereignty', 'WESTPHALIAN_SOVEREIGNTY__CONDITIONAL_SOVEREIGNTY', 330).
test_case('testsets/westphalian_sovereignty__graduated_sovereignty.pl', 'westphalian_sovereignty__graduated_sovereignty', 'WESTPHALIAN_SOVEREIGNTY__GRADUATED_SOVEREIGNTY', 331).
test_case('testsets/woman_female_category__gender_identity_reading.pl', 'woman_female_category__gender_identity_reading', 'WOMAN_FEMALE_CATEGORY__GENDER_IDENTITY_READING', 332).
test_case('testsets/woman_female_category__hybrid_contextual_reading.pl', 'woman_female_category__hybrid_contextual_reading', 'WOMAN_FEMALE_CATEGORY__HYBRID_CONTEXTUAL_READING', 333).
test_case('testsets/woman_female_category__sex_biology_reading.pl', 'woman_female_category__sex_biology_reading', 'WOMAN_FEMALE_CATEGORY__SEX_BIOLOGY_READING', 334).
test_case('testsets/wto_treaty_framework__developmental_reading.pl', 'wto_treaty_framework__developmental_reading', 'WTO_TREATY_FRAMEWORK__DEVELOPMENTAL_READING', 335).
test_case('testsets/wto_treaty_framework__market_access_reading.pl', 'wto_treaty_framework__market_access_reading', 'WTO_TREATY_FRAMEWORK__MARKET_ACCESS_READING', 336).

% --- Test Suite Runner ---
run_dynamic_suite :-
    retractall(test_passed(_)),
    retractall(test_failed(_, _, _)),
    writeln('--- STARTING DYNAMIC VALIDATION ---'),
    forall(test_case(Path, ID, Label, N), run_single_test(Path, ID, Label, N)),
    count_and_report,
    % Call validate_all directly from data_validation module
    data_validation:validate_all.

% --- Single Test Executor ---
%  Per-test timeout guard (60s) prevents any single test from consuming
%  the entire sweep timeout. Elapsed timing aids diagnostic profiling.
run_single_test(Path, ID, _Label, N) :-
    format('~n[~w] EXECUTING: ~w~n', [N, Path]),
    get_time(T0),
    catch(
        call_with_time_limit(
            60,
            (   catch_with_backtrace(
                    ( load_and_run(Path, ID) ->
                        assertz(test_passed(Path)),
                        format('[PASS] ~w~n', [Path])
                    ;   assertz(test_failed(Path, audit_failed, 'load_and_run returned false')),
                        format('[AUDIT FAIL] ~w~n', [Path])
                    ),
                    E,
                    (   assertz(test_failed(Path, exception, E)),
                        format('[FAIL] Exception for ~w: ~w~n', [Path, E]),
                        print_prolog_backtrace(current_output, E)
                    )
                ),
                report_generator:generate_llm_feedback(ID)
            )
        ),
        time_limit_exceeded,
        (   assertz(test_failed(Path, timeout, 'Exceeded 60s per-test limit')),
            format('[TIMEOUT] ~w~n', [Path])
        )
    ),
    get_time(T1),
    Elapsed is T1 - T0,
    format('[ELAPSED] ~w: ~3fs~n', [Path, Elapsed]).

% --- Result Counter & Reporter ---
count_and_report :-
    findall(P, test_passed(P), Ps), length(Ps, PC),
    findall(F, test_failed(F,_,_), Fs), length(Fs, FC),
    writeln(''),
    writeln('=================================================='),
    writeln('           TEST SUITE SUMMARY'),
    writeln('=================================================='),
    format('Passed: ~w~n', [PC]),
    format('Failed: ~w~n', [FC]),
    (FC > 0 -> report_failures ; true),
    writeln('==================================================').

report_failures :-
    writeln('--- FAILED TESTS ---'),
    forall(test_failed(Path, Type, Detail),
           format('~n  - [~w] ~w~n    Reason: ~w~n', [Type, Path, Detail])).

