:- module(validation_suite, [run_dynamic_suite/0]).
:- use_module(library(prolog_stack)).
:- use_module(library(time)).
:- use_module(scenario_manager).
:- use_module(data_validation).
:- use_module(report_generator).

:- chdir('../prolog').

:- dynamic test_passed/1, test_failed/3, test_case/4.

% --- Test Case Definitions ---
test_case('testsets/abrahamic_covenant__isaac_covenant_reading.pl', 'abrahamic_covenant__isaac_covenant_reading', 'ABRAHAMIC_COVENANT__ISAAC_COVENANT_READING', 1).
test_case('testsets/abrahamic_covenant__ishmael_covenant_reading.pl', 'abrahamic_covenant__ishmael_covenant_reading', 'ABRAHAMIC_COVENANT__ISHMAEL_COVENANT_READING', 2).
test_case('testsets/abrahamic_covenant__land_promise_constraint.pl', 'abrahamic_covenant__land_promise_constraint', 'ABRAHAMIC_COVENANT__LAND_PROMISE_CONSTRAINT', 3).
test_case('testsets/acceptable_risk_for_energy__catastrophic_tail_dominant.pl', 'acceptable_risk_for_energy__catastrophic_tail_dominant', 'ACCEPTABLE_RISK_FOR_ENERGY__CATASTROPHIC_TAIL_DOMINANT', 4).
test_case('testsets/acceptable_risk_for_energy__comparative_risk_dominant.pl', 'acceptable_risk_for_energy__comparative_risk_dominant', 'ACCEPTABLE_RISK_FOR_ENERGY__COMPARATIVE_RISK_DOMINANT', 5).
test_case('testsets/acceptable_risk_for_energy__expected_value_dominant.pl', 'acceptable_risk_for_energy__expected_value_dominant', 'ACCEPTABLE_RISK_FOR_ENERGY__EXPECTED_VALUE_DOMINANT', 6).
test_case('testsets/adjunctification_of_university_teaching_c0.pl', 'adjunctification_of_university_teaching_c0', 'ADJUNCTIFICATION_OF_UNIVERSITY_TEACHING_C0', 7).
test_case('testsets/ai_alignment_commitment__ethics_justice_reading.pl', 'ai_alignment_commitment__ethics_justice_reading', 'AI_ALIGNMENT_COMMITMENT__ETHICS_JUSTICE_READING', 8).
test_case('testsets/ai_alignment_commitment__integrated_reading.pl', 'ai_alignment_commitment__integrated_reading', 'AI_ALIGNMENT_COMMITMENT__INTEGRATED_READING', 9).
test_case('testsets/ai_alignment_commitment__safety_control_reading.pl', 'ai_alignment_commitment__safety_control_reading', 'AI_ALIGNMENT_COMMITMENT__SAFETY_CONTROL_READING', 10).
test_case('testsets/ai_dignity_safeguarding__autonomy_rights_reading.pl', 'ai_dignity_safeguarding__autonomy_rights_reading', 'AI_DIGNITY_SAFEGUARDING__AUTONOMY_RIGHTS_READING', 11).
test_case('testsets/ai_dignity_safeguarding__imago_dei_reading.pl', 'ai_dignity_safeguarding__imago_dei_reading', 'AI_DIGNITY_SAFEGUARDING__IMAGO_DEI_READING', 12).
test_case('testsets/ai_dignity_safeguarding__posthuman_continuity_reading.pl', 'ai_dignity_safeguarding__posthuman_continuity_reading', 'AI_DIGNITY_SAFEGUARDING__POSTHUMAN_CONTINUITY_READING', 13).
test_case('testsets/ai_governance_legitimacy__magisterial_subsidiarity_reading.pl', 'ai_governance_legitimacy__magisterial_subsidiarity_reading', 'AI_GOVERNANCE_LEGITIMACY__MAGISTERIAL_SUBSIDIARITY_READING', 14).
test_case('testsets/ai_governance_legitimacy__market_libertarian_reading.pl', 'ai_governance_legitimacy__market_libertarian_reading', 'AI_GOVERNANCE_LEGITIMACY__MARKET_LIBERTARIAN_READING', 15).
test_case('testsets/ai_governance_legitimacy__technocratic_optimization_reading.pl', 'ai_governance_legitimacy__technocratic_optimization_reading', 'AI_GOVERNANCE_LEGITIMACY__TECHNOCRATIC_OPTIMIZATION_READING', 16).
test_case('testsets/ai_human_relationship__incarnational_humanism.pl', 'ai_human_relationship__incarnational_humanism', 'AI_HUMAN_RELATIONSHIP__INCARNATIONAL_HUMANISM', 17).
test_case('testsets/ai_human_relationship__instrumental_subsidiarity.pl', 'ai_human_relationship__instrumental_subsidiarity', 'AI_HUMAN_RELATIONSHIP__INSTRUMENTAL_SUBSIDIARITY', 18).
test_case('testsets/ai_human_relationship__technocratic_optimization.pl', 'ai_human_relationship__technocratic_optimization', 'AI_HUMAN_RELATIONSHIP__TECHNOCRATIC_OPTIMIZATION', 19).
test_case('testsets/ai_risk_governance_priority__bridge_reading.pl', 'ai_risk_governance_priority__bridge_reading', 'AI_RISK_GOVERNANCE_PRIORITY__BRIDGE_READING', 20).
test_case('testsets/ai_risk_governance_priority__existential_risk_reading.pl', 'ai_risk_governance_priority__existential_risk_reading', 'AI_RISK_GOVERNANCE_PRIORITY__EXISTENTIAL_RISK_READING', 21).
test_case('testsets/ai_risk_governance_priority__near_term_harms_reading.pl', 'ai_risk_governance_priority__near_term_harms_reading', 'AI_RISK_GOVERNANCE_PRIORITY__NEAR_TERM_HARMS_READING', 22).
test_case('testsets/all_men_created_equal__originalist_reading.pl', 'all_men_created_equal__originalist_reading', 'ALL_MEN_CREATED_EQUAL__ORIGINALIST_READING', 23).
test_case('testsets/all_men_created_equal__textualist_paradox_reading.pl', 'all_men_created_equal__textualist_paradox_reading', 'ALL_MEN_CREATED_EQUAL__TEXTUALIST_PARADOX_READING', 24).
test_case('testsets/all_men_created_equal__universalist_reading.pl', 'all_men_created_equal__universalist_reading', 'ALL_MEN_CREATED_EQUAL__UNIVERSALIST_READING', 25).
test_case('testsets/aneyoshi_land_use_prohibition__behavioral_competence_reading.pl', 'aneyoshi_land_use_prohibition__behavioral_competence_reading', 'ANEYOSHI_LAND_USE_PROHIBITION__BEHAVIORAL_COMPETENCE_READING', 26).
test_case('testsets/aneyoshi_land_use_prohibition__commemorative_husk_reading.pl', 'aneyoshi_land_use_prohibition__commemorative_husk_reading', 'ANEYOSHI_LAND_USE_PROHIBITION__COMMEMORATIVE_HUSK_READING', 27).
test_case('testsets/animal_moral_status__abolitionist_reading.pl', 'animal_moral_status__abolitionist_reading', 'ANIMAL_MORAL_STATUS__ABOLITIONIST_READING', 28).
test_case('testsets/animal_moral_status__property_reading.pl', 'animal_moral_status__property_reading', 'ANIMAL_MORAL_STATUS__PROPERTY_READING', 29).
test_case('testsets/animal_moral_status__welfare_reading.pl', 'animal_moral_status__welfare_reading', 'ANIMAL_MORAL_STATUS__WELFARE_READING', 30).
test_case('testsets/article_17_complementarity__international_oversight_reading.pl', 'article_17_complementarity__international_oversight_reading', 'ARTICLE_17_COMPLEMENTARITY__INTERNATIONAL_OVERSIGHT_READING', 31).
test_case('testsets/article_17_complementarity__national_primacy_reading.pl', 'article_17_complementarity__national_primacy_reading', 'ARTICLE_17_COMPLEMENTARITY__NATIONAL_PRIMACY_READING', 32).
test_case('testsets/article_9_war_renunciation__collective_self_defense_reading.pl', 'article_9_war_renunciation__collective_self_defense_reading', 'ARTICLE_9_WAR_RENUNCIATION__COLLECTIVE_SELF_DEFENSE_READING', 33).
test_case('testsets/article_9_war_renunciation__inherent_right_reading.pl', 'article_9_war_renunciation__inherent_right_reading', 'ARTICLE_9_WAR_RENUNCIATION__INHERENT_RIGHT_READING', 34).
test_case('testsets/article_9_war_renunciation__strict_pacifist_reading.pl', 'article_9_war_renunciation__strict_pacifist_reading', 'ARTICLE_9_WAR_RENUNCIATION__STRICT_PACIFIST_READING', 35).
test_case('testsets/balfour_mandate_instruments__dual_obligation_indigenous_rights.pl', 'balfour_mandate_instruments__dual_obligation_indigenous_rights', 'BALFOUR_MANDATE_INSTRUMENTS__DUAL_OBLIGATION_INDIGENOUS_RIGHTS', 36).
test_case('testsets/balfour_mandate_instruments__jewish_national_home_primacy.pl', 'balfour_mandate_instruments__jewish_national_home_primacy', 'BALFOUR_MANDATE_INSTRUMENTS__JEWISH_NATIONAL_HOME_PRIMACY', 37).
test_case('testsets/balfour_mandate_instruments__mandatory_interpretive_discretion.pl', 'balfour_mandate_instruments__mandatory_interpretive_discretion', 'BALFOUR_MANDATE_INSTRUMENTS__MANDATORY_INTERPRETIVE_DISCRETION', 38).
test_case('testsets/biblical_authority__conciliar_reading.pl', 'biblical_authority__conciliar_reading', 'BIBLICAL_AUTHORITY__CONCILIAR_READING', 39).
test_case('testsets/biblical_authority__sola_scriptura_reading.pl', 'biblical_authority__sola_scriptura_reading', 'BIBLICAL_AUTHORITY__SOLA_SCRIPTURA_READING', 40).
test_case('testsets/biblical_authority__tradition_scripture_reading.pl', 'biblical_authority__tradition_scripture_reading', 'BIBLICAL_AUTHORITY__TRADITION_SCRIPTURE_READING', 41).
test_case('testsets/bitcoin_consensus_kernel__maximalist_reading.pl', 'bitcoin_consensus_kernel__maximalist_reading', 'BITCOIN_CONSENSUS_KERNEL__MAXIMALIST_READING', 42).
test_case('testsets/bitcoin_consensus_kernel__utility_reading.pl', 'bitcoin_consensus_kernel__utility_reading', 'BITCOIN_CONSENSUS_KERNEL__UTILITY_READING', 43).
test_case('testsets/bitcoin_whitepaper_purpose__electronic_cash_reading.pl', 'bitcoin_whitepaper_purpose__electronic_cash_reading', 'BITCOIN_WHITEPAPER_PURPOSE__ELECTRONIC_CASH_READING', 44).
test_case('testsets/bitcoin_whitepaper_purpose__nakamoto_oracle_opacity.pl', 'bitcoin_whitepaper_purpose__nakamoto_oracle_opacity', 'BITCOIN_WHITEPAPER_PURPOSE__NAKAMOTO_ORACLE_OPACITY', 45).
test_case('testsets/bitcoin_whitepaper_purpose__store_of_value_reading.pl', 'bitcoin_whitepaper_purpose__store_of_value_reading', 'BITCOIN_WHITEPAPER_PURPOSE__STORE_OF_VALUE_READING', 46).
test_case('testsets/border_legitimacy__freedom_of_movement_reading.pl', 'border_legitimacy__freedom_of_movement_reading', 'BORDER_LEGITIMACY__FREEDOM_OF_MOVEMENT_READING', 47).
test_case('testsets/border_legitimacy__humanitarian_obligation_reading.pl', 'border_legitimacy__humanitarian_obligation_reading', 'BORDER_LEGITIMACY__HUMANITARIAN_OBLIGATION_READING', 48).
test_case('testsets/border_legitimacy__sovereignty_reading.pl', 'border_legitimacy__sovereignty_reading', 'BORDER_LEGITIMACY__SOVEREIGNTY_READING', 49).
test_case('testsets/border_normative_status__freedom_primary.pl', 'border_normative_status__freedom_primary', 'BORDER_NORMATIVE_STATUS__FREEDOM_PRIMARY', 50).
test_case('testsets/border_normative_status__qualified_sovereignty.pl', 'border_normative_status__qualified_sovereignty', 'BORDER_NORMATIVE_STATUS__QUALIFIED_SOVEREIGNTY', 51).
test_case('testsets/border_normative_status__sovereignty_primary.pl', 'border_normative_status__sovereignty_primary', 'BORDER_NORMATIVE_STATUS__SOVEREIGNTY_PRIMARY', 52).
test_case('testsets/catastrophe_memory_transmission__hybrid_embedded_reading.pl', 'catastrophe_memory_transmission__hybrid_embedded_reading', 'CATASTROPHE_MEMORY_TRANSMISSION__HYBRID_EMBEDDED_READING', 53).
test_case('testsets/catastrophe_memory_transmission__operational_competence_reading.pl', 'catastrophe_memory_transmission__operational_competence_reading', 'CATASTROPHE_MEMORY_TRANSMISSION__OPERATIONAL_COMPETENCE_READING', 54).
test_case('testsets/catastrophe_memory_transmission__symbol_continuity_reading.pl', 'catastrophe_memory_transmission__symbol_continuity_reading', 'CATASTROPHE_MEMORY_TRANSMISSION__SYMBOL_CONTINUITY_READING', 55).
test_case('testsets/cbdr_principle__historical_responsibility_reading.pl', 'cbdr_principle__historical_responsibility_reading', 'CBDR_PRINCIPLE__HISTORICAL_RESPONSIBILITY_READING', 56).
test_case('testsets/cbdr_principle__voluntary_commitment_reading.pl', 'cbdr_principle__voluntary_commitment_reading', 'CBDR_PRINCIPLE__VOLUNTARY_COMMITMENT_READING', 57).
test_case('testsets/church_turing_thesis__epistemological_boundary_reading.pl', 'church_turing_thesis__epistemological_boundary_reading', 'CHURCH_TURING_THESIS__EPISTEMOLOGICAL_BOUNDARY_READING', 58).
test_case('testsets/church_turing_thesis__mathematical_definition_reading.pl', 'church_turing_thesis__mathematical_definition_reading', 'CHURCH_TURING_THESIS__MATHEMATICAL_DEFINITION_READING', 59).
test_case('testsets/church_turing_thesis__physical_claim_reading.pl', 'church_turing_thesis__physical_claim_reading', 'CHURCH_TURING_THESIS__PHYSICAL_CLAIM_READING', 60).
test_case('testsets/climate_harm_prevention__adaptation_priority.pl', 'climate_harm_prevention__adaptation_priority', 'CLIMATE_HARM_PREVENTION__ADAPTATION_PRIORITY', 61).
test_case('testsets/climate_harm_prevention__degrowth_reading.pl', 'climate_harm_prevention__degrowth_reading', 'CLIMATE_HARM_PREVENTION__DEGROWTH_READING', 62).
test_case('testsets/climate_harm_prevention__mitigation_priority.pl', 'climate_harm_prevention__mitigation_priority', 'CLIMATE_HARM_PREVENTION__MITIGATION_PRIORITY', 63).
test_case('testsets/climate_mitigation_imperative__opportunity_cost_reading.pl', 'climate_mitigation_imperative__opportunity_cost_reading', 'CLIMATE_MITIGATION_IMPERATIVE__OPPORTUNITY_COST_READING', 64).
test_case('testsets/climate_mitigation_imperative__portfolio_optimization_reading.pl', 'climate_mitigation_imperative__portfolio_optimization_reading', 'CLIMATE_MITIGATION_IMPERATIVE__PORTFOLIO_OPTIMIZATION_READING', 65).
test_case('testsets/climate_mitigation_imperative__systems_transition_reading.pl', 'climate_mitigation_imperative__systems_transition_reading', 'CLIMATE_MITIGATION_IMPERATIVE__SYSTEMS_TRANSITION_READING', 66).
test_case('testsets/climate_response_action__adaptation_priority.pl', 'climate_response_action__adaptation_priority', 'CLIMATE_RESPONSE_ACTION__ADAPTATION_PRIORITY', 67).
test_case('testsets/climate_response_action__degrowth_transformation.pl', 'climate_response_action__degrowth_transformation', 'CLIMATE_RESPONSE_ACTION__DEGROWTH_TRANSFORMATION', 68).
test_case('testsets/climate_response_action__mitigation_priority.pl', 'climate_response_action__mitigation_priority', 'CLIMATE_RESPONSE_ACTION__MITIGATION_PRIORITY', 69).
test_case('testsets/climate_response_obligation__adaptation_priority.pl', 'climate_response_obligation__adaptation_priority', 'CLIMATE_RESPONSE_OBLIGATION__ADAPTATION_PRIORITY', 70).
test_case('testsets/climate_response_obligation__degrowth_reading.pl', 'climate_response_obligation__degrowth_reading', 'CLIMATE_RESPONSE_OBLIGATION__DEGROWTH_READING', 71).
test_case('testsets/climate_response_obligation__mitigation_priority.pl', 'climate_response_obligation__mitigation_priority', 'CLIMATE_RESPONSE_OBLIGATION__MITIGATION_PRIORITY', 72).
test_case('testsets/combatant_status_definition__functional_protection_reading.pl', 'combatant_status_definition__functional_protection_reading', 'COMBATANT_STATUS_DEFINITION__FUNCTIONAL_PROTECTION_READING', 73).
test_case('testsets/combatant_status_definition__national_liberation_reading.pl', 'combatant_status_definition__national_liberation_reading', 'COMBATANT_STATUS_DEFINITION__NATIONAL_LIBERATION_READING', 74).
test_case('testsets/combatant_status_definition__state_centric_reading.pl', 'combatant_status_definition__state_centric_reading', 'COMBATANT_STATUS_DEFINITION__STATE_CENTRIC_READING', 75).
test_case('testsets/commerce_clause_scope__broad_effects_test.pl', 'commerce_clause_scope__broad_effects_test', 'COMMERCE_CLAUSE_SCOPE__BROAD_EFFECTS_TEST', 76).
test_case('testsets/commerce_clause_scope__intermediate_channels.pl', 'commerce_clause_scope__intermediate_channels', 'COMMERCE_CLAUSE_SCOPE__INTERMEDIATE_CHANNELS', 77).
test_case('testsets/commerce_clause_scope__narrow_originalist.pl', 'commerce_clause_scope__narrow_originalist', 'COMMERCE_CLAUSE_SCOPE__NARROW_ORIGINALIST', 78).
test_case('testsets/competence_exercise_requirement__catastrophe_as_necessary_anchor.pl', 'competence_exercise_requirement__catastrophe_as_necessary_anchor', 'COMPETENCE_EXERCISE_REQUIREMENT__CATASTROPHE_AS_NECESSARY_ANCHOR', 79).
test_case('testsets/competence_exercise_requirement__hybrid_dependency.pl', 'competence_exercise_requirement__hybrid_dependency', 'COMPETENCE_EXERCISE_REQUIREMENT__HYBRID_DEPENDENCY', 80).
test_case('testsets/competence_exercise_requirement__simulation_as_adequate_exercise.pl', 'competence_exercise_requirement__simulation_as_adequate_exercise', 'COMPETENCE_EXERCISE_REQUIREMENT__SIMULATION_AS_ADEQUATE_EXERCISE', 81).
test_case('testsets/competence_exercise_validity__continuous_refresh_hybrid.pl', 'competence_exercise_validity__continuous_refresh_hybrid', 'COMPETENCE_EXERCISE_VALIDITY__CONTINUOUS_REFRESH_HYBRID', 82).
test_case('testsets/competence_exercise_validity__real_catastrophe_only.pl', 'competence_exercise_validity__real_catastrophe_only', 'COMPETENCE_EXERCISE_VALIDITY__REAL_CATASTROPHE_ONLY', 83).
test_case('testsets/competence_exercise_validity__simulation_as_proxy.pl', 'competence_exercise_validity__simulation_as_proxy', 'COMPETENCE_EXERCISE_VALIDITY__SIMULATION_AS_PROXY', 84).
test_case('testsets/constitutional_authority_boundary__coordinate_construction_reading.pl', 'constitutional_authority_boundary__coordinate_construction_reading', 'CONSTITUTIONAL_AUTHORITY_BOUNDARY__COORDINATE_CONSTRUCTION_READING', 85).
test_case('testsets/constitutional_authority_boundary__judicial_supremacy_reading.pl', 'constitutional_authority_boundary__judicial_supremacy_reading', 'CONSTITUTIONAL_AUTHORITY_BOUNDARY__JUDICIAL_SUPREMACY_READING', 86).
test_case('testsets/constitutional_authority_boundary__parliamentary_primacy_reading.pl', 'constitutional_authority_boundary__parliamentary_primacy_reading', 'CONSTITUTIONAL_AUTHORITY_BOUNDARY__PARLIAMENTARY_PRIMACY_READING', 87).
test_case('testsets/constitutional_text_authority__living_constitutionalist_reading.pl', 'constitutional_text_authority__living_constitutionalist_reading', 'CONSTITUTIONAL_TEXT_AUTHORITY__LIVING_CONSTITUTIONALIST_READING', 88).
test_case('testsets/constitutional_text_authority__originalist_reading.pl', 'constitutional_text_authority__originalist_reading', 'CONSTITUTIONAL_TEXT_AUTHORITY__ORIGINALIST_READING', 89).
test_case('testsets/constitutional_text_authority__positivist_reading.pl', 'constitutional_text_authority__positivist_reading', 'CONSTITUTIONAL_TEXT_AUTHORITY__POSITIVIST_READING', 90).
test_case('testsets/correct_latin__continuity_reading.pl', 'correct_latin__continuity_reading', 'CORRECT_LATIN__CONTINUITY_READING', 91).
test_case('testsets/correct_latin__discontinuity_reading.pl', 'correct_latin__discontinuity_reading', 'CORRECT_LATIN__DISCONTINUITY_READING', 92).
test_case('testsets/correct_latin__hybrid_reading.pl', 'correct_latin__hybrid_reading', 'CORRECT_LATIN__HYBRID_READING', 93).
test_case('testsets/correct_latin_kernel__continuity_reading.pl', 'correct_latin_kernel__continuity_reading', 'CORRECT_LATIN_KERNEL__CONTINUITY_READING', 94).
test_case('testsets/correct_latin_kernel__discontinuity_reading.pl', 'correct_latin_kernel__discontinuity_reading', 'CORRECT_LATIN_KERNEL__DISCONTINUITY_READING', 95).
test_case('testsets/correct_latin_kernel__hybrid_reading.pl', 'correct_latin_kernel__hybrid_reading', 'CORRECT_LATIN_KERNEL__HYBRID_READING', 96).
test_case('testsets/cultural_property_legal_corpus__indigenous_stewardship_reading.pl', 'cultural_property_legal_corpus__indigenous_stewardship_reading', 'CULTURAL_PROPERTY_LEGAL_CORPUS__INDIGENOUS_STEWARDSHIP_READING', 97).
test_case('testsets/cultural_property_legal_corpus__sovereign_repatriation_reading.pl', 'cultural_property_legal_corpus__sovereign_repatriation_reading', 'CULTURAL_PROPERTY_LEGAL_CORPUS__SOVEREIGN_REPATRIATION_READING', 98).
test_case('testsets/cultural_property_legal_corpus__universal_heritage_reading.pl', 'cultural_property_legal_corpus__universal_heritage_reading', 'CULTURAL_PROPERTY_LEGAL_CORPUS__UNIVERSAL_HERITAGE_READING', 99).
test_case('testsets/decalogue_image_prohibition__iconoclast_reading.pl', 'decalogue_image_prohibition__iconoclast_reading', 'DECALOGUE_IMAGE_PROHIBITION__ICONOCLAST_READING', 100).
test_case('testsets/decalogue_image_prohibition__iconodule_reading.pl', 'decalogue_image_prohibition__iconodule_reading', 'DECALOGUE_IMAGE_PROHIBITION__ICONODULE_READING', 101).
test_case('testsets/decalogue_image_prohibition__moderate_iconoclast_reading.pl', 'decalogue_image_prohibition__moderate_iconoclast_reading', 'DECALOGUE_IMAGE_PROHIBITION__MODERATE_ICONOCLAST_READING', 102).
test_case('testsets/demographic_skill_mismatch_c0.pl', 'demographic_skill_mismatch_c0', 'DEMOGRAPHIC_SKILL_MISMATCH_C0', 103).
test_case('testsets/digital_money_emergence_boundary__conceptualization_reading.pl', 'digital_money_emergence_boundary__conceptualization_reading', 'DIGITAL_MONEY_EMERGENCE_BOUNDARY__CONCEPTUALIZATION_READING', 104).
test_case('testsets/digital_money_emergence_boundary__consumer_holdings_reading.pl', 'digital_money_emergence_boundary__consumer_holdings_reading', 'DIGITAL_MONEY_EMERGENCE_BOUNDARY__CONSUMER_HOLDINGS_READING', 105).
test_case('testsets/digital_money_emergence_boundary__infrastructure_reading.pl', 'digital_money_emergence_boundary__infrastructure_reading', 'DIGITAL_MONEY_EMERGENCE_BOUNDARY__INFRASTRUCTURE_READING', 106).
test_case('testsets/digital_money_origin__became_thinkable_reading.pl', 'digital_money_origin__became_thinkable_reading', 'DIGITAL_MONEY_ORIGIN__BECAME_THINKABLE_READING', 107).
test_case('testsets/digital_money_origin__first_held_reading.pl', 'digital_money_origin__first_held_reading', 'DIGITAL_MONEY_ORIGIN__FIRST_HELD_READING', 108).
test_case('testsets/digital_money_origin__regulatory_recognition_reading.pl', 'digital_money_origin__regulatory_recognition_reading', 'DIGITAL_MONEY_ORIGIN__REGULATORY_RECOGNITION_READING', 109).
test_case('testsets/divine_legitimacy_substrate__amun_polytheistic_reading.pl', 'divine_legitimacy_substrate__amun_polytheistic_reading', 'DIVINE_LEGITIMACY_SUBSTRATE__AMUN_POLYTHEISTIC_READING', 110).
test_case('testsets/divine_legitimacy_substrate__atenist_monotheistic_reading.pl', 'divine_legitimacy_substrate__atenist_monotheistic_reading', 'DIVINE_LEGITIMACY_SUBSTRATE__ATENIST_MONOTHEISTIC_READING', 111).
test_case('testsets/divine_legitimacy_substrate__folk_syncretistic_reading.pl', 'divine_legitimacy_substrate__folk_syncretistic_reading', 'DIVINE_LEGITIMACY_SUBSTRATE__FOLK_SYNCRETISTIC_READING', 112).
test_case('testsets/dollar_gold_convertibility__policy_flexible_reading.pl', 'dollar_gold_convertibility__policy_flexible_reading', 'DOLLAR_GOLD_CONVERTIBILITY__POLICY_FLEXIBLE_READING', 113).
test_case('testsets/dollar_gold_convertibility__strict_convertibility_reading.pl', 'dollar_gold_convertibility__strict_convertibility_reading', 'DOLLAR_GOLD_CONVERTIBILITY__STRICT_CONVERTIBILITY_READING', 114).
test_case('testsets/dollar_gold_convertibility__triffin_structural_reading.pl', 'dollar_gold_convertibility__triffin_structural_reading', 'DOLLAR_GOLD_CONVERTIBILITY__TRIFFIN_STRUCTURAL_READING', 115).
test_case('testsets/dual_class_legitimacy__disclosure_consent.pl', 'dual_class_legitimacy__disclosure_consent', 'DUAL_CLASS_LEGITIMACY__DISCLOSURE_CONSENT', 116).
test_case('testsets/dual_class_legitimacy__founder_stewardship.pl', 'dual_class_legitimacy__founder_stewardship', 'DUAL_CLASS_LEGITIMACY__FOUNDER_STEWARDSHIP', 117).
test_case('testsets/dual_class_legitimacy__minority_extraction.pl', 'dual_class_legitimacy__minority_extraction', 'DUAL_CLASS_LEGITIMACY__MINORITY_EXTRACTION', 118).
test_case('testsets/dueling_disappearance_mechanism__contraction_reading.pl', 'dueling_disappearance_mechanism__contraction_reading', 'DUELING_DISAPPEARANCE_MECHANISM__CONTRACTION_READING', 119).
test_case('testsets/dueling_disappearance_mechanism__institutional_displacement_reading.pl', 'dueling_disappearance_mechanism__institutional_displacement_reading', 'DUELING_DISAPPEARANCE_MECHANISM__INSTITUTIONAL_DISPLACEMENT_READING', 120).
test_case('testsets/dueling_disappearance_mechanism__overdetermined_composite_reading.pl', 'dueling_disappearance_mechanism__overdetermined_composite_reading', 'DUELING_DISAPPEARANCE_MECHANISM__OVERDETERMINED_COMPOSITE_READING', 121).
test_case('testsets/ecb_mandate_article_127__climate_incorporation.pl', 'ecb_mandate_article_127__climate_incorporation', 'ECB_MANDATE_ARTICLE_127__CLIMATE_INCORPORATION', 122).
test_case('testsets/ecb_mandate_article_127__expansive_secondary_objectives.pl', 'ecb_mandate_article_127__expansive_secondary_objectives', 'ECB_MANDATE_ARTICLE_127__EXPANSIVE_SECONDARY_OBJECTIVES', 123).
test_case('testsets/ecb_mandate_article_127__orthodox_price_stability.pl', 'ecb_mandate_article_127__orthodox_price_stability', 'ECB_MANDATE_ARTICLE_127__ORTHODOX_PRICE_STABILITY', 124).
test_case('testsets/employment_boundary__formalist_employment_reading.pl', 'employment_boundary__formalist_employment_reading', 'EMPLOYMENT_BOUNDARY__FORMALIST_EMPLOYMENT_READING', 125).
test_case('testsets/employment_boundary__hybrid_security_reading.pl', 'employment_boundary__hybrid_security_reading', 'EMPLOYMENT_BOUNDARY__HYBRID_SECURITY_READING', 126).
test_case('testsets/employment_boundary__substantive_employment_reading.pl', 'employment_boundary__substantive_employment_reading', 'EMPLOYMENT_BOUNDARY__SUBSTANTIVE_EMPLOYMENT_READING', 127).
test_case('testsets/end_of_life_authority__autonomy_reading.pl', 'end_of_life_authority__autonomy_reading', 'END_OF_LIFE_AUTHORITY__AUTONOMY_READING', 128).
test_case('testsets/end_of_life_authority__sanctity_reading.pl', 'end_of_life_authority__sanctity_reading', 'END_OF_LIFE_AUTHORITY__SANCTITY_READING', 129).
test_case('testsets/end_of_life_authority__slippery_slope_mechanism.pl', 'end_of_life_authority__slippery_slope_mechanism', 'END_OF_LIFE_AUTHORITY__SLIPPERY_SLOPE_MECHANISM', 130).
test_case('testsets/eternal_marriage_covenant__immutable_commandment_reading.pl', 'eternal_marriage_covenant__immutable_commandment_reading', 'ETERNAL_MARRIAGE_COVENANT__IMMUTABLE_COMMANDMENT_READING', 131).
test_case('testsets/eternal_marriage_covenant__prophetic_override_reading.pl', 'eternal_marriage_covenant__prophetic_override_reading', 'ETERNAL_MARRIAGE_COVENANT__PROPHETIC_OVERRIDE_READING', 132).
test_case('testsets/eternal_marriage_covenant__temporal_accommodation_reading.pl', 'eternal_marriage_covenant__temporal_accommodation_reading', 'ETERNAL_MARRIAGE_COVENANT__TEMPORAL_ACCOMMODATION_READING', 133).
test_case('testsets/exercise_as_competence_maintenance__hybrid_decay_reading.pl', 'exercise_as_competence_maintenance__hybrid_decay_reading', 'EXERCISE_AS_COMPETENCE_MAINTENANCE__HYBRID_DECAY_READING', 134).
test_case('testsets/exercise_as_competence_maintenance__lived_catastrophe_necessity_reading.pl', 'exercise_as_competence_maintenance__lived_catastrophe_necessity_reading', 'EXERCISE_AS_COMPETENCE_MAINTENANCE__LIVED_CATASTROPHE_NECESSITY_READING', 135).
test_case('testsets/exercise_as_competence_maintenance__simulation_sufficiency_reading.pl', 'exercise_as_competence_maintenance__simulation_sufficiency_reading', 'EXERCISE_AS_COMPETENCE_MAINTENANCE__SIMULATION_SUFFICIENCY_READING', 136).
test_case('testsets/family_law_authority__christian_canonical_reading.pl', 'family_law_authority__christian_canonical_reading', 'FAMILY_LAW_AUTHORITY__CHRISTIAN_CANONICAL_READING', 137).
test_case('testsets/family_law_authority__hindu_dharmashastra_reading.pl', 'family_law_authority__hindu_dharmashastra_reading', 'FAMILY_LAW_AUTHORITY__HINDU_DHARMASHASTRA_READING', 138).
test_case('testsets/family_law_authority__muslim_shariat_reading.pl', 'family_law_authority__muslim_shariat_reading', 'FAMILY_LAW_AUTHORITY__MUSLIM_SHARIAT_READING', 139).
test_case('testsets/family_law_authority__parsi_zoroastrian_reading.pl', 'family_law_authority__parsi_zoroastrian_reading', 'FAMILY_LAW_AUTHORITY__PARSI_ZOROASTRIAN_READING', 140).
test_case('testsets/family_law_authority__secular_contractual_reading.pl', 'family_law_authority__secular_contractual_reading', 'FAMILY_LAW_AUTHORITY__SECULAR_CONTRACTUAL_READING', 141).
test_case('testsets/federation_membership__integration_reading.pl', 'federation_membership__integration_reading', 'FEDERATION_MEMBERSHIP__INTEGRATION_READING', 142).
test_case('testsets/federation_membership__sovereignty_reading.pl', 'federation_membership__sovereignty_reading', 'FEDERATION_MEMBERSHIP__SOVEREIGNTY_READING', 143).
test_case('testsets/federation_membership_kernel__integration_reading.pl', 'federation_membership_kernel__integration_reading', 'FEDERATION_MEMBERSHIP_KERNEL__INTEGRATION_READING', 144).
test_case('testsets/federation_membership_kernel__member_sovereignty_reading.pl', 'federation_membership_kernel__member_sovereignty_reading', 'FEDERATION_MEMBERSHIP_KERNEL__MEMBER_SOVEREIGNTY_READING', 145).
test_case('testsets/federation_membership_kernel__welfare_coordination_reading.pl', 'federation_membership_kernel__welfare_coordination_reading', 'FEDERATION_MEMBERSHIP_KERNEL__WELFARE_COORDINATION_READING', 146).
test_case('testsets/federation_membership_obligations__integration_primary.pl', 'federation_membership_obligations__integration_primary', 'FEDERATION_MEMBERSHIP_OBLIGATIONS__INTEGRATION_PRIMARY', 147).
test_case('testsets/federation_membership_obligations__member_sovereignty_primary.pl', 'federation_membership_obligations__member_sovereignty_primary', 'FEDERATION_MEMBERSHIP_OBLIGATIONS__MEMBER_SOVEREIGNTY_PRIMARY', 148).
test_case('testsets/federation_membership_obligations__selective_solidarity.pl', 'federation_membership_obligations__selective_solidarity', 'FEDERATION_MEMBERSHIP_OBLIGATIONS__SELECTIVE_SOLIDARITY', 149).
test_case('testsets/feud_obligation_kernel__christianized_pacification_reading.pl', 'feud_obligation_kernel__christianized_pacification_reading', 'FEUD_OBLIGATION_KERNEL__CHRISTIANIZED_PACIFICATION_READING', 150).
test_case('testsets/feud_obligation_kernel__extraction_cycle_reading.pl', 'feud_obligation_kernel__extraction_cycle_reading', 'FEUD_OBLIGATION_KERNEL__EXTRACTION_CYCLE_READING', 151).
test_case('testsets/feud_obligation_kernel__stateless_coordination_reading.pl', 'feud_obligation_kernel__stateless_coordination_reading', 'FEUD_OBLIGATION_KERNEL__STATELESS_COORDINATION_READING', 152).
test_case('testsets/fifth_republic_constitution__cohabitation_equilibrium_reading.pl', 'fifth_republic_constitution__cohabitation_equilibrium_reading', 'FIFTH_REPUBLIC_CONSTITUTION__COHABITATION_EQUILIBRIUM_READING', 153).
test_case('testsets/fifth_republic_constitution__hyper_presidential_reading.pl', 'fifth_republic_constitution__hyper_presidential_reading', 'FIFTH_REPUBLIC_CONSTITUTION__HYPER_PRESIDENTIAL_READING', 154).
test_case('testsets/fifth_republic_constitution__parliamentary_constraint_reading.pl', 'fifth_republic_constitution__parliamentary_constraint_reading', 'FIFTH_REPUBLIC_CONSTITUTION__PARLIAMENTARY_CONSTRAINT_READING', 155).
test_case('testsets/genesis_creation_cosmology__literary_framework.pl', 'genesis_creation_cosmology__literary_framework', 'GENESIS_CREATION_COSMOLOGY__LITERARY_FRAMEWORK', 156).
test_case('testsets/genesis_creation_cosmology__theistic_evolution.pl', 'genesis_creation_cosmology__theistic_evolution', 'GENESIS_CREATION_COSMOLOGY__THEISTIC_EVOLUTION', 157).
test_case('testsets/genesis_creation_cosmology__young_earth_literal.pl', 'genesis_creation_cosmology__young_earth_literal', 'GENESIS_CREATION_COSMOLOGY__YOUNG_EARTH_LITERAL', 158).
test_case('testsets/geneva_conventions_protective_scope__hybrid_proportionality_reading.pl', 'geneva_conventions_protective_scope__hybrid_proportionality_reading', 'GENEVA_CONVENTIONS_PROTECTIVE_SCOPE__HYBRID_PROPORTIONALITY_READING', 159).
test_case('testsets/geneva_conventions_protective_scope__state_centric_reading.pl', 'geneva_conventions_protective_scope__state_centric_reading', 'GENEVA_CONVENTIONS_PROTECTIVE_SCOPE__STATE_CENTRIC_READING', 160).
test_case('testsets/geneva_conventions_protective_scope__universal_rights_reading.pl', 'geneva_conventions_protective_scope__universal_rights_reading', 'GENEVA_CONVENTIONS_PROTECTIVE_SCOPE__UNIVERSAL_RIGHTS_READING', 161).
test_case('testsets/gita_kurukshetra_discourse__gandhian_allegorical_reading.pl', 'gita_kurukshetra_discourse__gandhian_allegorical_reading', 'GITA_KURUKSHETRA_DISCOURSE__GANDHIAN_ALLEGORICAL_READING', 162).
test_case('testsets/gita_kurukshetra_discourse__orthodox_literal_reading.pl', 'gita_kurukshetra_discourse__orthodox_literal_reading', 'GITA_KURUKSHETRA_DISCOURSE__ORTHODOX_LITERAL_READING', 163).
test_case('testsets/gita_kurukshetra_discourse__universalist_devotional_reading.pl', 'gita_kurukshetra_discourse__universalist_devotional_reading', 'GITA_KURUKSHETRA_DISCOURSE__UNIVERSALIST_DEVOTIONAL_READING', 164).
test_case('testsets/gold_fiat_transition_mechanism__automatic_constraint_reading.pl', 'gold_fiat_transition_mechanism__automatic_constraint_reading', 'GOLD_FIAT_TRANSITION_MECHANISM__AUTOMATIC_CONSTRAINT_READING', 165).
test_case('testsets/gold_fiat_transition_mechanism__composite_overdetermination_reading.pl', 'gold_fiat_transition_mechanism__composite_overdetermination_reading', 'GOLD_FIAT_TRANSITION_MECHANISM__COMPOSITE_OVERDETERMINATION_READING', 166).
test_case('testsets/gold_fiat_transition_mechanism__creditor_discipline_reading.pl', 'gold_fiat_transition_mechanism__creditor_discipline_reading', 'GOLD_FIAT_TRANSITION_MECHANISM__CREDITOR_DISCIPLINE_READING', 167).
test_case('testsets/gpl_copyleft_scope__enforcement_vacuum_reading.pl', 'gpl_copyleft_scope__enforcement_vacuum_reading', 'GPL_COPYLEFT_SCOPE__ENFORCEMENT_VACUUM_READING', 168).
test_case('testsets/gpl_copyleft_scope__narrow_scope_reading.pl', 'gpl_copyleft_scope__narrow_scope_reading', 'GPL_COPYLEFT_SCOPE__NARROW_SCOPE_READING', 169).
test_case('testsets/gpl_copyleft_scope__strong_copyleft_reading.pl', 'gpl_copyleft_scope__strong_copyleft_reading', 'GPL_COPYLEFT_SCOPE__STRONG_COPYLEFT_READING', 170).
test_case('testsets/hagia_sophia_substrate__islamic_sovereignty_reading.pl', 'hagia_sophia_substrate__islamic_sovereignty_reading', 'HAGIA_SOPHIA_SUBSTRATE__ISLAMIC_SOVEREIGNTY_READING', 171).
test_case('testsets/hagia_sophia_substrate__orthodox_restitution_reading.pl', 'hagia_sophia_substrate__orthodox_restitution_reading', 'HAGIA_SOPHIA_SUBSTRATE__ORTHODOX_RESTITUTION_READING', 172).
test_case('testsets/hagia_sophia_substrate__universal_heritage_reading.pl', 'hagia_sophia_substrate__universal_heritage_reading', 'HAGIA_SOPHIA_SUBSTRATE__UNIVERSAL_HERITAGE_READING', 173).
test_case('testsets/hebrew_continuity__bridge_pidginized.pl', 'hebrew_continuity__bridge_pidginized', 'HEBREW_CONTINUITY__BRIDGE_PIDGINIZED', 174).
test_case('testsets/hebrew_continuity__liturgical_preservation.pl', 'hebrew_continuity__liturgical_preservation', 'HEBREW_CONTINUITY__LITURGICAL_PRESERVATION', 175).
test_case('testsets/hebrew_continuity__native_generative.pl', 'hebrew_continuity__native_generative', 'HEBREW_CONTINUITY__NATIVE_GENERATIVE', 176).
test_case('testsets/hebrew_living_language__literary_revival_reading.pl', 'hebrew_living_language__literary_revival_reading', 'HEBREW_LIVING_LANGUAGE__LITERARY_REVIVAL_READING', 177).
test_case('testsets/hebrew_living_language__liturgical_continuity_reading.pl', 'hebrew_living_language__liturgical_continuity_reading', 'HEBREW_LIVING_LANGUAGE__LITURGICAL_CONTINUITY_READING', 178).
test_case('testsets/hebrew_living_language__native_generation_reading.pl', 'hebrew_living_language__native_generation_reading', 'HEBREW_LIVING_LANGUAGE__NATIVE_GENERATION_READING', 179).
test_case('testsets/hebrew_vitality__hybrid_continuity_reading.pl', 'hebrew_vitality__hybrid_continuity_reading', 'HEBREW_VITALITY__HYBRID_CONTINUITY_READING', 180).
test_case('testsets/hebrew_vitality__liturgical_reading.pl', 'hebrew_vitality__liturgical_reading', 'HEBREW_VITALITY__LITURGICAL_READING', 181).
test_case('testsets/hebrew_vitality__native_daily_reading.pl', 'hebrew_vitality__native_daily_reading', 'HEBREW_VITALITY__NATIVE_DAILY_READING', 182).
test_case('testsets/historical_treaty_substrate__extinguishment_reading.pl', 'historical_treaty_substrate__extinguishment_reading', 'HISTORICAL_TREATY_SUBSTRATE__EXTINGUISHMENT_READING', 183).
test_case('testsets/historical_treaty_substrate__nation_to_nation_reading.pl', 'historical_treaty_substrate__nation_to_nation_reading', 'HISTORICAL_TREATY_SUBSTRATE__NATION_TO_NATION_READING', 184).
test_case('testsets/honor_settlement_legitimacy__composite_reading.pl', 'honor_settlement_legitimacy__composite_reading', 'HONOR_SETTLEMENT_LEGITIMACY__COMPOSITE_READING', 185).
test_case('testsets/honor_settlement_legitimacy__contraction_reading.pl', 'honor_settlement_legitimacy__contraction_reading', 'HONOR_SETTLEMENT_LEGITIMACY__CONTRACTION_READING', 186).
test_case('testsets/honor_settlement_legitimacy__drop_reading.pl', 'honor_settlement_legitimacy__drop_reading', 'HONOR_SETTLEMENT_LEGITIMACY__DROP_READING', 187).
test_case('testsets/human_dignity_ai_governance__magisterial_integralist_reading.pl', 'human_dignity_ai_governance__magisterial_integralist_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__MAGISTERIAL_INTEGRALIST_READING', 188).
test_case('testsets/human_dignity_ai_governance__pluralist_pragmatic_reading.pl', 'human_dignity_ai_governance__pluralist_pragmatic_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__PLURALIST_PRAGMATIC_READING', 189).
test_case('testsets/human_dignity_ai_governance__secular_humanist_reading.pl', 'human_dignity_ai_governance__secular_humanist_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__SECULAR_HUMANIST_READING', 190).
test_case('testsets/human_dignity_ai_governance__techno_optimist_reading.pl', 'human_dignity_ai_governance__techno_optimist_reading', 'HUMAN_DIGNITY_AI_GOVERNANCE__TECHNO_OPTIMIST_READING', 191).
test_case('testsets/human_dignity_ai_safeguarding__autonomy_rights_reading.pl', 'human_dignity_ai_safeguarding__autonomy_rights_reading', 'HUMAN_DIGNITY_AI_SAFEGUARDING__AUTONOMY_RIGHTS_READING', 192).
test_case('testsets/human_dignity_ai_safeguarding__imago_dei_reading.pl', 'human_dignity_ai_safeguarding__imago_dei_reading', 'HUMAN_DIGNITY_AI_SAFEGUARDING__IMAGO_DEI_READING', 193).
test_case('testsets/human_dignity_ai_safeguarding__posthumanist_reading.pl', 'human_dignity_ai_safeguarding__posthumanist_reading', 'HUMAN_DIGNITY_AI_SAFEGUARDING__POSTHUMANIST_READING', 194).
test_case('testsets/human_transcendence_pathway__babel_reading.pl', 'human_transcendence_pathway__babel_reading', 'HUMAN_TRANSCENDENCE_PATHWAY__BABEL_READING', 195).
test_case('testsets/human_transcendence_pathway__jerusalem_reading.pl', 'human_transcendence_pathway__jerusalem_reading', 'HUMAN_TRANSCENDENCE_PATHWAY__JERUSALEM_READING', 196).
test_case('testsets/human_transcendence_pathway__technocratic_vs_incarnational_reading.pl', 'human_transcendence_pathway__technocratic_vs_incarnational_reading', 'HUMAN_TRANSCENDENCE_PATHWAY__TECHNOCRATIC_VS_INCARNATIONAL_READING', 197).
test_case('testsets/imposition_mechanism_kernel__endogenous_climb_reading.pl', 'imposition_mechanism_kernel__endogenous_climb_reading', 'IMPOSITION_MECHANISM_KERNEL__ENDOGENOUS_CLIMB_READING', 198).
test_case('testsets/imposition_mechanism_kernel__exogenous_override_reading.pl', 'imposition_mechanism_kernel__exogenous_override_reading', 'IMPOSITION_MECHANISM_KERNEL__EXOGENOUS_OVERRIDE_READING', 199).
test_case('testsets/imposition_mechanism_kernel__hybrid_legitimation_reading.pl', 'imposition_mechanism_kernel__hybrid_legitimation_reading', 'IMPOSITION_MECHANISM_KERNEL__HYBRID_LEGITIMATION_READING', 200).
test_case('testsets/imposition_pathway_kernel__endogenous_climb_reading.pl', 'imposition_pathway_kernel__endogenous_climb_reading', 'IMPOSITION_PATHWAY_KERNEL__ENDOGENOUS_CLIMB_READING', 201).
test_case('testsets/imposition_pathway_kernel__exogenous_override_reading.pl', 'imposition_pathway_kernel__exogenous_override_reading', 'IMPOSITION_PATHWAY_KERNEL__EXOGENOUS_OVERRIDE_READING', 202).
test_case('testsets/imposition_pathway_kernel__hybrid_cascade_reading.pl', 'imposition_pathway_kernel__hybrid_cascade_reading', 'IMPOSITION_PATHWAY_KERNEL__HYBRID_CASCADE_READING', 203).
test_case('testsets/income_support_commitment__dependency_trap_reading.pl', 'income_support_commitment__dependency_trap_reading', 'INCOME_SUPPORT_COMMITMENT__DEPENDENCY_TRAP_READING', 204).
test_case('testsets/income_support_commitment__freedom_floor_reading.pl', 'income_support_commitment__freedom_floor_reading', 'INCOME_SUPPORT_COMMITMENT__FREEDOM_FLOOR_READING', 205).
test_case('testsets/income_support_commitment__targeting_efficiency_reading.pl', 'income_support_commitment__targeting_efficiency_reading', 'INCOME_SUPPORT_COMMITMENT__TARGETING_EFFICIENCY_READING', 206).
test_case('testsets/income_support_conditionality__dependency_trap_reading.pl', 'income_support_conditionality__dependency_trap_reading', 'INCOME_SUPPORT_CONDITIONALITY__DEPENDENCY_TRAP_READING', 207).
test_case('testsets/income_support_conditionality__freedom_floor_reading.pl', 'income_support_conditionality__freedom_floor_reading', 'INCOME_SUPPORT_CONDITIONALITY__FREEDOM_FLOOR_READING', 208).
test_case('testsets/income_support_conditionality__wage_subsidy_reading.pl', 'income_support_conditionality__wage_subsidy_reading', 'INCOME_SUPPORT_CONDITIONALITY__WAGE_SUBSIDY_READING', 209).
test_case('testsets/institutional_trust_erosion_c0.pl', 'institutional_trust_erosion_c0', 'INSTITUTIONAL_TRUST_EROSION_C0', 210).
test_case('testsets/jewish_territorial_claim__cultural_zionism_reading.pl', 'jewish_territorial_claim__cultural_zionism_reading', 'JEWISH_TERRITORIAL_CLAIM__CULTURAL_ZIONISM_READING', 211).
test_case('testsets/jewish_territorial_claim__political_zionism_reading.pl', 'jewish_territorial_claim__political_zionism_reading', 'JEWISH_TERRITORIAL_CLAIM__POLITICAL_ZIONISM_READING', 212).
test_case('testsets/jewish_territorial_claim__revisionist_zionism_reading.pl', 'jewish_territorial_claim__revisionist_zionism_reading', 'JEWISH_TERRITORIAL_CLAIM__REVISIONIST_ZIONISM_READING', 213).
test_case('testsets/jurisprudential_method_kernel__hanafi_reading.pl', 'jurisprudential_method_kernel__hanafi_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__HANAFI_READING', 214).
test_case('testsets/jurisprudential_method_kernel__hanbali_reading.pl', 'jurisprudential_method_kernel__hanbali_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__HANBALI_READING', 215).
test_case('testsets/jurisprudential_method_kernel__maliki_reading.pl', 'jurisprudential_method_kernel__maliki_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__MALIKI_READING', 216).
test_case('testsets/jurisprudential_method_kernel__shafii_reading.pl', 'jurisprudential_method_kernel__shafii_reading', 'JURISPRUDENTIAL_METHOD_KERNEL__SHAFII_READING', 217).
test_case('testsets/kami_buddha_ontology__domain_partition.pl', 'kami_buddha_ontology__domain_partition', 'KAMI_BUDDHA_ONTOLOGY__DOMAIN_PARTITION', 218).
test_case('testsets/kami_buddha_ontology__honji_suijaku_monism.pl', 'kami_buddha_ontology__honji_suijaku_monism', 'KAMI_BUDDHA_ONTOLOGY__HONJI_SUIJAKU_MONISM', 219).
test_case('testsets/kami_buddha_ontology__incoherent_bundle.pl', 'kami_buddha_ontology__incoherent_bundle', 'KAMI_BUDDHA_ONTOLOGY__INCOHERENT_BUNDLE', 220).
test_case('testsets/kjv_text_1611__exclusive_inspiration_reading.pl', 'kjv_text_1611__exclusive_inspiration_reading', 'KJV_TEXT_1611__EXCLUSIVE_INSPIRATION_READING', 221).
test_case('testsets/kjv_text_1611__functional_equivalence_reading.pl', 'kjv_text_1611__functional_equivalence_reading', 'KJV_TEXT_1611__FUNCTIONAL_EQUIVALENCE_READING', 222).
test_case('testsets/kjv_text_1611__revisable_translation_reading.pl', 'kjv_text_1611__revisable_translation_reading', 'KJV_TEXT_1611__REVISABLE_TRANSLATION_READING', 223).
test_case('testsets/kodashim_obligation__study_as_archive.pl', 'kodashim_obligation__study_as_archive', 'KODASHIM_OBLIGATION__STUDY_AS_ARCHIVE', 224).
test_case('testsets/kodashim_obligation__study_as_performance.pl', 'kodashim_obligation__study_as_performance', 'KODASHIM_OBLIGATION__STUDY_AS_PERFORMANCE', 225).
test_case('testsets/kodashim_obligation__study_as_preparation.pl', 'kodashim_obligation__study_as_preparation', 'KODASHIM_OBLIGATION__STUDY_AS_PREPARATION', 226).
test_case('testsets/lausanne_minority_protections__expansive_reading.pl', 'lausanne_minority_protections__expansive_reading', 'LAUSANNE_MINORITY_PROTECTIONS__EXPANSIVE_READING', 227).
test_case('testsets/lausanne_minority_protections__guarantor_reading.pl', 'lausanne_minority_protections__guarantor_reading', 'LAUSANNE_MINORITY_PROTECTIONS__GUARANTOR_READING', 228).
test_case('testsets/lausanne_minority_protections__restrictive_reading.pl', 'lausanne_minority_protections__restrictive_reading', 'LAUSANNE_MINORITY_PROTECTIONS__RESTRICTIVE_READING', 229).
test_case('testsets/legal_personhood_boundary__developmental_potentiality_reading.pl', 'legal_personhood_boundary__developmental_potentiality_reading', 'LEGAL_PERSONHOOD_BOUNDARY__DEVELOPMENTAL_POTENTIALITY_READING', 230).
test_case('testsets/legal_personhood_boundary__functional_capacity_reading.pl', 'legal_personhood_boundary__functional_capacity_reading', 'LEGAL_PERSONHOOD_BOUNDARY__FUNCTIONAL_CAPACITY_READING', 231).
test_case('testsets/legal_personhood_boundary__restrictive_anthropocentric_reading.pl', 'legal_personhood_boundary__restrictive_anthropocentric_reading', 'LEGAL_PERSONHOOD_BOUNDARY__RESTRICTIVE_ANTHROPOCENTRIC_READING', 232).
test_case('testsets/legitimate_health_intervention__bodily_autonomy_primary.pl', 'legitimate_health_intervention__bodily_autonomy_primary', 'LEGITIMATE_HEALTH_INTERVENTION__BODILY_AUTONOMY_PRIMARY', 233).
test_case('testsets/legitimate_health_intervention__proportionality_reading.pl', 'legitimate_health_intervention__proportionality_reading', 'LEGITIMATE_HEALTH_INTERVENTION__PROPORTIONALITY_READING', 234).
test_case('testsets/legitimate_health_intervention__public_health_primary.pl', 'legitimate_health_intervention__public_health_primary', 'LEGITIMATE_HEALTH_INTERVENTION__PUBLIC_HEALTH_PRIMARY', 235).
test_case('testsets/liability_attribution__deployer_liability.pl', 'liability_attribution__deployer_liability', 'LIABILITY_ATTRIBUTION__DEPLOYER_LIABILITY', 236).
test_case('testsets/liability_attribution__developer_liability.pl', 'liability_attribution__developer_liability', 'LIABILITY_ATTRIBUTION__DEVELOPER_LIABILITY', 237).
test_case('testsets/liability_attribution__shared_liability.pl', 'liability_attribution__shared_liability', 'LIABILITY_ATTRIBUTION__SHARED_LIABILITY', 238).
test_case('testsets/literacy_acquisition_kernel__balanced_literacy_reading.pl', 'literacy_acquisition_kernel__balanced_literacy_reading', 'LITERACY_ACQUISITION_KERNEL__BALANCED_LITERACY_READING', 239).
test_case('testsets/literacy_acquisition_kernel__phonics_reading.pl', 'literacy_acquisition_kernel__phonics_reading', 'LITERACY_ACQUISITION_KERNEL__PHONICS_READING', 240).
test_case('testsets/literacy_acquisition_kernel__structured_literacy_reading.pl', 'literacy_acquisition_kernel__structured_literacy_reading', 'LITERACY_ACQUISITION_KERNEL__STRUCTURED_LITERACY_READING', 241).
test_case('testsets/literacy_acquisition_kernel__whole_language_reading.pl', 'literacy_acquisition_kernel__whole_language_reading', 'LITERACY_ACQUISITION_KERNEL__WHOLE_LANGUAGE_READING', 242).
test_case('testsets/living_language_status__literary_continuity_reading.pl', 'living_language_status__literary_continuity_reading', 'LIVING_LANGUAGE_STATUS__LITERARY_CONTINUITY_READING', 243).
test_case('testsets/living_language_status__liturgical_preservation_reading.pl', 'living_language_status__liturgical_preservation_reading', 'LIVING_LANGUAGE_STATUS__LITURGICAL_PRESERVATION_READING', 244).
test_case('testsets/living_language_status__native_generation_reading.pl', 'living_language_status__native_generation_reading', 'LIVING_LANGUAGE_STATUS__NATIVE_GENERATION_READING', 245).
test_case('testsets/magna_carta_1215__baronial_privilege_reading.pl', 'magna_carta_1215__baronial_privilege_reading', 'MAGNA_CARTA_1215__BARONIAL_PRIVILEGE_READING', 246).
test_case('testsets/magna_carta_1215__living_document_reading.pl', 'magna_carta_1215__living_document_reading', 'MAGNA_CARTA_1215__LIVING_DOCUMENT_READING', 247).
test_case('testsets/magna_carta_1215__universal_rights_reading.pl', 'magna_carta_1215__universal_rights_reading', 'MAGNA_CARTA_1215__UNIVERSAL_RIGHTS_READING', 248).
test_case('testsets/market_as_natural_default__beneficiary_maintained_reading.pl', 'market_as_natural_default__beneficiary_maintained_reading', 'MARKET_AS_NATURAL_DEFAULT__BENEFICIARY_MAINTAINED_READING', 249).
test_case('testsets/market_as_natural_default__hybrid_amnesia_reading.pl', 'market_as_natural_default__hybrid_amnesia_reading', 'MARKET_AS_NATURAL_DEFAULT__HYBRID_AMNESIA_READING', 250).
test_case('testsets/market_as_natural_default__lapsed_alternative_reading.pl', 'market_as_natural_default__lapsed_alternative_reading', 'MARKET_AS_NATURAL_DEFAULT__LAPSED_ALTERNATIVE_READING', 251).
test_case('testsets/market_naturalization__beneficiary_maintained_reading.pl', 'market_naturalization__beneficiary_maintained_reading', 'MARKET_NATURALIZATION__BENEFICIARY_MAINTAINED_READING', 252).
test_case('testsets/market_naturalization__hybrid_reading.pl', 'market_naturalization__hybrid_reading', 'MARKET_NATURALIZATION__HYBRID_READING', 253).
test_case('testsets/market_naturalization__lapsed_alternative_reading.pl', 'market_naturalization__lapsed_alternative_reading', 'MARKET_NATURALIZATION__LAPSED_ALTERNATIVE_READING', 254).
test_case('testsets/marriage_authority__communal_autonomy_reading.pl', 'marriage_authority__communal_autonomy_reading', 'MARRIAGE_AUTHORITY__COMMUNAL_AUTONOMY_READING', 255).
test_case('testsets/marriage_authority__federalist_millet_reading.pl', 'marriage_authority__federalist_millet_reading', 'MARRIAGE_AUTHORITY__FEDERALIST_MILLET_READING', 256).
test_case('testsets/marriage_authority__gender_rights_reading.pl', 'marriage_authority__gender_rights_reading', 'MARRIAGE_AUTHORITY__GENDER_RIGHTS_READING', 257).
test_case('testsets/marriage_authority__judicial_harmonization_reading.pl', 'marriage_authority__judicial_harmonization_reading', 'MARRIAGE_AUTHORITY__JUDICIAL_HARMONIZATION_READING', 258).
test_case('testsets/marriage_authority__secularist_reading.pl', 'marriage_authority__secularist_reading', 'MARRIAGE_AUTHORITY__SECULARIST_READING', 259).
test_case('testsets/marriage_commitment_legitimacy__endogenous_reinterpretation_reading.pl', 'marriage_commitment_legitimacy__endogenous_reinterpretation_reading', 'MARRIAGE_COMMITMENT_LEGITIMACY__ENDOGENOUS_REINTERPRETATION_READING', 260).
test_case('testsets/marriage_commitment_legitimacy__exogenous_override_reading.pl', 'marriage_commitment_legitimacy__exogenous_override_reading', 'MARRIAGE_COMMITMENT_LEGITIMACY__EXOGENOUS_OVERRIDE_READING', 261).
test_case('testsets/marriage_commitment_legitimacy__hybrid_pragmatic_reading.pl', 'marriage_commitment_legitimacy__hybrid_pragmatic_reading', 'MARRIAGE_COMMITMENT_LEGITIMACY__HYBRID_PRAGMATIC_READING', 262).
test_case('testsets/marriage_commitment_reversal__endogenous_reinterpretation_reading.pl', 'marriage_commitment_reversal__endogenous_reinterpretation_reading', 'MARRIAGE_COMMITMENT_REVERSAL__ENDOGENOUS_REINTERPRETATION_READING', 263).
test_case('testsets/marriage_commitment_reversal__exogenous_override_reading.pl', 'marriage_commitment_reversal__exogenous_override_reading', 'MARRIAGE_COMMITMENT_REVERSAL__EXOGENOUS_OVERRIDE_READING', 264).
test_case('testsets/marriage_commitment_reversal__practice_doctrine_gap.pl', 'marriage_commitment_reversal__practice_doctrine_gap', 'MARRIAGE_COMMITMENT_REVERSAL__PRACTICE_DOCTRINE_GAP', 265).
test_case('testsets/marriage_sacrament__civic_pastoral_reading.pl', 'marriage_sacrament__civic_pastoral_reading', 'MARRIAGE_SACRAMENT__CIVIC_PASTORAL_READING', 266).
test_case('testsets/marriage_sacrament__hierarchical_indissolubility_reading.pl', 'marriage_sacrament__hierarchical_indissolubility_reading', 'MARRIAGE_SACRAMENT__HIERARCHICAL_INDISSOLUBILITY_READING', 267).
test_case('testsets/monetary_anchor_principle__overdetermined_composite_reading.pl', 'monetary_anchor_principle__overdetermined_composite_reading', 'MONETARY_ANCHOR_PRINCIPLE__OVERDETERMINED_COMPOSITE_READING', 268).
test_case('testsets/monetary_anchor_principle__punctuated_swap_reading.pl', 'monetary_anchor_principle__punctuated_swap_reading', 'MONETARY_ANCHOR_PRINCIPLE__PUNCTUATED_SWAP_READING', 269).
test_case('testsets/monetary_anchor_principle__triffin_inevitability_reading.pl', 'monetary_anchor_principle__triffin_inevitability_reading', 'MONETARY_ANCHOR_PRINCIPLE__TRIFFIN_INEVITABILITY_READING', 270).
test_case('testsets/montevideo_statehood_criteria__constitutive_reading.pl', 'montevideo_statehood_criteria__constitutive_reading', 'MONTEVIDEO_STATEHOOD_CRITERIA__CONSTITUTIVE_READING', 271).
test_case('testsets/montevideo_statehood_criteria__declaratory_reading.pl', 'montevideo_statehood_criteria__declaratory_reading', 'MONTEVIDEO_STATEHOOD_CRITERIA__DECLARATORY_READING', 272).
test_case('testsets/montevideo_statehood_criteria__hybrid_reading.pl', 'montevideo_statehood_criteria__hybrid_reading', 'MONTEVIDEO_STATEHOOD_CRITERIA__HYBRID_READING', 273).
test_case('testsets/nafta_jurisdictional_boundary__capital_supremacy_reading.pl', 'nafta_jurisdictional_boundary__capital_supremacy_reading', 'NAFTA_JURISDICTIONAL_BOUNDARY__CAPITAL_SUPREMACY_READING', 274).
test_case('testsets/nafta_jurisdictional_boundary__embedded_liberalism_reading.pl', 'nafta_jurisdictional_boundary__embedded_liberalism_reading', 'NAFTA_JURISDICTIONAL_BOUNDARY__EMBEDDED_LIBERALISM_READING', 275).
test_case('testsets/nafta_jurisdictional_boundary__sovereignty_primacy_reading.pl', 'nafta_jurisdictional_boundary__sovereignty_primacy_reading', 'NAFTA_JURISDICTIONAL_BOUNDARY__SOVEREIGNTY_PRIMACY_READING', 276).
test_case('testsets/naskh_principle__classical_abrogation.pl', 'naskh_principle__classical_abrogation', 'NASKH_PRINCIPLE__CLASSICAL_ABROGATION', 277).
test_case('testsets/naskh_principle__contextual_harmonization.pl', 'naskh_principle__contextual_harmonization', 'NASKH_PRINCIPLE__CONTEXTUAL_HARMONIZATION', 278).
test_case('testsets/naskh_principle__progressive_restriction.pl', 'naskh_principle__progressive_restriction', 'NASKH_PRINCIPLE__PROGRESSIVE_RESTRICTION', 279).
test_case('testsets/nicene_christological_kernel__homoiousios_reading.pl', 'nicene_christological_kernel__homoiousios_reading', 'NICENE_CHRISTOLOGICAL_KERNEL__HOMOIOUSIOS_READING', 280).
test_case('testsets/nicene_christological_kernel__homoousios_reading.pl', 'nicene_christological_kernel__homoousios_reading', 'NICENE_CHRISTOLOGICAL_KERNEL__HOMOOUSIOS_READING', 281).
test_case('testsets/notability_guidelines__deletionist_reading.pl', 'notability_guidelines__deletionist_reading', 'NOTABILITY_GUIDELINES__DELETIONIST_READING', 282).
test_case('testsets/notability_guidelines__inclusionist_reading.pl', 'notability_guidelines__inclusionist_reading', 'NOTABILITY_GUIDELINES__INCLUSIONIST_READING', 283).
test_case('testsets/npt_treaty_1970__oligopoly_enforcement_reading.pl', 'npt_treaty_1970__oligopoly_enforcement_reading', 'NPT_TREATY_1970__OLIGOPOLY_ENFORCEMENT_READING', 284).
test_case('testsets/npt_treaty_1970__reciprocal_disarmament_reading.pl', 'npt_treaty_1970__reciprocal_disarmament_reading', 'NPT_TREATY_1970__RECIPROCAL_DISARMAMENT_READING', 285).
test_case('testsets/npt_treaty_1970__withdrawal_sovereignty_reading.pl', 'npt_treaty_1970__withdrawal_sovereignty_reading', 'NPT_TREATY_1970__WITHDRAWAL_SOVEREIGNTY_READING', 286).
test_case('testsets/nsl_legal_text__democratic_enclosure_reading.pl', 'nsl_legal_text__democratic_enclosure_reading', 'NSL_LEGAL_TEXT__DEMOCRATIC_ENCLOSURE_READING', 287).
test_case('testsets/nsl_legal_text__jurisdictional_capture_reading.pl', 'nsl_legal_text__jurisdictional_capture_reading', 'NSL_LEGAL_TEXT__JURISDICTIONAL_CAPTURE_READING', 288).
test_case('testsets/nsl_legal_text__sovereignty_restoration_reading.pl', 'nsl_legal_text__sovereignty_restoration_reading', 'NSL_LEGAL_TEXT__SOVEREIGNTY_RESTORATION_READING', 289).
test_case('testsets/nuclear_impossibility_kernel__credibility_paradox_reading.pl', 'nuclear_impossibility_kernel__credibility_paradox_reading', 'NUCLEAR_IMPOSSIBILITY_KERNEL__CREDIBILITY_PARADOX_READING', 290).
test_case('testsets/nuclear_impossibility_kernel__rational_dropout_reading.pl', 'nuclear_impossibility_kernel__rational_dropout_reading', 'NUCLEAR_IMPOSSIBILITY_KERNEL__RATIONAL_DROPOUT_READING', 291).
test_case('testsets/nuclear_impossibility_kernel__structural_contraction_reading.pl', 'nuclear_impossibility_kernel__structural_contraction_reading', 'NUCLEAR_IMPOSSIBILITY_KERNEL__STRUCTURAL_CONTRACTION_READING', 292).
test_case('testsets/organization_floor_c0.pl', 'organization_floor_c0', 'ORGANIZATION_FLOOR_C0', 293).
test_case('testsets/ost_article_ii_non_appropriation__commons_conservation.pl', 'ost_article_ii_non_appropriation__commons_conservation', 'OST_ARTICLE_II_NON_APPROPRIATION__COMMONS_CONSERVATION', 294).
test_case('testsets/ost_article_ii_non_appropriation__extraction_permissive.pl', 'ost_article_ii_non_appropriation__extraction_permissive', 'OST_ARTICLE_II_NON_APPROPRIATION__EXTRACTION_PERMISSIVE', 295).
test_case('testsets/ost_article_ii_non_appropriation__international_regime.pl', 'ost_article_ii_non_appropriation__international_regime', 'OST_ARTICLE_II_NON_APPROPRIATION__INTERNATIONAL_REGIME', 296).
test_case('testsets/paris_article_4_ndc__equity_reading.pl', 'paris_article_4_ndc__equity_reading', 'PARIS_ARTICLE_4_NDC__EQUITY_READING', 297).
test_case('testsets/paris_article_4_ndc__sovereigntist_reading.pl', 'paris_article_4_ndc__sovereigntist_reading', 'PARIS_ARTICLE_4_NDC__SOVEREIGNTIST_READING', 298).
test_case('testsets/paris_article_4_ndc__supranational_reading.pl', 'paris_article_4_ndc__supranational_reading', 'PARIS_ARTICLE_4_NDC__SUPRANATIONAL_READING', 299).
test_case('testsets/personhood_boundary__birth_threshold_reading.pl', 'personhood_boundary__birth_threshold_reading', 'PERSONHOOD_BOUNDARY__BIRTH_THRESHOLD_READING', 300).
test_case('testsets/personhood_boundary__fitness_contingent_reading.pl', 'personhood_boundary__fitness_contingent_reading', 'PERSONHOOD_BOUNDARY__FITNESS_CONTINGENT_READING', 301).
test_case('testsets/personhood_boundary__potential_based_reading.pl', 'personhood_boundary__potential_based_reading', 'PERSONHOOD_BOUNDARY__POTENTIAL_BASED_READING', 302).
test_case('testsets/preparedness_commitment__competence_reading.pl', 'preparedness_commitment__competence_reading', 'PREPAREDNESS_COMMITMENT__COMPETENCE_READING', 303).
test_case('testsets/preparedness_commitment__husk_reading.pl', 'preparedness_commitment__husk_reading', 'PREPAREDNESS_COMMITMENT__HUSK_READING', 304).
test_case('testsets/preparedness_commitment__hybrid_reading.pl', 'preparedness_commitment__hybrid_reading', 'PREPAREDNESS_COMMITMENT__HYBRID_READING', 305).
test_case('testsets/preparedness_transmission__competence_reading.pl', 'preparedness_transmission__competence_reading', 'PREPAREDNESS_TRANSMISSION__COMPETENCE_READING', 306).
test_case('testsets/preparedness_transmission__husk_reading.pl', 'preparedness_transmission__husk_reading', 'PREPAREDNESS_TRANSMISSION__HUSK_READING', 307).
test_case('testsets/preparedness_transmission__hybrid_reading.pl', 'preparedness_transmission__hybrid_reading', 'PREPAREDNESS_TRANSMISSION__HYBRID_READING', 308).
test_case('testsets/press_reformation_causality__co_constitution.pl', 'press_reformation_causality__co_constitution', 'PRESS_REFORMATION_CAUSALITY__CO_CONSTITUTION', 309).
test_case('testsets/press_reformation_causality__strategic_deployment.pl', 'press_reformation_causality__strategic_deployment', 'PRESS_REFORMATION_CAUSALITY__STRATEGIC_DEPLOYMENT', 310).
test_case('testsets/press_reformation_causality__technological_determinism.pl', 'press_reformation_causality__technological_determinism', 'PRESS_REFORMATION_CAUSALITY__TECHNOLOGICAL_DETERMINISM', 311).
test_case('testsets/press_reformation_causation__strategic_deployment.pl', 'press_reformation_causation__strategic_deployment', 'PRESS_REFORMATION_CAUSATION__STRATEGIC_DEPLOYMENT', 312).
test_case('testsets/press_reformation_causation__technological_determinism.pl', 'press_reformation_causation__technological_determinism', 'PRESS_REFORMATION_CAUSATION__TECHNOLOGICAL_DETERMINISM', 313).
test_case('testsets/provincial_sovereignty_boundary__compact_federalism.pl', 'provincial_sovereignty_boundary__compact_federalism', 'PROVINCIAL_SOVEREIGNTY_BOUNDARY__COMPACT_FEDERALISM', 314).
test_case('testsets/provincial_sovereignty_boundary__constitutional_subordination.pl', 'provincial_sovereignty_boundary__constitutional_subordination', 'PROVINCIAL_SOVEREIGNTY_BOUNDARY__CONSTITUTIONAL_SUBORDINATION', 315).
test_case('testsets/provincial_sovereignty_boundary__resource_sovereignty_primacy.pl', 'provincial_sovereignty_boundary__resource_sovereignty_primacy', 'PROVINCIAL_SOVEREIGNTY_BOUNDARY__RESOURCE_SOVEREIGNTY_PRIMACY', 316).
test_case('testsets/public_health_mandate_authority__bodily_autonomy_primary.pl', 'public_health_mandate_authority__bodily_autonomy_primary', 'PUBLIC_HEALTH_MANDATE_AUTHORITY__BODILY_AUTONOMY_PRIMARY', 317).
test_case('testsets/public_health_mandate_authority__proportionality_reading.pl', 'public_health_mandate_authority__proportionality_reading', 'PUBLIC_HEALTH_MANDATE_AUTHORITY__PROPORTIONALITY_READING', 318).
test_case('testsets/public_health_mandate_authority__public_health_primary.pl', 'public_health_mandate_authority__public_health_primary', 'PUBLIC_HEALTH_MANDATE_AUTHORITY__PUBLIC_HEALTH_PRIMARY', 319).
test_case('testsets/quran_ontological_status__created_reading.pl', 'quran_ontological_status__created_reading', 'QURAN_ONTOLOGICAL_STATUS__CREATED_READING', 320).
test_case('testsets/quran_ontological_status__state_enforced_creation_reading.pl', 'quran_ontological_status__state_enforced_creation_reading', 'QURAN_ONTOLOGICAL_STATUS__STATE_ENFORCED_CREATION_READING', 321).
test_case('testsets/quran_ontological_status__uncreated_reading.pl', 'quran_ontological_status__uncreated_reading', 'QURAN_ONTOLOGICAL_STATUS__UNCREATED_READING', 322).
test_case('testsets/qwerty_persistence__incumbent_preservation_reading.pl', 'qwerty_persistence__incumbent_preservation_reading', 'QWERTY_PERSISTENCE__INCUMBENT_PRESERVATION_READING', 323).
test_case('testsets/qwerty_persistence__lapsed_alternatives_reading.pl', 'qwerty_persistence__lapsed_alternatives_reading', 'QWERTY_PERSISTENCE__LAPSED_ALTERNATIVES_READING', 324).
test_case('testsets/qwerty_persistence_mechanism__beneficiary_extraction_reading.pl', 'qwerty_persistence_mechanism__beneficiary_extraction_reading', 'QWERTY_PERSISTENCE_MECHANISM__BENEFICIARY_EXTRACTION_READING', 325).
test_case('testsets/qwerty_persistence_mechanism__lock_in_reading.pl', 'qwerty_persistence_mechanism__lock_in_reading', 'QWERTY_PERSISTENCE_MECHANISM__LOCK_IN_READING', 326).
test_case('testsets/qwerty_persistence_mechanism__naturalization_reading.pl', 'qwerty_persistence_mechanism__naturalization_reading', 'QWERTY_PERSISTENCE_MECHANISM__NATURALIZATION_READING', 327).
test_case('testsets/reading_acquisition_legitimacy__balanced_literacy_integration.pl', 'reading_acquisition_legitimacy__balanced_literacy_integration', 'READING_ACQUISITION_LEGITIMACY__BALANCED_LITERACY_INTEGRATION', 328).
test_case('testsets/reading_acquisition_legitimacy__phonics_decoding_primacy.pl', 'reading_acquisition_legitimacy__phonics_decoding_primacy', 'READING_ACQUISITION_LEGITIMACY__PHONICS_DECODING_PRIMACY', 329).
test_case('testsets/reading_acquisition_legitimacy__structured_literacy_remediation.pl', 'reading_acquisition_legitimacy__structured_literacy_remediation', 'READING_ACQUISITION_LEGITIMACY__STRUCTURED_LITERACY_REMEDIATION', 330).
test_case('testsets/reading_acquisition_mechanism__balanced_literacy_reading.pl', 'reading_acquisition_mechanism__balanced_literacy_reading', 'READING_ACQUISITION_MECHANISM__BALANCED_LITERACY_READING', 331).
test_case('testsets/reading_acquisition_mechanism__phonics_reading.pl', 'reading_acquisition_mechanism__phonics_reading', 'READING_ACQUISITION_MECHANISM__PHONICS_READING', 332).
test_case('testsets/reading_acquisition_mechanism__whole_language_reading.pl', 'reading_acquisition_mechanism__whole_language_reading', 'READING_ACQUISITION_MECHANISM__WHOLE_LANGUAGE_READING', 333).
test_case('testsets/reformation_composite__political_realignment_reading.pl', 'reformation_composite__political_realignment_reading', 'REFORMATION_COMPOSITE__POLITICAL_REALIGNMENT_READING', 334).
test_case('testsets/reformation_composite__technological_mediation_reading.pl', 'reformation_composite__technological_mediation_reading', 'REFORMATION_COMPOSITE__TECHNOLOGICAL_MEDIATION_READING', 335).
test_case('testsets/reformation_composite__theological_fragmentation_reading.pl', 'reformation_composite__theological_fragmentation_reading', 'REFORMATION_COMPOSITE__THEOLOGICAL_FRAGMENTATION_READING', 336).
test_case('testsets/refugee_convention_text__expansive_humanitarian_reading.pl', 'refugee_convention_text__expansive_humanitarian_reading', 'REFUGEE_CONVENTION_TEXT__EXPANSIVE_HUMANITARIAN_READING', 337).
test_case('testsets/refugee_convention_text__procedural_integrity_reading.pl', 'refugee_convention_text__procedural_integrity_reading', 'REFUGEE_CONVENTION_TEXT__PROCEDURAL_INTEGRITY_READING', 338).
test_case('testsets/refugee_convention_text__restrictive_sovereignty_reading.pl', 'refugee_convention_text__restrictive_sovereignty_reading', 'REFUGEE_CONVENTION_TEXT__RESTRICTIVE_SOVEREIGNTY_READING', 339).
test_case('testsets/remonstrance_authority__crown_reading.pl', 'remonstrance_authority__crown_reading', 'REMONSTRANCE_AUTHORITY__CROWN_READING', 340).
test_case('testsets/remonstrance_authority__magistrate_reading.pl', 'remonstrance_authority__magistrate_reading', 'REMONSTRANCE_AUTHORITY__MAGISTRATE_READING', 341).
test_case('testsets/sacrifice_obligation_kernel__messianic_suspension_reading.pl', 'sacrifice_obligation_kernel__messianic_suspension_reading', 'SACRIFICE_OBLIGATION_KERNEL__MESSIANIC_SUSPENSION_READING', 342).
test_case('testsets/sacrifice_obligation_kernel__performance_only_reading.pl', 'sacrifice_obligation_kernel__performance_only_reading', 'SACRIFICE_OBLIGATION_KERNEL__PERFORMANCE_ONLY_READING', 343).
test_case('testsets/sacrifice_obligation_kernel__study_as_exercise_reading.pl', 'sacrifice_obligation_kernel__study_as_exercise_reading', 'SACRIFICE_OBLIGATION_KERNEL__STUDY_AS_EXERCISE_READING', 344).
test_case('testsets/sacrifice_obligation_kernel__symbolic_archive_reading.pl', 'sacrifice_obligation_kernel__symbolic_archive_reading', 'SACRIFICE_OBLIGATION_KERNEL__SYMBOLIC_ARCHIVE_READING', 345).
test_case('testsets/scale_ceiling_c0.pl', 'scale_ceiling_c0', 'SCALE_CEILING_C0', 346).
test_case('testsets/secession_legitimacy_boundary__constitutional_impossibility_reading.pl', 'secession_legitimacy_boundary__constitutional_impossibility_reading', 'SECESSION_LEGITIMACY_BOUNDARY__CONSTITUTIONAL_IMPOSSIBILITY_READING', 347).
test_case('testsets/secession_legitimacy_boundary__grievance_threshold_reading.pl', 'secession_legitimacy_boundary__grievance_threshold_reading', 'SECESSION_LEGITIMACY_BOUNDARY__GRIEVANCE_THRESHOLD_READING', 348).
test_case('testsets/secession_legitimacy_boundary__popular_sovereignty_reading.pl', 'secession_legitimacy_boundary__popular_sovereignty_reading', 'SECESSION_LEGITIMACY_BOUNDARY__POPULAR_SOVEREIGNTY_READING', 349).
test_case('testsets/secession_legitimacy_boundary__treaty_primacy_reading.pl', 'secession_legitimacy_boundary__treaty_primacy_reading', 'SECESSION_LEGITIMACY_BOUNDARY__TREATY_PRIMACY_READING', 350).
test_case('testsets/second_amendment_boundary__individual_right_reading.pl', 'second_amendment_boundary__individual_right_reading', 'SECOND_AMENDMENT_BOUNDARY__INDIVIDUAL_RIGHT_READING', 351).
test_case('testsets/second_amendment_boundary__insurrectionist_reading.pl', 'second_amendment_boundary__insurrectionist_reading', 'SECOND_AMENDMENT_BOUNDARY__INSURRECTIONIST_READING', 352).
test_case('testsets/second_amendment_boundary__militia_conditioned_reading.pl', 'second_amendment_boundary__militia_conditioned_reading', 'SECOND_AMENDMENT_BOUNDARY__MILITIA_CONDITIONED_READING', 353).
test_case('testsets/second_amendment_text__collective_security_reading.pl', 'second_amendment_text__collective_security_reading', 'SECOND_AMENDMENT_TEXT__COLLECTIVE_SECURITY_READING', 354).
test_case('testsets/second_amendment_text__individual_right_reading.pl', 'second_amendment_text__individual_right_reading', 'SECOND_AMENDMENT_TEXT__INDIVIDUAL_RIGHT_READING', 355).
test_case('testsets/second_amendment_text__originalist_civic_virtue_reading.pl', 'second_amendment_text__originalist_civic_virtue_reading', 'SECOND_AMENDMENT_TEXT__ORIGINALIST_CIVIC_VIRTUE_READING', 356).
test_case('testsets/separation_of_powers_text__formalist_reading.pl', 'separation_of_powers_text__formalist_reading', 'SEPARATION_OF_POWERS_TEXT__FORMALIST_READING', 357).
test_case('testsets/separation_of_powers_text__functionalist_reading.pl', 'separation_of_powers_text__functionalist_reading', 'SEPARATION_OF_POWERS_TEXT__FUNCTIONALIST_READING', 358).
test_case('testsets/separation_of_powers_text__unitary_executive_reading.pl', 'separation_of_powers_text__unitary_executive_reading', 'SEPARATION_OF_POWERS_TEXT__UNITARY_EXECUTIVE_READING', 359).
test_case('testsets/shinbutsu_coexistence_commitment__domain_partition_reading.pl', 'shinbutsu_coexistence_commitment__domain_partition_reading', 'SHINBUTSU_COEXISTENCE_COMMITMENT__DOMAIN_PARTITION_READING', 360).
test_case('testsets/shinbutsu_coexistence_commitment__incoherent_bundle_reading.pl', 'shinbutsu_coexistence_commitment__incoherent_bundle_reading', 'SHINBUTSU_COEXISTENCE_COMMITMENT__INCOHERENT_BUNDLE_READING', 361).
test_case('testsets/shinbutsu_coexistence_commitment__syncretic_fusion_reading.pl', 'shinbutsu_coexistence_commitment__syncretic_fusion_reading', 'SHINBUTSU_COEXISTENCE_COMMITMENT__SYNCRETIC_FUSION_READING', 362).
test_case('testsets/shinbutsu_ontological_commitment__incoherence_reading.pl', 'shinbutsu_ontological_commitment__incoherence_reading', 'SHINBUTSU_ONTOLOGICAL_COMMITMENT__INCOHERENCE_READING', 363).
test_case('testsets/shinbutsu_ontological_commitment__partition_reading.pl', 'shinbutsu_ontological_commitment__partition_reading', 'SHINBUTSU_ONTOLOGICAL_COMMITMENT__PARTITION_READING', 364).
test_case('testsets/shinbutsu_ontological_commitment__syncretic_reading.pl', 'shinbutsu_ontological_commitment__syncretic_reading', 'SHINBUTSU_ONTOLOGICAL_COMMITMENT__SYNCRETIC_READING', 365).
test_case('testsets/shinbutsu_ontological_substrate__domain_partition_reading.pl', 'shinbutsu_ontological_substrate__domain_partition_reading', 'SHINBUTSU_ONTOLOGICAL_SUBSTRATE__DOMAIN_PARTITION_READING', 366).
test_case('testsets/shinbutsu_ontological_substrate__incoherent_bundle_reading.pl', 'shinbutsu_ontological_substrate__incoherent_bundle_reading', 'SHINBUTSU_ONTOLOGICAL_SUBSTRATE__INCOHERENT_BUNDLE_READING', 367).
test_case('testsets/shinbutsu_ontological_substrate__syncretic_fusion_reading.pl', 'shinbutsu_ontological_substrate__syncretic_fusion_reading', 'SHINBUTSU_ONTOLOGICAL_SUBSTRATE__SYNCRETIC_FUSION_READING', 368).
test_case('testsets/simultaneous_veneration__domain_partition_reading.pl', 'simultaneous_veneration__domain_partition_reading', 'SIMULTANEOUS_VENERATION__DOMAIN_PARTITION_READING', 369).
test_case('testsets/simultaneous_veneration__ontological_fusion_reading.pl', 'simultaneous_veneration__ontological_fusion_reading', 'SIMULTANEOUS_VENERATION__ONTOLOGICAL_FUSION_READING', 370).
test_case('testsets/simultaneous_veneration__pragmatic_incoherence_reading.pl', 'simultaneous_veneration__pragmatic_incoherence_reading', 'SIMULTANEOUS_VENERATION__PRAGMATIC_INCOHERENCE_READING', 371).
test_case('testsets/software_source_status__freedom_imperative_reading.pl', 'software_source_status__freedom_imperative_reading', 'SOFTWARE_SOURCE_STATUS__FREEDOM_IMPERATIVE_READING', 372).
test_case('testsets/software_source_status__pragmatic_development_reading.pl', 'software_source_status__pragmatic_development_reading', 'SOFTWARE_SOURCE_STATUS__PRAGMATIC_DEVELOPMENT_READING', 373).
test_case('testsets/software_source_status__property_rights_reading.pl', 'software_source_status__property_rights_reading', 'SOFTWARE_SOURCE_STATUS__PROPERTY_RIGHTS_READING', 374).
test_case('testsets/software_source_status__utilitarian_hybrid_reading.pl', 'software_source_status__utilitarian_hybrid_reading', 'SOFTWARE_SOURCE_STATUS__UTILITARIAN_HYBRID_READING', 375).
test_case('testsets/sovereign_legitimacy__constitutional_hybrid_reading.pl', 'sovereign_legitimacy__constitutional_hybrid_reading', 'SOVEREIGN_LEGITIMACY__CONSTITUTIONAL_HYBRID_READING', 376).
test_case('testsets/sovereign_legitimacy__monarchical_reading.pl', 'sovereign_legitimacy__monarchical_reading', 'SOVEREIGN_LEGITIMACY__MONARCHICAL_READING', 377).
test_case('testsets/sovereign_legitimacy__republican_reading.pl', 'sovereign_legitimacy__republican_reading', 'SOVEREIGN_LEGITIMACY__REPUBLICAN_READING', 378).
test_case('testsets/speech_protection_kernel__absolutist_reading.pl', 'speech_protection_kernel__absolutist_reading', 'SPEECH_PROTECTION_KERNEL__ABSOLUTIST_READING', 379).
test_case('testsets/speech_protection_kernel__democratic_participation_reading.pl', 'speech_protection_kernel__democratic_participation_reading', 'SPEECH_PROTECTION_KERNEL__DEMOCRATIC_PARTICIPATION_READING', 380).
test_case('testsets/speech_protection_kernel__dignity_reading.pl', 'speech_protection_kernel__dignity_reading', 'SPEECH_PROTECTION_KERNEL__DIGNITY_READING', 381).
test_case('testsets/speech_protection_kernel__harm_threshold_reading.pl', 'speech_protection_kernel__harm_threshold_reading', 'SPEECH_PROTECTION_KERNEL__HARM_THRESHOLD_READING', 382).
test_case('testsets/speech_protection_kernel__marketplace_reading.pl', 'speech_protection_kernel__marketplace_reading', 'SPEECH_PROTECTION_KERNEL__MARKETPLACE_READING', 383).
test_case('testsets/state_execution_authority__abolition_reading.pl', 'state_execution_authority__abolition_reading', 'STATE_EXECUTION_AUTHORITY__ABOLITION_READING', 384).
test_case('testsets/state_execution_authority__deterrence_reading.pl', 'state_execution_authority__deterrence_reading', 'STATE_EXECUTION_AUTHORITY__DETERRENCE_READING', 385).
test_case('testsets/state_execution_authority__retributive_reading.pl', 'state_execution_authority__retributive_reading', 'STATE_EXECUTION_AUTHORITY__RETRIBUTIVE_READING', 386).
test_case('testsets/state_killing_authority__categorical_abolition.pl', 'state_killing_authority__categorical_abolition', 'STATE_KILLING_AUTHORITY__CATEGORICAL_ABOLITION', 387).
test_case('testsets/state_killing_authority__deterrence_instrument.pl', 'state_killing_authority__deterrence_instrument', 'STATE_KILLING_AUTHORITY__DETERRENCE_INSTRUMENT', 388).
test_case('testsets/state_killing_authority__retributive_desert.pl', 'state_killing_authority__retributive_desert', 'STATE_KILLING_AUTHORITY__RETRIBUTIVE_DESERT', 389).
test_case('testsets/state_killing_legitimacy__deterrence_reading.pl', 'state_killing_legitimacy__deterrence_reading', 'STATE_KILLING_LEGITIMACY__DETERRENCE_READING', 390).
test_case('testsets/state_killing_legitimacy__retributive_reading.pl', 'state_killing_legitimacy__retributive_reading', 'STATE_KILLING_LEGITIMACY__RETRIBUTIVE_READING', 391).
test_case('testsets/substance_control_authority__harm_reduction_reading.pl', 'substance_control_authority__harm_reduction_reading', 'SUBSTANCE_CONTROL_AUTHORITY__HARM_REDUCTION_READING', 392).
test_case('testsets/substance_control_authority__legalization_reading.pl', 'substance_control_authority__legalization_reading', 'SUBSTANCE_CONTROL_AUTHORITY__LEGALIZATION_READING', 393).
test_case('testsets/substance_control_authority__prohibition_reading.pl', 'substance_control_authority__prohibition_reading', 'SUBSTANCE_CONTROL_AUTHORITY__PROHIBITION_READING', 394).
test_case('testsets/substance_control_legitimacy__harm_reduction_reading.pl', 'substance_control_legitimacy__harm_reduction_reading', 'SUBSTANCE_CONTROL_LEGITIMACY__HARM_REDUCTION_READING', 395).
test_case('testsets/substance_control_legitimacy__legalization_reading.pl', 'substance_control_legitimacy__legalization_reading', 'SUBSTANCE_CONTROL_LEGITIMACY__LEGALIZATION_READING', 396).
test_case('testsets/substance_control_legitimacy__prohibition_reading.pl', 'substance_control_legitimacy__prohibition_reading', 'SUBSTANCE_CONTROL_LEGITIMACY__PROHIBITION_READING', 397).
test_case('testsets/tcp_ip_interpretation__neutrality_reading.pl', 'tcp_ip_interpretation__neutrality_reading', 'TCP_IP_INTERPRETATION__NEUTRALITY_READING', 398).
test_case('testsets/tcp_ip_interpretation__prioritization_reading.pl', 'tcp_ip_interpretation__prioritization_reading', 'TCP_IP_INTERPRETATION__PRIORITIZATION_READING', 399).
test_case('testsets/tcp_ip_interpretation__zero_rating_reading.pl', 'tcp_ip_interpretation__zero_rating_reading', 'TCP_IP_INTERPRETATION__ZERO_RATING_READING', 400).
test_case('testsets/technology_reformation_causality__beneficiary_agency_reading.pl', 'technology_reformation_causality__beneficiary_agency_reading', 'TECHNOLOGY_REFORMATION_CAUSALITY__BENEFICIARY_AGENCY_READING', 401).
test_case('testsets/technology_reformation_causality__co_constitution_reading.pl', 'technology_reformation_causality__co_constitution_reading', 'TECHNOLOGY_REFORMATION_CAUSALITY__CO_CONSTITUTION_READING', 402).
test_case('testsets/technology_reformation_causality__technological_determinism_reading.pl', 'technology_reformation_causality__technological_determinism_reading', 'TECHNOLOGY_REFORMATION_CAUSALITY__TECHNOLOGICAL_DETERMINISM_READING', 403).
test_case('testsets/temple_sacrifice_commitment__hybrid_preparatory.pl', 'temple_sacrifice_commitment__hybrid_preparatory', 'TEMPLE_SACRIFICE_COMMITMENT__HYBRID_PREPARATORY', 404).
test_case('testsets/temple_sacrifice_commitment__performance_only.pl', 'temple_sacrifice_commitment__performance_only', 'TEMPLE_SACRIFICE_COMMITMENT__PERFORMANCE_ONLY', 405).
test_case('testsets/temple_sacrifice_commitment__study_as_exercise.pl', 'temple_sacrifice_commitment__study_as_exercise', 'TEMPLE_SACRIFICE_COMMITMENT__STUDY_AS_EXERCISE', 406).
test_case('testsets/temple_sacrifice_commitment__symbolic_transformation.pl', 'temple_sacrifice_commitment__symbolic_transformation', 'TEMPLE_SACRIFICE_COMMITMENT__SYMBOLIC_TRANSFORMATION', 407).
test_case('testsets/tenure_contract__academic_freedom_reading.pl', 'tenure_contract__academic_freedom_reading', 'TENURE_CONTRACT__ACADEMIC_FREEDOM_READING', 408).
test_case('testsets/tenure_contract__demographic_reproduction_reading.pl', 'tenure_contract__demographic_reproduction_reading', 'TENURE_CONTRACT__DEMOGRAPHIC_REPRODUCTION_READING', 409).
test_case('testsets/tenure_contract__institutional_extraction_reading.pl', 'tenure_contract__institutional_extraction_reading', 'TENURE_CONTRACT__INSTITUTIONAL_EXTRACTION_READING', 410).
test_case('testsets/territorial_legitimacy__indigenous_continuity_reading.pl', 'territorial_legitimacy__indigenous_continuity_reading', 'TERRITORIAL_LEGITIMACY__INDIGENOUS_CONTINUITY_READING', 411).
test_case('testsets/territorial_legitimacy__partition_reading.pl', 'territorial_legitimacy__partition_reading', 'TERRITORIAL_LEGITIMACY__PARTITION_READING', 412).
test_case('testsets/territorial_legitimacy__security_necessity_reading.pl', 'territorial_legitimacy__security_necessity_reading', 'TERRITORIAL_LEGITIMACY__SECURITY_NECESSITY_READING', 413).
test_case('testsets/territorial_sovereignty_legitimacy__covenant_continuity_reading.pl', 'territorial_sovereignty_legitimacy__covenant_continuity_reading', 'TERRITORIAL_SOVEREIGNTY_LEGITIMACY__COVENANT_CONTINUITY_READING', 414).
test_case('testsets/territorial_sovereignty_legitimacy__existential_matrix_reading.pl', 'territorial_sovereignty_legitimacy__existential_matrix_reading', 'TERRITORIAL_SOVEREIGNTY_LEGITIMACY__EXISTENTIAL_MATRIX_READING', 415).
test_case('testsets/territorial_sovereignty_legitimacy__self_determination_reading.pl', 'territorial_sovereignty_legitimacy__self_determination_reading', 'TERRITORIAL_SOVEREIGNTY_LEGITIMACY__SELF_DETERMINATION_READING', 416).
test_case('testsets/total_war_possibility_space__deterrence_equilibrium_reading.pl', 'total_war_possibility_space__deterrence_equilibrium_reading', 'TOTAL_WAR_POSSIBILITY_SPACE__DETERRENCE_EQUILIBRIUM_READING', 417).
test_case('testsets/total_war_possibility_space__nuclear_taboo_reading.pl', 'total_war_possibility_space__nuclear_taboo_reading', 'TOTAL_WAR_POSSIBILITY_SPACE__NUCLEAR_TABOO_READING', 418).
test_case('testsets/total_war_possibility_space__space_contraction_reading.pl', 'total_war_possibility_space__space_contraction_reading', 'TOTAL_WAR_POSSIBILITY_SPACE__SPACE_CONTRACTION_READING', 419).
test_case('testsets/transition_causality__contingent_choice_reading.pl', 'transition_causality__contingent_choice_reading', 'TRANSITION_CAUSALITY__CONTINGENT_CHOICE_READING', 420).
test_case('testsets/transition_causality__hybrid_trigger_reading.pl', 'transition_causality__hybrid_trigger_reading', 'TRANSITION_CAUSALITY__HYBRID_TRIGGER_READING', 421).
test_case('testsets/transition_causality__overdetermined_collapse_reading.pl', 'transition_causality__overdetermined_collapse_reading', 'TRANSITION_CAUSALITY__OVERDETERMINED_COLLAPSE_READING', 422).
test_case('testsets/tsunami_stone_commitment__behavioral_competence_reading.pl', 'tsunami_stone_commitment__behavioral_competence_reading', 'TSUNAMI_STONE_COMMITMENT__BEHAVIORAL_COMPETENCE_READING', 423).
test_case('testsets/tsunami_stone_commitment__catastrophe_validation_axis.pl', 'tsunami_stone_commitment__catastrophe_validation_axis', 'TSUNAMI_STONE_COMMITMENT__CATASTROPHE_VALIDATION_AXIS', 424).
test_case('testsets/tsunami_stone_commitment__commemorative_husk_reading.pl', 'tsunami_stone_commitment__commemorative_husk_reading', 'TSUNAMI_STONE_COMMITMENT__COMMEMORATIVE_HUSK_READING', 425).
test_case('testsets/turkish_graphemic_substrate__gradual_transition_reading.pl', 'turkish_graphemic_substrate__gradual_transition_reading', 'TURKISH_GRAPHEMIC_SUBSTRATE__GRADUAL_TRANSITION_READING', 426).
test_case('testsets/turkish_graphemic_substrate__ottoman_continuity_reading.pl', 'turkish_graphemic_substrate__ottoman_continuity_reading', 'TURKISH_GRAPHEMIC_SUBSTRATE__OTTOMAN_CONTINUITY_READING', 427).
test_case('testsets/turkish_graphemic_substrate__secular_nationalist_reading.pl', 'turkish_graphemic_substrate__secular_nationalist_reading', 'TURKISH_GRAPHEMIC_SUBSTRATE__SECULAR_NATIONALIST_READING', 428).
test_case('testsets/udhr_authority__aspirational_sovereignty_reading.pl', 'udhr_authority__aspirational_sovereignty_reading', 'UDHR_AUTHORITY__ASPIRATIONAL_SOVEREIGNTY_READING', 429).
test_case('testsets/udhr_authority__binding_universalism_reading.pl', 'udhr_authority__binding_universalism_reading', 'UDHR_AUTHORITY__BINDING_UNIVERSALISM_READING', 430).
test_case('testsets/udhr_authority__customary_emergence_reading.pl', 'udhr_authority__customary_emergence_reading', 'UDHR_AUTHORITY__CUSTOMARY_EMERGENCE_READING', 431).
test_case('testsets/unclos_maritime_sovereignty__expansive_construction_reading.pl', 'unclos_maritime_sovereignty__expansive_construction_reading', 'UNCLOS_MARITIME_SOVEREIGNTY__EXPANSIVE_CONSTRUCTION_READING', 432).
test_case('testsets/unclos_maritime_sovereignty__hybrid_effective_control_reading.pl', 'unclos_maritime_sovereignty__hybrid_effective_control_reading', 'UNCLOS_MARITIME_SOVEREIGNTY__HYBRID_EFFECTIVE_CONTROL_READING', 433).
test_case('testsets/unclos_maritime_sovereignty__strict_geographic_reading.pl', 'unclos_maritime_sovereignty__strict_geographic_reading', 'UNCLOS_MARITIME_SOVEREIGNTY__STRICT_GEOGRAPHIC_READING', 434).
test_case('testsets/unclos_sovereignty_boundary__historical_rights_reading.pl', 'unclos_sovereignty_boundary__historical_rights_reading', 'UNCLOS_SOVEREIGNTY_BOUNDARY__HISTORICAL_RIGHTS_READING', 435).
test_case('testsets/unclos_sovereignty_boundary__non_ratifier_enforcement_reading.pl', 'unclos_sovereignty_boundary__non_ratifier_enforcement_reading', 'UNCLOS_SOVEREIGNTY_BOUNDARY__NON_RATIFIER_ENFORCEMENT_READING', 436).
test_case('testsets/unclos_sovereignty_boundary__strict_eez_reading.pl', 'unclos_sovereignty_boundary__strict_eez_reading', 'UNCLOS_SOVEREIGNTY_BOUNDARY__STRICT_EEZ_READING', 437).
test_case('testsets/us_constitution_1787__living_reading.pl', 'us_constitution_1787__living_reading', 'US_CONSTITUTION_1787__LIVING_READING', 438).
test_case('testsets/us_constitution_1787__originalist_reading.pl', 'us_constitution_1787__originalist_reading', 'US_CONSTITUTION_1787__ORIGINALIST_READING', 439).
test_case('testsets/us_constitution_1787__positivist_reading.pl', 'us_constitution_1787__positivist_reading', 'US_CONSTITUTION_1787__POSITIVIST_READING', 440).
test_case('testsets/us_constitution_interpretive__living_constitution_reading.pl', 'us_constitution_interpretive__living_constitution_reading', 'US_CONSTITUTION_INTERPRETIVE__LIVING_CONSTITUTION_READING', 441).
test_case('testsets/us_constitution_interpretive__originalist_reading.pl', 'us_constitution_interpretive__originalist_reading', 'US_CONSTITUTION_INTERPRETIVE__ORIGINALIST_READING', 442).
test_case('testsets/us_constitution_interpretive__popular_constitutionalism_reading.pl', 'us_constitution_interpretive__popular_constitutionalism_reading', 'US_CONSTITUTION_INTERPRETIVE__POPULAR_CONSTITUTIONALISM_READING', 443).
test_case('testsets/us_constitution_meaning__living_constitutionalist_reading.pl', 'us_constitution_meaning__living_constitutionalist_reading', 'US_CONSTITUTION_MEANING__LIVING_CONSTITUTIONALIST_READING', 444).
test_case('testsets/us_constitution_meaning__originalist_reading.pl', 'us_constitution_meaning__originalist_reading', 'US_CONSTITUTION_MEANING__ORIGINALIST_READING', 445).
test_case('testsets/us_constitution_meaning__positivist_reading.pl', 'us_constitution_meaning__positivist_reading', 'US_CONSTITUTION_MEANING__POSITIVIST_READING', 446).
test_case('testsets/us_constitution_text__living_constitutionalist_reading.pl', 'us_constitution_text__living_constitutionalist_reading', 'US_CONSTITUTION_TEXT__LIVING_CONSTITUTIONALIST_READING', 447).
test_case('testsets/us_constitution_text__originalist_reading.pl', 'us_constitution_text__originalist_reading', 'US_CONSTITUTION_TEXT__ORIGINALIST_READING', 448).
test_case('testsets/us_constitution_text__positivist_reading.pl', 'us_constitution_text__positivist_reading', 'US_CONSTITUTION_TEXT__POSITIVIST_READING', 449).
test_case('testsets/usul_al_fiqh_method__hanafi_reading.pl', 'usul_al_fiqh_method__hanafi_reading', 'USUL_AL_FIQH_METHOD__HANAFI_READING', 450).
test_case('testsets/usul_al_fiqh_method__hanbali_reading.pl', 'usul_al_fiqh_method__hanbali_reading', 'USUL_AL_FIQH_METHOD__HANBALI_READING', 451).
test_case('testsets/usul_al_fiqh_method__maliki_reading.pl', 'usul_al_fiqh_method__maliki_reading', 'USUL_AL_FIQH_METHOD__MALIKI_READING', 452).
test_case('testsets/usul_al_fiqh_method__shafii_reading.pl', 'usul_al_fiqh_method__shafii_reading', 'USUL_AL_FIQH_METHOD__SHAFII_READING', 453).
test_case('testsets/vaccine_mandate_legitimacy__bodily_autonomy_primacy_reading.pl', 'vaccine_mandate_legitimacy__bodily_autonomy_primacy_reading', 'VACCINE_MANDATE_LEGITIMACY__BODILY_AUTONOMY_PRIMACY_READING', 454).
test_case('testsets/vaccine_mandate_legitimacy__public_health_primacy_reading.pl', 'vaccine_mandate_legitimacy__public_health_primacy_reading', 'VACCINE_MANDATE_LEGITIMACY__PUBLIC_HEALTH_PRIMACY_READING', 455).
test_case('testsets/vaccine_mandate_legitimacy__risk_stratification_reading.pl', 'vaccine_mandate_legitimacy__risk_stratification_reading', 'VACCINE_MANDATE_LEGITIMACY__RISK_STRATIFICATION_READING', 456).
test_case('testsets/valuation_legitimacy__dcf_fundamentalist.pl', 'valuation_legitimacy__dcf_fundamentalist', 'VALUATION_LEGITIMACY__DCF_FUNDAMENTALIST', 457).
test_case('testsets/valuation_legitimacy__governance_skeptic.pl', 'valuation_legitimacy__governance_skeptic', 'VALUATION_LEGITIMACY__GOVERNANCE_SKEPTIC', 458).
test_case('testsets/valuation_legitimacy__musk_cult_believer.pl', 'valuation_legitimacy__musk_cult_believer', 'VALUATION_LEGITIMACY__MUSK_CULT_BELIEVER', 459).
test_case('testsets/valuation_legitimacy__real_options_technologist.pl', 'valuation_legitimacy__real_options_technologist', 'VALUATION_LEGITIMACY__REAL_OPTIONS_TECHNOLOGIST', 460).
test_case('testsets/vatican_ii_authority__composite_overdetermination_reading.pl', 'vatican_ii_authority__composite_overdetermination_reading', 'VATICAN_II_AUTHORITY__COMPOSITE_OVERDETERMINATION_READING', 461).
test_case('testsets/vatican_ii_authority__continuity_reading.pl', 'vatican_ii_authority__continuity_reading', 'VATICAN_II_AUTHORITY__CONTINUITY_READING', 462).
test_case('testsets/vatican_ii_authority__rupture_reading.pl', 'vatican_ii_authority__rupture_reading', 'VATICAN_II_AUTHORITY__RUPTURE_READING', 463).
test_case('testsets/vedic_corpus_social_prescription__colonial_orientalist_reading.pl', 'vedic_corpus_social_prescription__colonial_orientalist_reading', 'VEDIC_CORPUS_SOCIAL_PRESCRIPTION__COLONIAL_ORIENTALIST_READING', 464).
test_case('testsets/vedic_corpus_social_prescription__orthodox_varna_reading.pl', 'vedic_corpus_social_prescription__orthodox_varna_reading', 'VEDIC_CORPUS_SOCIAL_PRESCRIPTION__ORTHODOX_VARNA_READING', 465).
test_case('testsets/vedic_corpus_social_prescription__reformist_spiritual_reading.pl', 'vedic_corpus_social_prescription__reformist_spiritual_reading', 'VEDIC_CORPUS_SOCIAL_PRESCRIPTION__REFORMIST_SPIRITUAL_READING', 466).
test_case('testsets/vedic_dharmic_corpus__bhakti_devotional_reading.pl', 'vedic_dharmic_corpus__bhakti_devotional_reading', 'VEDIC_DHARMIC_CORPUS__BHAKTI_DEVOTIONAL_READING', 467).
test_case('testsets/vedic_dharmic_corpus__hereditary_monopoly_reading.pl', 'vedic_dharmic_corpus__hereditary_monopoly_reading', 'VEDIC_DHARMIC_CORPUS__HEREDITARY_MONOPOLY_READING', 468).
test_case('testsets/vedic_dharmic_corpus__reformist_egalitarian_reading.pl', 'vedic_dharmic_corpus__reformist_egalitarian_reading', 'VEDIC_DHARMIC_CORPUS__REFORMIST_EGALITARIAN_READING', 469).
test_case('testsets/waitangi_sovereignty_allocation__crown_sovereignty_reading.pl', 'waitangi_sovereignty_allocation__crown_sovereignty_reading', 'WAITANGI_SOVEREIGNTY_ALLOCATION__CROWN_SOVEREIGNTY_READING', 470).
test_case('testsets/waitangi_sovereignty_allocation__partnership_reading.pl', 'waitangi_sovereignty_allocation__partnership_reading', 'WAITANGI_SOVEREIGNTY_ALLOCATION__PARTNERSHIP_READING', 471).
test_case('testsets/waitangi_sovereignty_allocation__rangatiratanga_reading.pl', 'waitangi_sovereignty_allocation__rangatiratanga_reading', 'WAITANGI_SOVEREIGNTY_ALLOCATION__RANGATIRATANGA_READING', 472).
test_case('testsets/westphalia_sovereignty__absolute_non_intervention.pl', 'westphalia_sovereignty__absolute_non_intervention', 'WESTPHALIA_SOVEREIGNTY__ABSOLUTE_NON_INTERVENTION', 473).
test_case('testsets/westphalia_sovereignty__conditional_responsibility.pl', 'westphalia_sovereignty__conditional_responsibility', 'WESTPHALIA_SOVEREIGNTY__CONDITIONAL_RESPONSIBILITY', 474).
test_case('testsets/westphalia_sovereignty__graded_sovereignty.pl', 'westphalia_sovereignty__graded_sovereignty', 'WESTPHALIA_SOVEREIGNTY__GRADED_SOVEREIGNTY', 475).
test_case('testsets/westphalian_sovereignty__absolute_sovereignty.pl', 'westphalian_sovereignty__absolute_sovereignty', 'WESTPHALIAN_SOVEREIGNTY__ABSOLUTE_SOVEREIGNTY', 476).
test_case('testsets/westphalian_sovereignty__conditional_sovereignty.pl', 'westphalian_sovereignty__conditional_sovereignty', 'WESTPHALIAN_SOVEREIGNTY__CONDITIONAL_SOVEREIGNTY', 477).
test_case('testsets/westphalian_sovereignty__graduated_sovereignty.pl', 'westphalian_sovereignty__graduated_sovereignty', 'WESTPHALIAN_SOVEREIGNTY__GRADUATED_SOVEREIGNTY', 478).
test_case('testsets/woman_female_category__gender_identity_reading.pl', 'woman_female_category__gender_identity_reading', 'WOMAN_FEMALE_CATEGORY__GENDER_IDENTITY_READING', 479).
test_case('testsets/woman_female_category__hybrid_contextual_reading.pl', 'woman_female_category__hybrid_contextual_reading', 'WOMAN_FEMALE_CATEGORY__HYBRID_CONTEXTUAL_READING', 480).
test_case('testsets/woman_female_category__sex_biology_reading.pl', 'woman_female_category__sex_biology_reading', 'WOMAN_FEMALE_CATEGORY__SEX_BIOLOGY_READING', 481).
test_case('testsets/wto_treaty_framework__developmental_reading.pl', 'wto_treaty_framework__developmental_reading', 'WTO_TREATY_FRAMEWORK__DEVELOPMENTAL_READING', 482).
test_case('testsets/wto_treaty_framework__market_access_reading.pl', 'wto_treaty_framework__market_access_reading', 'WTO_TREATY_FRAMEWORK__MARKET_ACCESS_READING', 483).
test_case('testsets/zero_as_number_entry__contingent_thinkability_reading.pl', 'zero_as_number_entry__contingent_thinkability_reading', 'ZERO_AS_NUMBER_ENTRY__CONTINGENT_THINKABILITY_READING', 484).
test_case('testsets/zero_as_number_entry__hybrid_scaffolding_reading.pl', 'zero_as_number_entry__hybrid_scaffolding_reading', 'ZERO_AS_NUMBER_ENTRY__HYBRID_SCAFFOLDING_READING', 485).
test_case('testsets/zero_as_number_entry__universal_discovery_reading.pl', 'zero_as_number_entry__universal_discovery_reading', 'ZERO_AS_NUMBER_ENTRY__UNIVERSAL_DISCOVERY_READING', 486).

% --- Test Suite Runner ---
run_dynamic_suite :-
    retractall(test_passed(_)),
    retractall(test_failed(_, _, _)),
    writeln('--- STARTING DYNAMIC VALIDATION ---'),
    forall(test_case(Path, ID, Label, N), run_single_test(Path, ID, Label, N)),
    count_and_report,
    % Call validate_all directly from data_validation module
    data_validation:validate_all.

% --- Single Test Executor ---
%  Per-test timeout guard (60s) prevents any single test from consuming
%  the entire sweep timeout. Elapsed timing aids diagnostic profiling.
run_single_test(Path, ID, _Label, N) :-
    format('~n[~w] EXECUTING: ~w~n', [N, Path]),
    get_time(T0),
    catch(
        call_with_time_limit(
            60,
            (   catch_with_backtrace(
                    ( load_and_run(Path, ID) ->
                        assertz(test_passed(Path)),
                        format('[PASS] ~w~n', [Path])
                    ;   assertz(test_failed(Path, audit_failed, 'load_and_run returned false')),
                        format('[AUDIT FAIL] ~w~n', [Path])
                    ),
                    E,
                    (   assertz(test_failed(Path, exception, E)),
                        format('[FAIL] Exception for ~w: ~w~n', [Path, E]),
                        print_prolog_backtrace(current_output, E)
                    )
                ),
                report_generator:generate_llm_feedback(ID)
            )
        ),
        time_limit_exceeded,
        (   assertz(test_failed(Path, timeout, 'Exceeded 60s per-test limit')),
            format('[TIMEOUT] ~w~n', [Path])
        )
    ),
    get_time(T1),
    Elapsed is T1 - T0,
    format('[ELAPSED] ~w: ~3fs~n', [Path, Elapsed]).

% --- Result Counter & Reporter ---
count_and_report :-
    findall(P, test_passed(P), Ps), length(Ps, PC),
    findall(F, test_failed(F,_,_), Fs), length(Fs, FC),
    writeln(''),
    writeln('=================================================='),
    writeln('           TEST SUITE SUMMARY'),
    writeln('=================================================='),
    format('Passed: ~w~n', [PC]),
    format('Failed: ~w~n', [FC]),
    (FC > 0 -> report_failures ; true),
    writeln('==================================================').

report_failures :-
    writeln('--- FAILED TESTS ---'),
    forall(test_failed(Path, Type, Detail),
           format('~n  - [~w] ~w~n    Reason: ~w~n', [Type, Path, Detail])).

