% ============================================================================
% CONSTRAINT STORY: recipe_scaling_ai
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-04-29
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_recipe_scaling_ai, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: recipe_scaling_ai
 *   human_readable: The NYT Cooking Generative Scaling Constraint
 *   domain: technological
 *
 * SUMMARY:
 *   A generative AI tool that automates recipe doubling/halving. This story
 *   examines the potential upsides and downsides of using AI to scale
 *   recipes, focusing on the coordination benefits for recipe providers (NYT
 *   Cooking) versus the potential risks for novice cooks and culinary
 *   traditions.
 *
 * KEY AGENTS:
 *   - NYT Cooking: Benefits from automated scaling (institutional/arbitrage).
 *   - Home Cooks (Novice): Bear the costs of inaccurate recipes (powerless/trapped).
 *   - Culinary Tradition Integrity: Abstract value potentially harmed by homogenization (powerless/trapped).
 *   - Recipe Developers (NYT): Benefits from improved workflow and efficiency (moderate/mobile).
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(recipe_scaling_ai, 0.35).
domain_priors:suppression_score(recipe_scaling_ai, 0.25).
domain_priors:theater_ratio(recipe_scaling_ai, 0.15).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(recipe_scaling_ai, extractiveness, 0.35).
narrative_ontology:constraint_metric(recipe_scaling_ai, suppression_requirement, 0.25).
narrative_ontology:constraint_metric(recipe_scaling_ai, theater_ratio, 0.15).

% --- Constraint claim ---
narrative_ontology:constraint_claim(recipe_scaling_ai, tangled_rope).
narrative_ontology:human_readable(recipe_scaling_ai, "The NYT Cooking Generative Scaling Constraint").
narrative_ontology:topic_domain(recipe_scaling_ai, "technological").

domain_priors:requires_active_enforcement(recipe_scaling_ai).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(recipe_scaling_ai, nyt_cooking).
narrative_ontology:constraint_beneficiary(recipe_scaling_ai, recipe_developers_nyt).
narrative_ontology:constraint_victim(recipe_scaling_ai, home_cooks_novice).
narrative_ontology:constraint_victim(recipe_scaling_ai, culinary_tradition_integrity).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% Novice home cooks may be trapped and bear the costs of inaccurate or poorly adapted recipes. They lack the experience to judge the validity of scaled recipes generated by AI, and thus face a Snare.
constraint_indexing:constraint_classification(recipe_scaling_ai, snare,
    context(agent_power(powerless),
            time_horizon(generational),
            exit_options(trapped),
            spatial_scope(global))).

% NYT Cooking benefits from the AI tool by automating recipe scaling, saving time and resources. This appears as a pure coordination mechanism.
constraint_indexing:constraint_classification(recipe_scaling_ai, rope,
    context(agent_power(institutional),
            time_horizon(biographical),
            exit_options(arbitrage),
            spatial_scope(national))).

% An analytical observer sees both the benefits of automation (coordination) and potential for extractive or suppressive effects (inaccurate results harming novice cooks or eroding culinary traditions), leading to a Tangled Rope classification.
constraint_indexing:constraint_classification(recipe_scaling_ai, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

% Recipe developers at NYT cooking may also benefit, but have mobile exit options, the AI scaling feature allows recipe adaptation quickly, and more robustly, acting as a tool to improve output.
constraint_indexing:constraint_classification(recipe_scaling_ai, rope,
    context(agent_power(moderate),
            time_horizon(biographical),
            exit_options(mobile),
            spatial_scope(national))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(recipe_scaling_ai_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(recipe_scaling_ai, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(recipe_scaling_ai, TypeOther, context(agent_power(institutional), _, _, _)),
    TypePowerless \= TypeOther.

:- end_tests(recipe_scaling_ai_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness: NYT gains efficiency while novice cooks may bear the cost of poorly adapted recipes. Suppression: Novice cooks may lack the skills to identify inaccurate scaled recipes. Theater Ratio: Relatively low, reflecting that the primary function is practical automation, not performative compliance.
 *
 * PERSPECTIVAL GAP:
 *   NYT sees a coordination tool (Rope), while novice cooks could be ensnared by inaccurate recipes (Snare). The analytical observer recognizes the mixed nature (Tangled Rope).
 *
 * DIRECTIONALITY LOGIC:
 *   NYT benefits significantly (low d), while novice cooks may be harmed (high d). The directionality values reflect these structural relationships.
 *
 * MANDATROPHY ANALYSIS:
 *   This example illustrates the difficulty in classifying generative AI: is it primarily a tool for efficiency (coordination) or a potential source of harm (extraction)? The answer depends on the AI's accuracy and the user's skills.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    ai_accuracy_threshold,
    'What is the accuracy threshold of the AI scaling algorithm required to avoid harming novice cooks?',
    'Empirical testing of AI-scaled recipes; feedback from users with varying skill levels.',
    'If accuracy is high, the constraint leans toward rope. If low, it leans toward snare.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(ai_accuracy_threshold, empirical, 'Accuracy threshold of the AI scaling algorithm').

omega_variable(
    culinary_tradition_erosion,
    'Does automated scaling lead to a homogenization of recipes and erosion of culinary traditions?',
    'Analysis of recipe diversity over time; assessment of cultural impact on food practices.',
    'If traditions are harmed, the extractive element of the constraint is strengthened. If not, it''s primarily a coordination mechanism.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(culinary_tradition_erosion, conceptual, 'Impact on culinary tradition').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(recipe_scaling_ai, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(reci_tr_t0, recipe_scaling_ai, theater_ratio, 0, 0.1).
narrative_ontology:measurement(reci_tr_t5, recipe_scaling_ai, theater_ratio, 5, 0.12).
narrative_ontology:measurement(reci_tr_t10, recipe_scaling_ai, theater_ratio, 10, 0.15).

% Extraction over time
narrative_ontology:measurement(reci_be_t0, recipe_scaling_ai, base_extractiveness, 0, 0.25).
narrative_ontology:measurement(reci_be_t5, recipe_scaling_ai, base_extractiveness, 5, 0.3).
narrative_ontology:measurement(reci_be_t10, recipe_scaling_ai, base_extractiveness, 10, 0.35).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(recipe_scaling_ai, information_standard).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
