% ============================================================================
% CONSTRAINT STORY: ai_risk_prioritization__near_term_harms_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_ai_risk_prioritization__near_term_harms_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:suppression_profile/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: ai_risk_prioritization__near_term_harms_reading
 *   human_readable: Near-Term Harms Reading of AI Risk Prioritization
 *   domain: AI safety / technology governance / risk assessment
 *
 * SUMMARY:
 *   This story instantiates ONE reading of the contested
 *   ai_risk_prioritization kernel: the near-term harms reading, which holds
 *   that measurable, present-tense algorithmic discrimination, labor
 *   displacement, and surveillance against identifiable marginalized
 *   populations are the primary object of AI-risk governance, and that
 *   existential-risk framing functions as a speculative distraction diverting
 *   resources from urgent justice interventions. The sibling reading
 *   (existential_risk_reading, not authored here) holds the inverse
 *   resource-allocation claim. This story does not describe or adjudicate the
 *   contest between readings; it authors only the near-term harms reading as
 *   a standalone, ε-invariant constraint: its own coordination function
 *   (concentrating scarce attention on documented present harms), its own
 *   beneficiary/victim structure, and its own extraction profile as this
 *   reading's advocates would themselves describe the standing arrangement.
 *
 * KEY AGENTS:
 *   - fairness_accountability_researchers: Primary agenda-setter and beneficiary (organized/mobile) — builds audit methodology and collects institutional standing from the framing's dominance
 *   - ai_ethics_consultancies: Secondary beneficiary (organized/mobile) — commercial capture of compliance demand generated by the framing
 *   - racialized_loan_and_hiring_applicants, gig_and_warehouse_workers, surveilled_low_income_tenants: Primary targets (powerless/trapped) — bear the named present-tense harms and receive uneven, often unenforced protective benefit
 *   - frontier_ai_labs, existential_risk_researchers: Excluded/adjacent actors — outside the near-term coalition's institutional venues, experience the framing as compliance cost or as delegitimizing pressure on their own resource claims
 *   - policy_analysts: Analytical observer — allocates scarce regulatory and legislative attention between competing risk claims
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(ai_risk_prioritization__near_term_harms_reading, 0.62).
domain_priors:suppression_score(ai_risk_prioritization__near_term_harms_reading, 0.48).
domain_priors:theater_ratio(ai_risk_prioritization__near_term_harms_reading, 0.4).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(ai_risk_prioritization__near_term_harms_reading, extractiveness, 0.62).
narrative_ontology:constraint_metric(ai_risk_prioritization__near_term_harms_reading, suppression_requirement, 0.48).
narrative_ontology:constraint_metric(ai_risk_prioritization__near_term_harms_reading, theater_ratio, 0.4).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(ai_risk_prioritization__near_term_harms_reading, accessibility_collapse, 0.4).
narrative_ontology:constraint_metric(ai_risk_prioritization__near_term_harms_reading, resistance, 0.6).

% --- Constraint claim ---
narrative_ontology:constraint_claim(ai_risk_prioritization__near_term_harms_reading, tangled_rope).
narrative_ontology:human_readable(ai_risk_prioritization__near_term_harms_reading, "Near-Term Harms Reading of AI Risk Prioritization").
narrative_ontology:topic_domain(ai_risk_prioritization__near_term_harms_reading, "AI safety / technology governance / risk assessment").

domain_priors:requires_active_enforcement(ai_risk_prioritization__near_term_harms_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(ai_risk_prioritization__near_term_harms_reading, '27eea68a-a6be-42a7-8517-352b889ddee0').
narrative_ontology:cs_kernel_codification('27eea68a-a6be-42a7-8517-352b889ddee0', distributed).
narrative_ontology:cs_authority_grounding('27eea68a-a6be-42a7-8517-352b889ddee0', distributed).
narrative_ontology:cs_reading_relation('27eea68a-a6be-42a7-8517-352b889ddee0', ai_risk_prioritization__existential_risk_reading, coexists_with).
narrative_ontology:cs_axiom('27eea68a-a6be-42a7-8517-352b889ddee0', foundational, present_measurable_harm_takes_priority_over_speculative_future_harm).
narrative_ontology:cs_axiom_status(present_measurable_harm_takes_priority_over_speculative_future_harm, holdable).
narrative_ontology:cs_axiom_grounding('27eea68a-a6be-42a7-8517-352b889ddee0', present_measurable_harm_takes_priority_over_speculative_future_harm, empirically_contingent).
narrative_ontology:cs_axiom('27eea68a-a6be-42a7-8517-352b889ddee0', foundational, justice_for_currently_marginalized_populations_is_the_paramount_ai_governance_obligation).
narrative_ontology:cs_axiom_status(justice_for_currently_marginalized_populations_is_the_paramount_ai_governance_obligation, holdable).
narrative_ontology:cs_axiom_grounding('27eea68a-a6be-42a7-8517-352b889ddee0', justice_for_currently_marginalized_populations_is_the_paramount_ai_governance_obligation, deontological).
narrative_ontology:cs_reference_frame('27eea68a-a6be-42a7-8517-352b889ddee0', documented_algorithmic_harm_as_governance_baseline).
narrative_ontology:cs_drift_state('27eea68a-a6be-42a7-8517-352b889ddee0', contemporary_ai_policy_debate, gap(revival_pressure, substantial, true)).
narrative_ontology:cs_created_at('27eea68a-a6be-42a7-8517-352b889ddee0', '').
narrative_ontology:cs_kernel_id(ai_risk_prioritization__near_term_harms_reading, ai_risk_prioritization).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(ai_risk_prioritization__near_term_harms_reading, fairness_accountability_researchers).
narrative_ontology:constraint_beneficiary(ai_risk_prioritization__near_term_harms_reading, ai_ethics_consultancies).
narrative_ontology:constraint_beneficiary(ai_risk_prioritization__near_term_harms_reading, compliance_vendor_firms).
narrative_ontology:constraint_victim(ai_risk_prioritization__near_term_harms_reading, racialized_loan_and_hiring_applicants).
narrative_ontology:constraint_victim(ai_risk_prioritization__near_term_harms_reading, gig_and_warehouse_workers).
narrative_ontology:constraint_victim(ai_risk_prioritization__near_term_harms_reading, surveilled_low_income_tenants).
narrative_ontology:constraint_vindicates(ai_risk_prioritization__near_term_harms_reading, algorithmic_discrimination_is_measurable_now).
narrative_ontology:constraint_vindicates(ai_risk_prioritization__near_term_harms_reading, present_harm_claims_require_no_speculative_forecasting).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Build the audit methodologies, publish disparate-impact findings, and set the terms of what counts as an actionable harm in policy venues. Career trajectories, grant pipelines, and conference prestige are built on this framing being the dominant one; they can shift research emphasis if funding moves but currently gain standing, citations, and consulting income from the near-term framing prevailing over long-horizon alignment framing.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, fairness_accountability_researchers, agenda_setter,
    organized, biographical, mobile, national).
narrative_ontology:stakeholder_secondary_role(ai_risk_prioritization__near_term_harms_reading, fairness_accountability_researchers, beneficiary).

% Sell bias-audit, compliance, and 'responsible AI' services to firms deploying scoring and surveillance systems. Revenue depends on the near-term harms framing remaining the operative regulatory lens; can pivot business lines if regulatory attention shifts elsewhere.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, ai_ethics_consultancies, beneficiary,
    organized, immediate, mobile, national).

% Are scored, screened, and sorted by deployed models in credit, hiring, and housing pipelines today. Bear the discrimination directly, cannot opt out of the systems that evaluate them, and have no visibility into the scoring logic. Benefit only indirectly and unevenly from audit-driven reforms, which arrive slowly and are frequently underenforced.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, racialized_loan_and_hiring_applicants, payer,
    powerless, immediate, trapped, national).

% Subject to algorithmic scheduling, productivity scoring, and automated discipline systems that displace labor bargaining power. Cannot exit the platforms without losing income; worker-protection interventions justified under this framing arrive as pilot programs and voluntary codes more often than binding law.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, gig_and_warehouse_workers, payer,
    powerless, immediate, trapped, national).

% Live under algorithmic tenant-screening and predictive-policing systems concentrated in low-income neighborhoods. Cannot relocate away from surveillance infrastructure without cost; the near-term framing names their harm explicitly but institutional remedy (audits, disclosure rules) rarely reaches enforcement with teeth.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, surveilled_low_income_tenants, payer,
    powerless, immediate, trapped, regional).

% Deploy the systems being audited but are largely absent from the near-term harms coalition's governance table except as regulatory targets; they fund alignment research and long-horizon safety framing instead, and experience the near-term framing as a compliance cost rather than a seat at the table where risk priorities are set.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, frontier_ai_labs, excluded,
    institutional, generational, arbitrage, global).

% Argue that concentrating governance attention and funding on present, measurable harms diverts resources and legitimacy from alignment work aimed at low-probability, high-severity future outcomes. Are frequently characterized within this reading's discourse as speculative or distracting, which affects their funding access and policy standing even though they are not present in the near-term coalition's institutional venues.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, existential_risk_researchers, excluded,
    organized, civilizational, constrained, global).

% Evaluate competing risk-prioritization claims for legislative and regulatory bodies, weighing near-term harm evidence against long-horizon uncertainty. Their allocation decisions determine which coalition's resource claims prevail in a given budget cycle.
narrative_ontology:constraint_stakeholder(ai_risk_prioritization__near_term_harms_reading, policy_analysts, observer,
    institutional, generational, analytical, national).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(ai_risk_prioritization__near_term_harms_reading, fairness_accountability_researchers).
narrative_ontology:fixing_cost_class(ai_risk_prioritization__near_term_harms_reading, cheap).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Concentrates scarce regulatory attention, research funding, and advocacy capacity on documented, measurable algorithmic harms occurring in deployed systems today, enabling coordinated audits, disclosure rules, and worker/tenant protections that would be harder to organize under a diffuse or purely speculative risk frame.
% TRANSFER_FUNCTION: Moves research funding, regulatory attention, compliance spending, and legislative bandwidth toward bias-audit and accountability infrastructure and toward the researchers/consultancies who supply it, while moving attention and resources away from long-horizon alignment research; moves some protective value toward affected marginalized populations, but unevenly and often without binding enforcement.
% ABSENT_VOICES: Existential-risk researchers and frontier lab safety teams are largely outside the near-term coalition's institutional venues and are frequently characterized within this framing as speculative or self-interested; they would object that civilizational-scale risk is being systematically under-weighted relative to its expected severity. Affected populations themselves (loan applicants, gig workers, surveilled tenants) are named as the victim class but rarely sit in the rooms where audit standards and enforcement priorities are actually set.
% DISAPPEARANCE_RATIONALE: If the near-term harms framing disappeared overnight, the fairness/accountability research field and compliance-consulting industry would lose their primary policy leverage and funding rationale — a real institutional rearrangement. Whether the underlying harms (discriminatory scoring, surveillance, labor displacement) would go unaddressed or would simply be picked up under a different framing is disputed: near-term advocates say the harms would go unaddressed without this framing's specific institutional machinery; x-risk-aligned critics say the harms are real but the framing's dominance is contingent on coalition politics, not on the harms' irreducibility to this particular institutional form.
% FOUNDING_PROBLEM: Deployed algorithmic systems (credit scoring, hiring filters, predictive policing, tenant screening, gig-work management) were producing documented, measurable discriminatory and exploitative outcomes for identifiable populations right now, while public and philanthropic attention and funding were disproportionately flowing to speculative long-horizon AI risk research.
% FOUNDING_PROBLEM_CORROBORATION: Documented by independent investigative journalism (e.g., audits of hiring and lending algorithms), academic disparate-impact studies published outside the advocacy coalition's own institutions, and litigation records in discrimination and labor cases — sources outside the fairness/accountability research and consultancy beneficiary set corroborate that measurable present-tense harms exist. Whether the specific institutional response (this framing's resource allocation) remains the right-sized answer to that live problem is contested by x-risk-aligned critics from outside the near-term coalition.
narrative_ontology:disappearance_verdict(ai_risk_prioritization__near_term_harms_reading, contested).
narrative_ontology:founding_problem_status(ai_risk_prioritization__near_term_harms_reading, live).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(ai_risk_prioritization__near_term_harms_reading, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet3', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(ai_risk_prioritization__near_term_harms_reading, 'none', 1).
narrative_ontology:epsilon_provenance(ai_risk_prioritization__near_term_harms_reading, 0.62, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(ai_risk_prioritization__near_term_harms_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(ai_risk_prioritization__near_term_harms_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(ai_risk_prioritization__near_term_harms_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.62 at interval end) reflects that a meaningful share of the resource flow this framing organizes — grant funding, consulting revenue, conference and publication capital — accrues to the researcher/consultancy layer rather than converting reliably into enforceable protection for the named victim populations; theater_ratio rising to 0.40 reflects a growing gap between audit/disclosure activity performed and binding structural remedy delivered (voluntary codes, unenforced disclosure rules, symbolic bias-bounty programs). Suppression (0.48) is moderate rather than severe: the framing does not physically bar the sibling reading, but it does actively work — in funding panels, conference programs, and media framing — to characterize existential-risk concern as privileged, speculative, or a distraction from urgent justice work, which constrains the sibling reading's resource access without foreclosing it outright. accessibility_collapse (0.4) is moderate: alternative framings remain articulable and held by identifiable actors (the excluded seats), so collapse is partial, not near-total. resistance (0.6) is substantial because the framing is actively contested by a well-organized rival coalition (frontier labs, x-risk researchers) rather than facing only diffuse or symbolic pushback.
 *
 * PERSPECTIVAL GAP:
 *   From the agenda-setter seat (fairness/accountability researchers), the arrangement reads as urgent, underfunded justice work correctly prioritized over speculative long-horizon concern. From the payer seats (racialized applicants, gig workers, surveilled tenants), the same arrangement can read as extraction-adjacent: their harms are named and used as the framing's justificatory center, but the resource flow the framing organizes disproportionately builds researcher and consultancy institutional capital relative to the binding, enforceable protection actually delivered to them. The engine's per-seat computation is expected to surface this divergence rather than resolve it — that divergence is the analytical product, not a flaw in the story.
 *
 * DIRECTIONALITY LOGIC:
 *   fairness_accountability_researchers and ai_ethics_consultancies sit near the beneficiary end: they set the terms of the framing and derive career capital, contracts, and institutional standing from its dominance, with mobile exit if the funding landscape shifts. The three payer groups sit at the full-target end: powerless, trapped exit, immediate time horizon, bearing the named harms directly while institutional remedy under this framing arrives slowly, unevenly, and often without enforcement teeth — real protective value exists but is diffuse and delayed relative to the resource capture at the agenda-setting layer. frontier_ai_labs and existential_risk_researchers are excluded rather than positioned as beneficiaries or victims within this reading's own structure — they are outside the coalition, experiencing the framing's dominance as external pressure on their own legitimacy and funding rather than as extraction from them via this constraint's mechanism.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem (documented, present-tense algorithmic harm to identifiable populations) remains live and corroborated from outside the beneficiary set — this is not a manufactured crisis. The mandatrophy risk is narrower: whether the specific institutional machinery this framing has built (audit consultancies, academic fairness centers, disclosure-rule advocacy) has begun to substitute its own persistence and resource capture for the harm-reduction outcome it was built to deliver. Classifying this as tangled_rope rather than snare or pure rope preserves both halves: it is not dismissed as pure extraction (the coordination function — concentrating attention on real, previously neglected harms — is genuine and its beneficiaries are not fabricated), and it is not certified as clean coordination either (the resource flow to the agenda-setting layer is disproportionate to enforceable benefit delivered to the named victim populations, and active suppression of the sibling framing is a real, if moderate, feature of how this reading maintains its resource position).
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    resource_allocation_zero_sum_ambiguity,
    'Is AI-risk governance attention and funding genuinely zero-sum between near-term harms work and existential-risk work, or is the perceived competition itself a coalition-politics artifact that could be resolved by simply expanding total resources?',
    'Track whether philanthropic and public AI-safety funding pools have grown enough over the interval that near-term and long-horizon allocations could both increase in absolute terms; if total funding is expanding faster than either coalition''s claims, the zero-sum framing is weaker than either coalition asserts.',
    'If genuinely zero-sum, the suppression this reading exerts on the sibling reading is a rational resource-competition strategy; if not zero-sum, the suppression is better read as reputational/legitimacy competition dressed as resource necessity, raising the effective extraction attributable to the agenda-setting layer.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(resource_allocation_zero_sum_ambiguity, empirical, 'Whether near-term and long-horizon AI risk framings are in real resource competition or manufactured competition.').

omega_variable(
    enforcement_gap_attribution,
    'Is the gap between audit/disclosure activity and enforceable protection for named victim populations attributable to the near-term coalition''s institutional design choices, or to external political constraints (legislative gridlock, industry lobbying) the coalition does not control?',
    'Compare jurisdictions where the near-term coalition achieved binding legislative wins against jurisdictions where only voluntary codes resulted, controlling for industry lobbying intensity and legislative composition.',
    'If the gap is coalition-attributable, theater_ratio and extractiveness scores understate the framing''s self-serving character; if externally constrained, the framing''s institutional layer is closer to a genuine but under-resourced rope than a tangled rope.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(enforcement_gap_attribution, empirical, 'Whether unenforced protection outcomes stem from coalition design or external political constraint.').

omega_variable(
    kernel_framing_choice_ambiguity,
    'Given that both readings of the ai_risk_prioritization kernel are held by well-organized, resource-seeking coalitions, is there a principled (non-coalition-interested) basis for adjudicating the correct resource split between near-term and long-horizon AI risk work, or is the split irreducibly a policy/values question?',
    'Would require an allocation framework external to both coalitions'' own institutional interests — e.g., expected-value analysis under explicit, contestable probability and severity estimates for both harm classes, subjected to adversarial review by parties with no stake in either coalition''s funding.',
    'If a principled basis exists and favors one reading, that reading''s suppression of the other becomes harder to justify as legitimate coordination; if the split is irreducibly a values question, both readings'' suppression behavior toward each other is better modeled as ordinary political contest than as extraction from a neutral optimum.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(kernel_framing_choice_ambiguity, preference, 'Whether the kernel''s resource-split question has a fact-of-the-matter answer or is irreducibly a values dispute.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(ai_risk_prioritization__near_term_harms_reading, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(ai_r_tr_t0, ai_risk_prioritization__near_term_harms_reading, theater_ratio, 0, 0.22).
narrative_ontology:measurement(ai_r_tr_t2, ai_risk_prioritization__near_term_harms_reading, theater_ratio, 2, 0.27).
narrative_ontology:measurement(ai_r_tr_t4, ai_risk_prioritization__near_term_harms_reading, theater_ratio, 4, 0.31).
narrative_ontology:measurement(ai_r_tr_t6, ai_risk_prioritization__near_term_harms_reading, theater_ratio, 6, 0.35).
narrative_ontology:measurement(ai_r_tr_t8, ai_risk_prioritization__near_term_harms_reading, theater_ratio, 8, 0.38).
narrative_ontology:measurement(ai_r_tr_t10, ai_risk_prioritization__near_term_harms_reading, theater_ratio, 10, 0.4).

% Extraction over time
narrative_ontology:measurement(ai_r_be_t0, ai_risk_prioritization__near_term_harms_reading, base_extractiveness, 0, 0.42).
narrative_ontology:measurement(ai_r_be_t2, ai_risk_prioritization__near_term_harms_reading, base_extractiveness, 2, 0.48).
narrative_ontology:measurement(ai_r_be_t4, ai_risk_prioritization__near_term_harms_reading, base_extractiveness, 4, 0.53).
narrative_ontology:measurement(ai_r_be_t6, ai_risk_prioritization__near_term_harms_reading, base_extractiveness, 6, 0.57).
narrative_ontology:measurement(ai_r_be_t8, ai_risk_prioritization__near_term_harms_reading, base_extractiveness, 8, 0.6).
narrative_ontology:measurement(ai_r_be_t10, ai_risk_prioritization__near_term_harms_reading, base_extractiveness, 10, 0.62).

% Suppression authored static: scalar-only by design, no temporal series
narrative_ontology:suppression_profile(ai_risk_prioritization__near_term_harms_reading, static).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(ai_risk_prioritization__near_term_harms_reading, enforcement_mechanism).
narrative_ontology:boltzmann_floor_override(ai_risk_prioritization__near_term_harms_reading, 0.12).
narrative_ontology:affects_constraint(ai_risk_prioritization__near_term_harms_reading, existential_risk_reading).

% DUAL FORMULATION NOTE:
% This constraint and existential_risk_reading are sibling readings of the shared kernel ai_risk_prioritization. They are linked but structurally distinct: different ε (this reading's extraction is measured against present-tense, documented harm; the sibling's is measured against speculative future severity), different beneficiary/victim sets, and different suppression mechanics (each reading characterizes the other as illegitimate or distracting). Do not merge their metrics or treat one as the 'true' reading with the other as noise — per the ε-invariance principle, each is authored as its own constraint.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
