% ============================================================================
% CONSTRAINT STORY: catastrophe_avoidance_retention__catastrophe_as_necessary_selector
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_catastrophe_avoidance_retention__catastrophe_as_necessary_selector, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: catastrophe_avoidance_retention__catastrophe_as_necessary_selector
 *   human_readable: Catastrophe as the Only True Selector of Competence
 *   domain: safety_engineering/organizational_learning
 *
 * SUMMARY:
 *   This story authors the 'catastrophe as necessary selector' reading of the
 *   catastrophe_avoidance_retention kernel: the view that only lived,
 *   chaotic, mortality-salient organizational trauma can restore or maintain
 *   safety competence, and that simulation and near-miss learning are
 *   structurally insufficient substitutes. This is a hybrid
 *   coordination/extraction structure: the underlying observation about
 *   vigilance decay during long peacetime intervals is empirically real and
 *   does coordinate genuine reform after disasters, but the doctrine also
 *   transfers the cost of maintaining competence onto frontline workers and
 *   adjacent communities while channeling the political and professional
 *   capital generated by catastrophe toward reform coalitions and
 *   investigators who did not bear the loss. As theater_ratio rises across
 *   the measured interval, an increasing share of 'lessons learned' activity
 *   becomes ritualized post-incident performance (task forces, blue-ribbon
 *   panels, memorial procedures) layered on top of the genuine but
 *   comparatively modest structural changes actually implemented.
 *
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 0.42).
domain_priors:suppression_score(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 0.31).
domain_priors:theater_ratio(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 0.58).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, extractiveness, 0.42).
narrative_ontology:constraint_metric(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, suppression_requirement, 0.31).
narrative_ontology:constraint_metric(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, theater_ratio, 0.58).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, accessibility_collapse, 0.4).
narrative_ontology:constraint_metric(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, resistance, 0.55).

% --- Constraint claim ---
narrative_ontology:constraint_claim(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, tangled_rope).
narrative_ontology:human_readable(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, "Catastrophe as the Only True Selector of Competence").
narrative_ontology:topic_domain(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, "safety_engineering/organizational_learning").

domain_priors:requires_active_enforcement(catastrophe_avoidance_retention__catastrophe_as_necessary_selector).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, '23a65fe0-faa8-4b76-a6eb-ea0f8734caaa').
narrative_ontology:cs_kernel_codification('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', distributed).
narrative_ontology:cs_authority_grounding('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', distributed).
narrative_ontology:cs_reading_relation('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', catastrophe_avoidance_retention__simulation_as_proxy_catastrophe, forecloses).
narrative_ontology:cs_reading_relation('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', catastrophe_avoidance_retention__hybrid_near_miss_learning, influences).
narrative_ontology:cs_axiom('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', foundational, mortality_salience_is_irreplaceable).
narrative_ontology:cs_axiom_status(mortality_salience_is_irreplaceable, holdable).
narrative_ontology:cs_axiom_grounding('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', mortality_salience_is_irreplaceable, empirically_contingent).
narrative_ontology:cs_axiom('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', secondary, simulated_stakes_cannot_substitute_for_real_organizational_trauma).
narrative_ontology:cs_axiom_status(simulated_stakes_cannot_substitute_for_real_organizational_trauma, holdable).
narrative_ontology:cs_axiom_grounding('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', simulated_stakes_cannot_substitute_for_real_organizational_trauma, empirically_contingent).
narrative_ontology:cs_reference_frame('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', pre_catastrophe_complacent_baseline).
narrative_ontology:cs_drift_state('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', contemporary_high_reliability_organization_era, gap(repudiation_pressure, substantial, false)).
narrative_ontology:cs_created_at('23a65fe0-faa8-4b76-a6eb-ea0f8734caaa', '').
narrative_ontology:cs_kernel_id(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, catastrophe_avoidance_retention).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, post_disaster_reform_coalitions).
narrative_ontology:constraint_beneficiary(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, career_investigators_and_forensic_consultants).
narrative_ontology:constraint_beneficiary(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, regulatory_bodies_seeking_new_mandates).
narrative_ontology:constraint_victim(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, frontline_operators_between_disasters).
narrative_ontology:constraint_victim(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, workers_and_communities_near_high_hazard_sites).
narrative_ontology:constraint_victim(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, organizations_starved_of_investment_absent_a_trigger_event).
narrative_ontology:constraint_vindicates(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, normalization_of_deviance_thesis).
narrative_ontology:constraint_vindicates(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, learning_only_through_pain_doctrine).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Gain legitimacy, funding, and institutional standing in the aftermath of a catastrophe. Their reform agendas — new inspection regimes, budget increases, restructured chains of command — only become politically actionable once a disaster has produced bodies, wreckage, or a public inquiry. They have structural incentive to frame prior peacetime as complacent.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, post_disaster_reform_coalitions, beneficiary,
    organized, generational, mobile, national).

% Build careers, consulting contracts, and expert authority around root-cause analysis of major failures. Their professional relevance is renewed each time a catastrophe occurs and diminishes during long stretches of quiet operation; they have no comparable market for warning about risks that never materialize.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, career_investigators_and_forensic_consultants, beneficiary,
    moderate, biographical, mobile, national).

% Administer the safety regime and can revise standards after an incident, but their statutory authority to compel costly changes is politically fragile absent a triggering disaster. They benefit from post-catastrophe mandate expansion but bear blame if a disaster occurs on their watch, so they are structurally dependent on catastrophe as the engine of their own relevance.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, regulatory_bodies_seeking_new_mandates, agenda_setter,
    institutional, generational, constrained, national).
narrative_ontology:stakeholder_secondary_role(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, regulatory_bodies_seeking_new_mandates, beneficiary).

% Work the plant floor, control room, or flight deck during the long peacetime intervals the doctrine treats as inevitable competence decay. They absorb the consequences of skill atrophy, understaffed drills, and deferred investment, and are the first blamed when an incident finally occurs, even though the underlying system starved their training and margins long before the event.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, frontline_operators_between_disasters, payer,
    powerless, immediate, trapped, local).

% Live and work adjacent to refineries, reactors, mines, or transit hubs whose safety culture, on this reading, cannot be reliably renewed without an actual catastrophic event. They bear the risk of that catastrophe occurring near them as the very mechanism the constraint claims is necessary — they are the raw material of the selection pressure, not its beneficiaries.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, workers_and_communities_near_high_hazard_sites, payer,
    powerless, biographical, trapped, regional).

% Operating companies whose safety budgets and staffing are systematically deprioritized against production targets during peacetime, because internal capital allocation follows the same doctrine — competence investment is treated as unnecessary until crisis proves otherwise. Executives who advocate proactive investment lose internal arguments to those who can point to years without incident as evidence nothing more is needed.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, organizations_starved_of_investment_absent_a_trigger_event, payer,
    moderate, biographical, constrained, national).

% Argue that high-fidelity simulation and structured drills can substitute for the mortality-salience effects of real catastrophe. Under this reading their position is treated as producing false confidence rather than genuine competence, so their evidence and funding requests are structurally discounted by agenda-setters oriented toward catastrophe-driven reform cycles.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, simulation_and_drill_program_advocates, excluded,
    moderate, biographical, constrained, national).

% Study organizational learning curves across industries and catastrophe cycles, comparing incident-driven reform to simulation-based and near-miss-based learning models. They can see the doctrine's self-serving structure for its beneficiaries but lack the standing to compel any organization to change its investment cycle.
narrative_ontology:constraint_stakeholder(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, safety_science_researchers, observer,
    analytical, civilizational, analytical, global).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, post_disaster_reform_coalitions).
narrative_ontology:fixing_cost_class(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Genuinely coordinates a real phenomenon: catastrophic events do reliably generate political will, budget release, and behavioral change that quieter periods do not, because mortality salience and visible organizational trauma overcome normal bureaucratic inertia against costly safety investment.
% TRANSFER_FUNCTION: Moves the cost of maintaining competence from continuous peacetime investment (borne collectively, diffusely, cheaply) to concentrated catastrophic loss (borne acutely by frontline workers and adjacent communities), while the political and professional capital generated by the catastrophe flows to reform coalitions, investigators, and regulators who were not the ones who paid the price.
% ABSENT_VOICES: Simulation and drill advocates are structurally discounted because their evidence of competence maintenance without catastrophe undercuts the doctrine's premise; workers who survive near-misses without a full catastrophic event have no comparable platform to argue those near-misses already constituted sufficient selection pressure.
% DISAPPEARANCE_RATIONALE: If the doctrine's grip disappeared overnight, reform coalitions and investigators would lose their primary narrative for post-incident mandate expansion, and organizations might shift real investment earlier — but proponents of the doctrine argue the underlying psychological/organizational mechanism (competence decay without real stakes) is a genuine feature of institutions, not merely a constructed excuse, so the parties dispute whether the world actually rearranges or whether the doctrine is simply naming an intractable fact.
% FOUNDING_PROBLEM: Organizations genuinely do decay in vigilance during long safe intervals — checklists get skipped, near-misses get normalized, budgets drift toward production over margin — and something is needed to explain why competence erodes and to justify periodic renewal of safety investment.
% FOUNDING_PROBLEM_CORROBORATION: Independent safety-science researchers outside the beneficiary set corroborate that vigilance decay during long safe intervals is real (citing normalization-of-deviance literature), but they do not corroborate the stronger claim that only actual catastrophe — as opposed to well-designed near-miss review or high-fidelity simulation — can restore it; that stronger claim is attested primarily by the investigators and reform coalitions who benefit from catastrophe-triggered mandate cycles.
narrative_ontology:disappearance_verdict(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, contested).
narrative_ontology:founding_problem_status(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet3', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 'none', 1).
narrative_ontology:epsilon_provenance(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 0.42, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(catastrophe_avoidance_retention__catastrophe_as_necessary_selector_tests).
:- end_tests(catastrophe_avoidance_retention__catastrophe_as_necessary_selector_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.42) reflects a real but moderate transfer: the doctrine does not primarily enrich a concentrated extractor, but it does systematically under-invest peacetime safety relative to what continuous vigilance would require, with the shortfall paid by those closest to the hazard. Suppression (0.31) is comparatively low because no active machinery suppresses alternatives outright — simulation and near-miss learning advocates are marginalized through funding and narrative discounting rather than formal prohibition. Accessibility collapse (0.4) is moderate: workable alternatives (structured near-miss review, high-fidelity simulation) genuinely exist and are practiced in some high-reliability organizations, so alternatives have not fully collapsed, but the doctrine's dominance in post-incident narrative-setting makes them harder to fund and institutionalize. Resistance (0.55) is elevated because safety-science researchers, simulation advocates, and some regulators actively contest the doctrine's strong claim.
 *
 * PERSPECTIVAL GAP:
 *   From the agenda-setter/beneficiary seats, this reading looks like sober realism about organizational psychology — an unwelcome but true account of how institutions actually learn. From the frontline operator and adjacent-community seats, the same doctrine looks like a self-fulfilling excuse that forecloses cheaper, less costly forms of competence renewal (simulation, near-miss review) that would spare them from being the necessary raw material of the 'selection pressure.' The engine's per-seat computation should reflect this divergence directly from the power/exit/beneficiary structure, not from any authored evaluative label.
 *
 * DIRECTIONALITY LOGIC:
 *   Reform coalitions, investigators, and mandate-seeking regulators are beneficiaries: catastrophe renews their relevance, funding, and authority, so their directionality sits near the subsidized end. Frontline operators, adjacent communities, and investment-starved organizations are targets: they absorb the decay of peacetime vigilance and the eventual catastrophic cost, so their directionality sits near the full-target end, amplified by trapped or constrained exit options. The regulatory body carries a dual role — agenda_setter administering the safety regime, and secondary beneficiary of post-catastrophe mandate expansion — which is why it is marked with a secondary_role rather than split into two seats.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem (vigilance decay during long safe intervals) is real and not obsolete — this prevents dismissing the whole doctrine as pure extraction. But the doctrine's strong causal claim, that ONLY actual catastrophe (not simulation, not near-miss review) can restore competence, is contested by outside researchers and is exactly the claim that most benefits the catastrophe-dependent professional and political ecosystem. The tangled_rope classification holds both truths: genuine coordination function (disasters do produce real reform) plus asymmetric extraction (the cost of maintaining the doctrine's strong claim is paid by those nearest the hazard, while the benefit accrues to those who arrive after the fact).
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    catastrophe_necessity_vs_sufficiency_confound,
    'Does catastrophe provide selection pressure that is genuinely necessary for competence maintenance, or merely sufficient — with near-miss review and high-fidelity simulation capable of providing equivalent pressure if given comparable institutional weight and funding?',
    'Comparative longitudinal study of high-reliability organizations (nuclear power, commercial aviation, some undersea operations) that have avoided major catastrophe for decades: do their competence and safety outcomes track measurably below organizations that experienced a triggering disaster, controlling for hazard exposure and regulatory environment?',
    'If catastrophe is merely sufficient rather than necessary, this reading''s claimed_type should be read as an extraction-heavy narrative riding on a real but overstated coordination story; if genuinely necessary, the tangled_rope''s coordination half is stronger than currently authored and the doctrine''s persistence is less discretionary.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(catastrophe_necessity_vs_sufficiency_confound, empirical, 'Whether catastrophe is a necessary or merely sufficient condition for competence renewal, relative to simulation and near-miss alternatives.').

omega_variable(
    beneficiary_capture_of_the_founding_narrative,
    'To what extent has the founding problem (real vigilance decay) been captured and amplified by parties who professionally and politically benefit from catastrophe-driven reform cycles, versus representing an accurate account of organizational psychology independent of who benefits from asserting it?',
    'Trace funding, career, and mandate-expansion patterns across multiple industries'' post-catastrophe reform cycles; compare against industries where structured near-miss programs produced comparable reform without a triggering disaster, to see whether the causal story or the beneficiary structure better predicts which narrative dominates.',
    'Strong beneficiary capture would push this constraint toward a false-summit-adjacent reading despite not being claimed as a mountain — the strong necessity claim would be revealed as substantially serving the interests of those who assert it; weak capture would support treating the doctrine as a largely accurate, if costly, description of institutional reality.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(beneficiary_capture_of_the_founding_narrative, conceptual, 'Whether the doctrine''s strong necessity claim is shaped more by beneficiary interest than by independent organizational-psychology evidence.').

omega_variable(
    cs_framing_kernel_vs_legitimacy_layer,
    'Is the relevant kernel here the empirical claim about organizational learning mechanisms itself, or the layered legitimacy claim that regulatory and reform authority DEPENDS on catastrophe having occurred (i.e., the political/legal doctrine that mandates are only defensible post-incident)?',
    'Examine whether regulatory bodies in this reading''s domain can and do issue costly proactive mandates absent a triggering incident, versus requiring a catastrophe as legal/political predicate; compare rulemaking histories.',
    'If the legitimacy-layer framing is more accurate, this constraint''s authority_grounding and axioms would shift toward describing a political-legal doctrine rather than a purely empirical organizational-psychology claim, which would change how axiom grounding_type should be read (conventional/institutional rather than purely empirically_contingent).',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(cs_framing_kernel_vs_legitimacy_layer, conceptual, 'Whether the kernel is best framed as an empirical learning-mechanism claim or a legitimacy doctrine about when reform mandates are politically actionable.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 0, 40).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(cata_tr_t0, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, theater_ratio, 0, 0.25).
narrative_ontology:measurement(cata_tr_t8, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, theater_ratio, 8, 0.33).
narrative_ontology:measurement(cata_tr_t16, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, theater_ratio, 16, 0.42).
narrative_ontology:measurement(cata_tr_t24, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, theater_ratio, 24, 0.49).
narrative_ontology:measurement(cata_tr_t32, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, theater_ratio, 32, 0.54).
narrative_ontology:measurement(cata_tr_t40, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, theater_ratio, 40, 0.58).

% Extraction over time
narrative_ontology:measurement(cata_be_t0, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, base_extractiveness, 0, 0.3).
narrative_ontology:measurement(cata_be_t8, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, base_extractiveness, 8, 0.34).
narrative_ontology:measurement(cata_be_t16, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, base_extractiveness, 16, 0.38).
narrative_ontology:measurement(cata_be_t24, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, base_extractiveness, 24, 0.4).
narrative_ontology:measurement(cata_be_t32, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, base_extractiveness, 32, 0.41).
narrative_ontology:measurement(cata_be_t40, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, base_extractiveness, 40, 0.42).

% Suppression requirement over time
narrative_ontology:measurement(cata_su_t0, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, suppression_requirement, 0, 0.22).
narrative_ontology:measurement(cata_su_t8, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, suppression_requirement, 8, 0.24).
narrative_ontology:measurement(cata_su_t16, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, suppression_requirement, 16, 0.27).
narrative_ontology:measurement(cata_su_t24, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, suppression_requirement, 24, 0.29).
narrative_ontology:measurement(cata_su_t32, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, suppression_requirement, 32, 0.3).
narrative_ontology:measurement(cata_su_t40, catastrophe_avoidance_retention__catastrophe_as_necessary_selector, suppression_requirement, 40, 0.31).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, enforcement_mechanism).
narrative_ontology:boltzmann_floor_override(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, 0.1).
narrative_ontology:affects_constraint(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, simulation_as_proxy_catastrophe).
narrative_ontology:affects_constraint(catastrophe_avoidance_retention__catastrophe_as_necessary_selector, hybrid_near_miss_learning).

% DUAL FORMULATION NOTE:
% This constraint is one of three readings of the catastrophe_avoidance_retention kernel, decomposed per the ε-invariance principle because 'how organizations maintain safety competence' resolves to structurally distinct claims about what mechanism actually does the work. 'catastrophe_as_necessary_selector' (this story) holds ε=0.42 with tangled_rope structure: real coordination function plus asymmetric cost transfer onto frontline/community payers. 'simulation_as_proxy_catastrophe' would author a lower ε and likely a rope or scaffold structure, since it locates competence maintenance in a deliberately designed, non-coercive practice with broadly distributed benefit. 'hybrid_near_miss_learning' would author an intermediate ε and likely a rope structure, treating distributed learning as the dominant mechanism with catastrophe and simulation as supplementary inputs rather than the necessary selector. All three readings share the same underlying phenomenon (organizational competence decay and renewal) but diverge on the causal mechanism and, consequently, on who is positioned as necessary payer of the renewal cost.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
