% ============================================================================
% CONSTRAINT STORY: price_formation_kernel__georgist_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_price_formation_kernel__georgist_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:suppression_profile/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: price_formation_kernel__georgist_reading
 *   human_readable: Georgist Reading: Price Formation as Land-Rent Extraction Layered on Improvement Coordination
 *   domain: political_economy/housing_markets/institutional_analysis
 *
 * SUMMARY:
 *   This story instantiates the Georgist reading of the price-formation
 *   kernel: prices for real property bundle two structurally distinct
 *   components. The land component reflects location scarcity that no owner
 *   produced — fixed supply, positional advantage generated by surrounding
 *   public investment and agglomeration — and is treated by this reading as a
 *   mountain-adjacent fact (location scarcity is real and largely
 *   irreducible) whose CAPTURE by private titleholders is a snare (extraction
 *   without production, sustained by property-rights enforcement that need
 *   not itself be coercive to be extractive). The improvement component —
 *   buildings, infrastructure, business capital layered onto the site —
 *   genuinely coordinates productive activity and functions as a rope. This
 *   story authors ε for the standing arrangement (unseparated market pricing
 *   that lets land rent ride inside ordinary property price) as this
 *   reading's own lights assess it: substantially extractive, because rent
 *   capture is not a coordination cost but a transfer with no productive
 *   counterpart. Sibling readings (naturalist, institutional,
 *   financialization) are NOT part of this constraint; they are separate
 *   stories addressing the same 'price formation' label from different
 *   structural premises, linked via network edges.
 *
 * KEY AGENTS:
 *   - landowners: Primary beneficiary (powerful/arbitrage) — collects unearned location value
 *   - land_speculators: Secondary beneficiary (organized/arbitrage) — profits from anticipated rent gains
 *   - mortgage_lenders_on_land_value: Institutional beneficiary (institutional/arbitrage) — profits from interest on inflated land collateral
 *   - wage_laborers: Primary target (powerless/trapped) — location value they help create is captured by others
 *   - tenants: Primary target (powerless/constrained) — pay bundled rent without ability to separate land charge
 *   - productive_capital_investors: Mixed (moderate/constrained) — benefit from improvement coordination, pay land-rent tax on entry
 *   - new_market_entrants: Excluded (powerless/trapped) — priced out before any transaction is recorded
 *   - georgist_land_value_tax_advocates: Analytical observer (organized/analytical) — supplies the decomposition this reading relies on
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(price_formation_kernel__georgist_reading, 0.68).
domain_priors:suppression_score(price_formation_kernel__georgist_reading, 0.55).
domain_priors:theater_ratio(price_formation_kernel__georgist_reading, 0.4).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, extractiveness, 0.68).
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, suppression_requirement, 0.55).
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, theater_ratio, 0.4).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, accessibility_collapse, 0.6).
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, resistance, 0.58).

% --- Constraint claim ---
narrative_ontology:constraint_claim(price_formation_kernel__georgist_reading, snare).
narrative_ontology:human_readable(price_formation_kernel__georgist_reading, "Georgist Reading: Price Formation as Land-Rent Extraction Layered on Improvement Coordination").
narrative_ontology:topic_domain(price_formation_kernel__georgist_reading, "political_economy/housing_markets/institutional_analysis").

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(price_formation_kernel__georgist_reading, 'e35269d8-b8cc-4117-96df-e88089d992ab').
narrative_ontology:cs_kernel_codification('e35269d8-b8cc-4117-96df-e88089d992ab', distributed).
narrative_ontology:cs_authority_grounding('e35269d8-b8cc-4117-96df-e88089d992ab', distributed).
narrative_ontology:cs_reading_relation('e35269d8-b8cc-4117-96df-e88089d992ab', price_formation_kernel__naturalist_reading, forecloses).
narrative_ontology:cs_reading_relation('e35269d8-b8cc-4117-96df-e88089d992ab', price_formation_kernel__institutional_reading, influences).
narrative_ontology:cs_reading_relation('e35269d8-b8cc-4117-96df-e88089d992ab', price_formation_kernel__financialization_reading, influences).
narrative_ontology:cs_axiom('e35269d8-b8cc-4117-96df-e88089d992ab', foundational, land_rent_is_unearned_and_separable).
narrative_ontology:cs_axiom_status(land_rent_is_unearned_and_separable, holdable).
narrative_ontology:cs_axiom_grounding('e35269d8-b8cc-4117-96df-e88089d992ab', land_rent_is_unearned_and_separable, empirically_contingent).
narrative_ontology:cs_axiom('e35269d8-b8cc-4117-96df-e88089d992ab', foundational, socially_created_value_should_be_socially_captured).
narrative_ontology:cs_axiom_status(socially_created_value_should_be_socially_captured, holdable).
narrative_ontology:cs_axiom_grounding('e35269d8-b8cc-4117-96df-e88089d992ab', socially_created_value_should_be_socially_captured, deontological).
narrative_ontology:cs_reference_frame('e35269d8-b8cc-4117-96df-e88089d992ab', classical_rent_theory_separation).
narrative_ontology:cs_drift_state('e35269d8-b8cc-4117-96df-e88089d992ab', contemporary_financialized_housing_markets, gap(practice_drift, substantial, false)).
narrative_ontology:cs_created_at('e35269d8-b8cc-4117-96df-e88089d992ab', '').
narrative_ontology:cs_kernel_id(price_formation_kernel__georgist_reading, price_formation_kernel).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(price_formation_kernel__georgist_reading, landowners).
narrative_ontology:constraint_beneficiary(price_formation_kernel__georgist_reading, land_speculators).
narrative_ontology:constraint_beneficiary(price_formation_kernel__georgist_reading, mortgage_lenders_on_land_value).
narrative_ontology:constraint_victim(price_formation_kernel__georgist_reading, wage_laborers).
narrative_ontology:constraint_victim(price_formation_kernel__georgist_reading, tenants).
narrative_ontology:constraint_victim(price_formation_kernel__georgist_reading, productive_capital_investors).
narrative_ontology:constraint_victim(price_formation_kernel__georgist_reading, new_market_entrants).
% Derived from stakeholders[] roles (beneficiary->beneficiary, payer->victim;
% agent-gated; excluded derives nothing; deduped against the authored arrays).
narrative_ontology:constraint_beneficiary(price_formation_kernel__georgist_reading, productive_capital_investors).
narrative_ontology:constraint_vindicates(price_formation_kernel__georgist_reading, law_of_rent).
narrative_ontology:constraint_vindicates(price_formation_kernel__georgist_reading, location_value_theorem).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Hold title to fixed-supply locations and collect the price premium that accrues from surrounding public investment, population growth, and agglomeration — none of which they produced. They can sell, lease, or hold indefinitely while the site appreciates; their income requires no improvement to the parcel.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, landowners, beneficiary,
    powerful, generational, arbitrage, regional).

% Acquire land ahead of anticipated infrastructure or zoning change and hold it vacant or underused, capturing the rent gain at resale. Their return comes purely from anticipated location value, not from any labor or capital improvement to the site.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, land_speculators, beneficiary,
    organized, biographical, arbitrage, national).

% Underwrite loans against total property price without distinguishing land component from improvement component, and profit from interest on the inflated land share. Their appraisal and lending practices institutionalize the conflation of rent and earned value into a single collateral figure.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, mortgage_lenders_on_land_value, beneficiary,
    institutional, generational, arbitrage, national).
narrative_ontology:stakeholder_secondary_role(price_formation_kernel__georgist_reading, mortgage_lenders_on_land_value, agenda_setter).

% Produce the goods and services whose demand generates the location value that landowners capture, while paying rising rent or purchase prices for access to the locations near jobs and infrastructure. Their wages are effectively taxed by the land-rent premium before they see the money.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, wage_laborers, payer,
    powerless, biographical, trapped, regional).

% Pay rent that bundles a genuine cost for the physical structure with an unrelated charge for locational advantage. They cannot separate or negotiate down the land-rent portion, and relocation to escape it usually means losing access to the same amenities that make the location valuable.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, tenants, payer,
    powerless, immediate, constrained, local).

% Invest in genuine improvements — construction, equipment, business capacity — but see a share of the return siphoned off as rising site cost before any building begins. They benefit from the improvement-coordination function of price formation while bearing the land-rent tax on entry.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, productive_capital_investors, payer,
    moderate, biographical, constrained, national).
narrative_ontology:stakeholder_secondary_role(price_formation_kernel__georgist_reading, productive_capital_investors, beneficiary).

% Would build housing or businesses in high-demand locations but are priced out before construction, since the land-rent premium is capitalized into the acquisition cost. Their absence from ownership is invisible in market price data, which registers only that they didn't buy, not why.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, new_market_entrants, excluded,
    powerless, biographical, trapped, regional).

% Argue for taxing land value at close to 100% while exempting improvements entirely, to strip the extractive rent component from price formation without discouraging productive investment. They supply the analytical decomposition this reading relies on.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, georgist_land_value_tax_advocates, observer,
    organized, generational, analytical, national).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(price_formation_kernel__georgist_reading, landowners).
narrative_ontology:fixing_cost_class(price_formation_kernel__georgist_reading, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Price formation genuinely coordinates the allocation of labor and capital toward productive improvements — signaling where construction, business investment, and development effort should flow.
% TRANSFER_FUNCTION: The land-rent component transfers value created by public investment, population density, and community activity from laborers, tenants, and productive investors into the pockets of whoever holds title to the location, without those titleholders having produced the value.
% ABSENT_VOICES: Communities and public infrastructure funders who created the location value (through transit, schools, safety, agglomeration) are not compensated in the price mechanism and have no seat in the transaction; land value tax advocates represent an analytical seat but not a bargaining one.
% DISAPPEARANCE_RATIONALE: If land rent were fully captured by public taxation and stripped from private price formation (the Georgist remedy), landowners would lose the arbitrage return, land speculation would become unprofitable, housing costs would fall toward improvement-value alone, and capital would redirect toward productive investment rather than land banking — a substantial reallocation of wealth and incentive.
% FOUNDING_PROBLEM: Land is fixed in supply and its value rises from social and public investment external to the owner's effort; the founding problem this reading identifies is that price formation as currently practiced fails to distinguish this unearned component from earned improvement value, allowing passive extraction to masquerade as market return.
% FOUNDING_PROBLEM_CORROBORATION: Land value tax advocates and public-finance economists outside the landowning class (going back to Ricardo's law of rent and continuing through modern land-value-tax empirical studies in jurisdictions like Pennsylvania and Denmark) corroborate that location value is separable from improvement value and that current tax and pricing systems fail to make the separation. No landowner or lender constituency independently corroborates the problem as live — their institutional interest runs the other way.
narrative_ontology:disappearance_verdict(price_formation_kernel__georgist_reading, world_rearranges).
narrative_ontology:founding_problem_status(price_formation_kernel__georgist_reading, live).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(price_formation_kernel__georgist_reading, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet3', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(price_formation_kernel__georgist_reading, 'none', 1).
narrative_ontology:epsilon_provenance(price_formation_kernel__georgist_reading, 0.68, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(price_formation_kernel__georgist_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(price_formation_kernel__georgist_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(price_formation_kernel__georgist_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.68) reflects the rent-capture component specifically, not the improvement-coordination component — this reading holds these apart structurally even though market price data reports them as one number. Suppression (0.55) is moderate: there is no direct coercion forcing participation, but property law, zoning that restricts land supply, and the absence of any land-value-tax alternative in most jurisdictions function as structural suppression of the separation this reading proposes. Theater ratio (0.40) reflects that a meaningful share of real-estate-sector activity (appraisal, financial product design, tax policy debate) increasingly serves to obscure or defend the land/improvement conflation rather than to build anything. Accessibility collapse (0.60) is moderate-high: once a jurisdiction's tax and financial system are built around unseparated property price, alternatives (land value taxation) become politically very difficult to introduce, though not impossible — several jurisdictions have done it. Resistance (0.58) is substantial: landowner and lender constituencies actively resist land value tax proposals wherever introduced.
 *
 * PERSPECTIVAL GAP:
 *   From the landowner and lender seats, price formation looks like ordinary market function — appreciation is simply what property does, and the reading's rent/improvement separation looks like an ideological imposition. From the wage-laborer and tenant seats, the same price signal looks like an unaccountable toll on access to opportunity they did nothing to create and cannot negotiate around. The engine should compute divergent seat classifications here: beneficiary seats likely land near rope/mountain (naturalized, coordination-flavored), payer seats likely land near snare, precisely the hybrid this reading predicts.
 *
 * DIRECTIONALITY LOGIC:
 *   Landowners, speculators, and land-value lenders receive low d (near full beneficiary) because the structural data shows them capturing value created by others' activity and public investment, with maximal exit optionality (they can sell into a liquid market at will). Wage laborers and tenants receive high d (near full target): they generate the location value through their economic activity and presence, yet cannot avoid paying for access to it, and their exit options are trapped or constrained by the need to live and work somewhere. Productive capital investors sit in between — they benefit from the genuine coordination function of price formation (signaling where to build) while also paying the land-rent toll to enter, making them structurally mixed.
 *
 * MANDATROPHY ANALYSIS:
 *   This reading's hybrid classification prevents two mislabeling errors symmetric to each other: treating ALL of price formation as pure extraction (which would ignore the genuine coordination the improvement-value component performs, mislabeling productive investment as rent-seeking) and treating ALL of price formation as natural coordination (which would launder the land-rent component's extraction under the cover story of 'the market accurately pricing scarcity'). The founding problem — location value is unearned and currently uncaptured for public benefit — remains live by this reading's own corroboration chain (Ricardo through modern land-value-tax jurisdictions), which is exactly the kind of persistence-after-founding-problem-resolution pattern mandatrophy analysis is built to catch, except here the analysis concludes the arrangement HASN'T resolved its founding problem — it has instead been captured by the very party whose position the founding problem describes.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    land_value_separability,
    'Can land value be non-arbitrarily separated from improvement value in observed market prices, or is this decomposition a theoretical construct not recoverable from transaction data?',
    'Assessed land-value data from jurisdictions with split-rate taxation (e.g., parts of Pennsylvania, Denmark''s historical land value taxation) compared against hedonic pricing models that attempt to isolate location value from structure value; convergence across independent methodologies would support separability.',
    'If land value cannot be non-arbitrarily separated, this reading''s core structural claim collapses into a normative preference rather than an empirical decomposition, and the snare classification for rent capture becomes much harder to sustain against the naturalist reading. If separable, the hybrid classification (mountain/snare land component, rope improvement component) is empirically grounded rather than merely conceptual.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(land_value_separability, empirical, 'Whether land rent is empirically separable from improvement value in real transaction data.').

omega_variable(
    location_scarcity_natural_vs_constructed,
    'Is location scarcity a natural-law fact (fixed geographic supply) or is it substantially constructed by zoning and regulatory land-use restriction that this reading treats as exogenous?',
    'Compare land-rent gradients across jurisdictions with materially different zoning permissiveness at similar underlying geographic scarcity; if rent gradients track zoning restriction more than geography, scarcity is substantially constructed rather than natural.',
    'If scarcity is substantially constructed, the mountain-like framing of the land component overstates its naturalness and the whole arrangement shifts further toward being a snare with an institutional_reading explanation of its mechanism, rather than a hybrid with a genuine natural-scarcity floor.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(location_scarcity_natural_vs_constructed, conceptual, 'Whether land scarcity is exogenous/natural or endogenous/constructed by land-use policy.').

omega_variable(
    kernel_framing_underdetermination,
    'Given four declared sibling readings of the price-formation kernel, is the georgist decomposition the correct causal-primary account, or one lens among several equally valid mechanism-level accounts (institutional, financialization, naturalist)?',
    'No single resolution mechanism exists across readings by construction (each reading is ε-invariant and self-contained); however, longitudinal comparison of price formation under land-value-tax regimes vs. zoning-reform regimes vs. credit-tightening regimes could show which lever most reliably moves price, which is suggestive though not dispositive evidence about causal primacy.',
    'This does not change this reading''s own classification (each reading stands on its own structural claim), but it bears on which reading policymakers should weight most heavily when only one lever can be pulled.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(kernel_framing_underdetermination, conceptual, 'Whether the georgist decomposition is causally primary among sibling kernel readings or one valid partial account among several.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(price_formation_kernel__georgist_reading, 0, 40).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(pric_tr_t0, price_formation_kernel__georgist_reading, theater_ratio, 0, 0.25).
narrative_ontology:measurement(pric_tr_t8, price_formation_kernel__georgist_reading, theater_ratio, 8, 0.28).
narrative_ontology:measurement(pric_tr_t16, price_formation_kernel__georgist_reading, theater_ratio, 16, 0.32).
narrative_ontology:measurement(pric_tr_t24, price_formation_kernel__georgist_reading, theater_ratio, 24, 0.35).
narrative_ontology:measurement(pric_tr_t32, price_formation_kernel__georgist_reading, theater_ratio, 32, 0.38).
narrative_ontology:measurement(pric_tr_t40, price_formation_kernel__georgist_reading, theater_ratio, 40, 0.4).

% Extraction over time
narrative_ontology:measurement(pric_be_t0, price_formation_kernel__georgist_reading, base_extractiveness, 0, 0.42).
narrative_ontology:measurement(pric_be_t8, price_formation_kernel__georgist_reading, base_extractiveness, 8, 0.48).
narrative_ontology:measurement(pric_be_t16, price_formation_kernel__georgist_reading, base_extractiveness, 16, 0.55).
narrative_ontology:measurement(pric_be_t24, price_formation_kernel__georgist_reading, base_extractiveness, 24, 0.6).
narrative_ontology:measurement(pric_be_t32, price_formation_kernel__georgist_reading, base_extractiveness, 32, 0.65).
narrative_ontology:measurement(pric_be_t40, price_formation_kernel__georgist_reading, base_extractiveness, 40, 0.68).

% Suppression authored static: scalar-only by design, no temporal series
narrative_ontology:suppression_profile(price_formation_kernel__georgist_reading, static).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(price_formation_kernel__georgist_reading, resource_allocation).
narrative_ontology:boltzmann_floor_override(price_formation_kernel__georgist_reading, 0.1).
narrative_ontology:affects_constraint(price_formation_kernel__georgist_reading, naturalist_reading).
narrative_ontology:affects_constraint(price_formation_kernel__georgist_reading, institutional_reading).
narrative_ontology:affects_constraint(price_formation_kernel__georgist_reading, financialization_reading).

% DUAL FORMULATION NOTE:
% This story is one of four linked readings of the price_formation_kernel. naturalist_reading treats undivided price as reflecting objective scarcity/preference (this reading directly contests that premise by asserting a decomposable rent component). institutional_reading attributes price formation to zoning/lending/tax mechanics (largely compatible — it explains HOW this reading's rent capture is institutionally enforced). financialization_reading attributes price dynamics to credit and asset-feedback loops (compatible as an accelerant mechanism, not a substitute explanation). Each reading carries its own ε, its own beneficiary/victim structure, and its own claimed_type; none averages over the others.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
