% ============================================================================
% CONSTRAINT STORY: sacrifice_obligation_continuity__study_as_performance
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_sacrifice_obligation_continuity__study_as_performance, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:suppression_profile/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: sacrifice_obligation_continuity__study_as_performance
 *   human_readable: Study of Sacrificial Law as Fulfillment of Commandment (Talmud Torah Substitution Reading)
 *   domain: religious/legal/textual
 *
 * SUMMARY:
 *   This constraint models the study_as_performance reading of the
 *   sacrifice-obligation-continuity kernel: the position, rooted in Talmudic
 *   statements and later codified in interpretive tradition, that engaging in
 *   the study of sacrificial law (Seder Kodashim, laws of korbanot) itself
 *   constitutes fulfillment of the commandment to offer sacrifice,
 *   notwithstanding the absence of a functioning Temple. This is a
 *   low-extraction, low-suppression rope: study is broadly accessible (no
 *   scarce material resource is gatekept), practitioners are net
 *   beneficiaries (they gain standing and continuity without needing an
 *   altar), and no identifiable victim group is generated by the arrangement
 *   — the obligation is read as SATISFIED, not suspended or breached. This
 *   story generates ONLY the study_as_performance reading per Rule 1; the
 *   sibling readings (performance_only, messianic_suspension,
 *   archival_preservation) are separate constraints with their own ε values
 *   and are not described here beyond identifying them as siblings in the
 *   kernel contest.
 *
 * KEY AGENTS:
 *   - torah_study_practitioners: primary beneficiary (moderate/mobile) — discharges obligation through study
 *   - yeshiva_institutions: agenda_setter (institutional/mobile) — curates and transmits the doctrine
 *   - diaspora_communities_without_temple_access: beneficiary (organized/mobile) — obligation becomes practicable without Temple access
 *   - rabbinic_interpretive_authority: agenda_setter/beneficiary (institutional/arbitrage) — adjudicates and is reinforced by the reading
 *   - advocates_of_sibling_readings: excluded (organized/mobile) — hold competing kernel-readings, not parties within this one
 *   - textual_tradition_analysts: observer (analytical) — sees the structural function across readings
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(sacrifice_obligation_continuity__study_as_performance, 0.08).
domain_priors:suppression_score(sacrifice_obligation_continuity__study_as_performance, 0.12).
domain_priors:theater_ratio(sacrifice_obligation_continuity__study_as_performance, 0.15).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(sacrifice_obligation_continuity__study_as_performance, extractiveness, 0.08).
narrative_ontology:constraint_metric(sacrifice_obligation_continuity__study_as_performance, suppression_requirement, 0.12).
narrative_ontology:constraint_metric(sacrifice_obligation_continuity__study_as_performance, theater_ratio, 0.15).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(sacrifice_obligation_continuity__study_as_performance, accessibility_collapse, 0.2).
narrative_ontology:constraint_metric(sacrifice_obligation_continuity__study_as_performance, resistance, 0.25).

% --- Constraint claim ---
narrative_ontology:constraint_claim(sacrifice_obligation_continuity__study_as_performance, rope).
narrative_ontology:human_readable(sacrifice_obligation_continuity__study_as_performance, "Study of Sacrificial Law as Fulfillment of Commandment (Talmud Torah Substitution Reading)").
narrative_ontology:topic_domain(sacrifice_obligation_continuity__study_as_performance, "religious/legal/textual").

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(sacrifice_obligation_continuity__study_as_performance, '733f2fd3-c00a-4953-a50a-db350f81c804').
narrative_ontology:cs_kernel_codification('733f2fd3-c00a-4953-a50a-db350f81c804', fixed_text).
narrative_ontology:cs_authority_grounding('733f2fd3-c00a-4953-a50a-db350f81c804', lineage).
narrative_ontology:cs_interpretation_layer_present('733f2fd3-c00a-4953-a50a-db350f81c804').
narrative_ontology:cs_reading_relation('733f2fd3-c00a-4953-a50a-db350f81c804', sacrifice_obligation_continuity__performance_only, forecloses).
narrative_ontology:cs_reading_relation('733f2fd3-c00a-4953-a50a-db350f81c804', sacrifice_obligation_continuity__messianic_suspension, coexists_with).
narrative_ontology:cs_reading_relation('733f2fd3-c00a-4953-a50a-db350f81c804', sacrifice_obligation_continuity__archival_preservation, influences).
narrative_ontology:cs_axiom('733f2fd3-c00a-4953-a50a-db350f81c804', foundational, study_constitutes_fulfillment).
narrative_ontology:cs_axiom_status(study_constitutes_fulfillment, holdable).
narrative_ontology:cs_axiom_grounding('733f2fd3-c00a-4953-a50a-db350f81c804', study_constitutes_fulfillment, conventional).
narrative_ontology:cs_axiom('733f2fd3-c00a-4953-a50a-db350f81c804', secondary, obligation_currently_satisfied_not_suspended).
narrative_ontology:cs_axiom_status(obligation_currently_satisfied_not_suspended, holdable).
narrative_ontology:cs_axiom_grounding('733f2fd3-c00a-4953-a50a-db350f81c804', obligation_currently_satisfied_not_suspended, conventional).
narrative_ontology:cs_reference_frame('733f2fd3-c00a-4953-a50a-db350f81c804', temple_era_sacrificial_performance).
narrative_ontology:cs_drift_state('733f2fd3-c00a-4953-a50a-db350f81c804', post_destruction_rabbinic_consolidation, gap(practice_drift, substantial, true)).
narrative_ontology:cs_created_at('733f2fd3-c00a-4953-a50a-db350f81c804', '').
narrative_ontology:cs_kernel_id(sacrifice_obligation_continuity__study_as_performance, sacrifice_obligation_continuity).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(sacrifice_obligation_continuity__study_as_performance, torah_study_practitioners).
narrative_ontology:constraint_beneficiary(sacrifice_obligation_continuity__study_as_performance, yeshiva_institutions).
narrative_ontology:constraint_beneficiary(sacrifice_obligation_continuity__study_as_performance, diaspora_communities_without_temple_access).
narrative_ontology:constraint_beneficiary(sacrifice_obligation_continuity__study_as_performance, rabbinic_interpretive_authority).
narrative_ontology:constraint_vindicates(sacrifice_obligation_continuity__study_as_performance, study_equals_performance_doctrine).
narrative_ontology:constraint_vindicates(sacrifice_obligation_continuity__study_as_performance, textual_engagement_satisfies_commandment).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Engage in structured textual study of sacrificial law (Seder Kodashim and related tractates) as a devotional and legal practice. Under this reading, that study itself discharges the obligation to engage with sacrifice law — no altar, no Temple, no physical performance required. They gain full religious standing and a sense of unbroken continuity with the commandment without needing access to any restored cultic apparatus.
narrative_ontology:constraint_stakeholder(sacrifice_obligation_continuity__study_as_performance, torah_study_practitioners, beneficiary,
    moderate, biographical, mobile, global).

% Curricular bodies that structure and transmit the study-as-performance reading, allocating scholarly time to sacrificial tractates despite their inapplicability in practice. They set which interpretive tradition is taught as authoritative, shaping how students and communities relate to the underlying obligation.
narrative_ontology:constraint_stakeholder(sacrifice_obligation_continuity__study_as_performance, yeshiva_institutions, agenda_setter,
    institutional, generational, mobile, global).

% Communities that have had no access to sacrificial performance for nearly two millennia. This reading resolves what would otherwise be a standing unfulfillable obligation into something practicable in ordinary communal and educational life — study halls, not altars, become the site of fulfillment.
narrative_ontology:constraint_stakeholder(sacrifice_obligation_continuity__study_as_performance, diaspora_communities_without_temple_access, beneficiary,
    organized, generational, mobile, global).

% The interpretive tradition (grounded in Talmudic sources treating study of sacrificial law as equivalent to offering) that adjudicates what counts as fulfillment. This authority both sets the reading and benefits from it: its interpretive centrality is reinforced every time study substitutes for performance, since study requires precisely the scholarly mediation this authority provides.
narrative_ontology:constraint_stakeholder(sacrifice_obligation_continuity__study_as_performance, rabbinic_interpretive_authority, agenda_setter,
    institutional, civilizational, arbitrage, global).
narrative_ontology:stakeholder_secondary_role(sacrifice_obligation_continuity__study_as_performance, rabbinic_interpretive_authority, beneficiary).

% Communities and scholars holding that sacrifice requires physical performance (performance_only), that the obligation is merely suspended pending restoration (messianic_suspension), or that the law is no longer binding at all (archival_preservation). They are not part of this reading's own framework and do not appear as parties within it, though they contest its conclusion from outside.
narrative_ontology:constraint_stakeholder(sacrifice_obligation_continuity__study_as_performance, advocates_of_sibling_readings, excluded,
    organized, generational, mobile, global).

% Scholars of religious law and ritual studies who examine how the study-as-performance doctrine functions structurally — as a mechanism that keeps an otherwise-suspended legal category alive and communally meaningful without material infrastructure.
narrative_ontology:constraint_stakeholder(sacrifice_obligation_continuity__study_as_performance, textual_tradition_analysts, observer,
    analytical, civilizational, analytical, global).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Provides a way for a legal obligation whose material precondition (a functioning Temple and altar) has been absent for centuries to remain a live, satisfiable commandment rather than becoming either permanently violated or theoretically suspended. Study substitutes for performance, letting communities coordinate around a shared practice of textual engagement instead of a shared impossibility.
% TRANSFER_FUNCTION: Moves religious standing and a sense of commandment-fulfillment from the domain of physical cultic performance to the domain of scholarly and communal study; no material resource is extracted from any party — the shift is normative/interpretive, not economic.
% ABSENT_VOICES: Adherents of the performance_only and messianic_suspension readings would object that no amount of study discharges an obligation whose content is physical offering; they hold that the obligation remains outstanding (suspended or unfulfilled) rather than satisfied. They are structurally outside this reading's own framework, not silenced within it — they simply hold a different kernel-reading and are not parties to this constraint's operation.
% DISAPPEARANCE_RATIONALE: If the study-as-performance doctrine disappeared, study of sacrificial law would not stop (it has independent scholarly and educational value), but its status would shift: for adherents it would revert to unfulfilled or suspended obligation, which some traditions hold produces real theological and communal consequences (a sense of the commandment going undischarged) while others (secular or archival readers) would see no change at all. Whether the world 'rearranges' depends entirely on which reading one already holds — hence contested rather than a clean verdict.
% FOUNDING_PROBLEM: The destruction of the Second Temple eliminated the physical site and apparatus required for sacrificial performance, creating an apparent permanent breach in a category of commandment that the tradition needed to resolve — either by declaring the obligation defunct, suspended, or satisfiable by another means.
% FOUNDING_PROBLEM_CORROBORATION: Talmudic sources themselves (e.g., statements equating study of sacrificial halakhah with the offering) are cited by the tradition's own beneficiaries as corroboration, which is an internal source. Outside the beneficiary set, comparative religion scholars and historians of Second Temple Judaism corroborate that the doctrine emerged specifically as a documented post-destruction adaptation — supporting that the founding problem (loss of the Temple) is real and historically dated — but these outside scholars do not corroborate the theological claim that study actually discharges the obligation; that claim has no corroboration from outside the traditions that hold it.
narrative_ontology:disappearance_verdict(sacrifice_obligation_continuity__study_as_performance, contested).
narrative_ontology:founding_problem_status(sacrifice_obligation_continuity__study_as_performance, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(sacrifice_obligation_continuity__study_as_performance, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet3', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(sacrifice_obligation_continuity__study_as_performance, 'none', 1).
narrative_ontology:epsilon_provenance(sacrifice_obligation_continuity__study_as_performance, 0.08, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(sacrifice_obligation_continuity__study_as_performance_tests).
:- end_tests(sacrifice_obligation_continuity__study_as_performance_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is authored low (0.08) because study, unlike Temple access, land, or ritual office, is not a scarce or gatekept resource in the same way — a substantial share of the population historically able to engage in text study benefits from the doctrine without paying a corresponding cost through the same structure. Suppression is low (0.12): no coercive apparatus forces the study-as-performance reading on dissenters; the sibling readings persist as live alternatives held by other communities. Accessibility collapse is modest (0.2) — study requires literacy and community infrastructure (yeshiva access), which is a real but not severe barrier, and has expanded over the interval as literacy and printed/digital text access spread. Resistance (0.25) reflects genuine, ongoing theological contestation from performance_only and messianic_suspension adherents, without rising to active suppression of either side.
 *
 * PERSPECTIVAL GAP:
 *   From the practitioner and institutional seats, this reading closes a two-thousand-year-old normative gap and lets an unfulfillable commandment become livable; from the seat of a performance_only or messianic_suspension adherent (structurally excluded from this constraint, since they hold a different kernel-reading), the same practice would be seen as substituting scholarship for obligation, not discharging it. The engine only computes seats within THIS reading's own stakeholder set; the sibling perspective is represented by the excluded stakeholder entry and by omega variables, not by importing their metrics here.
 *
 * DIRECTIONALITY LOGIC:
 *   All named parties within this reading sit near the beneficiary end of directionality: torah_study_practitioners and diaspora_communities gain religious standing and communal coherence at negligible cost; yeshiva_institutions and rabbinic_interpretive_authority gain curricular and interpretive centrality. No victim group is declared because, by this reading's own terms, the obligation is genuinely satisfied — there is no one paying an extraction cost through the study structure. This is a structural feature of the reading, not an oversight: the sibling readings (performance_only, messianic_suspension) would generate a different beneficiary/victim topology (e.g., a standing sense of unfulfilled obligation for those who reject substitution), but that topology belongs to those other constraint stories.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem (loss of Temple access) is real and dated, but its status is contested rather than resolved cleanly: this reading holds the problem is fully addressed (study = fulfillment, no residual mandate), which prevents mislabeling the doctrine as either pure legacy theater (a piton with no live function) or pure extraction (a snare with victims). Because study genuinely occupies communal, educational, and identity-forming roles independent of the sacrificial-law question, and because no coercive machinery compels the reading on outsiders, mandatrophy is not declared here — the arrangement's coordination function (giving a stranded obligation a livable form) remains active and voluntarily adopted rather than merely inertial.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    study_as_performance_vs_sibling_readings_location,
    'Where precisely does the disagreement between study_as_performance and its sibling readings (performance_only, messianic_suspension, archival_preservation) live — is it a dispute about the CONTENT of the commandment (what counts as ''offering''), or about the STATUS of the obligation (satisfied vs. suspended vs. defunct)?',
    'Close textual analysis of the specific Talmudic and later halakhic sources each reading cites, tracing whether the disagreement is exegetical (different readings of the same proof-texts) or doctrinal (different underlying theories of what commandments require).',
    'If the disagreement is exegetical, the four readings could in principle converge through further textual scholarship; if doctrinal, they represent stable, permanently coexisting positions — this affects whether the kernel is better modeled as heading toward resolution or as a genuine, standing four-way fork.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(study_as_performance_vs_sibling_readings_location, conceptual, 'Locating the structural disagreement among sibling readings of the sacrifice-obligation kernel.').

omega_variable(
    sibling_reading_structural_delta,
    'What would the beneficiary/victim structure look like for the performance_only and messianic_suspension siblings, where the obligation is NOT treated as satisfied by study?',
    'Author the sibling constraint stories (performance_only, messianic_suspension, archival_preservation) independently and compare their beneficiary/victim declarations and ε values against this one, per the ε-invariance decomposition principle.',
    'If the sibling readings generate a victim group (e.g., communities experiencing chronic unfulfilled-obligation distress, or messianic movements whose urgency is dampened by ''readiness'' framings that never resolve), the kernel as a whole shows real structural stakes beyond this reading''s own low-extraction profile — this reading''s low ε would then be understood as one low-extraction branch of a kernel that is NOT uniformly low-extraction across readings.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(sibling_reading_structural_delta, empirical, 'How ε and victim structure differ across sibling readings of the same kernel.').

omega_variable(
    study_as_performance_naturalness_or_construction,
    'Is the equivalence ''study = fulfillment'' a genuine, organically emergent interpretive development from within the tradition''s own logic, or was it partly shaped by the practical needs of diaspora communities and scholarly institutions that benefit from a framework requiring no material infrastructure and centering textual authority?',
    'Historical-critical analysis of when and in what political/social circumstances the study-equals-offering statements were first emphasized as normatively load-bearing (versus existing merely as homiletical asides), and whether their prominence correlates with periods of rabbinic institution-building.',
    'If substantially institutionally shaped, the doctrine''s low-extraction, purely-coordinative character would need qualification — it would still lack a clear victim group, but its selection over sibling readings would be partly explained by whose institutional interests it serves (yeshiva_institutions, rabbinic_interpretive_authority) rather than purely by textual necessity.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(study_as_performance_naturalness_or_construction, conceptual, 'Whether the reading''s dominance reflects textual necessity or institutional convenience.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(sacrifice_obligation_continuity__study_as_performance, 0, 1900).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(sacr_tr_t0, sacrifice_obligation_continuity__study_as_performance, theater_ratio, 0, 0.1).
narrative_ontology:measurement(sacr_tr_t300, sacrifice_obligation_continuity__study_as_performance, theater_ratio, 300, 0.11).
narrative_ontology:measurement(sacr_tr_t700, sacrifice_obligation_continuity__study_as_performance, theater_ratio, 700, 0.13).
narrative_ontology:measurement(sacr_tr_t1100, sacrifice_obligation_continuity__study_as_performance, theater_ratio, 1100, 0.14).
narrative_ontology:measurement(sacr_tr_t1500, sacrifice_obligation_continuity__study_as_performance, theater_ratio, 1500, 0.15).
narrative_ontology:measurement(sacr_tr_t1900, sacrifice_obligation_continuity__study_as_performance, theater_ratio, 1900, 0.15).

% Extraction over time
narrative_ontology:measurement(sacr_be_t0, sacrifice_obligation_continuity__study_as_performance, base_extractiveness, 0, 0.05).
narrative_ontology:measurement(sacr_be_t300, sacrifice_obligation_continuity__study_as_performance, base_extractiveness, 300, 0.06).
narrative_ontology:measurement(sacr_be_t700, sacrifice_obligation_continuity__study_as_performance, base_extractiveness, 700, 0.07).
narrative_ontology:measurement(sacr_be_t1100, sacrifice_obligation_continuity__study_as_performance, base_extractiveness, 1100, 0.07).
narrative_ontology:measurement(sacr_be_t1500, sacrifice_obligation_continuity__study_as_performance, base_extractiveness, 1500, 0.08).
narrative_ontology:measurement(sacr_be_t1900, sacrifice_obligation_continuity__study_as_performance, base_extractiveness, 1900, 0.08).

% Suppression authored static: scalar-only by design, no temporal series
narrative_ontology:suppression_profile(sacrifice_obligation_continuity__study_as_performance, static).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */


/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
