% ============================================================================
% CONSTRAINT STORY: substance_control_kernel__prohibition_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-15
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_substance_control_kernel__prohibition_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: substance_control_kernel__prohibition_reading
 *   human_readable: Prohibition Reading of Substance Control: Moral Transgression Requiring State Punishment
 *   domain: criminal_justice/public_health/political_economy
 *
 * SUMMARY:
 *   This constraint instantiates the prohibition reading of the substance
 *   control kernel: substance use is framed as a moral transgression that
 *   threatens social order and therefore warrants state punishment. Under
 *   this reading, users are structurally reclassified as criminal offenders
 *   rather than patients or free actors, and a durable enforcement,
 *   corrections, and forfeiture apparatus becomes the primary institutional
 *   beneficiary of continued criminalization. Black-market violence is a
 *   secondary externality generated by the price premium enforcement creates,
 *   borne mostly by bystanders uninvolved in either use or distribution. This
 *   is a distinct constraint from the harm_reduction_reading (which treats
 *   use as a health condition warranting pragmatic intervention) and the
 *   legalization_reading (which treats use as a liberty matter bounded by
 *   third-party harm) — each reading produces a different victim set, a
 *   different beneficiary structure, and a different ε, and each is authored
 *   as its own constraint story per the ε-invariance principle.
 *
 * KEY AGENTS:
 *   - law_enforcement_agencies: primary agenda_setter and beneficiary (institutional/arbitrage) — administers enforcement and captures budget/forfeiture rents
 *   - substance_users: primary target (powerless/trapped) — bears criminal liability and collateral consequences
 *   - private_prison_operators: secondary institutional beneficiary (organized/arbitrage) — captures incarceration revenue
 *   - racial_minority_communities: disproportionately burdened victim class (powerless/trapped, generational) — bears enforcement intensity asymmetry
 *   - harm_reduction_advocates: excluded voice (moderate/constrained) — argues for a different reading, structurally sidelined from enforcement policy setting
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(substance_control_kernel__prohibition_reading, 0.81).
domain_priors:suppression_score(substance_control_kernel__prohibition_reading, 0.87).
domain_priors:theater_ratio(substance_control_kernel__prohibition_reading, 0.42).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(substance_control_kernel__prohibition_reading, extractiveness, 0.81).
narrative_ontology:constraint_metric(substance_control_kernel__prohibition_reading, suppression_requirement, 0.87).
narrative_ontology:constraint_metric(substance_control_kernel__prohibition_reading, theater_ratio, 0.42).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(substance_control_kernel__prohibition_reading, accessibility_collapse, 0.38).
narrative_ontology:constraint_metric(substance_control_kernel__prohibition_reading, resistance, 0.72).

% --- Constraint claim ---
narrative_ontology:constraint_claim(substance_control_kernel__prohibition_reading, tangled_rope).
narrative_ontology:human_readable(substance_control_kernel__prohibition_reading, "Prohibition Reading of Substance Control: Moral Transgression Requiring State Punishment").
narrative_ontology:topic_domain(substance_control_kernel__prohibition_reading, "criminal_justice/public_health/political_economy").

domain_priors:requires_active_enforcement(substance_control_kernel__prohibition_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(substance_control_kernel__prohibition_reading, 'c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db').
narrative_ontology:cs_kernel_codification('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', distributed).
narrative_ontology:cs_authority_grounding('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', extraction).
narrative_ontology:cs_interpretation_layer_present('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db').
narrative_ontology:cs_reading_relation('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', substance_control_kernel__harm_reduction_reading, coexists_with).
narrative_ontology:cs_reading_relation('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', substance_control_kernel__legalization_reading, influences).
narrative_ontology:cs_axiom('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', foundational, substance_use_is_moral_transgression_against_social_order).
narrative_ontology:cs_axiom_status(substance_use_is_moral_transgression_against_social_order, holdable).
narrative_ontology:cs_axiom_grounding('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', substance_use_is_moral_transgression_against_social_order, deontological).
narrative_ontology:cs_axiom('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', foundational, state_punishment_is_necessary_and_proportionate_response_to_use).
narrative_ontology:cs_axiom_status(state_punishment_is_necessary_and_proportionate_response_to_use, holdable).
narrative_ontology:cs_axiom_grounding('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', state_punishment_is_necessary_and_proportionate_response_to_use, instrumental).
narrative_ontology:cs_reference_frame('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', criminalization_as_moral_order_enforcement).
narrative_ontology:cs_drift_state('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', contemporary_post_mass_incarceration_era, gap(axiom_overriding, substantial, false)).
narrative_ontology:cs_created_at('c7b5650e-ab96-411f-8a1a-e4ebe7f6c6db', '').
narrative_ontology:cs_kernel_id(substance_control_kernel__prohibition_reading, substance_control_kernel).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(substance_control_kernel__prohibition_reading, law_enforcement_agencies).
narrative_ontology:constraint_beneficiary(substance_control_kernel__prohibition_reading, private_prison_operators).
narrative_ontology:constraint_beneficiary(substance_control_kernel__prohibition_reading, asset_forfeiture_units).
narrative_ontology:constraint_beneficiary(substance_control_kernel__prohibition_reading, drug_testing_industry).
narrative_ontology:constraint_beneficiary(substance_control_kernel__prohibition_reading, politicians_running_on_order_platforms).
narrative_ontology:constraint_victim(substance_control_kernel__prohibition_reading, substance_users).
narrative_ontology:constraint_victim(substance_control_kernel__prohibition_reading, low_income_defendants).
narrative_ontology:constraint_victim(substance_control_kernel__prohibition_reading, racial_minority_communities).
narrative_ontology:constraint_victim(substance_control_kernel__prohibition_reading, families_of_incarcerated_users).
narrative_ontology:constraint_victim(substance_control_kernel__prohibition_reading, black_market_violence_bystanders).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Administers drug enforcement, sets operational priorities within statutory limits, receives budget allocations, equipment grants, and asset forfeiture proceeds tied directly to enforcement volume. Frames continued criminalization as protecting communities from moral and social decay; the framing also justifies the agency's budget growth and headcount.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, law_enforcement_agencies, agenda_setter,
    institutional, generational, arbitrage, national).
narrative_ontology:stakeholder_secondary_role(substance_control_kernel__prohibition_reading, law_enforcement_agencies, beneficiary).

% Contracts with state and federal corrections systems are priced per-bed and per-day; a substantial share of the incarcerated population is present on drug possession or distribution convictions. Lobbies against decriminalization measures through trade associations and campaign contributions.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, private_prison_operators, beneficiary,
    organized, biographical, arbitrage, national).

% Seizes cash, vehicles, and property in connection with drug enforcement actions, often without conviction, and retains a share of proceeds for departmental budgets. Has a direct financial stake in maintaining criminalized status regardless of public-health outcomes.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, asset_forfeiture_units, beneficiary,
    institutional, biographical, arbitrage, national).

% Faces arrest, prosecution, and incarceration for possession or use; a criminal record forecloses employment, housing, and financial access afterward. Cannot exit the constraint by changing behavior alone once caught in the system — collateral consequences persist independent of subsequent sobriety.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, substance_users, payer,
    powerless, biographical, trapped, local).

% Lacks resources for private counsel, cannot make bail, and accepts plea deals under coercive time pressure regardless of the underlying facts. Bears the process costs of prohibition disproportionately relative to wealthier defendants who can litigate or divert into treatment programs.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, low_income_defendants, payer,
    powerless, biographical, trapped, local).

% Subject to enforcement intensity disproportionate to usage rates relative to other populations, documented across multiple jurisdictions and decades. Community-level effects include disrupted family structures, reduced political participation from felony disenfranchisement, and diminished trust in state institutions.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, racial_minority_communities, payer,
    powerless, generational, trapped, national).

% Loses household income and caregiving capacity when a member is incarcerated for a drug offense; bears the emotional and financial cost of an extraction the family did not choose and cannot exit while the member is detained.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, families_of_incarcerated_users, payer,
    powerless, biographical, trapped, local).

% Lives in neighborhoods where prohibition-driven price premiums fund armed distribution networks; experiences violence as a side effect of a market structure created by criminalization, without having participated in substance use or distribution themselves.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, black_market_violence_bystanders, payer,
    powerless, immediate, trapped, local).

% Campaigns on tough-on-crime and moral-order platforms, using visible enforcement activity as an electoral asset. Bears little of the downstream cost of incarceration or black-market violence and can pivot rhetoric as public opinion shifts without personal exposure to the system's costs.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, politicians_running_on_order_platforms, beneficiary,
    powerful, biographical, mobile, national).

% Argues that punitive framing worsens health outcomes and drives users away from services that could reduce overdose deaths and disease transmission. Their evidence base is frequently cited in policy debate but rarely determines the enforcement posture, which remains set by legislatures and prosecutorial discretion.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, harm_reduction_advocates, excluded,
    moderate, generational, constrained, national).

% Sells testing services to employers, courts, and probation systems whose demand is generated directly by the criminalization regime and its associated compliance mandates; revenue scales with the scope of the punitive apparatus rather than with any independent health outcome.
narrative_ontology:constraint_stakeholder(substance_control_kernel__prohibition_reading, drug_testing_industry, beneficiary,
    organized, biographical, arbitrage, national).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(substance_control_kernel__prohibition_reading, law_enforcement_agencies).
narrative_ontology:fixing_cost_class(substance_control_kernel__prohibition_reading, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Provides a shared moral and legal standard against substance use that some communities and institutions genuinely want enforced, and generates a visible signal of social order that certain constituencies value independent of health outcomes.
% TRANSFER_FUNCTION: Moves liberty, income, and family stability from substance users and their households to enforcement agencies, corrections contractors, forfeiture units, and testing firms, and moves political capital to officials who campaign on the enforcement posture.
% ABSENT_VOICES: Substance users themselves rarely testify in the legislative process that sets penalties; harm reduction researchers and public health epidemiologists are frequently excluded from criminal-justice policy committees in favor of law enforcement testimony; formerly incarcerated people are excluded from most professional licensing boards that could otherwise employ them.
% DISAPPEARANCE_RATIONALE: If criminal punishment for substance use vanished overnight, incarcerated populations would drop sharply, corrections budgets and forfeiture revenue streams would need replacement, drug-market violence tied to enforcement-driven price premiums would likely fall as markets normalized, and millions of people with existing records would face a different (though not eliminated) barrier landscape. The enforcement apparatus itself would need to reorganize around a different mandate or shrink.
% FOUNDING_PROBLEM: Early-to-mid twentieth century policy sought to suppress substances viewed as morally corrosive and socially destabilizing, framing use as a threat to public order requiring state punishment rather than treatment.
% FOUNDING_PROBLEM_CORROBORATION: Law enforcement leadership and some legislators attest the moral-order problem remains live and requires continued punitive enforcement. Independent criminologists, public health researchers, and multiple government commissions (including the 1972 Shafer Commission and subsequent drug policy review bodies) attest the founding moral-threat framing has been substantially undermined by evidence that punitive enforcement does not reduce use rates and instead generates the black-market violence and incarceration costs now observed — corroboration from outside the benefiting enforcement and corrections institutions supports the dead/shifted-function reading.
narrative_ontology:disappearance_verdict(substance_control_kernel__prohibition_reading, world_rearranges).
narrative_ontology:founding_problem_status(substance_control_kernel__prohibition_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(substance_control_kernel__prohibition_reading, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_sonnet3', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(substance_control_kernel__prohibition_reading, 'none', 1).
narrative_ontology:epsilon_provenance(substance_control_kernel__prohibition_reading, 0.81, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(substance_control_kernel__prohibition_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(substance_control_kernel__prohibition_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(substance_control_kernel__prohibition_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is high (0.81 at interval end) because the constraint moves liberty and income from a powerless, trapped population to institutional actors whose budgets and revenue scale directly with enforcement volume — this is not incidental cost but a structural transfer. Suppression is even higher (0.87) because the constraint's persistence depends on active criminal enforcement, asset seizure, and incarceration infrastructure, not on voluntary compliance. Accessibility collapse is comparatively low (0.38) because genuine policy alternatives (decriminalization, harm reduction, legalization) are visibly live in public debate and adopted in some jurisdictions — the constraint has not achieved the near-total alternative foreclosure a mountain would show. Resistance is substantial (0.72), reflecting decades of organized advocacy, litigation, and jurisdictional reform pressure against the punitive framing.
 *
 * PERSPECTIVAL GAP:
 *   From the enforcement-agency seat, this reading is a legitimate exercise of coercive state authority protecting social order — a rope defending a real moral consensus. From the substance-user and affected-community seats, the identical structure operates as extraction: criminal liability imposed on behavior that in the sibling readings would be treated as a health condition or a liberty matter. The engine computes this divergence from the declared power/exit/beneficiary structure; the claimed_type of tangled_rope reflects the authoring seat's judgment that both a genuine (if contested) coordination function and asymmetric extraction are structurally present, requiring active enforcement to hold — not a reconciliation of the metrics to the claim.
 *
 * DIRECTIONALITY LOGIC:
 *   Law enforcement agencies, private prison operators, forfeiture units, and the drug testing industry sit near the beneficiary end of directionality: their revenue and institutional mandate scale with enforcement volume, and their exit options are arbitrage-grade (they can redirect resources but rarely bear personal cost from the regime they administer). Substance users, low-income defendants, and affected communities sit near the full-target end: trapped exit options, powerless structural position, and direct bearing of the criminal liability the constraint imposes. Politicians benefit electorally while bearing almost none of the downstream cost, which is why their exit options are coded mobile rather than arbitrage-grade — they can shift rhetoric but do not extract direct institutional revenue the way agencies and contractors do.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem — a perceived moral threat requiring punitive suppression — is contested rather than settled dead or clearly live: enforcement leadership maintains the moral-threat framing is still operative, while multiple government commissions and independent researchers have found punitive enforcement does not reduce use rates and instead generates the incarceration and black-market violence costs now observed externally. This mismatch (contested founding problem status against a disappearance_verdict of world_rearranges) is exactly the signal the mandatrophy check exists to surface: an arrangement whose original justification is empirically undermined but whose institutional beneficiaries have strong incentive to maintain the original framing regardless.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    moral_consensus_vs_manufactured_consensus,
    'Is the moral-transgression framing a genuine, durable social consensus that the state is enforcing on behalf of a real coordination demand, or is it a framing actively manufactured and sustained by the institutions (enforcement agencies, private prisons, forfeiture units) that profit from its persistence?',
    'Comparative analysis of public opinion polling on substance-use framing across jurisdictions that have decriminalized versus those that have not, cross-referenced with lobbying expenditure and campaign contribution data from enforcement-adjacent industries in maintaining punitive statutes.',
    'If the moral consensus is substantially manufactured/sustained by beneficiary lobbying rather than organic public demand, the coordination function claimed for this reading is weaker than authored and the constraint tilts further toward snare; if the moral consensus is genuinely broad-based and independent of institutional lobbying, the tangled_rope classification (real coordination plus extraction) is better supported.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(moral_consensus_vs_manufactured_consensus, conceptual, 'Whether the prohibition reading''s moral-order coordination claim is organic or institutionally manufactured.').

omega_variable(
    kernel_reading_selection_mechanism,
    'What structural or political mechanism determines which reading of the substance_control_kernel (prohibition, harm_reduction, legalization) a given jurisdiction adopts at a given time, and how much of that selection is path-dependent on prior enforcement infrastructure investment rather than fresh evaluation of outcomes?',
    'Longitudinal comparative policy analysis tracking jurisdictions that have shifted between readings (e.g., cannabis decriminalization/legalization waves, Portugal''s 2001 decriminalization) and the sunk-infrastructure factors present or absent at the point of transition.',
    'If reading selection is strongly path-dependent on existing enforcement infrastructure (sunk cost lock-in), this supports treating the prohibition reading''s persistence as partly inertial/institutional rather than purely a live moral judgment being freshly re-affirmed; this would strengthen a piton-adjacent reading of the enforcement apparatus specifically, distinct from the tangled_rope reading of the constraint as a whole.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(kernel_reading_selection_mechanism, empirical, 'Whether jurisdictional reading-selection is driven by fresh evaluation or infrastructure lock-in.').

omega_variable(
    racial_disparity_intent_vs_effect,
    'Is the disproportionate enforcement burden on racial minority communities a designed feature of the prohibition reading''s operation, or an unintended structural effect of otherwise race-neutral enforcement priorities interacting with pre-existing socioeconomic geography?',
    'Historical legislative record analysis (statements of intent at time of key statute passage) combined with statistical analysis of enforcement patterns controlling for usage-rate parity across demographic groups.',
    'If disparate impact is traceable to demonstrable discriminatory intent in the reading''s historical construction, this strengthens the snare-adjacent extraction reading for that specific victim class; if it is a structural effect without traceable intent, the tangled_rope classification''s coordination-function claim survives more intact for that population, though the harm remains equally real.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(racial_disparity_intent_vs_effect, empirical, 'Whether racially disparate enforcement outcomes reflect designed intent or structural effect.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(substance_control_kernel__prohibition_reading, 0, 50).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(subs_tr_t0, substance_control_kernel__prohibition_reading, theater_ratio, 0, 0.2).
narrative_ontology:measurement(subs_tr_t10, substance_control_kernel__prohibition_reading, theater_ratio, 10, 0.26).
narrative_ontology:measurement(subs_tr_t20, substance_control_kernel__prohibition_reading, theater_ratio, 20, 0.31).
narrative_ontology:measurement(subs_tr_t30, substance_control_kernel__prohibition_reading, theater_ratio, 30, 0.36).
narrative_ontology:measurement(subs_tr_t40, substance_control_kernel__prohibition_reading, theater_ratio, 40, 0.4).
narrative_ontology:measurement(subs_tr_t50, substance_control_kernel__prohibition_reading, theater_ratio, 50, 0.42).

% Extraction over time
narrative_ontology:measurement(subs_be_t0, substance_control_kernel__prohibition_reading, base_extractiveness, 0, 0.55).
narrative_ontology:measurement(subs_be_t10, substance_control_kernel__prohibition_reading, base_extractiveness, 10, 0.63).
narrative_ontology:measurement(subs_be_t20, substance_control_kernel__prohibition_reading, base_extractiveness, 20, 0.7).
narrative_ontology:measurement(subs_be_t30, substance_control_kernel__prohibition_reading, base_extractiveness, 30, 0.76).
narrative_ontology:measurement(subs_be_t40, substance_control_kernel__prohibition_reading, base_extractiveness, 40, 0.79).
narrative_ontology:measurement(subs_be_t50, substance_control_kernel__prohibition_reading, base_extractiveness, 50, 0.81).

% Suppression requirement over time
narrative_ontology:measurement(subs_su_t0, substance_control_kernel__prohibition_reading, suppression_requirement, 0, 0.62).
narrative_ontology:measurement(subs_su_t10, substance_control_kernel__prohibition_reading, suppression_requirement, 10, 0.7).
narrative_ontology:measurement(subs_su_t20, substance_control_kernel__prohibition_reading, suppression_requirement, 20, 0.77).
narrative_ontology:measurement(subs_su_t30, substance_control_kernel__prohibition_reading, suppression_requirement, 30, 0.82).
narrative_ontology:measurement(subs_su_t40, substance_control_kernel__prohibition_reading, suppression_requirement, 40, 0.85).
narrative_ontology:measurement(subs_su_t50, substance_control_kernel__prohibition_reading, suppression_requirement, 50, 0.87).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(substance_control_kernel__prohibition_reading, enforcement_mechanism).
narrative_ontology:affects_constraint(substance_control_kernel__prohibition_reading, substance_control_kernel__harm_reduction_reading).
narrative_ontology:affects_constraint(substance_control_kernel__prohibition_reading, substance_control_kernel__legalization_reading).

% DUAL FORMULATION NOTE:
% This constraint is one of three sibling readings of the substance_control_kernel, decomposed per the ε-invariance principle because the natural-language concept 'drug policy' or 'the state's stance toward substance use' conflates structurally distinct claims with different ε values, different beneficiary/victim structures, and different classifications. The prohibition_reading authors ε=0.81 (substantially extractive, tangled_rope) because users are criminalized and an enforcement/corrections apparatus becomes a concentrated institutional beneficiary. The harm_reduction_reading and legalization_reading are separate constraint stories with their own authored ε, beneficiaries, and victims, linked here via affects_constraints. The prohibition reading structurally influences the sibling readings by consuming enforcement budget and political capital that could otherwise fund harm-reduction infrastructure, and by generating a criminal-record population that legalization reforms must subsequently address (expungement, record-sealing) — an upstream/downstream pressure relationship rather than a logical foreclosure.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
