% ============================================================================
% OQ-93 GRID-VIABILITY PROBE STORY: fcr_div_fixture
% Generated by make_probe_stories.py from the pre-registered value table.
% NOT a corpus testset — lives in the audit dir, run via load_and_run by path.
% All 32 grid points AUTHORED (source ids probe_auth_*); shim must be OFF.
% ============================================================================

:- module(constraint_fcr_div_fixture, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:intent_viable_alternative/3,
    narrative_ontology:intent_alternative_rejected/3,
    narrative_ontology:intent_power_change/3,
    narrative_ontology:intent_suppression_level/4,
    narrative_ontology:intent_resistance_level/4.

narrative_ontology:interval(fcr_div_fixture, 0, 10).
domain_priors:base_extractiveness(fcr_div_fixture, 0.30).
domain_priors:suppression_score(fcr_div_fixture, 0.40).
domain_priors:theater_ratio(fcr_div_fixture, 0.20).
narrative_ontology:constraint_metric(fcr_div_fixture, extractiveness, 0.30).
narrative_ontology:constraint_metric(fcr_div_fixture, suppression_requirement, 0.40).
narrative_ontology:constraint_metric(fcr_div_fixture, theater_ratio, 0.20).

% --- AUTHORED 32-point grid (fcr_div_fixture) ---

narrative_ontology:measurement(probe_auth_01, fcr_div_fixture, accessibility_collapse(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_02, fcr_div_fixture, accessibility_collapse(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_03, fcr_div_fixture, stakes_inflation(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_04, fcr_div_fixture, stakes_inflation(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_05, fcr_div_fixture, suppression(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_06, fcr_div_fixture, suppression(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_07, fcr_div_fixture, resistance(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_08, fcr_div_fixture, resistance(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_09, fcr_div_fixture, accessibility_collapse(organizational), 0, 0.50).
narrative_ontology:measurement(probe_auth_10, fcr_div_fixture, accessibility_collapse(organizational), 10, 0.50).
narrative_ontology:measurement(probe_auth_11, fcr_div_fixture, stakes_inflation(organizational), 0, 0.50).
narrative_ontology:measurement(probe_auth_12, fcr_div_fixture, stakes_inflation(organizational), 10, 0.50).
narrative_ontology:measurement(probe_auth_13, fcr_div_fixture, suppression(organizational), 0, 0.50).
narrative_ontology:measurement(probe_auth_14, fcr_div_fixture, suppression(organizational), 10, 0.50).
narrative_ontology:measurement(probe_auth_15, fcr_div_fixture, resistance(organizational), 0, 0.50).
narrative_ontology:measurement(probe_auth_16, fcr_div_fixture, resistance(organizational), 10, 0.50).
narrative_ontology:measurement(probe_auth_17, fcr_div_fixture, accessibility_collapse(class), 0, 0.50).
narrative_ontology:measurement(probe_auth_18, fcr_div_fixture, accessibility_collapse(class), 10, 0.50).
narrative_ontology:measurement(probe_auth_19, fcr_div_fixture, stakes_inflation(class), 0, 0.50).
narrative_ontology:measurement(probe_auth_20, fcr_div_fixture, stakes_inflation(class), 10, 0.50).
narrative_ontology:measurement(probe_auth_21, fcr_div_fixture, suppression(class), 0, 0.50).
narrative_ontology:measurement(probe_auth_22, fcr_div_fixture, suppression(class), 10, 0.50).
narrative_ontology:measurement(probe_auth_23, fcr_div_fixture, resistance(class), 0, 0.50).
narrative_ontology:measurement(probe_auth_24, fcr_div_fixture, resistance(class), 10, 0.50).
narrative_ontology:measurement(probe_auth_25, fcr_div_fixture, accessibility_collapse(individual), 0, 0.80).
narrative_ontology:measurement(probe_auth_26, fcr_div_fixture, accessibility_collapse(individual), 10, 0.20).
narrative_ontology:measurement(probe_auth_27, fcr_div_fixture, stakes_inflation(individual), 0, 0.80).
narrative_ontology:measurement(probe_auth_28, fcr_div_fixture, stakes_inflation(individual), 10, 0.20).
narrative_ontology:measurement(probe_auth_29, fcr_div_fixture, suppression(individual), 0, 0.80).
narrative_ontology:measurement(probe_auth_30, fcr_div_fixture, suppression(individual), 10, 0.20).
narrative_ontology:measurement(probe_auth_31, fcr_div_fixture, resistance(individual), 0, 0.80).
narrative_ontology:measurement(probe_auth_32, fcr_div_fixture, resistance(individual), 10, 0.20).
