% ============================================================================
% OQ-93 GRID-VIABILITY PROBE STORY: grid_probe_tn_only
% Generated by make_probe_stories.py from the pre-registered value table.
% NOT a corpus testset — lives in the audit dir, run via load_and_run by path.
% All 32 grid points AUTHORED (source ids probe_auth_*); shim must be OFF.
% ============================================================================

:- module(constraint_grid_probe_tn_only, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:intent_viable_alternative/3,
    narrative_ontology:intent_alternative_rejected/3,
    narrative_ontology:intent_power_change/3,
    narrative_ontology:intent_suppression_level/4,
    narrative_ontology:intent_resistance_level/4.

narrative_ontology:interval(grid_probe_tn_only, 0, 10).
domain_priors:base_extractiveness(grid_probe_tn_only, 0.50).
domain_priors:suppression_score(grid_probe_tn_only, 0.40).
domain_priors:theater_ratio(grid_probe_tn_only, 0.20).
narrative_ontology:constraint_metric(grid_probe_tn_only, extractiveness, 0.50).
narrative_ontology:constraint_metric(grid_probe_tn_only, suppression_requirement, 0.40).
narrative_ontology:constraint_metric(grid_probe_tn_only, theater_ratio, 0.20).

% --- AUTHORED 32-point grid (grid_probe_tn_only) ---

narrative_ontology:measurement(probe_auth_02, grid_probe_tn_only, accessibility_collapse(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_04, grid_probe_tn_only, stakes_inflation(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_06, grid_probe_tn_only, suppression(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_08, grid_probe_tn_only, resistance(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_10, grid_probe_tn_only, accessibility_collapse(organizational), 10, 0.80).
narrative_ontology:measurement(probe_auth_12, grid_probe_tn_only, stakes_inflation(organizational), 10, 0.80).
narrative_ontology:measurement(probe_auth_14, grid_probe_tn_only, suppression(organizational), 10, 0.80).
narrative_ontology:measurement(probe_auth_16, grid_probe_tn_only, resistance(organizational), 10, 0.80).
narrative_ontology:measurement(probe_auth_18, grid_probe_tn_only, accessibility_collapse(class), 10, 0.80).
narrative_ontology:measurement(probe_auth_20, grid_probe_tn_only, stakes_inflation(class), 10, 0.80).
narrative_ontology:measurement(probe_auth_22, grid_probe_tn_only, suppression(class), 10, 0.80).
narrative_ontology:measurement(probe_auth_24, grid_probe_tn_only, resistance(class), 10, 0.80).
narrative_ontology:measurement(probe_auth_26, grid_probe_tn_only, accessibility_collapse(individual), 10, 0.80).
narrative_ontology:measurement(probe_auth_28, grid_probe_tn_only, stakes_inflation(individual), 10, 0.80).
narrative_ontology:measurement(probe_auth_30, grid_probe_tn_only, suppression(individual), 10, 0.80).
narrative_ontology:measurement(probe_auth_32, grid_probe_tn_only, resistance(individual), 10, 0.80).
