% ============================================================================
% OQ-93 GRID-VIABILITY PROBE STORY: grid_probe_partial8
% Generated by make_probe_stories.py from the pre-registered value table.
% NOT a corpus testset — lives in the audit dir, run via load_and_run by path.
% 8/32 grid points AUTHORED (structural only) (source ids probe_auth_*); shim must be OFF.
% ============================================================================

:- module(constraint_grid_probe_partial8, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:intent_viable_alternative/3,
    narrative_ontology:intent_alternative_rejected/3,
    narrative_ontology:intent_power_change/3,
    narrative_ontology:intent_suppression_level/4,
    narrative_ontology:intent_resistance_level/4.

narrative_ontology:interval(grid_probe_partial8, 0, 10).
domain_priors:base_extractiveness(grid_probe_partial8, 0.50).
domain_priors:suppression_score(grid_probe_partial8, 0.40).
domain_priors:theater_ratio(grid_probe_partial8, 0.20).
narrative_ontology:constraint_metric(grid_probe_partial8, extractiveness, 0.50).
narrative_ontology:constraint_metric(grid_probe_partial8, suppression_requirement, 0.40).
narrative_ontology:constraint_metric(grid_probe_partial8, theater_ratio, 0.20).

% --- AUTHORED PARTIAL 8/32 grid (structural level only, both endpoints) ---

narrative_ontology:measurement(probe_auth_01, grid_probe_partial8, accessibility_collapse(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_02, grid_probe_partial8, accessibility_collapse(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_03, grid_probe_partial8, stakes_inflation(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_04, grid_probe_partial8, stakes_inflation(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_05, grid_probe_partial8, suppression(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_06, grid_probe_partial8, suppression(structural), 10, 0.80).
narrative_ontology:measurement(probe_auth_07, grid_probe_partial8, resistance(structural), 0, 0.20).
narrative_ontology:measurement(probe_auth_08, grid_probe_partial8, resistance(structural), 10, 0.80).
