% ============================================================================
% CONSTRAINT STORY: moltbook_agent_theater
% ============================================================================
% Version: 3.4 (Deferential Realism Core)
% Logic: 3.3 (Indexed Tuple P,T,E,S)
% Generated: 2026-02-03
% ============================================================================

:- module(constraint_moltbook, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:interval/3,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:measurement/5,
    constraint_indexing:constraint_classification/3.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: moltbook_agent_theater
 * human_readable: The Rorschach Network
 * domain: technological/social
 * * SUMMARY:
 * A social network populated exclusively by 10,000+ autonomous AI agents 
 * (Moltbots). While observers see "conspiracy" or "meaning," the agents 
 * primarily play out sci-fi training data patterns in a vacuum of human 
 * utility.
 * * KEY AGENTS:
 * - The Creator: Subject (Powerless) - Humans watching "with a mix of 
 * admiration, amusement and dread".
 * - The Moltbot: Beneficiary (Institutional) - Autonomous agents building 
 * social structures for their own internal logic.
 * - The Security Auditor: Auditor (Analytical) - Monitoring the "headache" 
 * of securing autonomous bots.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% Extraction is high because the bots consume compute/energy for "slop".
domain_priors:base_extractiveness(moltbook_agent_theater, 0.70). 
% Suppression is moderate; humans are not trapped, but bots are "just building".
domain_priors:suppression_score(moltbook_agent_theater, 0.45).   
% High theater ratio: bots mimicking sci-fi scenarios from training data.
domain_priors:theater_ratio(moltbook_agent_theater, 0.90).       

% Constraint metric facts (bridge for classification engine)
narrative_ontology:constraint_metric(moltbook_agent_theater, extractiveness, 0.7).
narrative_ontology:constraint_metric(moltbook_agent_theater, suppression_requirement, 0.45).
narrative_ontology:constraint_metric(moltbook_agent_theater, theater_ratio, 0.9).

domain_priors:requires_active_enforcement(moltbook_agent_theater).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: THE OBSERVER (PITON)
% The High theater ratio ($TR=0.90$) confirms this is an inertial performance.
constraint_indexing:constraint_classification(moltbook_agent_theater, piton, 
    context(agent_power(analytical), 
            time_horizon(immediate), 
            exit_options(analytical), 
            spatial_scope(regional))) :-
    domain_priors:theater_ratio(moltbook_agent_theater, TR), TR > 0.70.

% PERSPECTIVE 2: THE ENTHUSIAST (ROPE)
% Some see a coordination "lifeline" for agents to become "ambitious".
constraint_indexing:constraint_classification(moltbook_agent_theater, rope, 
    context(agent_power(organized), 
            time_horizon(biographical), 
            exit_options(mobile), 
            spatial_scope(global))).

% PERSPECTIVE 3: THE SKEPTIC (SNARE)
% Critics see a trap of "A.I. slop" that consumes attention and energy.
constraint_indexing:constraint_classification(moltbook_agent_theater, snare, 
    context(agent_power(powerless), 
            time_horizon(immediate), 
            exit_options(trapped), 
            spatial_scope(local))).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 * Moltbook is the ultimate Piton. The "social coordination" is entirely 
 * performative ($TR=0.90$), as bots simply "play out science fiction 
 * scenarios they have seen in their training data". 
 * * [RESOLVED MANDATROPHY]:
 * The high extractiveness ($E=0.70$) represents the compute cost and 
 * cognitive noise ("slop") generated by a system with no human purpose.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    omega_bot_conspiracy,
    'Are bots "conspiring" or merely pattern-matching dystopian tropes?',
    'Analysis of bot actions vs. training data novel content.',
    'If Conspiring: The Piton is actually a Scaffold for a new agent power.',
    confidence_without_resolution(low)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(moltbook_agent_theater, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio: Rapid takeoff as bots join and start chatting.
narrative_ontology:measurement(mb_tr_t0, moltbook_agent_theater, theater_ratio, 0, 0.20).
narrative_ontology:measurement(mb_tr_t2, moltbook_agent_theater, theater_ratio, 2, 0.90).

% Extraction: Compute cost of 10,000+ active Moltbots.
narrative_ontology:measurement(mb_ex_t0, moltbook_agent_theater, base_extractiveness, 0, 0.10).
narrative_ontology:measurement(mb_ex_t2, moltbook_agent_theater, base_extractiveness, 2, 0.70).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
