% ============================================================================
% CONSTRAINT STORY: synthetic_data_feedback_loop
% ============================================================================
% Version: 3.4 (Deferential Realism Core)
% Logic: 3.3 (Indexed Tuple P,T,E,S)
% Generated: 2026-01-28
% ============================================================================

:- module(synthetic_data_feedback_loop, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks (Required for loading) ---
:- multifile 
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:interval/3,
    constraint_indexing:constraint_classification/3.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: synthetic_data_feedback_loop
 * human_readable: The Model Autophagy Trap
 * domain: technological/AI/informational
 * * SUMMARY:
 * A scenario where AI models are increasingly trained on data generated by 
 * previous generations of AI, leading to "model collapse." This "Rope" for 
 * infinite data scaling becomes a "Snare" as the informational diversity of 
 * the internet is liquidated, trapping the system in a self-reinforcing 
 * loop of decreasing variance and increasing hallucination.
 * * KEY AGENTS:
 * - Independent Content Creator: Subject (Powerless)
 * - Large-Scale Model Trainer: Beneficiary (Institutional)
 * - Informational Ecologist: Auditor (Analytical)
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% High extraction (0.88) because the loop liquidates the "ground truth" 
% biological signal to feed the institutional need for low-cost tokens.
domain_priors:base_extractiveness(synthetic_data_feedback_loop, 0.88). 
domain_priors:suppression_score(synthetic_data_feedback_loop, 0.72). 
domain_priors:theater_ratio(synthetic_data_feedback_loop, 0.81). % High theater: performative claims of "data quality" masking entropic decay.

% Constraint metric facts (bridge for classification engine)
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, extractiveness, 0.88).
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, suppression_requirement, 0.72).
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, theater_ratio, 0.81).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: THE SUBJECT (SNARE)
% The human creator is trapped: their original work is drowned out by 
% high-volume synthetic mimics, liquidating their visibility and economic agency.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, snare, 
    context(agent_power(powerless), 
            time_horizon(biographical), 
            exit_options(trapped), 
            spatial_scope(national))).

% PERSPECTIVE 2: THE BENEFICIARY (ROPE)
% The trainer views synthetic data as a Rope—the only way to coordinate 
% the massive token counts required for frontier capability without 
% exhausting the finite supply of human-written text.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, rope, 
    context(agent_power(institutional), 
            time_horizon(generational), 
            exit_options(mobile), 
            spatial_scope(global))).

% PERSPECTIVE 3: THE SYSTEMS AUDITOR (PITON)
% Theater ratio (0.81) > 0.70 triggers Piton: the "Reinforcement Learning" 
% protocols are an inertial spike; they refine the mean but no longer 
% capture the territory of reality.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, piton, 
    context(agent_power(analytical), 
            time_horizon(historical), 
            exit_options(analytical), 
            spatial_scope(global))).

% PERSPECTIVE 4: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% Detects high extraction (0.88) and coordination necessity as a Tangled Rope.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, tangled_rope, 
    context(agent_power(analytical), 
            time_horizon(civilizational), 
            exit_options(arbitrage), 
            spatial_scope(universal))) :-
    domain_priors:base_extractiveness(synthetic_data_feedback_loop, E), E >= 0.50,
    domain_priors:suppression_score(synthetic_data_feedback_loop, S), S > 0.40.

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(synthetic_data_feedback_loop_tests).

test(perspectival_gap) :-
    % Verify Snare for the subject vs Rope for the institutional trainer.
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, snare, 
        context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, rope, 
        context(agent_power(institutional), _, _, _)).

test(piton_trigger) :-
    % Ensure high theater ratio (0.81) correctly triggers the Piton classification.
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, piton, 
        context(agent_power(analytical), _, _, _)).

test(extraction_mandatrophy) :-
    % Ensure high extraction (0.88) triggers mandatory v3.4 resolution logic.
    domain_priors:base_extractiveness(synthetic_data_feedback_loop, E),

    E > 0.70.

:- end_tests(synthetic_data_feedback_loop_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 * The extraction score (0.88) reflects a "Mandatrophy" state where the 
 * "coordination" of data scaling is actually a parasitic liquidation of the 
 * informational commons.
 * 
 * * PERSPECTIVAL GAP:
 * The Content Creator feels a Snare because their unique signal is 
 * cannibalized by the system. The Trainer sees a Rope because the scaling 
 * laws demand more data than the species can produce biologically.
 * * [RESOLVED MANDATROPHY]:
 * Resolved via the Piton and Tangled Rope classifications. For an analytical 
 * observer, the "data scaling" is no longer functional relative to truth 
 * (Theater 0.81); it is an inert spike siphoning 0.88 of the informational 
 * surplus.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

% Required for high-extraction constraints (> 0.46).
omega_variable(
    omega_autophagous_threshold,
    'Can "curated" synthetic data prevent collapse, or is entropy absolute (Snare vs Mountain)?',
    'Tracking the perplexity delta between models trained on 10% vs 90% synthetic data.',
    'If perplexity stabilizes: Snare of current technique. If it explodes: Mountain of Information Entropy.',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for structural_linter.py.
narrative_ontology:interval(synthetic_data_feedback_loop, 0, 10). 

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
