% ============================================================================
% CONSTRAINT STORY: too_big_to_manage
% ============================================================================
% Version: 3.4 (Deferential Realism Core)
% Logic: 3.3 (Indexed Tuple P,T,E,S)
% Generated: 2026-01-28
% ============================================================================

:- module(too_big_to_manage, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks (Required for loading) ---
:- multifile 
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:interval/3,
    constraint_indexing:constraint_classification/3.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: too_big_to_manage
 * human_readable: The Administrative Singularity
 * domain: organizational/technological/political
 * * SUMMARY:
 * A scenario where an organization's scale exceeds the cognitive and 
 * computational limits of its management structure. The internal coordination 
 * overhead consumes all surplus, turning a supposed "Rope" for efficiency 
 * into a "Snare" of bureaucracy. Decisions are no longer made relative to 
 * reality, but relative to the internal model's inertia.
 * * KEY AGENTS:
 * - Line Employee: Subject (Powerless)
 * - Executive Leadership: Beneficiary (Institutional)
 * - Systems Resilience Auditor: Auditor (Analytical)
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% High extraction (0.85) as the institution siphons the labor and focus of 
% participants into self-preservation of the management layer itself.
domain_priors:base_extractiveness(too_big_to_manage, 0.85). 
domain_priors:suppression_score(too_big_to_manage, 0.72). 
domain_priors:theater_ratio(too_big_to_manage, 0.90). % Extreme theater: High-production corporate rituals masking total lack of steering.

% Constraint metric facts (bridge for classification engine)
narrative_ontology:constraint_metric(too_big_to_manage, extractiveness, 0.85).
narrative_ontology:constraint_metric(too_big_to_manage, suppression_requirement, 0.72).
narrative_ontology:constraint_metric(too_big_to_manage, theater_ratio, 0.9).

% This is an entropic state of late-stage organizations.
% narrative_ontology:has_sunset_clause(too_big_to_manage). 

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: THE SUBJECT (SNARE)
% For the line employee, the scale is a snare: they are trapped in 
% contradictory directives generated by uncoordinated sub-departments.
constraint_indexing:constraint_classification(too_big_to_manage, snare, 
    context(agent_power(powerless), 
            time_horizon(biographical), 
            exit_options(trapped), 
            spatial_scope(national))).

% PERSPECTIVE 2: THE BENEFICIARY (ROPE)
% The leadership views the scale as a Rope—the only way to maintain global 
% market coordination and project-level dominance.
constraint_indexing:constraint_classification(too_big_to_manage, rope, 
    context(agent_power(institutional), 
            time_horizon(generational), 
            exit_options(mobile), 
            spatial_scope(global))).

% PERSPECTIVE 3: THE SYSTEMS AUDITOR (PITON)
% Theater ratio (0.90) > 0.70 triggers Piton: the management structure 
% is now a non-functional, performative spike maintained by cultural inertia.
constraint_indexing:constraint_classification(too_big_to_manage, piton, 
    context(agent_power(analytical), 
            time_horizon(civilizational), 
            exit_options(arbitrage), 
            spatial_scope(universal))) :-
    domain_priors:theater_ratio(too_big_to_manage, TR), TR > 0.70.

% PERSPECTIVE 4: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% Detects high extraction (0.85) and high theater (0.90) as a Tangled Rope.
constraint_indexing:constraint_classification(too_big_to_manage, tangled_rope, 
    context(agent_power(analytical), 
            time_horizon(historical), 
            exit_options(analytical), 
            spatial_scope(global))) :-
    domain_priors:base_extractiveness(too_big_to_manage, E), E >= 0.50,
    domain_priors:suppression_score(too_big_to_manage, S), S > 0.40.

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(too_big_to_manage_tests).

test(perspectival_gap) :-
    % Verify Snare for the subject vs Rope for the institutional beneficiary.
    constraint_indexing:constraint_classification(too_big_to_manage, snare, 
        context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(too_big_to_manage, rope, 
        context(agent_power(institutional), _, _, _)).

test(piton_trigger) :-
    % Ensure high theater ratio (0.90) triggers Piton classification.
    constraint_indexing:constraint_classification(too_big_to_manage, piton, 
        context(agent_power(analytical), _, _, _)).

test(extraction_mandatrophy) :-
    % Ensure extraction (0.85) triggers mandatory v3.4 resolution logic.
    domain_priors:base_extractiveness(too_big_to_manage, E),

    E > 0.70.

:- end_tests(too_big_to_manage_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 * The extraction score (0.85) reflects a "Mandatrophy" state where the 
 * "coordination" is actually a parasitic consumption of resources by the 
 * administrative layer itself.
 * 
 * * PERSPECTIVAL GAP:
 * The Line Employee feels a Snare because their work is siphoned into 
 * reports that no one reads. The Leadership sees a Rope because the 
 * massive scale is the only way they know how to coordinate a global mission.
 * * [RESOLVED MANDATROPHY]:
 * Resolved via the Piton and Tangled Rope classifications. For an 
 * analytical observer, the management is no longer steering the ship 
 * (Theater 0.90); it is an inert spike of logic that extracts 0.85 of 
 * the surplus to feed its own internal friction.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

% Required for high-extraction constraints (> 0.46).
omega_variable(
    omega_management_efficiency,
    'Can AI or automation restore management efficiency, or is scale an irreducible limit (Snare vs Mountain)?',
    'Tracking the ratio of administrative staff to productive staff over time.',
    'If ratio drops: Snare of current design. If ratio stays high: Mountain of Complexity.',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for structural_linter.py.
narrative_ontology:interval(too_big_to_manage, 0, 10). 

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
