% ============================================================================
% OQ-93 GRID-VIABILITY PROBE STORY: grid_probe_intent_max
% Generated by make_probe_stories.py from the pre-registered value table.
% NOT a corpus testset — lives in the audit dir, run via load_and_run by path.
% All 32 grid points AUTHORED (source ids probe_auth_*); shim must be OFF.
% ============================================================================

:- module(constraint_grid_probe_intent_max, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:intent_viable_alternative/3,
    narrative_ontology:intent_alternative_rejected/3,
    narrative_ontology:intent_power_change/3,
    narrative_ontology:intent_suppression_level/4,
    narrative_ontology:intent_resistance_level/4.

narrative_ontology:interval(grid_probe_intent_max, 0, 10).
domain_priors:base_extractiveness(grid_probe_intent_max, 0.50).
domain_priors:suppression_score(grid_probe_intent_max, 0.40).
domain_priors:theater_ratio(grid_probe_intent_max, 0.20).
narrative_ontology:constraint_metric(grid_probe_intent_max, extractiveness, 0.50).
narrative_ontology:constraint_metric(grid_probe_intent_max, suppression_requirement, 0.40).
narrative_ontology:constraint_metric(grid_probe_intent_max, theater_ratio, 0.20).

% --- AUTHORED 32-point grid (grid_probe_intent_max) ---

narrative_ontology:measurement(probe_auth_01, grid_probe_intent_max, accessibility_collapse(structural), 0, 0.00).
narrative_ontology:measurement(probe_auth_02, grid_probe_intent_max, accessibility_collapse(structural), 10, 1.00).
narrative_ontology:measurement(probe_auth_03, grid_probe_intent_max, stakes_inflation(structural), 0, 0.00).
narrative_ontology:measurement(probe_auth_04, grid_probe_intent_max, stakes_inflation(structural), 10, 1.00).
narrative_ontology:measurement(probe_auth_05, grid_probe_intent_max, suppression(structural), 0, 0.00).
narrative_ontology:measurement(probe_auth_06, grid_probe_intent_max, suppression(structural), 10, 1.00).
narrative_ontology:measurement(probe_auth_07, grid_probe_intent_max, resistance(structural), 0, 0.00).
narrative_ontology:measurement(probe_auth_08, grid_probe_intent_max, resistance(structural), 10, 1.00).
narrative_ontology:measurement(probe_auth_09, grid_probe_intent_max, accessibility_collapse(organizational), 0, 0.00).
narrative_ontology:measurement(probe_auth_10, grid_probe_intent_max, accessibility_collapse(organizational), 10, 1.00).
narrative_ontology:measurement(probe_auth_11, grid_probe_intent_max, stakes_inflation(organizational), 0, 0.00).
narrative_ontology:measurement(probe_auth_12, grid_probe_intent_max, stakes_inflation(organizational), 10, 1.00).
narrative_ontology:measurement(probe_auth_13, grid_probe_intent_max, suppression(organizational), 0, 0.00).
narrative_ontology:measurement(probe_auth_14, grid_probe_intent_max, suppression(organizational), 10, 1.00).
narrative_ontology:measurement(probe_auth_15, grid_probe_intent_max, resistance(organizational), 0, 0.00).
narrative_ontology:measurement(probe_auth_16, grid_probe_intent_max, resistance(organizational), 10, 1.00).
narrative_ontology:measurement(probe_auth_17, grid_probe_intent_max, accessibility_collapse(class), 0, 0.00).
narrative_ontology:measurement(probe_auth_18, grid_probe_intent_max, accessibility_collapse(class), 10, 1.00).
narrative_ontology:measurement(probe_auth_19, grid_probe_intent_max, stakes_inflation(class), 0, 0.00).
narrative_ontology:measurement(probe_auth_20, grid_probe_intent_max, stakes_inflation(class), 10, 1.00).
narrative_ontology:measurement(probe_auth_21, grid_probe_intent_max, suppression(class), 0, 0.00).
narrative_ontology:measurement(probe_auth_22, grid_probe_intent_max, suppression(class), 10, 1.00).
narrative_ontology:measurement(probe_auth_23, grid_probe_intent_max, resistance(class), 0, 0.00).
narrative_ontology:measurement(probe_auth_24, grid_probe_intent_max, resistance(class), 10, 1.00).
narrative_ontology:measurement(probe_auth_25, grid_probe_intent_max, accessibility_collapse(individual), 0, 0.00).
narrative_ontology:measurement(probe_auth_26, grid_probe_intent_max, accessibility_collapse(individual), 10, 1.00).
narrative_ontology:measurement(probe_auth_27, grid_probe_intent_max, stakes_inflation(individual), 0, 0.00).
narrative_ontology:measurement(probe_auth_28, grid_probe_intent_max, stakes_inflation(individual), 10, 1.00).
narrative_ontology:measurement(probe_auth_29, grid_probe_intent_max, suppression(individual), 0, 0.00).
narrative_ontology:measurement(probe_auth_30, grid_probe_intent_max, suppression(individual), 10, 1.00).
narrative_ontology:measurement(probe_auth_31, grid_probe_intent_max, resistance(individual), 0, 0.00).
narrative_ontology:measurement(probe_auth_32, grid_probe_intent_max, resistance(individual), 10, 1.00).

% --- Best-case authored intent evidence (Conditions 2-4; the only producer
% these tables have ever had) ---
narrative_ontology:intent_viable_alternative(grid_probe_intent_max, system_a, alt_x).
narrative_ontology:intent_alternative_rejected(grid_probe_intent_max, system_a, alt_x).
narrative_ontology:intent_power_change(grid_probe_intent_max, corporate_elite, 0.80).
narrative_ontology:intent_suppression_level(grid_probe_intent_max, corporate_elite, structural, 0.90).
narrative_ontology:intent_resistance_level(grid_probe_intent_max, corporate_elite, structural, 0.90).

