
% OQ-207 stage-1 dump (generated by oq207_stakeholder_h1_census.py — the
% canonical copy lives in that script; do not edit this file).
dump_leg(Leg, OutFile) :-
    retractall(config:param(corpus_path, _)),
    assertz(config:param(corpus_path, Leg)),
    cache_registry:clear_all_caches,
    format(user_error, "[clear] caches cleared for leg ~w~n", [Leg]),
    corpus_loader:load_all_testsets,
    setup_call_cleanup(open(OutFile, write, S), dump_records(S), close(S)).

dump_records(S) :-
    format(S, "[", []),
    findall(C, corpus_loader:corpus_constraint(C), Cs),
    dump_list(S, Cs),
    format(S, "~n]~n", []).

dump_list(_, []).
dump_list(S, [C|T]) :-
    dump_one(S, C),
    ( T == [] -> true ; format(S, ",", []) ),
    dump_list(S, T).

% n_excluded is MEASURED for every record by direct fact query, independent
% of the verdict shape (pre-OQ-217 dumps authored 0 for non-mcc verdicts — an
% authored-zero that under-determined the movement prediction, witnessed
% 2026-07-12 in movement_diff v1; Build Discipline Pattern 5).
dump_one(S, C) :-
    stakeholder_seats:stakeholder_obstruction(C, H0, H1, NS, NR),
    stakeholder_seats:consensus_provenance(C, V),
    findall(X, narrative_ontology:constraint_stakeholder(C, X, excluded, _, _, _, _), Excl),
    length(Excl, NExcl),
    verdict_fields(V, VName, HasUnknown),
    format(S, '~n  {"id": "~w", "h0": ~w, "h1": ~w, "n_seats": ~w, "n_real": ~w, "verdict": "~w", "plural_has_unknown": ~w, "n_excluded": ~w}',
           [C, H0, H1, NS, NR, VName, HasUnknown, NExcl]).

verdict_fields(no_agent_seats,               no_agent_seats,               null).
verdict_fields(seats_untyped,                seats_untyped,                null).
verdict_fields(insufficient_real_seats,      insufficient_real_seats,      null).
verdict_fields(unanimous_no_excluded_seats,  unanimous_no_excluded_seats,  null).
verdict_fields(unanimous_with_untypeable_seats,
               unanimous_with_untypeable_seats, null).
verdict_fields(manufactured_consensus_candidate(_),
               manufactured_consensus_candidate, null).
verdict_fields(manufactured_consensus_candidate_untypeable(_),
               manufactured_consensus_candidate_untypeable, null).
% plural_has_unknown is a RETIRED-cell tripwire post-OQ-217: the unknown token
% can no longer appear in a plural term, so true here = regression.
verdict_fields(plural(Us), plural, HU) :-
    ( memberchk(unknown, Us) -> HU = true ; HU = false ).
