% ============================================================================
% CONSTRAINT STORY: inner_model_theory_constraints
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-02-24
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_inner_model_theory_constraints, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    domain_priors:emerges_naturally/1,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: inner_model_theory_constraints
 *   human_readable: The Axiom of Constructibility (V=L) and Inner Model Theory Constraints
 *   domain: mathematical/logical
 *
 * SUMMARY:
 *   The Axiom of Constructibility (V=L) states that every set is
 *   constructible — that is, every set in the mathematical universe V belongs
 *   to the inner model L, which is generated by iterating the Def operator
 *   (definable subsets) over ordinals. This constraint emerges from the
 *   recursive definition of the constructible hierarchy and represents a
 *   foundational boundary on what sets are accessible to rational inquiry.
 *   Inner Model Theory studies sub-universes of ZFC that model
 *   constructibility-like properties, asking: which smaller universes
 *   preserve which axioms? The constraint appears differently across
 *   observers: to the logical analyst, it is an immutable law of
 *   definability; to the set theorist working inside L, it is the natural
 *   structure of their universe; to the realist outside L, it is a
 *   coordination framework with extractive costs; to the curriculum
 *   maintainer, it is a degraded piton; to the proof-theoretic community, it
 *   is a pure coordination mechanism; to Gödel, it expresses logical
 *   necessity. The constraint's extractiveness (0.12) is uniformly low
 *   because V=L does not impose asymmetric costs on agents — it defines a
 *   structure that all agents observe the same way, or exit from with equal
 *   difficulty. The theater ratio (0.15) is low because the constraint's
 *   logical properties are not performative; they either hold or they do not.
 *   The accessibility collapse (0.92) reflects that acceptance of V=L
 *   severely restricts which sets are accessible (all undefinable sets become
 *   inaccessible); the resistance (0.08) reflects that few mathematicians
 *   actively resist the constraint — most simply work outside it.
 *
 * KEY AGENTS:
 *   - Logical Analysts: Observers who study the mathematical structure of V=L without commitment. Analytical perspective. See the constraint as Mountain.
 *   - Set Theorists in L: Mathematicians working within the constructible universe. Powerful but constrained by the framework they accept. See Mountain.
 *   - Set Theorists Outside L: Mathematicians rejecting V=L or working in extensions (L[U], core models, large cardinals). Powerful, mobile, realist. See Tangled Rope.
 *   - Proof Theorists: Community that uses inner model theory as a measurement scale for axiom strength. Organized, with arbitrage access to multiple frameworks. See Rope.
 *   - Finitists/Predicativists: Critics of constructibility who reject the axiom or argue it is too permissive. Victims of the realist perspective (forced to adopt stronger foundations).
 *   - Curriculum Maintainers: Institutional gatekeepers who teach V=L as foundational material. Institutional perspective, low functional engagement. See Piton.
 *   - Gödel (Historical/Philosophical): Proponent of constructibility as a logical necessity. Analytical, civilizational perspective. See Mountain.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(inner_model_theory_constraints, 0.12).
domain_priors:suppression_score(inner_model_theory_constraints, 0.03).
domain_priors:theater_ratio(inner_model_theory_constraints, 0.15).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(inner_model_theory_constraints, extractiveness, 0.12).
narrative_ontology:constraint_metric(inner_model_theory_constraints, suppression_requirement, 0.03).
narrative_ontology:constraint_metric(inner_model_theory_constraints, theater_ratio, 0.15).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(inner_model_theory_constraints, accessibility_collapse, 0.92).
narrative_ontology:constraint_metric(inner_model_theory_constraints, resistance, 0.08).

% --- Constraint claim ---
narrative_ontology:constraint_claim(inner_model_theory_constraints, mountain).
narrative_ontology:human_readable(inner_model_theory_constraints, "The Axiom of Constructibility (V=L) and Inner Model Theory Constraints").
narrative_ontology:topic_domain(inner_model_theory_constraints, "mathematical/logical").

domain_priors:emerges_naturally(inner_model_theory_constraints).

% --- Structural relationships ---
% No enrichment needed. As a Mountain (physical limit), this constraint does
% not have beneficiaries or victims in the structural sense.

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: LOGICAL ANALYST (MOUNTAIN) — From the vantage of mathematical logic, V=L represents a structural constraint inherent to the theory of inner models. The axiom defines a universe where every set is constructible, which imposes a rigid hierarchy. The constraint emerges from the recursive definition of constructibility itself: L₀ = ∅, L_{α+1} = Def(L_α), L_λ = ∪_{α<λ} L_α. This recursion is not imposed from outside but follows from the logical structure of definability. The constraint cannot be violated without abandoning the very concept of constructibility. ε=0.12, suppression=0.03, theater=0.15. No extraction or coercion; no beneficiaries or victims. The constraint is invariant across all mathematical observation.
constraint_indexing:constraint_classification(inner_model_theory_constraints, mountain,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(universal))).

% PERSPECTIVE 2: SET THEORIST IN L (MOUNTAIN) — A mathematician working exclusively within L experiences the constraint as a natural law of their operating universe. In L, the Axiom of Choice holds, the Generalized Continuum Hypothesis is true, and many classical results are settled. The constraint appears as an accessibility collapse: if you accept V=L, entire classes of questions become inaccessible (undecidable within L); you cannot ask whether arbitrary sets satisfy properties that depend on V \ L. ε=0.12, suppression=0.03. The constraint is not resisted because no alternative framework is accessible from within L; the theorist has no exit. But this is not extraction — it is structural necessity.
constraint_indexing:constraint_classification(inner_model_theory_constraints, mountain,
    context(agent_power(powerful),
            time_horizon(civilizational),
            exit_options(constrained),
            spatial_scope(universal))).

% PERSPECTIVE 3: SET THEORIST OUTSIDE L / REALIST (TANGLED ROPE) — A set theorist who rejects V=L (or remains agnostic) experiences the constraint as a coordinating framework with extractive elements. Inner Model Theory provides a shared language for comparing sub-universes: L, L[U], L[μ], Jensen's core model, the HOD (Hereditarily Ordinal Definable sets). This is coordination — the constraint enables rigorous discussion of large cardinal axioms and their consistency. But it is also extractive: working outside L requires accepting additional axioms (large cardinals), strengthening assumptions beyond ZFC, which imposes a cognitive and proof-theoretic cost. The realist must commit to stronger foundations to escape L's bounds. ε=0.35, suppression=0.42, requires_active_enforcement=true. Beneficiaries: proof_theorists, large_cardinal_researchers. Victims: finitists, predicativists. The realist perspective shows both coordination (a shared mathematical language) and asymmetric cost (commitment to stronger axioms).
constraint_indexing:constraint_classification(inner_model_theory_constraints, tangled_rope,
    context(agent_power(powerful),
            time_horizon(generational),
            exit_options(mobile),
            spatial_scope(global))).

% PERSPECTIVE 4: MATHEMATICAL CURRICULUM MAINTAINER (PITON) — From an institutional teaching/publishing perspective, the axiom of constructibility appears as a degraded framework maintained through inertia. Most working mathematicians outside set theory do not engage with V=L or inner model theory. The curriculum teaches ZFC as a foundation, mentions V=L as a historical curiosity, then moves on. The constraint persists in textbooks and foundational discussions not because it functionally constrains modern mathematics, but because it is embedded in the historical narrative of set theory. theater_ratio=0.72: the axiom occupies formal space in foundational discussions but exercises minimal actual constraint on contemporary mathematical practice. The institutional perspective sees this as a piton — a former load-bearing element that is now maintained through ritual rather than functional necessity.
constraint_indexing:constraint_classification(inner_model_theory_constraints, piton,
    context(agent_power(institutional),
            time_horizon(biographical),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 5: PROOF-THEORETIC RESEARCH COMMUNITY (ROPE) — For proof theorists, inner model theory is pure coordination without extraction. The theory provides a formal language for comparing proof-theoretic strength: V=L is proof-theoretically weak (it adds no new theorems to ZFC). Alternative inner models (V=L[U], core models) are stronger, and large cardinals are stronger still. This creates a shared scale for discussing consistency and relative strength. ε=0.08, suppression=0.05, χ ≈ 0.06. The research community coordinates on this framework; it solves the collective action problem of how to discuss axiom strength without universal agreement on which axioms to adopt. No beneficiary extracts asymmetric value. All agents in the community benefit equally from the shared measurement standard.
constraint_indexing:constraint_classification(inner_model_theory_constraints, rope,
    context(agent_power(organized),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 6: LOGICAL NECESSITY / GÖDEL'S VIEW (MOUNTAIN) — Gödel's foundational perspective sees constructibility as reflecting a deep logical principle: every set exists because it is definable in finite terms. This is not an arbitrary axiom but an expression of how minds naturally construct mathematical objects. From this angle, V=L is not a constraint imposed on mathematics but a law of mathematical existence itself. It is not resisted because alternatives (like V ≠ L, accepting arbitrary undefinable sets) violate the principle of intelligibility. ε=0.08, suppression=0.02, accessibility_collapse=0.95. The constraint is universal and ineliminable — it reflects the structure of rational thought itself. However, modern mathematics has rejected this view: large cardinals, forcing, and ultrapowers have shown that V ≠ L is consistent and fertile. This perspective's classification as Mountain is epistemically justified but its factual claim is contested.
constraint_indexing:constraint_classification(inner_model_theory_constraints, mountain,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(universal))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(inner_model_theory_constraints_tests).

test(invariance_check) :-
    % Verify that as a Mountain, the classification is uniform across perspectives.
    constraint_indexing:constraint_classification(inner_model_theory_constraints, TypeTarget, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(inner_model_theory_constraints, TypeBeneficiary, context(agent_power(institutional), _, _, _)),
    TypeTarget == TypeBeneficiary,
    TypeTarget == mountain.

test(mountain_threshold_validation) :-
    config:param(extractiveness_metric_name, ExtMetricName),
    narrative_ontology:constraint_metric(inner_model_theory_constraints, ExtMetricName, E),
    domain_priors:suppression_score(inner_model_theory_constraints, S),
    E =< 0.25,
    S =< 0.05.

test(nl_profile_validation) :-
    domain_priors:emerges_naturally(inner_model_theory_constraints),
    narrative_ontology:constraint_metric(inner_model_theory_constraints, accessibility_collapse, AC),
    narrative_ontology:constraint_metric(inner_model_theory_constraints, resistance, R),
    AC >= 0.85,
    R =< 0.15.

test(piton_threshold) :-
    domain_priors:theater_ratio(inner_model_theory_constraints, TR),
    TR >= 0.70.

:- end_tests(inner_model_theory_constraints_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.12): Very low. The Axiom of Constructibility does not extract asymmetric value from any agent. A set theorist working in L gains no advantage from other agents being forced to accept L; the framework's truth value is universal (under each perspective's framework). Alternative frameworks (V ≠ L + large cardinals) do not extract from finitists or predicativists — they simply require additional assumptions, which is a cost of stronger theories, not extraction. Suppression (0.03): Extremely low. V=L does not suppress alternatives through coercion. Large cardinal axioms, forcing-compatible frameworks, and predicativist systems exist alongside and apart from L. No agent is forced to accept V=L under threat; they simply work in different frameworks. Theater ratio (0.15): Very low. The logical properties of constructibility are not performative. The recursion L₀ = ∅, L_{α+1} = Def(L_α) either generates a consistent universe or it does not. Modern set theory has moved away from V=L (Cohen's forcing showed V ≠ L is consistent; large cardinals are incompatible with V=L), so the axiom occupies minimal functional space. However, inner model theory still uses V=L as a baseline for comparison, which explains the slight increase in theater from t=0 to t=50.
 *
 * PERSPECTIVAL GAP:
 *   The perspectives produce a presheaf structure over observation frameworks rather than perspectival disagreement about the same fact. The Gödel perspective and the Realist perspective disagree on the status of V=L (necessary vs. contingent), which generates different classifications (Mountain vs. Tangled Rope). The Logical Analyst perspective sees Mountain across all observations. The Curriculum Maintainer sees Piton (degraded but persistent). The Proof Theorist sees Rope (coordination without extraction). These are not conflicting measurements of the same constraint but coherent readings of different structural relationships to V=L. The gap is not reduced by more data — it is resolved by recognizing that V=L occupies different structural positions in different mathematical frameworks. This is a characteristic feature of foundational constraints in mathematics: they do not admit a single 'objective' classification because their status (necessary law, contingent axiom, or institutional convention) depends on one's foundational commitments.
 *
 * DIRECTIONALITY LOGIC:
 *   Inner Model Theory constraints are unusual in DR classification because they involve no asymmetric power distribution. All agents (whether inside or outside L) operate under the same logical rules. Beneficiaries and victims cannot be clearly demarcated because the constraint does not extract from some agents for the benefit of others. The realist perspective (Tangled Rope) identifies finitists and predicativists as 'victims' in the sense that accepting large cardinals to escape L's bounds requires stronger axioms, which is a proof-theoretic cost. But this is not extraction in the classical sense (one agent gains asymmetric advantage) — it is simply the cost of choosing a stronger theory. For the Mountain perspectives (Logical Analyst, In-L Theorist, Gödel), there are no beneficiaries or victims because the constraint is universal and ineliminable. The Rope perspective (Proof Theorists) sees pure coordination: all agents use the same L framework to measure axiom strength, and all benefit equally from the shared measurement scale. The Piton perspective sees neither benefits nor costs — the constraint is maintained through institutional inertia.
 *
 * MANDATROPHY ANALYSIS:
 *   This constraint resolves mandatrophy by demonstrating that inner model theory itself is NOT extracted value; it is a FRAMEWORK for understanding extraction in other constraints. The axiom of constructibility does not extract in the Snare sense (high χ, suppression, coercion). It does not coordinate without extraction (pure Rope). It does not mix coordination with extraction (Tangled Rope) in the classical sense — the 'extraction' in the realist perspective is merely the cost of axiom choice, not asymmetric power. The constraint is primarily Mountain (logical necessity) from the foundational perspective, with Piton elements (institutional maintenance) in contemporary mathematics. The mandatrophy resolution shows that large-cardinal set theory and forcing-compatible frameworks have empirically demonstrated that V=L is not necessary (Cohen's theorem) and not productive for solving classical problems (large cardinals solve CH, solve projective determinacy, etc.). The Gödel perspective's Mountain classification is thus epistemically justified (founded in logical reasoning) but factually incorrect (V ≠ L is consistent and productive). This is a rare case where a Mountain classification is not false but incomplete — the constraint is described accurately from one perspective but fails to be universal.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    v_equals_l_consistency,
    'Is V=L a necessary truth of mathematics, a consistent but contingent axiom, or a useful fiction for inner model theory?',
    'Gödel-Cohen forcing analysis: study the structure of ground models and generic extensions. Examine empirical success of alternatives (large cardinals, determinacy, forcing) in resolving classical problems.',
    'If necessary: Mountain classification holds universally. If contingent: Tangled Rope or Rope classification (depending on coordination function). If fiction: Piton classification (ritual maintenance without function).',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(v_equals_l_consistency, conceptual, 'Whether V=L is necessary, contingent, or fictive').

omega_variable(
    constructibility_measurement_independence,
    'Does the observability of inner models depend on the axioms adopted (forcing framework, large cardinal assumptions), or is constructibility framework-independent?',
    'Examine invariance of constructibility definitions across different forcing extensions and cardinal strength assumptions. Determine whether L is identifiable in L[G], L[U], core models.',
    'If frame-dependent: different epsilon values for L under different observation bases → constraint family decomposition needed. If frame-independent: single Mountain constraint.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(constructibility_measurement_independence, empirical, 'Whether constructibility is framework-independent').

omega_variable(
    godel_program_viability,
    'Does Gödel''s foundational program (mathematics as exploration of necessary structures) remain viable after forcing, ultrapowers, and large cardinals?',
    'Historical-philosophical analysis of how Gödel''s platonism responds to post-Gödel developments. Examine whether modern set theorists adopt Gödel''s necessity view or treat axioms as tools.',
    'If viable: Gödel''s Mountain perspective remains structurally justified. If abandoned: the perspective is a degraded piton, maintained for historical reasons only.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(godel_program_viability, conceptual, 'Whether Gödel''s foundational program survives modern set theory').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(inner_model_theory_constraints, 0, 100).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(imt_tr_t0, inner_model_theory_constraints, theater_ratio, 0, 0.1).
narrative_ontology:measurement(imt_tr_t50, inner_model_theory_constraints, theater_ratio, 50, 0.15).
narrative_ontology:measurement(imt_tr_t100, inner_model_theory_constraints, theater_ratio, 100, 0.15).

% Extraction over time
narrative_ontology:measurement(imt_be_t0, inner_model_theory_constraints, base_extractiveness, 0, 0.12).
narrative_ontology:measurement(imt_be_t50, inner_model_theory_constraints, base_extractiveness, 50, 0.12).
narrative_ontology:measurement(imt_be_t100, inner_model_theory_constraints, base_extractiveness, 100, 0.12).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(inner_model_theory_constraints, information_standard).
narrative_ontology:affects_constraint(inner_model_theory_constraints, large_cardinal_consistency).
narrative_ontology:affects_constraint(inner_model_theory_constraints, forcing_independence_results).
narrative_ontology:affects_constraint(inner_model_theory_constraints, continuum_hypothesis_indeterminacy).

% DUAL FORMULATION NOTE:
% Inner Model Theory constraints form a family with large cardinal constraints. V=L is the baseline inner model (ε=0.12, Mountain). Alternative inner models (L[U], core models) have higher extractiveness (ε~0.35) because they require additional axioms and impose proof-theoretic costs (Tangled Rope). Large cardinal hypotheses are downstream: they are formulated in response to V=L's limitations. The network encodes this dependency: constructibility theory provides the language for comparing all inner models.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
