% ============================================================================
% CONSTRAINT STORY: sovereignty_as_arbitrage
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-02-24
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_sovereignty_as_arbitrage, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: sovereignty_as_arbitrage
 *   human_readable: The Alberta Prosperity Project (State-Building Arbitrage)
 *   domain: political/economic
 *
 * SUMMARY:
 *   The Alberta Prosperity Project (APP) and related separatist organizations
 *   frame Alberta sovereignty as a mechanism for economic arbitrage — exiting
 *   federal equalization transfers, resource-sharing agreements, and fiscal
 *   redistribution to retain wealth generated by energy extraction. This
 *   constraint operates as a snare because it extracts political and social
 *   value from those unable to exit (federal equalization beneficiaries,
 *   low-income Albertans outside energy sectors, equalization-receiving
 *   provinces) while offering only narrative compensation: the promise that
 *   sovereignty will unlock prosperity. The arbitrage mechanism is
 *   structural: separatist leadership benefits from political mobilization
 *   and institutional power accumulation; energy corporations benefit from
 *   reduced federal environmental and tax oversight; but those who lose
 *   federal transfers (elderly, disabled, poor rural populations) and those
 *   whose equalization is eliminated (Atlantic Canada, Quebec, Manitoba)
 *   cannot exit or organize effective resistance. Theater_ratio has increased
 *   from 0.40 to 0.65 because separatist institutions have shifted from
 *   economic grievance documentation to performative institutional
 *   capacity-building: independence movements, provincial-government-aligned
 *   rhetoric, and constitutional negotiation theater, while the underlying
 *   equalization problem remains unsolved.
 *
 * KEY AGENTS:
 *   - Separatist Political Leadership: Primary beneficiary (institutional/arbitrage) — mobilizes grievance narrative, builds institutional capacity, captures political authority and media platform; benefits from political organizing and potential post-separation governance roles
 *   - Alberta Energy Corporations: Secondary beneficiary (organized/constrained) — benefits from reduced environmental oversight, tax competition threats, regulatory alignment with energy priorities; constrained by continental trade integration and shared infrastructure
 *   - Federal Equalization System: Primary victim (powerless/trapped) — abstract fiscal mechanism with no agency; extraction via narrative reframing as 'unfair redistribution'
 *   - Low-Income Albertans Outside Energy Sector: Dual victim (powerless/trapped) — loses federal income support (CPP, OAS, child benefits) without equivalent provincial replacement; also bears costs of federal revenue reduction
 *   - Equalization-Receiving Provinces: Institutional victim (organized/trapped) — constrained by federal fiscal framework; cannot defend equalization mechanism politically; loses fiscal base if Alberta exits
 *   - Fiscal Federalism Reform Coalition: Moderate agent (moderate/constrained) — sees constraint as temporary; working toward equalization reform or constitutional amendment to reduce arbitrage opportunity
 *   - Canadian Constitutional Order: Institutional observer (institutional/arbitrage) — formal rules are performative; real authority negotiated informally through fiscal power and political coalition
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(sovereignty_as_arbitrage, 0.52).
domain_priors:suppression_score(sovereignty_as_arbitrage, 0.68).
domain_priors:theater_ratio(sovereignty_as_arbitrage, 0.65).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(sovereignty_as_arbitrage, extractiveness, 0.52).
narrative_ontology:constraint_metric(sovereignty_as_arbitrage, suppression_requirement, 0.68).
narrative_ontology:constraint_metric(sovereignty_as_arbitrage, theater_ratio, 0.65).

% --- Constraint claim ---
narrative_ontology:constraint_claim(sovereignty_as_arbitrage, snare).
narrative_ontology:human_readable(sovereignty_as_arbitrage, "The Alberta Prosperity Project (State-Building Arbitrage)").
narrative_ontology:topic_domain(sovereignty_as_arbitrage, "political/economic").

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(sovereignty_as_arbitrage, separatist_political_leadership).
narrative_ontology:constraint_beneficiary(sovereignty_as_arbitrage, resource_extraction_corporations).
narrative_ontology:constraint_victim(sovereignty_as_arbitrage, federal_fiscal_redistribution_system).
narrative_ontology:constraint_victim(sovereignty_as_arbitrage, low_income_albertans).
narrative_ontology:constraint_victim(sovereignty_as_arbitrage, canadian_equalization_beneficiaries).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: FEDERAL EQUALIZATION SYSTEM (SNARE) — Cannot exit arbitrage exploitation. The constraint extracts via reframing: framing federal equalization as 'unfair redistribution' rather than constitutional fiscal federalism creates extraction narrative that justifies unilateral exit. d≈0.92, f(d)≈1.40, σ=1.0 → χ≈0.73.
constraint_indexing:constraint_classification(sovereignty_as_arbitrage, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(national))).

% PERSPECTIVE 2: LOW-INCOME ALBERTANS (SNARE) — Trapped in dual extraction: federal equalization reduces their purchasing power as inter-provincial transfers; separatist exit would eliminate federal social transfers (CPP, OAS, child benefits) without equivalent provincial replacement, leaving them exposed. Separatist narrative minimizes this cost. d≈0.88, f(d)≈1.35, σ=0.9 → χ≈0.62.
constraint_indexing:constraint_classification(sovereignty_as_arbitrage, snare,
    context(agent_power(powerless),
            time_horizon(generational),
            exit_options(trapped),
            spatial_scope(national))).

% PERSPECTIVE 3: EQUALIZATION-RECEIVING PROVINCES (SNARE) — Trapped. Alberta's separatist exit threatens the fiscal base of equalization, forcing fiscal contraction in Atlantic Canada, Quebec, and Manitoba. These provinces have no exit option and cannot defend the equalization mechanism (politically toxic federally). d≈0.90, f(d)≈1.38, σ=1.1 → χ≈0.79.
constraint_indexing:constraint_classification(sovereignty_as_arbitrage, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(continental))).

% PERSPECTIVE 4: ALBERTA ENERGY INDUSTRY (TANGLED ROPE) — Benefits from separatist framing (lower corporate tax threats, regulatory alignment with energy priorities, weakened federal environmental oversight) but constrained by Canadian continental trade integration (access to eastern refineries, continental grid, shared infrastructure). Extracts via political pressure; coordinated through industry associations. d≈0.35, f(d)≈0.33, σ=1.0 → χ≈0.17.
constraint_indexing:constraint_classification(sovereignty_as_arbitrage, tangled_rope,
    context(agent_power(organized),
            time_horizon(biographical),
            exit_options(constrained),
            spatial_scope(national))).

% PERSPECTIVE 5: SEPARATIST POLITICAL LEADERSHIP (ROPE) — Primary beneficiary. Experiences the constraint as coordination: mobilizing grievance narratives, organizing supporters, building institutional capacity for potential exit. Arbitrage access via political organizing and media platform. d≈0.08, f(d)≈-0.09, σ=0.9 → χ≈-0.04. Net beneficiary of the extraction mechanism.
constraint_indexing:constraint_classification(sovereignty_as_arbitrage, rope,
    context(agent_power(institutional),
            time_horizon(immediate),
            exit_options(arbitrage),
            spatial_scope(regional))).

% PERSPECTIVE 6: FISCAL FEDERALISM REFORM MOVEMENT (SCAFFOLD) — Sees the constraint as a temporary coordination failure with a sunset: equalization formula reform, devolution of power, or constitutional amendment could restructure the fiscal relationship and eliminate the arbitrage opportunity. d≈0.50, f(d)≈0.65, σ=1.0 → χ≈0.34. Moderate effective extraction because reform actors have agency and see a path forward within federalism.
constraint_indexing:constraint_classification(sovereignty_as_arbitrage, scaffold,
    context(agent_power(moderate),
            time_horizon(biographical),
            exit_options(constrained),
            spatial_scope(national))).

% PERSPECTIVE 7: CANADIAN CONSTITUTIONAL ORDER (PITON) — The formal constitutional rules (notwithstanding clause, sovereignty over natural resources, federal spending power) are substantially performative. Real authority is negotiated informally through fiscal power and political coalitions. Formal rules persist through institutional inertia despite functional degradation (equalization formula is outdated; interprovincial dispute resolution is weak). theater_ratio=0.65 approaches piton threshold. d≈0.05, f(d)≈-0.12, σ=1.0 → χ≈-0.04.
constraint_indexing:constraint_classification(sovereignty_as_arbitrage, piton,
    context(agent_power(institutional),
            time_horizon(civilizational),
            exit_options(arbitrage),
            spatial_scope(global))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(sovereignty_as_arbitrage_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(sovereignty_as_arbitrage, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(sovereignty_as_arbitrage, TypeOther, context(agent_power(organized), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(sovereignty_as_arbitrage, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

test(piton_threshold) :-
    domain_priors:theater_ratio(sovereignty_as_arbitrage, TR),
    TR >= 0.70.

:- end_tests(sovereignty_as_arbitrage_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.52): Moderate-high. The constraint extracts by enabling separatist leadership to capture political authority through grievance mobilization, and by enabling energy corporations to reduce oversight costs. But extraction is not at snare maximum (0.70+) because: (1) equalization transfers are legitimate federal fiscal mechanism, not pure rent-seeking; (2) energy corporations face real constraints (continental integration, trade agreements, climate policy); (3) separatist exit is materially possible (though costly) — victims are not absolutely trapped, only politically and economically constrained. Suppression (0.68): High. Significant barriers to exit or defense: federal equalization is politically taboo (defensible as constitutional fairness but not mobilizing); low-income Albertans lack political organization; equalization beneficiaries cannot organize collective defense without appearing to defend 'unfair transfers'; energy corporations' stakes are not transparent to voters. Theater ratio (0.65): Moderate-high. Separatist institutions perform institutional capacity-building (legislatures, governments, constitutional proposals) with genuine organizational function but also performative signaling (symbolic nationalism, grievance rituals). As separatist institutions mature, their function shifts from purely organizational to increasingly performative — governance theater without delivery of material separation goods.
 *
 * PERSPECTIVAL GAP:
 *   Separatist political leadership sees the constraint as coordination (Rope) — solving the problem of organizing political will for sovereignty. Energy corporations see a mixed coordination-extraction hybrid (Tangled Rope) — both benefiting from reduced oversight and constrained by continental integration. Low-income Albertans see pure extraction (Snare) — losing federal transfers without equivalent provincial replacement. Federal equalization system sees extraction (Snare) — reframed as unfair without agency to defend. Equalization-receiving provinces see extraction (Snare) — losing fiscal base. Fiscal federalism reformers see a temporary problem with a sunset (Scaffold) — equalization reform or constitutional amendment could restructure relationships. The Canadian constitutional order sees its own degraded formal rules (Piton) — theater of constitutional federalism masks real negotiation of power through fiscal coalitions and informal hierarchy. The perspectival gap reveals the constraint's true structure: what appears as coordination to separatist leadership appears as pure extraction to those with no political voice.
 *
 * DIRECTIONALITY LOGIC:
 *   Separatist leadership: Beneficiary + arbitrage → d≈0.08, f(d)≈-0.09. Net beneficiary. Energy corporations: Beneficiary + constrained → d≈0.35, f(d)≈0.33. Moderate extraction benefit offset by continental constraints. Federal equalization: Victim + trapped → d≈0.92, f(d)≈1.40. Maximum extraction — abstract system with no agency. Low-income Albertans: Victim + trapped → d≈0.88, f(d)≈1.35. Severe extraction — vulnerable population with no alternative. Equalization-receiving provinces: Victim + trapped → d≈0.90, f(d)≈1.38. Severe extraction — institutional actors constrained by federal structure. Fiscal federalism reformers: Moderate + constrained → d≈0.50, f(d)≈0.65. Low effective extraction because they see a path forward and have some policy agency. Constitutional order: Institutional + arbitrage → d≈0.05, f(d)≈-0.12. Formal rules are net beneficial (or neutral) to system stability — extraction happens through informal power, not formal structure.
 *
 * MANDATROPHY ANALYSIS:
 *   SNARE CONFIRMED (ε=0.52, suppression=0.68, χ≈0.68). The constraint resolves the mandatrophy by demonstrating that separatist state-building arbitrage is extraction from those with no exit option (federal equalization, low-income populations, equalization-receiving provinces), not coordination. The beneficiary narrative ('unlock Alberta prosperity through sovereignty') obscures structural asymmetry: beneficiaries (leadership, energy corporations) have exit options (separatist government, capital mobility); victims do not. The theater_ratio increase (0.40→0.65) indicates Goodhart drift: separatist institutions increasingly focus on performative institutional capacity-building (governance rituals, constitutional theater) rather than solving actual equalization problems. The classification as snare is robust across multiple perspectives (powerless agents all see extraction) while beneficiaries see rope (coordination), confirming the perspectival structure of extraction: the extractor experiences it as coordination-building, the victim experiences it as pure coercion.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    equalization_fairness_threshold,
    'What transfer level threshold distinguishes legitimate fiscal federalism from extractive redistribution?',
    'Comparative analysis of equalization ratios across federal systems (Australia, Germany, Mexico); historical analysis of how ratios have changed relative to resource base volatility',
    'If threshold < 5% of provincial revenue: current equalization is marginal (snare classification weakens). If threshold > 15%: current system is severe extraction (snare confirmed). Current Alberta transfer rate ~12%.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(equalization_fairness_threshold, empirical, 'Equalization threshold for fairness vs extraction').

omega_variable(
    separation_economic_viability,
    'Can an independent Alberta sustain its current welfare state and services without federal transfers and equalization contributions?',
    'Fiscal modeling of separation scenario: revenue projection (oil/gas volatility, tax base, investment flows) vs expenditure requirements (healthcare, education, pensions, debt servicing). Comparison with Scotland, Catalonia independence models.',
    'If viable (>95% revenue autonomy): snare framing collapses — separation is real option, not trap. If non-viable (<85%): victims genuinely trapped — snare confirmed. Current estimates: 70-80% viable depending on commodity prices.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(separation_economic_viability, empirical, 'Whether Alberta separation is economically viable').

omega_variable(
    narrative_capture_mechanism,
    'Does the separatist narrative (''we pay, they benefit'') accurately represent Alberta''s fiscal position, or does it obscure Alberta''s benefits from federal programs and national infrastructure?',
    'Full accounting: calculate total federal spending in Alberta (military, research, infrastructure, transfer programs) vs federal revenue collected. Compare to provincial contribution to other provinces'' welfare costs.',
    'If Alberta net beneficiary: snare framing is false narrative (constraint is tangled_rope, not snare). If Alberta net payer by >10%: snare framing is accurate (snare confirmed). Current data: Alberta is net contributor ~$5-8B annually but also receives significant federal military/infrastructure spending.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(narrative_capture_mechanism, empirical, 'Accuracy of separatist fiscal narrative').

omega_variable(
    institutional_coalition_stability,
    'Can separatist political leadership sustain a unified coalition without delivering material economic gains from separation?',
    'Tracking of separatist party support over time; analysis of coalition fragmentation in comparable movements (Catalan independence, Scottish independence); exit surveys of separatist voters.',
    'If coalition fragments without delivery: separatist snare is actually an aspiring-leader extraction mechanism masked as popular movement (snare confirmed for different reasons). If coalition holds: genuine mass movement (snare classification maintained but with different beneficiary structure).',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(institutional_coalition_stability, empirical, 'Stability of separatist political coalition').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(sovereignty_as_arbitrage, 0, 16).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(sov_arb_tr_t0, sovereignty_as_arbitrage, theater_ratio, 0, 0.4).
narrative_ontology:measurement(sov_arb_tr_t8, sovereignty_as_arbitrage, theater_ratio, 8, 0.52).
narrative_ontology:measurement(sov_arb_tr_t16, sovereignty_as_arbitrage, theater_ratio, 16, 0.65).

% Extraction over time
narrative_ontology:measurement(sov_arb_be_t0, sovereignty_as_arbitrage, base_extractiveness, 0, 0.32).
narrative_ontology:measurement(sov_arb_be_t8, sovereignty_as_arbitrage, base_extractiveness, 8, 0.42).
narrative_ontology:measurement(sov_arb_be_t16, sovereignty_as_arbitrage, base_extractiveness, 16, 0.52).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(sovereignty_as_arbitrage, enforcement_mechanism).
narrative_ontology:affects_constraint(sovereignty_as_arbitrage, canadian_equalization_system).
narrative_ontology:affects_constraint(sovereignty_as_arbitrage, interprovincial_fiscal_federalism).

% DUAL FORMULATION NOTE:
% Sovereignty-as-arbitrage is downstream of the Canadian equalization system and interprovincial fiscal federalism constraints. The upstream equalization constraint has ε≈0.15 (legitimate fiscal mechanism); the arbitrage constraint has ε=0.52 (extraction opportunity). The downstream constraint reveals extractive dynamics latent in the upstream structure.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(sovereignty_as_arbitrage, institutional, 0.88).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
