% ============================================================================
% CONSTRAINT STORY: price_formation_kernel__georgist_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-12
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_price_formation_kernel__georgist_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: price_formation_kernel__georgist_reading
 *   human_readable: Land Rent Extraction via Price Formation (Georgist Reading)
 *   domain: political_economy/housing_markets/institutional_analysis
 *
 * SUMMARY:
 *   The georgist reading asserts that housing price formation separates two
 *   economically distinct phenomena: land rent (location-scarcity-based,
 *   unearned, fixed-supply) and improvement value (labor-and-capital-based,
 *   earned, producible). Under this reading, the constraint is a tangled
 *   rope: the improvement component is genuine coordination (architects,
 *   builders, financiers work together to produce housing); the land
 *   component is pure extraction (incumbent owners capture appreciation
 *   generated by surrounding development and demographic demand, without
 *   producing anything). The price formation itself enforces the regime by
 *   making the land-rent component liquid and capitalizable through mortgage
 *   debt, which concentrates it into the hands of those with access to
 *   credit. The reading conflicts structurally with naturalist
 *   (price-as-equilibrium), institutional (price-as-constructed), and
 *   financialization (price-as-credit-driven) framings—not because those
 *   readings are false, but because they deny or subsume the land-rent
 *   distinction as the primary causal mechanism.
 *
 * KEY AGENTS:
 *   - incumbent_landowners: hold location-based unearned income; high power, arbitrage exit
 *   - aspiring_homebuyers: must pay the rent extraction as a forced cost of participation; powerless, trapped
 *   - renters: continuously pay rent that capitalizes land value; powerless, constrained exit
 *   - financial_intermediaries: originate debt that capitalizes land-rent expectations; institutional power, arbitrage
 *   - labor_intensive_producers: compete with speculators for space; moderate power, constrained by rent burden
 *   - improvers: benefit from active construction, but capped by landowner capture of appreciation
 *   - planning_authorities: hold the power to alter tax treatment or enforce land-value capture, but are captured
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(price_formation_kernel__georgist_reading, 0.78).
domain_priors:suppression_score(price_formation_kernel__georgist_reading, 0.72).
domain_priors:theater_ratio(price_formation_kernel__georgist_reading, 0.48).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, extractiveness, 0.78).
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, suppression_requirement, 0.72).
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, theater_ratio, 0.48).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, accessibility_collapse, 0.62).
narrative_ontology:constraint_metric(price_formation_kernel__georgist_reading, resistance, 0.58).

% --- Constraint claim ---
narrative_ontology:constraint_claim(price_formation_kernel__georgist_reading, tangled_rope).
narrative_ontology:human_readable(price_formation_kernel__georgist_reading, "Land Rent Extraction via Price Formation (Georgist Reading)").
narrative_ontology:topic_domain(price_formation_kernel__georgist_reading, "political_economy/housing_markets/institutional_analysis").

domain_priors:requires_active_enforcement(price_formation_kernel__georgist_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(price_formation_kernel__georgist_reading, '69dcdf4b-40d3-487d-a04c-d2a8b2870433').
narrative_ontology:cs_kernel_codification('69dcdf4b-40d3-487d-a04c-d2a8b2870433', distributed).
narrative_ontology:cs_authority_grounding('69dcdf4b-40d3-487d-a04c-d2a8b2870433', extraction).
narrative_ontology:cs_interpretation_layer_present('69dcdf4b-40d3-487d-a04c-d2a8b2870433').
narrative_ontology:cs_reading_relation('69dcdf4b-40d3-487d-a04c-d2a8b2870433', price_formation_kernel__naturalist_reading, coexists_with).
narrative_ontology:cs_reading_relation('69dcdf4b-40d3-487d-a04c-d2a8b2870433', price_formation_kernel__institutional_reading, influences).
narrative_ontology:cs_reading_relation('69dcdf4b-40d3-487d-a04c-d2a8b2870433', price_formation_kernel__financialization_reading, coexists_with).
narrative_ontology:cs_axiom('69dcdf4b-40d3-487d-a04c-d2a8b2870433', foundational, land_value_unearned_by_incumbent_owner).
narrative_ontology:cs_axiom_status(land_value_unearned_by_incumbent_owner, holdable).
narrative_ontology:cs_axiom_grounding('69dcdf4b-40d3-487d-a04c-d2a8b2870433', land_value_unearned_by_incumbent_owner, empirically_contingent).
narrative_ontology:cs_axiom('69dcdf4b-40d3-487d-a04c-d2a8b2870433', foundational, location_scarcity_is_intrinsic_not_produced).
narrative_ontology:cs_axiom_status(location_scarcity_is_intrinsic_not_produced, holdable).
narrative_ontology:cs_axiom_grounding('69dcdf4b-40d3-487d-a04c-d2a8b2870433', location_scarcity_is_intrinsic_not_produced, empirically_contingent).
narrative_ontology:cs_axiom('69dcdf4b-40d3-487d-a04c-d2a8b2870433', secondary, rent_extraction_requires_legal_enforcement).
narrative_ontology:cs_axiom_status(rent_extraction_requires_legal_enforcement, holdable).
narrative_ontology:cs_axiom_grounding('69dcdf4b-40d3-487d-a04c-d2a8b2870433', rent_extraction_requires_legal_enforcement, deontological).
narrative_ontology:cs_reference_frame('69dcdf4b-40d3-487d-a04c-d2a8b2870433', land_value_earned_by_ownership).
narrative_ontology:cs_drift_state('69dcdf4b-40d3-487d-a04c-d2a8b2870433', contemporary_housing_affordability_crisis, gap(authority_erosion, substantial, false)).
narrative_ontology:cs_created_at('69dcdf4b-40d3-487d-a04c-d2a8b2870433', '').
narrative_ontology:cs_kernel_id(price_formation_kernel__georgist_reading, price_formation_kernel).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(price_formation_kernel__georgist_reading, incumbent_landowners).
narrative_ontology:constraint_beneficiary(price_formation_kernel__georgist_reading, financial_intermediaries).
narrative_ontology:constraint_victim(price_formation_kernel__georgist_reading, aspiring_homebuyers).
narrative_ontology:constraint_victim(price_formation_kernel__georgist_reading, renters).
narrative_ontology:constraint_victim(price_formation_kernel__georgist_reading, labor_intensive_producers).
% Derived from stakeholders[] roles (beneficiary->beneficiary, payer->victim;
% agent-gated; excluded derives nothing; deduped against the authored arrays).
narrative_ontology:constraint_beneficiary(price_formation_kernel__georgist_reading, improvers).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Hold land parcels whose value appreciates passively through location scarcity and surrounding development. Capture the difference between their acquisition cost and current market price without having improved the land itself. Their political weight is concentrated—few owners controlling large holdings—and they deploy it to defend property-rights frameworks that protect rent capture. Exit for them is trivial: they can hold, sell, or leverage the appreciated value through debt instruments.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, incumbent_landowners, beneficiary,
    organized, generational, arbitrage, national).
narrative_ontology:stakeholder_secondary_role(price_formation_kernel__georgist_reading, incumbent_landowners, agenda_setter).

% Must bid against incumbent owners and speculators for land in desirable locations. The land-value component of the final price is unearned income flowing to sellers, not payment for anything the buyer receives beyond location access. Their exit options are heavily constrained: without access to owner-occupied housing in job-market hubs, career and wealth-building pathways narrow. They absorb the rent extraction as a forced cost of economic participation.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, aspiring_homebuyers, payer,
    powerless, biographical, trapped, local).

% Compete for rental housing in markets where rents capitalize the land-value component. Landlords pass through the rent extraction to tenants, who have limited geographic mobility and face near-zero exit options in tight housing markets. They bear the unearned-income extraction directly and continuously, with no asset accumulation benefit.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, renters, payer,
    powerless, immediate, constrained, local).

% Originate and service mortgage debt that capitalizes land-rent expectations into present prices. They benefit from the inflation of housing prices (higher loan origination volumes, higher collateral values, higher interest revenue on larger principal amounts). They also benefit from price volatility that creates refinancing and derivatives demand. They enforce the price-formation regime by refusing to finance purchases that don't conform to their models of land-value capitalization.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, financial_intermediaries, beneficiary,
    institutional, generational, arbitrage, global).

% Manufacturers, artisans, small-business owners who need industrial or retail space. They compete with financial speculators and incumbent landowners for locations. Rent extraction on land reduces capital available for wages, reinvestment, and productive expansion. They cannot fully pass the rent burden to customers (who face their own budget constraints) and must absorb it, limiting their growth and competitiveness relative to firms in lower-rent jurisdictions.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, labor_intensive_producers, payer,
    moderate, biographical, constrained, regional).

% Contractors, architects, tradespeople, engineers who build the improvements on land. They benefit from active construction and renovation activity—the improvement component of housing value is genuinely earned through their labor and expertise. However, their earnings are capped and volatile because landowner capture of appreciation reduces the return on capital for development projects, limiting the flow of improvement-demanding work.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, improvers, beneficiary,
    moderate, biographical, mobile, regional).

% Enforce zoning, building codes, and title systems that legally instantiate the land-improvement distinction in deed and conveyance. They have the power to alter the tax treatment, enforce value-capture mechanisms (land value taxes, betterment charges), or mandate separation of land rent from improvement sales. Their institutional inertia and political capture by incumbent landowners keeps them from deploying this power.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, planning_and_regulatory_authorities, agenda_setter,
    institutional, generational, analytical, national).

% Political and intellectual movements that articulate this reading and propose remedies (land value taxation, community land trusts, site-value capture mechanisms). They lack concentrated institutional power but carry the structural truth claim forward and link it to reform agendas.
narrative_ontology:constraint_stakeholder(price_formation_kernel__georgist_reading, georgist_advocacy_movements, observer,
    powerless, generational, analytical, national).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(price_formation_kernel__georgist_reading, incumbent_landowners).
narrative_ontology:fixing_cost_class(price_formation_kernel__georgist_reading, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Price formation establishes a shared metric (monetary value) that allows exchange of heterogeneous goods and allocates land across competing uses via revealed preference. The improvement component genuinely coordinates labor, capital, and materials into productive structures. The land component merely licenses access to location scarcity, which is fixed and inherent, not produced.
% TRANSFER_FUNCTION: Transfers unearned income (land-value appreciation) from aspiring participants to incumbent landowners and financial intermediaries who capitalize the land value. The improvement component is payment for actual work done. The rent extraction compounds over time as location demand grows, and it is structurally asymmetric: incumbent holders capture appreciation without production; newcomers must bid against that captured value with their own earned income.
% ABSENT_VOICES: Competing price-formation theories (naturalist equilibrium, institutional construction, financialization-driven) are structurally excluded from this framing. Their adherents would argue that separating land from improvements is an artificial distinction, or that institutional factors are primary, or that credit dynamics dominate. Under this reading, they are excluded because the reading asserts the land-rent distinction is empirically real and theoretically foundational, not constructed or secondary.
% DISAPPEARANCE_RATIONALE: If this reading's rent-separation mechanism were operationally recognized and taxed away (land value captured for public purposes, improvement value left to owners), housing prices would fall dramatically, rental costs would compress, land would reallocate from speculation to productive use, and the wealth-extraction flow from aspiring participants to incumbent owners would cease. The current price formation persists because the rent extraction is naturalized (treated as market equilibrium) rather than recognized as enforced transfer.
% FOUNDING_PROBLEM: Early industrial societies faced land monopoly: productive workers and new businesses needed access to location, but land title was concentrated in hereditary aristocracy. Price formation was supposed to solve this by allowing land to be bought and sold in markets, making location access contestable on price rather than birth. But financial capitalism's emergence created a new mechanism: mortgages that capitalize future rent expectations into present prices, reconstituting the functional monopoly under a democratic appearance.
% FOUNDING_PROBLEM_CORROBORATION: Georgist economists and land-reform advocates attest the founding problem persists and has worsened (Piketty, Graeber on historic debt cycles; contemporary housing-affordability research documenting the land-value share of housing price). Incumbent landowners and mainstream economic theory attest the problem is solved (markets freely allocate land; price reflects utility). Institutional scholars (Zuboff on surveillance capital, Ostrom on commons) document the mechanisms by which 'market' prices are constructed by regulatory frameworks, not natural equilibrium—supporting the reading that price formation is enforced, not spontaneous.
narrative_ontology:disappearance_verdict(price_formation_kernel__georgist_reading, world_rearranges).
narrative_ontology:founding_problem_status(price_formation_kernel__georgist_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(price_formation_kernel__georgist_reading, 'e03e2210ef39e1af4d109acadf9515e5d2d8b7d7',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_haiku3', 'agent/example_platform_commission.json',
    'claude-haiku-4-5-20251001', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(price_formation_kernel__georgist_reading, 'none', 1).
narrative_ontology:epsilon_provenance(price_formation_kernel__georgist_reading, 0.78, 'claude-haiku-4-5-20251001', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(price_formation_kernel__georgist_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(price_formation_kernel__georgist_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(price_formation_kernel__georgist_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is high (0.78 at interval end) because the land-value component of housing prices is unearned income in the strict sense—it does not compensate the landowner for any production or risk-bearing they engaged in. The appreciation is generated by surrounding development and demographic demand, which the landowner captures without producing. Suppression is also high (0.72) because the regime's persistence depends on active legal enforcement: title systems that prohibit seizure of land-rent without compensation, mortgage systems that refuse to finance alternative arrangements, regulatory capture that prevents land-value taxation. Theater is moderate-to-high (0.48) because the price formation is presented as 'market clearing' and 'equilibrium discovery,' when it is structurally a redistribution mechanism enforced by institutional design. The measurement series track the constraint over 40 time periods: extractiveness rises as credit expansion inflates land values relative to improvement costs, and suppression tightens as incumbent interests defend the rent-capture mechanism against tax and regulatory proposals.
 *
 * PERSPECTIVAL GAP:
 *   From the landowner and financial-intermediary seats, price formation is a rope: it solves the coordination problem of matching land to productive use, permits capital to finance improvements, and creates wealth incentives for maintenance and development. The appreciation is treated as the justified return to holding a productive asset. From the aspiring-homebuyer and renter seats, the same structure is a snare: they are forced to bid against owners' capture of unearned appreciation, they cannot escape the market (location is a necessity), and the enforcement (mortgage underwriting, legal title) keeps them trapped. The engine should compute the constraint as different types from different power atoms: institutional agenda-setter (owners) sees rope; powerless targets see snare. The divergence is not perceptual noise—it reflects a real structural asymmetry in how the constraint operates on different agents.
 *
 * DIRECTIONALITY LOGIC:
 *   Incumbent landowners and financial intermediaries sit at d ≈ 0.0–0.1 (beneficiaries): they collect rent without enforcement cost, have high mobility (can hold, sell, or leverage), and face zero exit friction. Aspiring homebuyers and renters sit at d ≈ 0.85–1.0 (full targets): they cannot exit (location is necessary, housing is a necessity good), they are powerless (atomized, unorganized), and the constraint's enforcement (mortgage underwriting, title law, zoning) falls entirely on them as barriers to participation. Labor-intensive producers sit at d ≈ 0.6–0.7: they bear rent costs that depress their returns, but retain some negotiation power (can locate in lower-rent regions, though with friction). Improvers sit at d ≈ 0.3–0.4: they benefit from construction activity, but their margins are compressed by landowner capture of appreciation. The directionality divergence is fundamental: the incumbents perceive price formation as coordination (unified market, efficient allocation); the targets perceive it as extraction (forced transfer of earned income to owners).
 *
 * MANDATROPHY ANALYSIS:
 *   The constraint carries a mandatrophy signal: the founding problem (land monopoly making location inaccessible except through hereditary aristocracy) was solved by introduction of land markets in the 19th century. However, the market mechanism itself created a new rent-extraction path through mortgage capitalization. The constraint persists not because the founding problem is live, but because the beneficiaries (incumbent owners and financial intermediaries) have rebuilt their monopoly under a market appearance. The theater_ratio's gradual rise (0.25 → 0.48) suggests the 'market efficiency' framing is increasingly performative—the constraint's actual function is rent capture, not price discovery. This is a classic case where classification should diverge from founding-problem status: the founding problem is dead, but the constraint is alive precisely because it has been repurposed. The classification as tangled_rope (not rope) reflects this: genuine coordination (improvement production) is real, but the enforcement machinery exists primarily to protect extraction (land-rent capture).
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    land_value_measurability,
    'Can land value be reliably separated from improvement value in real markets, or is the distinction analytically sound but practically inseparable in observed prices?',
    'Comparative institutional study of jurisdictions with explicit land-value taxation (Denmark, Estonia, Singapore) examining whether the tax creates a revealed-market distinction or whether improvement and land values remain functionally bundled.',
    'If separable and observable, the extraction mechanism is empirically precise and remedies (land-value capture) are technically feasible. If inseparable, the georgist distinction is theoretically valid but policy interventions must be less granular (e.g., broad anti-speculation taxes rather than surgical land-value capture).',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(land_value_measurability, empirical, 'Whether land-value separation is empirically observable or analytically sound but practically bundled.').

omega_variable(
    reading_foreclosure_test,
    'Does the georgist assertion that land-value is an unearned income claim logically foreclose the naturalist reading that price reflects objective scarcity and preference, or do the readings represent incommensurable theories that coexist?',
    'Philosophical analysis of the axioms: if naturalism asserts ''all value is earned by meeting demand (including demand for location scarcity)'' and georgism asserts ''location scarcity creates unearned income for incumbents,'' these seem contradictory. Resolution: either one forecloses the other (tight logical relation), or they represent different normative framings of the same empirical fact (coexistence with different policy implications).',
    'If forecloses: the reading relations should show forecloses, not coexists_with. If coexists: they are different policy frameworks applied to a shared empirical object. The distinction affects how competing readings are weighted in institutional design.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(reading_foreclosure_test, conceptual, 'Whether georgism and naturalism are logically incompatible or represent different normative readings of the same price data.').

omega_variable(
    financial_intermediary_role_ambiguity,
    'Are financial intermediaries (mortgage lenders) structural beneficiaries of the rent-extraction regime, or are they neutral conduits that would operate identically under any price-formation system?',
    'Comparative institutional analysis: studying mortgage markets in jurisdictions with different land-tax regimes (Denmark with land-value tax vs. US with property tax) to assess whether lender behavior and profitability change when land-value extraction is decoupled from private ownership.',
    'If financial intermediaries are structural beneficiaries, they are politically aligned with incumbent landowners and form a coalition defending the regime. If neutral, they are only incidental supporters. This affects the political economy of reform: is the coalition permanent, or can financial intermediaries be neutralized by alternative financing models?',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(financial_intermediary_role_ambiguity, empirical, 'Whether financial intermediaries'' interests are tied to land-rent capture or whether they would adapt to alternative systems.').

omega_variable(
    improvement_coordination_purity,
    'Is the improvement component of housing production genuinely a rope (pure coordination with voluntary participation and net benefits), or does it contain extractive elements tied to the land-rent regime?',
    'Comparative cost analysis of construction in high-rent vs. low-rent markets, controlling for material costs and labor rates. If improvement-value costs are higher in high-rent markets independent of supply/demand for construction services, extraction is layered into the improvement component.',
    'If the improvement component is pure rope, addressing the land-rent extraction leaves the coordination intact. If extraction is layered, the constraint is less separable and remedies (land-value taxation) must be paired with construction-cost control or subsidy.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(improvement_coordination_purity, empirical, 'Whether improvement-value production is a pure coordination or contains tied extraction.').

omega_variable(
    kernel_reading_identity,
    'Is the georgist reading historically grounded in an actual kernel (Georgist economics as a coherent doctrine), or is it a retrospective framing applied to housing markets for analytical purposes?',
    'Historiography: examining whether Henry George and his intellectual heirs articulated the land-rent distinction as a theory of price formation, or whether the reading is constructed post hoc by contemporary analysts applying the distinction to observed housing dynamics.',
    'If historically grounded, the reading is an explicit doctrine with a tradition of corroboration and critique. If retrospective, the reading is analytically sound but lacks lineage authority, which affects how institutional actors treat it as legitimate knowledge.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(kernel_reading_identity, empirical, 'Whether the georgist reading has historical lineage or is a contemporary analytical construction.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(price_formation_kernel__georgist_reading, 0, 40).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(pric_tr_t0, price_formation_kernel__georgist_reading, theater_ratio, 0, 0.25).
narrative_ontology:measurement(pric_tr_t8, price_formation_kernel__georgist_reading, theater_ratio, 8, 0.32).
narrative_ontology:measurement(pric_tr_t16, price_formation_kernel__georgist_reading, theater_ratio, 16, 0.38).
narrative_ontology:measurement(pric_tr_t24, price_formation_kernel__georgist_reading, theater_ratio, 24, 0.43).
narrative_ontology:measurement(pric_tr_t32, price_formation_kernel__georgist_reading, theater_ratio, 32, 0.46).
narrative_ontology:measurement(pric_tr_t40, price_formation_kernel__georgist_reading, theater_ratio, 40, 0.48).

% Extraction over time
narrative_ontology:measurement(pric_be_t0, price_formation_kernel__georgist_reading, base_extractiveness, 0, 0.52).
narrative_ontology:measurement(pric_be_t8, price_formation_kernel__georgist_reading, base_extractiveness, 8, 0.61).
narrative_ontology:measurement(pric_be_t16, price_formation_kernel__georgist_reading, base_extractiveness, 16, 0.68).
narrative_ontology:measurement(pric_be_t24, price_formation_kernel__georgist_reading, base_extractiveness, 24, 0.74).
narrative_ontology:measurement(pric_be_t32, price_formation_kernel__georgist_reading, base_extractiveness, 32, 0.77).
narrative_ontology:measurement(pric_be_t40, price_formation_kernel__georgist_reading, base_extractiveness, 40, 0.78).

% Suppression requirement over time
narrative_ontology:measurement(pric_su_t0, price_formation_kernel__georgist_reading, suppression_requirement, 0, 0.58).
narrative_ontology:measurement(pric_su_t8, price_formation_kernel__georgist_reading, suppression_requirement, 8, 0.63).
narrative_ontology:measurement(pric_su_t16, price_formation_kernel__georgist_reading, suppression_requirement, 16, 0.67).
narrative_ontology:measurement(pric_su_t24, price_formation_kernel__georgist_reading, suppression_requirement, 24, 0.7).
narrative_ontology:measurement(pric_su_t32, price_formation_kernel__georgist_reading, suppression_requirement, 32, 0.71).
narrative_ontology:measurement(pric_su_t40, price_formation_kernel__georgist_reading, suppression_requirement, 40, 0.72).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(price_formation_kernel__georgist_reading, resource_allocation).
narrative_ontology:boltzmann_floor_override(price_formation_kernel__georgist_reading, 0.18).
narrative_ontology:affects_constraint(price_formation_kernel__georgist_reading, price_formation_kernel__naturalist_reading).
narrative_ontology:affects_constraint(price_formation_kernel__georgist_reading, price_formation_kernel__institutional_reading).
narrative_ontology:affects_constraint(price_formation_kernel__georgist_reading, price_formation_kernel__financialization_reading).

% DUAL FORMULATION NOTE:
% The price_formation_kernel decomposes into four constraints, one per reading: georgist (this story), naturalist, institutional, financialization. Each reading instantiates a different ε (structurally different mechanisms) and therefore is a separate constraint. They share the same referent (housing price formation) but differ in which causal mechanisms are held to be primary and which agents are identified as beneficiaries/victims. The georgist reading claims land-rent extraction is the primary mechanism; siblings deny or subsume it. The network edges model that each reading's adoption would create downstream pressure on the others' policy viability.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(price_formation_kernel__georgist_reading, institutional, 0.15).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
