% ============================================================================
% CONSTRAINT STORY: ai_nonconsensual_content_facilitation
% ============================================================================
% Version: 6.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-05-21
% ============================================================================

:- module(constraint_ai_nonconsensual_content_facilitation, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: ai_nonconsensual_content_facilitation
 *   human_readable: Facilitation of AI-Generated Non-Consensual Sexual Content on Social Media Platforms
 *   domain: technological
 *
 * SUMMARY:
 *   Social media platforms, particularly X, operate with policies and technical
 *   affordances that enable and facilitate the rapid creation and viral
 *   dissemination of non-consensual sexual images generated by AI. This
 *   dynamic creates profound and asymmetric harm for the targets while
 *   generating engagement and potential revenue for the platform and the
 *   content creators.
 *
 * KEY AGENTS (by structural relationship):
 *   - targets_of_harassment: Primary target (powerless/trapped) — individuals whose likenesses are used without consent, bearing severe reputational and psychological costs.
 *   - platform_operator: Primary beneficiary (institutional/arbitrage) — benefits from engagement generated by viral content, with legal shields limiting direct liability.
 *   - malicious_content_creators: Secondary beneficiary (organized/mobile) — benefit from attention, social status, or financial gain derived from creating and sharing the content.
 *   - analytical_observer: Analytical observer — sees the full structure of coordination and extraction.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(ai_nonconsensual_content_facilitation, 0.75).
domain_priors:suppression_score(ai_nonconsensual_content_facilitation, 0.80).   % Structural property (raw, unscaled).
domain_priors:theater_ratio(ai_nonconsensual_content_facilitation, 0.40).       % Piton detection (>= 0.70)

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(ai_nonconsensual_content_facilitation, extractiveness, 0.75).
narrative_ontology:constraint_metric(ai_nonconsensual_content_facilitation, suppression_requirement, 0.80).
narrative_ontology:constraint_metric(ai_nonconsensual_content_facilitation, theater_ratio, 0.40).

% --- Constraint claim (must match analytical perspective type) ---
narrative_ontology:constraint_claim(ai_nonconsensual_content_facilitation, tangled_rope).
narrative_ontology:human_readable(ai_nonconsensual_content_facilitation, "Facilitation of AI-Generated Non-Consensual Sexual Content on Social Media Platforms").
narrative_ontology:topic_domain(ai_nonconsensual_content_facilitation, "technological").

% --- Binary flags ---
domain_priors:requires_active_enforcement(ai_nonconsensual_content_facilitation). % Required for Tangled Rope. The platform's stated goal of being a safe public square requires enforcement, which is failing.

% --- Structural relationships (REQUIRED for non-mountain constraints) ---
% These feed the directionality derivation chain: the engine computes
% d (directionality) from agent membership in these groups + exit_options.

% Who benefits from this constraint existing?
narrative_ontology:constraint_beneficiary(ai_nonconsensual_content_facilitation, platform_operator).
narrative_ontology:constraint_beneficiary(ai_nonconsensual_content_facilitation, malicious_content_creators).
%
% Who bears disproportionate cost?
narrative_ontology:constraint_victim(ai_nonconsensual_content_facilitation, targets_of_harassment).
%
% Gate requirements:
%   Tangled Rope: beneficiary + victim + requires_active_enforcement (all three met)

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   χ = ε × f(d) × σ(S)
   where f(d) is the sigmoid directionality function:
     f(d) = -0.20 + 1.70 / (1 + e^(-6*(d - 0.50)))
   The engine derives d from beneficiary/victim membership + exit_options.
   Scope modifiers: local=0.8, regional=0.9, national=1.0,
                    continental=1.1, global=1.2, universal=1.0.
   CONTEXT ARITY: All context() terms must have exactly 4 arguments.
   ========================================================================== */

% PERSPECTIVE 1: THE PRIMARY TARGET (SNARE)
% Agent who bears the most extraction. Engine derives d from:
%   victim membership + trapped exit → d ≈ 0.95 → f(d) ≈ 1.42 → high χ
% The victim experiences this as a pure trap with no coordination benefit.
constraint_indexing:constraint_classification(ai_nonconsensual_content_facilitation, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(global))).

% PERSPECTIVE 2: THE PRIMARY BENEFICIARY (ROPE)
% Agent who benefits most. Engine derives d from:
%   beneficiary membership + arbitrage exit → d ≈ 0.05 → f(d) ≈ -0.12 → low/negative χ
% The platform sees its own system as a coordination tool, with harms being
% negative externalities that are managed or absorbed.
constraint_indexing:constraint_classification(ai_nonconsensual_content_facilitation, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 3: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% Default analytical context (civilizational/analytical/global).
% This view recognizes both the platform's coordination function and the
% severe, asymmetric extraction it enables. It satisfies all gates for a
% Tangled Rope classification.
constraint_indexing:constraint_classification(ai_nonconsensual_content_facilitation, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

% PERSPECTIVE 4: THE CONTENT CREATOR (ROPE)
% A secondary beneficiary. Engine derives d from:
%   beneficiary membership + mobile exit → d ≈ 0.15 → f(d) ≈ -0.01 → low χ
% For the malicious actor, the platform is a pure coordination tool for
% gaining attention and influence, with no perceived costs.
constraint_indexing:constraint_classification(ai_nonconsensual_content_facilitation, rope,
    context(agent_power(organized),
            time_horizon(biographical),
            exit_options(mobile),
            spatial_scope(global))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(ai_nonconsensual_content_facilitation_tests).

test(perspectival_gap_target_vs_beneficiary) :-
    constraint_indexing:constraint_classification(ai_nonconsensual_content_facilitation, snare, context(agent_power(powerless), _, exit_options(trapped), _)),
    constraint_indexing:constraint_classification(ai_nonconsensual_content_facilitation, rope, context(agent_power(institutional), _, exit_options(arbitrage), _)),
    true.

test(tangled_rope_analytical_view) :-
    constraint_indexing:constraint_classification(ai_nonconsensual_content_facilitation, tangled_rope, context(agent_power(analytical), _, _, _)).

test(threshold_validation_high_extraction) :-
    domain_priors:base_extractiveness(ai_nonconsensual_content_facilitation, E),
    domain_priors:suppression_score(ai_nonconsensual_content_facilitation, S),
    E >= 0.46,
    S >= 0.60.

:- end_tests(ai_nonconsensual_content_facilitation_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   The scores reflect a system where a legitimate coordination technology
 *   (a global social media platform) has been weaponized for severe, targeted
 *   harassment with ineffective or indifferent moderation.
 *   - Base Extractiveness (ε=0.75): Extremely high, reflecting the profound,
 *     asymmetric psychological, reputational, and professional harm inflicted
 *     on victims.
 *   - Suppression Score (s=0.80): High. Victims have few effective remedies.
 *     Legal recourse is slow and jurisdictionally complex, while platform
 *     takedown mechanisms are easily overwhelmed and circumvented, trapping
 *     the victim in a cycle of abuse.
 *   - Theater Ratio (τ=0.40): Non-trivial. Platforms issue statements and
 *     policy updates that give the appearance of action, but the underlying
 *     technical and policy reality changes little, indicating a significant
 *     degree of performative compliance.
 *
 * PERSPECTIVAL GAP:
 *   The gap is extreme. For a victim (powerless, trapped), the platform is
 *   an inescapable Snare, a machine for generating harm. For the platform
 *   operator (institutional, arbitrage), it is a Rope—a valuable coordination
 *   tool whose negative externalities (harassment) are a manageable business
 *   cost, balanced against engagement metrics. Malicious creators also see a
 *   Rope, a tool for their own ends. The analytical observer sees a Tangled
 *   Rope, recognizing that the platform's legitimate coordination function is
 *   inseparably entangled with a severe extractive mechanism.
 *
 * DIRECTIONALITY LOGIC:
 *   The flow of value and harm is starkly directional. Harm is extracted from
 *   `targets_of_harassment`. Value, in the form of attention, engagement, and
 *   ad revenue, flows to `malicious_content_creators` and the `platform_operator`.
 *   The beneficiary/victim declarations directly model this structural flow,
 *   which drives the directionality (d) calculations and explains the vast
 *   difference in computed effective extraction (χ) across perspectives.
 *
 * MANDATROPHY ANALYSIS:
 *   This classification avoids two key errors. To label the platform simply a
 *   "Snare" would ignore its vast, legitimate coordination function used by
 *   billions. To label it a "Rope" would be to ignore the immense, asymmetric
 *   harm it facilitates. The Tangled Rope classification is essential, as it
 *   correctly identifies that a system with a genuine coordination purpose is
 *   simultaneously serving as a powerful engine for extraction, and that this
 *   extractive function is not an accident but a structural feature of its
 *   current operation. [RESOLVED MANDATROPHY]
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    omega_ai_nonconsensual_content_facilitation,
    'Is the platform''s failure to prevent this content a deliberate choice for engagement (malice) or a result of technical/financial incapacity (incompetence)?',
    'Internal platform documents, moderation budget data, whistleblower testimony, A/B testing data on moderation effectiveness vs. engagement.',
    'If malice, the constraint is closer to a pure Snare by design. If incompetence, it is a catastrophically failed Tangled Rope where the coordination function has degraded.',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for external script parsing
narrative_ontology:interval(ai_nonconsensual_content_facilitation, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Temporal data reflects the worsening of this problem as AI tools proliferated
% and platform moderation standards were relaxed.
% T=0 (~2021, nascent AI tools); T=5 (~2023, widespread tools, moderation cuts); T=10 (present day).

% Theater ratio over time (public statements increase as problem worsens):
narrative_ontology:measurement(ai_ncf_tr_t0, ai_nonconsensual_content_facilitation, theater_ratio, 0, 0.10).
narrative_ontology:measurement(ai_ncf_tr_t5, ai_nonconsensual_content_facilitation, theater_ratio, 5, 0.30).
narrative_ontology:measurement(ai_ncf_tr_t10, ai_nonconsensual_content_facilitation, theater_ratio, 10, 0.40).

% Extraction over time (harm potential increases with tool accessibility and platform inaction):
narrative_ontology:measurement(ai_ncf_ex_t0, ai_nonconsensual_content_facilitation, base_extractiveness, 0, 0.30).
narrative_ontology:measurement(ai_ncf_ex_t5, ai_nonconsensual_content_facilitation, base_extractiveness, 5, 0.60).
narrative_ontology:measurement(ai_ncf_ex_t10, ai_nonconsensual_content_facilitation, base_extractiveness, 10, 0.75).

/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

% Coordination type (enables Boltzmann floor + complexity offset)
% The platform functions as a piece of global communication infrastructure.
narrative_ontology:coordination_type(ai_nonconsensual_content_facilitation, global_infrastructure).

% Network relationships (structural influence edges)
% This constraint is enabled and influenced by other technological and legal constraints.
narrative_ontology:affects_constraint(platform_liability_shield_section230, ai_nonconsensual_content_facilitation).
narrative_ontology:affects_constraint(ai_model_accessibility, ai_nonconsensual_content_facilitation).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

% No overrides are needed for this story. The automatic derivation from
% beneficiary/victim declarations and exit options accurately captures the
% structural relationships between the platform, its users, and its victims.

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */