% ============================================================================
% CONSTRAINT STORY: big_data_astrophysics_arbitrage
% ============================================================================
% Generated: 2026-01-21
% Model: Gemini 2.0 Flash
% Source: Alex Wilkins, "Filming the universe’s biggest dramas"
% Status: [RESOLVED MANDATROPHY]
% ============================================================================

:- module(constraint_big_data_astrophysics_arbitrage, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks (Required for loading) ---
:- multifile 
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:requires_active_enforcement/1,
    constraint_indexing:constraint_classification/3.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: big_data_astrophysics_arbitrage
 * human_readable: Big Data Arbitrage in Modern Astrophysics
 * domain: technological/scientific
 * temporal_scope: 2009 (Palomar Transient Factory) to 2026+
 * spatial_scope: Global (High-altitude observatories like Pan-STARRS in Hawaii)
 * * SUMMARY:
 * As astronomy shifts from spatial mapping to time-domain "searching in time," the 1.6 petabytes of data 
 * generated by surveys like Pan-STARRS creates a new "Big Data Arbitrage". 
 * Scientists and automated systems arbitrage this information "blizzard" to prioritize fleeting 
 * "transient" events, moving away from "happy accidents" toward industrialized data extraction.
 * * KEY AGENTS:
 * - The Data Scientist/Astronomer: Arbitrages the petabyte-scale stream to find "guest stars".
 * - The Automated Conveyor Belt: The infrastructure (ZTF, Pan-STARRS) that processes 1.6 petabytes of data.
 * - The Traditional Observer: Relied on "chance" to catch glimpses of cosmic drama.
 * * NARRATIVE ARC:
 * The field has moved from a "Mountain" of chance sightings to a "Rope" of industrial-scale 
 * data coordination. This "automated serendipity" allows for 
 * the arbitrage of nanosecond-to-lifetime timescales, but it acts as a "Snare" for 
 * traditionalists who lack the computational capacity to survive the information blizzard.
 */

/* ==========================================================================
   2. CORE SYSTEM INTEGRATION (The "Reality" Layer)
   ========================================================================== */

narrative_ontology:interval(big_data_astrophysics_arbitrage, 0, 10).
narrative_ontology:constraint_claim([big_data_astrophysics_arbitrage], [information_arbitrage]).

% Base extractiveness score (0.75 = High)
% Rationale: High extractiveness is driven by the "largest volume of astronomical data of all time" (1.6 petabytes) 
% being processed through a "conveyor belt" that extracts scientific value with industrial efficiency.
domain_priors:base_extractiveness(big_data_astrophysics_arbitrage, 0.75).

% Suppression score (0.45 = Moderate)
% Rationale: Traditional "chance-based" methods are suppressed as the field 
% adopts a "search in time, rather than space" strategy.
domain_priors:suppression_score(big_data_astrophysics_arbitrage, 0.45).

% Enforcement requirements: Requires active enforcement (Advanced computing, automated surveys, and coordinated telescopes).
domain_priors:requires_active_enforcement(big_data_astrophysics_arbitrage).

% Metrics required for Section 1 of the Executive Summary
narrative_ontology:constraint_metric(big_data_astrophysics_arbitrage, extractiveness, 0.75).
narrative_ontology:constraint_metric(big_data_astrophysics_arbitrage, suppression_requirement, 0.45).

% BENEFICIARIES & VICTIMS
% Modern institutions (University of Amsterdam, Palomar, Pan-STARRS) that benefit from the data volume.
constraint_beneficiary(big_data_astrophysics_arbitrage, institutional_data_centers).
% Individual observers who lack the resources to access or process the 1.6-petabyte stream.
constraint_victim(big_data_astrophysics_arbitrage, resource_limited_astronomers).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (Perspectival Truth)
   ========================================================================== */

/* --------------------------------------------------------------------------
   PERSPECTIVE 1: THE DATA-ENABLED RESEARCHER - Rope
   --------------------------------------------------------------------------
   
   WHO: individual_moderate (Has the agency to leverage "well-oiled machine" data)
   WHEN: biographical (Current era of transient astronomy)
   WHERE: arbitrage (Can switch between 1.6 petabytes of data points to find transients)
   SCOPE: global (Accessing surveys in Hawaii and California)
   
   WHY THIS CLASSIFICATION:
   For the researcher, Big Data is a Rope—a functional tool to move from "happy accidents" 
   to a systematic search across poorly explored time scales.
   
   NARRATIVE EVIDENCE:
   "You could leverage all this data... and use it for your task. And that was hugely powerful".
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    big_data_astrophysics_arbitrage,
    rope,
    context(
        agent_power(individual_moderate),
        time_horizon(biographical),
        exit_options(arbitrage),
        spatial_scope(global)
    )
) :-
    domain_priors:base_extractiveness(big_data_astrophysics_arbitrage, E),
    E < 0.8,
    !.

/* --------------------------------------------------------------------------
   PERSPECTIVE 2: THE "CHANCE" OBSERVER - Snare
   --------------------------------------------------------------------------
   
   WHO: individual_powerless (Relies on serendipity in an era of conveyor belts)
   WHEN: immediate (Addressing fleeting flashes in real-time)
   WHERE: trapped (Cannot process the blizzard of 1.6 petabytes)
   SCOPE: local (Limited to what can be seen from one spot)
   
   WHY THIS CLASSIFICATION:
   For the observer without automated tools, the "conveyor belt" is a Snare. It extracts the 
   legitimacy of "chance" discovery and places authority into the "well-oiled machine".
   
   NARRATIVE EVIDENCE:
   "Relying on chance to capture these events risks missing much of the action... astronomers have now automated the process".
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    big_data_astrophysics_arbitrage,
    snare,
    context(
        agent_power(individual_powerless),
        time_horizon(immediate),
        exit_options(trapped),
        spatial_scope(local)
    )
) :-
    domain_priors:base_extractiveness(big_data_astrophysics_arbitrage, E),
    E > 0.7,
    !.

/* --------------------------------------------------------------------------
   PERSPECTIVE 3: THE PAN-STARRS SURVEY - Mountain
   --------------------------------------------------------------------------
   
   WHO: institutional (Rule-making infrastructure that dominates data volume)
   WHEN: civilizational (Archiving the largest volume of astronomical data in history)
   WHERE: constrained (Bound by the physical limits of 1.6 petabytes of storage)
   SCOPE: global
   
   WHY THIS CLASSIFICATION:
   The survey acts as a Mountain—an immutable fact of modern science. The "conveyor belt" 
   is now the natural law of astronomy; one cannot simply go back to 1000 years ago.
   
   NARRATIVE EVIDENCE:
   "Pan-STARRS survey... has collected the largest volume of astronomical data of all time, at 1.6 petabytes".
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    big_data_astrophysics_arbitrage,
    mountain,
    context(
        agent_power(institutional),
        time_horizon(civilizational),
        exit_options(constrained),
        spatial_scope(global)
    )
) :-
    % Classification based on the physical reality of the "conveyor belt"
    true,
    !.

/* ==========================================================================
   4. TESTS (What We Learn About Constraints)
   ========================================================================== */

:- begin_tests(big_data_astrophysics_arbitrage_tests).

test(multi_perspective_variance) :-
    % Researcher (Rope) vs Individual (Snare) vs System (Mountain)
    constraint_indexing:constraint_classification(big_data_astrophysics_arbitrage, rope, context(individual_moderate, _, arbitrage, _)),
    constraint_indexing:constraint_classification(big_data_astrophysics_arbitrage, snare, context(individual_powerless, _, trapped, _)),
    constraint_indexing:constraint_classification(big_data_astrophysics_arbitrage, mountain, context(institutional, _, _, _)).

test(power_extractiveness_scaling) :-
    % Powerless individuals experience the extraction of their scientific agency (Score 1)
    % while institutions experience data leverage.
    Score1 = 0.75,
    Score2 = 0.20,
    Score1 > Score2.

:- end_tests(big_data_astrophysics_arbitrage_tests).

/* ==========================================================================
   5. MODEL INTERPRETATION (Commentary)
   ========================================================================== */

/**
 * LLM GENERATION NOTES
 * * Model: Gemini 2.0 Flash
 * Date: 2026-01-21
 * * KEY DECISIONS:
 * * 1. EXTRACTIVENESS SCORE (0.75):
 * Reasoning: Chosen because the "1.6 petabytes" represents a high-density 
 * extraction of the universe's actions into human-controlled storage.
 * * 2. MANDATROPHY STATUS:
 * Status: [RESOLVED MANDATROPHY]. High extraction is justified as a 
 * functional "Rope" for the researcher but becomes a "Snare" of exclusion 
 * for those outside the automated institutional loop.
 * * 3. PERSPECTIVE SELECTION:
 * Chose the "Chance" Observer (Powerless) to show how industrialization 
 * removes exit options from traditional discovery methods.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    big_data_astrophysics_arbitrage_extraction_intent,
    "Is the 1.6 petabyte extraction a functional necessity for understanding the universe or a predatory capture of cosmic data?",
    resolution_mechanism("Audit of scientific value derived from automated transients vs. legacy serendipity discoveries"),
    impact("If necessity: Mountain. If predatory: Snare/Mandatrophy."),
    confidence_without_resolution(medium)
).

omega_variable(
    data_redundancy_clog,
    "Will the blizzard of data (1.6PB) create a 'noise snare' where true signals are buried under automated artifacts?",
    resolution_mechanism("Measure the ratio of confirmed transients to 'conveyor belt' errors over time"),
    impact("If signal: Rope. If noise: Snare."),
    confidence_without_resolution(low)
).

/* ==========================================================================
   7. ALTERNATIVE ANALYSIS
   ========================================================================== */

/**
 * VIABLE ALTERNATIVES
 * * ALTERNATIVE 1: Slow-Mapping / Spatial Astronomy
 * Viability: Historically dominant; focused on stable mapping of stars.
 * Suppression: Being replaced by time-domain surveys ("search in time, 
 * rather than space").
 * * CONCLUSION:
 * The move to "Automated Serendipity" creates a Rope for those within the system 
 * but effectively suppresses the traditional "Slow Map" Snare.
 */

/* ==========================================================================
   8. INTEGRATION HOOKS
   ========================================================================== */

/**
 * TO USE THIS FILE:
 * 1. Load: ?- [constraints/big_data_astrophysics_arbitrage].
 * 2. Multi-perspective: ?- multi_index_report(big_data_astrophysics_arbitrage).
 */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
