% ============================================================================
% CONSTRAINT STORY: blackstone_tra
% ============================================================================
% Version: 5.2 (Deferential Realism Core + Boltzmann + Purity + Network)
% Logic: 5.2 (Indexed Tuple P,T,E,S + Coupling + Purity + Network Drift)
% Generated: 2024-07-21
% ============================================================================

:- module(constraint_blackstone_tra, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: blackstone_tra
 * human_readable: Blackstone Tax Receivable Agreement (TRA)
 * domain: economic
 * * SUMMARY:
 * A contract where the public entity (Blackstone Group L.P.) agrees to pay
 * 85% of its tax savings—generated by the purchase of interests from
 * existing partners—directly back to those partners. This effectively
 * privatizes the tax benefits that would otherwise accrue to the public
 * unitholders, creating a permanent, asymmetric cash transfer from the
 * public entity to its former owners.
 * * KEY AGENTS:
 * - Public Unitholders: Subject (Powerless)
 * - Senior Managing Directors (SMDs): Beneficiary (Institutional)
 * - Systems Auditor: Auditor (Analytical)
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% Numerical anchors for v3.4 thresholds
% Rationale: Highly extractive; 85% of a specific cash benefit is diverted
% to a subset of insiders by contract.
domain_priors:base_extractiveness(blackstone_tra, 0.85).
% Rationale: The agreement is a "condition" of the IPO; there is no
% mechanism for public unitholders to opt-out or renegotiate.
domain_priors:suppression_score(blackstone_tra, 0.95).
% Rationale: The TRA is a purely functional financial instrument with no
% performative or theatrical component.
domain_priors:theater_ratio(blackstone_tra, 0.05).

% Constraint metric facts — primary keys used by the classification engine.
narrative_ontology:constraint_metric(blackstone_tra, extractiveness, 0.85).
narrative_ontology:constraint_metric(blackstone_tra, suppression_requirement, 0.95).
narrative_ontology:constraint_metric(blackstone_tra, theater_ratio, 0.05).

% Constraint self-claim (what does the constraint claim to be?)
% It claims to be a constructed financial agreement for sharing tax benefits.
narrative_ontology:constraint_claim(blackstone_tra, tangled_rope).
narrative_ontology:human_readable(blackstone_tra, "Blackstone Tax Receivable Agreement (TRA)").
narrative_ontology:topic_domain(blackstone_tra, "economic").

% Binary flags
% The TRA is a core contractual obligation requiring legal enforcement.
domain_priors:requires_active_enforcement(blackstone_tra).

% Structural property derivation hooks:
% These are required for Tangled Rope classification.
narrative_ontology:constraint_beneficiary(blackstone_tra, senior_managing_directors).
narrative_ontology:constraint_victim(blackstone_tra, public_unitholders).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   χ = ε × π(P) × σ(S)
   Power (P) and Scope (S) both affect effective extraction.
   Scope modifiers: local=0.8, regional=0.9, national=1.0,
                    continental=1.1, global=1.2, universal=1.0.
   ========================================================================== */

% PERSPECTIVE 1: THE SUBJECT (SNARE)
% For the public unitholder, the TRA is a trap. Value that should accrue to
% their investment is contractually siphoned off to insiders.
constraint_indexing:constraint_classification(blackstone_tra, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(national))).

% PERSPECTIVE 2: THE BENEFICIARY (ROPE)
% For the Senior Managing Directors, the TRA is a sophisticated coordination
% tool to maximize the economic value of their exit.
constraint_indexing:constraint_classification(blackstone_tra, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(national))).

% PERSPECTIVE 3: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% Analytically, the TRA has a genuine coordination function (for the SMDs)
% but also imposes severe asymmetric extraction (on unitholders) and requires
% active enforcement. This is the definition of a Tangled Rope.
constraint_indexing:constraint_classification(blackstone_tra, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(blackstone_tra_tests).

test(perspectival_gap) :-
    % Verify there is a perspectival gap between powerless and institutional.
    constraint_indexing:constraint_classification(blackstone_tra, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(blackstone_tra, TypeInstitutional, context(agent_power(institutional), _, _, _)),
    TypePowerless \= TypeInstitutional,
    TypePowerless = snare,
    TypeInstitutional = rope.

test(threshold_validation) :-
    % Verify the extraction score is in the high-extraction (Snare/Tangled) range.
    narrative_ontology:constraint_metric(blackstone_tra, extractiveness, E),
    E >= 0.46.

test(tangled_rope_detection) :-
    % Verify the analytical observer correctly identifies it as a Tangled Rope.
    constraint_indexing:constraint_classification(blackstone_tra, tangled_rope, context(agent_power(analytical), _, _, _)).

:- end_tests(blackstone_tra_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 * The base extractiveness of 0.85 is taken directly from the 85% cash-sharing
 * ratio specified in Blackstone's S-1 filing. The suppression score of 0.95
 * reflects that this agreement was a non-negotiable condition of the IPO,
 * leaving public investors with no alternative.
 *
 * The Perspectival Gap is stark:
 * - For the powerless unitholder, it's a Snare, an unavoidable leakage of value.
 * - For the institutional beneficiary (the SMDs), it's a Rope, a tool to
 *   coordinate and maximize their exit compensation.
 *
 * * MANDATROPHY ANALYSIS: [RESOLVED MANDATROPHY]
 * The analytical classification as a Tangled Rope is crucial. A simpler model
 * might label this a pure Snare, missing its coordination function for the
 * beneficiaries. By classifying it as a Tangled Rope, the system correctly
 * identifies that this is not just simple predation; it's a sophisticated,
 * constructed mechanism with both coordination and extraction functions,
 * which prevents mislabeling it as a natural or unavoidable market feature.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

% omega_variable(ID, Question, Resolution_Mechanism, Impact, Confidence).
omega_variable(
    omega_blackstone_tra,
    'Will future corporate tax rates decrease, reducing the value of the TRA payments?',
    'Tracking of US Congressional legislative action on federal corporate tax rates.',
    'If rates drop, the Snare loosens (less value is extracted). If rates rise, the Snare tightens.',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for external script parsing
narrative_ontology:interval(blackstone_tra, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% The TRA is a fixed contractual obligation established at the IPO. Its core
% metrics are stable over its lifecycle.
%
% Theater ratio over time (stable and low):
narrative_ontology:measurement(blackstone_tra_tr_t0, blackstone_tra, theater_ratio, 0, 0.05).
narrative_ontology:measurement(blackstone_tra_tr_t5, blackstone_tra, theater_ratio, 5, 0.05).
narrative_ontology:measurement(blackstone_tra_tr_t10, blackstone_tra, theater_ratio, 10, 0.05).

% Extraction over time (stable and high, fixed by contract):
narrative_ontology:measurement(blackstone_tra_ex_t0, blackstone_tra, base_extractiveness, 0, 0.85).
narrative_ontology:measurement(blackstone_tra_ex_t5, blackstone_tra, base_extractiveness, 5, 0.85).
narrative_ontology:measurement(blackstone_tra_ex_t10, blackstone_tra, base_extractiveness, 10, 0.85).

/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA (v5.0-5.2)
   ========================================================================== */

% Coordination type (enables Boltzmann floor + complexity offset)
% The TRA is a mechanism for allocating a specific resource (tax savings).
narrative_ontology:coordination_type(blackstone_tra, resource_allocation).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */