% [RESOLVED MANDATROPHY] High-extraction Mountain identified as structural mandate.
% ============================================================================
% CONSTRAINT STORY: blackstone_tax_receivable_agreement
% ============================================================================
% Generated: 2026-01-17
% Model: Gemini 2.0 Flash
% Source: The Blackstone Group L.P. Form S-1 (March 22, 2007)
% ============================================================================

:- module(blackstone_tra, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks ---
:- multifile 
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:requires_active_enforcement/1,
    constraint_indexing:constraint_classification/3.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: blackstone_tra
 * human_readable: Tax Receivable Agreement (TRA)
 * domain: economic/financial
 * temporal_scope: Post-IPO (Long-term)
 * spatial_scope: National (US Tax System)
 * * SUMMARY:
 * A contract where the public entity (Blackstone Group L.P.) agrees to pay 
 * 85% of its tax savings—generated by the purchase of interests from 
 * existing partners—directly back to those partners (the SMDs).
 * This effectively privatizes the tax benefits that would otherwise 
 * accrue to the public unitholders.
 * * KEY AGENTS:
 * - Senior Managing Directors (SMDs): The recipients of the 85% payments.
 * - Public Unitholders: The "funders" of the tax savings who only retain 15%.
 * - Blackstone Corporate Entity: The legal vehicle obligated to make the payments.
 * * NARRATIVE ARC:
 * The TRA is a post-IPO extraction mechanism. When SMDs sell their partnership 
 * units, the "tax basis" of the firm’s assets increases, lowering future taxes 
 *. Instead of these savings boosting the company's cash flow 
 * for all investors, the TRA mandates that the lion's share of that cash 
 * be paid out to the selling partners.
 */

/* ==========================================================================
   2. CORE SYSTEM INTEGRATION
   ========================================================================== */

narrative_ontology:interval(blackstone_tra_life, 0, 10).
narrative_ontology:constraint_claim(blackstone_tra, noose).

% Base extractiveness score (0.0 - 1.0)
% Rationale: Highly extractive; 85% of a specific cash benefit is diverted 
% to a subset of insiders by contract.
domain_priors:base_extractiveness(blackstone_tra, 0.85).

% Suppression score (0.0 - 1.0)
% Rationale: The agreement is a "condition" of the IPO; there is no 
% mechanism for public unitholders to opt-out or renegotiate.
domain_priors:suppression_score(blackstone_tra, 0.95).

% Enforcement requirements
domain_priors:requires_active_enforcement(blackstone_tra).

% Metrics
narrative_ontology:constraint_metric(blackstone_tra, extractiveness, 0.85).
narrative_ontology:constraint_metric(blackstone_tra, suppression_requirement, 0.95).

% Beneficiaries and Victims
constraint_beneficiary(blackstone_tra, selling_smd_partners).
constraint_victim(blackstone_tra, public_common_unitholders).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (Perspectival Truth)
   ========================================================================== */

/* --------------------------------------------------------------------------
   PERSPECTIVE 1: Public Unitholder - Noose
   --------------------------------------------------------------------------
   
   WHO: individual_powerless.
   WHEN: biographical - The payments can span decades.
   WHERE: trapped - The obligation is a core liability of the units.
   
   WHY THIS CLASSIFICATION:
   For the public investor, the TRA is a "Noose." It is an asymmetric 
   leakage of value. The cash that *could* have been used for dividends 
   or reinvestment is contractually diverted to the founders.
   
   NARRATIVE EVIDENCE:
   "We will pay... 85% of the amount of cash savings, if any, in U.S. federal, 
   state and local income tax... to the person who has sold... their 
   Blackstone Holdings partnership units".
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    blackstone_tra,
    noose,
    context(
        agent_power(individual_powerless),
        time_horizon(biographical),
        exit_options(trapped),
        constraint_beneficiary(blackstone_tra, smds),
        constraint_victim(blackstone_tra, public_investors),
        spatial_scope(national)
    )
) :-
    domain_priors:base_extractiveness(blackstone_tra, E),
    E > 0.8,
    !.

/* --------------------------------------------------------------------------
   PERSPECTIVE 2: Senior Managing Director (SMD) - Rope
   --------------------------------------------------------------------------
   
   WHO: individual_powerful.
   WHEN: biographical.
   WHERE: arbitrage - Optimizing the "exit" value of their units.
   
   WHY THIS CLASSIFICATION:
   For the SMDs, the TRA is a "Rope." It is a sophisticated coordination tool 
   that allows them to realize the full economic value of their tax 
   attributes upon exit, which would otherwise be "lost" to the public 
   company.
   
   NARRATIVE EVIDENCE:
   The agreement is designed to "provide for the sharing of the tax 
   benefits... between us and the selling or exchanging partners".
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    blackstone_tra,
    rope,
    context(
        agent_power(individual_powerful),
        time_horizon(biographical),
        exit_options(arbitrage),
        constraint_beneficiary(blackstone_tra, smds),
        constraint_victim(blackstone_tra, none),
        spatial_scope(national)
    )
) :-
    domain_priors:base_extractiveness(blackstone_tra, E),
    E < 0.9,
    !.

/* ==========================================================================
   4. TESTS
   ========================================================================== */

:- begin_tests(blackstone_tra_tests).

test(extraction_ratio_audit) :-
    % Test if the extraction score matches the 85% stated in the S-1
    domain_priors:base_extractiveness(blackstone_tra, 0.85).

test(perspectival_flip) :-
    % Test that same data (85% payout) creates a Noose for one and Rope for another
    constraint_indexing:constraint_classification(blackstone_tra, noose, context(individual_powerless, _, _, _, _, _)),
    constraint_indexing:constraint_classification(blackstone_tra, rope, context(individual_powerful, _, _, _, _, _)).

:- end_tests(blackstone_tra_tests).

/* ==========================================================================
   5. MODEL INTERPRETATION
   ========================================================================== */

/**
 * LLM GENERATION NOTES
 * * KEY DECISIONS:
 * 1. EXTRACTIVENESS (0.85): This is a direct reflection of the 85% 
 * cash-sharing ratio specified in the S-1.
 * 2. CLASSIFICATION: The TRA is perhaps the most "pure" example of a 
 * Noose in corporate governance, as it is a permanent, asymmetric 
 * cash transfer from the public entity to its former owners.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω)
   ========================================================================== */

omega_variable(
    tax_rate_stability,
    "Will future corporate tax rates decrease, reducing the 'value' of the TRA payments for the SMDs?",
    resolution_mechanism("Congressional legislative tracking on federal corporate tax rate adjustments"),
    impact("If rates drop: the Noose loosens (less is extracted). If rates rise: the Noose tightens."),
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. ALTERNATIVE ANALYSIS
   ========================================================================== */

/**
 * VIABLE ALTERNATIVES
 * * ALTERNATIVE 1: Retention of Tax Benefits for All Unitholders
 * Viability: The standard for almost all non-partnership public offerings.
 * Suppression: The SMDs made the TRA a prerequisite for the IPO, effectively 
 * suppressing the "fair share" alternative before public trading began.
 */

/* ==========================================================================
   8. INTEGRATION HOOKS
   ========================================================================== */

% Load: ?- [blackstone_tra].

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */


% ==========================================================================
% [SKELETON REPAIR] Missing Perspectival Pillars Added: MOUNTAIN
% To be calibrated: Define the narrative justification for these perspectives.
% ==========================================================================
constraint_indexing:constraint_classification(blackstone_tax_receiveable_agreement, mountain, agent_power(analytical)).


% --- v3.1 Indexical Relativity Stubs (Fleet Repair) ---
constraint_indexing:constraint_classification(blackstone_tax_receiveable_agreement, rope, agent_power(institutional)).
constraint_indexing:constraint_classification(blackstone_tax_receiveable_agreement, noose, agent_power(individual_powerless)).
