% ============================================================================
% CONSTRAINT STORY: cultural_homogenization_social_media
% ============================================================================
% Version: 6.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-02-29
% ============================================================================

:- module(constraint_cultural_homogenization_social_media, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    domain_priors:emerges_naturally/1,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: cultural_homogenization_social_media
 *   human_readable: Cultural Homogenization via Global Social Media
 *   domain: social
 *
 * SUMMARY:
 *   The dominance of a few global social media platforms leads to cultural homogenization as local content creators and smaller cultures are pushed out of the mainstream, replaced by trends and narratives generated by larger, often Western-centric, media ecosystems.  This constraint limits the diversity of cultural expression and threatens the survival of unique cultural identities.
 *
 * KEY AGENTS (by structural relationship):
 *   - Individuals in smaller cultural groups: Primary target (powerless/trapped) — bears extraction
 *   - Global Social Media Platforms: Primary beneficiary (institutional/arbitrage) — benefits from constraint
 *   - Governments: Secondary actor (institutional/constrained) — potentially regulates or is influenced by the platforms
 *   - Analytical Observer: Analytical observer (analytical/analytical) — sees full structure
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(cultural_homogenization_social_media, 0.55).
domain_priors:suppression_score(cultural_homogenization_social_media, 0.70).   % Structural property (raw, unscaled).
domain_priors:theater_ratio(cultural_homogenization_social_media, 0.30).       % This is an active, not degraded, constraint.

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(cultural_homogenization_social_media, extractiveness, 0.55).
narrative_ontology:constraint_metric(cultural_homogenization_social_media, suppression_requirement, 0.70).
narrative_ontology:constraint_metric(cultural_homogenization_social_media, theater_ratio, 0.30).

% --- NL Profile Metrics (required for mountain constraints) ---
% These feed the natural_law_signature certification chain in
% structural_signatures.pl. Uncomment and set for mountain constraints.
% Without these, the NL signature defaults to 0.5 and fails certification.
%
% narrative_ontology:constraint_metric(cultural_homogenization_social_media, accessibility_collapse, [0.85-1.0]).
% narrative_ontology:constraint_metric(cultural_homogenization_social_media, resistance, [0.0-0.15]).

% --- Constraint claim (must match analytical perspective type) ---
narrative_ontology:constraint_claim(cultural_homogenization_social_media, tangled_rope).
narrative_ontology:human_readable(cultural_homogenization_social_media, "Cultural Homogenization via Global Social Media").
narrative_ontology:topic_domain(cultural_homogenization_social_media, "social").

% --- Binary flags ---
% narrative_ontology:has_sunset_clause(cultural_homogenization_social_media).      % Mandatory if Scaffold
domain_priors:requires_active_enforcement(cultural_homogenization_social_media). % Required for Tangled Rope

% --- Emergence flag (required for mountain constraints) ---
% Uncomment for constraints that emerge naturally without human design
% or enforcement. Required for the mountain metric gate: without this,
% the classify_from_metrics mountain clause will not fire.
%
% domain_priors:emerges_naturally(cultural_homogenization_social_media).

% --- Structural relationships (REQUIRED for non-mountain constraints) ---
% These feed the directionality derivation chain: the engine computes
% d (directionality) from agent membership in these groups + exit_options.
% Without these, the engine falls back to generic power-atom assumptions.
%
% Who benefits from this constraint existing?
narrative_ontology:constraint_beneficiary(cultural_homogenization_social_media, global_social_media_platforms).
%
% Who bears disproportionate cost?
narrative_ontology:constraint_victim(cultural_homogenization_social_media, smaller_cultural_groups).
%
% Gate requirements:
%   Tangled Rope: beneficiary + victim + requires_active_enforcement (all three)
%   Scaffold:     beneficiary + (has_sunset_clause OR no enforcement)
%   Snare:        victim required; beneficiary optional

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   χ = ε × f(d) × σ(S)
   where f(d) is the sigmoid directionality function:
     f(d) = -0.20 + 1.70 / (1 + e^(-6*(d - 0.50)))
   The engine derives d from beneficiary/victim membership + exit_options.
   Scope modifiers: local=0.8, regional=0.9, national=1.0,
                    continental=1.1, global=1.2, universal=1.0.
   CONTEXT ARITY: All context() terms must have exactly 4 arguments.
   Do not add measurement_basis, beneficiary/victim, or other metadata.
   Linter Rule 23 rejects files with context arity ≠ 4.
   ========================================================================== */

% PERSPECTIVE 1: INDIVIDUALS IN SMALLER CULTURAL GROUPS (SNARE)
% Agent who bears the most extraction. Engine derives d from:
%   victim membership + trapped exit → d ≈ 0.95 → f(d) ≈ 1.42 → high χ
%
% NOTE: Per "Dynamic Coalition" extension, this agent's power may be
% upgraded to 'organized' if the constraint is a snare with a critical
% mass of victims, potentially changing the classification.
constraint_indexing:constraint_classification(cultural_homogenization_social_media, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(global))).

% PERSPECTIVE 2: GLOBAL SOCIAL MEDIA PLATFORMS (ROPE)
% Agent who benefits most. Engine derives d from:
%   beneficiary membership + arbitrage exit → d ≈ 0.05 → f(d) ≈ -0.12 → low/negative χ
constraint_indexing:constraint_classification(cultural_homogenization_social_media, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 3: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% Default analytical context (civilizational/analytical/global).
% Used by the bridge to derive constraint_claim.
% Engine derives d ≈ 0.72 → f(d) ≈ 1.15 for analytical perspective.
constraint_indexing:constraint_classification(cultural_homogenization_social_media, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

% --- INTER-INSTITUTIONAL PERSPECTIVES ---
% When a constraint operates between institutional actors with different
% structural relationships, declare separate perspectives for each.

% Perspective 4A: National Governments (institutional, constrained exit)
constraint_indexing:constraint_classification(cultural_homogenization_social_media, tangled_rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(national))).

% Perspective 4B: Regional Governments (institutional, constrained exit)
constraint_indexing:constraint_classification(cultural_homogenization_social_media, tangled_rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(regional))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(cultural_homogenization_social_media_tests).

test(perspectival_gap) :-
    % Verify perspectival gap between target and beneficiary.
    constraint_indexing:constraint_classification(cultural_homogenization_social_media, TypeTarget, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(cultural_homogenization_social_media, TypeBeneficiary, context(agent_power(institutional), _, _, _)),
    TypeTarget \= TypeBeneficiary.

test(threshold_validation) :-
    config:param(extractiveness_metric_name, ExtMetricName),
    narrative_ontology:constraint_metric(cultural_homogenization_social_media, ExtMetricName, E),
    (E =< 0.25 -> true ; E >= 0.46). % Mountain or high-extraction Snare/Tangled.

:- end_tests(cultural_homogenization_social_media_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   The base extractiveness is set to 0.55, representing a significant level of extraction. While social media platforms provide value (coordination), they also extract attention, data, and cultural influence from users, particularly smaller cultures. The suppression score is 0.70, reflecting the reduced visibility and influence of smaller cultural groups in the face of dominant trends and algorithms. The theater ratio is low (0.30) because the constraint's function is very real and active, not degraded or performative.
 *
 * PERSPECTIVAL GAP:
 *   Individuals in smaller cultural groups perceive the constraint as a snare because they experience a loss of cultural identity and a suppression of their own content. Global social media platforms, however, see it as a rope, providing a global platform for communication and marketing. The analytical view is a tangled rope, acknowledging both the coordination function and the asymmetric extraction.
 *
 * DIRECTIONALITY LOGIC:
 *   Global social media platforms benefit by expanding their reach, increasing engagement, and profiting from advertising revenue generated by users. Smaller cultural groups bear the cost as their languages, traditions, and artistic expressions are marginalized by dominant narratives and algorithmic biases. Governments face a tangled situation, needing the platforms for communication but wanting to defend their local cultures.
 *
 * INTER-INSTITUTIONAL DYNAMICS:
 *   National and Regional Governments experience the constraint differently. National governments have more resources and regulatory power to potentially counteract the homogenization effects (e.g., through cultural subsidies, content regulation), so their exit is "constrained" but perhaps less severely than smaller, regional governments.
 *
 * MANDATROPHY ANALYSIS:
 *   The Tangled Rope classification prevents mislabeling this phenomenon as pure extraction because global social media platforms do offer a coordination function, connecting people across borders and facilitating communication. However, the asymmetric extraction of cultural influence and the suppression of local content make it a "tangled" scenario, not pure coordination.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

% omega_variable(ID, Question, Resolution_Mechanism, Impact, Confidence).
omega_variable(
    omega_cultural_homogenization,
    'To what extent is cultural homogenization an inevitable consequence of globalization versus a contingent outcome of specific platform designs and policies?',
    'Cross-cultural studies comparing the impact of different social media platforms on cultural diversity, analysis of algorithmic biases, and assessments of the effectiveness of cultural preservation policies.',
    'If inevitable, then mitigation efforts are likely futile. If contingent, then targeted interventions and platform regulation could be effective.',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for external script parsing
narrative_ontology:interval(cultural_homogenization_social_media, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Temporal data enables drift detection (metric_substitution,
% extraction_accumulation) by providing measurements at multiple time points.
%
% Required for high-extraction constraints (base_extractiveness > 0.46).
% Use at least 3 time points (T=0, midpoint, T=end) for each tracked metric.
%
% Theater ratio over time (triggers metric_substitution detection):
narrative_ontology:measurement(cultural_homogenization_tr_t0, cultural_homogenization_social_media, theater_ratio, 0, 0.20).
narrative_ontology:measurement(cultural_homogenization_tr_t5, cultural_homogenization_social_media, theater_ratio, 5, 0.25).
narrative_ontology:measurement(cultural_homogenization_tr_t10, cultural_homogenization_social_media, theater_ratio, 10, 0.30).

% Extraction over time (triggers extraction_accumulation detection):
narrative_ontology:measurement(cultural_homogenization_ex_t0, cultural_homogenization_social_media, base_extractiveness, 0, 0.45).
narrative_ontology:measurement(cultural_homogenization_ex_t5, cultural_homogenization_social_media, base_extractiveness, 5, 0.50).
narrative_ontology:measurement(cultural_homogenization_ex_t10, cultural_homogenization_social_media, base_extractiveness, 10, 0.55).

/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

% Coordination type (enables Boltzmann floor + complexity offset)
% Valid types: information_standard, resource_allocation,
%              enforcement_mechanism, global_infrastructure
narrative_ontology:coordination_type(cultural_homogenization_social_media, information_standard).

% Boltzmann floor override (only if domain knowledge justifies)
% Value must be in [0.0, 1.0]
% narrative_ontology:boltzmann_floor_override(cultural_homogenization_social_media, [0.0-1.0]).

% Network relationships (structural influence edges)
% Declare when constraints share regulatory domain, causal dependency,
% or institutional coupling.
% narrative_ontology:affects_constraint(cultural_homogenization_social_media, [other_constraint_id]).

% --- Network Decomposition (Constraint Families) ---
% When a natural-language label covers multiple constraints with different ε
% values, each gets its own file. Link family members with affects_constraint:
%
% DUAL FORMULATION NOTE:
% This constraint is one of [N] stories decomposed from [colloquial label].
% Decomposed because ε differs across observables (ε-invariance principle).
% Related stories:
%   - [sibling_constraint_1] (ε=[value], [Type])
%   - [sibling_constraint_2] (ε=[value], [Type])
%
% narrative_ontology:affects_constraint(cultural_homogenization_social_media, [sibling_constraint_id]).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

% Use ONLY when the automatic derivation (beneficiary/victim + exit → d)
% would produce an inaccurate directionality value. The derivation chain
% priority is: override > structural > canonical fallback.
%
% Format: directionality_override(ConstraintID, PowerAtom, D_Value)
%   D_Value in [0.0, 1.0]: 0.0 = full beneficiary, 1.0 = full target
%
% Common override scenarios:
%   - Regulatory capture: institution that appears to benefit but is
%     actually partly captured → override d upward (0.25-0.40)
%   - Indirect beneficiary: agent in victim group who actually benefits
%     through secondary effects → override d downward
%   - Asymmetric institutional: two institutional actors that the
%     derivation can't distinguish → override to differentiate
%
% Example (uncomment if needed):
% constraint_indexing:directionality_override(cultural_homogenization_social_media, institutional, 0.30).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */