% ============================================================================
% CONSTRAINT STORY: debt_service_squeeze
% ============================================================================
% Version: 6.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-05-23
% ============================================================================

:- module(constraint_debt_service_squeeze, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    domain_priors:emerges_naturally/1,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: debt_service_squeeze
 *   human_readable: Consumer Debt Service Squeeze on Higher-Income Households
 *   domain: economic
 *
 * SUMMARY:
 *   A system of consumer credit (auto loans, credit cards) that, when combined
 *   with inflation and rising interest rates, places a severe and growing
 *   debt-service burden even on households with incomes above $75,000.
 *   This erodes their financial stability, leading to rising delinquencies
 *   in a demographic cohort previously considered resilient. The constraint
 *   is the structure of the credit market itself, which coordinates capital
 *   flow while simultaneously extracting significant value from borrowers.
 *
 * KEY AGENTS (by structural relationship):
 *   - Higher-Income Households ($75k+): Primary target (powerless/trapped) — bears the extraction from interest, fees, and penalties.
 *   - Lending Institutions: Primary beneficiary (institutional/arbitrage) — benefits from interest revenue and fees generated by the system.
 *   - Federal Reserve: Secondary actor (institutional/constrained) — its monetary policy (rate hikes) intensifies the constraint on borrowers.
 *   - Economist: Analytical observer — sees the full structure of coordination and extraction.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(debt_service_squeeze, 0.68).
domain_priors:suppression_score(debt_service_squeeze, 0.80).   % Structural property (raw, unscaled).
domain_priors:theater_ratio(debt_service_squeeze, 0.15).       % Piton detection (>= 0.70)

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(debt_service_squeeze, extractiveness, 0.68).
narrative_ontology:constraint_metric(debt_service_squeeze, suppression_requirement, 0.80).
narrative_ontology:constraint_metric(debt_service_squeeze, theater_ratio, 0.15).

% --- NL Profile Metrics (required for mountain constraints) ---
% N/A for this constraint.

% --- Constraint claim (must match analytical perspective type) ---
narrative_ontology:constraint_claim(debt_service_squeeze, tangled_rope).
narrative_ontology:human_readable(debt_service_squeeze, "Consumer Debt Service Squeeze on Higher-Income Households").
narrative_ontology:topic_domain(debt_service_squeeze, "economic").

% --- Binary flags ---
domain_priors:requires_active_enforcement(debt_service_squeeze). % Required for Tangled Rope

% --- Structural relationships (REQUIRED for non-mountain constraints) ---
% These feed the directionality derivation chain: the engine computes
% d (directionality) from agent membership in these groups + exit_options.
%
% Who benefits from this constraint existing?
narrative_ontology:constraint_beneficiary(debt_service_squeeze, lending_institutions).
%
% Who bears disproportionate cost?
narrative_ontology:constraint_victim(debt_service_squeeze, higher_income_households).
%
% Gate requirements:
%   Tangled Rope: beneficiary + victim + requires_active_enforcement (all three) -> MET

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   χ = ε × f(d) × σ(S)
   where f(d) is the sigmoid directionality function:
     f(d) = -0.20 + 1.70 / (1 + e^(-6*(d - 0.50)))
   The engine derives d from beneficiary/victim membership + exit_options.
   Scope modifiers: local=0.8, regional=0.9, national=1.0,
                    continental=1.1, global=1.2, universal=1.0.
   CONTEXT ARITY: All context() terms must have exactly 4 arguments.
   ========================================================================== */

% PERSPECTIVE 1: THE PRIMARY TARGET (SNARE)
% The higher-income household is trapped by debt obligations. High income provides
% little power against the structural extraction of the credit system.
% Engine derives d from victim + trapped → d ≈ 0.95 → f(d) ≈ 1.42.
% χ = 0.68 * 1.42 * 1.0 (national) ≈ 0.96.
% With ε=0.68, suppression=0.80, and χ>0.66, this is a clear Snare.
constraint_indexing:constraint_classification(debt_service_squeeze, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(national))).

% PERSPECTIVE 2: THE PRIMARY BENEFICIARY (ROPE)
% Lending institutions see the system as a mechanism for allocating capital and
% generating predictable returns.
% Engine derives d from beneficiary + arbitrage → d ≈ 0.05 → f(d) ≈ -0.12.
% χ = 0.68 * (-0.12) * 1.0 (national) ≈ -0.08.
% With negative χ, the constraint is subsidizing this agent. It is a pure
% coordination Rope from their perspective.
constraint_indexing:constraint_classification(debt_service_squeeze, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(national))).

% PERSPECTIVE 3: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% The economist sees both the vital coordination function (capital allocation)
% and the severe asymmetric extraction.
% Engine derives d ≈ 0.72 → f(d) ≈ 1.15 for analytical perspective.
% χ = 0.68 * 1.15 * 1.2 (global) ≈ 0.94.
% With a coordination function, asymmetric extraction, and required enforcement,
% this is a Tangled Rope. The high χ value (0.94) places it at the very edge
% of the Tangled Rope/Snare boundary, indicating the extractive function
% is currently dominating the coordination function.
constraint_indexing:constraint_classification(debt_service_squeeze, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(debt_service_squeeze_tests).

test(perspectival_gap) :-
    % Verify perspectival gap between target (Snare) and beneficiary (Rope).
    constraint_indexing:constraint_classification(debt_service_squeeze, snare, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(debt_service_squeeze, rope, context(agent_power(institutional), _, _, _)).

test(analytical_classification) :-
    % Verify the analytical perspective resolves to Tangled Rope.
    constraint_indexing:constraint_classification(debt_service_squeeze, tangled_rope, context(agent_power(analytical), _, _, _)).

test(threshold_validation) :-
    % Verify base extractiveness and suppression are in the high-extraction range.
    domain_priors:base_extractiveness(debt_service_squeeze, E), E >= 0.46,
    domain_priors:suppression_score(debt_service_squeeze, S), S >= 0.60.

test(tangled_rope_gates_pass) :-
    % Verify all three structural requirements for Tangled Rope are present.
    narrative_ontology:constraint_beneficiary(debt_service_squeeze, _),
    narrative_ontology:constraint_victim(debt_service_squeeze, _),
    domain_priors:requires_active_enforcement(debt_service_squeeze).

:- end_tests(debt_service_squeeze_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   - Base Extractiveness (ε=0.68): This is high, reflecting the compound interest, fees, and penalties inherent in consumer credit products, which are designed for revenue generation.
 *   - Suppression Score (0.80): Also high. Accessing major economic goods (housing, transportation, education) in the modern US economy is functionally impossible for most without engaging with this credit system. Alternatives are strongly suppressed.
 *   - The combination of high ε and high suppression makes this a highly coercive system.
 *
 * PERSPECTIVAL GAP:
 *   The gap between the borrower's Snare and the lender's Rope is the core of this constraint.
 *   - For the Higher-Income Household (powerless, trapped), the constraint is a pure extraction mechanism. Their income is insufficient to escape the debt's gravity, and non-payment carries severe consequences. It is a Snare.
 *   - For the Lending Institution (institutional, arbitrage), the same system is a well-functioning coordination device. It allocates capital to consumers, creating a profitable, manageable portfolio of assets (loans). It is a Rope.
 *   - The analytical perspective (Tangled Rope) acknowledges the truth in both views: the system performs a genuine coordination function (allocating capital) but does so in a way that creates severe, asymmetric extraction.
 *
 * DIRECTIONALITY LOGIC:
 *   - Beneficiary: `lending_institutions`. They design the system, set the terms, and are the primary recipients of the extracted value (interest and fees). This declaration gives them a low directionality `d`.
 *   - Victim: `higher_income_households`. They are the targets of the extraction. Their payments fund the system's beneficiaries. Even with higher incomes, their structural position is one of a target, giving them a high `d`.
 *   This mapping is direct and structural.
 *
 * MANDATROPHY ANALYSIS:
 *   This framework correctly identifies the dual nature of consumer credit, avoiding a monolithic classification. A simplistic analysis might label the entire system a "Snare," ignoring its essential role in capital allocation. Conversely, an industry-friendly view might call it a "Rope," ignoring the immense extraction. The Tangled Rope classification, derived from the analytical perspective, prevents both errors by demanding evidence of both coordination (`constraint_beneficiary`) and extraction (`constraint_victim`, high ε) to exist simultaneously.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    omega_debt_service_squeeze,
    'Is this level of extraction a necessary feature for a stable credit market, or is it a sign of regulatory failure and market capture?',
    'Comparative analysis of household debt burdens and default rates in economies with substantially different consumer credit regulations (e.g., rate caps, simplified contracts).',
    'If necessary -> Tangled Rope is the best possible state. If regulatory failure -> A less extractive Tangled Rope or even a pure Rope is achievable.',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for external script parsing. Interval represents 2014-2024.
narrative_ontology:interval(debt_service_squeeze, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% This constraint intensified after 2021 due to inflation and rate hikes.
% Base extractiveness is modeled as increasing as the real burden of the
% same nominal rates grew heavier. T=0 is 2014, T=7 is 2021, T=10 is 2024.
%
% Theater ratio over time (stable and low):
narrative_ontology:measurement(dss_tr_t0, debt_service_squeeze, theater_ratio, 0, 0.15).
narrative_ontology:measurement(dss_tr_t7, debt_service_squeeze, theater_ratio, 7, 0.15).
narrative_ontology:measurement(dss_tr_t10, debt_service_squeeze, theater_ratio, 10, 0.15).

% Extraction over time (extraction_accumulation drift):
narrative_ontology:measurement(dss_ex_t0, debt_service_squeeze, base_extractiveness, 0, 0.55).
narrative_ontology:measurement(dss_ex_t7, debt_service_squeeze, base_extractiveness, 7, 0.62).
narrative_ontology:measurement(dss_ex_t10, debt_service_squeeze, base_extractiveness, 10, 0.68).

/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

% Coordination type (enables Boltzmann floor + complexity offset)
% The system's primary coordination function is allocating capital.
narrative_ontology:coordination_type(debt_service_squeeze, resource_allocation).

% Network relationships (structural influence edges)
% This constraint is heavily influenced by monetary policy decisions made
% to control inflation.
narrative_ontology:affects_constraint(monetary_policy_inflation_control, debt_service_squeeze).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

% No overrides are necessary for this constraint. The standard derivation
% based on beneficiary/victim status and exit options accurately models
% the structural relationships between borrowers and lenders.

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */