% ============================================================================
% CONSTRAINT STORY: hagia_sophia_status
% ============================================================================
% Version: 6.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-05-21
% ============================================================================

:- module(constraint_hagia_sophia_status, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    domain_priors:emerges_naturally/1.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: hagia_sophia_status
 *   human_readable: The enforced religious and political status of the Hagia Sophia
 *   domain: religious/political
 *
 * SUMMARY:
 *   The Hagia Sophia in Istanbul has been the site of intense contestation,
 *   serving sequentially as an Orthodox cathedral, a mosque, a secular museum,
 *   and (since 2020) a mosque again. This constraint represents the state-enforced
 *   designation of the building's use, which simultaneously serves as a coordination
 *   mechanism for one group while extracting symbolic and political capital at the
 *   expense of others. Its status is not a natural state but a deliberate,
 *   enforced policy with significant geopolitical and cultural implications.
 *
 * KEY AGENTS (by structural relationship):
 *   - Orthodox Christians and secular internationalists: Primary target (powerless/trapped) — bears the cost of exclusion from a site of central religious/cultural importance.
 *   - The ruling Turkish political establishment and its base: Primary beneficiary (institutional/arbitrage) — benefits from the immense symbolic capital and nationalist cohesion generated by controlling the site's status.
 *   - Historians, architectural preservationists, UNESCO: Analytical observer — sees the building's complex, layered history and the tension between its universal heritage value and its use as a political instrument.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(hagia_sophia_status, 0.48). % High symbolic/political extraction.
domain_priors:suppression_score(hagia_sophia_status, 0.75).   % Alternative uses (museum, church, shared space) are legally and politically suppressed.
domain_priors:theater_ratio(hagia_sophia_status, 0.40).       % High political performance, but also a functioning religious site.

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(hagia_sophia_status, extractiveness, 0.48).
narrative_ontology:constraint_metric(hagia_sophia_status, suppression_requirement, 0.75).
narrative_ontology:constraint_metric(hagia_sophia_status, theater_ratio, 0.40).

% --- NL Profile Metrics (required for mountain constraints) ---
% Not a mountain; these are not applicable.

% --- Constraint claim (must match analytical perspective type) ---
narrative_ontology:constraint_claim(hagia_sophia_status, tangled_rope).

% --- Binary flags ---
domain_priors:requires_active_enforcement(hagia_sophia_status). % Status is maintained by state decree and security apparatus.

% --- Emergence flag (required for mountain constraints) ---
% Not applicable.

% --- Structural relationships (REQUIRED for non-mountain constraints) ---
% These feed the directionality derivation chain: the engine computes
% d (directionality) from agent membership in these groups + exit_options.

% Who benefits from this constraint existing?
narrative_ontology:constraint_beneficiary(hagia_sophia_status, ruling_turkish_political_establishment).

% Who bears disproportionate cost?
narrative_ontology:constraint_victim(hagia_sophia_status, orthodox_christians_and_secular_internationalists).

% Gate requirements:
%   Tangled Rope: beneficiary + victim + requires_active_enforcement (all three are present)

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   χ = ε × f(d) × σ(S)
   where f(d) is the sigmoid directionality function:
     f(d) = -0.20 + 1.70 / (1 + e^(-6*(d - 0.50)))
   The engine derives d from beneficiary/victim membership + exit_options.
   Scope modifiers: local=0.8, regional=0.9, national=1.0,
                    continental=1.1, global=1.2, universal=1.0.
   CONTEXT ARITY: All context() terms must have exactly 4 arguments.
   Do not add measurement_basis, beneficiary/victim, or other metadata.
   Linter Rule 23 rejects files with context arity ≠ 4.
   ========================================================================== */

% PERSPECTIVE 1: THE PRIMARY TARGET (SNARE)
% For Orthodox Christians and secular internationalists, the constraint is purely
% extractive and coercive. They are victims with no internal recourse (trapped).
% Engine derives d from: victim + trapped exit → d ≈ 0.95 → f(d) ≈ 1.42.
% χ = 0.48 * 1.42 * 1.0 (national) = 0.68. This meets the Snare threshold (χ ≥ 0.66).
constraint_indexing:constraint_classification(hagia_sophia_status, snare,
    context(agent_power(powerless),
            time_horizon(generational),
            exit_options(trapped),
            spatial_scope(national))).

% PERSPECTIVE 2: THE PRIMARY BENEFICIARY (ROPE)
% For the ruling political establishment, the constraint is a powerful tool for
% coordinating national and religious identity. They are beneficiaries with full
% control (arbitrage).
% Engine derives d from: beneficiary + arbitrage exit → d ≈ 0.05 → f(d) ≈ -0.12.
% χ = 0.48 * -0.12 * 1.0 = -0.058. This negative effective extraction signifies pure benefit.
constraint_indexing:constraint_classification(hagia_sophia_status, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(national))).

% PERSPECTIVE 3: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% A historian or UNESCO analyst recognizes both the coordination function for the
% in-group AND the asymmetric extraction imposed on out-groups, enforced by the state.
% Engine derives d ≈ 0.72 → f(d) ≈ 1.15 for the analytical observer.
% Scope is global (σ=1.2) reflecting its world heritage status.
% χ = 0.48 * 1.15 * 1.2 = 0.6624. This χ is in the Tangled Rope range (0.40 ≤ χ ≤ 0.90).
% The structural requirements (beneficiary, victim, enforcement) are met.
constraint_indexing:constraint_classification(hagia_sophia_status, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(hagia_sophia_status_tests).

test(perspectival_gap_is_snare_vs_rope, [nondet]) :-
    % Verify the core perspectival gap between target and beneficiary.
    constraint_indexing:constraint_classification(hagia_sophia_status, snare, context(agent_power(powerless), _, exit_options(trapped), _)),
    constraint_indexing:constraint_classification(hagia_sophia_status, rope, context(agent_power(institutional), _, exit_options(arbitrage), _)).

test(analytical_view_is_tangled_rope, [nondet]) :-
    % Verify the analytical classification resolves the gap as a Tangled Rope.
    constraint_indexing:constraint_classification(hagia_sophia_status, tangled_rope, context(agent_power(analytical), _, _, _)).

test(tangled_rope_structural_gates_pass) :-
    % Verify all three structural requirements for Tangled Rope are met.
    narrative_ontology:constraint_beneficiary(hagia_sophia_status, _),
    narrative_ontology:constraint_victim(hagia_sophia_status, _),
    domain_priors:requires_active_enforcement(hagia_sophia_status).

:- end_tests(hagia_sophia_status_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   - Base Extractiveness (0.48): The extraction is primarily symbolic, political, and cultural, not financial. It represents the capture of a universal symbol for a particular nationalist-religious narrative. This value is high enough to trigger a Snare classification from the target's perspective.
 *   - Suppression (0.75): Extremely high. The Turkish high court annulled the 1934 decree that made it a museum, legally erasing the primary alternative. Any attempt to use the site for non-Islamic worship would be met with state force.
 *
 * PERSPECTIVAL GAP:
 *   The gap is profound and is the core of the conflict.
 *   - The beneficiary (ruling establishment) sees a Rope: a tool to coordinate and affirm the identity of their base, fulfilling a historical "right." The costs imposed on others are dismissed as irrelevant or illegitimate.
 *   - The target (Orthodox Christians, etc.) sees a Snare: a coercive act of cultural and religious appropriation that denies their heritage and access, with no possibility of appeal.
 *   The system correctly models this by calculating a negative chi (benefit) for the institutional actor and a high positive chi (extraction) for the powerless one.
 *
 * DIRECTIONALITY LOGIC:
 *   The directionality is unambiguous. The flow of symbolic capital is from a universal/Christian heritage into a nationalist/Islamic political project.
 *   - Beneficiary: `ruling_turkish_political_establishment` directly benefits through political consolidation and popular support.
 *   - Victim: `orthodox_christians_and_secular_internationalists` bear the direct cost through the loss of a central site of worship and a symbol of shared world heritage.
 *   These declarations correctly inform the directionality 'd' for each perspective, driving the Rope/Snare classification gap.
 *
 * MANDATROPHY ANALYSIS:
 *   This is a classic case where a simplistic analysis would fail. Calling it just a "Snare" ignores the genuine coordination function it serves for millions of people. Calling it just a "Rope" ignores the profound, coercive exclusion it imposes on others. The Tangled Rope classification from the analytical perspective is essential, as it acknowledges both functions simultaneously, identifying the constraint as a hybrid of coordination and asymmetric extraction, which is precisely what it is.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

% omega_variable(ID, Question, Resolution_Mechanism, Impact, Confidence).
omega_variable(
    omega_hagia_sophia_status,
    'Is the primary function of the conversion a genuine religious coordination mechanism, or a theatrical political tool for nationalist consolidation?',
    'Analysis of internal government communications, patterns of state funding for religious vs. nationalist projects, and polling data on public sentiment versus political rhetoric.',
    'If primarily religious, the `theater_ratio` might be lower (e.g., 0.25). If primarily political, the symbolic `base_extractiveness` would be confirmed as high or even higher (e.g., 0.55).',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for external script parsing. Interval represents the modern era of contestation.
narrative_ontology:interval(hagia_sophia_status, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% This constraint has undergone significant lifecycle drift.
% T=0: 1935 (becomes a museum - low extraction)
% T=5: ~1980s-2000s (status is debated, becoming a political tool - rising extraction)
% T=10: 2020 (converted to a mosque - high extraction)

% Theater ratio over time:
narrative_ontology:measurement(hs_tr_t0, hagia_sophia_status, theater_ratio, 0, 0.15).
narrative_ontology:measurement(hs_tr_t5, hagia_sophia_status, theater_ratio, 5, 0.25).
narrative_ontology:measurement(hs_tr_t10, hagia_sophia_status, theater_ratio, 10, 0.40).

% Extraction over time (extraction_accumulation):
narrative_ontology:measurement(hs_ex_t0, hagia_sophia_status, base_extractiveness, 0, 0.10).
narrative_ontology:measurement(hs_ex_t5, hagia_sophia_status, base_extractiveness, 5, 0.25).
narrative_ontology:measurement(hs_ex_t10, hagia_sophia_status, base_extractiveness, 10, 0.48).

/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

% Coordination type (enables Boltzmann floor + complexity offset)
% The constraint allocates a unique, symbolic resource (the building itself).
narrative_ontology:coordination_type(hagia_sophia_status, resource_allocation).

% Network relationships (structural influence edges)
% The status of Hagia Sophia is structurally linked to the broader constraint
% of state-enforced secularism ('Laïcité') in Turkey. A weakening of the
% latter enabled the change in the former.
narrative_ontology:affects_constraint(laiklik_principle_degradation, hagia_sophia_status).


/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

% No overrides are needed for this constraint. The standard derivation chain,
% informed by the beneficiary/victim declarations and exit options, accurately
% models the directionality for the key perspectives.

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */