% ============================================================================
% CONSTRAINT STORY: medical_residency_match
% ============================================================================
% Generated: 2026-01-17
% Model: Gemini 2.0 Flash
% Source: National Resident Matching Program (NRMP) / Roth-Peranson Algorithm
% ============================================================================

:- module(constraint_medical_match, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks ---
:- multifile 
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:requires_active_enforcement/1,
    constraint_indexing:constraint_classification/3.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: medical_residency_match
 * human_readable: The NRMP Medical Residency Match
 * domain: economic/social/technological
 * temporal_scope: Biographical (Final year of med school)
 * spatial_scope: National (USA)
 * * SUMMARY:
 * The "Match" is a centralized clearinghouse that uses a version of the 
 * Gale-Shapley algorithm (Roth-Peranson) to pair medical students with 
 * residency programs. It is a legally binding contract generated by an 
 * algorithm, designed to prevent "exploding offers" and market unraveling.
 * * KEY AGENTS:
 * - The Medical Student: Submits a Rank Order List (ROL) of programs.
 * - The Residency Program: Submits a Rank Order List of applicants.
 * - The NRMP: The institutional architect enforcing the "no-departure" rule.
 * * NARRATIVE ARC:
 * For decades, the market "unraveled"—hospitals made offers earlier and 
 * earlier, sometimes to students years before graduation. The Match was 
 * implemented as a stabilization mechanism, but it created a monolithic 
 * bottleneck that determines a doctor's entire career path in one second.
 */

/* ==========================================================================
   2. BASE PROPERTIES (Reality Layer)
   ========================================================================== */

narrative_ontology:interval(medical_residency_match, 0, 10).
narrative_ontology:constraint_claim(medical_residency_match, rope).

% Base extractiveness: High (0.6).
% Hospitals gain significant wage-setting power because students cannot 
% negotiate individual contracts once matched.
domain_priors:base_extractiveness(medical_residency_match, 0.6).

% Suppression: Extreme (0.95).
% Side-deals (pre-matching) are strictly prohibited and can result in 
% being banned from the profession. The Match is the only legal path.
domain_priors:suppression_score(medical_residency_match, 0.95).

% Enforcement: Requires active enforcement (NRMP legal framework).
domain_priors:requires_active_enforcement(medical_residency_match).

% Beneficiaries: Hospital Systems (predictable labor supply, suppressed wages).
constraint_beneficiary(medical_residency_match, hospital_networks).

% Victims: Fourth-year Med Students (lack of bargaining power, high stress).
constraint_victim(medical_residency_match, medical_graduates).

% Metrics
narrative_ontology:constraint_metric(medical_residency_match, extractiveness, 0.6).
narrative_ontology:constraint_metric(medical_residency_match, suppression_requirement, 0.95).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (Perspectival Truth)
   ========================================================================== */

/* --------------------------------------------------------------------------
   PERSPECTIVE 1: THE STUDENT - Noose
   --------------------------------------------------------------------------
   WHO: individual_powerless
   WHEN: immediate (Match Day)
   WHERE: trapped (Binding legal contract)
   SCOPE: national
   
   WHY THIS CLASSIFICATION:
   For the student, the Match is a "Noose." They have no "exit" option; 
   once the algorithm runs, they are legally bound to work at the 
   resulting hospital, often in a different city, with no room to 
   negotiate salary or hours. The suppression of side-deals makes 
   it a mandatory bottleneck.
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    medical_residency_match,
    noose,
    context(
        agent_power(individual_powerless),
        time_horizon(immediate),
        exit_options(trapped),
        spatial_scope(national)
    )
) :-
    domain_priors:suppression_score(medical_residency_match, S),
    S > 0.9,
    !.

/* --------------------------------------------------------------------------
   PERSPECTIVE 2: THE HOSPITAL ADMINISTRATOR - Rope
   --------------------------------------------------------------------------
   WHO: institutional
   WHEN: generational
   WHERE: mobile
   SCOPE: regional
   
   WHY THIS CLASSIFICATION:
   To the hospital, the Match is a "Rope." it coordinates the chaos of 
   recruiting thousands of residents simultaneously. It ensures they 
   fill their quotas with the "best" available candidates according 
   to their rank list, preventing a bidding war for talent.
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    medical_residency_match,
    rope,
    context(
        agent_power(institutional),
        time_horizon(generational),
        exit_options(mobile),
        spatial_scope(regional)
    )
) :-
    true.

/* --------------------------------------------------------------------------
   PERSPECTIVE 3: THE LABOR ECONOMIST - Mountain
   --------------------------------------------------------------------------
   WHO: analytical
   WHEN: historical
   WHERE: analytical
   SCOPE: global
   
   WHY THIS CLASSIFICATION:
   The economist sees the Match as a "Mountain." Market unraveling 
   (congestion) is a natural economic force. A centralized 
   clearinghouse is the only "stable" solution to this game-theoretic 
   problem. The algorithm isn't a choice; it's a structural necessity.
   -------------------------------------------------------------------------- */

constraint_indexing:constraint_classification(
    medical_residency_match,
    mountain,
    context(
        agent_power(analytical),
        time_horizon(historical),
        exit_options(analytical),
        spatial_scope(global)
    )
) :-
    domain_priors:emerges_naturally(medical_residency_match),
    !.

/* ==========================================================================
   4. TESTS
   ========================================================================== */

:- begin_tests(medical_match_tests).

test(exit_option_noose) :-
    % Testing that 'trapped' agents (students) experience a Noose.
    constraint_indexing:constraint_classification(medical_residency_match, noose, context(_, _, trapped, _)).

test(coordination_rope) :-
    % Testing that institutions see the Rope of coordination.
    constraint_indexing:constraint_classification(medical_residency_match, rope, context(institutional, _, _, _)).

:- end_tests(medical_match_tests).

/* ==========================================================================
   5. MODEL INTERPRETATION (Commentary)
   ========================================================================== */

/**
 * LLM GENERATION NOTES
 * Model: Gemini 2.0 Flash
 * * KEY DECISIONS:
 * The medical match is the "hardest" version of a matching market. 
 * I set suppression to 0.95 because there is literally no other way to 
 * become a licensed physician in the US without going through this 
 * specific algorithm. This makes it a perfect example of a "Noose" 
 * from the perspective of the individual laborer.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω)
   ========================================================================== */

omega_variable(
    antitrust_exemption,
    "Will the legal exemption allowing the Match to suppress wage competition be overturned?",
    resolution_mechanism("Supreme Court or Congressional review of Jung v. Association of American Medical Colleges"),
    impact("If Yes: The 'Mountain' collapses into a decentralized 'Auction' (Rope/Noose reversal)."),
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. ALTERNATIVE ANALYSIS
   ========================================================================== */

/**
 * VIABLE ALTERNATIVES:
 * 1. Decentralized Labor Market: (History shows this leads to 'exploding offers' 
 * and market failure/unraveling).
 * 2. Multi-Stage Match: (Allows for some negotiation after the first match).
 * * CONCLUSION:
 * The Match is a "Stable" outcome (Mountain), but the *price* of that 
 * stability is the removal of student agency (Noose).
 */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
