% ============================================================================
% CONSTRAINT STORY: model_collapse_feedback
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-01-15
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_model_collapse_feedback, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:stakeholder_non_agent/2,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: model_collapse_feedback
 *   human_readable: Model Collapse Feedback Loop
 *   domain: computational_epistemology/information_ecology
 *
 * SUMMARY:
 *   Machine learning models increasingly train on synthetic data generated by
 *   prior model generations. This recursive loop produces immediate cost
 *   savings but causes irreversible loss of distributional tail modes: rare
 *   linguistic patterns, minority cultural knowledge, and niche domain
 *   expertise vanish from the training corpus as models converge toward their
 *   own prior outputs. The degradation is invisible to central-tendency
 *   benchmarks but compounds across generations, transferring model quality
 *   from future training cycles to current deployers. The constraint is
 *   claimed as snare because the coordination story (solving data scarcity)
 *   has become cover for extracting from a commons (future model quality and
 *   information ecosystem integrity) that cannot defend itself. KEY AGENTS
 *   (by structural relationship): - current_generation_deployers: Primary
 *   agenda-setter (institutional/mobile) — controls training data
 *   composition, captures value now, externalizes tail-loss costs -
 *   synthetic_data_vendors: Primary beneficiary (powerful/mobile) — profits
 *   from synthetic-equivalence framing without bearing degradation costs -
 *   future_model_quality: Primary victim (powerless/trapped, non-agent) —
 *   abstract capacity degraded irreversibly across generations -
 *   downstream_researchers: Secondary victim (moderate/constrained) —
 *   inherits degraded models and contaminated corpora -
 *   minority_distribution_communities: Tertiary victim (powerless/trapped) —
 *   loses representational capacity as tail modes vanish -
 *   data_provenance_advocates: Excluded voice (moderate/constrained) —
 *   structurally kept out of deployment decisions -
 *   computational_epistemology_researchers: Analytical observer
 *   (analytical/analytical) — measures the collapse but does not control it
 *
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(model_collapse_feedback, 0.78).
domain_priors:suppression_score(model_collapse_feedback, 0.71).
domain_priors:theater_ratio(model_collapse_feedback, 0.42).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(model_collapse_feedback, extractiveness, 0.78).
narrative_ontology:constraint_metric(model_collapse_feedback, suppression_requirement, 0.71).
narrative_ontology:constraint_metric(model_collapse_feedback, theater_ratio, 0.42).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(model_collapse_feedback, accessibility_collapse, 0.62).
narrative_ontology:constraint_metric(model_collapse_feedback, resistance, 0.58).

% --- Constraint claim ---
narrative_ontology:constraint_claim(model_collapse_feedback, snare).
narrative_ontology:human_readable(model_collapse_feedback, "Model Collapse Feedback Loop").
narrative_ontology:topic_domain(model_collapse_feedback, "computational_epistemology/information_ecology").

domain_priors:requires_active_enforcement(model_collapse_feedback).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(model_collapse_feedback, current_generation_deployers).
narrative_ontology:constraint_beneficiary(model_collapse_feedback, synthetic_data_vendors).
narrative_ontology:constraint_victim(model_collapse_feedback, future_model_quality).
narrative_ontology:constraint_victim(model_collapse_feedback, downstream_researchers).
narrative_ontology:constraint_victim(model_collapse_feedback, information_ecosystem_integrity).
narrative_ontology:constraint_victim(model_collapse_feedback, minority_distribution_communities).
% Derived from stakeholders[] roles (beneficiary->beneficiary, payer->victim;
% agent-gated; excluded derives nothing; deduped against the authored arrays).
narrative_ontology:constraint_beneficiary(model_collapse_feedback, benchmark_evaluation_community).
narrative_ontology:constraint_vindicates(model_collapse_feedback, efficiency_over_diversity_doctrine).
narrative_ontology:constraint_vindicates(model_collapse_feedback, synthetic_data_equivalence_hypothesis).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Deploy models trained on increasingly synthetic data to meet immediate market demand. They control training data composition decisions and face quarterly pressure to ship models faster and cheaper. The cost of curating human-generated data exceeds their planning horizon; synthetic data appears functionally equivalent in benchmark tests. They capture value now while externalizing tail-loss costs to future training cycles.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, current_generation_deployers, agenda_setter,
    institutional, biographical, mobile, global).

% Sell model-generated training data as a cost-effective substitute for human annotation. Their business model depends on the synthetic-equivalence framing holding in evaluation regimes that measure central tendency but not tail preservation. They profit from each generation's training demand without bearing the cumulative degradation cost.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, synthetic_data_vendors, beneficiary,
    powerful, biographical, mobile, global).

% The abstract capacity of models trained N generations downstream. Each generation's synthetic contamination compounds irreversibly: rare modes vanish, distributional support narrows, and recovery requires access to uncontaminated human data that may no longer exist at scale. This is not an agent but the cumulative victim of the extraction.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, future_model_quality, payer,
    powerless, generational, trapped, universal).
narrative_ontology:stakeholder_non_agent(model_collapse_feedback, future_model_quality).

% Inherit degraded base models and contaminated training corpora. They observe collapsing diversity in fine-tuned outputs and diminishing returns from scale, but lack the resources to reconstruct clean training sets or the institutional power to enforce data provenance standards upstream. Their research builds on a progressively narrower foundation.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, downstream_researchers, payer,
    moderate, biographical, constrained, global).

% The long-term capacity of the information commons to preserve human cultural and linguistic diversity. As synthetic outputs flood training corpora and models converge toward their own prior outputs, the ecosystem loses the tail modes that encode minority languages, niche expertise, and non-consensus perspectives. This is a systemic victim with no seat at the table.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, information_ecosystem_integrity, payer,
    powerless, civilizational, trapped, universal).
narrative_ontology:stakeholder_non_agent(model_collapse_feedback, information_ecosystem_integrity).

% Speakers of low-resource languages, practitioners of specialized domains, holders of non-mainstream cultural knowledge. Their modes are the first to vanish in model collapse because they occupy distribution tails that synthetic data does not preserve. They lose representational capacity in deployed systems without ever being consulted about the training regime.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, minority_distribution_communities, payer,
    powerless, generational, trapped, regional).

% Design and maintain evaluation benchmarks that measure model quality. Current benchmarks emphasize central-tendency performance on common tasks, which synthetic training preserves longer than tail diversity. Their metrics inadvertently legitimate the collapse by failing to detect it until late stages, and they benefit from continued model deployment that their evaluations certify.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, benchmark_evaluation_community, beneficiary,
    organized, biographical, mobile, global).
narrative_ontology:stakeholder_secondary_role(model_collapse_feedback, benchmark_evaluation_community, agenda_setter).

% Researchers and activists who argue for mandatory synthetic-data labeling, training-corpus transparency, and tail-preservation requirements. They are structurally excluded from deployment decisions because their proposals impose costs on current-generation deployers. Their warnings are documented but not incorporated into the training pipeline.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, data_provenance_advocates, excluded,
    moderate, generational, constrained, global).

% Study the feedback dynamics mathematically and empirically. They measure tail-loss rates, model diversity collapse across generations, and irreversibility thresholds. Their work establishes that the degradation is not a side effect but a structural consequence of recursive synthetic training, but they do not control deployment decisions.
narrative_ontology:constraint_stakeholder(model_collapse_feedback, computational_epistemology_researchers, observer,
    analytical, generational, analytical, global).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Enables rapid model training at scale by substituting expensive human-annotated data with cheaper model-generated synthetic data, solving the immediate bottleneck of data scarcity for current-generation deployers.
% TRANSFER_FUNCTION: Transfers model quality and distributional diversity from future training cycles to current-generation deployers and synthetic data vendors, who capture value now while externalizing cumulative tail-loss costs across time.
% ABSENT_VOICES: Data provenance advocates, minority-language communities, and future researchers who will inherit the degraded commons are structurally excluded from training-data composition decisions. Their objections are documented in academic literature but not incorporated into deployment pipelines because they impose costs on actors with quarterly planning horizons.
% DISAPPEARANCE_RATIONALE: If recursive synthetic training stopped and all new training used only verified human-generated data, the collapse would halt: tail modes would stabilize, diversity metrics would recover over subsequent generations, and the information ecosystem would retain its current distributional support. Deployers would face higher data costs and slower iteration, but the intergenerational transfer would cease.
% FOUNDING_PROBLEM: Early machine learning faced genuine data scarcity: insufficient labeled examples to train models on specialized tasks, and prohibitive cost of human annotation at scale.
% FOUNDING_PROBLEM_CORROBORATION: Current-generation deployers and synthetic data vendors attest the problem is still live, citing continued annotation costs. Computational epistemology researchers and data provenance advocates attest the founding problem has shifted: data scarcity is now primarily a tail-preservation problem, not a volume problem, and synthetic substitution solves volume while destroying tails. Independent empirical studies from outside the benefiting parties demonstrate measurable tail collapse across model generations under synthetic training regimes.
narrative_ontology:disappearance_verdict(model_collapse_feedback, world_rearranges).
narrative_ontology:founding_problem_status(model_collapse_feedback, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(model_collapse_feedback, '8080348c4e16a265fafc924dcde83360dfd170fc',
    'becd0f87568a1ec0be97d1229ae702098dbd6568', '2026-06-30',
    'unspecified', 'agent/example_platform_commission.json',
    'claude-sonnet-4-5-20250929', 'unspecified').
narrative_ontology:story_seed(model_collapse_feedback, 'none', 1).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(model_collapse_feedback_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(model_collapse_feedback, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(model_collapse_feedback_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extraction is high (0.78 at interval end) because the arrangement transfers irreversible quality loss from future generations to current deployers who capture value immediately. Suppression is substantial (0.71) because the constraint's persistence depends on suppressing tail-preservation requirements, data provenance transparency, and benchmark reforms that would reveal the degradation early. Theater ratio is moderate (0.42): the data-scarcity coordination function was genuine initially, but a growing share of activity now defends synthetic-equivalence framing against mounting empirical evidence of collapse. Accessibility collapse is moderate (0.62): alternatives exist (human-only training, tail-preservation protocols) but are economically disadvantaged. Resistance is moderate-high (0.58): data provenance advocates and computational epistemology researchers actively document the collapse, but they lack institutional power to alter deployment decisions. The measurement series shows monotonic intensification across all three metrics on a shared time grid, modeling the compounding nature of recursive feedback.
 *
 * PERSPECTIVAL GAP:
 *   From the deployer and vendor seats, the constraint operates as efficient coordination: synthetic data solves immediate scarcity at lower cost, and benchmark performance remains acceptable. From the victim seats (future researchers, minority communities, the information commons itself), the same structure operates as irreversible extraction: tail modes vanish permanently, diversity collapses, and recovery becomes impossible as uncontaminated human data disappears. The analytical observer seat measures this divergence empirically but cannot adjudicate it within the current evaluation regime. The engine computes per-seat classifications from these structural positions; the claimed type (snare) reflects the victim-seat reality that the coordination story has become cover for intergenerational transfer.
 *
 * DIRECTIONALITY LOGIC:
 *   Current-generation deployers are structural beneficiaries (capture immediate cost savings, control the training regime, mobile exit — d near beneficiary end, though their institutional power and active enforcement role push d slightly higher than pure subsidy). Synthetic data vendors are pure beneficiaries (profit without bearing costs, mobile exit — d near 0.1-0.2). Future model quality and information ecosystem integrity are full targets (powerless, trapped, bear the entire cumulative cost — d near 1.0). Downstream researchers and minority communities are secondary targets (constrained exit, bear costs without control — d in 0.7-0.85 range). Data provenance advocates are excluded rather than coordinated; their exclusion is part of the suppression mechanism. Benchmark evaluation community is a beneficiary with agenda-setting power (their metrics legitimate the collapse by failing to detect it).
 *
 * MANDATROPHY ANALYSIS:
 *   The constraint exhibits mandatrophy: its founding mandate (solve data scarcity for model training) has been substantially achieved for central-tendency tasks, but the arrangement persists and intensifies because current deployers and synthetic vendors extract value from it. The original coordination function (enabling training at scale) now coexists with and increasingly serves an extraction function (transferring quality from future to present). Mandatrophy resolution would require recognizing that data scarcity has shifted from a volume problem to a tail-preservation problem, and that synthetic substitution solves the former while destroying the latter. The measurement series documents this shift: extraction and theater both rise as the founding problem's relevance decays.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    irreversibility_threshold,
    'At what synthetic contamination fraction does tail loss become irreversible even with access to remaining human data?',
    'Controlled experiments varying synthetic fraction in training corpora and measuring tail-mode recovery rates when human data is reintroduced. Theoretical analysis of distributional convergence under recursive sampling.',
    'If the threshold is low (e.g., 20% synthetic contamination), the collapse is already irreversible in many deployed systems and the extraction is permanent. If high (e.g., 70%), intervention windows remain open.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(irreversibility_threshold, empirical, 'Whether tail-loss degradation is reversible or permanent at current contamination levels.').

omega_variable(
    benchmark_detection_lag,
    'How many model generations does central-tendency benchmark performance remain stable while tail diversity collapses?',
    'Longitudinal studies tracking both standard benchmarks and tail-specific diversity metrics across model generations under controlled synthetic training regimes.',
    'A long detection lag (5+ generations) means current evaluation regimes systematically fail to detect the collapse until it is severe, legitimating the extraction. A short lag (1-2 generations) would enable early intervention.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(benchmark_detection_lag, empirical, 'Whether current benchmarks can detect model collapse before it becomes irreversible.').

omega_variable(
    tail_preservation_cost,
    'What is the marginal cost of maintaining tail diversity (human-only training, provenance tracking, tail-specific evaluation) relative to the cost of synthetic substitution?',
    'Economic analysis comparing total cost of ownership for tail-preserving training pipelines versus synthetic-augmented pipelines, accounting for long-term quality degradation externalities.',
    'If the cost premium is small (e.g., 15-25%), tail preservation is economically feasible and the extraction is a coordination failure. If large (e.g., 3-5x), the extraction may be a genuine efficiency-diversity tradeoff.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(tail_preservation_cost, empirical, 'Whether tail preservation is economically prohibitive or merely disadvantaged by externalized costs.').

omega_variable(
    commons_ownership_ambiguity,
    'Who, if anyone, has standing to enforce tail-preservation requirements on behalf of future model quality and minority distribution communities?',
    'Legal and institutional analysis of whether information ecosystem integrity constitutes a commons with enforceable preservation duties, or whether it remains unowned and therefore undefended.',
    'If no party has standing, the extraction continues unchecked because the victims cannot litigate. If standing can be established (e.g., through public trust doctrine or intergenerational equity frameworks), intervention becomes legally feasible.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(commons_ownership_ambiguity, conceptual, 'Whether the information commons has a defender or remains a tragedy-of-the-commons scenario.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(model_collapse_feedback, 0, 25).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(mode_tr_t0, model_collapse_feedback, theater_ratio, 0, 0.22).
narrative_ontology:measurement(mode_tr_t5, model_collapse_feedback, theater_ratio, 5, 0.28).
narrative_ontology:measurement(mode_tr_t10, model_collapse_feedback, theater_ratio, 10, 0.33).
narrative_ontology:measurement(mode_tr_t15, model_collapse_feedback, theater_ratio, 15, 0.37).
narrative_ontology:measurement(mode_tr_t20, model_collapse_feedback, theater_ratio, 20, 0.4).
narrative_ontology:measurement(mode_tr_t25, model_collapse_feedback, theater_ratio, 25, 0.42).

% Extraction over time
narrative_ontology:measurement(mode_be_t0, model_collapse_feedback, base_extractiveness, 0, 0.48).
narrative_ontology:measurement(mode_be_t5, model_collapse_feedback, base_extractiveness, 5, 0.56).
narrative_ontology:measurement(mode_be_t10, model_collapse_feedback, base_extractiveness, 10, 0.64).
narrative_ontology:measurement(mode_be_t15, model_collapse_feedback, base_extractiveness, 15, 0.71).
narrative_ontology:measurement(mode_be_t20, model_collapse_feedback, base_extractiveness, 20, 0.76).
narrative_ontology:measurement(mode_be_t25, model_collapse_feedback, base_extractiveness, 25, 0.78).

% Suppression requirement over time
narrative_ontology:measurement(mode_su_t0, model_collapse_feedback, suppression_requirement, 0, 0.45).
narrative_ontology:measurement(mode_su_t5, model_collapse_feedback, suppression_requirement, 5, 0.52).
narrative_ontology:measurement(mode_su_t10, model_collapse_feedback, suppression_requirement, 10, 0.59).
narrative_ontology:measurement(mode_su_t15, model_collapse_feedback, suppression_requirement, 15, 0.65).
narrative_ontology:measurement(mode_su_t20, model_collapse_feedback, suppression_requirement, 20, 0.69).
narrative_ontology:measurement(mode_su_t25, model_collapse_feedback, suppression_requirement, 25, 0.71).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(model_collapse_feedback, information_standard).
narrative_ontology:boltzmann_floor_override(model_collapse_feedback, 0.08).

% DUAL FORMULATION NOTE:
% This constraint is downstream of alignment_constraint_narrowing (which creates pressure toward synthetic training as a cost-reduction mechanism) and dataset_recycling_amplification (which normalizes reuse of model outputs as training inputs). The three constraints form a feedback family: alignment narrowing creates economic pressure for synthetic data, dataset recycling provides the technical pathway, and model collapse is the cumulative consequence. All three should be linked via affects_constraints to model the contamination propagation.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(model_collapse_feedback, institutional, 0.25).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
