% ============================================================================
% CONSTRAINT STORY: simultaneous_veneration__ontological_fusion_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-12
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_simultaneous_veneration__ontological_fusion_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: simultaneous_veneration__ontological_fusion_reading
 *   human_readable: Honji-Suijaku Ontological Fusion: Buddhist Interpretive Monopoly over Kami
 *   domain: religious/metaphysical/institutional
 *
 * SUMMARY:
 *   In medieval and early modern Japan, simultaneous veneration of kami
 *   (indigenous deities rooted in place, history, and agricultural cycles)
 *   and buddhist figures (buddhas and bodhisattvas claimed as universal
 *   salvific truth) faced a logical coherence problem. Honji-suijaku theory
 *   (the original essence / manifest trace distinction) solved this by
 *   asserting kami are local manifestations of universal Buddhist entities —
 *   a single metaphysical reality expressed through different cultural
 *   lenses. This constraint story instantiates ONE reading of a contested
 *   kernel: the simultaneous-veneration fact. The honji-suijaku reading
 *   claims to capture metaphysical truth; two sibling readings
 *   (domain-partition reading: kami and buddhas are genuinely distinct;
 *   pragmatic-incoherence reading: coherence was never achieved) offer
 *   structurally different accounts of the same historical practice. This
 *   story traces honji-suijaku's structural consequences: Buddhist
 *   institutional hierarchy claims interpretive monopoly; indigenous kami
 *   practitioners' autonomy narratives are subordinated; local shrine
 *   authority is absorbed into Buddhist temple networks. The authoring
 *   position separates the truth claim from the extraction claim (independent
 *   axes): a doctrine can be metaphysically true AND extractive if only
 *   certain institutional actors are permitted to interpret it. This story
 *   traces the extractive institutional path generated by the
 *   ontological-fusion reading.
 *
 * KEY AGENTS:
 *   - buddhist_institutional_hierarchy: Institutional agenda-setter and beneficiary; controls temple networks, textual transmission, ordination; benefits from honji-suijaku's elevation of Buddhist cosmology as universal explanatory framework; power: institutional; exit: arbitrage (can adopt alternatives at prestige cost).
 *   - indigenous_kami_practitioners: Primary victim; identity-locked (kami veneration constitutive of local identity and place); bear cost of interpretive subordination — their own account of kami as autonomous beings is reframed as metaphysically mistaken; power: moderate; exit: identity-locked (cannot exit without losing cultural self).
 *   - local_shrine_autonomy: Institutional victim; loses independent authority when kami redefined as Buddha-manifestations; absorbed into Buddhist temple network; power: moderate; exit: constrained (refusal means marginalization).
 *   - buddhist_scholars_theologians: Beneficiaries; advance careers through mastery of honji-suijaku framework; power: institutional; exit: mobile (can adopt alternatives but lose prestige).
 *   - lay_practitioners: Asymmetric beneficiary-payer; experience genuine intellectual satisfaction (unified cosmology) but diminished interpretation authority (defer to institutional Buddhist reading); power: powerless; exit: constrained.
 *   - alternative_reading_advocates: Excluded (would argue domain-partition or pragmatic-incoherence); barred from institutional authority; power: powerless; exit: trapped.
 *   - meiji_state_authorities: Analytical observers; enforce separation (1868+), revealing prior constraint was maintained by institutional authority, not metaphysical necessity.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(simultaneous_veneration__ontological_fusion_reading, 0.82).
domain_priors:suppression_score(simultaneous_veneration__ontological_fusion_reading, 0.71).
domain_priors:theater_ratio(simultaneous_veneration__ontological_fusion_reading, 0.58).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(simultaneous_veneration__ontological_fusion_reading, extractiveness, 0.82).
narrative_ontology:constraint_metric(simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 0.71).
narrative_ontology:constraint_metric(simultaneous_veneration__ontological_fusion_reading, theater_ratio, 0.58).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(simultaneous_veneration__ontological_fusion_reading, accessibility_collapse, 0.73).
narrative_ontology:constraint_metric(simultaneous_veneration__ontological_fusion_reading, resistance, 0.68).

% --- Constraint claim ---
narrative_ontology:constraint_claim(simultaneous_veneration__ontological_fusion_reading, tangled_rope).
narrative_ontology:human_readable(simultaneous_veneration__ontological_fusion_reading, "Honji-Suijaku Ontological Fusion: Buddhist Interpretive Monopoly over Kami").
narrative_ontology:topic_domain(simultaneous_veneration__ontological_fusion_reading, "religious/metaphysical/institutional").

domain_priors:requires_active_enforcement(simultaneous_veneration__ontological_fusion_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(simultaneous_veneration__ontological_fusion_reading, '33caf761-e08e-4e07-83e9-566a705c4aec').
narrative_ontology:cs_kernel_codification('33caf761-e08e-4e07-83e9-566a705c4aec', fixed_text).
narrative_ontology:cs_authority_grounding('33caf761-e08e-4e07-83e9-566a705c4aec', extraction).
narrative_ontology:cs_interpretation_layer_present('33caf761-e08e-4e07-83e9-566a705c4aec').
narrative_ontology:cs_reading_relation('33caf761-e08e-4e07-83e9-566a705c4aec', simultaneous_veneration__domain_partition_reading, forecloses).
narrative_ontology:cs_reading_relation('33caf761-e08e-4e07-83e9-566a705c4aec', simultaneous_veneration__pragmatic_incoherence_reading, forecloses).
narrative_ontology:cs_axiom('33caf761-e08e-4e07-83e9-566a705c4aec', foundational, metaphysical_monism_kami_buddha_identity).
narrative_ontology:cs_axiom_status(metaphysical_monism_kami_buddha_identity, holdable).
narrative_ontology:cs_axiom_grounding('33caf761-e08e-4e07-83e9-566a705c4aec', metaphysical_monism_kami_buddha_identity, deontological).
narrative_ontology:cs_axiom('33caf761-e08e-4e07-83e9-566a705c4aec', foundational, buddhist_universal_interpretive_authority).
narrative_ontology:cs_axiom_status(buddhist_universal_interpretive_authority, holdable).
narrative_ontology:cs_axiom_grounding('33caf761-e08e-4e07-83e9-566a705c4aec', buddhist_universal_interpretive_authority, instrumental).
narrative_ontology:cs_reference_frame('33caf761-e08e-4e07-83e9-566a705c4aec', universal_buddhist_metaphysical_hierarchy).
narrative_ontology:cs_drift_state('33caf761-e08e-4e07-83e9-566a705c4aec', meiji_restoration_enforced_separation, gap(authority_erosion, severe, true)).
narrative_ontology:cs_created_at('33caf761-e08e-4e07-83e9-566a705c4aec', '').
narrative_ontology:cs_kernel_id(simultaneous_veneration__ontological_fusion_reading, simultaneous_veneration).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(simultaneous_veneration__ontological_fusion_reading, buddhist_institutional_hierarchy).
narrative_ontology:constraint_victim(simultaneous_veneration__ontological_fusion_reading, indigenous_kami_practitioners).
narrative_ontology:constraint_victim(simultaneous_veneration__ontological_fusion_reading, local_shrine_autonomy).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(simultaneous_veneration__ontological_fusion_reading, '22843cdfd28a814d8f30c35778e75821452545bd',
    '2e9dff2fe8ce0cd758f85569a335a6c41ea42068', '2026-06-13',
    'no_scope_rebuild', 'agent/example_platform_commission.json',
    'claude-haiku-4-5-20251001', 'max_tokens=16384,temperature=api_default').
narrative_ontology:story_seed(simultaneous_veneration__ontological_fusion_reading, 'none', 1).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(simultaneous_veneration__ontological_fusion_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(simultaneous_veneration__ontological_fusion_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(simultaneous_veneration__ontological_fusion_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is high (0.82) and rises monotonically from 0.58 across the interval because the constraint transfers interpretive authority from local practitioners to Buddhist institutional hierarchy without equivalent return in institutional autonomy. Early adoption by elite Tendai/Shingon circles generated lower extractiveness (0.58 — more voluntary, less enforced); systematization and state reinforcement raised extractiveness as the doctrine became Buddhist orthodoxy (final value 0.82). Suppression is substantial (0.71) because persistence depends on actively excluding alternative readings from institutional authority (what would domain-partition advocates propose? what would pragmatic-incoherence advocates claim?) and reinterpreting indigenous narratives as misunderstandings rather than legitimate alternatives. Theater ratio rises monotonically to 0.58 and plateaus because as the doctrine matured, growing share of enforcement activity is textual commentary and scholastic argument (performative maintenance of metaphysical truth) rather than functional coordination. Accessibility collapse is moderate (0.73) because practitioners could in principle adopt alternatives, but institutional barriers (control of temples, education, prestige positions) make alternatives costly; local folk communities sometimes sustained kami-autonomy framings despite institutional suppression. Resistance is substantial (0.68) because indigenous practitioners and alternative-reading advocates continuously object to the monopoly, though suppressed rather than militarily crushed. The measurement series all share the single time grid (t=0 to t=40) so temporal analysis has coherent data; no metric is authored at different endpoints.
 *
 * PERSPECTIVAL GAP:
 *   Buddhist institutional seat and indigenous kami practitioner seat should compute radically different types from the engine. From institutional Buddhist seat: this is genuine coordination. Honji-suijaku solves the logical coherence problem and provides an elegant metaphysical framework practitioners appreciate (they experience the constraint as intellectual unification). The constraint's work is real — it enables simultaneous practice without contradiction. From indigenous seat: the same structure operates as enforced interpretive subordination. Kami autonomy is overridden, shrine authority is absorbed, and practitioners are told their own understanding is metaphysically mistaken. The constraint's work is authority extraction disguised as truth discovery. The engine computes this divergence from structural data: institutional seat is (institutional power + arbitrage exit + agenda-setter role) → lower directionality (beneficiary range); indigenous seat is (moderate power + identity-locked exit + victim role) → higher directionality (target range). The structural asymmetry is authored explicitly; the engine computes per-seat types from it. The claim/metric independence rule is key here: honji-suijaku is CLAIMED as tangled_rope (has coordination + asymmetric extraction). The metrics describe high extractiveness and suppression. If the engine computed this as snare or rope, that divergence is the measurement the corpus exists to take.
 *
 * DIRECTIONALITY LOGIC:
 *   Buddhist institutional hierarchy: Beneficiary seat. Power is institutional (control temple networks, textual transmission, ordination authority), exit is arbitrage (could adopt alternatives but at career cost), role is agenda-setter (sets the doctrine, enforces through institutional authority). Directionality d near 0.10 (full beneficiary leaning) — they collect interpretive authority and institutional prestige; the constraint's benefits accrue to them. The beneficiary declaration captures this structural position. Indigenous kami practitioners: Victim seat. Power is moderate (can mount community resistance but lack institutional platform), exit is identity-locked (cannot abandon kami veneration without losing self-concept and community), role is victim (bear the cost of interpretive subordination). Directionality d near 0.90 (near-full target) — they bear the extraction (loss of explanatory autonomy, reinterpretation of their practice); the constraint operates on them. The victim declaration captures this. Local shrine autonomy: Victim-adjacent seat. Power is moderate, exit is constrained (refusal means marginalization), role is payer (loses autonomous authority). Directionality d near 0.85-0.90. Buddhist scholars: Beneficiary seat with mobile exit. Power is institutional, exit is mobile (can leave by adopting alternatives), role is beneficiary (prestige/career advancement). Directionality d near 0.25-0.30 (beneficiary with visible exit) — override from structural derivation (~0.18) to 0.12 to reflect that while they profit from the framework, exit is more available than pure beneficiary would suggest; their d reflects that. Lay practitioners: Hybrid seat near symmetric. Power is powerless, exit is constrained, role is beneficiary + payer (both gain coordination value and lose interpretive authority). Directionality d near 0.45-0.55 (symmetric with asymmetric components) — they benefit and pay roughly equally, but the asymmetry is that the benefit is automatic while the payment is enforced.
 *
 * MANDATROPHY ANALYSIS:
 *   The tangled_rope classification prevents false natural-law misreading and false pure-extraction misreading. If this were labeled mountain: the framework would claim honji-suijaku is unchangeable natural law, that simultaneous veneration necessarily requires this doctrine, that the constraint would persist regardless of institutional enforcement. False natural-law reading. The extracted ε (0.82) and suppression (0.71) make this implausible; the Meiji refutation (constraint collapsed when institutional enforcement shifted) proves it is not natural law. If this were labeled snare: the classification would claim no genuine coordination function, that the entire arrangement is extraction justified by false universality claim. But practitioners genuinely experience intellectual coherence and logical unification from honji-suijaku — this is not all cover story. The coordination is real even though it is asymmetric. Tangled_rope correctly names both: the constraint solves a genuine logical problem (coordination function is real) AND it asymmetrically transfers authority from indigenous to institutional Buddhist seats (extraction is real). The measurement series reinforces this: early high coordination value (extractiveness rising from 0.58 suggests accumulating extraction overlaid on coordination foundation), theater ratio plateauing at 0.58 (doctrinal elaboration is performative maintenance, not functional adaptation), suppression remaining high (enforcement required to exclude alternatives indicates coordination is enforced, not voluntary). A piton reading would claim the function has atrophied and only performance remains — but the coordination (resolution of logical incoherence problem) remains functionally vital, so piton does not fit.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    metaphysical_monism_vs_constructed_hermeneutics,
    'Is honji-suijaku an accurate metaphysical description of kami and buddhist ontology, or is it a hermeneutical framework constructed to justify Buddhist institutional authority over indigenous practice?',
    'Genealogical analysis of honji-suijaku''s origin: when did the doctrine emerge (Heian period?), in what institutional contexts (Tendai/Shingon elite circles?), for what stated purposes? Comparison with alternative metaphysical frameworks that would equally permit simultaneous veneration (domain-partition, plurality without unity). Examination of whether practitioners spontaneously adopted this reading or required institutional enforcement and education to accept it. Post-Meiji analysis: when separation was enforced, did practitioners readily accept it (suggesting prior framework was institutional imposition) or resist it (suggesting genuine metaphysical commitment)?',
    'If genuine metaphysical truth: the extraction reading is underestimated; the constraint serves real coordination function and the transfer of authority is price of maintaining truth. If constructed hermeneutics: the constraint is primarily extractive institutional monopoly disguised as metaphysical discovery; reclassification slides toward snare (pure extraction justified by false universality claim). This is the foundational omega for the reading: the claim to capture metaphysical truth is precisely what enables institutional authority extraction.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(metaphysical_monism_vs_constructed_hermeneutics, empirical, 'Whether honji-suijaku is discovered metaphysical truth or constructed interpretive monopoly.').

omega_variable(
    indigenous_kami_autonomy_suppression_mechanism,
    'Is the suppression of indigenous kami-autonomy narratives structural (enforced by institutional authority, economic dependency on Buddhist temple networks, exclusion from positions of religious legitimacy) or internalized (practitioners come to believe in Buddhist universalism as truth, not coercion)?',
    'Historical trace of resistance or dissent from indigenous kami practitioners: did they mount challenges to honji-suijaku? If suppressed, through what mechanisms (exclusion from institutional authority, economic pressure, doctrinal condemnation)? Did kami-autonomy framings persist at local/folk level despite institutional suppression (indicating internalization was partial)? Post-Meiji analysis: when external enforcement shifted from Buddhist institutional authority to state secular authority, did practitioners maintain honji-suijaku commitment or adopt domain-partition/pragmatic-incoherence readings (indicating prior suppression was primarily structural, not internalized)?',
    'If primarily structural: suppression metric (0.71) is accurate; exit remains constrained but not internalized. If significantly internalized: the measured suppression underestimates effective lock-in; victim populations carry the constraint with them even after institutional enforcement ceases — they continue to believe honji-suijaku metaphysical truth even when alternative readings are made available. Internalization would indicate more extensive extractive capture than suppression metric alone suggests.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(indigenous_kami_autonomy_suppression_mechanism, empirical, 'Structural vs. internalized suppression of indigenous kami-autonomy narratives.').

omega_variable(
    kernel_reading_contest_containment,
    'Does the honji-suijaku reading logically foreclose its sibling readings (domain-partition, pragmatic-incoherence), or do all three readings remain live positions that can coexist in different institutional and lay contexts?',
    'Historical documentation: were alternative readings explicitly repudiated as heretically false, or merely subordinated as less sophisticated? Did Buddhist texts contain refutations of domain-partition and pragmatic-incoherence readings, or only elevation of honji-suijaku? Lay practice analysis: did practitioners sustain multiple readings simultaneously (honji-suijaku at institutional level, domain-partition at folk level)? Post-Meiji reorganization: which readings became primary, which persisted in marginal contexts? Did any re-emerge with vigor once institutional Buddhist authority weakened?',
    'If honji-suijaku logically forecloses siblings within the commitment framework: the constraint is a coherent metaphysical system competing with alternatives on epistemic grounds — classification is more sustainable as tangled_rope with genuine coordination function. If all three readings remain live in practice: honji-suijaku is one hegemonic reading suppressing alternatives that could equally rationalize practice — reclassifies toward snare (pure extraction justified by false universality and false logical necessity claim).',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_reading_contest_containment, conceptual, 'Does honji-suijaku logically foreclose or institutionally suppress sibling readings?').

omega_variable(
    meiji_refutation_as_epistemic_signal,
    'The Meiji Restoration enforced separation of kami and buddhism, suggesting prior fusion was not natural or necessary. Does the enforceability of reversal indicate honji-suijaku constraint required continuous institutional maintenance, or was reversal itself an artificial imposition that practitioners later resisted?',
    'Comparative analysis: did honji-suijaku practice re-emerge after Meiji separation was relaxed (post-WWII loosening of state control)? How quickly did honji-suijaku framing reassert among practitioners or remain displaced? Was Meiji separation state-enforced through legal/economic coercion (suggesting prior constraint was institutional), or did practitioners voluntarily accept separation and maintain it independently? Post-1950s religious freedom: do contemporary practitioners voluntarily practice honji-suijaku fusion or maintain Meiji-imposed separation? Do they experience separation as natural or as historical accident they inherited?',
    'If constraint reasserted after Meiji pressure relaxed: it has institutional or deep practitioner commitment roots. If it did not reassert despite opportunity: it was sustained primarily by enforced institutional authority and would require re-establishment of that authority to re-emerge. This indicates whether the constraint is self-sustaining or requires continuous enforcement.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(meiji_refutation_as_epistemic_signal, empirical, 'Whether honji-suijaku constraint''s persistence is institutionally driven or self-sustaining.').

omega_variable(
    kernel_reading_distinction_validity,
    'Is the decomposition of simultaneous-veneration kernel into three distinct readings (ontological-fusion, domain-partition, pragmatic-incoherence) structurally justified, or do these represent merely different evaluative framings of a single constraint that should be unified?',
    'ε-invariance test: do the three readings generate significantly different ε values (~>0.15 absolute difference)? Yes — ontological-fusion generates 0.82, domain-partition would generate ~0.40-0.50 (no institutional monopoly claim), pragmatic-incoherence would generate ~0.35-0.45 (no false truth claim to maintain). Different beneficiary/victim structures? Yes — ontological-fusion benefits Buddhist hierarchy and harms indigenous practitioners; domain-partition benefits both by accepting their separate domains; pragmatic-incoherence benefits honesty advocates. Different suppression requirements? Yes — ontological-fusion requires high suppression (0.71) to maintain claim to truth; domain-partition requires low suppression (0.20-0.30, mere functional coordination); pragmatic-incoherence requires low suppression (accepting contradiction is easy). Decomposition is valid per ε-invariance principle.',
    'If decomposition is valid: three separate constraint stories with separate network links is correct authoring. If not valid: this story should be retracted and replaced with a unified story with measurement variations along an ''reading weight'' axis (not recommended by framework — framework rejects observable-dependent ε).',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(kernel_reading_distinction_validity, conceptual, 'ε-invariance validity of kernel reading decomposition.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(simultaneous_veneration__ontological_fusion_reading, 0, 40).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(simu_tr_t0, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 0, 0.32).
narrative_ontology:measurement(simu_tr_t5, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 5, 0.38).
narrative_ontology:measurement(simu_tr_t10, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 10, 0.44).
narrative_ontology:measurement(simu_tr_t15, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 15, 0.5).
narrative_ontology:measurement(simu_tr_t20, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 20, 0.55).
narrative_ontology:measurement(simu_tr_t25, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 25, 0.58).
narrative_ontology:measurement(simu_tr_t30, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 30, 0.58).
narrative_ontology:measurement(simu_tr_t40, simultaneous_veneration__ontological_fusion_reading, theater_ratio, 40, 0.58).

% Extraction over time
narrative_ontology:measurement(simu_be_t0, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 0, 0.58).
narrative_ontology:measurement(simu_be_t5, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 5, 0.64).
narrative_ontology:measurement(simu_be_t10, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 10, 0.71).
narrative_ontology:measurement(simu_be_t15, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 15, 0.76).
narrative_ontology:measurement(simu_be_t20, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 20, 0.8).
narrative_ontology:measurement(simu_be_t25, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 25, 0.81).
narrative_ontology:measurement(simu_be_t30, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 30, 0.82).
narrative_ontology:measurement(simu_be_t40, simultaneous_veneration__ontological_fusion_reading, base_extractiveness, 40, 0.82).

% Suppression requirement over time
narrative_ontology:measurement(simu_su_t0, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 0, 0.42).
narrative_ontology:measurement(simu_su_t5, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 5, 0.5).
narrative_ontology:measurement(simu_su_t10, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 10, 0.57).
narrative_ontology:measurement(simu_su_t15, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 15, 0.63).
narrative_ontology:measurement(simu_su_t20, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 20, 0.68).
narrative_ontology:measurement(simu_su_t25, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 25, 0.7).
narrative_ontology:measurement(simu_su_t30, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 30, 0.71).
narrative_ontology:measurement(simu_su_t40, simultaneous_veneration__ontological_fusion_reading, suppression_requirement, 40, 0.71).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(simultaneous_veneration__ontological_fusion_reading, identity_coordination).
narrative_ontology:boltzmann_floor_override(simultaneous_veneration__ontological_fusion_reading, 0.1).
narrative_ontology:affects_constraint(simultaneous_veneration__ontological_fusion_reading, simultaneous_veneration__domain_partition_reading).
narrative_ontology:affects_constraint(simultaneous_veneration__ontological_fusion_reading, simultaneous_veneration__pragmatic_incoherence_reading).

% DUAL FORMULATION NOTE:
% The simultaneous_veneration kernel decomposes into three structurally distinct constraint stories, each instantiating a different reading of the historical practice. This story (ontological_fusion_reading) asserts honji-suijaku captures metaphysical truth and generates high extraction through Buddhist institutional interpretive monopoly. The sibling stories (domain_partition_reading, pragmatic_incoherence_reading) offer alternative accounts with different ε values, beneficiary/victim structures, and classifications. All three are linked via network.affects_constraints to represent the kernel contest: the three readings compete to be the legitimate account of simultaneous veneration. The choice among readings has structural consequences — which reading becomes institutionally dominant determines who bears extraction costs and whose autonomy narratives are subordinated. See kernel_context in commentary for the decomposition logic.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(simultaneous_veneration__ontological_fusion_reading, moderate, 0.12).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
