% ============================================================================
% CONSTRAINT STORY: synthetic_data_feedback_loop
% ============================================================================
% Version: 5.2 (Deferential Realism Core + Boltzmann + Purity + Network)
% Logic: 5.2 (Indexed Tuple P,T,E,S + Coupling + Purity + Network Drift)
% Generated: 2024-07-16
% ============================================================================

:- module(constraint_synthetic_data_feedback_loop, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 * * constraint_id: synthetic_data_feedback_loop
 * human_readable: The Model Autophagy Trap
 * domain: technological/AI/informational
 * * SUMMARY:
 * A scenario where AI models are increasingly trained on data generated by
 * previous generations of AI, leading to "model collapse." This "Rope" for
 * infinite data scaling becomes a "Snare" as the informational diversity of
 * the internet is liquidated, trapping the system in a self-reinforcing
 * loop of decreasing variance and increasing hallucination.
 * * KEY AGENTS:
 * - Independent Content Creator: Subject (Powerless)
 * - Large-Scale Model Trainer: Beneficiary (Institutional)
 * - Informational Ecologist: Auditor (Analytical)
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% High extraction (0.88) because the loop liquidates the "ground truth"
% biological signal to feed the institutional need for low-cost tokens.
domain_priors:base_extractiveness(synthetic_data_feedback_loop, 0.88).
domain_priors:suppression_score(synthetic_data_feedback_loop, 0.72).
domain_priors:theater_ratio(synthetic_data_feedback_loop, 0.81). % High theater: performative claims of "data quality" masking entropic decay.

% Constraint metric facts — primary keys used by the classification engine.
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, extractiveness, 0.88).
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, suppression_requirement, 0.72).
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, theater_ratio, 0.81).

% Constraint self-claim (what does the constraint claim to be?)
narrative_ontology:constraint_claim(synthetic_data_feedback_loop, tangled_rope).

% Binary flags
domain_priors:requires_active_enforcement(synthetic_data_feedback_loop). % Required for Tangled Rope

% Structural property derivation hooks:
% has_coordination_function/1 is DERIVED from constraint_beneficiary/2
% has_asymmetric_extraction/1 is DERIVED from constraint_victim/2
narrative_ontology:constraint_beneficiary(synthetic_data_feedback_loop, large_scale_model_trainer).
narrative_ontology:constraint_victim(synthetic_data_feedback_loop, independent_content_creator).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   χ = ε × π(P) × σ(S)
   Power (P) and Scope (S) both affect effective extraction.
   Scope modifiers: local=0.8, regional=0.9, national=1.0,
                    continental=1.1, global=1.2, universal=1.0.
   ========================================================================== */

% PERSPECTIVE 1: THE SUBJECT (SNARE)
% The human creator is trapped: their original work is drowned out by
% high-volume synthetic mimics, liquidating their visibility and economic agency.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(national))).

% PERSPECTIVE 2: THE BENEFICIARY (ROPE)
% The trainer views synthetic data as a Rope—the only way to coordinate
% the massive token counts required for frontier capability without
% exhausting the finite supply of human-written text.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(mobile),
            spatial_scope(global))).

% PERSPECTIVE 3: THE ANALYTICAL OBSERVER (TANGLED ROPE)
% Detects the dual nature: a genuine coordination problem (data scaling)
% solved via a mechanism with severe asymmetric extraction (liquidating the commons).
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

% PERSPECTIVE 4: THE SYSTEMS AUDITOR (PITON)
% Theater ratio (0.81) > 0.70 triggers Piton: the "Reinforcement Learning"
% protocols are an inertial spike; they refine the mean but no longer
% capture the territory of reality.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, piton,
    context(agent_power(analytical),
            time_horizon(historical),
            exit_options(arbitrage),
            spatial_scope(universal))) :-
    domain_priors:theater_ratio(synthetic_data_feedback_loop, TR), TR > 0.70.

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(synthetic_data_feedback_loop_tests).

test(perspectival_gap) :-
    % Verify Snare for the subject vs Rope for the institutional trainer.
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, snare,
        context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, rope,
        context(agent_power(institutional), _, _, _)),
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, tangled_rope,
        context(agent_power(analytical), _, _, _)).

test(piton_trigger) :-
    % Ensure high theater ratio (0.81) correctly triggers the Piton classification.
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, piton,
        context(agent_power(analytical), _, _, _)).

test(threshold_validation) :-
    % Ensure high extraction (0.88) is consistent with high-extraction types.
    config:param(extractiveness_metric_name, ExtMetricName),
    narrative_ontology:constraint_metric(synthetic_data_feedback_loop, ExtMetricName, E),
    (E >= 0.46).

:- end_tests(synthetic_data_feedback_loop_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 * The extraction score (0.88) reflects a "Mandatrophy" state where the
 * "coordination" of data scaling is actually a parasitic liquidation of the
 * informational commons. The high theater ratio (0.81) indicates that the
 * performative aspects of "data curation" and "alignment" now outweigh the
 * functional goal of modeling reality, leading to the Piton classification.
 *
 * * PERSPECTIVAL GAP:
 * The Content Creator feels a Snare because their unique signal is
 * cannibalized by the system. The Trainer sees a Rope because the scaling
 * laws demand more data than the species can produce biologically.
 * * [RESOLVED MANDATROPHY]:
 * Resolved via the Tangled Rope classification. This prevents the system from
 * collapsing the constraint into a pure Snare, correctly identifying that a
 * genuine coordination function (data scaling) exists alongside the severe
 * asymmetric extraction. The Piton classification further refines this,
 * showing that the original function has degraded into theatrical maintenance.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

% Required for high-extraction constraints (> 0.46).
omega_variable(
    omega_autophagous_threshold,
    'Can "curated" synthetic data prevent collapse, or is entropy absolute (Snare vs Mountain)?',
    'Tracking the perplexity delta between models trained on 10% vs 90% synthetic data.',
    'If perplexity stabilizes: Snare of current technique. If it explodes: Mountain of Information Entropy.',
    confidence_without_resolution(medium)
).

/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

% Required for external script parsing
narrative_ontology:interval(synthetic_data_feedback_loop, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Temporal data enables drift detection. This models the constraint's
% degradation from a necessary scaling tool into a parasitic, high-theater loop.
% Required for high-extraction constraints (base_extractiveness > 0.46).

% Theater ratio over time (triggers metric_substitution detection):
narrative_ontology:measurement(sdf_tr_t0, synthetic_data_feedback_loop, theater_ratio, 0, 0.20).
narrative_ontology:measurement(sdf_tr_t5, synthetic_data_feedback_loop, theater_ratio, 5, 0.55).
narrative_ontology:measurement(sdf_tr_t10, synthetic_data_feedback_loop, theater_ratio, 10, 0.81).

% Extraction over time (triggers extraction_accumulation detection):
narrative_ontology:measurement(sdf_ex_t0, synthetic_data_feedback_loop, base_extractiveness, 0, 0.50).
narrative_ontology:measurement(sdf_ex_t5, synthetic_data_feedback_loop, base_extractiveness, 5, 0.75).
narrative_ontology:measurement(sdf_ex_t10, synthetic_data_feedback_loop, base_extractiveness, 10, 0.88).

/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA (v5.0-5.2)
   ========================================================================== */

% Coordination type (enables Boltzmann floor + complexity offset)
% The constraint is a mechanism for allocating training data resources.
narrative_ontology:coordination_type(synthetic_data_feedback_loop, resource_allocation).

% Network relationships (structural influence edges)
% The degradation of the information commons by this loop directly impacts
% the reliability of scientific and journalistic outputs.
narrative_ontology:affects_constraint(synthetic_data_feedback_loop, scientific_reproducibility).
narrative_ontology:affects_constraint(synthetic_data_feedback_loop, journalistic_integrity).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */