% ============================================================================
% CONSTRAINT STORY: synthetic_data_feedback_loop
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-02-26
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_synthetic_data_feedback_loop, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: synthetic_data_feedback_loop
 *   human_readable: The Model Autophagy Trap
 *   domain: technological/AI/informational
 *
 * SUMMARY:
 *   The synthetic data feedback loop represents a structural trap where AI
 *   model training increasingly depends on data generated by
 *   previous-generation models, degrading information diversity and model
 *   capacity in a self-reinforcing cycle. This constraint exhibits the
 *   classic snare signature: high suppression (barriers to obtaining
 *   human-generated data due to capital costs and licensing friction), high
 *   extractiveness (training providers benefit from short-term scaling while
 *   the epistemic commons is liquidated), and victims with no practical exit
 *   (information diversity, users, independent data producers). The
 *   constraint manifests differently across institutional perspectives: for
 *   commercial training providers it appears as coordination logic (a
 *   solution to data scarcity), for end users it appears as performance
 *   ceiling collapse, for content creators it appears as labor extraction
 *   without compensation, for the research community it appears as degraded
 *   verification substrate. The analytical observer risks naturalizing the
 *   feedback loop as an inevitable information-theoretic limit when it is
 *   actually a contingent choice to prioritize synthetic data over licensing
 *   diverse information sources. The theater ratio is moderate (0.48) because
 *   the production of synthetic data and model training involves genuine
 *   computational work, not pure performance — but the substitution of
 *   synthetic for human-generated training data increasingly obscures what
 *   actual model capabilities are versus what appears to work on synthetic
 *   benchmarks.
 *
 * KEY AGENTS:
 *   - Commercial AI Training Providers: Primary beneficiary (institutional/arbitrage) — capture scaling advantages and avoid licensing costs in immediate product cycles (1-3 years)
 *   - Information Diversity (Epistemic Commons): Primary victim (powerless/trapped) — unique human-generated content is progressively liquidated; cannot organize or exit; no alternative source of original information
 *   - End Users / Downstream Model Consumers: Secondary victim (moderate/constrained) — experience model capability ceiling; exit options constrained to competing models facing same loop or waiting for breakthroughs
 *   - Independent Data Producers / Content Creators: Secondary victim (powerful/mobile) — labor and intellectual property extracted without compensation; exit options exist but friction-laden (opt-out, platform migration, legal action)
 *   - Research Community / Academic Discourse: Tertiary actor (institutional/arbitrage) — maintains performative verification structures while substrate degrades; sees own credibility mechanisms as increasingly theatrical
 *   - Analytical Observer: Civilizational perspective (analytical/analytical) — risks false summit by naturalizing contingent capital constraints as information-theoretic inevitability
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(synthetic_data_feedback_loop, 0.58).
domain_priors:suppression_score(synthetic_data_feedback_loop, 0.62).
domain_priors:theater_ratio(synthetic_data_feedback_loop, 0.48).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, extractiveness, 0.58).
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, suppression_requirement, 0.62).
narrative_ontology:constraint_metric(synthetic_data_feedback_loop, theater_ratio, 0.48).

% --- Constraint claim ---
narrative_ontology:constraint_claim(synthetic_data_feedback_loop, snare).
narrative_ontology:human_readable(synthetic_data_feedback_loop, "The Model Autophagy Trap").
narrative_ontology:topic_domain(synthetic_data_feedback_loop, "technological/AI/informational").

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(synthetic_data_feedback_loop, model_training_providers).
narrative_ontology:constraint_beneficiary(synthetic_data_feedback_loop, commercial_ai_platforms).
narrative_ontology:constraint_victim(synthetic_data_feedback_loop, information_diversity).
narrative_ontology:constraint_victim(synthetic_data_feedback_loop, future_model_capacity).
narrative_ontology:constraint_victim(synthetic_data_feedback_loop, end_users).
narrative_ontology:constraint_victim(synthetic_data_feedback_loop, independent_data_producers).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: INFORMATION DIVERSITY (SNARE) — The epistemic commons (diverse human-generated content, cultural voices, marginal perspectives) cannot organize to exit the feedback loop. As training datasets become progressively synthetic, the diversity of information available for future training contracts irreversibly. This constraint extracts the unique informational substrate that made the original training possible, leaving only degraded copies. Maximum experienced extraction — the commons has no alternative and no recourse.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(global))).

% PERSPECTIVE 2: END USERS / MODEL QUALITY DEGRADATION (SNARE) — Users of downstream models experience model collapse as performance ceiling lowered by constrained training data. Exit options are constrained: switching to competing models (which face the same loop), waiting for architectural breakthroughs (uncertain), or funding alternative training approaches (capital barriers). The constraint extracts utility from user expectations by degrading model capabilities over generational timescales. High experienced extraction with constrained but real exit options.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, snare,
    context(agent_power(moderate),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(global))).

% PERSPECTIVE 3: COMMERCIAL AI PLATFORMS (ROPE) — The largest training providers benefit from the illusion of infinite scaling: synthetic data appears to solve the training data bottleneck in the immediate term (1-3 year product cycles). They experience the constraint as coordination logic: using model outputs as training data enables continuous product iteration without licensing costs. Arbitrage exit exists — these institutions can license proprietary human-generated data or fund content production. The constraint functions as coordination for them: aggregate and deploy. Net beneficiary perspective.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, rope,
    context(agent_power(institutional),
            time_horizon(immediate),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 4: INDEPENDENT DATA PRODUCERS (TANGLED ROPE) — Content creators, writers, researchers face a hybrid: their work is liquidated as training material (extracted without compensation in most current arrangements) while they also depend on model-generated tools for productivity. Exit options are mobile but friction-laden (opt-out from platforms, demand compensation, migrate to proprietary models). They experience both coordination benefit (access to better tools) and extraction (labor value captured by training providers without consent or attribution). Active enforcement (terms of service, copyright claims, DMCA takedowns) sustains the asymmetry. Mixed-experienced extraction with some agency.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, tangled_rope,
    context(agent_power(powerful),
            time_horizon(biographical),
            exit_options(mobile),
            spatial_scope(national))).

% PERSPECTIVE 5: ACADEMIC RESEARCH COMMUNITY (PITON) — Academic publishing and peer review processes are largely preserved in form but degraded in function by model-generated synthetic text. Journals still require peer review; conferences still curate; citations still accumulate — but the signal-to-noise ratio of the underlying literature is declining. The research community maintains the performative rituals (peer review, citation tracking) while the substrate they evaluate becomes progressively synthetic. Theater ratio high because verification processes persist despite reduced epistemic content. This is institutional inertia, not high extraction — the community sees its own credibility mechanisms as increasingly theatrical.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, piton,
    context(agent_power(institutional),
            time_horizon(civilizational),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 6: ANALYTICAL OBSERVER / INFORMATION-THEORETIC VIEW (MOUNTAIN) — From a civilizational perspective, the feedback loop reflects an immutable constraint: information-theoretic limits on what can be learned from data that was itself generated from previous models. Each iteration degrades the mutual information available for training the next model. From this view, the collapse is not a policy choice but a natural law of statistical learning: you cannot extract more information from a system than you inject. However, the structural data contradicts the mountain classification — the engine should flag this as false summit. The constraint is not a law of information theory; it is a contingent institutional arrangement where synthetic data is prioritized over licensing diverse information sources due to capital constraints and market structure.
constraint_indexing:constraint_classification(synthetic_data_feedback_loop, mountain,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(universal))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(synthetic_data_feedback_loop_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(synthetic_data_feedback_loop, TypeOther, context(agent_power(institutional), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(synthetic_data_feedback_loop, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

test(piton_threshold) :-
    domain_priors:theater_ratio(synthetic_data_feedback_loop, TR),
    TR >= 0.70.

:- end_tests(synthetic_data_feedback_loop_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.58): High but not maximum. The constraint extracts information diversity and future model capacity from the system, liquidating the original human-generated internet as training material. The extractiveness is high because once synthetic data becomes the dominant training source, the extraction is largely irreversible — you cannot recover the information diversity that was used up. However, extractiveness is not at maximum (0.70+) because: (1) alternative sources exist (licensing, human curation, new content) but are capital-intensive rather than structurally impossible; (2) the extraction window has a timeline (10-20 years before model collapse becomes obvious); (3) users retain some agency through retraining or architectural innovation. Suppression (0.62): High. Barriers to using diverse human-generated data include: capital costs of licensing, fragmentation across platforms and jurisdictions, copyright complexity, platform terms-of-service that consolidate data, and the competitive pressure to use cheap synthetic data rather than expensive licensed alternatives. Suppression is not total because: (1) some licensing markets exist; (2) some communities produce openly available data; (3) regulatory pressure (EU AI Act, future copyright enforcement) may raise licensing costs and make it more economically viable. Theater ratio (0.48): Moderate. Model training and synthetic data generation involve real computational work and genuine research innovation — the theater content is lower than in purely performative constraints. However, the substitution of synthetic for real data introduces theater: benchmark performance metrics rise (due to synthetic data being optimized for benchmarks) while actual model robustness may decline. The measured theater increase over time (0.15 → 0.48) reflects this: as synthetic data dominates, there is growing divergence between published benchmark performance and real-world model reliability.
 *
 * PERSPECTIVAL GAP:
 *   This constraint demonstrates how the same underlying loop (model outputs recycled as training data) maps to radically different experienced classifications. The commercial training provider sees a coordination solution (Rope) — a mechanism for continuous scaling without licensing friction. The information diversity sees extraction (Snare) — its unique content is progressively consumed with no recourse. The end user sees quality collapse (Snare) — performance ceilings lowered by constrained data. The content creator sees mixed extraction and benefit (Tangled Rope) — their work is used without compensation but they also benefit from model-generated tools. The research community sees degraded verification (Piton) — peer review persists but the literature it evaluates becomes increasingly synthetic. The analytical observer sees an immutable limit (Mountain) — but the structural data reveals this as false naturalization of a capital-constraint choice. The perspectival gap widens over time as the feedback loop tightens: initial (t=0) perspectives all see coordination or temporary dysfunction; final (t=6) perspectives converge on snare/extraction because the irreversibility becomes apparent.
 *
 * DIRECTIONALITY LOGIC:
 *   Each perspective's directionality value derives from the agent's structural position relative to the information flow. Training providers (d ≈ 0.15, beneficiary + arbitrage) experience negative or low effective extraction — the loop benefits them. Information diversity (d ≈ 0.95, victim + trapped) experiences maximum extraction — it has no exit and no ability to protect itself. End users (d ≈ 0.65, victim + constrained) experience high extraction — they are trapped in the model ecosystem but retain some exit options (alternative providers, waiting for innovation). Content creators (d ≈ 0.50, mixed + mobile) experience moderate extraction — they are both victimized (labor extracted) and benefited (access to tools) and have exit options (licensing negotiation, platform migration, copyright enforcement). The research community (institutional perspective) derives d ≈ 0.25 because it benefits from model-generated assistance while also experiencing extraction through degraded verification substrate — the net effect depends on the specific institutional position. Directionality overrides are not required; the canonical derivation captures the structural dynamics accurately.
 *
 * MANDATROPHY ANALYSIS:
 *   RESOLVED: The mandatrophy question is 'Is this pure extraction or legitimate coordination?' The constraint resolves as pure extraction (Snare) rather than coordination (Rope) because: (1) the victims (information diversity, future capacity, end users) outnumber and outweigh the beneficiaries (training providers); (2) the beneficiaries could achieve similar coordination outcomes at lower cost through licensing diverse data, but choose synthetic data for capital reasons, not structural necessity; (3) the constraint's existence depends on suppressing alternatives (making licensing expensive, making opt-out difficult), not on voluntary participation in a mutually beneficial arrangement. The rope-perspective (training provider's experience) is real but narrow and short-term. The snare classification stands because: (1) the institutional perspective shows the trap is self-reinforcing and hard to exit once locked in; (2) the informational diversity perspective shows irreversible loss; (3) the timescale analysis shows that while the constraint benefits some agents immediately (1-3 years), it extracts from all agents over longer timescales (10-20 years) as model collapse becomes observable. The false summit risk (analytical/mountain) is explicitly identified as a naturalization fallacy: treating a choice to prioritize capital efficiency over information diversity as if it were a law of nature. The training data availability is not a fixed scarcity; it is a choice to substitute cheap synthetic data for expensive diverse data due to market structure and capital constraints.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    synthetic_data_threshold,
    'At what proportion of training data does synthetic-data contamination produce measurable model collapse in downstream tasks?',
    'Empirical evaluation: benchmark standard tasks (MMLU, natural language understanding, coding) across model lineages with controlled synthetic data injection ratios; identify the collapse threshold',
    'If threshold < 30%: feedback loop triggers quickly, constraining scaling timelines for all providers. If threshold > 70%: immediate urgency is lower, extraction window extends longer, delaying corrective investment.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(synthetic_data_threshold, empirical, 'Synthetic data contamination threshold for measurable model collapse').

omega_variable(
    proprietary_data_licensing_scalability,
    'Can proprietary human-generated data sources (licensed journalism, academic databases, creative works, research preprints) be licensed at scale to replace synthetic training material without prohibitive capital costs?',
    'Market analysis: survey licensing costs for major data providers; calculate total-cost-of-ownership for training runs using licensed vs synthetic data; identify whether licensing becomes economically viable at scale',
    'If licensing scales profitably: exit option emerges for training providers, converting snare to tangled_rope or rope. If licensing remains capital-prohibitive: snare classification hardens, feedback loop becomes quasi-inevitable.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(proprietary_data_licensing_scalability, empirical, 'Whether proprietary data licensing can replace synthetic training material at scale').

omega_variable(
    architectural_mitigation_possibility,
    'Can architectural innovations (e.g., retrieval-augmented generation, continuous online learning from human feedback) substantially reduce dependence on pretraining from synthetic data and restore information diversity as a training signal?',
    'Research trajectory analysis: track progress on RAG systems, RLHF scaling, and online learning architectures; measure whether these approaches demonstrably reduce model collapse risk compared to scaling pretraining dataset size',
    'If viable: alternative escape route exists, converting snare to temporary scaffold with sunset clause. If not viable: architectural path-dependence locks systems into feedback loop.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(architectural_mitigation_possibility, empirical, 'Whether architectural innovations can mitigate synthetic-data feedback dependence').

omega_variable(
    institutional_coordination_on_data_preservation,
    'Will major training providers voluntarily coordinate to preserve diverse information sources (e.g., via agreements to exclude synthetic text from training, to license human content, to fund independent data curation) rather than competing to scale on cheap synthetic data?',
    'Institutional analysis: track whether coalition agreements, industry standards, or regulatory frameworks emerge that mandate diverse data sources; measure compliance and defection rates',
    'If coordination emerges: constraint converts from snare to tangled_rope with enforcement; victims gain some protection. If coordination fails (prisoner''s dilemma): snare classification hardens; competitive pressure enforces the feedback loop.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(institutional_coordination_on_data_preservation, conceptual, 'Whether institutional coordination can prevent competitive race to synthetic training').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(synthetic_data_feedback_loop, 0, 6).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(synth_tr_t0, synthetic_data_feedback_loop, theater_ratio, 0, 0.15).
narrative_ontology:measurement(synth_tr_t3, synthetic_data_feedback_loop, theater_ratio, 3, 0.32).
narrative_ontology:measurement(synth_tr_t6, synthetic_data_feedback_loop, theater_ratio, 6, 0.48).

% Extraction over time
narrative_ontology:measurement(synth_be_t0, synthetic_data_feedback_loop, base_extractiveness, 0, 0.22).
narrative_ontology:measurement(synth_be_t3, synthetic_data_feedback_loop, base_extractiveness, 3, 0.4).
narrative_ontology:measurement(synth_be_t6, synthetic_data_feedback_loop, base_extractiveness, 6, 0.58).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(synthetic_data_feedback_loop, information_standard).
narrative_ontology:affects_constraint(synthetic_data_feedback_loop, model_collapse_loss_of_capability).
narrative_ontology:affects_constraint(synthetic_data_feedback_loop, llm_training_data_licensing).
narrative_ontology:affects_constraint(synthetic_data_feedback_loop, platform_content_extraction).

% DUAL FORMULATION NOTE:
% The synthetic data feedback loop decomposes into three related constraints with different ε values: (1) model_collapse_loss_of_capability (ε ≈ 0.72, immediate empirical consequence) represents the direct loss of model capacity; (2) llm_training_data_licensing (ε ≈ 0.38, coordination problem) represents the market coordination failure that makes licensing prohibitively expensive; (3) platform_content_extraction (ε ≈ 0.45, tangled rope) represents the extraction of creator labor without consent. This constraint story focuses on the feedback loop mechanism itself (ε ≈ 0.58) and links as upstream cause to the others.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
