% ============================================================================
% CONSTRAINT STORY: tychonoff_theorem
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-02-26
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_tychonoff_theorem, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    domain_priors:emerges_naturally/1,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: tychonoff_theorem
 *   human_readable: Tychonoff Theorem: Compactness of Arbitrary Products
 *   domain: mathematics/topology
 *
 * SUMMARY:
 *   The Tychonoff theorem states that an arbitrary product of compact
 *   topological spaces is compact in the product topology. This is a
 *   fundamental result in general topology with profound implications for
 *   functional analysis and measure theory. The theorem classifies as a
 *   mountain — a constraint that emerges naturally from the structure of
 *   mathematics itself, not from human institutional design. No agent can
 *   evade it; no alternative formulation circumvents it; no observational
 *   context changes its truth value. The constraint exhibits zero degrees of
 *   freedom across all indices and perspectives. The theorem's necessity
 *   derives from the interaction of three structural elements: (1) the
 *   definition of compactness as having every open cover admit a finite
 *   subcover, (2) the definition of the product topology as generated by
 *   products of open sets in each factor, and (3) the axiom of choice, which
 *   is either assumed or interchangeably deployed in the standard proof. Any
 *   agent attempting to work with infinite products of compact spaces must
 *   accept this compactness preservation or explicitly reject one of these
 *   foundational elements. The theater ratio is minimal (0.05) because the
 *   theorem requires no performative element — the proof is either valid or
 *   invalid; there is no ritual maintenance or alternative interpretation
 *   that would constitute theater. Extractiveness is low (0.12) because the
 *   constraint does not extract from any agent; it is a feature of the
 *   mathematical structure itself, not a mechanism by which one agent
 *   benefits at another's expense.
 *
 * KEY AGENTS:
 *   - Proof-seeker (powerless/trapped): Any mathematician or student attempting to prove product compactness without invoking the axiom of choice will fail inevitably. The structural constraint admits no exit.
 *   - Mathematics educator (institutional/arbitrage): Must teach the theorem and its proof as part of standard topology curriculum. Can choose pedagogical emphasis but cannot avoid the constraint's necessity.
 *   - Analytical observer (analytical/analytical): Observes the theorem as a logical consequence of set-theoretic foundations. Recognizes no perspectival gap — the mountain classification is invariant.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(tychonoff_theorem, 0.12).
domain_priors:suppression_score(tychonoff_theorem, 0.02).
domain_priors:theater_ratio(tychonoff_theorem, 0.05).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(tychonoff_theorem, extractiveness, 0.12).
narrative_ontology:constraint_metric(tychonoff_theorem, suppression_requirement, 0.02).
narrative_ontology:constraint_metric(tychonoff_theorem, theater_ratio, 0.05).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(tychonoff_theorem, accessibility_collapse, 0.92).
narrative_ontology:constraint_metric(tychonoff_theorem, resistance, 0.08).

% --- Constraint claim ---
narrative_ontology:constraint_claim(tychonoff_theorem, mountain).
narrative_ontology:human_readable(tychonoff_theorem, "Tychonoff Theorem: Compactness of Arbitrary Products").
narrative_ontology:topic_domain(tychonoff_theorem, "mathematics/topology").

domain_priors:emerges_naturally(tychonoff_theorem).

% --- Structural relationships ---
% No enrichment needed. As a Mountain (physical limit), this constraint does
% not have beneficiaries or victims in the structural sense.

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% Any agent attempting to construct a proof that arbitrary products of compact spaces are compact without invoking the axiom of choice (or equivalent principle) will fail. The structural constraint is invariant — no escape exists.
constraint_indexing:constraint_classification(tychonoff_theorem, mountain,
    context(agent_power(powerless),
            time_horizon(civilizational),
            exit_options(trapped),
            spatial_scope(universal))).

% No institutional actor can circumvent the theorem's necessity. Any topology course covering product spaces must eventually confront compactness preservation or explicitly reject the axiom of choice. The institutional constraint is immutable.
constraint_indexing:constraint_classification(tychonoff_theorem, mountain,
    context(agent_power(institutional),
            time_horizon(civilizational),
            exit_options(arbitrage),
            spatial_scope(universal))).

% From the analytical perspective, the Tychonoff theorem is a logical necessity deriving from the interaction between infinite products, compactness, and the axiom of choice. The constraint emerges naturally from the structure of set theory itself. No observational ambiguity or perspectival gap disrupts this classification.
constraint_indexing:constraint_classification(tychonoff_theorem, mountain,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(universal))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(tychonoff_theorem_tests).

test(invariance_check) :-
    % Verify that as a Mountain, the classification is uniform across perspectives.
    constraint_indexing:constraint_classification(tychonoff_theorem, TypeTarget, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(tychonoff_theorem, TypeBeneficiary, context(agent_power(institutional), _, _, _)),
    TypeTarget == TypeBeneficiary,
    TypeTarget == mountain.

test(mountain_threshold_validation) :-
    config:param(extractiveness_metric_name, ExtMetricName),
    narrative_ontology:constraint_metric(tychonoff_theorem, ExtMetricName, E),
    domain_priors:suppression_score(tychonoff_theorem, S),
    E =< 0.25,
    S =< 0.05.

test(nl_profile_validation) :-
    domain_priors:emerges_naturally(tychonoff_theorem),
    narrative_ontology:constraint_metric(tychonoff_theorem, accessibility_collapse, AC),
    narrative_ontology:constraint_metric(tychonoff_theorem, resistance, R),
    AC >= 0.85,
    R =< 0.15.

:- end_tests(tychonoff_theorem_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.12): Minimal. The theorem does not extract value from any agent in the sense of asymmetric benefit. It is a constraint on what is mathematically possible, not a mechanism by which one agent captures value at another's expense. The low nonzero value reflects that understanding and applying the theorem requires intellectual effort from the proof-seeker — effort that produces no extraction but is nonetheless required. Suppression (0.02): Minimal. The theorem suppresses no viable alternative approaches at scale; it simply marks the boundary of what is provable within standard set theory. The minimal value reflects that proof-seekers have perfect information about the constraint (the theorem is fully stated and proven) and face no hidden barriers. Theater ratio (0.05): Minimal. Mathematical proofs are either valid or invalid; they do not perform a social function independent of their logical content. The minimal nonzero value reflects only that any human communication requires some performative element (language, pedagogy, presentation) distinct from pure logical form.
 *
 * PERSPECTIVAL GAP:
 *   There is no perspectival gap for the Tychonoff theorem. All three perspectives — the proof-seeker, the educator, and the analytical observer — agree on the classification and the constraint's necessity. This is the defining characteristic of a mountain: the constraint is observer-independent. The powerless agent cannot negotiate with the constraint; the institutional agent cannot exploit it for institutional advantage; the analytical observer cannot reframe it. All three perspectives perceive the same immutable structure. This uniformity across perspectives is itself a diagnostic signal that the classification is correct.
 *
 * DIRECTIONALITY LOGIC:
 *   Directionality derivation does not apply to mountain constraints. The theorem does not beneficiary or victim groups; it is not an extractive mechanism. The constraint is a structural feature of mathematical topology, not a relationship between agents with different power levels or exit options. All agents face the same constraint with equal force.
 *
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    axiom_of_choice_equivalence,
    'Is the Tychonoff theorem fundamentally dependent on the axiom of choice, or is it a logical consequence of weaker set-theoretic assumptions?',
    'Formal proof exploration in constructive set theories (IZF, CZF) and investigations into whether restricted versions (finite products, countable products) require choice',
    'If Tychonoff is provable without choice: the constraint is a feature of infinite product topology, not of AC-induced extraction. Classification remains mountain but the mechanism shifts. If Tychonoff requires full AC: the constraint is a junction point where set-theoretic foundations enforce a structural limit.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(axiom_of_choice_equivalence, conceptual, 'Dependence of Tychonoff on axiom of choice').

omega_variable(
    compactness_definition_invariance,
    'Does the Tychonoff theorem hold under all mathematically reasonable definitions of compactness, or does it depend on the specific open-cover formulation?',
    'Investigation of compactness under alternative definitions: sequential compactness, relative compactness, countable compactness; examination of which definitions preserve product compactness',
    'If product compactness holds across all definitions: the constraint is a deep topological invariant. If it holds only for specific definitions: the constraint is a feature of the chosen formalism, not of geometry itself.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(compactness_definition_invariance, conceptual, 'Invariance of Tychonoff across compactness definitions').

omega_variable(
    product_space_naturality,
    'Is the infinite product topology the only or most natural way to define topology on products of arbitrary families?',
    'Examination of alternative product topologies (box topology, other categorical structures) and their compactness preservation properties; analysis of which topology is forced by category-theoretic universality',
    'If infinite product topology is forced by naturality: the constraint emerges from essential mathematics. If alternatives are equally valid: Tychonoff is a feature of a chosen formalism, not a natural law.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(product_space_naturality, conceptual, 'Naturality of infinite product topology definition').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(tychonoff_theorem, 0, 100).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(tych_tr_t0, tychonoff_theorem, theater_ratio, 0, 0.05).
narrative_ontology:measurement(tych_tr_t50, tychonoff_theorem, theater_ratio, 50, 0.05).
narrative_ontology:measurement(tych_tr_t100, tychonoff_theorem, theater_ratio, 100, 0.05).

% Extraction over time
narrative_ontology:measurement(tych_be_t0, tychonoff_theorem, base_extractiveness, 0, 0.12).
narrative_ontology:measurement(tych_be_t50, tychonoff_theorem, base_extractiveness, 50, 0.12).
narrative_ontology:measurement(tych_be_t100, tychonoff_theorem, base_extractiveness, 100, 0.12).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(tychonoff_theorem, information_standard).
narrative_ontology:affects_constraint(tychonoff_theorem, compactness_sequential_preservation).
narrative_ontology:affects_constraint(tychonoff_theorem, stone_cech_compactification).

% DUAL FORMULATION NOTE:
% The Tychonoff theorem is a downstream consequence of the axiom of choice combined with topological definitions. It affects constraints on sequential compactness preservation and the Stone-Čech compactification, which are distinct topological mechanisms that depend on Tychonoff's structure.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
