% ============================================================================
% CONSTRAINT STORY: winners_curse
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-02-26
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_winners_curse, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: winners_curse
 *   human_readable: The Winner's Curse in Common Value Auctions
 *   domain: economic/social
 *
 * SUMMARY:
 *   The winner's curse in common value auctions is a structural tension
 *   between the coordination function of auctions (allocating assets to
 *   interested parties) and the extraction mechanism embedded in the
 *   information asymmetry. When the true value of an asset is unknown to
 *   bidders but identical across all participants (common value), the winning
 *   bidder is statistically the agent whose valuation estimate was highest.
 *   Since all estimates are noisy, the highest estimate is biased upward —
 *   the winner has overestimated and overpaid. This phenomenon was
 *   empirically documented in offshore oil lease auctions and has since
 *   become a canonical case in experimental economics. Yet despite widespread
 *   academic knowledge, the curse persists in practice across auctions for
 *   mineral rights, acquisitions, and IPOs. The constraint exhibits a crucial
 *   characteristic: the curse serves the seller's interest (higher revenues)
 *   while harming the winner (negative expected returns). This alignment
 *   means the curse is simultaneously a coordination mechanism (allocating to
 *   the highest-valuation agent) and an extraction mechanism (capturing
 *   bidder surplus through the information asymmetry).
 *
 * KEY AGENTS:
 *   - Naive Winning Bidders: Primary victims (powerless/trapped) — systematically overpay due to optimism bias and failure to adjust for the curse; cannot exit once they have won
 *   - Sophisticated Bidders: Secondary actors (moderate/constrained) — understand the curse and adjust estimates downward, but remain subject to winner's curse through alternative mechanisms
 *   - Auction Sellers: Primary beneficiaries (institutional/arbitrage) — capture surplus generated by bidder overpayment; can select auction format to maximize the curse effect
 *   - Regulatory Auction Designers: Secondary actors (organized/mobile) — can mitigate the curse through mechanism design (ascending auctions, information disclosure, entry filters)
 *   - Academic Discourse: Institutional observer (institutional/arbitrage) — produces and disseminates knowledge about the curse that is cited but not consistently applied
 *   - Analytical Observer: Civilizational perspective (analytical/analytical) — sees the curse as an emergent property of information asymmetry and bidding protocols
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(winners_curse, 0.52).
domain_priors:suppression_score(winners_curse, 0.65).
domain_priors:theater_ratio(winners_curse, 0.58).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(winners_curse, extractiveness, 0.52).
narrative_ontology:constraint_metric(winners_curse, suppression_requirement, 0.65).
narrative_ontology:constraint_metric(winners_curse, theater_ratio, 0.58).

% --- Constraint claim ---
narrative_ontology:constraint_claim(winners_curse, tangled_rope).
narrative_ontology:human_readable(winners_curse, "The Winner's Curse in Common Value Auctions").
narrative_ontology:topic_domain(winners_curse, "economic/social").

domain_priors:requires_active_enforcement(winners_curse).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(winners_curse, auction_sellers).
narrative_ontology:constraint_beneficiary(winners_curse, information_advantaged_bidders).
narrative_ontology:constraint_victim(winners_curse, winning_bidders).
narrative_ontology:constraint_victim(winners_curse, naive_bidders).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: NAIVE WINNING BIDDER (SNARE) — Unaware of the curse's mechanics, bidder cannot exit the auction process or adjust their estimation once commitment is made. Bears full extraction through systematic overpayment. Maximum experienced extraction — bidder is trapped by their own lack of understanding and by the irreversibility of the winning bid.
constraint_indexing:constraint_classification(winners_curse, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(global))).

% PERSPECTIVE 2: SOPHISTICATED BIDDER (TANGLED ROPE) — Understands the curse and can adjust bidding strategy downward (coordination benefit: rational pricing), but faces extraction from the auction structure itself. Can exit if valuation doesn't meet threshold, but bidding protocol constrains strategy. Mixed: benefits from understanding, but still exposed to winner's curse if other bidders also adjust and the curse persists through different mechanisms.
constraint_indexing:constraint_classification(winners_curse, tangled_rope,
    context(agent_power(moderate),
            time_horizon(biographical),
            exit_options(constrained),
            spatial_scope(national))).

% PERSPECTIVE 3: AUCTION SELLER (ROPE) — Experiences the winner's curse as pure coordination: the curse ensures buyers systematically overpay relative to true value, and the seller captures the surplus. Seller can arbitrage between sealed-bid and open-outcry formats or between common-value and private-value auctions. Net beneficiary — the mechanism generates revenue through the curse itself.
constraint_indexing:constraint_classification(winners_curse, rope,
    context(agent_power(institutional),
            time_horizon(immediate),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 4: REGULATORY AUCTION DESIGNER (SCAFFOLD) — Can restructure auction mechanisms to mitigate the curse: ascending auctions reveal valuations progressively; sealed-bid variants with asymmetric information disclosure; entry fees that filter naive bidders. Sunset mechanism: as market participants learn curse dynamics, the extraction mechanism weakens. Organized actors can design around it or enforce transparency requirements.
constraint_indexing:constraint_classification(winners_curse, scaffold,
    context(agent_power(organized),
            time_horizon(generational),
            exit_options(mobile),
            spatial_scope(global))).

% PERSPECTIVE 5: ACADEMIC DISCOURSE (PITON) — The winner's curse was identified empirically in the 1950s-1970s (offshore drilling lease auctions, etc.) and has been extensively studied. Yet the curse persists in real-world auctions despite decades of academic work and its regular rediscovery by practitioners. The knowledge about the curse is performative: it's cited, taught, and intellectually acknowledged but does not consistently change bidding behavior. Theater ratio is high because the theory is well-established but behavioral adoption is weak. Piton classification: the constraint persists through institutional inertia and bounded rationality despite clear understanding of the mechanism.
constraint_indexing:constraint_classification(winners_curse, piton,
    context(agent_power(institutional),
            time_horizon(civilizational),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 6: ANALYTICAL OBSERVER (TANGLED ROPE) — From a civilizational perspective, the winner's curse is a structural feature of common-value auctions with incomplete information. It combines coordination (the auction mechanism itself solves the allocation problem) with extraction (the mechanism induces overpayment). The curse is neither purely natural law nor purely institutional design — it emerges from information asymmetry meeting bidding protocols. The constraint persists because it simultaneously serves the seller's interest (capturing surplus) and the mechanism's function (allocating the asset).
constraint_indexing:constraint_classification(winners_curse, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(universal))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(winners_curse_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(winners_curse, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(winners_curse, TypeOther, context(agent_power(moderate), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(winners_curse, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

test(piton_threshold) :-
    domain_priors:theater_ratio(winners_curse, TR),
    TR >= 0.70.

:- end_tests(winners_curse_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.52): Moderate-high. The curse induces systematic overpayment by winners, representing a transfer from naive bidders to the seller. The extractiveness is not as severe as pure extraction (Snare) because the auction mechanism also serves a genuine allocation function — the asset goes to the bidder willing to pay the most. The extraction is parasitic on the coordination, not replacing it. The value reflects that the curse is a design feature of many auctions, not a purely coercive mechanism. Suppression (0.65): Moderate-high. Barriers to avoiding the curse include: (1) bounded rationality — not all bidders grasp the statistical reasoning, (2) commitment irreversibility — winning bids are legally binding, (3) information barriers — bidders cannot perfectly estimate asset values even with sophisticated modeling, (4) competitive pressure — bidders must bid aggressively to win, creating incentive to ignore the curse. However, suppression is not total because sophisticated bidders can and do adjust strategy. Theater ratio (0.58): Moderate. The academic understanding of the curse is well-established and widely taught, but its behavioral implementation remains inconsistent. The theater reflects the gap between theoretical knowledge (highly formalized) and practical behavior (curse persists). As bidders gain experience and academic knowledge spreads, theater has increased — the performative acknowledgment of the curse (without changing behavior) has become more explicit.
 *
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    curse_magnitude_variability,
    'Does the winner''s curse magnitude vary systematically by auction format, or is it an invariant property of common-value auctions?',
    'Cross-format empirical comparison: sealed-bid vs ascending auctions, first-price vs second-price, with controls for information symmetry and bidder sophistication',
    'If format-invariant: curse is a structural property of common-value inference. If format-dependent: curse is a contingent institutional feature that can be engineered away, shifting classification toward Scaffold from all perspectives.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(curse_magnitude_variability, empirical, 'Whether curse magnitude is invariant across auction formats').

omega_variable(
    learning_dynamics_convergence,
    'Do bidders learn to account for the curse through repeated auction participation, or does bidding behavior remain stable despite experience?',
    'Longitudinal tracking of individual bidders across multiple auctions; analysis of whether price trajectories converge toward theoretical predictions or remain persistently above them',
    'If learning occurs: piton classification is correct (theater fades as practice improves). If learning doesn''t occur: extraction persists despite knowledge, suggesting behavioral constraint deeper than information asymmetry.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(learning_dynamics_convergence, empirical, 'Whether bidders learn to account for the curse').

omega_variable(
    information_asymmetry_necessity,
    'Is the winner''s curse a necessary consequence of asymmetric information, or can it be eliminated through disclosure mechanisms while preserving the auction''s allocation function?',
    'Experimental comparison: auctions with progressive information revelation vs sealed-bid; measurement of price convergence to true value and allocation efficiency',
    'If elimination possible: curse is an extraction feature of information design (Tangled Rope confirmed). If curse persists despite symmetry: curse reflects deeper statistical property, shifting toward Mountain.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(information_asymmetry_necessity, empirical, 'Whether asymmetric information is necessary for the curse').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(winners_curse, 0, 50).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(wc_tr_t0, winners_curse, theater_ratio, 0, 0.42).
narrative_ontology:measurement(wc_tr_t25, winners_curse, theater_ratio, 25, 0.52).
narrative_ontology:measurement(wc_tr_t50, winners_curse, theater_ratio, 50, 0.58).

% Extraction over time
narrative_ontology:measurement(wc_be_t0, winners_curse, base_extractiveness, 0, 0.35).
narrative_ontology:measurement(wc_be_t25, winners_curse, base_extractiveness, 25, 0.48).
narrative_ontology:measurement(wc_be_t50, winners_curse, base_extractiveness, 50, 0.52).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(winners_curse, resource_allocation).
narrative_ontology:affects_constraint(winners_curse, information_asymmetry_exploitation).
narrative_ontology:affects_constraint(winners_curse, acquisition_overpayment_trap).

% DUAL FORMULATION NOTE:
% The winner's curse decomposes into two related constraints: (1) the statistical curse inherent to common-value auctions (information-asymmetric inference problem, ε ≈ 0.35, lower extraction), and (2) the behavioral curse in practice (boundedly rational bidders fail to adjust despite knowledge, ε ≈ 0.52, higher extraction). The first is closer to a natural law of information; the second is a contingent institutional failure. Both stories are included in the network to reflect the decomposition.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(winners_curse, institutional, 0.1).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
