% ============================================================================
% CONSTRAINT STORY: reformation_composite__theological_fragmentation_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-07-30
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_reformation_composite__theological_fragmentation_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: reformation_composite__theological_fragmentation_reading
 *   human_readable: Reformation: Theological Fragmentation (Reading)
 *   domain: historical_epistemology/religious_history/political_economy
 *
 * SUMMARY:
 *   This constraint models the Reformation as primarily a theological event,
 *   where competing doctrines of salvation (soteriology) and church structure
 *   (ecclesiology) led to the formation of distinct, often mutually
 *   exclusive, Christian denominations. The constraint is the ongoing
 *   structural incompatibility generated by these theological differences,
 *   which in turn sustains distinct institutional forms and leadership. This
 *   reading emphasizes doctrinal pluralism as the primary observable and
 *   confessional documents as key artifacts.
 *
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(reformation_composite__theological_fragmentation_reading, 0.65).
domain_priors:suppression_score(reformation_composite__theological_fragmentation_reading, 0.7).
domain_priors:theater_ratio(reformation_composite__theological_fragmentation_reading, 0.2).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(reformation_composite__theological_fragmentation_reading, extractiveness, 0.65).
narrative_ontology:constraint_metric(reformation_composite__theological_fragmentation_reading, suppression_requirement, 0.7).
narrative_ontology:constraint_metric(reformation_composite__theological_fragmentation_reading, theater_ratio, 0.2).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(reformation_composite__theological_fragmentation_reading, accessibility_collapse, 0.4).
narrative_ontology:constraint_metric(reformation_composite__theological_fragmentation_reading, resistance, 0.75).

% --- Constraint claim ---
narrative_ontology:constraint_claim(reformation_composite__theological_fragmentation_reading, tangled_rope).
narrative_ontology:human_readable(reformation_composite__theological_fragmentation_reading, "Reformation: Theological Fragmentation (Reading)").
narrative_ontology:topic_domain(reformation_composite__theological_fragmentation_reading, "historical_epistemology/religious_history/political_economy").

domain_priors:requires_active_enforcement(reformation_composite__theological_fragmentation_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(reformation_composite__theological_fragmentation_reading, 'c1564077-fe21-41d5-b33c-ae8f4b6ea110').
narrative_ontology:cs_kernel_codification('c1564077-fe21-41d5-b33c-ae8f4b6ea110', formalized).
narrative_ontology:cs_authority_grounding('c1564077-fe21-41d5-b33c-ae8f4b6ea110', lineage).
narrative_ontology:cs_interpretation_layer_present('c1564077-fe21-41d5-b33c-ae8f4b6ea110').
narrative_ontology:cs_reading_relation('c1564077-fe21-41d5-b33c-ae8f4b6ea110', reformation_composite__political_realignment_reading, coexists_with).
narrative_ontology:cs_reading_relation('c1564077-fe21-41d5-b33c-ae8f4b6ea110', reformation_composite__technological_mediation_reading, coexists_with).
narrative_ontology:cs_axiom('c1564077-fe21-41d5-b33c-ae8f4b6ea110', foundational, sola_fide_sola_scriptura).
narrative_ontology:cs_axiom_status(sola_fide_sola_scriptura, holdable).
narrative_ontology:cs_axiom_grounding('c1564077-fe21-41d5-b33c-ae8f4b6ea110', sola_fide_sola_scriptura, theological).
narrative_ontology:cs_axiom('c1564077-fe21-41d5-b33c-ae8f4b6ea110', foundational, priesthood_of_all_believers).
narrative_ontology:cs_axiom_status(priesthood_of_all_believers, holdable).
narrative_ontology:cs_axiom_grounding('c1564077-fe21-41d5-b33c-ae8f4b6ea110', priesthood_of_all_believers, theological).
narrative_ontology:cs_reference_frame('c1564077-fe21-41d5-b33c-ae8f4b6ea110', early_protestant_confessionalism).
narrative_ontology:cs_drift_state('c1564077-fe21-41d5-b33c-ae8f4b6ea110', contemporary_ecumenical_dialogue, gap(revival_pressure, minor, true)).
narrative_ontology:cs_created_at('c1564077-fe21-41d5-b33c-ae8f4b6ea110', '').
narrative_ontology:cs_kernel_id(reformation_composite__theological_fragmentation_reading, reformation_composite).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(reformation_composite__theological_fragmentation_reading, denominational_leadership).
narrative_ontology:constraint_beneficiary(reformation_composite__theological_fragmentation_reading, confessional_theologians).
narrative_ontology:constraint_victim(reformation_composite__theological_fragmentation_reading, religious_minorities).
narrative_ontology:constraint_victim(reformation_composite__theological_fragmentation_reading, ecumenical_movements).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Establishes and enforces doctrinal boundaries, benefiting from the distinct identity and institutional structures of their specific confession. Their authority is grounded in the theological claims that differentiate their denomination.
narrative_ontology:constraint_stakeholder(reformation_composite__theological_fragmentation_reading, denominational_leadership, agenda_setter,
    institutional, generational, identity_locked, regional).

% Their careers and intellectual projects are often built around articulating, defending, and elaborating specific denominational doctrines. They benefit from the ongoing need for theological justification of distinct confessional identities.
narrative_ontology:constraint_stakeholder(reformation_composite__theological_fragmentation_reading, confessional_theologians, beneficiary,
    organized, biographical, constrained, national).

% Bear the costs of theological fragmentation through persecution, social exclusion, or forced conversion in regions dominated by a different confession. Their existence challenges the theological uniformity enforced by dominant groups.
narrative_ontology:constraint_stakeholder(reformation_composite__theological_fragmentation_reading, religious_minorities, payer,
    powerless, immediate, trapped, local).

% Seek to bridge theological divides and foster unity among Christian denominations. They face significant resistance from entrenched denominational structures and the theological commitments that define them, making their work costly and often frustrating.
narrative_ontology:constraint_stakeholder(reformation_composite__theological_fragmentation_reading, ecumenical_movements, payer,
    moderate, generational, constrained, global).

% Observe and sometimes intervene in religious conflicts, often seeking to maintain civil order or assert state control over religious institutions. Their perspective is often pragmatic, viewing theological differences as a source of political instability.
narrative_ontology:constraint_stakeholder(reformation_composite__theological_fragmentation_reading, secular_authorities, observer,
    institutional, generational, analytical, national).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Provides a clear, internally consistent theological framework and community identity for adherents, coordinating belief and practice within specific denominational boundaries.
% TRANSFER_FUNCTION: Transfers loyalty, resources, and intellectual effort from a unified Christian identity to specific denominational structures and their theological justifications, from adherents to denominational leadership and theologians.
% ABSENT_VOICES: Those who sought a unified, non-confessional Christian identity, or those whose theological views were suppressed by dominant factions, are absent. Their voices would challenge the necessity and legitimacy of the fragmentation.
% DISAPPEARANCE_RATIONALE: If the theological commitments driving fragmentation vanished, the institutional structures of denominations would lose their primary justification, leading to a significant realignment of religious and political power, and potentially a re-emergence of unified religious movements.
% FOUNDING_PROBLEM: The perceived corruption and theological errors of the late medieval Catholic Church, particularly regarding salvation and ecclesiastical authority, created a demand for reform and a return to perceived biblical purity.
% FOUNDING_PROBLEM_CORROBORATION: Denominational leaders and theologians continue to assert the founding problems (theological purity, true doctrine) are live, justifying their distinct existence. Ecumenical movements and historical scholars, from outside the benefiting parties, corroborate the historical existence of the problems but contest their ongoing 'live' status as justification for continued fragmentation.
narrative_ontology:disappearance_verdict(reformation_composite__theological_fragmentation_reading, world_rearranges).
narrative_ontology:founding_problem_status(reformation_composite__theological_fragmentation_reading, live).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(reformation_composite__theological_fragmentation_reading, '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-21',
    'no_scope_rebuild_gemini2', 'agent/example_platform_commission.json',
    'gemini-2.5-flash', 'max_tokens=16384,temperature=0.1,thinking_budget=0').
narrative_ontology:story_seed(reformation_composite__theological_fragmentation_reading, 'none', 1).
narrative_ontology:epsilon_provenance(reformation_composite__theological_fragmentation_reading, 0.65, 'gemini-2.5-flash', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(reformation_composite__theological_fragmentation_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(reformation_composite__theological_fragmentation_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(reformation_composite__theological_fragmentation_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.65) is substantial because the theological fragmentation demands adherence to specific doctrines, often at the cost of broader Christian unity or individual conscience, and creates institutional overhead. Suppression (0.70) is high due to the active enforcement of confessional boundaries, often backed by state power, leading to persecution of religious minorities. Theater ratio (0.20) is moderate; while genuine theological debate occurs, some efforts to maintain distinctness become performative, defending institutional turf rather than purely theological truth. The initial rise in extractiveness and suppression reflects the hardening of confessional lines and the ensuing religious wars, with a slight decline after the Peace of Westphalia as a new, albeit fragmented, equilibrium is established.
 *
 * PERSPECTIVAL GAP:
 *   From the perspective of denominational leadership, the theological fragmentation is a necessary defense of truth and purity, a 'rope' coordinating true believers. From the perspective of religious minorities or ecumenical movements, it is a 'snare' or 'tangled rope' that extracts conformity and prevents unity through coercive doctrinal enforcement. The engine's classification will reflect this divergence based on the structural positions.
 *
 * DIRECTIONALITY LOGIC:
 *   Denominational leadership and confessional theologians are beneficiaries (d near 0.0) as their authority and careers are built upon and sustained by these distinct theological commitments. Religious minorities and ecumenical movements are victims/targets (d near 1.0) as they bear the direct costs of fragmentation, either through persecution or the difficulty of achieving unity. Secular authorities are observers, sometimes intervening to manage the political fallout of theological disputes.
 *
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    theological_vs_political_causality,
    'To what extent was theological fragmentation a primary cause of political realignment, versus being a tool or consequence of pre-existing political ambitions?',
    'Comparative historical analysis of regions where theological shifts preceded political shifts versus those where political interests drove religious change, controlling for other factors.',
    'If theological causality is primary, this reading''s emphasis on doctrinal incompatibility is strengthened. If political causality is dominant, the ''political_realignment_reading'' gains explanatory power, suggesting this reading''s extractiveness is partly a cover for political power grabs.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(theological_vs_political_causality, empirical, 'Disentangling the causal primacy of theological vs. political factors in Reformation fragmentation.').

omega_variable(
    print_technology_mediation,
    'How much did the printing press merely amplify existing theological differences versus fundamentally altering the nature and scale of theological debate, making fragmentation inevitable?',
    'Counterfactual historical analysis: what would the Reformation''s theological landscape look like without the printing press? Analysis of pre-print heresies vs. post-print denominationalism.',
    'If the printing press was a fundamental mediator, the ''technological_mediation_reading'' gains strength, suggesting this reading''s ''theological'' fragmentation is inseparable from its technological substrate. If it was merely an amplifier, this reading''s focus on pure theological incompatibility is more robust.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(print_technology_mediation, conceptual, 'Role of printing technology in shaping theological fragmentation.').

omega_variable(
    genuine_theological_incompatibility,
    'Are the core soteriological and ecclesiological differences truly irreconcilable, or are they maintained by institutional inertia and power dynamics within denominations?',
    'Inter-denominational theological dialogues and agreements (e.g., Joint Declaration on the Doctrine of Justification) that demonstrate convergence on previously ''irreconcilable'' points.',
    'If differences are genuinely irreconcilable, the ''tangled_rope'' classification is robust. If they are largely maintained by non-theological factors, the constraint leans more towards ''snare'' or ''piton'', with theological claims serving as cover.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(genuine_theological_incompatibility, preference, 'Whether theological differences are genuinely irreconcilable or institutionally maintained.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(reformation_composite__theological_fragmentation_reading, 1517, 1648).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(refo_tr_t1517, reformation_composite__theological_fragmentation_reading, theater_ratio, 1517, 0.1).
narrative_ontology:measurement(refo_tr_t1530, reformation_composite__theological_fragmentation_reading, theater_ratio, 1530, 0.15).
narrative_ontology:measurement(refo_tr_t1555, reformation_composite__theological_fragmentation_reading, theater_ratio, 1555, 0.2).
narrative_ontology:measurement(refo_tr_t1580, reformation_composite__theological_fragmentation_reading, theater_ratio, 1580, 0.25).
narrative_ontology:measurement(refo_tr_t1610, reformation_composite__theological_fragmentation_reading, theater_ratio, 1610, 0.22).
narrative_ontology:measurement(refo_tr_t1648, reformation_composite__theological_fragmentation_reading, theater_ratio, 1648, 0.2).

% Extraction over time
narrative_ontology:measurement(refo_be_t1517, reformation_composite__theological_fragmentation_reading, base_extractiveness, 1517, 0.4).
narrative_ontology:measurement(refo_be_t1530, reformation_composite__theological_fragmentation_reading, base_extractiveness, 1530, 0.5).
narrative_ontology:measurement(refo_be_t1555, reformation_composite__theological_fragmentation_reading, base_extractiveness, 1555, 0.6).
narrative_ontology:measurement(refo_be_t1580, reformation_composite__theological_fragmentation_reading, base_extractiveness, 1580, 0.65).
narrative_ontology:measurement(refo_be_t1610, reformation_composite__theological_fragmentation_reading, base_extractiveness, 1610, 0.68).
narrative_ontology:measurement(refo_be_t1648, reformation_composite__theological_fragmentation_reading, base_extractiveness, 1648, 0.65).

% Suppression requirement over time
narrative_ontology:measurement(refo_su_t1517, reformation_composite__theological_fragmentation_reading, suppression_requirement, 1517, 0.5).
narrative_ontology:measurement(refo_su_t1530, reformation_composite__theological_fragmentation_reading, suppression_requirement, 1530, 0.6).
narrative_ontology:measurement(refo_su_t1555, reformation_composite__theological_fragmentation_reading, suppression_requirement, 1555, 0.7).
narrative_ontology:measurement(refo_su_t1580, reformation_composite__theological_fragmentation_reading, suppression_requirement, 1580, 0.75).
narrative_ontology:measurement(refo_su_t1610, reformation_composite__theological_fragmentation_reading, suppression_requirement, 1610, 0.72).
narrative_ontology:measurement(refo_su_t1648, reformation_composite__theological_fragmentation_reading, suppression_requirement, 1648, 0.7).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(reformation_composite__theological_fragmentation_reading, identity_coordination).
narrative_ontology:affects_constraint(reformation_composite__theological_fragmentation_reading, reformation_composite__political_realignment_reading).
narrative_ontology:affects_constraint(reformation_composite__theological_fragmentation_reading, reformation_composite__technological_mediation_reading).

% DUAL FORMULATION NOTE:
% This constraint is one of three readings of the 'reformation_composite' kernel. This 'theological_fragmentation_reading' focuses on doctrinal incompatibility. It influences and is influenced by the 'political_realignment_reading' and 'technological_mediation_reading' as these factors are deeply intertwined in the historical event.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
