% ============================================================================
% CONSTRAINT STORY: cultural_property_legal_corpus__sovereign_repatriation_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-19
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_cultural_property_legal_corpus__sovereign_repatriation_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: cultural_property_legal_corpus__sovereign_repatriation_reading
 *   human_readable: Sovereign Repatriation Reading of Cultural Property Law
 *   domain: international_law/cultural_property/post_colonial_studies
 *
 * SUMMARY:
 *   This story instantiates the sovereign-repatriation reading of the
 *   cultural property legal corpus: colonial-era acquisition is treated as
 *   illegitimate extraction, and legitimate title reverts to the modern
 *   successor state claiming historical continuity with the expropriated
 *   people. Under this reading, the state itself — not the specific community
 *   from whom an object was taken — is the legal beneficiary and the vehicle
 *   of restitution. This produces a genuine coordination function (a
 *   tractable diplomatic and legal channel for resolving century-old
 *   acquisition disputes) layered with a real extraction dynamic: the
 *   identity capital, custody, and narrative control generated by a
 *   successful restitution claim accrues disproportionately to state
 *   institutions rather than to the sub-national communities the moral case
 *   is built on. Encyclopedic museums bear the direct cost (deaccession,
 *   reputational and legal pressure); the community whose ancestors actually
 *   held the object often receives nothing beyond symbolic inclusion in the
 *   state's account of its own restored heritage.
 *
 * KEY AGENTS:
 *   - successor_state_governments: primary agenda-setter and beneficiary (institutional/arbitrage) — files and controls the claim
 *   - national_museum_authorities_of_successor_states: derivative beneficiary (institutional/constrained) — receives custody and prestige
 *   - encyclopedic_museums: primary payer (institutional/constrained) — bears legal, reputational, and collection cost
 *   - originating_subnational_communities: excluded party (powerless/trapped) — the doctrine's moral subject but not its legal beneficiary
 *   - international_cultural_property_tribunals: analytical observer (institutional/analytical) — administers the operative legal standard
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(cultural_property_legal_corpus__sovereign_repatriation_reading, 0.48).
domain_priors:suppression_score(cultural_property_legal_corpus__sovereign_repatriation_reading, 0.42).
domain_priors:theater_ratio(cultural_property_legal_corpus__sovereign_repatriation_reading, 0.3).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(cultural_property_legal_corpus__sovereign_repatriation_reading, extractiveness, 0.48).
narrative_ontology:constraint_metric(cultural_property_legal_corpus__sovereign_repatriation_reading, suppression_requirement, 0.42).
narrative_ontology:constraint_metric(cultural_property_legal_corpus__sovereign_repatriation_reading, theater_ratio, 0.3).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(cultural_property_legal_corpus__sovereign_repatriation_reading, accessibility_collapse, 0.5).
narrative_ontology:constraint_metric(cultural_property_legal_corpus__sovereign_repatriation_reading, resistance, 0.62).

% --- Constraint claim ---
narrative_ontology:constraint_claim(cultural_property_legal_corpus__sovereign_repatriation_reading, tangled_rope).
narrative_ontology:human_readable(cultural_property_legal_corpus__sovereign_repatriation_reading, "Sovereign Repatriation Reading of Cultural Property Law").
narrative_ontology:topic_domain(cultural_property_legal_corpus__sovereign_repatriation_reading, "international_law/cultural_property/post_colonial_studies").

domain_priors:requires_active_enforcement(cultural_property_legal_corpus__sovereign_repatriation_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(cultural_property_legal_corpus__sovereign_repatriation_reading, '00fff8c6-0572-4006-8eda-b198efe3b1ab').
narrative_ontology:cs_kernel_codification('00fff8c6-0572-4006-8eda-b198efe3b1ab', distributed).
narrative_ontology:cs_authority_grounding('00fff8c6-0572-4006-8eda-b198efe3b1ab', distributed).
narrative_ontology:cs_reading_relation('00fff8c6-0572-4006-8eda-b198efe3b1ab', cultural_property_legal_corpus__indigenous_stewardship_reading, forecloses).
narrative_ontology:cs_reading_relation('00fff8c6-0572-4006-8eda-b198efe3b1ab', cultural_property_legal_corpus__universal_heritage_reading, coexists_with).
narrative_ontology:cs_axiom('00fff8c6-0572-4006-8eda-b198efe3b1ab', foundational, state_succession_confers_sovereign_title).
narrative_ontology:cs_axiom_status(state_succession_confers_sovereign_title, holdable).
narrative_ontology:cs_axiom_grounding('00fff8c6-0572-4006-8eda-b198efe3b1ab', state_succession_confers_sovereign_title, conventional).
narrative_ontology:cs_axiom('00fff8c6-0572-4006-8eda-b198efe3b1ab', foundational, colonial_acquisition_is_illegitimate_extraction).
narrative_ontology:cs_axiom_status(colonial_acquisition_is_illegitimate_extraction, holdable).
narrative_ontology:cs_axiom_grounding('00fff8c6-0572-4006-8eda-b198efe3b1ab', colonial_acquisition_is_illegitimate_extraction, deontological).
narrative_ontology:cs_reference_frame('00fff8c6-0572-4006-8eda-b198efe3b1ab', westphalian_state_succession_standard).
narrative_ontology:cs_drift_state('00fff8c6-0572-4006-8eda-b198efe3b1ab', post_2000_restitution_wave, gap(revival_pressure, substantial, true)).
narrative_ontology:cs_created_at('00fff8c6-0572-4006-8eda-b198efe3b1ab', '').
narrative_ontology:cs_kernel_id(cultural_property_legal_corpus__sovereign_repatriation_reading, cultural_property_legal_corpus).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(cultural_property_legal_corpus__sovereign_repatriation_reading, successor_state_governments).
narrative_ontology:constraint_beneficiary(cultural_property_legal_corpus__sovereign_repatriation_reading, national_museum_authorities_of_successor_states).
narrative_ontology:constraint_victim(cultural_property_legal_corpus__sovereign_repatriation_reading, encyclopedic_museums).
narrative_ontology:constraint_victim(cultural_property_legal_corpus__sovereign_repatriation_reading, originating_subnational_communities).
narrative_ontology:constraint_vindicates(cultural_property_legal_corpus__sovereign_repatriation_reading, colonial_acquisition_illegitimacy_doctrine).
narrative_ontology:constraint_vindicates(cultural_property_legal_corpus__sovereign_repatriation_reading, state_succession_continuity_doctrine).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Files diplomatic and legal claims asserting sovereign title to artifacts removed during the colonial period, using the doctrine of state succession to expropriated peoples. Sets the terms of restitution negotiations, drafts bilateral repatriation agreements, and, once artifacts return, controls their display, narrative framing, and any onward loan or sale. Collects the diplomatic, cultural, and sometimes tourism-revenue capital that repatriation generates.
narrative_ontology:constraint_stakeholder(cultural_property_legal_corpus__sovereign_repatriation_reading, successor_state_governments, agenda_setter,
    institutional, generational, arbitrage, national).
narrative_ontology:stakeholder_secondary_role(cultural_property_legal_corpus__sovereign_repatriation_reading, successor_state_governments, beneficiary).

% Receives repatriated objects into state collections, builds new galleries and international prestige around them, and administers access. Its authority over the objects is derivative of the state's sovereign claim, not of any direct lineage to the originating community; it benefits from the state's win in the claim without itself having borne the extraction.
narrative_ontology:constraint_stakeholder(cultural_property_legal_corpus__sovereign_repatriation_reading, national_museum_authorities_of_successor_states, beneficiary,
    institutional, generational, constrained, national).

% Holds objects acquired during the colonial period, often under acquisition instruments now characterized as illegitimate. Faces mounting legal claims, reputational pressure, and diplomatic sanction if it refuses restitution; loses collection holdings, exhibition drawing power, and donor confidence either through forced repatriation or through the reputational cost of visible refusal. Its exit options are narrow: litigate, negotiate loan-back arrangements, or comply.
narrative_ontology:constraint_stakeholder(cultural_property_legal_corpus__sovereign_repatriation_reading, encyclopedic_museums, payer,
    institutional, biographical, constrained, global).

% The specific ethnic, religious, or kinship group from whom the objects were actually taken often does not correspond to the borders or population of the modern successor state that now presses the legal claim. They have no standing in state-to-state restitution negotiations and frequently do not regain custody, ritual access, or decision authority over the returned objects even after repatriation succeeds — the state, not the community, receives the object.
narrative_ontology:constraint_stakeholder(cultural_property_legal_corpus__sovereign_repatriation_reading, originating_subnational_communities, excluded,
    powerless, civilizational, trapped, regional).
narrative_ontology:stakeholder_secondary_role(cultural_property_legal_corpus__sovereign_repatriation_reading, originating_subnational_communities, payer).

% Adjudicates or mediates restitution disputes under instruments like the 1970 UNESCO Convention and bilateral treaties, applying the state-succession framework as the operative legal standard. Its rulings determine which claims succeed, reinforcing whichever party holds cognizable sovereign standing.
narrative_ontology:constraint_stakeholder(cultural_property_legal_corpus__sovereign_repatriation_reading, international_cultural_property_tribunals, observer,
    institutional, generational, analytical, global).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Provides a legally tractable, state-to-state channel for resolving colonial-era acquisition disputes: a successor state with recognized sovereignty can file a claim, negotiate, and receive custody without needing to identify or empower every dispersed sub-national claimant, which would otherwise be procedurally impossible under existing international law.
% TRANSFER_FUNCTION: Moves physical custody, legal title, symbolic capital, and diplomatic prestige from holding institutions to successor-state governments and their national museum authorities; moves comparatively little of that capital onward to the specific communities from whom the objects were originally taken.
% ABSENT_VOICES: Sub-state and diaspora communities whose ancestors were the actual expropriated parties are structurally absent from state-to-state negotiations — they hold no seat at the tribunal and no standing under the treaties that govern restitution, even though they are the population the doctrine's own moral narrative names as the historically wronged party.
% DISAPPEARANCE_RATIONALE: Holding institutions would argue the world barely changes — most contested objects have sat in their collections for a century without legal disturbance, and absent the sovereign-succession doctrine, restitution claims would revert to case-by-case diplomacy or lapse. Successor states and international tribunals would argue the world rearranges substantially: an entire body of active claims, bilateral treaties, and museum deaccession programs is currently organized around this doctrine and would lose its legal footing without it.
% FOUNDING_PROBLEM: Colonial-era removal of cultural artifacts left millions of objects in the collections of former colonial powers with no legal mechanism for the states that emerged from decolonization to contest acquisition legitimacy or recover items understood as central to national identity and historical memory.
% FOUNDING_PROBLEM_CORROBORATION: Successor-state governments and allied legal scholars attest the founding problem remains live — colonial-era extraction was real and its legal remedy is incomplete. Independent legal historians and anthropologists working outside both the claimant states and the holding museums note that the doctrine's state-succession framing was itself substantially shaped in the post-independence period by elite national governments consolidating cultural authority, and that the sub-national communities the doctrine's moral narrative centers were rarely consulted in either the doctrine's formation or its individual claim outcomes.
narrative_ontology:disappearance_verdict(cultural_property_legal_corpus__sovereign_repatriation_reading, contested).
narrative_ontology:founding_problem_status(cultural_property_legal_corpus__sovereign_repatriation_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(cultural_property_legal_corpus__sovereign_repatriation_reading, '8080348c4e16a265fafc924dcde83360dfd170fc',
    'becd0f87568a1ec0be97d1229ae702098dbd6568', '2026-07-05',
    'no_scope_rebuild_sonnet', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(cultural_property_legal_corpus__sovereign_repatriation_reading, 'none', 1).
narrative_ontology:epsilon_provenance(cultural_property_legal_corpus__sovereign_repatriation_reading, 0.48, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(cultural_property_legal_corpus__sovereign_repatriation_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(cultural_property_legal_corpus__sovereign_repatriation_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(cultural_property_legal_corpus__sovereign_repatriation_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extraction is authored at moderate (0.48) rather than high, reflecting the expected structural delta: repatriation does impose real diplomatic friction, legal cost, and reputational damage on holding institutions, but the object itself is genuinely restored rather than merely relabeled — some real symbolic value transfers, not pure rent extraction. Suppression is moderate (0.42) and has risen over the interval as the legal machinery (UNESCO instruments, bilateral treaty regimes, tribunal precedent) has hardened from a loosely normative claim in 1970 into an increasingly binding and actively enforced doctrine by 2026. Theater ratio is modest but rising (0.12 to 0.30), tracking the growing gap between ceremonial repatriation events (state visits, handover ceremonies) and the underlying question of whether custody actually reaches the originating community.
 *
 * DIRECTIONALITY LOGIC:
 *   Successor-state governments and their museum authorities sit near the beneficiary end of directionality: they set the claim's terms, control post-restitution custody, and capture the diplomatic and cultural capital with minimal ongoing cost. Encyclopedic museums sit near the target end: constrained exit, bearing legal and reputational cost with no offsetting gain. Originating sub-national communities are the structurally interesting case — the doctrine's own moral narrative names them as the wronged party, yet the legal and institutional architecture routes the remedy to the state rather than to them, leaving their directionality closer to a victim's despite nominal alignment with the 'right side' of the restitution claim.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem — colonial extraction with no legal remedy — is genuinely still partially live (unresolved claims exist), which prevents this from being classified as simple zombie mandatrophy. But the doctrine's application has drifted from remedying the original wrong (returning objects to the people who lost them) toward consolidating state cultural authority, which is a different function than the one that justified the doctrine's creation. Tangled Rope captures this correctly: coordination function (a workable claims channel) and extraction (state capture of communal restitution) coexist in the same structure, and enforcement (treaty regimes, tribunal rulings) is required to hold it in place.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    state_vs_community_title_gap,
    'Should legal title to a repatriated object vest in the successor state or in the specific sub-national community from whom it was taken, when the two do not coincide?',
    'Comparative case study of restitution outcomes where community-level custody claims were filed alongside or against state claims; track whether tribunals ever award custody below the state level.',
    'If community-level title is systematically unavailable under current doctrine, the sovereign-repatriation reading is structurally extractive toward the very population its moral narrative centers, strengthening the case for classification as tangled_rope rather than rope.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(state_vs_community_title_gap, conceptual, 'Whether state succession doctrine structurally forecloses community-level restitution.').

omega_variable(
    successor_state_continuity_fiction,
    'How much genuine historical-cultural continuity exists between the modern successor state and the pre-colonial polity or people from whom the object was taken, versus how much is a legal fiction constructed to support the claim?',
    'Historical and ethnographic analysis of specific claims comparing the borders, population, and governance of the claimant state against the originating polity at time of expropriation.',
    'Where continuity is thin, the doctrine functions primarily to transfer identity capital to a state apparatus with weak historical claim, which would push the classification further toward extraction; where continuity is strong, the coordination function is more genuine.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(successor_state_continuity_fiction, empirical, 'Empirical strength of the state-succession continuity premise underlying the reading.').

omega_variable(
    kernel_reading_selection,
    'This story adopts the sovereign-repatriation reading of the cultural property kernel among three coexisting readings (indigenous stewardship, sovereign repatriation, universal heritage). Is the choice of successor-state sovereignty as the operative legal standard itself contestable ground, or is it the settled international-law default?',
    'Survey of which reading currently governs binding international instruments (UNESCO 1970, UNIDROIT 1995) versus which readings appear only in advocacy and scholarly literature; track shifts in tribunal precedent toward indigenous or universal-heritage standards.',
    'If the indigenous-stewardship reading gains binding legal traction, the sovereign-repatriation reading''s beneficiary set (states) would lose title priority to originating communities directly, changing both ε and the beneficiary declaration in this story.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_reading_selection, conceptual, 'Committer-frame note: this constraint is one reading of the cultural_property_legal_corpus kernel; sibling readings would redistribute the beneficiary and victim sets differently.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(cultural_property_legal_corpus__sovereign_repatriation_reading, 1970, 2026).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(cult_tr_t1970, cultural_property_legal_corpus__sovereign_repatriation_reading, theater_ratio, 1970, 0.12).
narrative_ontology:measurement(cult_tr_t1982, cultural_property_legal_corpus__sovereign_repatriation_reading, theater_ratio, 1982, 0.15).
narrative_ontology:measurement(cult_tr_t1994, cultural_property_legal_corpus__sovereign_repatriation_reading, theater_ratio, 1994, 0.19).
narrative_ontology:measurement(cult_tr_t2006, cultural_property_legal_corpus__sovereign_repatriation_reading, theater_ratio, 2006, 0.23).
narrative_ontology:measurement(cult_tr_t2018, cultural_property_legal_corpus__sovereign_repatriation_reading, theater_ratio, 2018, 0.27).
narrative_ontology:measurement(cult_tr_t2026, cultural_property_legal_corpus__sovereign_repatriation_reading, theater_ratio, 2026, 0.3).

% Extraction over time
narrative_ontology:measurement(cult_be_t1970, cultural_property_legal_corpus__sovereign_repatriation_reading, base_extractiveness, 1970, 0.28).
narrative_ontology:measurement(cult_be_t1982, cultural_property_legal_corpus__sovereign_repatriation_reading, base_extractiveness, 1982, 0.33).
narrative_ontology:measurement(cult_be_t1994, cultural_property_legal_corpus__sovereign_repatriation_reading, base_extractiveness, 1994, 0.36).
narrative_ontology:measurement(cult_be_t2006, cultural_property_legal_corpus__sovereign_repatriation_reading, base_extractiveness, 2006, 0.41).
narrative_ontology:measurement(cult_be_t2018, cultural_property_legal_corpus__sovereign_repatriation_reading, base_extractiveness, 2018, 0.45).
narrative_ontology:measurement(cult_be_t2026, cultural_property_legal_corpus__sovereign_repatriation_reading, base_extractiveness, 2026, 0.48).

% Suppression requirement over time
narrative_ontology:measurement(cult_su_t1970, cultural_property_legal_corpus__sovereign_repatriation_reading, suppression_requirement, 1970, 0.22).
narrative_ontology:measurement(cult_su_t1982, cultural_property_legal_corpus__sovereign_repatriation_reading, suppression_requirement, 1982, 0.28).
narrative_ontology:measurement(cult_su_t1994, cultural_property_legal_corpus__sovereign_repatriation_reading, suppression_requirement, 1994, 0.31).
narrative_ontology:measurement(cult_su_t2006, cultural_property_legal_corpus__sovereign_repatriation_reading, suppression_requirement, 2006, 0.35).
narrative_ontology:measurement(cult_su_t2018, cultural_property_legal_corpus__sovereign_repatriation_reading, suppression_requirement, 2018, 0.39).
narrative_ontology:measurement(cult_su_t2026, cultural_property_legal_corpus__sovereign_repatriation_reading, suppression_requirement, 2026, 0.42).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(cultural_property_legal_corpus__sovereign_repatriation_reading, enforcement_mechanism).
narrative_ontology:affects_constraint(cultural_property_legal_corpus__sovereign_repatriation_reading, cultural_property_legal_corpus__universal_heritage_reading).
narrative_ontology:affects_constraint(cultural_property_legal_corpus__sovereign_repatriation_reading, cultural_property_legal_corpus__indigenous_stewardship_reading).

% DUAL FORMULATION NOTE:
% This story is one of three linked readings of the cultural_property_legal_corpus kernel. The universal_heritage_reading treats encyclopedic museums as legitimate stewards and would classify much of what this story treats as extraction as instead a preservation function under threat; its beneficiary set (major museums) is nearly the inverse of this story's victim set. The indigenous_stewardship_reading treats this story's own beneficiary (the successor state) as itself an extractor of communal identity capital, on the same structural grounds this story uses against encyclopedic museums — the sovereign-repatriation reading's coordination story becomes the indigenous-stewardship reading's extraction story. All three share the same underlying artifacts and acquisition history but diverge on where legitimate authority is located, producing three structurally distinct ε values and beneficiary/victim maps rather than one constraint measured three ways.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
