% ============================================================================
% CONSTRAINT STORY: substance_control_legitimacy__prohibition_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-19
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_substance_control_legitimacy__prohibition_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: substance_control_legitimacy__prohibition_reading
 *   human_readable: Criminalization-Based Substance Prohibition Regime
 *   domain: public_health/criminal_justice/political_economy
 *
 * SUMMARY:
 *   This story instantiates the prohibition reading of the
 *   substance_control_legitimacy kernel: substance use is treated as
 *   inherently harmful, and state authority to criminalize is grounded in a
 *   moral duty to prevent that harm. Under this reading, users themselves
 *   enter the victim set (via arrest, conviction, and collateral
 *   consequence), carceral extraction is high because the mechanism of
 *   harm-prevention IS incarceration, and black-market violence is an
 *   externality generated by the prohibition mechanism rather than by the
 *   substances themselves. This is a distinct constraint from the
 *   harm_reduction_reading (public health framing, no criminalization) and
 *   the legalization_reading (autonomy framing, state limited to third-party
 *   harm) — those are separate constraint files with their own ε values, not
 *   alternate measurements of this one.
 *
 * KEY AGENTS:
 *   - substance_users: primary target of criminalization (powerless/trapped) — bear arrest, conviction, and lasting collateral consequence
 *   - law_enforcement_agencies: agenda-setter and beneficiary (institutional/arbitrage) — administer enforcement and capture budget/forfeiture revenue tied to enforcement volume
 *   - carceral_industry_contractors: beneficiary (organized/arbitrage) — revenue scales with incarceration volume
 *   - organized_trafficking_networks: beneficiary (organized/arbitrage) — monopoly rents created precisely by the absence of legal competition
 *   - public_health_researchers: excluded analytical voice — evidence on outcomes is contested input, not governing input
 *   - legislators_and_courts: agenda-setting observer — write and adjudicate the statutes but bear none of the accumulated costs
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(substance_control_legitimacy__prohibition_reading, 0.78).
domain_priors:suppression_score(substance_control_legitimacy__prohibition_reading, 0.87).
domain_priors:theater_ratio(substance_control_legitimacy__prohibition_reading, 0.42).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(substance_control_legitimacy__prohibition_reading, extractiveness, 0.78).
narrative_ontology:constraint_metric(substance_control_legitimacy__prohibition_reading, suppression_requirement, 0.87).
narrative_ontology:constraint_metric(substance_control_legitimacy__prohibition_reading, theater_ratio, 0.42).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(substance_control_legitimacy__prohibition_reading, accessibility_collapse, 0.4).
narrative_ontology:constraint_metric(substance_control_legitimacy__prohibition_reading, resistance, 0.72).

% --- Constraint claim ---
narrative_ontology:constraint_claim(substance_control_legitimacy__prohibition_reading, tangled_rope).
narrative_ontology:human_readable(substance_control_legitimacy__prohibition_reading, "Criminalization-Based Substance Prohibition Regime").
narrative_ontology:topic_domain(substance_control_legitimacy__prohibition_reading, "public_health/criminal_justice/political_economy").

domain_priors:requires_active_enforcement(substance_control_legitimacy__prohibition_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(substance_control_legitimacy__prohibition_reading, '992a722c-f7ca-4e45-a596-4731f69dd8fd').
narrative_ontology:cs_kernel_codification('992a722c-f7ca-4e45-a596-4731f69dd8fd', formalized).
narrative_ontology:cs_authority_grounding('992a722c-f7ca-4e45-a596-4731f69dd8fd', extraction).
narrative_ontology:cs_interpretation_layer_present('992a722c-f7ca-4e45-a596-4731f69dd8fd').
narrative_ontology:cs_reading_relation('992a722c-f7ca-4e45-a596-4731f69dd8fd', substance_control_legitimacy__harm_reduction_reading, coexists_with).
narrative_ontology:cs_reading_relation('992a722c-f7ca-4e45-a596-4731f69dd8fd', substance_control_legitimacy__legalization_reading, forecloses).
narrative_ontology:cs_axiom('992a722c-f7ca-4e45-a596-4731f69dd8fd', foundational, substance_use_is_inherently_harmful_regardless_of_context).
narrative_ontology:cs_axiom_status(substance_use_is_inherently_harmful_regardless_of_context, holdable).
narrative_ontology:cs_axiom_grounding('992a722c-f7ca-4e45-a596-4731f69dd8fd', substance_use_is_inherently_harmful_regardless_of_context, empirically_contingent).
narrative_ontology:cs_axiom('992a722c-f7ca-4e45-a596-4731f69dd8fd', foundational, state_has_moral_duty_to_prevent_harm_via_criminal_sanction).
narrative_ontology:cs_axiom_status(state_has_moral_duty_to_prevent_harm_via_criminal_sanction, holdable).
narrative_ontology:cs_axiom_grounding('992a722c-f7ca-4e45-a596-4731f69dd8fd', state_has_moral_duty_to_prevent_harm_via_criminal_sanction, deontological).
narrative_ontology:cs_reference_frame('992a722c-f7ca-4e45-a596-4731f69dd8fd', moral_harm_prevention_mandate).
narrative_ontology:cs_drift_state('992a722c-f7ca-4e45-a596-4731f69dd8fd', post_mass_incarceration_era, gap(axiom_overriding, substantial, false)).
narrative_ontology:cs_created_at('992a722c-f7ca-4e45-a596-4731f69dd8fd', '').
narrative_ontology:cs_kernel_id(substance_control_legitimacy__prohibition_reading, substance_control_legitimacy).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(substance_control_legitimacy__prohibition_reading, carceral_industry_contractors).
narrative_ontology:constraint_beneficiary(substance_control_legitimacy__prohibition_reading, law_enforcement_agencies).
narrative_ontology:constraint_beneficiary(substance_control_legitimacy__prohibition_reading, prohibition_aligned_political_actors).
narrative_ontology:constraint_beneficiary(substance_control_legitimacy__prohibition_reading, organized_trafficking_networks).
narrative_ontology:constraint_victim(substance_control_legitimacy__prohibition_reading, substance_users).
narrative_ontology:constraint_victim(substance_control_legitimacy__prohibition_reading, low_income_defendants).
narrative_ontology:constraint_victim(substance_control_legitimacy__prohibition_reading, communities_of_color).
narrative_ontology:constraint_victim(substance_control_legitimacy__prohibition_reading, families_of_incarcerated_users).
narrative_ontology:constraint_victim(substance_control_legitimacy__prohibition_reading, bystanders_to_black_market_violence).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Use is defined as inherently harmful regardless of actual pattern of use or dependency status, converting a health condition into a criminal one. Arrest, conviction, and incarceration are the primary state response; exit requires either abstinence enforced under threat of prosecution or ongoing concealment. Criminal records foreclose housing, employment, and custody outcomes long after any sentence is served.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, substance_users, payer,
    powerless, biographical, trapped, national).

% Lack resources for private counsel, diversion programs, or bail, and so absorb the harshest version of the same statutes that wealthier users navigate through treatment alternatives or simply avoid via private use settings. Plea pressure and mandatory minimums remove practical exit from the system once charged.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, low_income_defendants, payer,
    powerless, biographical, trapped, national).

% Bear disproportionate enforcement intensity relative to documented use rates, concentrating arrest, incarceration, and collateral consequences (voting rights, employment licensure, family separation) across generations within the same neighborhoods repeatedly targeted for enforcement resources.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, communities_of_color, payer,
    powerless, generational, trapped, national).

% Absorb the economic and caregiving costs of a parent's or partner's incarceration for a possession or use offense, including lost income, custody disruption, and the enduring stigma attached to the household. They have no standing in the proceedings that produced these costs.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, families_of_incarcerated_users, payer,
    powerless, generational, trapped, national).

% Live in neighborhoods where prohibition has pushed distribution into unregulated, violently competitive markets. They did not choose to use the substances at issue but absorb the externality of turf disputes, stray gunfire, and destabilized local governance that accompanies an illicit trade with no legal dispute-resolution mechanism.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, bystanders_to_black_market_violence, payer,
    powerless, immediate, trapped, regional).

% Administer enforcement, set operational priorities within statutory bounds, and receive budget allocations, asset forfeiture proceeds, and federal grant funding tied to drug-enforcement activity levels. Their institutional continuity and expansion are substantially justified by the existence and scale of the prohibited market.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, law_enforcement_agencies, agenda_setter,
    institutional, generational, arbitrage, national).
narrative_ontology:stakeholder_secondary_role(substance_control_legitimacy__prohibition_reading, law_enforcement_agencies, beneficiary).

% Operate private prisons, supply chain services, and correctional labor programs whose revenue scales directly with incarceration volume. Possession and low-level distribution convictions are a substantial and stable share of the incarcerated population they are paid per-capita or per-contract to house.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, carceral_industry_contractors, beneficiary,
    organized, generational, arbitrage, national).

% Build electoral and fundraising platforms around 'tough on crime' framing, collecting political capital, donor support, and durable institutional positioning from visible enforcement activity, independent of whether the underlying harm-prevention rationale is empirically supported.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, prohibition_aligned_political_actors, beneficiary,
    powerful, biographical, arbitrage, national).

% Extract monopoly-style profits precisely because prohibition removes legal competition and price transparency; enforcement pressure raises prices and margins more than it reduces market volume, and organizational sophistication becomes a competitive advantage that legal firms could never claim to hold.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, organized_trafficking_networks, beneficiary,
    organized, biographical, arbitrage, continental).

% Produce decades of evidence on treatment efficacy, overdose mortality, and comparative outcomes between criminalized and decriminalized regimes, but their findings enter policy debate as contested input rather than governing evidence — the criminalization framework is set independent of, and often contrary to, their consensus.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, public_health_researchers, excluded,
    moderate, civilizational, analytical, national).

% Write and adjudicate the statutes that define substance use as criminal, periodically revisiting sentencing structure and scheduling. They can observe the accumulated carceral and market-violence costs but bear none of them directly and face asymmetric political cost for loosening rather than tightening enforcement.
narrative_ontology:constraint_stakeholder(substance_control_legitimacy__prohibition_reading, legislators_and_courts, observer,
    institutional, generational, analytical, national).
narrative_ontology:stakeholder_secondary_role(substance_control_legitimacy__prohibition_reading, legislators_and_courts, agenda_setter).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: In principle, coordinates a collective response to substance-related harm by establishing a uniform, publicly enforced prohibition rather than leaving harm mitigation to fragmented private or local action.
% TRANSFER_FUNCTION: Moves liberty, income, and family stability from substance users and their communities to carceral contractors, enforcement agencies, and political actors who convert enforcement activity into budget, revenue, and electoral capital; simultaneously moves consumer surplus from users to organized trafficking networks via prohibition-inflated prices.
% ABSENT_VOICES: Public health researchers and the substance users themselves are structurally outside the legislative process that defines the offense and sets sentencing; families and bystanders bearing collateral and externality costs have no formal standing in the proceedings that produce those costs.
% DISAPPEARANCE_RATIONALE: If criminalization were removed overnight, incarceration populations tied to possession and low-level distribution would collapse, carceral revenue streams would shrink sharply, trafficking network margins would compress as legal competition became possible, and enforcement agency budgets and political messaging built around drug enforcement would require substantial reorganization.
% FOUNDING_PROBLEM: Widespread, unregulated substance use was framed as producing severe individual and social harm (addiction, family breakdown, public disorder) that ungoverned markets and private conduct could not adequately address, justifying state intervention through criminal law.
% FOUNDING_PROBLEM_CORROBORATION: Enforcement agencies and prohibition-aligned political actors attest the harm-prevention problem remains live and justifies current statutes. Public health researchers, drug policy commissions in jurisdictions that have shifted toward decriminalization, and international bodies studying comparative outcomes attest the mechanism has substantially failed on its own terms — use rates are not reliably reduced relative to non-criminalized regimes, while incarceration and market-violence harms have grown — constituting corroboration from outside the beneficiary set that the founding problem is either unsolved by this mechanism or has mutated into a different, self-sustaining function.
narrative_ontology:disappearance_verdict(substance_control_legitimacy__prohibition_reading, world_rearranges).
narrative_ontology:founding_problem_status(substance_control_legitimacy__prohibition_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(substance_control_legitimacy__prohibition_reading, '8080348c4e16a265fafc924dcde83360dfd170fc',
    'becd0f87568a1ec0be97d1229ae702098dbd6568', '2026-07-05',
    'no_scope_rebuild_sonnet', 'agent/example_platform_commission.json',
    'claude-sonnet-5', 'max_tokens=16384,thinking=disabled,temperature=api_default').
narrative_ontology:story_seed(substance_control_legitimacy__prohibition_reading, 'none', 1).
narrative_ontology:epsilon_provenance(substance_control_legitimacy__prohibition_reading, 0.78, 'claude-sonnet-5', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(substance_control_legitimacy__prohibition_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(substance_control_legitimacy__prohibition_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(substance_control_legitimacy__prohibition_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness is authored high (0.78) and rising because the mechanism explicitly converts substance use into criminal liability, and the resulting carceral, political, and black-market revenue streams grow as enforcement intensifies — this is the structural delta the prohibition reading requires relative to its siblings. Suppression is authored very high (0.87) because the regime depends on continuous, resourced enforcement (policing, prosecution, incarceration infrastructure) to hold; without active suppression the classification could not persist as prohibition. Theater ratio is moderate and rising (0.42) reflecting a growing gap between the stated harm-prevention rationale and enforcement's actual correlation with harm reduction outcomes — a substantial share of enforcement activity now sustains institutional budgets and political messaging rather than measurably reducing substance-related harm. Accessibility collapse is moderate (0.4), not extreme, because private use, treatment-seeking, and underground harm-mitigation practices persist despite criminalization — the constraint does not fully close alternatives, it just makes them costly and dangerous. Resistance is substantial (0.72), reflecting sustained advocacy, litigation, and jurisdictional decriminalization movements pushing back against the regime.
 *
 * DIRECTIONALITY LOGIC:
 *   Substance users, low-income defendants, communities of color, families of incarcerated users, and bystanders to black-market violence are all declared victims because the criminalization mechanism transfers liberty, income, and safety from them to enforcement institutions, carceral contractors, political actors, and trafficking networks. Law enforcement agencies, carceral contractors, and prohibition-aligned political actors are beneficiaries with institutional or organized power and arbitrage-level exit — they can relocate resources, reframe messaging, or redirect enforcement priorities without bearing the downside. Organized trafficking networks are an unusual but structurally necessary beneficiary class: prohibition is the source of their monopoly rents, making them structural beneficiaries of the very regime nominally designed to eliminate them.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem (harm from unregulated substance use) is contested as still live: enforcement agencies assert it persists and justifies continued criminalization, but public health evidence and jurisdictions that have shifted approach report the mechanism does not reliably reduce use or harm relative to alternatives, while independently generating carceral and market-violence costs. This mismatch — founding_problem_status contested, disappearance_verdict world_rearranges — is exactly the signal the R5 genealogy interview exists to surface: an arrangement whose original justification is empirically disputed but whose removal would still visibly reorganize incarceration, market structure, and political economy, indicating the arrangement now sustains itself partly independent of its founding rationale.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    harm_prevention_efficacy_of_criminalization,
    'Does criminalization actually reduce substance-related harm relative to the sibling readings'' non-criminal mechanisms, or does it primarily relocate and amplify harm (incarceration, market violence) while leaving underlying use rates comparable?',
    'Comparative longitudinal analysis of jurisdictions that shifted from criminalization to decriminalization or regulated legalization, controlling for enforcement intensity, treatment access, and baseline use rates.',
    'If criminalization shows no differential harm-reduction benefit over the sibling mechanisms, the moral-duty justification for this reading''s authority claim is substantially undermined, supporting a reclassification toward tangled_rope or snare with a weaker coordination component.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(harm_prevention_efficacy_of_criminalization, empirical, 'Whether criminalization achieves its stated harm-prevention function relative to non-criminal alternatives.').

omega_variable(
    kernel_reading_selection_mechanism,
    'Why does a given jurisdiction adopt the prohibition_reading rather than the harm_reduction_reading or legalization_reading of the same underlying substance-use-and-harm kernel, given that all three readings claim to address the same founding problem?',
    'Comparative political economy analysis of which institutional actors (law enforcement, carceral industry, moral/religious coalitions) have historically had agenda-setting power in jurisdictions that adopted prohibition versus those that adopted alternative readings.',
    'If reading selection correlates strongly with the presence of concentrated beneficiaries (carceral capacity, enforcement budgets) rather than with harm outcomes, this supports treating the prohibition_reading as substantially beneficiary-driven rather than harm-driven, reinforcing the tangled_rope classification over a rope or mountain framing.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_reading_selection_mechanism, conceptual, 'Committer-frame question: what drives selection of this reading over its siblings within the same kernel.').

omega_variable(
    black_market_violence_attribution,
    'Is black-market violence properly attributed to the criminalization mechanism (an externality of prohibition) or to substance use itself (an inherent property of the substances)?',
    'Cross-jurisdictional comparison of violence rates in regulated-legal markets for the same substances versus criminalized markets for the same substances, holding substance pharmacology constant.',
    'If violence tracks market-legality status rather than substance identity, this strongly supports classifying the violence as an externality generated by the prohibition constraint itself, deepening the victim-side extractiveness measure for bystanders and reinforcing the case that this reading''s harm-prevention rationale is partly self-defeating.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(black_market_violence_attribution, empirical, 'Whether black-market violence is a property of prohibition or of the substances being prohibited.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(substance_control_legitimacy__prohibition_reading, 0, 50).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(subs_tr_t0, substance_control_legitimacy__prohibition_reading, theater_ratio, 0, 0.2).
narrative_ontology:measurement(subs_tr_t10, substance_control_legitimacy__prohibition_reading, theater_ratio, 10, 0.26).
narrative_ontology:measurement(subs_tr_t20, substance_control_legitimacy__prohibition_reading, theater_ratio, 20, 0.31).
narrative_ontology:measurement(subs_tr_t30, substance_control_legitimacy__prohibition_reading, theater_ratio, 30, 0.35).
narrative_ontology:measurement(subs_tr_t40, substance_control_legitimacy__prohibition_reading, theater_ratio, 40, 0.39).
narrative_ontology:measurement(subs_tr_t50, substance_control_legitimacy__prohibition_reading, theater_ratio, 50, 0.42).

% Extraction over time
narrative_ontology:measurement(subs_be_t0, substance_control_legitimacy__prohibition_reading, base_extractiveness, 0, 0.42).
narrative_ontology:measurement(subs_be_t10, substance_control_legitimacy__prohibition_reading, base_extractiveness, 10, 0.53).
narrative_ontology:measurement(subs_be_t20, substance_control_legitimacy__prohibition_reading, base_extractiveness, 20, 0.61).
narrative_ontology:measurement(subs_be_t30, substance_control_legitimacy__prohibition_reading, base_extractiveness, 30, 0.68).
narrative_ontology:measurement(subs_be_t40, substance_control_legitimacy__prohibition_reading, base_extractiveness, 40, 0.74).
narrative_ontology:measurement(subs_be_t50, substance_control_legitimacy__prohibition_reading, base_extractiveness, 50, 0.78).

% Suppression requirement over time
narrative_ontology:measurement(subs_su_t0, substance_control_legitimacy__prohibition_reading, suppression_requirement, 0, 0.65).
narrative_ontology:measurement(subs_su_t10, substance_control_legitimacy__prohibition_reading, suppression_requirement, 10, 0.72).
narrative_ontology:measurement(subs_su_t20, substance_control_legitimacy__prohibition_reading, suppression_requirement, 20, 0.78).
narrative_ontology:measurement(subs_su_t30, substance_control_legitimacy__prohibition_reading, suppression_requirement, 30, 0.82).
narrative_ontology:measurement(subs_su_t40, substance_control_legitimacy__prohibition_reading, suppression_requirement, 40, 0.85).
narrative_ontology:measurement(subs_su_t50, substance_control_legitimacy__prohibition_reading, suppression_requirement, 50, 0.87).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(substance_control_legitimacy__prohibition_reading, enforcement_mechanism).
narrative_ontology:affects_constraint(substance_control_legitimacy__prohibition_reading, harm_reduction_reading).
narrative_ontology:affects_constraint(substance_control_legitimacy__prohibition_reading, legalization_reading).

% DUAL FORMULATION NOTE:
% This story is one of three sibling readings of the substance_control_legitimacy kernel. harm_reduction_reading treats substance use as a public health issue with no criminalization and a much lower victim/extraction profile for users. legalization_reading treats competent adult use as an autonomy matter with state authority confined to third-party harm, foreclosing much of this reading's carceral apparatus. All three share the same underlying kernel (state authority over substance use) but instantiate structurally distinct constraints with different ε, different beneficiary/victim sets, and different classifications; they are linked here for contamination-propagation analysis, not merged.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
