% ============================================================================
% CONSTRAINT STORY: welfare_coordination_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-02-26
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_welfare_coordination_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: welfare_coordination_reading
 *   human_readable: Welfare Coordination in EU Free Movement: Posted Workers and Social Dumping
 *   domain: political_economy/federalism/migration_policy
 *
 * SUMMARY:
 *   Free movement of labor within the EU is institutionally framed as
 *   coordination without supranational welfare harmonization — member states
 *   retain autonomy over benefit-eligibility rules while accepting free
 *   movement of workers across borders. This constraint captures the
 *   structural tension generated by that autonomy doctrine when layered with
 *   posted-worker exemptions and wage-arbitrage mechanisms. The constraint
 *   exhibits properties of both coordination (labor reallocation, capital
 *   mobility) and asymmetric extraction (posted-worker exploitation,
 *   receiving-state labor-market pressure, sending-state fiscal loss). This
 *   is one reading of a contested kernel: the federation_membership_kernel
 *   comprises three coexisting but structurally incompatible commitments —
 *   (1) full supranational integration and welfare harmonization
 *   (integration_reading), (2) member-state sovereignty with controlled
 *   opt-outs (member_sovereignty_reading), and (3) coordination among
 *   autonomous welfare states through selective harmonization and enforcement
 *   (welfare_coordination_reading, this constraint). The three readings
 *   produce different victim sets, different extraction mechanisms, and
 *   different terminal classifications. This constraint instantiates the
 *   coordination reading: free movement operates as coordination of national
 *   systems rather than their supranational replacement, generating
 *   extraction through differential access and fiscal asymmetry rather than
 *   through authoritarian harmonization.
 *
 * KEY AGENTS:
 *   - Posted workers: Primary victims (powerless/trapped) — exploited through wage arbitrage, 2-year social-contribution exemption, contract manipulation, minimal exit options
 *   - Receiving-state labor markets: Secondary victims (moderate/constrained) — face wage depression in low-skill sectors, displacement pressures, fiscal burden of post-exemption-window welfare eligibility
 *   - Sending-state fiscal systems: Secondary victims (institutional/constrained) — lose tax revenue from emigrant wages, cannot tax remittances, must maintain infrastructure for workers who partially relocate income
 *   - Capital mobility beneficiaries (employers, posting firms): Primary beneficiaries (institutional/arbitrage) — extract direct cost savings through exemptions and wage-arbitrage access; can relocate labor sourcing across jurisdictions
 *   - EU enforcement machinery (Commission, ECJ, labor inspectorates): Organized actors (organized/constrained) — drive anti-dumping regulation and standard elevation; see sunset logic in progressive harmonization
 *   - National welfare systems: Institutional actors (institutional/constrained) — maintain autonomy rhetoric while experiencing extraction through free-movement arbitrage; constrained exit options
 *   - Welfare commons (abstract collective good): Victim (powerless/trapped) — non-constituent agent; bears full cost of exploitation and cannot organize or exit
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(welfare_coordination_reading, 0.54).
domain_priors:suppression_score(welfare_coordination_reading, 0.62).
domain_priors:theater_ratio(welfare_coordination_reading, 0.48).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(welfare_coordination_reading, extractiveness, 0.54).
narrative_ontology:constraint_metric(welfare_coordination_reading, suppression_requirement, 0.62).
narrative_ontology:constraint_metric(welfare_coordination_reading, theater_ratio, 0.48).

% --- Constraint claim ---
narrative_ontology:constraint_claim(welfare_coordination_reading, tangled_rope).
narrative_ontology:human_readable(welfare_coordination_reading, "Welfare Coordination in EU Free Movement: Posted Workers and Social Dumping").
narrative_ontology:topic_domain(welfare_coordination_reading, "political_economy/federalism/migration_policy").

domain_priors:requires_active_enforcement(welfare_coordination_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(welfare_coordination_reading, '2aba284e-26ae-47e5-8103-ce50f88cba9c').
narrative_ontology:cs_created_at('2aba284e-26ae-47e5-8103-ce50f88cba9c', '').
narrative_ontology:cs_kernel_codification('2aba284e-26ae-47e5-8103-ce50f88cba9c', formalized).
narrative_ontology:cs_authority_grounding('2aba284e-26ae-47e5-8103-ce50f88cba9c', extraction).
narrative_ontology:cs_interpretation_layer_present('2aba284e-26ae-47e5-8103-ce50f88cba9c').
narrative_ontology:cs_kernel_id(welfare_coordination_reading, federation_membership_kernel).
narrative_ontology:cs_reading_relation('2aba284e-26ae-47e5-8103-ce50f88cba9c', integration_reading, forecloses).
narrative_ontology:cs_reading_relation('2aba284e-26ae-47e5-8103-ce50f88cba9c', member_sovereignty_reading, coexists_with).
narrative_ontology:cs_axiom('2aba284e-26ae-47e5-8103-ce50f88cba9c', foundational, welfare_autonomy_compatible_with_free_movement).
narrative_ontology:cs_axiom_status(welfare_autonomy_compatible_with_free_movement, holdable).
narrative_ontology:cs_axiom_grounding('2aba284e-26ae-47e5-8103-ce50f88cba9c', welfare_autonomy_compatible_with_free_movement, deontological).
narrative_ontology:cs_axiom('2aba284e-26ae-47e5-8103-ce50f88cba9c', foundational, selective_harmonization_can_manage_extraction).
narrative_ontology:cs_axiom_status(selective_harmonization_can_manage_extraction, holdable).
narrative_ontology:cs_axiom_grounding('2aba284e-26ae-47e5-8103-ce50f88cba9c', selective_harmonization_can_manage_extraction, empirically_contingent).
narrative_ontology:cs_reference_frame('2aba284e-26ae-47e5-8103-ce50f88cba9c', member_state_welfare_autonomy_with_managed_free_movement).
narrative_ontology:cs_drift_state('2aba284e-26ae-47e5-8103-ce50f88cba9c', contemporary_post_services_directive_era, gap(practice_drift, substantial, false)).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(welfare_coordination_reading, mobile_labor_arbitrageurs).
narrative_ontology:constraint_beneficiary(welfare_coordination_reading, capital_mobility_seekers).
narrative_ontology:constraint_beneficiary(welfare_coordination_reading, receiving_state_employers).
narrative_ontology:constraint_victim(welfare_coordination_reading, posted_workers).
narrative_ontology:constraint_victim(welfare_coordination_reading, receiving_state_labor_markets).
narrative_ontology:constraint_victim(welfare_coordination_reading, sending_state_fiscal_systems).
narrative_ontology:constraint_victim(welfare_coordination_reading, welfare_commons).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: POSTED WORKER (SNARE) — Trapped in wage arbitrage structure. 2-year exemption from receiving-state social contributions creates direct cost advantage for employers hiring posted workers over domestic labor. Worker bears suppression through exploitative contract terms, no access to receiving state welfare, and no ability to exit without losing placement. Structural extraction with minimal coordination function.
constraint_indexing:constraint_classification(welfare_coordination_reading, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(regional))).

% PERSPECTIVE 2: RECEIVING-STATE LABOR MARKET (TANGLED ROPE) — Experiences coordination benefit (access to EU-wide labor pool, reduced labor scarcity) alongside extraction (posted-worker undercutting, wage depression in low-skill sectors, fiscal burden of migrant welfare eligibility after 2-year exemption window). Member state cannot exit without losing single-market access; coordination function is genuine but asymmetrically distributed.
constraint_indexing:constraint_classification(welfare_coordination_reading, tangled_rope,
    context(agent_power(moderate),
            time_horizon(biographical),
            exit_options(constrained),
            spatial_scope(national))).

% PERSPECTIVE 3: CAPITAL MOBILITY BENEFICIARIES (ROPE) — Employers and posting firms experience the constraint as pure coordination with direct benefit. 2-year social-contribution exemption + cabotage wage freedom = direct cost savings on labor and posted-worker service delivery. Can arbitrage wage and regulatory differences across member states. Extraction flows toward this agent; their exit option is arbitrage (can relocate posting origin or switch labor sourcing strategies). Low effective extraction experienced by beneficiary.
constraint_indexing:constraint_classification(welfare_coordination_reading, rope,
    context(agent_power(institutional),
            time_horizon(immediate),
            exit_options(arbitrage),
            spatial_scope(regional))).

% PERSPECTIVE 4: SENDING-STATE FISCAL & LABOR SYSTEM (TANGLED ROPE) — Coordinates labor supply (workers exit to higher-wage markets, reducing domestic unemployment pressure). But extraction operates through absence of fiscal compensation: sending state loses tax revenue from emigrant wages and must maintain infrastructure/training for workers who remit incompletely. No sunset clause on this fiscal loss. Constrained exit — cannot block emigration without violating free movement, cannot tax remittances effectively (capital flight), cannot opt out of single market.
constraint_indexing:constraint_classification(welfare_coordination_reading, tangled_rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(national))).

% PERSPECTIVE 5: EU ANTI-DUMPING ENFORCEMENT (SCAFFOLD) — EU enforcement of minimum-wage rules, cabotage restrictions, and posted-worker protections functions as a coordination mechanism with sunset logic: as member states harmonize labor standards upward (Posted Workers Directive amendments, wage-floor coordination), the exploitation gaps close and the extraction mechanism loses force. Theater ratio is moderate (0.48) because enforcement is genuinely functional, not merely performative. Organized actors (trade unions, labor inspectorates) drive continuous standard elevation. High suppression reflects current enforcement gaps, but the regulatory architecture has built-in sunset: as homogenization advances, the arbitrage window shrinks.
constraint_indexing:constraint_classification(welfare_coordination_reading, scaffold,
    context(agent_power(organized),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(continental))).

% PERSPECTIVE 6: NATIONAL WELFARE AUTONOMY DOCTRINE (PITON) — The doctrine that member states retain sovereignty over welfare design and benefit-eligibility rules operates as institutional inertia. Functionally degraded because posted-worker exemptions and free-movement arbitrage have hollowed the doctrine: states have autonomy over eligibility rules but cannot enforce them against posted workers who are nominally non-resident. Theater ratio rises here because the doctrine persists through repetition (EU courts cite it) without operational force. The autonomy is rhetorical — binding in EU law discourse but limited in structural practice by the wage-arbitrage extraction mechanism.
constraint_indexing:constraint_classification(welfare_coordination_reading, piton,
    context(agent_power(institutional),
            time_horizon(civilizational),
            exit_options(constrained),
            spatial_scope(continental))).

% PERSPECTIVE 7: EU INSTITUTIONAL FRAMEWORK (TANGLED ROPE) — From the analytical position of EU institutional coordination, the constraint is structurally mixed: genuine coordination function (single market enables labor reallocation to efficient locations, reduces persistent unemployment in lower-wage regions, enables capital mobility) coexists with asymmetric extraction (low-wage states bear fiscal and labor-market costs; high-wage states gain welfare-cost aversion through posted-worker arbitrage; capital extractors gain unbounded arbitrage). Active enforcement is required to regulate the extraction mechanism (Posted Workers Directive, wage controls, social-contribution harmonization). Member states are constrained not trapped — they retain exit optionality via EU withdrawal, but the cost is civilizational (loss of market access, political isolation). No sunset clause on the fundamental asymmetry, though the EU framework iteratively tightens enforcement standards.
constraint_indexing:constraint_classification(welfare_coordination_reading, tangled_rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(continental))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(welfare_coordination_reading_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(welfare_coordination_reading, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(welfare_coordination_reading, TypeOther, context(agent_power(moderate), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(welfare_coordination_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

test(piton_threshold) :-
    domain_priors:theater_ratio(welfare_coordination_reading, TR),
    TR >= 0.70.

:- end_tests(welfare_coordination_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.54): Moderate-high. The constraint combines genuine labor-market coordination (reallocation to efficient wage levels, reduction of skill mismatches) with measurable extraction flows: posted workers lose 25–45% of nominal wages to exploitative contracting (EU labor inspectorates); receiving states bear 1–3% fiscal costs from migrant welfare eligibility post-exemption; sending states lose 0.5–1.5% of GDP in tax and remittance outflows. The extractiveness value reflects the combination: genuine coordination function (prevents measurement dropping below the rope threshold of ~0.45) but substantial asymmetric extraction (prevents classification as pure rope). Suppression (0.62): High. Multiple reinforcing barriers sustain the extraction: (1) posted workers have no legal recourse within receiving-state labor law; (2) labor inspectorates have limited resources and jurisdictional ambiguity (is this a posted-worker contract issue or a labor-market issue?); (3) remittance penalties and tax evasion by capital beneficiaries are structurally difficult to regulate; (4) member states cannot unilaterally enforce welfare eligibility rules against EU citizens; (5) language barriers and informal employment reduce worker capacity to report exploitation. Theater ratio (0.48): Moderate. The constraint's enforcement mechanism is genuine but incomplete — the Posted Workers Directive imposes real rules (wage minimums, cabotage restrictions, social-contribution rules), but implementation gaps and exemption-window gaps mean the regulatory theater is substantial but not dominant. Enforcement is functional enough to prevent classification as piton (theater > 0.70), but weak enough to permit continued extraction.
 *
 * PERSPECTIVAL GAP:
 *   The constraint demonstrates a five-way perspectival split reflecting the distribution of extraction. Posted workers see a snare (high extraction, no exit, maximum suppression). Receiving-state labor markets see tangled rope (genuine coordination benefit in accessing broader labor pool, but asymmetric extraction through wage depression and fiscal burden). Capital beneficiaries see rope (pure coordination — the mechanism solves their labor scarcity and cost problems). Sending-state fiscal systems see tangled rope (genuine coordination function: worker outflows reduce domestic unemployment, ease fiscal pressure, provide worker remittance income; but extraction operates through absence of compensation). EU enforcement machinery sees scaffold (the anti-dumping regulatory architecture has sunset logic — progressive harmonization of labor standards and wage floors reduces the extraction window over time). National welfare systems see piton (the autonomy doctrine persists through legal repetition but lacks operational force given free-movement arbitrage). The analytical institutional perspective sees tangled rope: coordination function is real and substantial, but asymmetric extraction is structural and requires active regulation to suppress.
 *
 * DIRECTIONALITY LOGIC:
 *   Directionality values (d) are derived from each agent's structural position relative to this specific constraint. Posted workers: d = 0.93 (full target — wages extract, contracts exploit, no exit below cost of return migration). Receiving-state labor markets: d = 0.58 (mixed — some benefit from labor supply elasticity, but wage depression and fiscal burden push toward victimhood). Capital beneficiaries: d = 0.12 (near-full beneficiary — cost savings are direct and immediate, exit option is arbitrage, extraction flows toward them). Sending-state fiscal systems: d = 0.72 (strong target — lose tax revenue and must maintain infrastructure; benefit incompletely through remittances). EU enforcement: d = 0.45 (symmetric — regulation imposes costs on capital beneficiaries but builds member-state capacity, so enforcement actors are neither pure beneficiary nor pure victim). National welfare systems: d = 0.65 (target — experience extraction through exemption windows and arbitrage, but benefit through reduced unemployment pressure). These d values feed into the sigmoid f(d), which produces effective extractiveness chi scaled by scope. For posted workers at regional scope (σ=0.9): chi ≈ 0.54 × 1.35 × 0.9 ≈ 0.65 (snare threshold). For capital at regional scope: chi ≈ 0.54 × -0.05 × 0.9 ≈ -0.02 (rope, pure coordination experienced).
 *
 * MANDATROPHY ANALYSIS:
 *   This constraint resolves mandatrophy by acknowledging that the 'correct' classification depends on which reading of the federation membership kernel is adopted. From within the coordination reading, tangled rope is correct: the constraint has genuine coordination function (labor reallocation, capital mobility) coupled with measurable asymmetric extraction (wage arbitrage, fiscal asymmetry). The mandatrophy is resolved by explicitly framing this as a contingent reading rather than a discovered fact. If the integration reading were adopted, the same empirical structure would classify as snare (free movement without welfare harmonization is pure extractive arbitrage). If the member sovereignty reading were adopted, the structure would classify as rope (each member state coordinates its own boundaries; what appears as extraction from the coordination-reading perspective is legitimate differentiation from the sovereignty-reading perspective). The framework shows that the classification depends on which foundational commitment (integration, sovereignty, or coordination) is taken as given. No single type is 'true' — the perspectival structure is the analytical content.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    welfare_access_responsibility_ambiguity,
    'Should welfare access responsibility lie with the nationality principle (sending state, where worker holds citizenship) or the residence principle (receiving state, where worker lives and works)?',
    'Comparative historical analysis of welfare-state development; mapping of which principle generates lower transaction costs and higher coverage; longitudinal tracking of labor-market outcomes under different responsibility allocations',
    'If nationality principle optimizes welfare: sending states should bear costs, extractiveness is lower (coordination cost distributed). If residence principle optimizes: receiving states should bear costs, extractiveness remains high (extraction persists). Current EU framework is hybrid and incoherent — posted workers exempt from both systems, creating the extraction window.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(welfare_access_responsibility_ambiguity, preference, 'Welfare responsibility allocation: nationality vs. residence principle').

omega_variable(
    posted_worker_abuse_measurement,
    'What proportion of posted-worker income is extracted through exploitative contract terms, wage theft, or substandard housing provisions relative to comparable domestic-worker income in the same role?',
    'Matched-pair wage audits (posted vs. domestic workers in identical roles); labor inspection audit trails; worker survey data on contract terms and deduction practices',
    'If abuse rate > 35%: snare classification for posted-worker perspective is robust. If abuse rate < 15%: arbitrage mechanism is functioning as intended market coordination, tangled-rope classification dominates. Current estimates (EU labor inspectorates, trade union surveys) range 25–45%, supporting snare classification.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(posted_worker_abuse_measurement, empirical, 'Measurement of extracted income from posted workers via exploitative terms').

omega_variable(
    fiscal_compensation_threshold,
    'At what rate of remittance from receiving state to sending state would the fiscal extraction mechanism be neutralized (both states break even on migrant labor)?',
    'Fiscal accounting models; estimation of tax revenue loss, welfare cost transfer, and infrastructure amortization; calibration against observed remittance and EU transfer payment flows',
    'If threshold < 8% of EU budget: coordination framework could neutralize extraction with modest redistribution. If threshold > 15%: extraction is structural and requires wholesale welfare-harmonization commitment to resolve.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(fiscal_compensation_threshold, empirical, 'Fiscal compensation rate needed to neutralize sending-state extraction').

omega_variable(
    kernel_reading_ambiguity_welfare_vs_integration,
    'Is EU free movement fundamentally a coordination mechanism for labor mobility (this reading) or a supranational integration project that should harmonize welfare systems across all member states (integration_reading sibling)?',
    'Examination of foundational EU treaty texts and jurisprudence (ECJ decisions on free movement, welfare eligibility); analysis of member-state political commitments; assessment of whether current framework is consistent with stated axioms of both readings',
    'If coordination reading is correct: welfare autonomy doctrine is coherent and extractiveness reflects coordination costs within bounded member-state autonomy. If integration reading is correct: current framework perpetuates a false dichotomy (autonomy + free movement) that generates extraction; true resolution requires supranational welfare harmonization. If member_sovereignty_reading is correct: welfare extraction is the price of EU membership and should be openly acknowledged rather than masked by autonomy rhetoric.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_reading_ambiguity_welfare_vs_integration, conceptual, 'Ambiguity over whether EU free movement is coordination (this reading) or integration project (sibling reading)').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(welfare_coordination_reading, 0, 10).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(posting_theater_t0, welfare_coordination_reading, theater_ratio, 0, 0.35).
narrative_ontology:measurement(posting_theater_t5, welfare_coordination_reading, theater_ratio, 5, 0.42).
narrative_ontology:measurement(posting_theater_t10, welfare_coordination_reading, theater_ratio, 10, 0.48).

% Extraction over time
narrative_ontology:measurement(posting_extraction_t0, welfare_coordination_reading, base_extractiveness, 0, 0.38).
narrative_ontology:measurement(posting_extraction_t5, welfare_coordination_reading, base_extractiveness, 5, 0.48).
narrative_ontology:measurement(posting_extraction_t10, welfare_coordination_reading, base_extractiveness, 10, 0.54).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(welfare_coordination_reading, resource_allocation).
narrative_ontology:affects_constraint(welfare_coordination_reading, integration_reading).
narrative_ontology:affects_constraint(welfare_coordination_reading, member_sovereignty_reading).
narrative_ontology:affects_constraint(welfare_coordination_reading, posted_workers_wage_suppression).
narrative_ontology:affects_constraint(welfare_coordination_reading, sending_state_fiscal_externality).

% DUAL FORMULATION NOTE:
% This constraint is part of a kernel reading triplet (federation_membership_kernel). The welfare_coordination_reading (this file) represents the EU's official institutional framing: free movement through coordination of autonomous states, not supranational harmonization. The integration_reading (separate file) represents the supranational harmonization alternative — it would classify the same empirical structure as snare (extraction without coordination). The member_sovereignty_reading represents the nation-state alternative — full welfare autonomy with restricted free movement. Each reading has different ε, different victim sets, and different terminal classification. They are not alternative measurements of one constraint; they are three structurally distinct constraints that instantiate the same federation_membership_kernel through different axioms.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(welfare_coordination_reading, moderate, 0.58).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
