% ============================================================================
% CONSTRAINT STORY: availability_heuristic
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-07-29
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_availability_heuristic, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: availability_heuristic
 *   human_readable: Availability Heuristic (as exploited by information systems)
 *   domain: cognitive/social/economic
 *
 * SUMMARY:
 *   The availability heuristic is a cognitive shortcut where individuals
 *   judge the frequency or likelihood of an event by the ease with which
 *   examples come to mind. While a natural part of human cognition, this
 *   heuristic is systematically exploited by modern information systems
 *   (social media, news algorithms, advertising networks). These systems
 *   amplify vivid, recent, and emotionally charged information, creating a
 *   significant gap between an individual's perceived reality and statistical
 *   reality. This manufactured availability extracts attention for profit and
 *   shapes public opinion for political gain.
 *
 * KEY AGENTS:
 *   - General Public: Primary target (powerless/trapped) — Their perception of risk and reality is distorted, leading to poor decision-making and heightened anxiety.
 *   - Media Platforms & Advertisers: Primary beneficiaries (institutional/arbitrage) — Profit by capturing and selling the attention generated by exploiting the heuristic.
 *   - Political Campaigns: Secondary beneficiaries (organized/arbitrage) — Manipulate public opinion and voter behavior by making certain issues or threats feel more salient.
 *   - Evidence-Based Policymakers: Victims (organized/constrained) — Their ability to govern based on statistical reality is undermined by a public reacting to manufactured crises.
 *   - Rational Discourse: Abstract victim (powerless/trapped) — The quality of public debate degrades as it becomes dominated by emotional reaction rather than reasoned analysis.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(availability_heuristic, 0.68).
domain_priors:suppression_score(availability_heuristic, 0.75).
domain_priors:theater_ratio(availability_heuristic, 0.6).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(availability_heuristic, extractiveness, 0.68).
narrative_ontology:constraint_metric(availability_heuristic, suppression_requirement, 0.75).
narrative_ontology:constraint_metric(availability_heuristic, theater_ratio, 0.6).

% --- Constraint claim ---
narrative_ontology:constraint_claim(availability_heuristic, snare).
narrative_ontology:human_readable(availability_heuristic, "Availability Heuristic (as exploited by information systems)").
narrative_ontology:topic_domain(availability_heuristic, "cognitive/social/economic").

domain_priors:requires_active_enforcement(availability_heuristic).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(availability_heuristic, media_platforms).
narrative_ontology:constraint_beneficiary(availability_heuristic, advertisers).
narrative_ontology:constraint_beneficiary(availability_heuristic, political_campaigns).
narrative_ontology:constraint_victim(availability_heuristic, general_public).
narrative_ontology:constraint_victim(availability_heuristic, rational_discourse).
narrative_ontology:constraint_victim(availability_heuristic, evidence_based_policymakers).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% PERSPECTIVE 1: THE GENERAL PUBLIC (SNARE) — Individually trapped within information ecosystems that algorithmically amplify vivid, emotionally charged, and recent events. This extracts attention and shapes beliefs, making exit from the distorted perception of reality nearly impossible. d≈0.95, f(d)≈1.42, σ=1.2 → χ≈1.16. This extreme effective extraction firmly classifies the constraint as a Snare.
constraint_indexing:constraint_classification(availability_heuristic, snare,
    context(agent_power(powerless),
            time_horizon(immediate),
            exit_options(trapped),
            spatial_scope(global))).

% PERSPECTIVE 2: THE MEDIA PLATFORM (ROPE) — Experiences the system as a pure coordination mechanism for matching users with 'engaging' content. The extraction of attention is framed as a fair value exchange for the service. From this position, the heuristic is a tool for efficient market-making. d≈0.05, f(d)≈-0.12, σ=1.2 → χ≈-0.10. Negative effective extraction signifies a net beneficiary.
constraint_indexing:constraint_classification(availability_heuristic, rope,
    context(agent_power(institutional),
            time_horizon(immediate),
            exit_options(arbitrage),
            spatial_scope(global))).

% PERSPECTIVE 3: THE COGNITIVE SCIENTIST (TANGLED ROPE) — The analytical view recognizes both the coordination function (rapidly disseminating salient information) and the severe, asymmetric extraction (systematic distortion of risk perception for profit). The underlying heuristic is a neutral cognitive mechanism, but its industrial-scale exploitation creates a classic Tangled Rope. d≈0.72, f(d)≈1.15, σ=1.2 → χ≈0.94.
constraint_indexing:constraint_classification(availability_heuristic, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

% PERSPECTIVE 4: THE POLICYMAKER (TANGLED ROPE) — Constrained by a public whose priorities are shaped by the heuristic, making it difficult to address statistically significant but less 'available' threats. They are victims of the constraint but must also work within it, using communication strategies that acknowledge public perception. d≈0.55, f(d)≈0.75, σ=1.0 → χ≈0.51.
constraint_indexing:constraint_classification(availability_heuristic, tangled_rope,
    context(agent_power(organized),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(national))).

% PERSPECTIVE 5: THE EVOLUTIONARY PSYCHOLOGIST (MOUNTAIN) — This perspective frames the heuristic as a fixed, immutable feature of human cognition, an evolved adaptation that is unchangeable. This naturalizes the constraint, viewing its effects as an inevitable consequence of our mental hardware. The engine will flag this as a false summit, as the high ε and suppression values are properties of the *exploitative system*, not the cognitive bias in isolation.
constraint_indexing:constraint_classification(availability_heuristic, mountain,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(universal))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(availability_heuristic_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(availability_heuristic, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(availability_heuristic, TypeOther, context(agent_power(institutional), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(availability_heuristic, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(availability_heuristic_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (ε=0.68): High. The value is extracted in the form of attention, which is then monetized or converted into political capital. The asymmetry is severe: platforms gain immense value, while the public's decision-making quality is degraded. Suppression (0.75): High. Algorithmic feeds and filter bubbles actively suppress less sensational, more nuanced, or statistically representative information. It is structurally difficult for a typical user to seek out and weigh a balanced set of information. Theater Ratio (0.60): The presentation of information is optimized for engagement (the 'theater') over accuracy or context (the 'function'). Headlines, thumbnails, and content selection are performative acts designed to trigger a cognitive shortcut.
 *
 * PERSPECTIVAL GAP:
 *   The gap is profound. Beneficiaries (platforms) see a benign Rope, a tool for coordinating user attention with relevant content. The primary victims (the public) are caught in a Snare, their cognitive biases turned against them. The analytical observer sees a Tangled Rope, acknowledging the system's dual role in both disseminating information and extractively distorting perception. A different analytical view (evolutionary psychology) might misclassify it as an unchangeable Mountain, a naturalization fallacy the framework is designed to detect by pointing to the high, non-natural ε and suppression scores.
 *
 * DIRECTIONALITY LOGIC:
 *   The directionality is derived from the clear beneficiary/victim structure. Media Platforms, as beneficiaries with arbitrage exit, have a very low directionality (d), resulting in negative effective extraction (χ < 0). The General Public, as victims with trapped exit, have a very high directionality (d≈1.0), resulting in an effective extraction (χ) that is significantly amplified from the base ε, confirming the Snare classification from their perspective.
 *
 * MANDATROPHY ANALYSIS:
 *   This constraint story resolves a key mandatrophy: distinguishing a natural cognitive bias from its artificial, industrial-scale exploitation. A naive analysis might label the heuristic itself a Mountain ('it's just how people think'). The DR framework avoids this by focusing on the *system* that exploits it. The high ε and suppression values are not properties of the human mind; they are properties of the technological and economic system built around it. This correctly identifies the structure as a contingent, extractive arrangement (Snare/Tangled Rope) rather than a natural law.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    intent_vs_emergence,
    'Is the large-scale exploitation of the availability heuristic a result of deliberate strategic design by platforms or an emergent property of optimizing for engagement metrics?',
    'Analysis of internal platform design documents, A/B test results for ranking algorithms, and interviews with system architects.',
    'If primarily deliberate, the Snare classification is strengthened. If primarily emergent, the Tangled Rope classification becomes more accurate from the analytical perspective, as the ''coordination'' function (engagement) is the driver.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(intent_vs_emergence, empirical, 'Distinguishing between deliberate exploitation and emergent properties of engagement optimization.').

omega_variable(
    cognitive_malleability,
    'To what extent can individuals be trained to consciously override the availability heuristic, even when immersed in an amplifying information system?',
    'Longitudinal studies on the effectiveness of media literacy and cognitive bias training programs.',
    'High malleability would suggest a Scaffold-based intervention is possible, reducing the constraint''s power. Low malleability reinforces the Snare classification for individuals.',
    confidence_without_resolution(low)
).

narrative_ontology:omega_variable(cognitive_malleability, empirical, 'Assessing the potential for training to mitigate the heuristic''s effects.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(availability_heuristic, 0, 30).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(avai_tr_t0, availability_heuristic, theater_ratio, 0, 0.2).
narrative_ontology:measurement(avai_tr_t15, availability_heuristic, theater_ratio, 15, 0.4).
narrative_ontology:measurement(avai_tr_t30, availability_heuristic, theater_ratio, 30, 0.6).

% Extraction over time
narrative_ontology:measurement(avai_be_t0, availability_heuristic, base_extractiveness, 0, 0.15).
narrative_ontology:measurement(avai_be_t15, availability_heuristic, base_extractiveness, 15, 0.45).
narrative_ontology:measurement(avai_be_t30, availability_heuristic, base_extractiveness, 30, 0.68).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(availability_heuristic, information_standard).
narrative_ontology:affects_constraint(availability_heuristic, political_polarization).
narrative_ontology:affects_constraint(availability_heuristic, financial_market_volatility).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
