% ============================================================================
% CONSTRAINT STORY: academic_peer_review_gatekeeping_u3_exp_r5
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-05-15
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_academic_peer_review_gatekeeping_u3_exp_r5, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: academic_peer_review_gatekeeping_u3_exp_r5
 *   human_readable: Academic Peer Review and Journal Gatekeeping
 *   domain: economic/social/technological
 *
 * SUMMARY:
 *   The academic publishing system relies on researchers, primarily at
 *   publicly-funded institutions, to provide free labor in the form of
 *   research, writing, peer review, and editing. For-profit publishers bundle
 *   this labor into journals, which they sell back to university libraries at
 *   extremely high subscription costs. This creates a cycle where value
 *   generated by the academic community is extracted by third-party
 *   corporations.
 *
 * KEY AGENTS:
 *   - Junior Professors: Primary target (powerless/trapped) - Must 'publish or perish' to gain tenure.
 *   - Journal Publishers: Primary beneficiary (institutional/arbitrage) - Capture value from free labor and market access.
 *   - University Libraries/Consortia: Victim and Auditor (institutional/constrained) - Forced to pay high fees, possess analytical view of the system's costs.
 *   - Tenured Senior Academics: Secondary beneficiary/enforcer (powerful/mobile) - Uphold the system that grants them prestige and gatekeeping power.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(academic_peer_review_gatekeeping_u3_exp_r5, 0.68).
domain_priors:suppression_score(academic_peer_review_gatekeeping_u3_exp_r5, 0.75).
domain_priors:theater_ratio(academic_peer_review_gatekeeping_u3_exp_r5, 0.4).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(academic_peer_review_gatekeeping_u3_exp_r5, extractiveness, 0.68).
narrative_ontology:constraint_metric(academic_peer_review_gatekeeping_u3_exp_r5, suppression_requirement, 0.75).
narrative_ontology:constraint_metric(academic_peer_review_gatekeeping_u3_exp_r5, theater_ratio, 0.4).

% --- Constraint claim ---
narrative_ontology:constraint_claim(academic_peer_review_gatekeeping_u3_exp_r5, tangled_rope).
narrative_ontology:human_readable(academic_peer_review_gatekeeping_u3_exp_r5, "Academic Peer Review and Journal Gatekeeping").
narrative_ontology:topic_domain(academic_peer_review_gatekeeping_u3_exp_r5, "economic/social/technological").

domain_priors:requires_active_enforcement(academic_peer_review_gatekeeping_u3_exp_r5).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(academic_peer_review_gatekeeping_u3_exp_r5, for_profit_journal_publishers).
narrative_ontology:constraint_beneficiary(academic_peer_review_gatekeeping_u3_exp_r5, tenured_senior_academics).
narrative_ontology:constraint_victim(academic_peer_review_gatekeeping_u3_exp_r5, junior_professors).
narrative_ontology:constraint_victim(academic_peer_review_gatekeeping_u3_exp_r5, university_libraries).
narrative_ontology:constraint_victim(academic_peer_review_gatekeeping_u3_exp_r5, the_general_public).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% Must publish in high-prestige journals to secure tenure, providing free labor (research, writing, reviewing) into a system that extracts value from them and their institution.
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u3_exp_r5, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(global))).

% Views the system as a valuable coordination mechanism for vetting and disseminating scientific knowledge, a service for which they are compensated. The extractive nature is seen as a standard business model.
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u3_exp_r5, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(global))).

% Simultaneously a victim (paying exorbitant subscription fees) and an enforcer (upholding tenure requirements based on journal prestige). They are constrained by the prestige economy they help perpetuate.
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u3_exp_r5, tangled_rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(national))).

% Recognizes both the genuine coordination function of peer review and the highly extractive, asymmetric nature of the publisher business model that has captured it.
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u3_exp_r5, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(academic_peer_review_gatekeeping_u3_exp_r5_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u3_exp_r5, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u3_exp_r5, TypeOther, context(agent_power(institutional), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(academic_peer_review_gatekeeping_u3_exp_r5, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(academic_peer_review_gatekeeping_u3_exp_r5_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.68) is high due to the direct conversion of free academic labor into corporate profit. Suppression (0.75) is high because the 'publish or perish' tenure system and the concentration of prestige in a few key journals create a powerful lock-in effect, making alternative publishing models difficult to adopt for career-focused academics.
 *
 * PERSPECTIVAL GAP:
 *   A significant gap exists between the publisher, who sees a Rope (a service coordinating scientific discourse), and the junior academic, who experiences a Snare (a coercive labor system they cannot escape without career penalty). The analytical view acknowledges both facets, classifying it as a Tangled Rope.
 *
 * DIRECTIONALITY LOGIC:
 *   The flow of value is unidirectional: from academics and their institutions to publishers. Publishers are the clear beneficiaries. Junior professors, university libraries (and their funders), and the general public (denied access to research they funded) are the victims. The system requires active enforcement through the university tenure and promotion process, which ties career advancement to publication in these specific venues.
 *
 * MANDATROPHY ANALYSIS:
 *   This constraint is a canonical example of a Tangled Rope, preventing misclassification. Labeling it a pure Snare would ignore the very real, and socially valuable, coordination function of organizing and vetting scientific literature. Labeling it a Rope would ignore the immense, asymmetric extraction and coercion involved. The Tangled Rope classification correctly identifies that a legitimate coordination mechanism has been captured by a highly extractive rent-seeking structure.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    prestige_as_quality_proxy,
    'Is the prestige of top-tier journals a reliable proxy for research quality, thus justifying the system's costs, or is it a self-perpetuating brand effect that primarily serves the gatekeepers?',
    'Longitudinal analysis comparing the citation impact and retraction rates of research in top-tier journals versus high-quality, peer-reviewed open-access platforms.',
    'If prestige is a reliable quality proxy, the system retains a strong coordination function (Tangled Rope). If it is primarily brand, the system is closer to a pure Snare.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(prestige_as_quality_proxy, empirical, 'Whether journal prestige is a functional quality signal or a rent-seeking brand.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(academic_peer_review_gatekeeping_u3_exp_r5, 1970, 2020).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(acad_tr_t1970, academic_peer_review_gatekeeping_u3_exp_r5, theater_ratio, 1970, 0.1).
narrative_ontology:measurement(acad_tr_t1995, academic_peer_review_gatekeeping_u3_exp_r5, theater_ratio, 1995, 0.25).
narrative_ontology:measurement(acad_tr_t2020, academic_peer_review_gatekeeping_u3_exp_r5, theater_ratio, 2020, 0.4).

% Extraction over time
narrative_ontology:measurement(acad_be_t1970, academic_peer_review_gatekeeping_u3_exp_r5, base_extractiveness, 1970, 0.25).
narrative_ontology:measurement(acad_be_t1995, academic_peer_review_gatekeeping_u3_exp_r5, base_extractiveness, 1995, 0.45).
narrative_ontology:measurement(acad_be_t2020, academic_peer_review_gatekeeping_u3_exp_r5, base_extractiveness, 2020, 0.68).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(academic_peer_review_gatekeeping_u3_exp_r5, information_standard).
narrative_ontology:affects_constraint(academic_peer_review_gatekeeping_u3_exp_r5, university_tenure_process).
narrative_ontology:affects_constraint(academic_peer_review_gatekeeping_u3_exp_r5, public_trust_in_science).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
