% ============================================================================
% CONSTRAINT STORY: academic_peer_review_gatekeeping_u2_exp_r1
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-05-21
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_academic_peer_review_gatekeeping_u2_exp_r1, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: academic_peer_review_gatekeeping_u2_exp_r1
 *   human_readable: Academic Peer Review and Journal Gatekeeping
 *   domain: economic/social/technological
 *
 * SUMMARY:
 *   The academic publishing system relies on researchers and academics
 *   providing free labor (writing articles, conducting peer reviews) to
 *   for-profit publishing houses. These publishers then package the research
 *   and sell it back at extremely high subscription fees to the very
 *   institutions (universities) that employ the researchers. This creates a
 *   cycle where value generated by a publicly or institutionally-funded
 *   commons is captured and privatized by third-party gatekeepers.
 *
 * KEY AGENTS:
 *   - Junior Professors: Primary target (powerless/trapped) - Career progression (tenure) is directly tied to publishing in high-prestige, high-cost journals.
 *   - For-Profit Journal Publishers: Primary beneficiary (institutional/arbitrage) - Capture immense value from free academic labor and institutional subscription fees.
 *   - University Libraries/Consortia: Victim/Auditor (institutional/constrained) - Bear the direct financial cost of the system, often with limited power to negotiate.
 *   - University Administration: Enforcer (institutional/constrained) - Upholds the 'publish or perish' standards that fuel the system, while also paying the bills.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(academic_peer_review_gatekeeping_u2_exp_r1, 0.68).
domain_priors:suppression_score(academic_peer_review_gatekeeping_u2_exp_r1, 0.75).
domain_priors:theater_ratio(academic_peer_review_gatekeeping_u2_exp_r1, 0.6).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(academic_peer_review_gatekeeping_u2_exp_r1, extractiveness, 0.68).
narrative_ontology:constraint_metric(academic_peer_review_gatekeeping_u2_exp_r1, suppression_requirement, 0.75).
narrative_ontology:constraint_metric(academic_peer_review_gatekeeping_u2_exp_r1, theater_ratio, 0.6).

% --- Constraint claim ---
narrative_ontology:constraint_claim(academic_peer_review_gatekeeping_u2_exp_r1, tangled_rope).
narrative_ontology:human_readable(academic_peer_review_gatekeeping_u2_exp_r1, "Academic Peer Review and Journal Gatekeeping").
narrative_ontology:topic_domain(academic_peer_review_gatekeeping_u2_exp_r1, "economic/social/technological").

domain_priors:requires_active_enforcement(academic_peer_review_gatekeeping_u2_exp_r1).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(academic_peer_review_gatekeeping_u2_exp_r1, for_profit_journal_publishers).
narrative_ontology:constraint_victim(academic_peer_review_gatekeeping_u2_exp_r1, junior_professors).
narrative_ontology:constraint_victim(academic_peer_review_gatekeeping_u2_exp_r1, university_libraries).
narrative_ontology:constraint_victim(academic_peer_review_gatekeeping_u2_exp_r1, the_public).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% Must publish in high-prestige journals to secure tenure, providing free labor (writing, reviewing) and facing career-ending consequences for non-participation.
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u2_exp_r1, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(global))).

% Views the system as a valuable coordination mechanism for vetting and disseminating scientific knowledge, from which it derives legitimate profit.
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u2_exp_r1, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(global))).

% Recognizes both the genuine coordination function of peer review and the severe, asymmetric extraction of value by publishers from the academic ecosystem.
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u2_exp_r1, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

% Simultaneously a victim (via massive library subscription costs) and an enforcer (via tenure policies that mandate participation in the prestige economy).
constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u2_exp_r1, tangled_rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(national))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(academic_peer_review_gatekeeping_u2_exp_r1_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u2_exp_r1, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(academic_peer_review_gatekeeping_u2_exp_r1, TypeOther, context(agent_power(institutional), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(academic_peer_review_gatekeeping_u2_exp_r1, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(academic_peer_review_gatekeeping_u2_exp_r1_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Base extractiveness (0.68) is high due to the model of free labor input and high-cost access output. Suppression (0.75) is severe because the academic prestige and tenure system makes alternatives (like pre-print servers or new open-access journals) career risks for junior academics, effectively locking them into the established system.
 *
 * PERSPECTIVAL GAP:
 *   The gap is stark. For the publisher, it's a Rope coordinating the complex task of scientific validation. For the junior academic, it's a Snare where they must surrender their labor and intellectual property for a chance at career survival. The analytical view, a Tangled Rope, acknowledges the system performs a real coordination function but has been captured by a highly extractive business model.
 *
 * DIRECTIONALITY LOGIC:
 *   Directionality is unambiguous. Value flows from academics (labor) and their institutions (cash) to the publishers. The publishers are the beneficiaries. The entire academic ecosystem, including the public who ultimately funds much of the research, are the victims.
 *
 * MANDATROPHY ANALYSIS:
 *   Classifying this as a pure Snare would miss the fact that the system *does* coordinate peer review and create a (flawed) signal of legitimacy. Classifying it as a Rope would ignore the coercive, extractive reality for participants. The Tangled Rope classification is essential to capture this duality: a necessary coordination function that has become a vehicle for immense, asymmetric rent-seeking.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    prestige_vs_quality,
    'Is the gatekeeping function of high-prestige journals a necessary proxy for scientific quality, or is it a manufactured commodity that primarily serves to justify extraction?',
    'Large-scale longitudinal study comparing the predictive validity and retraction rates of articles in high-cost journals versus well-regarded open-access platforms.',
    'If prestige is a reliable proxy for quality, the system is a costly but functional Tangled Rope. If not, it is a Snare masquerading as a coordination mechanism.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(prestige_vs_quality, empirical, 'Whether the system's cost ensures quality or extracts rent via prestige.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(academic_peer_review_gatekeeping_u2_exp_r1, 1985, 2025).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(acad_tr_t1985, academic_peer_review_gatekeeping_u2_exp_r1, theater_ratio, 1985, 0.2).
narrative_ontology:measurement(acad_tr_t2005, academic_peer_review_gatekeeping_u2_exp_r1, theater_ratio, 2005, 0.45).
narrative_ontology:measurement(acad_tr_t2025, academic_peer_review_gatekeeping_u2_exp_r1, theater_ratio, 2025, 0.6).

% Extraction over time
narrative_ontology:measurement(acad_be_t1985, academic_peer_review_gatekeeping_u2_exp_r1, base_extractiveness, 1985, 0.3).
narrative_ontology:measurement(acad_be_t2005, academic_peer_review_gatekeeping_u2_exp_r1, base_extractiveness, 2005, 0.55).
narrative_ontology:measurement(acad_be_t2025, academic_peer_review_gatekeeping_u2_exp_r1, base_extractiveness, 2025, 0.68).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(academic_peer_review_gatekeeping_u2_exp_r1, information_standard).
narrative_ontology:affects_constraint(academic_peer_review_gatekeeping_u2_exp_r1, university_tenure_process).
narrative_ontology:affects_constraint(academic_peer_review_gatekeeping_u2_exp_r1, research_funding_allocation).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
