% ============================================================================
% CONSTRAINT STORY: subscription_economy_model_u3_str_r1
% ============================================================================
% Version: 2.1 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2024-07-29
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_subscription_economy_model_u3_str_r1, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: subscription_economy_model_u3_str_r1
 *   human_readable: Subscription Economy Model
 *   domain: economic/technological
 *
 * SUMMARY:
 *   This constraint describes the widespread business model shift from
 *   one-time product sales (perpetual licenses) to recurring subscription
 *   fees. While offering a coordination benefit (continuous updates, service
 *   access), it asymmetrically extracts value by creating consumer inertia,
 *   making cancellation difficult (a 'hassle tax'), and revoking ownership
 *   rights. The model is actively enforced by Digital Rights Management (DRM)
 *   and the strategic suppression of non-subscription alternatives.
 *
 * KEY AGENTS:
 *   - Individual Consumers: Primary target (powerless/trapped) — bear the costs of subscription fatigue, loss of ownership, and cancellation friction.
 *   - Subscription-based Corporations: Primary beneficiary (institutional/arbitrage) — benefit from predictable recurring revenue and increased customer lifetime value.
 *   - Platform Investors: Secondary beneficiary (institutional/arbitrage) — value the predictable, high-margin revenue streams generated by subscription models.
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(subscription_economy_model_u3_str_r1, 0.68).
domain_priors:suppression_score(subscription_economy_model_u3_str_r1, 0.75).
domain_priors:theater_ratio(subscription_economy_model_u3_str_r1, 0.25).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(subscription_economy_model_u3_str_r1, extractiveness, 0.68).
narrative_ontology:constraint_metric(subscription_economy_model_u3_str_r1, suppression_requirement, 0.75).
narrative_ontology:constraint_metric(subscription_economy_model_u3_str_r1, theater_ratio, 0.25).

% --- Constraint claim ---
narrative_ontology:constraint_claim(subscription_economy_model_u3_str_r1, tangled_rope).
narrative_ontology:human_readable(subscription_economy_model_u3_str_r1, "Subscription Economy Model").
narrative_ontology:topic_domain(subscription_economy_model_u3_str_r1, "economic/technological").

domain_priors:requires_active_enforcement(subscription_economy_model_u3_str_r1).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(subscription_economy_model_u3_str_r1, subscription_based_corporations).
narrative_ontology:constraint_beneficiary(subscription_economy_model_u3_str_r1, platform_investors).
narrative_ontology:constraint_victim(subscription_economy_model_u3_str_r1, individual_consumers).
narrative_ontology:constraint_victim(subscription_economy_model_u3_str_r1, small_businesses_dependent_on_tools).

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% For a consumer, the high switching costs, loss of perpetual access, and 'subscription fatigue' make this model feel like a trap with no viable alternatives.
constraint_indexing:constraint_classification(subscription_economy_model_u3_str_r1, snare,
    context(agent_power(powerless),
            time_horizon(biographical),
            exit_options(trapped),
            spatial_scope(national))).

% For the corporation, this is a pure coordination tool to smooth revenue, fund continuous development, and maintain a direct customer relationship. Extraction is viewed as fair payment for ongoing service.
constraint_indexing:constraint_classification(subscription_economy_model_u3_str_r1, rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(global))).

% The analytical view recognizes both the genuine coordination function (service delivery) and the asymmetric extraction enabled by consumer inertia and the suppression of ownership models.
constraint_indexing:constraint_classification(subscription_economy_model_u3_str_r1, tangled_rope,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(global))).

% From the U3 position, the model is a strategic tool. The extractive elements are acknowledged but seen as a feature for ensuring market stability and predictable growth, not a bug. It's a tangled rope, but one that is managed, not suffered.
constraint_indexing:constraint_classification(subscription_economy_model_u3_str_r1, tangled_rope,
    context(agent_power(institutional),
            time_horizon(generational),
            exit_options(arbitrage),
            spatial_scope(national))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(subscription_economy_model_u3_str_r1_tests).

test(perspectival_gap) :-
    constraint_indexing:constraint_classification(subscription_economy_model_u3_str_r1, TypePowerless, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(subscription_economy_model_u3_str_r1, TypeOther, context(agent_power(institutional), _, _, _)),
    TypePowerless \= TypeOther.

test(extraction_signature) :-
    domain_priors:base_extractiveness(subscription_economy_model_u3_str_r1, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(subscription_economy_model_u3_str_r1_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Base extractiveness (0.68) is high, reflecting the value captured through inertia, bundling, price hikes, and cancellation friction, which goes beyond the direct value of the service. Suppression (0.75) is also high because corporations actively phase out perpetual licenses and use DRM to prevent ownership, leaving consumers with few alternatives.
 *
 * PERSPECTIVAL GAP:
 *   A significant gap exists between the consumer, who experiences a Snare due to being trapped in ever-increasing recurring payments with no equity, and the corporation, which sees a perfect Rope for coordinating revenue with service delivery. The analytical observer sees the Tangled Rope, acknowledging both sides of the structure.
 *
 * DIRECTIONALITY LOGIC:
 *   The flow of value is directed from a broad base of individual consumers to a concentrated group of corporations and their investors. Consumers are the victims as they lose asset ownership and are subjected to a continuous payment obligation. Corporations are the beneficiaries, gaining financial stability and market control.
 *
 * MANDATROPHY ANALYSIS:
 *   The Tangled Rope classification is crucial for avoiding mandatrophy. A simplistic analysis might label the model a pure Snare (ignoring the real services provided) or a pure Rope (ignoring the coercive and extractive elements). The Tangled Rope correctly identifies that a genuine coordination function has been coupled with a powerful extraction mechanism, which is the defining feature of the modern subscription economy.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    inertia_vs_value,
    'Is the recurring revenue primarily compensation for continuous value delivery (updates, service) or is it rent extracted from consumer inertia and high cancellation friction?',
    'Comparative analysis of user engagement data versus churn rates, correlated with the measured difficulty of the cancellation process across different platforms.',
    'If primarily value-driven, the constraint's base extractiveness would be lower, pushing it towards a Rope. If primarily inertia-driven, it confirms the Snare/Tangled Rope classification.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(inertia_vs_value, empirical, 'Distinguishing between value-based recurring payment and inertia-based rent extraction.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(subscription_economy_model_u3_str_r1, 2005, 2025).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(subs_tr_t2005, subscription_economy_model_u3_str_r1, theater_ratio, 2005, 0.1).
narrative_ontology:measurement(subs_tr_t2015, subscription_economy_model_u3_str_r1, theater_ratio, 2015, 0.15).
narrative_ontology:measurement(subs_tr_t2025, subscription_economy_model_u3_str_r1, theater_ratio, 2025, 0.25).

% Extraction over time
narrative_ontology:measurement(subs_be_t2005, subscription_economy_model_u3_str_r1, base_extractiveness, 2005, 0.2).
narrative_ontology:measurement(subs_be_t2015, subscription_economy_model_u3_str_r1, base_extractiveness, 2015, 0.5).
narrative_ontology:measurement(subs_be_t2025, subscription_economy_model_u3_str_r1, base_extractiveness, 2025, 0.68).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(subscription_economy_model_u3_str_r1, resource_allocation).
narrative_ontology:affects_constraint(subscription_economy_model_u3_str_r1, digital_ownership_rights).
narrative_ontology:affects_constraint(subscription_economy_model_u3_str_r1, right_to_repair).

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
