% ============================================================================
% CONSTRAINT STORY: total_war_possibility_space__space_contraction_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-06-11
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_total_war_possibility_space__space_contraction_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:suppression_profile/2,
    constraint_indexing:constraint_classification/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:fixing_cost_class/2,
    domain_priors:emerges_naturally/1,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: total_war_possibility_space__space_contraction_reading
 *   human_readable: Nuclear Closure of the Total-War Planning Space (Space-Contraction Reading)
 *   domain: international relations/strategic studies
 *
 * SUMMARY:
 *   A thermonuclear-revolution claim read through its strongest structural
 *   interpretation: after roughly a decade of delivery-system maturation (T0
 *   = 1945; interval measured in years since), total war between great powers
 *   — society-wide mobilization prosecuted to unlimited aims — ceased to be
 *   an option planners could coherently entertain, not because it was priced
 *   too high (the deterrence reading) or forbidden by norm (the taboo
 *   reading), but because the plan defeats its own objective: a war aimed at
 *   societal victory cannot be won by a society the war annihilates. This
 *   file instantiates only the space-contraction reading as a clean,
 *   epsilon-invariant constraint; the sibling readings are separate stories
 *   linked through network.affects_constraints. The claimed type is mountain:
 *   the closure is presented as a material-logical limit with zero degrees of
 *   freedom — no seat administers it, none could repeal it short of
 *   dismantling global second-strike survivability, and it would persist
 *   whether or not anyone defended it. The authored metrics independently
 *   describe near-zero extraction and suppression, near-total accessibility
 *   collapse, negligible resistance, and a slowly rising theater ratio
 *   generated by the vestigial planning apparatus downstream of the closure —
 *   the atrophy the reading predicts. Claim and metrics are authored
 *   independently; the engine computes per-seat classifications from the
 *   structural data. KEY AGENTS (by structural relationship): -
 *   great_power_general_staffs: bearing seat (institutional/identity_locked)
 *   — inherits planning institutions whose founding object exited the option
 *   set - strategic_studies_academia: constitutive beneficiary
 *   (moderate/mobile) — the discipline exists because the space closed -
 *   nuclear_armed_state_leaderships: ambient beneficiary
 *   (powerful/constrained) — receive the closure's output without
 *   administering it - civil_defense_establishments: bearing seat
 *   (organized/constrained) — maintain vestigial societal-preparedness
 *   programs - strategic_theory_historians: analytical observer — weighs
 *   rival accounts of the closure from outside every operating seat
 *
 * KEY AGENTS:
 *   - great_power_general_staffs: bearing seat (institutional/identity_locked) — bears the atrophy of the planning tradition the closure rendered vestigial
 *   - strategic_studies_academia: constitutive beneficiary (moderate/mobile) — professional field founded on the closed space
 *   - nuclear_armed_state_leaderships: ambient beneficiary (powerful/constrained) — govern inside the closure without administering it
 *   - civil_defense_establishments: bearing seat (organized/constrained) — carry vestigial preparedness programs sized for a deleted event class
 *   - strategic_theory_historians: analytical observer (analytical/analytical) — sees the full structure and adjudicates between rival mechanisms
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(total_war_possibility_space__space_contraction_reading, 0.05).
domain_priors:suppression_score(total_war_possibility_space__space_contraction_reading, 0.02).
domain_priors:theater_ratio(total_war_possibility_space__space_contraction_reading, 0.45).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, extractiveness, 0.05).
narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, suppression_requirement, 0.02).
narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, theater_ratio, 0.45).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, accessibility_collapse, 0.92).
narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, resistance, 0.06).

% --- Constraint claim ---
narrative_ontology:constraint_claim(total_war_possibility_space__space_contraction_reading, mountain).
narrative_ontology:human_readable(total_war_possibility_space__space_contraction_reading, "Nuclear Closure of the Total-War Planning Space (Space-Contraction Reading)").
narrative_ontology:topic_domain(total_war_possibility_space__space_contraction_reading, "international relations/strategic studies").

domain_priors:emerges_naturally(total_war_possibility_space__space_contraction_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(total_war_possibility_space__space_contraction_reading, 'acc4409a-e235-4d1c-ad51-730d1583f679').
narrative_ontology:cs_kernel_codification('acc4409a-e235-4d1c-ad51-730d1583f679', distributed).
narrative_ontology:cs_authority_grounding('acc4409a-e235-4d1c-ad51-730d1583f679', distributed).
narrative_ontology:cs_reading_relation('acc4409a-e235-4d1c-ad51-730d1583f679', total_war_possibility_space__deterrence_equilibrium_reading, forecloses).
narrative_ontology:cs_reading_relation('acc4409a-e235-4d1c-ad51-730d1583f679', total_war_possibility_space__nuclear_taboo_reading, coexists_with).
narrative_ontology:cs_axiom('acc4409a-e235-4d1c-ad51-730d1583f679', foundational, total_war_outside_strategic_possibility_space).
narrative_ontology:cs_axiom_status(total_war_outside_strategic_possibility_space, holdable).
narrative_ontology:cs_axiom_grounding('acc4409a-e235-4d1c-ad51-730d1583f679', total_war_outside_strategic_possibility_space, empirically_contingent).
narrative_ontology:cs_axiom('acc4409a-e235-4d1c-ad51-730d1583f679', secondary, strategic_thinkability_tracks_material_possibility).
narrative_ontology:cs_axiom_status(strategic_thinkability_tracks_material_possibility, holdable).
narrative_ontology:cs_axiom_grounding('acc4409a-e235-4d1c-ad51-730d1583f679', strategic_thinkability_tracks_material_possibility, empirically_contingent).
narrative_ontology:cs_reference_frame('acc4409a-e235-4d1c-ad51-730d1583f679', thermonuclear_closed_planning_space).
narrative_ontology:cs_drift_state('acc4409a-e235-4d1c-ad51-730d1583f679', contemporary_great_power_competition_era, gap(practice_drift, minor, false)).
narrative_ontology:cs_created_at('acc4409a-e235-4d1c-ad51-730d1583f679', '').
narrative_ontology:cs_kernel_id(total_war_possibility_space__space_contraction_reading, total_war_possibility_space).

% --- Structural relationships ---
% Derived from stakeholders[] roles (beneficiary->beneficiary, payer->victim;
% agent-gated; excluded derives nothing; deduped against the authored arrays).
narrative_ontology:constraint_beneficiary(total_war_possibility_space__space_contraction_reading, strategic_studies_academia).
narrative_ontology:constraint_beneficiary(total_war_possibility_space__space_contraction_reading, nuclear_armed_state_leaderships).
narrative_ontology:constraint_victim(total_war_possibility_space__space_contraction_reading, great_power_general_staffs).
narrative_ontology:constraint_victim(total_war_possibility_space__space_contraction_reading, civil_defense_establishments).
narrative_ontology:constraint_vindicates(total_war_possibility_space__space_contraction_reading, thermonuclear_total_war_victory_incoherence).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Inherited planning institutions — mobilization schedules, war-college curricula, industrial-conversion plans — built across a century of society-wide war. The object of that planning exited the option set their staffs exist to explore; the apparatus persists as legacy doctrine, commemorative exercises, and mobilization studies that no longer connect to an executable campaign. Professional identity is fused with mastery of the lost object; there is no exit from the condition, only adaptation of the curriculum.
narrative_ontology:constraint_stakeholder(total_war_possibility_space__space_contraction_reading, great_power_general_staffs, payer,
    institutional, generational, identity_locked, national).

% The closure is the discipline's founding condition: deterrence theory, arms control, escalation management, and crisis stability exist as fields because unlimited war left the option set — had total war remained the operative object, strategy would have remained a branch of war-fighting rather than becoming a theoretical enterprise. Scholars build careers analyzing the shape of the closed space; they can and do move between fields, and nothing is taken from them.
narrative_ontology:constraint_stakeholder(total_war_possibility_space__space_contraction_reading, strategic_studies_academia, beneficiary,
    moderate, biographical, mobile, global).

% Govern the armed states living inside the closed space. They receive the condition's output — no adversary can pursue their society's annihilation as a winnable project — without administering or maintaining it; the closure is ambient, like geography. Their own planning freedom is bounded by the same closure: they cannot generate total-war options of their own, whatever their preferences in a crisis.
narrative_ontology:constraint_stakeholder(total_war_possibility_space__space_contraction_reading, nuclear_armed_state_leaderships, beneficiary,
    powerful, generational, constrained, national).

% Maintain societal-preparedness programs sized for an event class the planning space no longer contains. Budgets, shelter inventories, and exercise calendars persist at levels justified by the historical mission rather than current planning assumptions; the establishments bear the cost of keeping vestigial capability alive and absorb the criticism that follows each mismatch between drill scale and threat assessment.
narrative_ontology:constraint_stakeholder(total_war_possibility_space__space_contraction_reading, civil_defense_establishments, payer,
    organized, biographical, constrained, national).

% Study the transformation from outside any operating seat: comparing pre-1945 general-staff planning corpora with post-1945 doctrine, tracking when mobilization language disappeared from staff colleges, and weighing rival accounts of why the option set closed. They collect no rents and bear no costs; their product is the record the other seats argue from.
narrative_ontology:constraint_stakeholder(total_war_possibility_space__space_contraction_reading, strategic_theory_historians, observer,
    analytical, civilizational, analytical, global).

narrative_ontology:fixing_cost_class(total_war_possibility_space__space_contraction_reading, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Aligns great-power planning expectations on a common empty region: every staff can assume no adversary will prosecute society-wide unlimited war, so no one must plan against it. The alignment is epistemic — a shared certainty about what will not happen — rather than behavioral enforcement; the constraint performs no ongoing coordination work beyond fixing this background expectation.
% TRANSFER_FUNCTION: Nothing transfers. The closure moves no money, labor, attention, or status between parties; it deletes one option from every planner's set simultaneously and symmetrically. The only flows are internal to each seat: planning attention and institutional resources drained out of total-war preparation into limited-war, deterrence, and arms-control formats over the interval.
% ABSENT_VOICES: The theorists of operational total war — the mobilization planners whose profession peaked in 1914-1945 — would object that strategy has been amputated of its supreme object, but they are absent because their institutions no longer reproduce the profession. Also absent: the populations of would-be belligerent societies, whose stake in the closure is total and who are represented only indirectly through leaderships that did not choose the closure and cannot revoke it.
% DISAPPEARANCE_RATIONALE: If the closure vanished overnight — if total war returned to the thinkable space as an executable project — great-power staffs would begin rebuilding mobilization doctrine, industrial-conversion planning, and society-wide war-gaming within months; force structures optimized for limited war would be retooled; alliance commitments would be repriced against a restored worst case; and the strategic studies field would lose its founding condition. The rearrangement would be civilizational in scale, which is the operational content of claiming the closure as a mountain.
% FOUNDING_PROBLEM: The recurrence of society-annihilating great-power war — the sequence running from the Napoleonic conflicts through 1939-45 — posed an unsolved problem for every planning institution: how to prepare for, or prevent, the next total war. The closure answered it by removing the war itself from the executable set.
% FOUNDING_PROBLEM_CORROBORATION: No benefiting-party attestation is possible — the constraint has no administering beneficiary. Corroboration is archival and external: the documented disappearance of total-war content from staff-college curricula and mobilization planning after the mid-1950s (military-historical record), and the survival of great-power peace across crises (Berlin 1948-49, Cuba 1962, Middle East 1973, Able Archer 1983) in which total-war options were available to no deliberating participant. Historians of strategy working outside any operating seat attest both the atrophy and the exclusion; they dispute whether the founding problem is extinct or merely suppressed, which is why the status is authored contested.
narrative_ontology:disappearance_verdict(total_war_possibility_space__space_contraction_reading, world_rearranges).
narrative_ontology:founding_problem_status(total_war_possibility_space__space_contraction_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(total_war_possibility_space__space_contraction_reading, '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-22',
    'no_scope_rebuild_stealth', 'agent/example_platform_commission.json',
    'stealth/ox-alpha', 'max_tokens=65536,temperature=model_default,reasoning=model_default').
narrative_ontology:story_seed(total_war_possibility_space__space_contraction_reading, 'none', 1).
narrative_ontology:epsilon_provenance(total_war_possibility_space__space_contraction_reading, 0.05, 'stealth/ox-alpha', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(total_war_possibility_space__space_contraction_reading_tests).

% OQ-194: diagnostic probe, NOT a gate. Failure here means the authored
% mountain claim diverges from the story's computed metrics (claim != actual
% is the DR core) -- contested/extractive territory, not a regression. Bars
% (E=<0.25, S=<0.05, AC>=0.85, R=<0.15) are hardcoded; recalibration -> OQ-48.
test(mountain_threshold_validation) :-
    config:param(extractiveness_metric_name, ExtMetricName),
    narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, ExtMetricName, E),
    domain_priors:suppression_score(total_war_possibility_space__space_contraction_reading, S),
    E =< 0.25,
    S =< 0.05.

test(nl_profile_validation) :-
    domain_priors:emerges_naturally(total_war_possibility_space__space_contraction_reading),
    narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, accessibility_collapse, AC),
    narrative_ontology:constraint_metric(total_war_possibility_space__space_contraction_reading, resistance, R),
    AC >= 0.85,
    R =< 0.15.

:- end_tests(total_war_possibility_space__space_contraction_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extraction is authored near floor (0.05 at interval end) because nothing is collected: the closure deletes an option symmetrically and no seat accrues a flow from its operation; the small nonzero value reflects occasional rhetorical appropriation of the impossibility to justify unrelated force-structure choices. Suppression is near zero (0.02) because the constraint runs no enforcement machinery — it coerces no one, and its persistence requires no defense; the enforcement picture is static across the whole interval, so per the scalar rule no suppression_requirement series is authored and the static value lives in base_properties alone. Theater ratio rises from 0.05 to 0.45 across the interval: early on, total-war planning was real recent practice; as the closure consolidated, the remaining apparatus (mobilization studies, civil-defense drills, commemorative war-gaming) became progressively performative relative to any executable campaign — the measurable signature of the atrophy the reading predicts, deliberately held below the 0.5 substitution threshold because residual planning retains partial function. Accessibility collapse is high (0.92): once thermonuclear exchange mechanics are understood, 'winnable total war' framings collapse almost completely for any planner who works through the physics. Resistance is low (0.06): the war-fighting school and 'victory is possible' rhetoric of the 1970s-80s attempted to reopen limited-use thinking and thereby conceded that total war proper was off the table. Both tracked series run on one shared nine-point grid (every metric authored at every examined time point); the interval unit is years since 1945.
 *
 * PERSPECTIVAL GAP:
 *   The seats should compute differently from identical structural exposure. From the general-staff seat the closure is experienced as amputation — a founding professional object removed, leaving identity fused to a vestigial tradition (identity_locked exit captures the fusion, not any barrier). From the academic seat the same closure is a foundation — the condition of the discipline's existence. From the leadership seat it is weather — ambient, unadministered, unchosen. Nothing varies in the constraint across these seats; what varies is what each seat had invested in the deleted option. The engine computes this per-seat divergence from power and exit data; the authored mountain claim does not adjudicate it.
 *
 * DIRECTIONALITY LOGIC:
 *   No beneficiaries or victims are declared in base_properties because nothing is extracted from anyone and nothing is subsidized: the closure grants and costs no flow, it removes an option. The directionality derivation chain therefore has no structural asymmetry to read and falls back to canonical per-power-atom defaults, which are immaterial under a constraint with zero degrees of freedom for all indices. Correspondingly, no directionality overrides are authored — there is no derived d to correct. The receipt surface is handled the same way: gain_flow is omitted entirely because no extraction exists to accrue to any seat (authoring 'diffuse' would assert a checked universal negative about a flow whose magnitude is zero); fixing_cost is authored prohibitive because removal would require dismantling secure second-strike survivability worldwide — beyond any seat's power, and desired by no operating seat.
 *
 * MANDATROPHY ANALYSIS:
 *   Two misclassifications are the live risks, and the mountain claim guards both. First, the atrophied planning apparatus invites a piton reading — vestigial, increasingly theatrical, maintained by inertia. But the piton test is cost-asymmetry on an administered constraint: here no seat administers the constraint itself, and the theater lives in downstream debris (legacy doctrine, civil-defense rituals), not in the closure, which requires no maintenance at all. Second, a snare reading — 'the war option was stolen from the professions' — fails for lack of any collector: no seat receives what the staffs lost. The mountain classification locates the fixity where this reading says it resides, in the material configuration rather than in any institution. If the omegas resolve toward cognitive closure (material_vs_cognitive_closure) or configuration contingency (technological_configuration_contingency), reclassification pressure toward constructed-constraint types follows, and the atrophied-apparatus question revives as a live mandatrophy candidate rather than a settled one.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    kernel_reading_contestation,
    'This story instantiates the space_contraction_reading of the kernel total_war_possibility_space; would the sibling readings (deterrence_equilibrium_reading, nuclear_taboo_reading) classify the same post-1945 exclusion differently, and where exactly is the disagreement located?',
    'Process-tracing crisis deliberation under degraded signaling: if decision-makers never generate total-war courses of action, the contraction reading holds; if they generate and reject them on cost calculus, the deterrence reading; if they generate and reject them on norm violation, the taboo reading.',
    'The classification of the exclusion flips with the reading: material impossibility supports mountain; a maintained cost-equilibrium supports a costly coordination arrangement requiring continuous vulnerability maintenance; a constructed prohibition supports a socially reproduced constraint dependent on cultural transmission.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(kernel_reading_contestation, conceptual, 'Which reading of the total-war kernel is instantiated determines the constraint''s type; siblings are separate stories.').

omega_variable(
    material_vs_cognitive_closure,
    'Is the closure of the planning space a property of the weapons'' material effects (any planner confronting thermonuclear exchange finds the plan self-defeating on its own terms), or of trained strategic cognition that has stopped generating the option?',
    'Declassified deliberation records from severe crises (Berlin, Cuba, 1973, Able Archer 83) plus generational-turnover studies of staff work: whether total-war courses of action appear in planning at all, and whether newly arrived planners regenerate them.',
    'If cognitive, the constraint is contingent on doctrinal transmission and could erode with generational change or institutional forgetting — incompatible with mountain certification; if material, it persists across personnel turnover and preference shifts.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(material_vs_cognitive_closure, empirical, 'Material versus cognitive mechanism of the option-space closure.').

omega_variable(
    technological_configuration_contingency,
    'Does the categorical impossibility survive plausible changes in the material configuration — leak-proof missile defense, disarming first-strike capability, autonomous decisive systems — or is it contingent on the current offense-defense balance?',
    'Technical assessment of emerging strategic-defense and counterforce programs against the survivability assumptions underlying second-strike stability; monitoring for any reopened path to societal victory.',
    'A reopened winning path would dissolve the mountain: total war re-enters the thinkable space, the atrophied planning apparatus question becomes live again, and the constraint stands revealed as configuration-contingent rather than a natural law.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(technological_configuration_contingency, empirical, 'Whether the closure is a law of the current configuration or a durable structural limit.').

omega_variable(
    planning_atrophy_completeness,
    'Has total-war planning atrophied as completely as the reading predicts — mobilization doctrine gone, great-power society-wide war-gaming ceased — or does residual executable capability persist in some staffs?',
    'Audit of current great-power planning documents, war-college curricula, and mobilization studies for society-wide war content, benchmarked against pre-1945 planning corpora.',
    'Substantial residual capability would weaken the categorical claim (partial contraction, not closure) and shift weight toward the deterrence and taboo readings; complete atrophy corroborates the space-contraction account.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(planning_atrophy_completeness, empirical, 'Completeness of the predicted institutional atrophy of total-war planning.').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(total_war_possibility_space__space_contraction_reading, 0, 80).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(twp_scr_tr_t0, total_war_possibility_space__space_contraction_reading, theater_ratio, 0, 0.05).
narrative_ontology:measurement(twp_scr_tr_t10, total_war_possibility_space__space_contraction_reading, theater_ratio, 10, 0.08).
narrative_ontology:measurement(twp_scr_tr_t20, total_war_possibility_space__space_contraction_reading, theater_ratio, 20, 0.13).
narrative_ontology:measurement(twp_scr_tr_t30, total_war_possibility_space__space_contraction_reading, theater_ratio, 30, 0.19).
narrative_ontology:measurement(twp_scr_tr_t40, total_war_possibility_space__space_contraction_reading, theater_ratio, 40, 0.26).
narrative_ontology:measurement(twp_scr_tr_t50, total_war_possibility_space__space_contraction_reading, theater_ratio, 50, 0.31).
narrative_ontology:measurement(twp_scr_tr_t60, total_war_possibility_space__space_contraction_reading, theater_ratio, 60, 0.36).
narrative_ontology:measurement(twp_scr_tr_t70, total_war_possibility_space__space_contraction_reading, theater_ratio, 70, 0.41).
narrative_ontology:measurement(twp_scr_tr_t80, total_war_possibility_space__space_contraction_reading, theater_ratio, 80, 0.45).

% Extraction over time
narrative_ontology:measurement(twp_scr_be_t0, total_war_possibility_space__space_contraction_reading, base_extractiveness, 0, 0.03).
narrative_ontology:measurement(twp_scr_be_t10, total_war_possibility_space__space_contraction_reading, base_extractiveness, 10, 0.03).
narrative_ontology:measurement(twp_scr_be_t20, total_war_possibility_space__space_contraction_reading, base_extractiveness, 20, 0.04).
narrative_ontology:measurement(twp_scr_be_t30, total_war_possibility_space__space_contraction_reading, base_extractiveness, 30, 0.04).
narrative_ontology:measurement(twp_scr_be_t40, total_war_possibility_space__space_contraction_reading, base_extractiveness, 40, 0.04).
narrative_ontology:measurement(twp_scr_be_t50, total_war_possibility_space__space_contraction_reading, base_extractiveness, 50, 0.05).
narrative_ontology:measurement(twp_scr_be_t60, total_war_possibility_space__space_contraction_reading, base_extractiveness, 60, 0.05).
narrative_ontology:measurement(twp_scr_be_t70, total_war_possibility_space__space_contraction_reading, base_extractiveness, 70, 0.05).
narrative_ontology:measurement(twp_scr_be_t80, total_war_possibility_space__space_contraction_reading, base_extractiveness, 80, 0.05).

% Suppression authored static: scalar-only by design, no temporal series
narrative_ontology:suppression_profile(total_war_possibility_space__space_contraction_reading, static).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:affects_constraint(total_war_possibility_space__space_contraction_reading, deterrence_equilibrium_reading).
narrative_ontology:affects_constraint(total_war_possibility_space__space_contraction_reading, nuclear_taboo_reading).

% DUAL FORMULATION NOTE:
% Constraint-family decomposition of the colloquial claim 'nuclear weapons ended total war.' The label conflates three structurally distinct constraints: this story (space_contraction_reading — material closure of the option set, claimed mountain, epsilon 0.05, no enforcement, no beneficiaries), deterrence_equilibrium_reading (total war reachable but deterred — a maintained equilibrium whose persistence requires continuous vulnerability maintenance, expected coordination-with-overhead profile), and nuclear_taboo_reading (normatively constructed prohibition — a reproduced social constraint contingent on cultural transmission). The readings share a referent — the standing post-1945 exclusion of great-power total war — and diverge on mechanism; epsilon here is authored only for the contraction reading's referent, per the epsilon-invariance principle. The upstream empirical record (no great-power total war since 1945, archival atrophy of planning content) is cited by all three readings, which is why the family edges run from this story to both siblings.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
