% ============================================================================
% CONSTRAINT STORY: homoousios_christology__arian_reading
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-08-04
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_homoousios_christology__arian_reading, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:constraint_vindicates/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    narrative_ontology:boltzmann_floor_override/2,
    constraint_indexing:constraint_classification/3,
    constraint_indexing:directionality_override/3,
    narrative_ontology:constraint_stakeholder/7,
    narrative_ontology:stakeholder_secondary_role/3,
    narrative_ontology:disappearance_verdict/2,
    narrative_ontology:founding_problem_status/2,
    narrative_ontology:stakeholder_gain_flow/2,
    narrative_ontology:fixing_cost_class/2,
    narrative_ontology:omega_variable/3,
    narrative_ontology:cs_story_uid/2,
    narrative_ontology:cs_kernel_codification/2,
    narrative_ontology:cs_authority_grounding/2,
    narrative_ontology:cs_interpretation_layer_present/1,
    narrative_ontology:cs_kernel_id/2,
    narrative_ontology:cs_reading_relation/3,
    narrative_ontology:cs_axiom/3,
    narrative_ontology:cs_axiom_status/2,
    narrative_ontology:cs_axiom_grounding/3,
    narrative_ontology:cs_reference_frame/2,
    narrative_ontology:cs_drift_state/3,
    narrative_ontology:cs_created_at/2,
    narrative_ontology:epsilon_provenance/5,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: homoousios_christology__arian_reading
 *   human_readable: Arian Christology — Christ as Created Subordinate to the Father
 *   domain: historical_theology/ecclesiastical_politics
 *
 * SUMMARY:
 *   The Arian reading of the homoousios_christology kernel instantiates the
 *   constraint that the Son (Logos/Christ) is a created being, generated by
 *   the Father before all ages but not coeternal, not of the same substance
 *   (homoousios), and subordinate in divinity. This reading emerged from the
 *   Alexandrian presbyter Arius (c. 256-336 CE) and became the basis for a
 *   major ecclesiastical coalition that controlled significant portions of
 *   the Eastern empire under Constantius II and Valens. The constraint
 *   functioned as both a coordination mechanism for non-Nicene bishops
 *   (providing doctrinal unity, liturgical coherence, and episcopal
 *   solidarity against imperial-Nicene pressure) and an extraction mechanism
 *   (requiring subscription to Arian creeds, displacing Nicene clergy,
 *   redirecting church resources). The interval 318-381 CE covers the period
 *   from the controversy's outbreak to the Council of Constantinople's
 *   definitive Nicene victory.
 *
 * KEY AGENTS:
 *   - non_nicene_bishops: Primary beneficiaries (institutional/constrained) — gain episcopal authority and imperial patronage under Arian regimes
 *   - arian_theologians: Primary beneficiaries (organized/constrained) — intellectual leadership defines the coalition's boundary
 *   - nicene_adherents_under_arian_rule: Primary victims (powerless/trapped) — displaced, exiled, or coerced into subscription
 *   - trinitarian_monastics: Victims (moderate/identity_locked) — monastic communities resisting Arian episcopal appointments
 *   - imperial_orthodoxy_enforcers: Secondary actors (institutional/mobile) — state power enforcing competing orthodoxy
 *   - gothic_missionary_networks: Beneficiaries (organized/mobile) — Ulfilas' Gothic Christianity adopts Arian framework for missional coherence
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(homoousios_christology__arian_reading, 0.68).
domain_priors:suppression_score(homoousios_christology__arian_reading, 0.35).
domain_priors:theater_ratio(homoousios_christology__arian_reading, 0.42).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(homoousios_christology__arian_reading, extractiveness, 0.68).
narrative_ontology:constraint_metric(homoousios_christology__arian_reading, suppression_requirement, 0.35).
narrative_ontology:constraint_metric(homoousios_christology__arian_reading, theater_ratio, 0.42).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(homoousios_christology__arian_reading, accessibility_collapse, 0.45).
narrative_ontology:constraint_metric(homoousios_christology__arian_reading, resistance, 0.72).

% --- Constraint claim ---
narrative_ontology:constraint_claim(homoousios_christology__arian_reading, tangled_rope).
narrative_ontology:human_readable(homoousios_christology__arian_reading, "Arian Christology — Christ as Created Subordinate to the Father").
narrative_ontology:topic_domain(homoousios_christology__arian_reading, "historical_theology/ecclesiastical_politics").

domain_priors:requires_active_enforcement(homoousios_christology__arian_reading).

% --- Commitment system structure ---
narrative_ontology:cs_story_uid(homoousios_christology__arian_reading, 'bcd4abc1-a762-43bf-9ec6-74449b755151').
narrative_ontology:cs_kernel_codification('bcd4abc1-a762-43bf-9ec6-74449b755151', formalized).
narrative_ontology:cs_authority_grounding('bcd4abc1-a762-43bf-9ec6-74449b755151', extraction).
narrative_ontology:cs_interpretation_layer_present('bcd4abc1-a762-43bf-9ec6-74449b755151').
narrative_ontology:cs_reading_relation('bcd4abc1-a762-43bf-9ec6-74449b755151', homoousios_christology__pro_nicene_reading, forecloses).
narrative_ontology:cs_reading_relation('bcd4abc1-a762-43bf-9ec6-74449b755151', homoousios_christology__semi_arian_reading, influences).
narrative_ontology:cs_axiom('bcd4abc1-a762-43bf-9ec6-74449b755151', foundational, son_created_not_coeternal).
narrative_ontology:cs_axiom_status(son_created_not_coeternal, holdable).
narrative_ontology:cs_axiom_grounding('bcd4abc1-a762-43bf-9ec6-74449b755151', son_created_not_coeternal, deontological).
narrative_ontology:cs_axiom('bcd4abc1-a762-43bf-9ec6-74449b755151', foundational, father_sole_unoriginate).
narrative_ontology:cs_axiom_status(father_sole_unoriginate, holdable).
narrative_ontology:cs_axiom_grounding('bcd4abc1-a762-43bf-9ec6-74449b755151', father_sole_unoriginate, deontological).
narrative_ontology:cs_reference_frame('bcd4abc1-a762-43bf-9ec6-74449b755151', monarchian_father_sole_principle).
narrative_ontology:cs_drift_state('bcd4abc1-a762-43bf-9ec6-74449b755151', post_constantinople_381, gap(authority_erosion, severe, false)).
narrative_ontology:cs_created_at('bcd4abc1-a762-43bf-9ec6-74449b755151', '2026-08-04T14:22:00Z').
narrative_ontology:cs_kernel_id(homoousios_christology__arian_reading, homoousios_christology).

% --- Structural relationships ---
narrative_ontology:constraint_beneficiary(homoousios_christology__arian_reading, non_nicene_bishops).
narrative_ontology:constraint_beneficiary(homoousios_christology__arian_reading, arian_theologians).
narrative_ontology:constraint_beneficiary(homoousios_christology__arian_reading, gothic_missionary_networks).
narrative_ontology:constraint_victim(homoousios_christology__arian_reading, nicene_adherents_under_arian_rule).
narrative_ontology:constraint_victim(homoousios_christology__arian_reading, trinitarian_monastics).
narrative_ontology:constraint_victim(homoousios_christology__arian_reading, imperial_orthodoxy_enforcers).
narrative_ontology:constraint_vindicates(homoousios_christology__arian_reading, monotheistic_preservation).
narrative_ontology:constraint_vindicates(homoousios_christology__arian_reading, father_sole_unoriginate).
narrative_ontology:constraint_vindicates(homoousios_christology__arian_reading, son_generated_not_coeternal).

/* ==========================================================================
   2b. STAKEHOLDER LAYER (OQ-83; roles from the DECLARED dial-set —
   see schemas/constraint_story_schema.json $defs/StakeholderRole and the
   attached residue ledger. Names are per-story and domain-specific; never
   standardized across readings (OQ-84).
   ========================================================================== */

% Eastern bishops who rejected Nicaea gained imperial patronage, episcopal sees vacated by exiled Nicene bishops, and a coherent theological identity distinguishing them from Western/Nicene centralization. Their exit was constrained: returning to Nicene communion meant losing their sees and admitting error; resisting meant permanent schism from Rome and Alexandria.
narrative_ontology:constraint_stakeholder(homoousios_christology__arian_reading, non_nicene_bishops, beneficiary,
    institutional, generational, constrained, regional).
narrative_ontology:stakeholder_secondary_role(homoousios_christology__arian_reading, non_nicene_bishops, agenda_setter).

% Theologians (Arius, Asterius, Eunomius, Auxentius) defined the coalition's doctrinal boundary and authored the creeds imposed at Arian councils. They gained intellectual authority and imperial sponsorship but were constrained by the need to maintain theological coherence against semi-Arian drift and Nicene refutation. Exit meant theological obsolescence or exile.
narrative_ontology:constraint_stakeholder(homoousios_christology__arian_reading, arian_theologians, agenda_setter,
    organized, biographical, constrained, regional).
narrative_ontology:stakeholder_secondary_role(homoousios_christology__arian_reading, arian_theologians, beneficiary).

% Laity and clergy in Arian-controlled dioceses faced mandatory subscription to Arian creeds (e.g., Dated Creed of 359), displacement of Nicene clergy, confiscation of church buildings, and exile of bishops (Athanasius exiled 5 times). Exit was nearly impossible: geographic mobility limited, identity bound to Nicene confession, and imperial law criminalized Nicene assembly under Valens.
narrative_ontology:constraint_stakeholder(homoousios_christology__arian_reading, nicene_adherents_under_arian_rule, payer,
    powerless, biographical, trapped, local).

% Monastic communities (Pachomian, Antonian, Nitrian) became centers of Nicene resistance. Their vow of stability and obedience to monastic rule fused with Nicene orthodoxy — exit from the resistance would break their monastic identity. Arian bishops attempted to install compliant abbots; monks resisted through flight, refusal of communion, and appeal to Western bishops.
narrative_ontology:constraint_stakeholder(homoousios_christology__arian_reading, trinitarian_monastics, payer,
    moderate, biographical, identity_locked, regional).
narrative_ontology:stakeholder_secondary_role(homoousios_christology__arian_reading, trinitarian_monastics, excluded).

% Imperial officials (Constantius II, Valens, Theodosius I) and their ecclesiastical allies enforced competing orthodoxies. They observed the Arian constraint's operation from the outside — as a rival system to be suppressed (Constantius/Valens) or as a defeated system to be dismantled (Theodosius). Their analytical seat computes the constraint's extraction from both Arian and Nicene perspectives.
narrative_ontology:constraint_stakeholder(homoousios_christology__arian_reading, imperial_orthodoxy_enforcers, observer,
    institutional, generational, analytical, continental).

% Ulfilas and his Gothic missionary network adopted Arian Christianity as a coherent framework for converting Germanic peoples. The Arian constraint provided liturgical texts in Gothic, a clear doctrinal boundary against paganism, and imperial sponsorship. Their exit was mobile: they could have adopted Nicene Christianity (as the Franks did) but chose Arianism for its missional coherence and imperial backing.
narrative_ontology:constraint_stakeholder(homoousios_christology__arian_reading, gothic_missionary_networks, beneficiary,
    organized, generational, mobile, continental).

% --- OQ-92 receipt surface: who RECEIVES the extraction (capture half).
% 'diffuse' = authored no-capture (piton-side); a seat name = capturer.
% ABSENT field = not authored, fail-closed. Never synthesized. ---
narrative_ontology:stakeholder_gain_flow(homoousios_christology__arian_reading, non_nicene_bishops).
narrative_ontology:fixing_cost_class(homoousios_christology__arian_reading, prohibitive).

% --- Six-questions battery (story-level; texts kept as comments — the
% engine consumes only the two atoms below; the founding-problem narrative
% is NEVER consumed as a claim, mismatch-consumer only, OQ-83 R5) ---
% COORDINATION_FUNCTION: Provided doctrinal and institutional coherence for Eastern bishops resisting Nicene centralization and Western ecclesiastical claims — a unified creed, shared liturgical practice, and mutual episcopal recognition across the Arian-controlled East.
% TRANSFER_FUNCTION: Moved episcopal authority, church property, imperial patronage, and doctrinal legitimacy from Nicene incumbents to Arian appointees; moved subscription costs (conscience, career, community) onto Nicene laity and clergy who refused Arian creeds.
% ABSENT_VOICES: Nicene laity in Arian dioceses (no representative voice in councils); women in monastic and lay communities (excluded from theological decision-making); Germanic converts (recipients of missionary framework, not authors); semi-Arian bishops (marginalized as 'inconsistent' by both poles).
% DISAPPEARANCE_RATIONALE: If the Arian constraint vanished overnight (as effectively happened at Constantinople 381), episcopal sees would revert to Nicene incumbents, imperial patronage would shift, Gothic churches would face doctrinal crisis, and the Eastern ecclesiastical map would reorganize around Nicene communion — the world rearranged because arrangements (sees, patronage, missionary structures) depended on the constraint.
% FOUNDING_PROBLEM: Preserving strict monotheism against the perceived ditheism of 'two unoriginates' (Father and Son both uncreated) — Arius argued that if the Son is uncreated (agennētos), there are two principles without origin, collapsing the monarchy of the Father.
% FOUNDING_PROBLEM_CORROBORATION: Arius and Asterius attested the problem as live (Thalia, Syntagmation). Athanasius, the Cappadocian Fathers, and Western synods (Serdica, Rome) attested the problem as resolved by homoousios — the Son's generation from the Father's substance preserves monarchy without creating a second unoriginate. The Council of Constantinople (381) and subsequent imperial law treated the founding problem as resolved. No neutral party corroborates the problem as live after 360; the Arian coalition's persistence was institutional, not theological.
narrative_ontology:disappearance_verdict(homoousios_christology__arian_reading, world_rearranges).
narrative_ontology:founding_problem_status(homoousios_christology__arian_reading, contested).

/* ==========================================================================
   3. PROVENANCE (cohort metadata — schema-required since Phase C)
   ========================================================================== */

narrative_ontology:story_provenance(homoousios_christology__arian_reading, '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28',
    '685ed7cf90d7b7bdcefb4b3c4e62d9bf2aa6ee28', '2026-08-21',
    'no_scope_rebuild_nemotron', 'agent/example_platform_commission.json',
    'nvidia/nemotron-3-ultra-550b-a55b:free', 'max_tokens=65536,temperature=model_default,reasoning=disabled').
narrative_ontology:story_seed(homoousios_christology__arian_reading, 'none', 1).
narrative_ontology:epsilon_provenance(homoousios_christology__arian_reading, 0.68, 'nvidia/nemotron-3-ultra-550b-a55b:free', 'none', direct).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(homoousios_christology__arian_reading_tests).

test(extraction_signature) :-
    domain_priors:base_extractiveness(homoousios_christology__arian_reading, E),
    E >= 0.46. % Ensures high-extraction Snare/Tangled territory.

:- end_tests(homoousios_christology__arian_reading_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.68) reflects the material and doctrinal demands Arian episcopal structures imposed: mandatory creedal subscription, displacement of Nicene clergy, redirection of church revenues to Arian hierarchies, and imperial enforcement against dissident communities. Suppression (0.35) is moderate because Arian regimes relied more on persuasion, imperial patronage, and episcopal appointment than systematic persecution — but suppression intensified under Valens (364-378). Theater ratio (0.42) captures the performative dimension: Arian councils (Sirmium, Ariminum, Constantinople 360) staged theological consensus while enforcing subscription. Accessibility collapse (0.45) is moderate — the theological boundary was sharp (created vs. uncreated) but semi-Arian compromise (homoiousios) offered a permeable middle ground. Resistance (0.72) is high: Nicene resistance (Athanasius' exiles, monastic opposition, Western synods) persisted throughout the interval. The claimed type tangled_rope reflects genuine coordination among non-Nicene bishops AND asymmetric extraction from Nicene communities.
 *
 * DIRECTIONALITY LOGIC:
 *   Non-Nicene bishops and Arian theologians are structural beneficiaries: they gain institutional coherence, imperial recognition (under Constantius/Valens), and doctrinal authority — directionality d near 0.1-0.2. Nicene adherents under Arian rule are structural targets: they bear displacement, exile, property loss, and coerced subscription — d near 0.8-0.9. Trinitarian monastics are identity-locked targets: their monastic vow binds them to Nicene orthodoxy, making exit spiritually impossible — d near 0.85. Gothic missionary networks are mobile beneficiaries: they adopt the Arian framework voluntarily for missional coherence among Germanic peoples — d near 0.2. Imperial enforcers are analytical/mobile observers of the constraint's operation from the opposing institutional seat.
 *
 * MANDATROPHY ANALYSIS:
 *   The founding problem (preserving monotheism against perceived ditheism in 'two unoriginates') was live in the 320s but became contested as the Nicene formulation (homoousios) demonstrated that coeternal Son does not entail two Fathers. The Arian constraint persisted past its founding problem's resolution because it became an ecclesiastical-political identity marker for Eastern bishops resisting Western/Nicene centralization. Mandatrophy is unresolved: the constraint's coordination function (episcopal solidarity) outlived its theological justification, and the extraction apparatus (creedal enforcement) continued serving institutional interests. The 381 Council of Constantinople did not resolve the mandatrophy — it suppressed the constraint by imperial force, leaving the structural pattern available for future anti-Nicene movements.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    kernel_reading_disambiguation,
    'Is this constraint a reading of the homoousios_christology kernel, and does the Arian reading structurally foreclose, coexist with, or influence the pro-Nicene and semi-Arian readings?',
    'Structural analysis of whether the Arian premise (Son is created, not coeternal) logically contradicts the pro-Nicene premise (Son is homoousios with Father) within a single doctrinal framework, or whether both remain live positions held by different ecclesiastical parties.',
    'If forecloses, the kernel has genuine logical incompatibility between readings; if coexists_with, the dispute is political-ecclesiastical rather than purely logical; if influences, the Arian reading''s institutional success creates downstream pressure on sibling readings'' legitimacy conditions.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(kernel_reading_disambiguation, conceptual, 'Structural relationship between Arian reading and sibling readings of the homoousios kernel').

omega_variable(
    imperial_enforcement_vs_theological_legitimacy,
    'Does the constraint''s extraction derive from imperial enforcement of Nicene orthodoxy (making Arianism a resistance position) or from Arian episcopal structures extracting compliance from their own constituencies?',
    'Historical analysis of whether Arian ecclesiastical structures (c. 350-380 CE) imposed liturgical, doctrinal, or material demands on local churches comparable to Nicene enforcement, or whether the primary extraction vector was imperial suppression of Arian communities.',
    'If Arian structures were extractive, the constraint operates as tangled_rope from both directions; if primarily resistance to imperial extraction, the constraint functions as rope/scaffold for Arian communities with extraction flowing from the opposing imperial-Nicene constraint.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(imperial_enforcement_vs_theological_legitimacy, empirical, 'Direction of extraction in the Arian-Nicene conflict').

omega_variable(
    son_subordination_mechanism,
    'Is the Son''s subordination in this reading ontological (created being, different substance) or functional (voluntary submission within shared divinity)?',
    'Exegetical and historical analysis of Arian theological texts (Arius'' Thalia, Asterius'' Syntagmation, Eunomius'' Apologeticus) to determine whether the subordination is constitutive of the Son''s being or a role within the economy of salvation.',
    'Ontological subordination makes the constraint a stronger boundary marker (higher accessibility_collapse); functional subordination makes it more permeable to semi-Arian compromise (homoiousios). Affects classification stability across the kernel family.',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(son_subordination_mechanism, conceptual, 'Nature of Son''s subordination in Arian theology').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(homoousios_christology__arian_reading, 318, 381).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(homoousios_arian_tr_t318, homoousios_christology__arian_reading, theater_ratio, 318, 0.15).
narrative_ontology:measurement(homoousios_arian_tr_t325, homoousios_christology__arian_reading, theater_ratio, 325, 0.28).
narrative_ontology:measurement(homoousios_arian_tr_t335, homoousios_christology__arian_reading, theater_ratio, 335, 0.35).
narrative_ontology:measurement(homoousios_arian_tr_t350, homoousios_christology__arian_reading, theater_ratio, 350, 0.4).
narrative_ontology:measurement(homoousios_arian_tr_t359, homoousios_christology__arian_reading, theater_ratio, 359, 0.42).
narrative_ontology:measurement(homoousios_arian_tr_t381, homoousios_christology__arian_reading, theater_ratio, 381, 0.55).

% Extraction over time
narrative_ontology:measurement(homoousios_arian_be_t318, homoousios_christology__arian_reading, base_extractiveness, 318, 0.35).
narrative_ontology:measurement(homoousios_arian_be_t325, homoousios_christology__arian_reading, base_extractiveness, 325, 0.52).
narrative_ontology:measurement(homoousios_arian_be_t335, homoousios_christology__arian_reading, base_extractiveness, 335, 0.61).
narrative_ontology:measurement(homoousios_arian_be_t350, homoousios_christology__arian_reading, base_extractiveness, 350, 0.65).
narrative_ontology:measurement(homoousios_arian_be_t359, homoousios_christology__arian_reading, base_extractiveness, 359, 0.68).
narrative_ontology:measurement(homoousios_arian_be_t381, homoousios_christology__arian_reading, base_extractiveness, 381, 0.42).

% Suppression requirement over time
narrative_ontology:measurement(homoousios_arian_su_t318, homoousios_christology__arian_reading, suppression_requirement, 318, 0.2).
narrative_ontology:measurement(homoousios_arian_su_t325, homoousios_christology__arian_reading, suppression_requirement, 325, 0.45).
narrative_ontology:measurement(homoousios_arian_su_t335, homoousios_christology__arian_reading, suppression_requirement, 335, 0.38).
narrative_ontology:measurement(homoousios_arian_su_t350, homoousios_christology__arian_reading, suppression_requirement, 350, 0.32).
narrative_ontology:measurement(homoousios_arian_su_t359, homoousios_christology__arian_reading, suppression_requirement, 359, 0.35).
narrative_ontology:measurement(homoousios_arian_su_t381, homoousios_christology__arian_reading, suppression_requirement, 381, 0.65).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(homoousios_christology__arian_reading, identity_coordination).
narrative_ontology:boltzmann_floor_override(homoousios_christology__arian_reading, 0.1).
narrative_ontology:affects_constraint(homoousios_christology__arian_reading, homoousios_christology__pro_nicene_reading).
narrative_ontology:affects_constraint(homoousios_christology__arian_reading, homoousios_christology__semi_arian_reading).
narrative_ontology:affects_constraint(homoousios_christology__arian_reading, imperial_christological_enforcement).
narrative_ontology:affects_constraint(homoousios_christology__arian_reading, germanic_arian_missionary_structure).

% DUAL FORMULATION NOTE:
% This constraint is one member of the homoousios_christology constraint family (kernel_id: homoousios_christology). The three readings (arian, pro_nicene, semi_arian) instantiate different constraints from the same kernel. The Arian reading's ε (0.68) differs substantially from the pro-Nicene reading's ε (expected ~0.25 as mountain/rope) because the Arian reading operated as an enforced ecclesiastical-political system with extraction, while the pro-Nicene reading functioned as a theological boundary with minimal extraction from its adherents. The kernel's label 'the Arian controversy' conflates these structurally distinct constraints.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

constraint_indexing:directionality_override(homoousios_christology__arian_reading, institutional, 0.15).
constraint_indexing:directionality_override(homoousios_christology__arian_reading, powerless, 0.85).
constraint_indexing:directionality_override(homoousios_christology__arian_reading, moderate, 0.75).
constraint_indexing:directionality_override(homoousios_christology__arian_reading, organized, 0.2).

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
