% ============================================================================
% CONSTRAINT STORY: earth_magnetic_field_generation
% ============================================================================
% Version: 1.0 (Deferential Realism Core + Directionality + Boltzmann + Network)
% Logic: 6.0 (Indexed Tuple P,T,E,S + Sigmoid f(d) + Coupling + Purity + Network)
% Generated: 2026-02-26
% Status: [ACTIVE]
% ============================================================================

:- module(constraint_earth_magnetic_field_generation, []).

:- use_module(constraint_indexing).
:- use_module(domain_priors).
:- use_module(narrative_ontology).

% --- Constraint Identity Rule (DP-001: ε-Invariance) ---
% Each constraint story must have a single, stable base extractiveness (ε).
% If changing the observable used to evaluate this constraint would change ε,
% you are looking at two distinct constraints. Write separate .pl files for
% each, link them with affects_constraint/2, and document the relationship
% in both files' narrative context sections.
%
% The context tuple is CLOSED at arity 4: (P, T, E, S).
% Do not add measurement_basis, beneficiary/victim, or any other arguments.
% Linter Rule 23 enforces context/4.
%
% See: epsilon_invariance_principle.md

% --- Namespace Hooks (Required for loading) ---
:- multifile
    domain_priors:base_extractiveness/2,
    domain_priors:suppression_score/2,
    domain_priors:theater_ratio/2,
    domain_priors:requires_active_enforcement/1,
    narrative_ontology:has_sunset_clause/1,
    narrative_ontology:interval/3,
    narrative_ontology:measurement/5,
    narrative_ontology:constraint_metric/3,
    narrative_ontology:constraint_beneficiary/2,
    narrative_ontology:constraint_victim/2,
    narrative_ontology:constraint_claim/2,
    narrative_ontology:affects_constraint/2,
    narrative_ontology:coordination_type/2,
    constraint_indexing:constraint_classification/3,
    domain_priors:emerges_naturally/1,
    narrative_ontology:omega_variable/3,
    narrative_ontology:human_readable/2,
    narrative_ontology:topic_domain/2.

/* ==========================================================================
   1. NARRATIVE CONTEXT
   ========================================================================== */

/**
 * CONSTRAINT IDENTIFICATION
 *   constraint_id: earth_magnetic_field_generation
 *   human_readable: Earth Magnetic Field Generation via Dynamo Action
 *   domain: geophysics/planetary_physics
 *
 * SUMMARY:
 *   The Earth's magnetic field is generated by convective dynamo action in
 *   the liquid iron outer core, driven by planetary rotation, internal heat
 *   flux, and compositional buoyancy. This constraint is a natural law: the
 *   field emerges necessarily from magnetohydrodynamic principles applied to
 *   planetary-scale systems. The constraint exhibits zero degrees of freedom
 *   — all agents (inhabitants, technological systems, observers) face
 *   immutable constraints from the field's topology, temporal variability,
 *   reversal cycles, and coupling to magnetospheric dynamics. No agent can
 *   exit, modify, or coordinate around the fundamental generation mechanism.
 *   The constraint is invariant across all observables and measurement
 *   methodologies — the MHD equations apply regardless of whether we measure
 *   the field via magnetometers, paleomagnetic cores, or satellite campaigns.
 *
 * KEY AGENTS:
 *   - Planetary System: Generator of the constraint (not an agent; the constraint emerges from core dynamics)
 *   - Planetary Inhabitants: Powerless agents (civilizational scale) — constrained by field topology, radiation protection, and biological navigation cues
 *   - Technological Infrastructure: Organized agents (generational scale) — face immutable limits on predictability of declination drift, secular variation, and auroral coupling
 *   - Observational Science: Analytical position — can measure and model the dynamo but cannot modify its fundamental operation
 */

/* ==========================================================================
   2. BASE PROPERTIES (DOMAIN PRIORS)
   ========================================================================== */

% --- Numerical metrics ---
domain_priors:base_extractiveness(earth_magnetic_field_generation, 0.08).
domain_priors:suppression_score(earth_magnetic_field_generation, 0.02).
domain_priors:theater_ratio(earth_magnetic_field_generation, 0.15).

% --- Constraint metric facts (engine primary keys, must mirror domain_priors) ---
narrative_ontology:constraint_metric(earth_magnetic_field_generation, extractiveness, 0.08).
narrative_ontology:constraint_metric(earth_magnetic_field_generation, suppression_requirement, 0.02).
narrative_ontology:constraint_metric(earth_magnetic_field_generation, theater_ratio, 0.15).

% --- NL Profile Metrics (required for mountain constraints) ---
narrative_ontology:constraint_metric(earth_magnetic_field_generation, accessibility_collapse, 0.92).
narrative_ontology:constraint_metric(earth_magnetic_field_generation, resistance, 0.08).

% --- Constraint claim ---
narrative_ontology:constraint_claim(earth_magnetic_field_generation, mountain).
narrative_ontology:human_readable(earth_magnetic_field_generation, "Earth Magnetic Field Generation via Dynamo Action").
narrative_ontology:topic_domain(earth_magnetic_field_generation, "geophysics/planetary_physics").

domain_priors:emerges_naturally(earth_magnetic_field_generation).

% --- Structural relationships ---
% No enrichment needed. As a Mountain (physical limit), this constraint does
% not have beneficiaries or victims in the structural sense.

/* ==========================================================================
   3. INDEXED CLASSIFICATIONS (P, T, E, S)
   ========================================================================== */

% The magnetic field is an immutable feature of planetary existence. No exit from its constraints — the field's topology, reversal dynamics, and particle trapping properties are fixed properties of magnetohydrodynamic action in the liquid outer core.
constraint_indexing:constraint_classification(earth_magnetic_field_generation, mountain,
    context(agent_power(powerless),
            time_horizon(civilizational),
            exit_options(trapped),
            spatial_scope(global))).

% Power grid operators, satellite systems, and navigation infrastructure face immutable constraints from magnetic field dynamics: declination drift, secular variation, auroral storm coupling. These are structural limits to predictability and control, not coordination problems.
constraint_indexing:constraint_classification(earth_magnetic_field_generation, mountain,
    context(agent_power(organized),
            time_horizon(generational),
            exit_options(constrained),
            spatial_scope(global))).

% From first principles: the Earth's magnetic field is generated by convective dynamo action in the liquid outer core — self-sustaining electromagnetic induction governed by the magnetohydrodynamic equations. The field emerges necessarily from planetary rotation, core composition, and thermal gradients. No alternative mechanism; no degrees of freedom for modification.
constraint_indexing:constraint_classification(earth_magnetic_field_generation, mountain,
    context(agent_power(analytical),
            time_horizon(civilizational),
            exit_options(analytical),
            spatial_scope(universal))).

/* ==========================================================================
   4. VALIDATION TESTS
   ========================================================================== */

:- begin_tests(earth_magnetic_field_generation_tests).

test(invariance_check) :-
    % Verify that as a Mountain, the classification is uniform across perspectives.
    constraint_indexing:constraint_classification(earth_magnetic_field_generation, TypeTarget, context(agent_power(powerless), _, _, _)),
    constraint_indexing:constraint_classification(earth_magnetic_field_generation, TypeBeneficiary, context(agent_power(institutional), _, _, _)),
    TypeTarget == TypeBeneficiary,
    TypeTarget == mountain.

test(mountain_threshold_validation) :-
    config:param(extractiveness_metric_name, ExtMetricName),
    narrative_ontology:constraint_metric(earth_magnetic_field_generation, ExtMetricName, E),
    domain_priors:suppression_score(earth_magnetic_field_generation, S),
    E =< 0.25,
    S =< 0.05.

test(nl_profile_validation) :-
    domain_priors:emerges_naturally(earth_magnetic_field_generation),
    narrative_ontology:constraint_metric(earth_magnetic_field_generation, accessibility_collapse, AC),
    narrative_ontology:constraint_metric(earth_magnetic_field_generation, resistance, R),
    AC >= 0.85,
    R =< 0.15.

:- end_tests(earth_magnetic_field_generation_tests).

/* ==========================================================================
   5. GENERATIVE COMMENTARY
   ========================================================================== */

/**
 * LOGIC RATIONALE:
 *   Extractiveness (0.08): Minimal. The constraint imposes no extraction — it is not that some agents benefit and others lose. Rather, the field is a shared physical substrate that all agents inhabit equally. The small non-zero extractiveness reflects only that the constraint is not a pure information standard (which would have ε ≈ 0.01). The MHD dynamo requires specific planetary conditions (liquid outer core, rotation, heat flux) that are not infinitely generalizable — in principle, planets without liquid cores have no dipole field. Suppression (0.02): Negligible. There are no alternative mechanisms being suppressed; suppression presupposes a choice between mechanisms. The dynamo is the only mechanism that produces planetary magnetic fields at observed strengths. Theater ratio (0.15): Very low. The field generation mechanism is fundamentally actual — not performative. Measurement and modeling of the dynamo are observationally rigorous; there is no ritual or theatrical element to the constraint itself. The small non-zero value reflects only that our observational access to the core is indirect (seismic, magnetic satellite data, paleomagnetic inference).
 *
 * PERSPECTIVAL GAP:
 *   No perspectival gap exists. All three perspectives produce Mountain classification with identical reasoning. The planetary inhabitant, technological systems manager, and analytical observer agree on the constraint's immutability because it follows necessarily from physical law. The constraint is invariant across all indexical positions — no agent sees a different type. This uniform classification is the diagnostic signature of a true natural law constraint.
 *
 * DIRECTIONALITY LOGIC:
 *   Directionality (d) is not applicable to mountain constraints. Natural law constraints have no beneficiaries or victims — the field is a shared substrate. The sigmoid f(d) and the full chi formula do not apply. The constraint's classification depends only on the base metrics (ε, suppression) meeting the mountain thresholds; it does not depend on beneficiary/victim relationships or agent power levels.
 *
 * MANDATROPHY ANALYSIS:
 *   This constraint resolves the mandatrophy trivially: all perspectives agree. There is no tension between coordination and extraction, no false natural law to unmask, no hidden institutional arrangement masquerading as physics. The constraint is genuinely a mountain — it emerges necessarily from physical law, has minimal extractiveness, has no suppression mechanism, and exhibits zero degrees of freedom. The uniform classification across all observables and perspectives confirms that the underlying ε is stable: no alternative measurement methodology would produce a different ε value.
 */

/* ==========================================================================
   6. OMEGA VARIABLES (Ω) - IRREDUCIBLE UNCERTAINTIES
   ========================================================================== */

omega_variable(
    dynamo_mechanism_closure,
    'Is the MHD dynamo mechanism fully determined by observable core parameters (composition, viscosity, rotation rate, thermal gradient), or are there unobserved degrees of freedom in the turbulent flow regime?',
    'Global magnetohydrodynamic simulations with increasing resolution and observational constraints from seismic tomography, paleomagnetic records, and magnetic satellite measurements; comparison of predicted vs observed field geometry and reversal statistics',
    'If fully determined: mountain classification confirmed at all scales. If unobserved degrees of freedom exist: reclassify as Rope at biographical/local scales (some agents have agency in influencing local magnetic environment via current loops or plasma confinement).',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(dynamo_mechanism_closure, empirical, 'Whether core dynamo is fully constrained by observable parameters').

omega_variable(
    reversal_predictability,
    'Are magnetic reversals (dipole field inversion on ~200,000-1,000,000 year timescales) deterministic chaos or genuinely stochastic emergent events with irreducible uncertainty?',
    'Long-duration paleomagnetic records showing field behavior across multiple reversal cycles; dynamical systems analysis of MHD reversal mechanisms; computational models testing sensitivity to initial conditions',
    'If deterministic chaos: reversals remain immutable but in principle predictable with infinite precision — mountain classification holds. If irreducibly stochastic: reversals are contingent events with no determination — mountain status weakens, approaches Rope (agents with knowledge can make probabilistic predictions).',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(reversal_predictability, empirical, 'Whether magnetic reversals are deterministic or stochastic').

omega_variable(
    anthropogenic_magnetic_modification,
    'Can large-scale human activities (global power distribution, industrial current loops, atmospheric nuclear detonations) modify the dynamo field generation mechanism, or is the anthropogenic perturbation negligible compared to core-scale driving forces?',
    'Magnetospheric measurement campaigns during periods of maximum global power transmission; modeling of current-loop coupling to magnetohydrodynamic turbulence in the core; comparison of field anomalies vs grid configuration changes',
    'If modification is possible at >1% of baseline field: reclassify from mountain to Tangled Rope or Scaffold (anthropogenic activity becomes a coordination/extraction constraint overlaid on the natural dynamo). If modification is <0.01% of baseline: mountain classification confirmed — anthropogenic effects are noise.',
    confidence_without_resolution(high)
).

narrative_ontology:omega_variable(anthropogenic_magnetic_modification, empirical, 'Whether anthropogenic activities can modify the dynamo mechanism').

omega_variable(
    multi_dipole_stability,
    'Is the current dipole-dominated magnetic configuration a stable attractor of the dynamo equations, or a metastable state that could transition to multi-dipole or quadrupole configurations under different core conditions?',
    'Paleomagnetic evidence for past field configurations (including reversal asymmetries and non-dipole components); dynamical systems analysis of MHD attractor landscape; comparison of Earth''s field to Jupiter''s and Saturn''s field multiplicity',
    'If dipole is stable attractor: current field configuration is immutable — mountain confirmed. If multi-dipole is possible: classify as Rope at civilizational scale (alternative stable states exist; which one is expressed depends on core initial conditions, not on current external forcing).',
    confidence_without_resolution(medium)
).

narrative_ontology:omega_variable(multi_dipole_stability, empirical, 'Whether dipole configuration is uniquely stable or metastable').


/* ==========================================================================
   7. INTEGRATION HOOKS
   ========================================================================== */

narrative_ontology:interval(earth_magnetic_field_generation, 0, 5000).

/* ==========================================================================
   8. TEMPORAL MEASUREMENTS (LIFECYCLE DRIFT DATA)
   ========================================================================== */

% Theater ratio over time
narrative_ontology:measurement(emfg_tr_t0, earth_magnetic_field_generation, theater_ratio, 0, 0.1).
narrative_ontology:measurement(emfg_tr_t2500, earth_magnetic_field_generation, theater_ratio, 2500, 0.14).
narrative_ontology:measurement(emfg_tr_t5000, earth_magnetic_field_generation, theater_ratio, 5000, 0.15).

% Extraction over time
narrative_ontology:measurement(emfg_be_t0, earth_magnetic_field_generation, base_extractiveness, 0, 0.06).
narrative_ontology:measurement(emfg_be_t2500, earth_magnetic_field_generation, base_extractiveness, 2500, 0.08).
narrative_ontology:measurement(emfg_be_t5000, earth_magnetic_field_generation, base_extractiveness, 5000, 0.08).


/* ==========================================================================
   9. BOLTZMANN & NETWORK DATA
   ========================================================================== */

narrative_ontology:coordination_type(earth_magnetic_field_generation, global_infrastructure).
narrative_ontology:affects_constraint(earth_magnetic_field_generation, magnetospheric_particle_trapping).
narrative_ontology:affects_constraint(earth_magnetic_field_generation, auroral_energy_dissipation).
narrative_ontology:affects_constraint(earth_magnetic_field_generation, magnetostratigraphy_dating).

% DUAL FORMULATION NOTE:
% The Earth's magnetic field generation is a foundational natural law constraint. Downstream constraints (particle trapping, auroral dynamics, paleomagnetic dating) depend structurally on this field's existence and properties, but each downstream constraint has its own ε value reflecting domain-specific mechanisms and observable contingencies.

/* ==========================================================================
   10. DIRECTIONALITY OVERRIDES (v6.0, OPTIONAL)
   ========================================================================== */

/* ==========================================================================
   END OF CONSTRAINT STORY
   ========================================================================== */
